### ISSUE TITLE
JIRA [IMG-1254] Consider new types of metrics

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#103]
From Lee:  It would be kind of fun to look into some way to build a feature lexicon that was based on actual experimental images, similar to my PCA pixel-based classifier attempt. Vebjorn&#39;s visitor who gave the unsupervised machine learning talk hinted about a size-invariant shape feature set. There are probably many other ideas out there which might yield much more informative and targeted feature measurements.<br/>

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1254
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
