### ISSUE TITLE
Resubmitting "Failure" cluster jobs does not update their status in ViewBatch.py 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1035]
In Batch # 4203 (http://imagingweb.broadinstitute.org/batchprofiler/cgi-bin/FileUI/CellProfiler/BatchProfiler/ViewBatch.py?batch_id=4203) I resubmitted a failed job by clicking the Resubmit button here:
![image](https://f.cloud.github.com/assets/1225595/2041490/bba16112-89c5-11e3-81de-9305b8143d3d.png)
and the job resubmits successfully, as shown by bjobs:
```
$ bjobs 5711280
JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
5711280 imagewe PEND  bweek      imagingweb              *_to_78050 Jan 30 10:40
```
however ViewBatch does not update the status from Failure to PEND.

I think the status Batch_X_to_X_DONE.mat file just needs to be deleted on resubmission.

**Comment by LeeKamentsky** [comment]
Fixed by new batchprofiler
