### ISSUE TITLE
Alert user during analysis run that they can reduce # of workers if needed

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1081]
A user reported that CP slowed her computer to a crawl during an analysis run, partially due to the workers hogging the CPUs.

Similar to #761, we can let the user know in the status/progress panel that if the analysis run is bringing things down, they can remedy it by lowering the # of workers in Preferences.

**Comment by AnneCarpenter** [comment]
The addition of the number of workers in the status bar is a nice touch - I agree it's not likely sufficient for most of us to realize that we can adjust the maximum number, but I 100% agree that there is no obvious graceful way to convey to users that this is adjustable and will affect their computer's performance overall. Given this is not terribly common and people can hopefully google their way to an answer, I'm closing as won't fix.
