### ISSUE TITLE
Plugins directory paths are not set consistently during install

### ISSUE THREAD

**Issue by nickholway** [CellProfiler/CellProfiler#1103]
The paths for plugins (both CellProfiler and Imagej) are set to the user who install the software and not the current user. The paths for default input and output are both set properly (see screenshot with obfuscated usernames). 

![image](https://cloud.githubusercontent.com/assets/3875607/2655300/0a7fccac-bfe4-11e3-9952-e3db7a535344.png)

This is with CellProfiler 2.1 on Windows (rev 0c7fb94).

**Comment by AnneCarpenter** [comment]
Plugins are not very commonly used so given our limited bandwidth, I will close this but mark it for future consideration.
