### ISSUE TITLE
Document ExportToSpreadsheet saves Experiment.csv to default output folder

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1110]
If ExportToSpreadsheet saves to a subfolder of the Default Output folder, and that folder uses Metadata tags, then the Experiment.csv is saved to the DOF, and not the specified subfolder.  All the other CSV files are put in the correct folder.

(Note: I used the Welcome Screen Fly images to test this.)

Attachments:
http://cellprofiler.org/issues/uploaded/cBQc5K/project_Experiment_CSV.cpproj

**Comment by AnneCarpenter** [comment]
Given that at least one reputable person in the world likes the current behavior, let's just document the behavior in the help and be done with it.

**Comment by AnneCarpenter** [comment]
(Could I ask @dlogan or @braymp to do this, if either of you still has an understanding of the issue?)

**Comment by dlogan** [comment]
Yes, I can add a little Help clarification for this soon.

**Comment by AnneCarpenter** [comment]
Hey @dlogan if you can just type the correct text in a comment I'm happy to put it in properly as a pull request.

**Comment by AnneCarpenter** [comment]
I will do this (as best I can)

**Comment by AnneCarpenter** [comment]
Strangely, I don't seem to have the power to close this issue @mcquin

**Comment by mcquin** [comment]
Closed #3232

**Comment by dlogan** [comment]
sorry @AnneCarpenter I lost track of this.  Your text edits read fine to me.
