### ISSUE TITLE
JIRA [IMG-1182] Show/hide module settings, to simplify pipelines

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#113]
The IADs have requested the ability to show/hide settings in each module, and save the show/hide status in the pipeline.  This way, they can create a pipeline for someone, and then hide most of the settings that the user does not need to adjust to create a simpler view.  This gets us closer to the long-term goal of making application-specific wizards with fewer user-adjustable parameters.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1182
Assignee: leek

**Comment by braymp** [comment]
From the old roadmap:

This enables creating simple pipelines with only a few visible settings (with the remaining advanced settings still readily available).This is useful for giving pipelines to users in which only a few module settings need to be changed for a new assay, so we can hide the settings that are not relevant.

We agreed to a format in which successive module settings can be collapsed into one line by pressing either a "-" or open eyeball to the right, or a down-facing triangle on the left ; pressing this button would change the icon to a "+", a closed eyeball, or a right-facing triangle respectively. We were undecided as to whether short-text indicating what the collapsed settings were should be provided as well (probably located on the same line).

**Comment by AnneCarpenter** [comment]
@0x00B1
