### ISSUE TITLE
GrayToColor Stack saving problem

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1131]
There is a difference in how 2- and 3-channel images are saved when GrayToColor >Stacks are saved with SaveImages.  When the attached project is run the two images appear below when viewed in Fiji:
http://cl.ly/image/1K1N3m1O152B

The 2-channel image appears proper (I think) as 2-channel tiff with the two  slices having different channel info.  The 3-channel tiff displays in Fiji as 3 slices however each slice has the same RGB image. 

Attachments:
http://cellprofiler.org/issues/uploaded/CeCQiI/test_project.cpproj

**Comment by AnneCarpenter** [comment]
Probably not affecting a huge number of users, nevertheless marking for future consideration.
