### ISSUE TITLE
Add module number to main GUI

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1141]
This [Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=17&t=3845&p=11217&sid=642abc0e82b1143f1c9c260249833d3b#p11217) has very long pipelines and notes that while the figure windows are numbered, the modules in the pipeline panel are not.  Can we add the module number in the main GUI somewhere?  These were my thoughts on where to put it:
I would hesitate to use up valuable pipeline panel real estate for this.
(1) Perhaps we could add it either as a popup when you hover over a module (though that could be annoying)
(2) Possibly within the Settings panel once you click the module? 
(3) Or maybe a Preference setting to toggle displaying it?

**Comment by LeeKamentsky** [comment]
I've added the module name and number to the module settings group box. I also added a menu command, Edit->Go to Module. It not only lets you go to a module by number, it makes it possible to go to a module without using the mouse (accessibility).

**Comment by dlogan** [comment]
Hmm, I don't see this in my dev version.  Did it get committed?

**Comment by LeeKamentsky** [comment]
sorry, forgot to commit
