### ISSUE TITLE
Failure to run project file when headless

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1147]
Running the attached project (which opens correctly with images if using just -p and -c) using -p, -c and -r yields the following error:

```
CP-JAVA 15:44:11.643 [Thread-0] WARN  o.c.imageset.ChannelFilter - Empty image s
et list: no images passed the filtering criteria.
```

Might be related to #1072?

Attachments:
http://cellprofiler.org/issues/uploaded/fle4qO/issue.cpproj

**Comment by cgershman** [comment]
This appears closed, but I am receiving the same error the current master branch. Any suggestions?

**Comment by LeeKamentsky** [comment]
There are a lot of reasons for this. What method are you using to specify image locations? It's usually a problem with how you've set up to do that. If you were using a project file, the image locations would be specified inside, but with a pipeline, many things can go wrong.

**Comment by cgershman** [comment]
Here is an example of the command line:
python CellProfiler.py -c -r -i c:\InputImages -o c:\Ou
tputImages -p c:\Pipelines\CounterPipeline.cppipe

**Comment by LeeKamentsky** [comment]
Could you post the pipeline? (or send to me directly) Does it use the input modules?

**Comment by cgershman** [comment]
Seems I can only post images. Yes, it uses the input modules. I left the image set empty, thinking it would look for images in the specified input directory.

**Comment by LeeKamentsky** [comment]
Nope - it doesn't read from the input directory. You might want to use the LoadImages module, in spite of all the warnings. It will do what you want. In 2.1.2, you'll be able to specify the files for the input modules on the command-line (--file-list=myfilelist.txt). Perhaps you're suggesting a worthwhile feature - that you specify a directory on the command line in batch mode and CellProfiler uses the files in that directory for input to the input modules.

**Comment by cgershman** [comment]
Thank you, LoadImages worked perfectly.
