### ISSUE TITLE
IdentifyPrimaryObjects Laplacian of Gaussian artifacts

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1156]
Using IdentifyPrimaryObjects with the Laplacian of Gaussian (LoG) can cause odd artifacts in some segmentations.  See the attached screenshot for a couple examples.

To replicate, load the project here (I believe it is self-contained).  The artifacts always seem to be diagonal invaginations which don't necessarily seem to match any intensity dip in the input image.

Attachments:
http://cellprofiler.org/issues/uploaded/8GnTRx/LoG_issue.cpproj
http://cellprofiler.org/issues/uploaded/i-0vm1/ScreenShot2014-07-01at9.38.24AM.png

**Comment by AnneCarpenter** [comment]
Given we have many functional methods for identifying objects, I don't think we need to go to heroics to save LoG or work around its limitations. I was going to go adjust the help for the module but can't find anything about LoG in IdentifyPrimaryObjects' help... where was this setting, @dlogan ? The project file attachments are no longer available so I couldn't check.

**Comment by braymp** [comment]
Similar artifacts occur with the Shape declumping method at times; I think the reasons are related. If I can find an example, I'll open a new issue.

**Comment by dlogan** [comment]
Sorry, just saw this @AnneCarpenter...
To see Laplacian of Gaussian (LoG), load up the Welcome Screen pipeline, and look under IdentifyPrimaryObjects, in the setting "Method to distinguish clumped objects".  
![image](https://cloud.githubusercontent.com/assets/1225595/19322481/40711d18-9087-11e6-8e16-4d385fc53cc1.png)
If you click the "?" next to that setting, there is some Help existing there.
