### ISSUE TITLE
Add a local maxima function to Morph

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1158]
Often you'd like a binary image where the local maxima in a grayscale were identified - for instance, the Matlab IdentifyPrimLoG (see issue #1156) could be realized using EnhanceOrSuppressFeatures + LoG followed by Morph with this operation.(maybe + shrink).

The code is:

   dilated = grayscale_dilation(image, strel)
   return dilation == image

**Comment by 0x00b1** [comment]
“Morph” will eventually be supplanted by modular morphological modules and a “maxima and minima” module is forthcoming.

**Comment by AnneCarpenter** [comment]
Is there an issue for Morph turning into modular morphological modules? I'd like to comment :)
