### ISSUE TITLE
ExportToDatabase: Worker error - "Encoder zip not available"

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1162]
A collaborator is running our Linux 2.1 build and is receiving the error shown below when the pipeline hits ExportToDatabase (sorry, no text, just a screenshot)
![image](https://cloud.githubusercontent.com/assets/1186440/3512168/ac9b50c4-06b6-11e4-9542-ae75cb76046f.png)
Looking at the code, it seems the problem is with how the thumbnail blobs are being written.  Also, the terminal output shows that PIL is being used when the error occurs. I thought we did away with PIL...? 

FYI: StackOverflow pointer:http://stackoverflow.com/questions/3544155/about-the-pil-error-ioerror-decoder-zip-not-available

**Comment by AnneCarpenter** [comment]
@braymp: Do you remember which collaborator this is, and if so can you check with them as to whether they can reproduce in current version of CP?

**Comment by braymp** [comment]
Appears to be a duplicate of #1228.

**Comment by braymp** [comment]
The collaborator has moved on to another position, so I doubt I'll get useful info from him at this point.

**Comment by AnneCarpenter** [comment]
Ok, buh-bye to this issue.
