### ISSUE TITLE
Inform user which image is active for interactive modules

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1167]
From http://cellprofiler.org/forum/viewtopic.php?f=14&t=3917

<blockquote>
I noticed as I was running the pipeline that when the Crop and Rotate windows are open, there is no indicator as to which file is being processed/which cycle is currently being run (as opposed to the Align window or the window that pops up after I have cropped an image). Is there are way for this to be displayed in the Crop/Rotate windows as well? The reason is that CP does not seem to process the images in a particular order (Cycle 1 then 4 then 2) and I need to keep track of which image I am on so I can rotate it appropriately.
</blockquote>

It might be useful to put the filename in the title bar or some such for these modules.

Affected modules:
- Crop
- DefineGrid
- FlipAndRotate
- EditObjectsManually
- StraightenWorms
- IdentifyObjectsManually

**Comment by braymp** [comment]
@AnneCarpenter, @mrohban brought this issue up again recently.

**Comment by LeeKamentsky** [comment]
Seems like a bug to me and an easy one to fix. So let's leave it open.

**Comment by jhung0** [comment]
I tried with Crop and FlipAndRotate, and it does have the cycle information.

**Comment by mcquin** [comment]
@jhung0 Can you please also verify the behavior of DefineGrid, EditObjectsManually, StraightenWorms, and IdentifyObjectsManually

**Comment by AnneCarpenter** [comment]
I've no idea, but it's possible that this problem went away when CP stopped using multiple threads for processing. Just a thought.
