### ISSUE TITLE
JIRA [IMG-1171] Chord measurement

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#117]
Lee (and other, but mostly Lee),<br/><br/>The GE IN Cell data I&#39;m working with has a measure for shapes called<br/>Chord Ratio, which is defined as&quot;shortest chord to longest chord<br/>ratio, with both chords passing through the shape&#39;s center of<br/>gravity&quot;.  From what I can tell, it&#39;s computed from the mask, not from<br/>the ellipse fit.  It seems to be useful in particular for finding<br/>segmentation artifacts.<br/><br/>Any thoughts on how to do this in parallel for a label matrix?<br/><br/>...<br/><br/>Ray<br/>

Original reporter: thouis
Jira link: https://jira.broadinstitute.org/browse/IMG-1171
Fix version: next
Assignee: leek

**Comment from leek on Thu, 7 Oct 2010 10:02:22 -0400:**
The naive algorithm is to draw a line from each point on the outline through the center and off to infinity in the other direction, noting the last point in the line that is within the mask - I have code to parellelize line drawing.<br/><br/>Another algorithm would involve measuring the angle of every point on the outline to the center and then to vertical. Order points by angle and match each point with the one that has the closest match to angle + 180. Obvious mechanisms to parallelize calculation of the angles, obvious O(N*N) parallelizable algorithm for finding best match among N outline points, tricky way to parallelize a sort algorithm that operates in O(log(N)) and is that worthwhile for&lt; 100 outline points / cell.

**Comment by dlogan** [comment]
Closing now, for future consideration.
