### ISSUE TITLE
Error during HDF5 temp file writing

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1177]
A user reports an error during HDF5 temp file writing:
![image](https://cloud.githubusercontent.com/assets/1186440/3707667/f9edb0e0-1437-11e4-850d-ce38c6bd3613.png)

I'm not sure it's a bug; could it be something as simple as some sort of out-of-space error?

From this forum post: http://cellprofiler.org/forum/viewtopic.php?f=16&t=3934&p=11641#p11604

**Comment by LeeKamentsky** [comment]
I'm closing this - it's stale.
