### ISSUE TITLE
JIRA [IMG-1170] Consider new measurements to add to CP

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#118]
We have been gathering ideas for new groups of measurements to enable CP to make, here:<br/><br/><a href="http://dev.broadinstitute.org/imaging/privatewiki/index.php/2010_04_15_Making_CellProfiler_measure_new_features_%28Imaging_Platform%29">http://dev.broadinstitute.org/imaging/privatewiki/index.php/2010_04_15_Making_CellProfiler_measure_new_features_%28Imaging_Platform%29</a>

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1170
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
