### ISSUE TITLE
Metadata module: Regexp for metadata matching

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1182]
Not sure how doable this is, but it would be nice to generalize the  metadata rule matching much like the ones for File and Directory. 

For example, the current matcher```[Metadata][Does][Have C matching][0]``` could become:
```[Metadata][Does][Have C][Contain regular expression][ [0-9] ]``` to get only certain slices.

From this forum post: http://cellprofiler.org/forum/viewtopic.php?f=14&t=3948

**Comment by AnneCarpenter** [comment]
Closing but marking for future consideration.
