### ISSUE TITLE
IdentifyPrimaryObjects: Objects with holes touching the image edge don't get filled in

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1187]
Run the attached pipeline on the attached image. The object on the image edge is not filled in, despite module settings.

Attachments:
http://cellprofiler.org/issues/uploaded/g-Ds3e/issue.cppipe
http://cellprofiler.org/issues/uploaded/6q8Hau/Untitled.png

**Comment by AnneCarpenter** [comment]
Based on my skim, it sounds like this is not something desperately needed and/or there are workarounds.
