### ISSUE TITLE
IdentifyWorms: output worm length as a measurement

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1190]
Add a better length measurement, based on the splines. 

*Communicated a lot with a PostDoc from UCLA who wants to use the WormToolbox to measure worm length. Currently, the only way to get a proper length measurement is to use the output from 'StraightenWorms', which is a bit over-doing it. We do create a nice non-branched skeleton already at the untangling step, and this would be perfect for extracting shape measurements. I'm considering putting together a special WormMeasurements module (including length, curvature, a few shape measures, mean, max and std of width etc) to make things easier for the users. Let me know if you have thoughts! 
Carolina

**Comment by AnneCarpenter** [comment]
Worthy task, closing but marking for future consideration.
