### ISSUE TITLE
For Broadies, CreateBatchFiles should allow better integration with BatchProfiler

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1191]
In BatchProfiler (NewBatch.py), it is annoying to have to populate the "Data output directory: " field to point to the output h5 file.  Clicking "Browse..." is slow, and anyway, CP knows where the output file is.  So I resort to manually copying the output directory from the CP GUI and pasting into the NewBatch.py web form, but the paths are not Unix-y.  So more typing.  

I would love to have a button on the CreateBatchFiles final dialog window to have a button labeled something like "Prepare Batch" that launches the proper NewBatch.py page (no hunting for the proper version!  FileUI, etc) with the Data Output Directory pre-populated from the root paths in CreateBatchFiles and the location of the h5 file.  This button would only be visible from machines within Broad (via IP address I suppose) since it is a Broad-specific feature.

**Comment by LeeKamentsky** [comment]
If you check the setting labeled "Launch BatchProfiler" and hit "Analyze", CP should start a browser at the URL, http://imageweb/batchprofiler/NewBatch.py with the directory for Batch_data.h5 preloaded. You can set the URL base in preferences.

Currently, the Broad's imageweb redirects the URL to the right location.

**Comment by dlogan** [comment]
This is my favorite button in CP this year.

**Comment by LeeKamentsky** [comment]
If you want it as a button in addition to the checkbox, I can do that too. Try it out and tell me if the workflow is better one way or the other.

**Comment by dlogan** [comment]
It's a radio button now. I will test functionality later, but in any case,
I like it.

David
--
Sent from my phone.
Please excuse terse tappings.

**Comment by braymp** [comment]
I think it would be better as a button on the msg dialog providing the location of the batch file.
