### ISSUE TITLE
ExportToDatabase: AUTO_INCREMENT error in CPA db creation

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1194]
When ExporttoDatabase creates the experiment table, the AUTO_INCREMENT field is used if the db is MySQL or MySQL/CSV. However, if the MySQL/CSV option is used, and the resulting .SQL file is referenced in a properties field for use in CPA, the SQLite db creation fails since AUTO_INCREMENT is not recognized.

I'm not sure of a way around this other than removing AUTO_INCREMENT?

**Comment by AnneCarpenter** [comment]
Needs a more precise description if anything is going to happen. Marking as future consideration until then.

**Comment by braymp** [comment]
Some more details (since I'm still running afoul of this even now); I'm attaching an example .SQL file produced by ExportToDB when MySQL/CSV is chosen.
[SQL_SETUP.SQL.txt](https://github.com/CellProfiler/CellProfiler/files/452445/SQL_SETUP.SQL.txt)

Specifically, these lines are the concern:
```
CREATE TABLE IF NOT EXISTS Experiment (
    experiment_id integer primary key AUTO_INCREMENT,
    name text);

CREATE TABLE IF NOT EXISTS Experiment_Properties (
    experiment_id integer not null,
    object_name text not null,
    field text not null,
    value longtext,
    constraint Experiment_Properties_pk primary key 
    (experiment_id, object_name(200), field(200)));
```
The SQLite db creation fails due to the <code>AUTO_INCREMENT</code> and the <code>object_name(200), field(200)</code> portions. 

My suggestion is as above: leave out the AUTOINCREMENT in Experiment and the Experiment_Properties constraint if MySQL/CSV is chosen.

**Comment by DavidStirling** [comment]
MySQL/CSV mode has now been removed in favour of just using ExportToSpreadsheet, so I think we can close this now. The longer term goal is currently to recreate export functionality as a single module for both sheets and databases, such a redesign should provide a better solution.
