### ISSUE TITLE
TrackObjects: add a TrackMate tracking option

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1197]
We can use trackmate (http://fiji.sc/TrackMate) programatically to track objects via its API. I think the best idea might be to perform the analysis post_group, loading the positions and features into a fiji.plugin.trackmate.Spot and then run it.

TrackMate is under heavy development and is gaining a lot of traction, so it makes some sense to leverage that and possibly even to do future tracking development in their framework. However, it looks like they use Jaqaman as well; that may be the most sophisticated method that comes with the distribution, so there may not be much to gain and we would lose our mitosis improvements.

**Comment by AnneCarpenter** [comment]
I'm keeping this open, although clarifying that the big-picture issue is to add new tracking options to CellProfiler, whether by this route or via code from ISBI Grand Challenges.

**Comment by mcquin** [comment]
We have no plans to include this.
