### ISSUE TITLE
Anaconda packages

### ISSUE THREAD

**Issue by ewiger** [CellProfiler/CellProfiler#1201]
Do you think it would be possible to pack CP into a conda repository and placed on https://binstar.org/ service for Mac and Linux?

It is quite difficult to handle all the dependencies for CP, e.g. compilation versus wx 2.8 or wx 3.0 is a true pain. maybe this could be simplified using binary packaging from conda? It already provides a nice management layout for numpy, scipy, mkl, etc.

**Comment by mcquin** [comment]
Moved to https://github.com/CellProfiler/distribution/issues/7
