### ISSUE TITLE
Workspace viewer: Measurement drop-downs don't update intuitively 

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1221]
* Load the welcome screen pipeline
* Run the pipeline so as as to execute IdentifyPrimaryObjs
* Select Image > Count > Nuclei from the measurement drop-downs 
* Now select "Nuclei" from the top measurement drop-down

I would expect the bottom 2 drop-downs to clear, to indicate to the user that something needs to be selected.

**Comment by 0x00B1** [comment]
Workspace Viewer was removed
