### ISSUE TITLE
Cannot double-click to open project on Mac

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler#1223]
When I double-click on a `.cpproj` file in Finder, CellProfiler starts, but it doesn't load the project. I have to  do File -> Open Project in order to load it.

Official build of CellProfiler 2.1.1 (6c2d896) on MacOS X.

**Comment by AnneCarpenter** [comment]
Can confirm this does not work in CP 2.2.0 (9969f42) either (Mac OS 10.10.5). Dragging the project onto CP's pipeline window does work.  It's a nicety, though, so moving to future consideration.
