### ISSUE TITLE
JIRA [IMG-1139] DefineGrid: Accommodate grid rotation

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#124]
Hopefully, the user lines up the dish/plate with the image coordinate axes, but that&#39;s not always the case. It would be nice if the grid was able to accommodate some amount of rotation in the control points.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1139
Fix version: future
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
