### ISSUE TITLE
Process large images in tiles

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1244]
Process large images by breaking them into tiles:

* Allow the user to specify a tile size and border size
* For each image set, determine the offsets and sizes needed to fetch tiles of the appropriate size and border
* Process each of the tiles in-turn, only loading the portions of the image within the tile
* Only use objects whose centers are not in the border region. Add tile offsets to any location measurement. Handle renumbering of objects to give a coherent view of objects from all tiles within the image set.
* Save images in tiles too

**Comment by dlogan** [comment]
Related to #198
