### ISSUE TITLE
Grayscale-weighted distance transform

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1249]
From @dlogan : 
The following paper describes a grayscale-weighted distance transform that helps highlight neurites.

Xiao, Hang, and Hanchuan Peng. “APP2: Automatic Tracing of 3D Neuron Morphology Based on Hierarchical Pruning of a Gray-Weighted Image Distance-Tree.” Bioinformatics 29, no. 11 (June 1, 2013): 1448–54. doi:10.1093/bioinformatics/btt170.

The algorithm:
* compute a conservative background (the pixels that are surely background). The paper suggests the mean intensity value - it could be a quartile too, e.g. 25%.
* compute the distance transform
* the pixels adjacent to background pixels retain their value
* other foreground pixels have a transformed value of their value plus the transformed value of the adjacent pixel closest to the background (i.e. the sum of all pixels along the shortest path to the background). I would do the average of all adjacent pixels at the same distance.

Not so hard to do - maybe 1/2 day including a test. I can see how it would give high weights to the spine of a neurite, even if it were a little foggy. The background method introduces some instability and parameterization - you probably need the full thresholding settings to give the user enough flexibility.

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/centrosome#16

**Comment by cvloc** [comment]
Dear Sir,
Please share the source code of gray weighted distance transform.
Thank you so much.

**Comment by AnneCarpenter** [comment]
We do not have any such code. Please follow this issue for updates: CellProfiler/centrosome#16
We would welcome contributions.
