### ISSUE TITLE
JIRA [IMG-1136] Check into Spotfire - CP integration

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#126]
Original reporter: dlogan
Jira link: https://jira.broadinstitute.org/browse/IMG-1136
  (Original JIRA has attachments.)
Fix version: next
Assignee: klmadden

**Comment from klmadden on Fri, 17 Sep 2010 14:54:56 -0400:**
looked into spotfire. wrote a tutorial. we can either put it on the website, or in the help maybe?

**Comment by dlogan** [comment]
I can't find this tutorial linked on the Interfaces page any more (http://cellprofiler.org/interfaces/).  Does it still exist?  Does anyone know if it is still valid?
@braymp

**Comment by AnneCarpenter** [comment]
Huh. I don't know anything about it, though the text on the interfaces page certainly doesn't imply that a tutorial ought to be there. @N3llz might be able to dig up past linked files for the site (or old versions of the site) to see if there is any mention of Spotfire beyond the little blurb on the interfaces page?

**Comment by dlogan** [comment]
I didn't know about it either.  I was curious and impatient so I found an old one (Thanks Wayback Machine!) by searching [here](https://web.archive.org/web/*/http://cellprofiler.org/interfaces.shtml).

Here's that tutorial at least:
https://web.archive.org/web/20140704153806/http://cellprofiler.org/tutorials/CellProfiler_Spotfire_Integration.pdf

The filename is above in case that helps in finding any newer versions @N3llz (though I doubt it).

**Comment by AnneCarpenter** [comment]
Wow, that is great. I'm pretty certain there would not be a more recent version, so closing this issue and making a new one at the website github, to re-post this file. It's a bit disturbing it was lost so  @N3llz  should ponder whether there is any way to figure out when it was lost (and if anything else was lost at the same era, likely before she arrived).
