### ISSUE TITLE
Run unit tests on the CellProfiler application after it's built

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1260]
We want to prove that the application, not the code base, works, so the CI integration servers should run the unit tests on the app after it's built.

**Comment by LeeKamentsky** [comment]
This is working for Jenkins / Windows and is a tremendous improvement.

**Comment by 0x00B1** [comment]
Is Jenkins publicly available? Have you considered adding Travis support? I started experimenting with this to test [some of the stuff](https://github.com/0x00B1/CellProfiler/tree/features/travis) I’ve been working on.

**Comment by LeeKamentsky** [comment]
Jenkins is open source. I remember looking at Travis and at the time there
was some blocker. Maybe it was our non-standard install?

There are directions for testing on the wiki (look at cpnose.py
<https://github.com/CellProfiler/CellProfiler/blob/master/cpnose.py>)

**Comment by 0x00B1** [comment]
No, no. I meant, is there a publicly available Jenkins installation for CP?

Non-standard install shouldn’t be a problem. You can run an arbitrary shell script.

**Comment by LeeKamentsky** [comment]
Jenkins is behind our firewall. It would not be a bad idea to at least move
the Linux build out into the cloud to make it more visible.

**Comment by 0x00B1** [comment]
Completed
