### ISSUE TITLE
CP usability for large image sets

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1268]
This Forum user is having some trouble with loading large images sets.  These two posts are not bug reports necessarily, however they might warrant some further comments besides my "Use LoadData" comment:
http://www.cellprofiler.org/forum/viewtopic.php?f=16&t=4061&p=12205#p12153

And also this on our Usability Improement suggesiton page:
http://cellprofiler.org/forum/viewtopic.php?f=16&t=1329&sid=cb1f1620e0b32c598ad78bb8fc6659a5&start=15#p12162

**Comment by braymp** [comment]
I imagine that the <code>---java-heap-size</code> would solve this. Closing.
