### ISSUE TITLE
ilastik crashes on close for compiled CP

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1275]
Use ilastik that come bundled with CP 2.1.1. Close the ilastik session and the following Windows error appears after the "stopping worker thread" messages.
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	CellProfiler.exe
  Application Version:	0.0.0.0
  Application Timestamp:	4c7cd184
  Fault Module Name:	opengl32.dll
  Fault Module Version:	6.1.7600.16385
  Fault Module Timestamp:	4a5be02b
  Exception Code:	c0000005
  Exception Offset:	00000000000dd6c4
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	6028
  Additional Information 2:	60286e3ffe50761a992853ac8f0b9394
  Additional Information 3:	fe38
  Additional Information 4:	fe385cddd66e84e33b82b395f8626d7a
```
Since the problem is in opengl32, I assume this is outside of our purview, but I thought I'd mention it anyway.

I save my project at ilastik's prompt on closing, and the project is unaffected, so that's good.

**Comment by LeeKamentsky** [comment]
I think this is fixed with the rebuilt Ilastik. I don't see the error after executing `cellprofiler --ilastik`, selecting the OpenGL mode and then closing the GUI frame window.
