### ISSUE TITLE
JIRA [IMG-1124] Consider additional texture measures

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#128]
It might be useful to check out the attached paper to decide whether any texture measures should be added to CP (Huh, Lee, and Murphy 2009).

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1124
  (Original JIRA has attachments.)
Assignee: leek

**Comment from anne on Fri, 18 Feb 2011 11:02:03 -0500:**
Pablo Hennings Yeomans gave a talk at Carnegie-Mellon that indicated a preference for using local binary patterns (LBP) for texture rather than Haralick measures, in their work on Otitis Media. Perhaps worth investigating.

**Comment by dlogan** [comment]
Closing now, for future consideration.
