### ISSUE TITLE
Add support for MIRAX .mrxs slide format

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1281]
From @braymp to @LeeKamentsky :
<blockquote>
<p>I've been working with MIRAX-format (.mrxs) images for a Janssen project; these are usually used for tissue IHC. Currently, BioFormats doesn't support it (though it's on their to-do: http://www.openmicroscopy.org/community/viewtopic.php?f=13&t=1133). I was wondering if this is something that can be done by us</p>
<p>I've been pointed to OpenSlide as a Python interface (http://openslide.org/api/python/, https://github.com/openslide/openslide/wiki/OpenSlideAndVIPS) but don't know how hard it is to handle. From this (http://lists.andrew.cmu.edu/pipermail/openslide-users/2012-July/000373.html), it sounds like it's insanely difficult, but wanted to get your thoughts first.</p>
</blockquote>

@LeeKamentsky's response:
<blockquote>
<p>I think some of the muck described on the openslide users list doesn't apply to us - the format stores progressively lower magnifications that are increasingly munged. We could just use the pristine lowest magnifications. The user's list gives us a pretty good starting point for writing a reader. If it were me, I would represent the tiles as OME images in order to correctly represent the X/Y position offsets which are slightly different for each. I would rather not correct for artifacts higher up in the pyramid and would rather not try to stitch things together - you could do that sort of thing using a utility program if you wanted.</p>

<p>So long story short, I guess a week of my time, assuming we have some good images, to do something basic that respects the data and that leaves it up to whoever uses the format to handle alignment and similar.</p>
</blockquote>

**Comment by hflynn** [comment]
Dear All,
You may be interested to read OME's latest blog post (http://blog.openmicroscopy.org/file-formats/community/2016/01/06/format-support/) which details the work that has put into this format by the Bio-Formats development team and explains why we have not yet delivered support,
Thanks,
The OME Team
