### ISSUE TITLE
SaveImages: For sequential number option, numbering uses image set number rather than group index

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1283]
If groups are used, the images are numbered by the image set number which results in the numbering not restarting at the beginning of the next group.

I suspect this might be as easy as replacing "image_set_number" with "group_index" in https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/saveimages.py#L823: 
```
padded_num_string = str(measurements.image_set_number).zfill(ndigits)
```

**Comment by AnneCarpenter** [comment]
I'm closing because I agree with Lee that sequential numbers is for casual users. I think it's ok if this doesn't work quite as expected for a likely very tiny subset of users, but happy to be argued otherwise.
