### ISSUE TITLE
Could not load cellprofiler.modules.ilastik_pixel_classification

### ISSUE THREAD

**Issue by alexforencich** [CellProfiler/CellProfiler#1284]
I'm running in to the following error when I try to run a clean cellprofiler install on a centos AWS instance:

    Version: 2014-11-04T15:34:33 2.1.1 / 20141104153433
    Pipeline saved with CellProfiler version 2014012415164
    Could not load cellprofiler.modules.ilastik_pixel_classification
    Traceback (most recent call last):
      File "/usr/cellprofiler/src/CellProfiler/cellprofiler/modules/__init__.py", line 301, in add_module
        m = __import__(mod, globals(), locals(), ['__all__'], 0)
    ImportError: No module named ilastik_pixel_classification
    could not load these modules: cellprofiler.modules.ilastik_pixel_classification

**Comment by braymp** [comment]
Fixed by cbe4c89f5235b383533d5fd34e7edefcc7779cf4
