### ISSUE TITLE
Weirdness double-clicking a new project to load into old CP

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1291]
Do the following:
* Try loading a newer project (e.g., built from source) in an older version of CP (e.g., release version) by dbl-clicking on it in Explorer.
* At the warning prompt, click 'Cancel'.

CP still opens, despite the cancel request, and it looks as below:
![image](https://cloud.githubusercontent.com/assets/1186440/5616426/4c29a3da-94d2-11e4-8b22-651f6f9b7363.png)

The UI looks fine if dbl-clicking a new pipeline, but the cancel prompt is still ignored,

**Comment by LeeKamentsky** [comment]
OK, not ideal, but here's the behavior:
* Double-click to start CellProfiler - just close silently after user hits cancel (as would be expected)
* Open a too-new project file or pipeline from the UI - clear the pipeline if the user hits cancel

The old pipeline has been demolished before the load starts, and lots of things are in an intermediate state until a new pipeline is loaded (e.g. the module list on the left still shows the old pipeline), so clearing the pipeline gets CellProfiler to a stable state, but might not be what the user would like best.
