### ISSUE TITLE
TrackObjects: Error in LinkType value

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1292]
Using TrackObjects after 49bd1a0b6b88db45ac1d756abc5f31b235067c6b:

Running the attached project file on the referenced images produces a single track consisting of one object (as it should). However, the LinkType field assumes values of 0, 1 or 4. 

A value of 4, according to the help, means the object was linked to a parent in a frame prior to the previous frame (a gap). However, there are no temporal gaps in the object track. The expected LinkValue value for all objects should be 0 or 1.

Attachments:
http://cellprofiler.org/issues/uploaded/ttALB2/project.cpproj

**Comment by braymp** [comment]
An associated SQLite db can be found here: \\iodine\imaging_docs\People\Mark\github\1292

**Comment by LeeKamentsky** [comment]
There are eight gaps during phase 1 (situations where the object in the following frame is not connected to the one in the prior). These are fixed during phase 2 using the gap model and are therefore assigned a 4. Mark and I agreed that, although there's no gap being bridged, it's useful to mark it as fixed during phase 2.
