### ISSUE TITLE
ExportToDatabase / ExportToSpreadsheet FlagImage removes columns completely

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1293]
For ExportToSpreadsheet and ExportToDatabase in SQL/CSV mode, it's possible for all image sets to be flagged and skipped by FlagImages. In this case, no values will be recorded downstream of the skip and the export modules will not have the headers for those measurements despite their being reported by get_measurement_columns.

The request is to make sure the user can count on a standardized number of columns (with NaN values for the missing values) even if all image sets are skipped.

**Comment by braymp** [comment]
I thought if FlagImages did the skip prior to measurements being taken for an object, there would be no row at all in the per-object, rather than just NULLs? If so, I would imagine that the table would only have headers and nothing else...

**Comment by LeeKamentsky** [comment]
It's a little screwy for MySQL/CSV and exporttospreadsheet since both of
those are calculated in post_run() instead of being skipped like everything
else in run(). So the partial measurements are there. Probably why we don't
care - we don't use either much.
