### ISSUE TITLE
Integrate CP-CHARM approach into production version of CP

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#1295]
Virginie Uhlmann finished reproducing the essence of WND-CHARM and validating it. 
https://github.com/CellProfiler/CellProfiler/issues/155

In so doing she created some new modules (which will soon be hosted at Github):

- calculatehistograms, which does what its name says
- moments, which calculates the first to fourth order moment of an input image
- a modified version of measuretexture that includes the so-called "Tamura textures"
- transform, which allows computing the Fourier, Haar or Chebyshev transform of an input image - to do so, I had to make some modifications to cpmath.filter

These need to be cleaned up and incorporated into production version CP. Which includes the following subtasks:
1. Decide which should remain as separate, new modules and which should be adaptations to existing modules. Anne votes that most of these be optional measurements/additional algorithms in existing modules because they seem to fit nicely. New modules could be given their own category, but we need to think carefully about the balance between excessive modules vs excessive categories 
2. Write the description that should appear on CP when the modules are selected (for new modules) 
3. Write help for setting any parameters
3. Write unit tests (does it run? does it work on an image of all zeros or a completely masked image?) and it would be nice if, when operating on masked images, the modules only analyzed the parts of the image where the mask was true. 
4. Have Lee check the quality overall

**Comment by dlogan** [comment]
Keeping open since I understand Virginie wants to do this, or have it done.
