### ISSUE TITLE
Entering text stops working during use on Mac OSX 10.10.1

### ISSUE THREAD

**Issue by maxruby** [CellProfiler/CellProfiler#1299]
When typing in e.g., Module notes, text editing stops working randomly and CellProfiler 2.1.1 must be restarted to work again (Typing on other windows appears to work fine).

Any suggestions on how to fix this?

**Comment by braymp** [comment]
Related to #1297, perhaps.

**Comment by LeeKamentsky** [comment]
Sorry about the delay. I have a machine with 10.10.1 installed and am running CellProfiler 2.1.1. I haven't reproduced this problem yet. Do you get any CellProfiler messages in the system console when this happens?

**Comment by maxruby** [comment]
I have not tried running CellProfiler from the terminal yet.  However, there are no messages when the problem arises - it is simply not possible to type into any field to change the parameters.  Is it possible that the binary for Mac is the source of the problem, and if so, would it wise for me to build CellProfiler from source?

**Comment by LeeKamentsky** [comment]
By any chance are you entering characters outside of the US ASCII set? I just tried that and I received a warning message. That's a bug - you should be allowed to enter any character you want.

I don't think running from source will fix the problem.

**Comment by maxruby** [comment]
No, I could not enter any characters whatsoever - it was not even possible to delete already existing values in any field.

**Comment by LeeKamentsky** [comment]
Does it happen when you open CellProfiler and start typing into the Module Notes box or do you have to load a particular project to get it to happen? If it only happens with a certain project, can you send it to me? (leek@broadinstitute.org). Thanks.

**Comment by maxruby** [comment]
Will do tomorrow morning - I don't believe that it is specific to a particular pipeline but we will see.

**Comment by maxruby** [comment]
Took longer to check this out again. We tested again our pipeline and found that text editing stopped during use.  There is nothing special about our pipeline though - its just a series of 7 consecutive regular modules from the menu.  Since the problem also occurred previously with a different pipeline, it is highly unlikely to be related to the pipeline itself.  

This last time, text editing stopped we we switched from test-mode back to regular (Analyze) mode.  
I am not sure there is much more useful information I can provide unless I start debugging step-by-step . . .  Hopefully, someone else is able to reproduce the problem or it disappears with a fresh re-install?

**Comment by LeeKamentsky** [comment]
It might be worth trying a new install. I would manually delete the /Applications/CellProfiler.app folder to ensure that only files from the current install were present. I'm going to try and replicate the behavior here - editing after running an analysis.

**Comment by 0x00B1** [comment]
I can't replicate. Closing.
