### ISSUE TITLE
OverlayOutlines: Better rendering of overlapping outlines

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1300]
If two outlines are drawn and they happen to completely overlap, it's not clear that this has occured from looking at the image. For example, the following was made using the welcome screen pipeline, changing the IdentifySecondary thresholding method on the 3rd image cycle:
![image](https://cloud.githubusercontent.com/assets/1186440/6062801/7e72921e-ad20-11e4-9cbc-c2c40e332e43.png)
Here, the secondary and primary objects are identical in some cases. I assume since the secondary outline was drawn last, that's the one that shows up. Perhaps an XOR of the colors to highlight it?

**Comment by LeeKamentsky** [comment]
I think the XOR or a combination of the colors might work. Also, we should think of this in terms of the new stuff in the workspace viewer - I can use lines to paint these and maybe those have alpha values that would automagically combine the colors. Here's an example with lines and alpha (red drawn first with alpha = 1, green with alpha = .5)
![image](https://cloud.githubusercontent.com/assets/660469/6063695/26bf6a18-ad27-11e4-8c7a-d390cf4d8ee9.png)

**Comment by braymp** [comment]
:+1:
