### ISSUE TITLE
Support export to CellH5

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1301]
Add a module, ExportToCellH5, that writes images, segmentations, measurements and relationships to the CellH5 format.

**Comment by LeeKamentsky** [comment]
@sommerc I have a branch, [exporttocellh5](https://github.com/CellProfiler/CellProfiler/tree/exporttocellh5), that has the file, [exporttocellh5.py](https://github.com/CellProfiler/CellProfiler/blob/exporttocellh5/cellprofiler/modules/exporttocellh5.py). I've put TODO comments throughout the file to indicate the places where things need to be saved. 

CellProfiler has a multiprocessing mode where the UI controls several workers. I've handled this by giving each worker its own subfile and every cycle, the worker asks the UI to make a link from the master file to the subfile for the site being processed. The model here is that writes to the master file are done by the UI and each worker has its own file to write to.

One open issue is how to handle Z and T stacks. I can think of two approaches:

* Represent each Z or T plane as a different site - this is closer to the CellProfiler model, but a little dishonest since the CellH5 model could represent them as the same site. Also, I don't know if you allow relationship links between segmentations at different sites and this might be the deal breaker.
* Stack segmentations and represent pipeline cycles at the same site as measurements and segmentations taken at different Z or T planes. The problem here is that object indexes in the segmentations would be reused; a pixel labeled as 1 in plane T=0 is not in the same object as a pixel labeled as 1 in plane T=1. It's a bit complex to renumber and the renumbering has to be carried forward to the relationship links and to certain measurements which are really object indices.

A second issue is that CellProfiler can produce overlapping segmentations (right now, mostly C. elegans worms which can cross each other so that the pixels in the areas shared by overlapping worms are labeled as belonging to both worms). We represent this by potentially storing multiple planes per segmentation and we ensure that the segmentations of worms that overlap are stored in separate planes.

For now, there are so many pipelines that do not use stacks or overlapping segmentations that I think we can ignore these issues temporarily and still give users something that they'll find usable for almost all cases, so my vote would be to think about the problems, but not solve them in the first iteration.

**Comment by sommerc** [comment]
Hey Lee!

> Represent each Z or T plane as a different site - this is closer to the CellProfiler model, but a little dishonest since the CellH5 model could represent them as the same site

Yes, I would rather think of an "image" in a well as being 5D in general, however this depends a bit on the use case. Some people would want to process z-slices or t-planes separately. Is there a "stacker module" in CP?

> Stack segmentations and represent pipeline cycles at the same site as measurements and segmentations taken at different Z or T planes. The problem here is that object indexes in the segmentations would be reused; a pixel labeled as 1 in plane T=0 is not in the same object as a pixel labeled as 1 in plane T=1.

In CellH5 the object labels are not renumbered. They are taken as is. Each segmentation will receive it's own unique object index, which then referes to the correct c, t, (z) and object label

> A second issue is that CellProfiler can produce overlapping segmentations 

It's not yet supported in CellH5, a thing we should certainly think about...

> For now, there are so many pipelines that do not use stacks or overlapping segmentations that I think we can ignore these issues temporarily and still give users something that they'll find usable for almost all cases, so my vote would be to think about the problems, but not solve them in the first iteration.

I agree. If it would not be too complicated, I would go for the stacked segmentations, but perhaps this is also easier to do later!?
