### ISSUE TITLE
DisplayPlatemap: Some display suggestions

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1302]
A few requested items:
* The colobar on the RHS is never updated and shows no legend.
* Labeling on the horizontal axis should show A-H instead of 0-11 and on the vertical axis 1-12 instead of 0-11 (for a 96w plate)

A follow-on from #1298. From this forum post: http://cellprofiler.org/forum/viewtopic.php?f=14&t=4149#p12530

**Comment by LeeKamentsky** [comment]
I think this is done.

**Comment by braymp** [comment]
Looks like to me.
