### ISSUE TITLE
GrayToColor: Downstream error if all channels left black

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1304]
It appears that if no channel selections are made in GrayToColor, the resultant image is the wrong shape (or doesn't exist?)

This can be replicated in the welcome screen pipeline by inserting a GrayToColor module after IdentifyPrimary, leaving the settings at the defaults, and then an OverlayOutlines after that, using  the GrayToColor output as input and the nuclei as the object to overlay. 

Running produces the following error:
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2777, in do_step
  File "cellprofiler\modules\overlayoutlines.pyc", line 208, in run
  File "cellprofiler\modules\overlayoutlines.pyc", line 332, in run_color
AttributeError: 'NoneType' object has no attribute 'ndim'
```

**Comment by LeeKamentsky** [comment]
I'm assuming that it's ok to fix this by adding a validation that prevents you from configuring it without any images, otherwise how is it to know what size to make the output?

**Comment by braymp** [comment]
Yah, that makes sense.

**Comment by LeeKamentsky** [comment]
GrayToColor.validate_module checked for this, but there was a bug that needed to be fixed before it would complain. So now it does.
