### ISSUE TITLE
Workspace viewer: Add help button

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1308]
It would probably be good to add a help button on the viewer itself. 
* The text would appear in a new HTML window.
* The text should be entered in cellprofiler\gui\help.py, as it will probably be re-used in the main UI help.

**Comment by LeeKamentsky** [comment]
I added WORKSPACE_VIEWER_HELP to help.py and added both a menu item and help button. I'm going to assign it to you to do the help, but you can assign it back to me if you want me to do the rough cut for the help which you can edit afterwards.

**Comment by LeeKamentsky** [comment]
The help text is filled-in, @braymp go ahead and edit.
