### ISSUE TITLE
Yosemite install asks for legacy Java SE runtime

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1312]
Error message on opening is "To open CellProfiler, you need to install the legacy Java SE 6 runtime".

CellProfiler's Java code is compiled for Java SE 6, but is compatible with later versions. The Javabridge is linked against Java SE 6 on the Mac, but should be compatible with the JVM for 7, so there should be no need to install 6.

**Comment by manics** [comment]
Sounds similar to the problems we had with the OMEOR.insight Mac packages https://github.com/openmicroscopy/openmicroscopy/pull/3417

**Comment by LeeKamentsky** [comment]
Thanks, Simon, that's a good reference point for doing the same thing.

**Comment by LeeKamentsky** [comment]
The problem is that Java 7+ are 64-bit only. We need the legacy anyway in order to run 32-bit.

**Comment by LeeKamentsky** [comment]
The current Javabridge doesn't explicitly link to the legacy JRE, so Apple no longer displays the warning. I think we need to add something to Info.plist or make CellProfiler display explicit directions on how to install the legacy Java, possibly with a button to go to the web page for downloading it.

**Comment by tlnagy** [comment]
I'm running into this issue right now on 10.11, is there any update on this? Thanks!

**Comment by 0x00b1** [comment]
Outdated
