### ISSUE TITLE
Workspace viewer: Outlines offset w.r.t. to image (and other oddities)

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1314]
I'm overlaying these objects on a grayscale image:
![image](https://cloud.githubusercontent.com/assets/1186440/6149775/2c042462-b1d9-11e4-8f8d-535b5b932edf.png)
and getting this:
![image](https://cloud.githubusercontent.com/assets/1186440/6149792/3d4809d2-b1d9-11e4-84c8-23dae14f4944.png)
A few things here:
* By my eye (and I could be wrong), the outlines seem offset down (and maybe to the left?) by a pixel.
* The original image has a white border at the bottom, so it seems that the axes are a bit off.
* The outline for the object at (3,19) seems to be broken into two pieces.
Will post the project file in a following comment.

**Comment by braymp** [comment]
Project file here: https://imageweb.broadinstitute.org/imaging/docs/People/Mark/github/1314/issue.cpproj

**Comment by LeeKamentsky** [comment]
I think I have this fixed. I have a pretty stable mechanism for mapping the image into the viewport given by the axes coordinates and the objects draw to the pixel centers in "lines" mode.
