### ISSUE TITLE
Subplots -> Image -> Image contrast / Interpolation do not apply to the right subplot

### ISSUE THREAD

**Issue by zindy** [CellProfiler/CellProfiler#1316]
Hello,

this is something I have checked with a couple of plugins. Tested with 2.1.2 rev fabe30e

As an example, I'm looking at IdentifyPrimaryObjects.

On the Figure generated, if I try Subplot -> "Image cycle #1" -> Image contrast -> Normalized,
the contrast is applied to the bottom left subplot / last subplot in the menu (say "Spot outlines").

If I then change the image contrast of  any of the other subplots (e.g. "Spots outlines") to Normalized, the subplots menu indicates that the contrast of "Image cycle #1" was changed to Normalized and the other subplots have their contrast set to raw. In the figure, the last subplot in the menu has its contrast altered, whichever subplot is selected in the Subplots menu.

Hope this makes sense. Interpolation seems to behave in the same way.

**Comment by LeeKamentsky** [comment]
Yup, that is a bug and I had no idea it was happening, thanks for finding, will get it fixed.

**Comment by LeeKamentsky** [comment]
BTW - if you're using the trunk build, check out the new workspace viewer (Test menu / View Workspace). You can send mail to cellprofiler-dev@broadinstitute.org with comments.
