### ISSUE TITLE
Workspace Viewer not getting the respect it deserves (individual module windows display anyway)

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1317]
On Mac, with Workspace Viewer activated, module windows open separately anyway and Workspace Viewer is blank.  Nothing reported in console. 
![screen shot 2015-02-12 at 10 57 54 am](https://cloud.githubusercontent.com/assets/1225595/6170926/f644dc5e-b2a5-11e4-82dc-d2e90f3fa3b7.png)

**Comment by LeeKamentsky** [comment]
I think this is by-design (so far). If you run to the end of the pipeline in test mode, set up the workspace and go to the next image, the pieces of the workspace should fill in as you step through the pipeline. I've left it up to the user whether to show or hide the figure windows - they are still useful in some circumstances.

Also, the workspace viewer only operates in test-mode, so if you want visual feedback during analysis, you need the figure windows.

**Comment by braymp** [comment]
@dlogan's comment is why I think there should be a WS viewer button among the test mode buttons, to make sure folks know it's there.

In the future, I can imagine the eyeballs going away completely and the WS viewer replacing that functionality. Eventually, the display windows too. 

However, as @LeeKamentsky mentions, some feedback, e.g, lower RHS stats from IdentifyPrimary, is still helpful. Not sure how to incorporate that info into the WS viewer, tho
