### ISSUE TITLE
Problems opening pipelines with corrupt URL

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1318]
Recently, I emailed a standard pipeline to someone, who then reported not being able to open it with the following error:
```
Error while loading None: Unknown mat file type, version 84, 119
```
Turns out that their institutional emailer intercepts URLs and rewrites them to avoid phishing scams (ProofPoint in this case, https://urldefense.proofpoint.com/). Since the first line in the pipeline is "CellProfiler Pipeline: http://www.cellprofiler.org", the rewritten link corrupted the pipeline. It looks like it inserted extra line/breaks as well.

Not sure what to be done about this, since I don't know how prevalent this sort of thing is.

Attachments:
http://cellprofiler.org/issues/uploaded/YSIui5/mangled_pipeline.cppipe

**Comment by LeeKamentsky** [comment]
Yup that's sad. I wonder what it allows through, for instance, XML namespaces have http URLs - does it mangle those too? I emailed them, asking them to exempt our files from alteration.

Regarding what to do, I'd rather not alter anything because of this, but you could convince me otherwise. I could leave the URL out of the check or improve the error message, but you assume that when you send someone a data file as an attachment, it gets there intact...

**Comment by LeeKamentsky** [comment]
Response I received via email:

    Eric Van Cleve <evancleve@proofpoint.com>
    6:17 PM (13 hours ago)
    
    to me 
    Lee-
     
      Thanks very much for contacting Proofpoint. My name is Eric Van Cleve.
     I am a product manager at Proofpoint, responsible for the URL Defense service.
     
     I’m sorry that you’re having difficulty with our rewrites breaking your file format.
     We do not globally whitelist third-parties for our entire customer base, so we
     cannot fulfill your specific request.
     
     However, it is very simple for this specific customer to exempt from re-writing:
 
        Messages addressed to certain recipients

        Messages addressed from certain senders
         
        URLs containing certain domains
 
      The customer just needs to make a simple configuration change on their email
    gateway. If they are uncertain on how to do it, they can contact Proofpoint 
    Technical Support at any time and we can walk them through the process.
    
     I hope this helps. Feel free to write back with any questions you might have.

**Comment by LeeKamentsky** [comment]
I found this on their FAQ page: http://support.proofpointessentials.com/index.php?/Knowledgebase/Article/View/170/34/url-defense-faqs
Q. Will all URLs in a message be defended? 

Yes. All URLs found in the email body content are re-written.
URLs located in attachments are not re-written.

Was the pipeline sent in an attachment?

**Comment by braymp** [comment]
It was, so that's odd. I'll email the recipient the pipeline again, and ask him to send it back to to confirm.

**Comment by braymp** [comment]
I asked him whether the pipeline appears in the email (1) as an actual attachment, or (2) as in-line text appended to the email. He said the former.

I also asked him, if an attachment, download it, zip it and send it back to me (just to make sure something doesn't happen to it both coming and going). The 1st line hash is slightly different, but otherwise looks the same as the one I posted earlier.

**Comment by braymp** [comment]
Looks like Boston Children's Hospital has adopted the same service, with the same effect.
