### ISSUE TITLE
JIRA [IMG-1105] evaluate scikits.image's heap.pyx for possible use in CP

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#132]
scikits.image has a heap implementation that we may be able to use in CP.  If so, we might consider dropping our own implementation and contributing any necessary improvements to their version to reduce code duplication.

Original reporter: thouis
Jira link: https://jira.broadinstitute.org/browse/IMG-1105
Assignee: leek

**Comment by 0x00B1** [comment]
CellProfiler/centrosome issue
