### ISSUE TITLE
Clean up the Worm Toolbox pipeline examples on the website

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#1323]
Note that we have some overlapping information that could be confusing:
http://cellprofiler.org/examples.shtml#UntangleWorms
http://cellprofiler.org/wormtoolbox/

We should at the least have a link from the first page to the second and vice versa. We think it's okay to have the pipelines on both pages.

**Comment by braymp** [comment]
Committed as svn revision 4690 to cellprofiler_www.
