### ISSUE TITLE
Display number of rows discovered in Input Modules 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1327]
I would find it useful for the Input Modules to display the number of images or sites discovered and displayed in the table after clicking "Update".  I.e. the number of rows in the table.  Especially for large data sets, the user often knows how many images or sites to expect and displaying the number found would provide a nice confirmation of this.

The number of rows found could be displayed in the status bar at the bottom of the window, but I am open to other locales certainly.

**Comment by braymp** [comment]
:+1:
