### ISSUE TITLE
CreateBatchFiles error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1332]
A [Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=16&t=4204&p=12668#p12668) reports that CreateBatchFiles errors in Windows.  I asked for more details.  

Here's the screenshot:
![snapshot](https://cloud.githubusercontent.com/assets/1225595/6575371/7938416a-c704-11e4-921e-956edc23b853.jpg)

Some non-ASCII issue?

**Comment by LeeKamentsky** [comment]
I think that when you upgraqde from 2.0 to 2.1, you might have c:\Users\.... in your default output or input folder. "\Users" gets parsed as "unicode character sers" which is nonsense. I will fix.

**Comment by LeeKamentsky** [comment]
lower-case "c:\users"
