### ISSUE TITLE
Add Help for Metadata Regexp "Guess" button

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1335]
At least on Mac, the Guess button never seems to do anything. Some students at a BroadE asked about this function, and even in trunk, I can't get it to fill in any regexp, given various inputs.  How is it supposed to work?

**Comment by LeeKamentsky** [comment]
It would only work if you have a file name from one of the supported microscopes. Try something from one of our screens (e.g. `20130213u2os-prescreendba18-96h_g16_s8_w11619fbbe-5bcd-487b-8e48-fc183b5072d9.tif`). That one worked for me. Perhaps if it can't guess, it should tell you.

**Comment by dlogan** [comment]
Ah yes, I see -- it works with another recent file from a local screen.  

Yes, it ought to tell you it can't match the Test text.  Even better, it could display the list of potential guesses from the "RE_FILENAME_GUESSES" in regexp_editor.py to inform the user what it is trying to match from, and maybe we could even ask users to send us other 'standard' file names.

**Comment by LeeKamentsky** [comment]
I think there's an issue somewhere from Christian Tischner about adding some config file that lets someone put their own expressions into the editor. But all of above would be good.
