### ISSUE TITLE
RenameOrRenumber: Error re: file in use

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1338]
Running the attached pipeline produces the following error:
```
Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 1934, in run_image_set
  File "cellprofiler\modules\renameorrenumberfiles.pyc", line 250, in run
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
```

From this forum post: http://cellprofiler.org/forum/viewtopic.php?f=14&t=4256&p=12847

Attachments:
http://cellprofiler.org/issues/uploaded/pvCjrl/issue.cppipe
http://cellprofiler.org/issues/uploaded/IDZped/A1_rescaled.png

**Comment by LeeKamentsky** [comment]
There's some bioformats fanciness to keep the image reader around in case we're reading movies. The file is open, so in Windows, you can't delete it. I cleared the cache - doesn't matter much here.
