### ISSUE TITLE
Consider an O(n) watershed

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1343]
This paper (http://www.ncbi.nlm.nih.gov/pubmed/17076410 Building the component tree in quasi-linear time) could give us the connected components at each level of a level set. That would let you examine the tree when creating a seeded watershed. Our watershed operates in N(log N) time and consumes a lot of memory and not in a cache-friendly manner.

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/centrosome#18
