### ISSUE TITLE
More feedback on Display Windows

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1344]
Users like [this one on the Forum](http://cellprofiler.org/forum/viewtopic.php?f=14&t=4251&sid=ad1e6d4e0db9cd5cc230160ec1ac5a3f) get misled by intensity scaling in the display windows all-too-often.  Context menus for this sort of setting are ok, but sometimes too hidden.  

I suggest, either:
(1) adding the intensity scaling setting to the display window as static text indicating the state (e.g. "RAW", "Normalized","Log normalized")
or 
(2) (Preferred!) Adding a drop-down chooser directly in the display window.  

Exactly where this might be placed can be up for debate (as well as whether or not to implement to begin with).

We could also add interpolation level and channel choosers for images, but the intensity scaling is the most critical one IMHO.

**Comment by LeeKamentsky** [comment]
It might be nice to have an associated controls window that you could expand or hide as necessary with the scaling controls and interpolation. We can add functionality to that window if people come up with other ideas. The trick is to figure out how to make the controls obvious while not eating screen real estate.

**Comment by dlogan** [comment]
Agreed that we need to think about how to implement this with other new controls, like the Workspace viewer.

**Comment by braymp** [comment]
Re: control window - Perhaps something like Adam's implementation of the display controls for the ImageViewer in CPA?
