### ISSUE TITLE
Yosemite: Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1348]
A Mac user gets the following error:
![image](https://cloud.githubusercontent.com/assets/660469/7252390/8e5ef614-e802-11e4-8976-6d75ece9fbc9.png)
![image](https://cloud.githubusercontent.com/assets/660469/7252393/932657f0-e802-11e4-874a-435ad5fd1359.png)
![image](https://cloud.githubusercontent.com/assets/660469/7252396/9a3f75bc-e802-11e4-83e7-c65fa7da30bd.png)
![image](https://cloud.githubusercontent.com/assets/660469/7252398/9e0bfc38-e802-11e4-9dd3-6770180c11a4.png)

**Comment by mcquin** [comment]
There isn't enough information here to debug.
