### ISSUE TITLE
Error while loading None: Unknown mat file type, version 57, 65

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1349]
Mac 10.10 user does this with trunk build:
"I have the latest rev. I was opening up cellprofiler, File > Import > Pipeline. Error message pops with the text
```
Error while loading None: Unknown mat file type, version 57, 65
Do you want to stop processing?
```
."

Attachments:
http://cellprofiler.org/issues/uploaded/BMsKtY/DL_organoids_pipeline_trunk_v2.cppipe

**Comment by dlogan** [comment]
I had loaded a couple illumination functions in this pipeline previously (which the user didn't have), however I have taken them out of NamesAndTypes.  Not sure why the "mat file" error is happening still.

**Comment by braymp** [comment]
If this pipeline was emailed to the user, then #1318 might be the reason, depending on the institution.

**Comment by dlogan** [comment]
Good catch Mark! I didn't realize the error was the same.

**Comment by braymp** [comment]
Probably best to close this issue. You can zip up the file and send it to them, or have them use a different email address. When I get back, I can discuss more workarounds for this.

**Comment by LeeKamentsky** [comment]
The .mat file error happens because CP tries to open it as a text pipeline first, then tries to open it as a .mat file pipeline after that. Perhaps you can fault me for the thoroughness of my desperation :stuck_out_tongue_winking_eye:

**Comment by dlogan** [comment]
Likely duplicate of #1318
