### ISSUE TITLE
Opening a project file via drag/dropping doesn't update the default output folder

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1355]
When opening a project file via drag/dropping, the default output folder remains as it was, rather than populating with the saved project DOF.

**Comment by LeeKamentsky** [comment]
Are you sure? I just did it and it worked. Do you have the project file?
Also, if it was on Iodine, it probably will reject the DOF because the directory is now on Argon.

**Comment by braymp** [comment]
The latter was probably the issue. Closing.
