### ISSUE TITLE
Python crash loading project into master

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1356]
The attached project was created with trunk build 6c2d896. Loading it into master (currently 8de4eb2) and then simply clicking various modules crashes Python with the following log:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	0.0.0.0
  Application Timestamp:	538b9977
  Fault Module Name:	wxmsw28u_core_vc.dll
  Fault Module Version:	2.8.12.0
  Fault Module Timestamp:	4e2ec923
  Exception Code:	c0000005
  Exception Offset:	0000000000007f55
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	71d8
  Additional Information 2:	71d8e37fee01ee9d1f0c273734b37c73
  Additional Information 3:	1b9d
  Additional Information 4:	1b9d4af7e628f84df652562e31f12bc5
```

Attachments:
http://cellprofiler.org/issues/uploaded/a4U4mI/strawberrymilkrev2orig.cpproj

**Comment by LeeKamentsky** [comment]
db2f9e78bc326d81c8fbad74afc01598219a7c6a introduced a bug: in some cases the multiplication factor setting could be added to the visible settings twice. The setting's windows then get processed twice which does something bad and unknown to WX's underpinnings causing it to segfault when the setting's windows are destroyed.
