### ISSUE TITLE
Metadata: Enhanced handling of digits for image set creation

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1357]
NamesAndTypes creates image sets in lexical order,so that a file starting with '10' is processed before one starting with '1'. But in some cases, the user may want the image set to be created in the intuitive numbered order, e.g, '1' before '10', and may not have the option of easily renaming the files to suit. It would be nice for CP to support this.

I was wondering where such a thing could be added, and had some thoughts:
* It should probably be allowed only if extracting metadata and then matching image sets by metadata. Otherwise, how else would you know what items should be ordered in what way?
* In Metadata, if the user selects a metadata type to be 'integer' instead of the default 'text', the list is ordered numerically automatically in NamesAndTypes if that metadata is used in image set matching.
* If not automatically, add a setting in the metadata type dialog for how ordering is to be done. Perhaps the default is 'Alphabetical', with the option of 'Numeric' (or whatever the proper terminology is).

**Comment by LeeKamentsky** [comment]
It should be (and if not, it's a bug) that matching by metadata in NamesAndTypes dictates the image set order. If you specify that a metadata item is numeric, it should order numerically. If more than one metadata item is used for matching, the list should be sorted by the first, then ties should be broken by the second and so on.
I'll check for this and add a test for it, if not present.

**Comment by LeeKamentsky** [comment]
I created a project that has a metadata field (N) that's used to sort the image sets. In the project as it is, it's set to numeric and it sorts in numeric order. If you change to text, it sorts alphabetically. So, if someone has more than one channel and can match by metadata, problem solved. It doesn't solve the problem of sorting single-channel assays or if you want to sort by metadata and match by order. I could add a "sort by" option to NamesAndTypes to do that. For a work-around, you can always add a bogus channel and use "None" to match a single bogus image against the metadata to use for ordering.

 https://broadinstitute.org/~leek/issue1357/issue1357.ccproj

**Comment by braymp** [comment]
This is sufficient, I think. I'll assign it to myself, add some documentation to this effect, and close when done.
