### ISSUE TITLE
FlagImage+Skip image grouping bug

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1360]
[This Forum user](http://cellprofiler.org/forum/viewtopic.php?f=16&t=4302) reports a bug in FlagImage, while skipping images and also using Grouping.  I am attaching the their project file here for convenience, though there are no images to go along with it.  Further details on the error are on the Forum page 

Attachments:
http://cellprofiler.org/issues/uploaded/iEyXA6/125_RPApipeline.cpproj

**Comment by LeeKamentsky** [comment]
I answered on the forum - I believe I've fixed a number of bugs in this area.

**Comment by braymp** [comment]
User reported that it did not fix the issue.

**Comment by AnneCarpenter** [comment]
This is likely complex to figure out and fix, unfortunately. Marking it for future consideration.
