### ISSUE TITLE
When drag/dropping to move multiple modules, clicked module is not moved

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1363]
To replicate:
* Load welcome screen pipeline
* Select the top 3 Crop modules
* Click-hold any one of the selected modules
* Attempt to move the selected 3 modules by drag/dropping the selected module

Only the modules not clicked on are moved; the one that was clicked-held stays where it is.

**Comment by LeeKamentsky** [comment]
I agree it should be fixed - just to explain, the click-down toggles the selection, often removing it and that creates the problem. If we could somehow make the toggle-selection happen after the user releases the button, the problem would be solved.
