### ISSUE TITLE
SaveImages: If objects loaded from file, object filename not available as file prefix

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1368]
If the user wants to save an object set, and would like to use the object filename as the prefix, they can't since only loaded images are shown in the drop-down.

Proposed solution: If "Objects" selected image type to save, add "From object filename" to the method drop-down, and add a drop-down that displays only the loaded object names.

**Comment by AnneCarpenter** [comment]
I'm guessing this is relatively uncommon situation... wouldn't there always be a decent workaround which is to choose a loaded image (which are displayed as options)? I am guessing nearly any pipeline someone would make would have some loaded images that would be sensibly used for naming, even if objects were loaded in this funky way. (will close and mark for future consideration - if this workaround seems an okay solution then remove the future consideration label)

**Comment by braymp** [comment]
I'm OK with this. Another workaround is to:
* Obtain the object filename in the Metadata module
* In SaveImages, use "Single image" for the method and insert the filename metadata tag in the text box.
