### ISSUE TITLE
Change UI color in test mode

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1372]
From a user at the Vertex workshop: He suggested changing the UI color when in test mode to make clearer (I guess the buttons/icons and such blend in too well).

**Comment by braymp** [comment]
From @AnneCarpenter: "Maybe just having the pipeline window take on an extra frame (if I'm using terminology correctly?) E.g., it gets an additional yellow outline around the pipeline area?"

**Comment by LeeKamentsky** [comment]
I think I need some more specific guidance. There's quite a lot of movement cues when you activate test mode (buttons change, the stepping interface appears) - I'd hope that would tell the story that you've gone into test mode. If it's a question of making the pause buttons more prominent, I'd welcome suggestions or edits on the images (cellprofiler/icons ).
