### ISSUE TITLE
CP doesn't let go of an image that is being overwriten

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1375]
In 2.1.2, the attached pipeline attempts to load a file, overwrite it and then load it again. It yields the following error (even though "Overwrite existing without warning" is set to "Yes"):
```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 1947, in run_image_set
    self.run_module(module, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2058, in run_module
    module.run(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 483, in run
    should_save = self.run_image(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 527, in run_image
    self.save_image(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 719, in save_image
    filename = self.get_filename(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 874, in get_filename
    os.remove(result)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\Developer\\Desktop\\random_grayscale_image_00_B.tif'
```
NB: This behavior worked successfully in 2.1.1

Attachments:
http://cellprofiler.org/issues/uploaded/gvaOhe/issue.cppipe
http://cellprofiler.org/issues/uploaded/pifAXd/random_grayscale_image_00_A.tif
http://cellprofiler.org/issues/uploaded/xbRwOV/random_grayscale_image_00_B.tif
http://cellprofiler.org/issues/uploaded/nft819/random_grayscale_image_01_A.tif

**Comment by braymp** [comment]
The attached pipeline doesn't have grouping enabled, which might mean that multiple workers are vying for the same file. If you enable the "Groups" module and have it group on "Frame" (a hacky way to insure 1 group for the 2 image sets), the same error results.

**Comment by LeeKamentsky** [comment]
It was holding onto the cache.

You might try to figure out a way to store the temp image inside ImageJ using some scripting. Load a blank image at the start of the group, get the current image at the start of the pipeline and remove all images, put the aggregate image at the end of the pipeline. Close all images at the end of the group.
