### ISSUE TITLE
Save workspace viewer state to project file

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1376]
Random idea: Is it possible to save the workspace viewer state (e.g, choice of images/objects, colors, zoom, crop location) as part of the project file? 

That way, it can be re-opened in the viewer across sessions, and is esp. convenient if the user has a lot of items to view, and happens to be particular about the configuration. (Not that I have anyone like that in mind...)

**Comment by LeeKamentsky** [comment]
I could have paid better attention to this - there are a lot of reasons it's a good idea since I'd have to separate the model of the display from the display itself. So let's keep it in mind, but definitely will have to wait.
