### ISSUE TITLE
Creating an EXE file for Windows and Mac

### ISSUE THREAD

**Issue by Niki1230** [CellProfiler/CellProfiler#1378]
Hi ! 

I am currently creating 2 modules in Cellprofiler and I am working on Linux. In this modules, I am using OpenCV and Numpy.

I would like to know if it is possible to create an executable file for Windows and Mac using these libraries so that anyone running this EXE file could use my modules. If so could you tell me how I should proceed? 

Thank you for your help!

Niki

**Comment by LeeKamentsky** [comment]
A module that uses numpy can be put into the plugins folder and just work with any compiled version of CellProfiler. OpenCV is another story. There's some chance OpenCV could become a dependency of CellProfiler in the future but for now it is not one.

You can build CellProfiler from the development environment on Windows and the Mac. Directions are here:
https://github.com/CellProfiler/CellProfiler/wiki#Developer_resources

At some point, we will be using our continuous integration server to build development environments for Windows and the Mac as  we do now for Linux and it will be much easier at that point to replicate our build process but until then, you are largely on your own aside from the directions above.

**Comment by Niki1230** [comment]
Thank you  :) !!
