### ISSUE TITLE
Make a Maximum Projection (Stack Image)

### ISSUE THREAD

**Issue by Niki1230** [CellProfiler/CellProfiler#1379]
Hi !! :)

I am having a problem with the MakeProjection module. I have followed this document in order to load the stack image but I am not sure of doing it the right way :/ ! 

http://www.cellprofiler.org/tutorials/Loading%20image%20stacks%20and%20movies.pdf

When I follow this tuto and I apply the MakeProjection module, I obtain the first image of the stack image, as if there was no projection made... :/

Thank you in advance :) 

Niki

**Comment by LeeKamentsky** [comment]
Hi Niki,
Can you post this on the forum (http://cellprofiler.org/forum)? That will get you a response from Mark or David who are much better at this.

-- Lee

**Comment by Niki1230** [comment]
Ok ! :) Thx !
