### ISSUE TITLE
Badly drawn objects touching edge

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1381]
The workspace displays an object with a line down the side of the display:
![image](https://cloud.githubusercontent.com/assets/660469/8130638/2a2ef654-10e2-11e5-9d30-a09aa2d249d7.png)

Pipeline (local to my machine) c:/temp/relateobjects/issue.cppipe

**Comment by AnneCarpenter** [comment]
Without the file, I don't think we can reproduce this unfortunately.
