### ISSUE TITLE
Provide a better image view for stacks/multi-plane images

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1391]
Now, a viewer is only shown the top slice of a stack.  It would be nice and less confusing for the user to be able to page through the stack

**Comment by 0x00B1** [comment]
duplicate issue

**Comment by AnneCarpenter** [comment]
I figured - I'm removing "future consideration" label now, then - if I revive something from the dead like that keep an eye out for that label as it can cause zombie-like behavior 😄

**Comment by 0x00B1** [comment]
Ah! I see.
