### ISSUE TITLE
Write a file (.html?) for debugging purposes

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1392]
From the old roadmap:

We can write a file (.html?) for debugging purposes. Lee is concerned about debugging these new modules, particularly with their many complicated interactions.

* If we provide a verbose but readable and navigable log of what each module is doing, we can allow the user to do more of their own debugging, and make it easier for us when they can't manage to fix problems on their own.

* Provide a dynamic display of:
Every file we saw while walking the source directories, marking every file removed for not matching filters.
Every image extracted from the remaining files, marking images removed for not matching image/metadata filters.
All the metadata extracted from filenames for every image.
All the channel assignments
Every imageset created.
All the rules that resulted in this process, at appropriate points.

* The user can see what was found, what was extracted, why each file was grouped as it was, etc.
If we cache the workspaces in a separate file, rather than the .HDF5, it should be in a format like this (HTML, not XML, and not .CSV).
If we store them in the .HDF5, we should add to each of Images, Metadata, NamesAndTypes, Groups an HTML panel (as a new Settings object type: cps.Feedback, perhaps?) with the relevant information, so the user can see it easily, along with a right-click menu to allow the user to save the html in a file.

**Comment by 0x00b1** [comment]
I don’t see this making module debugging easier.
