### ISSUE TITLE
export to spreadsheet in batch mode with -o option

### ISSUE THREAD

**Issue by erexhepa** [CellProfiler/CellProfiler#1397]
Hi,

I'm running in the cluster in batch mode using by using the create batch files module. To send jobs to different nodes of the cluster I'm using the -f and -l switch but to generate the output for each run I use -o switch by giving a folder name. 

Everything goes smoothly during the analysis and there are folders created by each job but folders are empty. 

Here is an example of a command send to to one of the nodes.

python /users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/CellProfiler.py -c -r -p testBatchmode/Batch_data.h5 -f 2 -l 2 -o testFolder

I was wondering if there is patch for this or if I'm doing something wrong with the options given to the command line to set the DOF for each job.

Thanks
Elton

**Comment by LeeKamentsky** [comment]
Which version of CellProfiler are you running? I think this was fixed, but after the 2.1.1 release. You should look at patch 3fdcb32 and issue #1146

**Comment by erexhepa** [comment]
I'm using version 2.1.1. 

I saw the patch you metioned above and tried it but had an error afterwards when starting the main script of cell profiler. It seemed to be due to the JVM. Anyway I will give another shot to the patch above because I had applied several patches before the 
https://github.com/CellProfiler/CellProfiler/commit/3fdcb3216a1913e1dc7934de719b0f2d804d7e3c and now since then I did a fresh install. 

Thanks

**Comment by erexhepa** [comment]
Well, I get again the jvm error below:
-----------------------------------------------------------------------------
WARNING: Java and JVM is not installed - Images will be loaded using PIL ('NoneType' object has no attribute 'endswith')
Traceback (most recent call last):
  File "/users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/CellProfiler.py", line 888, in <module>
    main(sys.argv)
  File "/users/biocomp/rexhepaj/CP_Bioclust/CellProfiler/CellProfiler.py", line 196, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/import/ar_biocomp/rexhepaj/CP_DEV_BIOCLUST/Biophenics/CP_Bioclust/CellProfiler/cellprofiler/utilities/cpjvm.py", line 15, in <module>
ImportError: libjvm.so: cannot open shared object file: No such file or directory

**Comment by LeeKamentsky** [comment]
CellProfiler isn't finding the location of libjvm.so. Is it possible that the location for libjvm.so at the time CellProfiler was compiled (`python CellProfiler.py --build-and-exit`) has changed? You might be able to correct this by setting LD_LIBRARY_PATH to $JAVA_HOME/jre/lib/amd64/server, assuming JAVA_HOME is correctly defined and you're running x86_64 / amd64.

**Comment by erexhepa** [comment]
no the variable LD_LIBRARY_PATH is set to the right point but the error is due to something going on during the checkout of the patch from github. 

It works before the checkout of the patch but after the checkout I get an error message (different one now)

Run external_dependencies with the -o switch to get full output.
running build_ext
skipping '_cpmorphology2.c' Cython extension (up-to-date)
skipping '_watershed.c' Cython extension (up-to-date)
skipping '_propagate.c' Cython extension (up-to-date)
skipping '_filter.c' Cython extension (up-to-date)
skipping '_lapjv.c' Cython extension (up-to-date)
skipping '_convex_hull.c' Cython extension (up-to-date)
skipping '_fastemd.cpp' Cython extension (up-to-date)
Error: Could not find or load main class findlibjvm
Traceback (most recent call last):
  File "CellProfiler.py", line 888, in <module>
    main(sys.argv)
  File "CellProfiler.py", line 196, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/home/eltonr/CP_INSTALL/CellProfiler/cellprofiler/utilities/cpjvm.py", line 16, in <module>
    import bioformats
  File "/home/eltonr/CP_INSTALL/CellProfiler/bioformats/__init__.py", line 150, in <module>
  File "/home/eltonr/CP_INSTALL/CellProfiler/bioformats/__init__.py", line 68, in start_cellprofiler_jvm
  File "/home/eltonr/CP_INSTALL/CellProfiler/external_dependencies.py", line 322, in get_cellprofiler_jars
    "Can't determine CellProfiler java dependencies because %s is missing. Please re-run external_dependencies with the -o switch" % path)
RuntimeError: Can't determine CellProfiler java dependencies because /home/eltonr/CP_INSTALL/CellProfiler/imagej/jars/cellprofiler-dependencies-classpath.txt is missing. Please re-run external_dependencies with the -o switch

should I do a merge of the patch with the master branch rather than a checkout ?

**Comment by LeeKamentsky** [comment]
You need to run `python external_dependencies.py -o` to update the .jar files.

**Comment by erexhepa** [comment]
now it seems to be stucked in cpjvm.py. it is blocked there with nothing happening after the error below

Traceback (most recent call last):
  File "CellProfiler.py", line 985, in <module>
    main(sys.argv)
  File "CellProfiler.py", line 199, in main
    cp_start_vm()
  File "/home/eltonr/CP_INSTALL/CellProfiler/cellprofiler/utilities/cpjvm.py", line 160, in cp_start_vm
    class_path = get_jars()
  File "/home/eltonr/CP_INSTALL/CellProfiler/cellprofiler/utilities/cpjvm.py", line 101, in get_jars
    class_path = javabridge.JARS + jar_files
AttributeError: 'module' object has no attribute 'JARS'

**Comment by LeeKamentsky** [comment]
Sorry, Elton, I just realized that this went unanswered. You likely have a copy of javabridge.so or javabridge.pyd in your cellprofiler/utilities directory left over from 2.1.1. You should delete those and try again. Also, I just fixed a problem related to yours: issue #1518. You should probably take the pull/1518 branch or, if 1518 is resolved, the master branch (after pull/1518 is merged).

**Comment by erexhepa** [comment]
Thanks Fixes #1518 solved indeed the issue. Thanks again. 
Elton
