### ISSUE TITLE
ClassifyPixels crashes when loading a color image as grayscale

### ISSUE THREAD

**Issue by manuels** [CellProfiler/CellProfiler#1399]
I'm CellProfiler 2.1.1 (revision 6c2d896) on Windows and I have created a ilastik classifier for some RGB tif images.
I accidentally forgot to choose "color image" under "NamesAndTypes" -> "Select the Image type" and when I ran the ClassifyPixel step, cell profiler crashed without any error message (Windows message box: "CellProfiler has stopped working").

When I figured out that I had to choose "color image", it worked perfectly. However, it took a while to find this mistake. It would be great if CellProfiler could show an error message in this case.

**Comment by LeeKamentsky** [comment]
I'm having a bit of difficulty figuring out whether I can discern where this information is recorded in the Ilastik classifier file - thanks for reporting, may not be able to fix.

**Comment by 0x00B1** [comment]
Ilastik has been removed
