### ISSUE TITLE
Workspace viewer: When displaying a color image, disable the color picker

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1400]
If a color image is displayed, it's a bit misleading to keep the color picker active, or at least, it's not clear what the picker should do. Perhaps it can be disabled/grayed out?

**Comment by LeeKamentsky** [comment]
I'll take a look at it. I was hoping, eventually, to carry through an image's color / grayscale / binary (and eventually 3D or ND nature) using a scheme like get_measurement_columns which would let the workspace viewer solve this kind of problem without referencing the image. I'll have to look and see if the UI has access to the image directly.

**Comment by braymp** [comment]
Not a huge priority, I think, so take your time.

**Comment by 0x00B1** [comment]
Workspace viewer has been removed
