### ISSUE TITLE
Installing CellProfiler on Ubuntu when behind a proxy server.

### ISSUE THREAD

**Issue by aolsux** [CellProfiler/CellProfiler#1401]
Hey guys, it took me some time, but now it seems to work.
I am behind the Charite Berlin proxy and hence all those automatic package download stuff is rather complicated. 
What i did is adding these lines to the external_dependencies.py script.

```
    proxy = urllib2.ProxyHandler({'http': 'proxy.charite.de:8080'})
    opener = urllib2.build_opener(proxy)
    urllib2.install_opener(opener)    
```

Providing an option for the dependcy script to use a proxy should be pretty straight forward. Maybe ill do that as pull request;-)

and further i needed to set up maven correctly to fetch poms via proxy. create/edit file $HOME/.m2/settings.xml to contain

```
<settings>
  <proxies>
   <proxy>
      <id>charite</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>proxy.charite.de</host>
      <port>8080</port>
    </proxy>
  </proxies>
</settings>
```

Because i have no clue of the whole maven thing, i dont know whether there is a straight forward way to configure maven from your python setup.
HtH Martin

**Comment by LeeKamentsky** [comment]
I think a good feature request would be adding a command-line switch to external_dependencies.py that would let you use a proxy server.

Pragmatically, you can run external_dependencies.py on a machine outside the firewall (e.g. get one from digitalocean.com or similar) and copy the contents of imagej/jars behind the firewall and run CP with the command-line switch --do-not-fetch from then on.
