### ISSUE TITLE
ConserveMemory: Does it still work?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1402]
With the changes in memory handling, it might be good to confirm that this module still works in the way we think it does (or at least, the way it should)

**Comment by LeeKamentsky** [comment]
In the context of 2.1.2, the answer is that adding ConserveMemory to your pipeline should have no detectable effect. Both objects and images are ejected from core and written to HDF5.

**Comment by braymp** [comment]
Sounds like it's worth deprecating in that case; we don't want to give users a false sense of hope :-)
