### ISSUE TITLE
Workspace viewer: Automatically add new objects to view

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1406]
Suggested by attendee @ Vertex workshop: He thought that it would be good to have the viewer automatically add objects to the list, and have them shown.

Personally, I'm not sure about this. It seems reasonable on the face of it, but my concern is that it can get cluttered v. quickly for long pipelines.

**Comment by LeeKamentsky** [comment]
My idea for the workspace viewer was that it was a place for the user to composite their view. This breaks that rule - something happens to the user's composition outside of their control. I would prefer not to do it.

**Comment by braymp** [comment]
I'm willing to accept that; closing.
