### ISSUE TITLE
JIRA [IMG-1078] ColorToGray: Grayscale enhancement

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#141]
One user on the forum came up with the suggestion to better merge color images into grayscale using this method:<a href="http://www.cl.cam.ac.uk/~mg290/Portfolio/TurnColorsGray.html#Portfolio">http://www.cl.cam.ac.uk/~mg290/Portfolio/TurnColorsGray.html#Portfolio</a><br/><br/>Does this seem like a good idea to include to GrayToColor? For my color projects, sometimes a good grayscale image is all I need instead of sorting out issues with color mixing....<br/>&nbsp;&nbsp;&nbsp;-Mark

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1078
  (Original JIRA has attachments.)
Fix version: future
Assignee: mbray

**Comment from mbray on Tue, 27 Jul 2010 12:27:48 -0400:**
On 1/22/2010 12:06 PM, Mark Bray wrote:<br/>&gt; If you&#39;re reducing a color image to grayscale for any reason, I wouldn&#39;t think you&#39;d want it for quantitative measurements anyway. I was thinking more of doing it for better object identification.<br/>

**Comment by braymp** [comment]
Might be something fun for Allen to do.
