### ISSUE TITLE
Error with "-t" switch for cellprofiler.py

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1411]
[This Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=18&t=4449) is getting an error when trying to change their temp directory on their cluster using the "-t" switch, using a recent CP clone (16 July 2015).  They have limited space on their cluster temp directory. 

Here's an example command:
```
python /home/pmt3sw/CellProfiler/CellProfiler.py --do-not-fetch -t /scratch/pmt3sw/temp -b -c -r -p /scratch/pmt3sw/control/DV005/batchE.h5 -f 1153 -l 1440
```

and their output:
```
Thu Jul 23 15:34:18 2015: Image # 1154, module NamesAndTypes # 3: 0.37 sec
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "/home/pmt3sw/CellProfiler/CellProfiler.py", line 279, in main
    run_pipeline_headless(options, args)
  File "/home/pmt3sw/CellProfiler/CellProfiler.py", line 982, in run_pipeline_headless
    measurements.close()
  File "/nv/blue/pmt3sw/CellProfiler/cellprofiler/measurements.py", line 359, in close
    self.__image_cache_file.flush()
  File "/share/apps/anaconda/2.2/lib/python2.7/site-packages/h5py/_hl/files.py", line 263, in flush
    h5f.flush(self.fid)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2362)
  File "h5py/h5f.pyx", line 109, in h5py.h5f.flush (-------src-dir-------/h5py-2.4.0/h5py/h5f.c:2044)
RuntimeError: Unable to flush file's cached information (File write failed: time = thu jul 23 15:34:19 2015
, filename = '/tmp/cellprofilerimagecachefb4pgg.h5', file descriptor = 231, errno = 28, error message = 'no space left on device', buf = 0x4b68198, total write size = 4096, bytes this sub-write = 4096, bytes actually written = 18446744073709551615, offset = 32097336)
Failed to stop Ilastik
```

**Comment by LeeKamentsky** [comment]
Nice catch by the user - the new image cacheing code was not using the temp directory to create the cache file.

**Comment by braymp** [comment]
I think this issue may still be outstanding in some form.

To replicate:
* Set the temp folder to someplace other than the default (I had to do this via the registry in Windows, per #1421). For reference, call the new temp location F1, and the default temp location F0
* Start CP and load the welcome screen pipeline (a temp Cpmeasurements file gets placed in F1) and start the analysis

I see the following (3 workers active):
* As the job starts, another Cpmeasurements file gets placed in F1, and a turbojpeg*.dll file in F0
* On the 1st image set, some temp TIFs, more turbojpeg and Cpmeasurements files, and theCellProfilerImageCache files get placed in F0
* When the job finishes, one Cpmeasurements is left in F1, and the turbojpeg files remain in F0.

**Comment by LeeKamentsky** [comment]
I went at this one pretty brutally - now CellProfiler sets tempfile.tempdir to the value in the -t switch. Hopefully that covers all cases.
