### ISSUE TITLE
Installing CellProfiler dev on Mac OSX Yosemite

### ISSUE THREAD

**Issue by keoughkath** [CellProfiler/CellProfiler#1413]
Hello, I'm trying to install CellProfiler developer version on Mac OSX Yosemite but as this OSX comes preloaded with Ruby 2.0 am running into errors during installation. I installed Ruby 1.8 but am still getting this error when I try to install:
>>CPhomebrew.git/bin/brew install cellprofiler-dev
  CPhomebrew.git/bin/brew: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory

Any tips would be much appreciated!

**Comment by dlogan** [comment]
Sounds like this issue and homebrew itself needs updating:

http://apple.stackexchange.com/questions/153790/how-to-fix-brew-after-osx-upgrade-to-yosemite

Please try these fixes and let us know how it goes!  As far as I know we haven't seen this yet.

**Comment by LeeKamentsky** [comment]
Unfortunately, we're out on a very outdated fork of Homebrew. Doing a GIT
pull will create quite a mess. We've recently hired a software engineer who
is pretty good at this sort of thing. Seeing that CellProfiler has some
problems with OS/X, it might make sense to have that be a priority for him.
But no simple immediate answers - it will be at least a week until we can
take a serious look at this.

This link <http://ryantvenge.com/2014/09/ruby-homebrea-yosemite/> describes
an ugly hack that might work for our homebrew, but it stands a better
chance than a git pull. Let us know if it works - we'll put it into our dev
docs if it does.

**Comment by dlogan** [comment]
Oh right -- yes, Lee's comment and link points to the same as the second-voted response on the apple.stackexchange.com link above.

**Comment by keoughkath** [comment]
Great thanks I'll give that hack a try and let you know.
