### ISSUE TITLE
Export Pipeline Comments

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1417]
I would find it useful to have a way to export a simple pipeline listing with the Module Notes associated with each module.  This would be useful for CP Forum posts, to list a summary of our posted pipeline, or even for publication, as a nice summary of the analysis steps.  

Something like:

[Module #]. [Module name]: [Module Notes]
[Module #]. [Module name]: [Module Notes]
...

It could live under File > Export > Pipeline Comments

**Comment by braymp** [comment]
:+1:
