### ISSUE TITLE
Image set chooser: Move listbox view to currently selected image set

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1420]
When a user brings up the image set chooser dialog in test mode, the list box should show the currently selected image set (if any) so the user doesn't have to scroll to find it. 

I think wxListBox::SetFirstItem	does this: http://docs.wxwidgets.org/trunk/classwx_list_box.html#ad51cf8a4f71c5525ad85a7217af56e74

The same would probably go for the image group chooser as well.

**Comment by LeeKamentsky** [comment]
I think it already does this [here](https://github.com/CellProfiler/CellProfiler/blob/b1f5c9b667f33f9a0297b0b1b09909240dcc1269/cellprofiler/gui/pipelinecontroller.py#L3165) for the image list and [here](https://github.com/CellProfiler/CellProfiler/blob/b1f5c9b667f33f9a0297b0b1b09909240dcc1269/cellprofiler/gui/pipelinecontroller.py#L3020) for groups. I tried it and it seems to work.

**Comment by braymp** [comment]
Ah, but if the list requires scrolling, the item is indeed selected but you have to scroll to find it; the default listbox view appears to be the top of the list. What I was thinking was having the view itself centered on the (already) selected item, wherever in the list it may be.

**Comment by LeeKamentsky** [comment]
OK will do now, sorry misread it.
