### ISSUE TITLE
Ilastik integration documentation

### ISSUE THREAD

**Issue by nickholway** [CellProfiler/CellProfiler#1430]
http://www.cellprofiler.org/interfaces.shtml has a link to a page at the Ilastik site which 404s. The page has moved to http://old.ilastik.org/index.php?cat=Documentation&page=Cellprofiler - however the images are missing. Would it be a good idea to have this documented at cellprofiler.org?

**Comment by dlogan** [comment]
Indeed that is a fine idea.  We can at least update our link to the old documentation.  But in fact, I emailed the ilastik team about the broken image links ling ago (before they were "old" docs) and I don't remember hearing back.  

But I do know now that the ilastik team is not so interested in pre-1.0 development.  So the best for us, I think, is to push out our 1.0 interface, which is on the horizon.  Thanks!

**Comment by nickholway** [comment]
That'd be good. It also appears that the "Export Classifier" functionality wasn't ported over to Ilastik 1.0 (https://github.com/ilastik/ilastik/issues/770), so a native CP solution would probably work very well.

**Comment by dlogan** [comment]
Please see Lee's subsequent comments on the Github page you linked.  Plus the ilastik folks' response.  So yes, thanks, it's on our/their radar.

**Comment by nickholway** [comment]
Fantastic. Thank you and have a nice weekend.

**Comment by dlogan** [comment]
I fixed the cp.org website link to the ilastik docs, albeit the old ones.  The thumbnail links are broken, though we may be able to find them by searching the web with the filename (like [this](https://www.google.com/search?q=cp1__.png), ugh).

**Comment by 0x00B1** [comment]
Ilastik support has been dropped.
