### ISSUE TITLE
Replace utf16encode and utf16decode?

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1431]
Could we replace our encoding methods ([utf16encode](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/utf16encode.py#L16) and [utf16decode](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/utf16encode.py#L42)) with [str.encode](https://docs.python.org/2/library/stdtypes.html#str.encode) and [str.decode](https://docs.python.org/2/library/stdtypes.html#str.decode)?

**Comment by LeeKamentsky** [comment]
I think personal ignorance at the time. Go for it - it was a mistake.

**Comment by AnneCarpenter** [comment]
Removing 'discussion' because it sounds settled - in fact, it might already be completed?

**Comment by mcquin** [comment]
Duplicated by #2539
