### ISSUE TITLE
Singleton?

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1432]
Is the Singleton [module](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/singleton.py) still used? If so, where? It looks like a leftover.

**Comment by LeeKamentsky** [comment]
For a brief time, ImageJ was accessed via a TCP API that ran its code out-of-process on the Mac. Singleton is from that era and is no longer used.

**Comment by 0x00B1** [comment]
> For a brief time, ImageJ was accessed via a TCP API that ran its code out-of-process on the Mac. 

:astonished:
