### ISSUE TITLE
Refactor Rules module into FilterObjects module 

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1433]
Presently, the [Rules module](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/rules.py) is used by one module, [FilterObjects](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/filterobjects.py).

We should refactor Rules into the FilterObjects module.

**Comment by braymp** [comment]
I think FlagImages uses it too? https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/flagimage.py

**Comment by 0x00B1** [comment]
@braymp oops!

**Comment by AnneCarpenter** [comment]
Seems ok to close this issue @0x00b1 ?
