### ISSUE TITLE
Use skimage.morphology.watershed

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1434]
[scikit-image](http://scikit-image.org/) has a [watershed implementation](http://scikit-image.org/docs/dev/auto_examples/plot_watershed.html).

We should use scikit-image’s implementation to improve inter-operate with Python numerical and scientific libraries NumPy and SciPy.

**Comment by braymp** [comment]
There's a (possibly) relevant note on this in the cellprofiler-dev mailing list (dated 5/20/15)

**Comment by LeeKamentsky** [comment]
Theirs is ours and we recently did some work to align the two (a9bdaaf2747a7c786db1d494aea9312563b0c2ae). So yes, this is safe to take.

**Comment by 0x00B1** [comment]
Awesome

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/centrosome#15
