### ISSUE TITLE
Contribute cpmath.zernike to scikit-image

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1435]
An implementation of Zernike’s moments is missing from scikit-image’s [moment’s module](https://github.com/scikit-image/scikit-image/blob/fb66edd7530deb425eee6854db1e166ecd207823/skimage/measure/_moments.py).

We should contribute @LeeKamentsky’s [module](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/cpmath/zernike.py).

**Comment by LeeKamentsky** [comment]
:+1:

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/centrosome#14
