### ISSUE TITLE
Contribute FastEMD to scikit-image 

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1436]
A [FastEMD](http://www.ariel.ac.il/sites/ofirpele/fastemd/code/) wrapper is broadly useful.

Let’s extract [our wrapper](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/cpmath/fastemd.py) from cpmath and release the package on PyPI.

**Comment by LeeKamentsky** [comment]
An alternative is to contribute it to [scikit-image](http://scikit-image.org/) (https://github.com/scikit-image/scikit-image). Much of skimage consists of pieces of cpmath contributed to them and long-term, it would be beneficial to everyone to have our code reside there.

**Comment by 0x00B1** [comment]
Great

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/centrosome#13
