### ISSUE TITLE
remove objgraph

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1438]
Let’s use [objgraph](https://pypi.python.org/pypi/objgraph/2.0.1) from PyPI and remove contrib.objgraph.

**Comment by 0x00B1** [comment]
We can also remove [contrib.asizeof](https://github.com/CellProfiler/CellProfiler/blob/master/contrib/asizeof.py) since contrib.objgraph is its sole dependent.

**Comment by LeeKamentsky** [comment]
:+1:
