### ISSUE TITLE
Replace utilities.get_proper_case_filename

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1440]
We can replace [utilities.get_proper_case_filename](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/get_proper_case_filename.py) with:

```Python
import win32api

win32api.GetLongPathName(win32api.GetShortPathName(str)))
```

**Comment by LeeKamentsky** [comment]
Do we want to use os.path.normcase (and os.path.normpath)? I think I overlooked these when I wrote get_proper_case_filename.

**Comment by 0x00B1** [comment]
Yeah, that’s preferable.
