### ISSUE TITLE
Move ./cellprofiler/icons/*.png into artwork directory 

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1445]

**Comment by LeeKamentsky** [comment]
Code in   https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/icons/__init__.py needs update to point at new location (and imports need fixing).

**Comment by 0x00B1** [comment]
No problem

**Comment by braymp** [comment]
When producing the manual, we run CP with the --help flag; it expects the icons to be in the icon folder (I think). You may want to check that this still works afterwards; the procedure for creating the manual is uber-lame but it's served us so far.
