### ISSUE TITLE
Retrieve prokaryote-*.*.*.jar during setup

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1448]

**Comment by 0x00B1** [comment]
@LeeKamentsky Where should the jar be located?

**Comment by LeeKamentsky** [comment]
Never a good solution for binaries - they always break py2exe when it puts everything into library.zip. I guess my choice is site-packages/cellprofiler/jars. I know we're not using py2exe going forward... it's someone else's problem if they do use it.

**Comment by 0x00B1** [comment]
What do you mean? This should replace the Maven build.

**Comment by LeeKamentsky** [comment]
Oh I thought you were asking where to put the .jar file in the cellprofiler package. Sorry, something other than that? The way you build it is great.

**Comment by 0x00B1** [comment]
I’m sorry! My reading comprehension is terrible today! :confused:

I was asking, what do you mean by “site-packages/cellprofiler/jars?”  Do you mean “CellProfiler/cellprofiler/jars?” Where does Cell Profiler expect to find jars? I know there’s an “imagej/jars” directory that’s created. Anywhere else?

**Comment by LeeKamentsky** [comment]
It expects them in imagej/jars from a list that's compiled as part of the maven pom (I think cellprofiler_dependencies.txt is it's name). But feel free to change. CellProfiler should preferentially load jars in the CLASSPATH environment variable.

**Comment by LeeKamentsky** [comment]
Also whatever jars are listed in javabridge.JARS

**Comment by 0x00B1** [comment]
OK, so:

1. download prokaryote-*.*.*.jar into CellProfiler/imagej
2. add  prokaryote-*.*.*.jar to the user’s classpath

Right?

I don’t feel awesome about modifying a user’s classpath.

**Comment by LeeKamentsky** [comment]
I would replace the code at [this if/else] (https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/cpjvm.py#L80) in utilities.cpjvm with

    jar_files = [os,path.join(imagej_path, <my jar>)]

I would also change [line 104](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/cpjvm.py#L104) to

    class_path = list(os.environ["CLASSPATH"].split(os.pathsep)) + class_path

to give users the opportunity to load their jars first.

`get_jars()` is called [here](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/cpjvm.py#L160) and the classpath is sent to the JVM [here](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/utilities/cpjvm.py#L173).

I wouldn't change the CLASSPATH environment variable.

**Comment by 0x00B1** [comment]
A starting point: https://github.com/CellProfiler/CellProfiler/pull/1484

**Comment by 0x00B1** [comment]
Ah. I see.

**Comment by 0x00B1** [comment]
I updated cpjvm.py with your suggestions.
