### ISSUE TITLE
Migrate wxPython to 2.9

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1486]
http://wxpython.org/migrationguide.php

- [ ] remove `wx.InitAllImageHandlers()`
- [ ] fix `wx.FlexGridSizer`
- [ ] fix `PrepareDC`

**Comment by LeeKamentsky** [comment]
Worth considering wx 3.0 (see pull request #1398).

**Comment by 0x00B1** [comment]
I agree. However, I think a an intermediary step makes sense.

**Comment by 0x00B1** [comment]
This has been resolved.
