### ISSUE TITLE
64-bit on OS X

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1487]
- [x] [Migrate wxPython to 2.9](https://github.com/CellProfiler/CellProfiler/issues/1486)

**Comment by LeeKamentsky** [comment]
Current blocker is issue #1486 (wx 2.8 does not support os/x x64, 2.9 or 3.0 does).
:+1:

**Comment by LeeKamentsky** [comment]
Should test the following:
* Open CellProfiler UI
* Insert the RunImageJ module (Edit/Add Module/Image Processing/RunImageJ)
* Press the button labeled "Show" at the bottom of the settings page.

**Comment by 0x00B1** [comment]
![64-bit](https://cloud.githubusercontent.com/assets/315821/9254138/de8e22c0-41af-11e5-97d5-89c94088249a.jpg)
