### ISSUE TITLE
JIRA [IMG-1028] implement visual programming a la pipeline pilot

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#150]
If I could make this future future future, I would.

Original reporter: klmadden
Jira link: https://jira.broadinstitute.org/browse/IMG-1028
Fix version: future
Assignee: leek

**Comment from anne on Tue, 22 Mar 2011 16:29:36 -0400:**
There are many alternatives to consider for this, which deserve massive amounts of debating prior to making Lee actually do anything.  For example, we could do the full visual programming route but could also make CellProfiler modules compatible with some other software that already has workflow structure (KNIME or pipeline pilot).  We could also do some less-disruptive changes to usability in the existing GUI, such as allowing collapse/expand of certain chunks of the pipeline (that is, enabling the creation of a sub-pipeline that can still be viewed in full detail). We could also simple allow a pipeline to save which settings are collapsed/expanded so that not all settings are presented to users when the pipeline is opened.

**Comment by dlogan** [comment]
More commentary here (https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-roadmap#problem-current-pipeline-view-renders-module-inputs-and-outputs-somewhat-obscure-for-new-users) but again, decided not to do this.
