### ISSUE TITLE
Trunk build page has error for old release builds

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1509]
http://www.cellprofiler.org/cgi-bin/trunk_build.cgi shows this error

```
No such file or directory: '/imaging/docs/People/Lee/cruisecontrol_win32/artifacts/CellProfiler_2_1_1' 
```

But regardless, shouldn't we just remove the "2.1.1 release candidate build" section since it's already been release for 1+ years?

**Comment by braymp** [comment]
The People folder was changed from "Lee" to "leek" out from under it :sob:

**Comment by AnneCarpenter** [comment]
MY FAULT!! I wondered how long it would take for anything to notice.

But really, something that our software depends on for building should not
be in someone's People folder :)

Anne


Anne E. Carpenter, Ph.D.
Director, Imaging Platform
Broad Institute of Harvard and MIT
415 Main Street,
Cambridge MA 02142

phone: (617) 714-7750
anne@broadinstitute.org
http://www.broadinstitute.org/~anne

**Comment by LeeKamentsky** [comment]
It stays as Lee - don't want to deal with fallout if it's not.
