### ISSUE TITLE
JIRA [IMG-1027] implement template matching

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#151]
- Create identify modules that work by template matching. (Good UROP project) We have many good projects as test cases, Wolthuis mitotic cells (ring shapes), Robbert Creton (zebrafish).  Benjamin Misselwitz donated code for this a few years ago (ask Ray to locate it).

Original reporter: klmadden
Jira link: https://jira.broadinstitute.org/browse/IMG-1027
Fix version: future
Assignee: leek

**Comment by AnneCarpenter** [comment]
Duplicate of #2261 so removing "future consideration" and leaving this issue closed.
