### ISSUE TITLE
Clarify Java requirements

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1511]
This [Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=14&t=4486) is asking about Java requirements, presumably for the 2.1.1 release.  Can anyone comment there on their CP/FIJI install issues?

Also, we should clarify on our downloads page what Java requirements are now (2.1.1) and going forward (2.1.2+). Can assign this to @dlogan or @braymp

**Comment by LeeKamentsky** [comment]
I commented. I forget how you're supposed to install Java 6 32-bit on Yosemite, hope someone else can help this user. I think it's you, David, because you're the Mac guy.

**Comment by dlogan** [comment]
I think he's on Windows?  He didn't really say outright, so I just asked.

**Comment by 0x00B1** [comment]
We just spent the past week fixing this. :)
