### ISSUE TITLE
Experiment table issues

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1515]
[This Forum user](http://cellprofiler.org/forum/viewtopic.php?f=14&t=4477) is having trouble with the Experiment table with the database.  I have not yet attempted to re-create, and they have a long explanation on the Forum, so I will not re-write here (sorry, it's not that helpful this time).

**Comment by LeeKamentsky** [comment]
I ran his pipeline on our database without any problems. I'm closing this, but feel free to reopen if user has problems after running on a fresh database with proper permissions.

**Comment by braymp** [comment]
Might have something to do with #1194?

**Comment by LeeKamentsky** [comment]
He's not using SQLite and he's making direct access of the database. Maybe it's a version issue, although it would have to be a very old database.
