### ISSUE TITLE
NULLs in database columns from LoadData

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1518]
I ran a pipeline with ExportToDatabase and many columns in the Per_Image table have all NULLs.

e.g. 
database = 2007_11_07_Hepatotoxicity_1
table = AssayDev_ilastik_WholePlate_Seeding_Per_Image

All the bad columns appear to come from the LoadData CSV.  But when the LoadData figure window pops up, all the metadata appears fine there, so it is being read into CP ok.  Hmm, this CSV used to work with this pipeline not long ago, or am I doing something stupid??

DEFAULT INPUT FOLDER: \\argon\imaging_analysis\2007_11_07_Hepatoxicity_SPARC\ilastik_CP_co-culture_METHODS_paper\file_lists
 
PIPELINE: http://cl.ly/463g3I1O2k3q

**Comment by dlogan** [comment]
P.S. Running locally, without CreateBatchFiles, and with a smaller CSV (\\argon\imaging_analysis\2007_11_07_Hepatoxicity_SPARC\ilastik_CP_co-culture_METHODS_paper\file_lists\File_list_ControlsOnly.csv) works fine and the metadata columns appear ok without all the NULLs.

**Comment by LeeKamentsky** [comment]
@dlogan Is this blocking your work? I'm working on it now, will keep it high-priority if so. Also, nice catch. Good thing the release didn't go out with this in it.

**Comment by dlogan** [comment]
I'm working around this, but yes, it is high priority for me, thanks.  

OK good, I checked over my Export settings 3 times and thought I was missing something.

**Comment by dlogan** [comment]
P.S.  A fairly quick test is to resubmit a single job from Batch 16 (http://imagewebrhel6/batchprofiler/cgi-bin/dev/ViewBatch.py?batch_id=16) and look in the corresponding database table for non_NULLs.  I aborted that run, as I noticed that it was still producing NULLs so the table is partially populated now. 

database = 2007_11_07_Hepatotoxicity_1
table = AssayDev_ilastik_WholePlate_Seeding_Per_Image

**Comment by LeeKamentsky** [comment]
I'm debugging it on Linux using a Batch_data.h5 that I created using the pipeline. It's a cacheing issue where CellProfiler prematurely gets the measurement columns and caches them before the default image directory is set. LoadData fails to load the CSV the first time through and reports that it has no measurements and that's cached and it never has a chance to correct itself.

A work-around would be to load the .csv in LoadData using an input data file location of "Elsewhere". Use \\argon\imaging_analysis\...\file_lists as the folder name.

**Comment by LeeKamentsky** [comment]
https://github.com/CellProfiler/CellProfiler/commit/3fdcb3216a1913e1dc7934de719b0f2d804d7e3c switched the behavior from changing the default input folder name to an absolute path to keeping it unmodified in order to support redirection of the default input and output files on the command-line.

My plan:
* In CreateBatchFiles, make sure that the Default_InputFolder and Default_OutputFolder experiment measurements are written.
* Make sure that these are used when in headless mode w/o the -i / -o switch
* Make sure that these are not used when in headless mode with the -i / -o switch

**Comment by dlogan** [comment]
Very much agree that DIF/DOF should be written, because otherwise project replication is difficult.
Or force LoadData to use Elsewhere... as DIF and DOF are possibly going away.
