### ISSUE TITLE
JIRA [IMG-1026] enable automatic adjustment of image processing pipelines to account for new image magnification

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#152]
We&#39;ll create a&quot;tool&quot; that allows user to automatically scale the parameters in an existing pipeline to adapt to a new magnification.

Original reporter: klmadden
Jira link: https://jira.broadinstitute.org/browse/IMG-1026
Fix version: future
Assignee: leek

**Comment from anne on Mon, 25 Apr 2011 17:42:25 -0400:**
A data tool, most likely.  We will need to seriously ponder which modules can be successfully size-translated and tell the user which modules have been translated and which ones must be dealt with manually, since we cannot guarantee every module can be adapted in this way.

**Comment by AnneCarpenter** [comment]
This would certainly be nice if it existed, but it would require constant vigilance to ensure every module knows which parameters are size-based, which is a maintenance burden and possible source of errors when (not if) we overlook some. It's not so terribly difficult to look at a pipeline and see which parameters have something to do with size, and adjust them manually. So, closing this.
