### ISSUE TITLE
MeasureObjectNeighbors: FIltered objects being treated the same as discarded objects

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1521]
The attached project file has two touching objects. One is filtered away, the adjacency stats measured for the remaining object. The output shows that the # of touching objects = 1, i.e., the removed object is still being used for adjacency.

Issue #363 (and the docs) say that "Objects discarded via modules such as IdentifyPrimaryObjects or IdentifySecondaryObjects will still register as a neighbors for the purposes of accurate measurement." In this case, the object was discarded with (a) a different module than those two, and (b) should be recognized as permanently gone for the purposes of MeasureObjectNeighbors. 

Attachments:
http://cellprofiler.org/issues/uploaded/e0km1N/issue.cpproj

**Comment by LeeKamentsky** [comment]
I think FilterObjects should create a "small_removed_segmented" segmentation (see https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifyprimaryobjects.py#L1004) that excludes the filtered objects but continues to include objects touching the edge.
