### ISSUE TITLE
JIRA [IMG-1025] Implement illumination correction using foreground segmentation

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#153]
first identify foreground objects using methods insensitive to illumination variation (what would those be exactly??)<br/>use mean intensities of objects and their locations across images to create the function<br/>use trimmed mean filtering as well as image by image rejection based on QC metrics to handle artificially bright outliers (debris)

Original reporter: klmadden
Jira link: https://jira.broadinstitute.org/browse/IMG-1025
Fix version: future
Assignee: leek

**Comment from anne on Mon, 25 Apr 2011 17:40:54 -0400:**
From the CP SW grant:<br/>&quot;We will implement new methods to handle well edges and nonlinear responses by first identifying<br/>foreground objects using methods that are insensitive to illumination variation. The mean intensities of<br/>these objects and their locations can be combined to find the illumination bias across a set of images,<br/>emphasizing accuracy for the foreground objects, but with accuracy elsewhere that is sufficient for<br/>segmentation purposes84. To handle outliers that contain artifactually bright signals, we will use robust<br/>estimation85 (e.g., trimmed mean filtering86), as well as image-by-image rejection based on quality-control<br/>metrics. These methods will be tested and provided as additional options in CellProfiler, along with<br/>guidance to the user as to which methods are appropriate under which conditions.&quot;<br/>

**Comment by AnneCarpenter** [comment]
It seems this will never be a high priority. Other illumination correction methods have superseded this, to boot.
