### ISSUE TITLE
Hang on Mac program close

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1536]
As reported by @jhung0 

```
open CP (2.1.2)
press the + button next to Adjust modules 
put something in the search box
press search 
close the window
close CP
```

My Crash Report is attached.

Attachments:
http://cellprofiler.org/issues/uploaded/UqmugJ/CellProfiler_2015-09-04-105930_wme3f-11a.hang

**Comment by LeeKamentsky** [comment]
oh sad it's simpler than that.
Open CellProfiler
Add the RunImageJ module
Quit CellProfiler (don't save project)

:skull: 
http://fiji.sc/2014-07-11_-_Fiji_won't_quit!
Issue #462

**Comment by 0x00B1** [comment]
Fixed
