### ISSUE TITLE
refactoring to avoid WX import

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1540]
Create a separate package of the UI components that depend on importing WX. These would include CellProfiler.py
cellprofiler/cellprofilerapp.py
cellprofiler/gui/*

Blockers on this:

cellprofiler/preferences.py:
Uses WX to save preferences to the Windows registry and similar for OS/X and Linux if not in headless mode. This can be changed to use platform-specific APIs directly. There is a wrapper on top of the WX calls so this is localized to a handful of functions.

cellprofiler.modules:
Modules can be run headless, but are currently allowed to import WX under the following circumstances (and this will need to be addressed):
* after checking cpprefs.get_headless()
* inside an override of handle_interaction, CPModule.display, CPModule.display_post_group or CPModule.display_post_run. These are called via TCP/ZMQ from the analysis worker to execute in the GUI.
* inside a method that is activated by the `DoSomething` setting. `DoSomething` translates to a button on the UI and it's activation method is only called in that UI context.
* inside CPModule.run_as_data_tool - this is only run in the UI and lets the user use the functionality of some modules outside of the context of a running pipeline.

The use cases:
* An optional message to be displayed to the user: e.g. [createbatchfiles.py:220](https://github.com/CellProfiler/CellProfiler/blob/1350faccf8574766ccba2c4a6f88719c4983f38e/cellprofiler/modules/createbatchfiles.py#L220). This can be replaced with a method on the workspace, handled via the TCP/ZMQ reflection.
* Interactive modules: Some modules have a mode that lets the user supply input in the course of the pipeline run. For instance [crop.py:453](https://github.com/CellProfiler/CellProfiler/blob/1350faccf8574766ccba2c4a6f88719c4983f38e/cellprofiler/modules/crop.py#L453) displays an image and lets the user manually crop it. IMHO not a big fan because the workflow is clumsy to say the least and the user's actions are not reproducible. The code for EditObjectsManually has largely migrated into cellprofiler.gui and maybe that is a good model.
* CPModule.run_as_data_tool - The data tools are designed to be used interactively. At their worst, e.g. MergeOutputFiles, they are only used interactively and the module framework is only there to let the user see the module's help.

Pragmatically, CellProfiler can always run a module without WX unless the module is misconfigured to require user interaction.

celllprofiler.pipeline:
[line 404](https://github.com/CellProfiler/CellProfiler/blob/1350faccf8574766ccba2c4a6f88719c4983f38e/cellprofiler/pipeline.py#L404) This is dead code
[line 1015](https://github.com/CellProfiler/CellProfiler/blob/1350faccf8574766ccba2c4a6f88719c4983f38e/cellprofiler/pipeline.py#L1015) This should be handled via some sort of callback or exception and is protected by a check for headlessness. 
[line 2011](https://github.com/CellProfiler/CellProfiler/blob/1350faccf8574766ccba2c4a6f88719c4983f38e/cellprofiler/pipeline.py#L2011) I wish it were dead code. The progress dialog could be hooked to the callback mechanism that supports it.

[To be continued]

**Comment by 0x00B1** [comment]
Completed (this issue has a lot of useful information should be added to the wiki)
