### ISSUE TITLE
NamesAndTypes: "Next image group" ignores color/grayscale type

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1545]
To replicate, do the following:
- Load the attached project: Loads color image as grayscale, does simple grayscale-based operation
- Enter test mode
- Step: module executes successfully
- Test menu item > Next image group
- Step: module fails with the msg:

```
Traceback (most recent call last):
  File "D:\Trunk\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2813, in do_step
    self.__pipeline.run_module(module, workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 2059, in run_module
    module.run(workspace)
  File "D:\Trunk\CellProfiler\cellprofiler\modules\graytocolor.py", line 259, in run
    must_be_grayscale=True)
  File "D:\Trunk\CellProfiler\cellprofiler\measurements.py", line 1643, in get_image
    raise ValueError("Image must be grayscale, but it was color")
ValueError: Image must be grayscale, but it was color
```

Attachments:
http://cellprofiler.org/issues/uploaded/pARG20/issue.cpproj

**Comment by braymp** [comment]
Seems like this occurs for "Next image set" within a group as well.

**Comment by dlogan** [comment]
I just got bit by this bug.  Very annoying, and hard to debug.  I thought the issue was with my images, but no, it was just using Test Mode. (I used Mac Beta from April, but I don't think it has been fixed since)

**Comment by jhung0** [comment]
For me, it occurs with next image group but not next image set

**Comment by jhung0** [comment]
It only happens in test mode, so the choice of grayscale is not persisting

**Comment by bethac07** [comment]
Probably fixed since not reported in 3 years, feel free to reopen if still an issue.
