### ISSUE TITLE
JIRA [IMG-1023] Adapt CP to use WNDCHRM

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#155]
1. New modules will subdivide an image into tiles, calculate feature sets from each<br/>tile, and train a classifier to discern positive and negative control images.<br/>2. We will also explore training classifiers on regions of interest (objects identified by CellProfiler&#39;s segmentation modules), rather than<br/>image tiles.<br/>3. We will evaluate the new methods using the IICBU test sets, whichwere gathered for this<br/>purpose<br/><br/>what about the CPA-whole-img-classification we&#39;re doing? doesn&#39;t this kind of override?

Original reporter: klmadden
Jira link: https://jira.broadinstitute.org/browse/IMG-1023
Fix version: future
Assignee: leek

**Comment from anne on Wed, 23 Nov 2011 08:17:50 -0500:**
The WND-CHARM team would be happy for us to create WND-CHARM-like functionality in CellProfiler.  A visiting student, Virginie Uhlmann, has begun work on the project.

**Comment by AnneCarpenter** [comment]
Virginie has finished this a while ago!
