### ISSUE TITLE
SSL certificate for cp.org

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1560]
From @braymp:
```
While looking at a weblink issue for Anne, I noticed that if you do the google search at the top-right of the page (e.g., search for "avi"), you get links that largely make sense but some that go to other pages @ Broad. E.g., 
https://www.cellprofiler.org/scientific-community/science/core-faculty-labs/regev-lab/regev-lab-home
https://www.cellprofiler.org/~fromer/
Is this a concern? 
```
Assigning to @0x00B1 for the meantime. 
Check whether IT can handle this for us, and/or what it takes to purchase a SSL certificate.

**Comment by 0x00B1** [comment]
Let’s wait a month or two for [Let’s Encrypt](https://letsencrypt.org). It’s a free, automated, and open certificate authority, run for the public’s benefit.

**Comment by 0x00B1** [comment]
This is an issue for the CellProfiler website.
