### ISSUE TITLE
RuntimeWarning: Mean of empty slice.

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1567]
``` sh
numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.

warnings.warn("Mean of empty slice.", RuntimeWarning)
```

**Comment by LeeKamentsky** [comment]
numpy.mean([]) returns NaN which is correct - investigate how to disable warning if numpy.mean([]) is designed to return NaN. If the behavior is inadvertent, create strategy to wrap.

**Comment by 0x00b1** [comment]
This was fixed a few months ago.
