### ISSUE TITLE
JIRA [IMG-996] Combine modules: EnhanceEdges and EnhanceOrSuppressFeatures

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#157]
Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-996
Assignee: leek

**Comment from anne on Fri, 18 Jun 2010 14:24:01 -0400:**
Might be most efficient to do all module-combining at the same time.  See<a href="https://jira.broadinstitute.org/browse/IMG-470"title="Investigate combining Crop and Mask modules into a single CropOrMask">IMG-470</a>and<a href="https://jira.broadinstitute.org/browse/IMG-875"title="Combine IdentifyPrimaryObjects and IdentifyObjectsManually">IMG-875</a>and<a href="https://jira.broadinstitute.org/browse/IMG-483"title="Combine ExportToDatabase and ExportToExcel into a single module">IMG-483</a>.

**Comment by AnneCarpenter** [comment]
While in my heart of hearts I think it's nice to have all "Enhance" functions in one module so users can choose among the options there, edge detection is a common computer vision task and different enough from the features in EnhanceOrSuppressFeatures that I'm willing to put this dream to rest; it doesn't warrant the work.
