### ISSUE TITLE
Why scale intensities between 0 and 1?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1572]
Marc Bickle brought this up during a brief chat, and I get the same question on occasion at workshops: why do we normalize pixel intensities between 0 and 1?

Pros:
* Aids portability, assuming that an images of different bit-depths really are comparable (but this breaks down in cases where the apparent bit-depth is misleading, e.g, 12-bit stored as 16-bit image)

Cons:
* Marc brought up that we may be paying a substantial memory overhead by storing numbers as doubles rather than integers.
* Not as intuitive to users coming from ImageJ/FIJI

@dlogan and I were a bit stymied as to where this convention came from; might be a legacy issue from the MATLAB days. I imagine that changing this behavior would be a colossal pain regardless.

**Comment by 0x00B1** [comment]
I don’t know. However, I can address the memory issue:

It isn’t substantial:

```Python
>>> import sys
>>> sys.getsizeof(1)
12
>>> sys.getsizeof(1.0)
16
```

Moreover, in NumPy:

```Python
>>> sys.getsizeof(numpy.float32(1.0))
12
>>> sys.getsizeof(numpy.float64(1.0))
16
```

While we should prioritize memory optimizations, numeric representations are minor.

**Comment by braymp** [comment]
For scalars, true, it's not a huge deal. But for numpy arrays of > 2k x 2k (typical), I imagine it adds up pretty quick...

**Comment by 0x00B1** [comment]
Oh, sure!

My point was a Python numeric has a 4-byte overhead so we’re trading memory for convenience regardless. Nonetheless, we should consider it!

**Comment by LeeKamentsky** [comment]
Is a legacy of matlab. It does add up - during the course of computation, calculations are done on 64-bit arrays so it's a factor of 8 for an image of uint8. A lot of it is to generalize all routines for the worst-case. At some point in a pipeline, there's usually a smoothing step or multiplication of two matrices. These operations would lose 1 bit accuracy (imagine having an array of uint8 going in and only even # uint8 coming out) and for convolutions, the error is larger.

I have a feeling that there would be little loss of information if the dtype that we used was np.float32. In some places in the code, I try to enforce this (e.g. when you put an image into the workspace, it's enforced if I remember right).

Short answer - float is used to avoid having to consider the sources of error during every calculation which results in less efficient, but less complex code and less chance of a bug resulting in losing information during the course of a calculation.

**Comment by 0x00B1** [comment]
[q]Is a legacy of matlab. It does add up - during the course of computation, calculations are done on 64-bit arrays so it's a factor of 8 for an image of uint8.[/q]

I don’t know. Let’s use concrete numbers:

[q]But for numpy arrays of > 2k x 2k (typical), I imagine it adds up pretty quick...[/q]

It’s a difference of 12 MB. Calculator.app allocates 16 MB on startup.

It’s a worthwhile optimization, but it’s minor when compared to other memory problems.

**Comment by 0x00B1** [comment]
I was curious about CellProfiler’s general-purpose memory usage. 

14 MB is allocated to “Show Welcome Screen.” :man:
