### ISSUE TITLE
Images module: Change highlight color for selected image

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1575]
Reported by @AnneCarpenter: When selecting an image in the Images module from source (00a8678) on a Mac, the dark background obscures the file name:
![image](https://cloud.githubusercontent.com/assets/1186440/9936158/a1594864-5d28-11e5-87dd-039c63c3ec82.png)

On Windows, the background is not quite as dark, but the foreground becomes light so you can at least see the filename.
![image](https://cloud.githubusercontent.com/assets/1186440/9936197/cbaf9b2c-5d28-11e5-9b85-5ca607427736.png)

**Comment by 0x00B1** [comment]
:+1:
