### ISSUE TITLE
Suggested changes to "About..." window

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1576]
Suggested by @AnneCarpenter: 
* Make the text in the ABout box selectable, so a user can copy/paste the Git hash to file a bug report.
* On her Mac, the About box is too big to fit on the screen. On my Windows, the box fits but initiallly extends off-screen (see screenshot). Perhaps make the About window resizeable/scrollable so it can fit on the screen.

![image](https://cloud.githubusercontent.com/assets/1186440/9936333/6e9b3e86-5d29-11e5-8781-e9a050627488.png)

**Comment by AnneCarpenter** [comment]
Right, "extends off-screen" describes the problem on the Mac, too,
especially if you click one of the buttons at the bottom which extends the
window further. It looks similar to Mark's screenshot on Windows.

**Comment by 0x00B1** [comment]
:+1:
