### ISSUE TITLE
wx3: Change background color for initial selection

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1579]
Running CP from source, using wx 3.0.2: When CP first appears, the bg color for the default selection of the Images module is light gray, so the text is barely visible. It appears that this is the color used for when a window loses focus.
![image](https://cloud.githubusercontent.com/assets/1186440/10024847/18d229ae-6127-11e5-96b2-bf24b899a079.png)
Actually selecting the module with a mouse click changes it to the usual color:
![image](https://cloud.githubusercontent.com/assets/1186440/10024911/69003f7e-6127-11e5-83f2-717924507d90.png)
May be related to #1575, and might be Windows-only.

**Comment by LeeKamentsky** [comment]
Hey mark, we both closed both duplicates. I'm opening this one.
