### ISSUE TITLE
Make wiki editable

### ISSUE THREAD

**Issue by purohit** [CellProfiler/CellProfiler#1583]
Hello,

I have some changes I'd like to make whenever I see an error or formatting problem in the Wiki. Furthermore, I just got Cellprofiler to build on our Ubuntu 14.10 server and want to create a writeup about how to do so for others, but I can't seem to edit or create Wiki changes. Can you please allow this? You have revision history so I don't think there's anything to worry about.

Thanks,
Ashwin

**Comment by 0x00B1** [comment]
@purohit No problem. Edit away! :smile_cat:

**Comment by purohit** [comment]
Thanks!

**Comment by purohit** [comment]
Just added the directions here: https://github.com/CellProfiler/CellProfiler/wiki/Installing-Cellprofiler-on-Ubuntu
