### ISSUE TITLE
Subplots should maintain approximately square aspect ratio/layout

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1584]
ClassifyPixels can have variable number of subplots/axes objects.  When there are many, it is hard to see the data.  I suggest that axes objects try and maintain a square aspect ratio. 
 
![screen shot 2015-09-24 at 2 41 26 pm](https://cloud.githubusercontent.com/assets/1225595/10083024/7de87376-62ca-11e5-9afb-a35ae80e9005.png)

Are there other modules this affects that have lots of subplots? Align?

**Comment by braymp** [comment]
Align does. So can CorrectIlluminateApply, depending on the # of images corrected.

**Comment by LeeKamentsky** [comment]
I think in general, I've tried to grid variable #s of images so they do grow in the vertical direction. Hopefully, ClassifyPixels is the only one that doesn't do this. If people find modules other than ClassifyPixels that have this problem, it's easiest for me if they file a separate issue for it.
