### ISSUE TITLE
Consider implementing Phansalkar local thresholding

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1587]
See https://github.com/stelfrich/imagej-ops/blob/7ef98f4101700213d49ac11184e4278f26b7a2bd/src/main/java/net/imagej/ops/threshold/localPhansalkar/LocalPhansalkar.java for an implementation in ImageJ and Phansalskar N. et al. Adaptive local thresholding for detection of nuclei in diversity stained cytology images. International Conference on Communications and Signal Processing (ICCSP), 2011, // 218 - 220 for the citation.

A local thresholding method based on a calculation done on the local mean and variance:

    # Phansalkar recommends k = 0.25, r = 0.5, p = 2 and q = 10
    img_mean = convolve(img, strel_disk(radius))
    img_stdev = sqrt(convolve((img - img-mean)**2, strel_disk(radius)))
    t = img_mean * (1 + p * exp(-q*img_mean) + k * ((stdev/r) - 1)

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/centrosome#17

**Comment by ahancock1** [comment]
I was trying to find an implementation of Phansalkar but couldn't find one in the end. Decided to write my own implementation which might be useful to include in your library. Unfortunately, i don't know enough about python to create a pull request.

Taken from https://it.mathworks.com/matlabcentral/answers/uploaded_files/23812/ICCSP_thresholding_2.pdf published by Neerad Phansalkar. Variables are the same as described in the paper and the implementation is written in c#


    public static Matrix Phansalkar(Matrix input, int radius)
    {
        var width = input.Width;
        var height = input.Height;

        var result = new Matrix(width, height);

        var p = 2;
        var q = 10;
        var k = 0.25;
        var r = 0.5;
            
        Parallel.For(0, height, y =>
        {
            var pixels = new List<float>();

            var index = y * width;

            for (var x = 0; x < width; x++)
            {
                var sum = 0f;

                for (var kx = -radius; kx <= radius; kx++)
                {
                    var px = x + kx;

                    for (var ky = -radius; ky <= radius; ky++)
                    {
                        var py = y + ky;

                        if (px >= 0 && px < width && py >= 0 && py < height)
                        {
                            var value = input[px, py] / byte.MaxValue;
                            pixels.Add(value);
                            sum += value;
                        }
                    }
                }

                var count = pixels.Count;
                var m = sum / count;
     
                sum = 0;
                for (var i = 0; i < count; i++)
                {
                    var value = pixels[i] - m;
                    sum += value * value;
                }
                sum /= count;
                var s = sum / sum;

                var threshold = m * (1f + p * Math.Exp(-q * m) + k * (s / r - 1));

                result[index + x] = input[index + x] / byte.MaxValue > threshold ? byte.MaxValue : 0;

                pixels.Clear();
            }
        });
            
        return result;
    }`

Matrix is a 1D array with a 2D indexer. p, q, k, r are constants from the paper. s is local standard deviation and m is local mean.

**Comment by penghongkwek** [comment]
Is there a working Phansalkar threshold function written in Python ?
