### ISSUE TITLE
Allow drag-drop of pipeline files with any extension

### ISSUE THREAD

**Issue by shntnu** [CellProfiler/CellProfiler#1588]
This will allow users to upload pipelines as .txt files. 
E.g. 
[analysis.cppipe.txt](https://github.com/CellProfiler/CellProfiler/files/2595/analysis.cppipe.txt)

**Comment by AnneCarpenter** [comment]
How would a person come into possession of such a file? Is this common? @shntnu

**Comment by AnneCarpenter** [comment]
(and is "any extension" really a good idea or do you think adding .txt suffices?

**Comment by 0x00b1** [comment]
I love you @shntnu, but I don’t know if this is worth implementing …
