### ISSUE TITLE
JIRA [IMG-980] Image Tools: Image profile across a line

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#159]
See this post:<a href="http://cellprofiler.org/forum/viewtopic.php?f=16&t=977">http://cellprofiler.org/forum/viewtopic.php?f=16&t=977</a><br/><br/>This would probably be a good idea to add to the image tools menu: Enable from menu item, click on image brings up cpfigure with intensity profile across a line (both along x and y), successive clicks update the same graph

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-980
Fix version: next
Assignee: afraser

**Comment by braymp** [comment]
Suggested by Marc Bickle. Changing to future-sooner since I'm thinking it's not too hard to do? Maybe incorporate in workspace viewer.

**Comment by LeeKamentsky** [comment]
Not so hard. I'm thinking you could do something super-cool like drawing dotted lines for the axes, going through the x-y position and differently dotted lines along the axes for the intensities (imagine the intensity plot on top of the horizontal or down the side of the vertical axes). A little bit of a problem if you do that at the top or bottom of the image, (and you could offset the graph to account for it maybe), but the advantage is that you don't need to pop up a different display and the position of the intensity graph corresponds to the pixel underneath the axis.

**Comment by dlogan** [comment]
Nice idea!  But that restricts the measurement to horizontal and vertical lines, if I understand you.  I suppose that's ok for most uses?

**Comment by dlogan** [comment]
P.S.  I think Marc Bickle said "draw a line" so I assumed plotting the intensity histogram of any random curve of any length is what he was thinking of.

**Comment by braymp** [comment]
I imagine that an arbitrary curve would be optimal, but a line segment in whatever direction (like the distance measurement tool does now) would cover most cases.
