### ISSUE TITLE
More useful message if no image sets created

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1594]
We may not be able to point a novice user to exactly why image sets can't be created, but we can at least provide better suggestions than the current "Check the Input modules". Perhaps a few tips in order of likelihood. 

Initial thoughts:
- "We suggest checking NamesAndTypes first, to confirm the channel selection. If you are extracting Metadata, check that next."

**Comment by AnneCarpenter** [comment]
I think the section of code where this would be addressed is in imagesetctrl.py:
https://github.com/CellProfiler/CellProfiler/blob/34600c3bcc856937fa96ca4bc3feb92a4b4732f9/cellprofiler/gui/imagesetctrl.py

           wx.MessageBox(
                    "Sorry, your pipeline doesn't produce any valid image sets "
                    "as currently configured. Check your Input module settings, "
                    "or see Help > %(CREATING_A_PROJECT_CAPTION)s for additional assistance "
                    "on using the Input modules." % locals(),
                    caption="No Image Sets Available",
                    style=wx.OK | wx.ICON_INFORMATION,
                    parent=self)

It already points to extensive documentation so it seems you want to just put the top one or two tips here. Is the text you wrote exactly what you'd like? Any other common things to mention?

**Comment by braymp** [comment]
Ugh, I wouldn't mind if @karhohs and @bethac07 weigh in on this one. I have to admit, the times when I run into this error, it's for a reason not solvable by these tips :smile:

**Comment by bethac07** [comment]
Having Groups enabled but not defining them properly is another one that causes this one, or NamesAndTypes using Metadata to group images (but doing it poorly).  

Maybe something like
-Check that all channels are defined correctly and all images are assigned a channel in NamesAndTypes
-If extracting Metadata, make sure all the metadata extracted are unique and that none of the values you expected are being returned as None 
-Make sure the groupings in NamesAndTypes and any options you may have used in Group are correctly configured

**Comment by mcquin** [comment]
Beth wrote a nice blog post. Let's link to it. https://blog.cellprofiler.org/2017/01/09/help-why-does-cellprofiler-say-it-cant-find-any-valid-image-sets/

**Comment by AnneCarpenter** [comment]
Seems @jhung0 is working on this one here https://github.com/CellProfiler/CellProfiler/blob/issues/1594/cellprofiler/gui/imagesetctrl.py

**Comment by AnneCarpenter** [comment]
@jhung0 I've not pondered this issue but the last msg indicates you are doing something about it... we can take over if you have a status report or understanding of what needs to be done?

**Comment by mcquin** [comment]
Resolved https://github.com/CellProfiler/CellProfiler/pull/2775
