### ISSUE TITLE
Window appears blank

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1598]
On Mac at least, the Morph module window appears blank at first and with a too-tall aspect ratio.  Once you resize it, then the images appear. 

Attachments:
http://cellprofiler.org/issues/uploaded/S6hMmo/DLtest.cpproj

**Comment by dlogan** [comment]
Actually now that I look at the screenshot, it is simply way too tall.
![screen shot 2015-09-25 at 1 24 44 pm](https://cloud.githubusercontent.com/assets/1225595/10107582/177ddcfa-638a-11e5-8960-490086fa9a80.png)

**Comment by LeeKamentsky** [comment]
Mac only, may be related to #1593

**Comment by 0x00B1** [comment]
Fixed
