### ISSUE TITLE
JIRA [IMG-963] MeasureNeuron graph should capture alternate paths

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#160]
The graph output should contain two edge measurements if two branchpoints are connected by two edges without any intervening points of interest in order to capture the topology of a loop between the two points.

Original reporter: leek
Jira link: https://jira.broadinstitute.org/browse/IMG-963
  (Original JIRA has attachments.)
Fix version: future
Assignee: leek

**Comment from leek on Tue, 1 Jun 2010 14:53:19 -0400:**
Currently, we only capture the length of edge 2 from point A to B, but we&#39;d like to capture edge 1&#39;s length as well, so we can capture the knowledge that A&amp; B are on a loop.

**Comment by AnneCarpenter** [comment]
Closing until someone finds a sufficient number of desperate biologists who want this feature.
