### ISSUE TITLE
CellProfiler fails and exits with an error code of 0

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1603]
CellProfiler should exit with a negative error code if it fails. Running CellProfiler headless with the -p switch, using the file, http://broadinstitute.org/~leek/bpissue6/Batch_data.h5, will recreate the problem.

**Comment by braymp** [comment]
@0x00B1: Is this and #2160 part of 2.2.0?

**Comment by 0x00B1** [comment]
@braymp 2.4.0
