### ISSUE TITLE
RuntimeError: Failed to start Java VM

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1611]
I raised the Java heap allocation in Preferences to 4000 MB (I am loading some big nd2 image stacks) and ran out of heap space).  Then on launch of the Dev CP on Mac, I got this RunTimeError:

```
[dlogan@wme2f-11a:~]$ /Users/dlogan/github/CellProfiler_dev_python.command ; exit;
Updating Java dependencies using Maven.
running build_ext
skipping '_cpmorphology2.c' Cython extension (up-to-date)
skipping '_watershed.c' Cython extension (up-to-date)
skipping '_propagate.c' Cython extension (up-to-date)
skipping '_filter.c' Cython extension (up-to-date)
skipping '_lapjv.c' Cython extension (up-to-date)
skipping '_convex_hull.c' Cython extension (up-to-date)
skipping '_fastemd.cpp' Cython extension (up-to-date)
Error occurred during initialization of VM
Could not reserve enough space for object heap
Failed to create Java virtual machine.

Traceback (most recent call last):
  File "/Users/dlogan/github/CPhomebrew/Cellar/cellprofiler-dev-python/1/cpdev/lib/python2.7/site-packages/javabridge/jutil.py", line 222, in start_thread
    vm.create_mac(args, RQCLS)
  File "_javabridge.pyx", line 638, in _javabridge.JB_VM.create_mac (_javabridge.c:6184)
RuntimeError: Failed to create Java VM. Return code = -4
Failed to create Java VM
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/CellProfiler.py", line 987, in <module>
    main(sys.argv)
  File "/Users/dlogan/github/CellProfiler/CellProfiler.py", line 200, in main
    cp_start_vm()
  File "/Users/dlogan/github/CellProfiler/cellprofiler/utilities/cpjvm.py", line 174, in cp_start_vm
    max_heap_size = heap_size)
  File "/Users/dlogan/github/CPhomebrew/Cellar/cellprofiler-dev-python/1/cpdev/lib/python2.7/site-packages/javabridge/jutil.py", line 259, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
logout
```

(Assigning to Allen, but feel free to re-assign to Lee.)

**Comment by LeeKamentsky** [comment]
I am guessing you are still running the 32-bit version. If so, please close this, it's the expected behavior.

To find out how many bits, run the following:

    python -c "import sys;import math;print math.log(sys.maxint)/math.log(2) + 1"

**Comment by dlogan** [comment]
```
$ python -c "import sys;import math;print math.log(sys.maxint)/math.log(2) + 1"
64.0
```

HOWEVER, I use a script to start CP:
```
#!/bin/bash

source ~/github/CPhomebrew/bin/activate-cpdev
pythonw32 ~/github/CellProfiler/CellProfiler.py
```

I'm guessing the '...w32'  means what I think it means ;) oops

But the instructions for Dev Mac here
https://github.com/CellProfiler/CellProfiler/wiki/Cellprofiler-developer's-version-installation-for-Mac
still state that 'pythonw32' is the way to start CP.  How *should* I launch it?

**Comment by LeeKamentsky** [comment]
These are @0x00B1 's instructions for installing what you'll need for 64 bits: https://github.com/CellProfiler/CellProfiler/wiki/OS-X-Installation. I can't see the MySQL install on that page - I'd ask Allen if there are updated instructions if you need ExportToDatabase.

**Comment by dlogan** [comment]
Right -- @0x00B1 should I update what I thought were the most current Mac Dev install wiki instructions https://github.com/CellProfiler/CellProfiler/wiki/Cellprofiler-developer's-version-installation-for-Mac with yours https://github.com/CellProfiler/CellProfiler/wiki/OS-X-Installation ?

Perhaps it's best if I try Allen's install method (on top of my existing?) next week and then I can better assess how to update the wiki instructions.  Then I should be able to close this issue.

**Comment by 0x00B1** [comment]
@dlogan was this resolved?

**Comment by 0x00B1** [comment]
(It works for me)

**Comment by dlogan** [comment]
Probably solved, but I'll re-open if it occurs again
