### ISSUE TITLE
Create a CP "Safe Mode"; or a clear Prefs tool

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1612]
Just now #1611 I got into a bad place in which I couldn't start Mac CP Dev unless I cleared the Preferences.  I did 
```
mv ~/Library/Preferences/CellProfilerLocal.cfg ~/Library/Preferences/CellProfilerLocal.cfg.OLD
```
which worked, but I couldn't see another way around that.

This happens to users on both Mac and Windows (where they have to clear the Registry setting for Cellprofiler.cfg http://cellprofiler.org/forum/viewtopic.php?f=14&t=806#p6493) frequently enough to get a post on the forum every few weeks it seems.  It would be useful to have a simple way to start CP in a "Safe Mode" which did not access the possibly corrupt or otherwise badly configured Preferences.

**Comment by LeeKamentsky** [comment]
Work-around is to set the memory size from the command-line:

    python CellProfiler.py --jvm-heap-size=256K

And deleting the preferences is a good work-around too. On Windows, you can have your installer install multiple applications, on OS/X, not possible I think. The most bullet-proof solution might be for CellProfiler to have a flag in the registry, "StartedSuccessfully". On startup:

* CellProfiler checks to see if it's going to start the UI.
* If headless, continue (can't mess with the registry if headless)
* If GUI
 * Check status of the "StartedSuccessfully" flag
 * If 0, ask user if they want to start in safe mode or clear the registry and do that
   * If 1, set it to 0
    * Start CellProfiler
    * When UI is up, set it to 1

**Comment by dlogan** [comment]
Thanks - the command-line workaround is good, but I really like the 'deleting preferences' registry flag addition too.
