### ISSUE TITLE
JIRA [IMG-951] Selective removal of objects and/or measurements

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#162]
This JIRA is inspired by this forum post:http://cellprofiler.org/forum/viewtopic.php?f=17&t=954

Two ideas:
* Expand ConserveMemory to remove objects of choice<br/>I&#39;m not sure what should happen to any associated measurements made prior to removal. Probably retain the object measurements, but if the removed objects are requested for downstream operations, throw an error.
* Give the user the option of what measurements to make for a given measurement module<br/>I imagine this would be like the measurement column selection tool in ExportToSpreadheet. The user could always select the specific measurements at the export stage, but I assume that measurement selection at the measurement module stage could help with memory and/or speed issues, especially if the user doesn't really need all those extra measurements.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-951
Fix version: future
Assignee: leek

**Comment by leeleavitt** [comment]
This needs to be done  i have a 3042 image frames and close to 3000 objects per image that only need a mean measurement.  Currently this takes an hour an a half to extract my data.

Should i start looking into the source code to develop a solution or has anyone fixed this?

**Comment by AnneCarpenter** [comment]
Can you clarify your issue? You are saying your analysis works but it's slower than you would like? 

- Post the pipeline to the forum - maybe someone will have a tip to streamline it. Or a suggested setting that is more time-consuming than an alternative.
- Make a custom Measure module that strips out all the features you don't want to measure - but before doing this I'd suggest checking what is taking the majority of the  time in your pipeline. I *think* either the per-Image or per-Experiment output file/spreadsheet records time spent per module. It can be a bit non-accurate in certain cases, but may point out to you where the pipeline is taking the most time. It may not be measurements at all.

**Comment by leeleavitt** [comment]
Hi Anne!  This is the [link](http://forum.cellprofiler.org/t/video-processing/3974/5) to what i have been working through on the help forum. 

this is my [pipeline] (https://drive.google.com/open?id=0B2ZhBPx5YIq3VmNuRElZZEFoZlU)
this is my [video file cropped] (https://drive.google.com/open?id=0B2ZhBPx5YIq3V2FSNm11SDNLaG8). I usually have a 3000 frame movie to analyze
And here is my [ROI](https://drive.google.com/open?id=0B2ZhBPx5YIq3Tmp1LVNWOTFMRzQ) i am using

The command line indicator says
MeasureObjectIntensity takes .46/sec
ExportToSpreadsheet takes .00 sec
The NamesandTypes module takes 1.46/s

Currently i'm looking at the  processing, and it claims that i am performing at 2744images/87minutes which is only 24 images/minute or less than .4 images/second.  

sidenote: while observing the command line indicator, this process seems to be taking the longest at Worker Starting Job, which doesn't have a time associated with it.

**Comment by AnneCarpenter** [comment]
Ah, thanks - it is indeed useful to tell us if you've already posted for help elsewhere  so we don't waste time repeating what others have thought of already. Given that measuring is taking less than 1 sec per image it doesn't seem that solving this particular Github issue is going to speed things up for you.

**Comment by leeleavitt** [comment]
It might.  I'm suspecting if i only gather the needed measurement i can drive that number down to 
MeasureObjectIntensity -> .00/sec

So, if this can be done, then i can export my image data at 2 images/second!  

Someone mentioned using LoadData instead of NamesType
Using LoadData module takes .5 seconds/image

So, instead of a rate .4 images/second taking 2 hours for 3000 images
I could potentially drive that down to 
2 images/second taking 25 minutes for 3000 images

**Comment by AnneCarpenter** [comment]
I see, sounds good!  This improvement definitely will not happen so keep us posted if you poke into the code and adjust the module.

**Comment by bethac07** [comment]
I'm afraid you're mistaken- you're processing 2744images/87minutes _while running 8 images at a time_, which is 32 images/minute or 4 images/worker/minute.  Each image takes you 15 seconds of a worker's time, not 2.5, so removing 0.5 seconds will not produce a noticeable speed increase.  Just something to consider.  The command line indicator doesn't reference time spent on stuff under the hood.
