### ISSUE TITLE
Align: Implement aligning color images similarly

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1634]
The Align module can align two grayscale images w.r.t each other, but yields an error if a color is used for alignment, This is reasonable since alignment of color images is a trickier thing, but if I want to align a color image with the "Similarly" option, it should be straightforward to do: simply apply the same offset to all 3 channels.

**Comment by braymp** [comment]
This issue was moved to CellProfiler/centrosome#43

**Comment by LeeKamentsky** [comment]
All the code is in cellprofiler.modules.align
