### ISSUE TITLE
MeasureObjectNeighbors: VisibleDeprecationWarning

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1639]
The Travis build is showing a VisibleDeprecationWarning when running test_measureobjectneighbors:

/home/travis/build/CellProfiler/CellProfiler/cellprofiler/modules/measureobjectneighbors.py:437: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 2 but corresponding boolean dimension is 1
  distance_matrix[:, ~has_pixels] = np.inf

**Comment by mcquin** [comment]
Resolved by https://github.com/CellProfiler/CellProfiler/pull/1640
