### ISSUE TITLE
test_convertobjectstoimage: VisibleDeprecationWarning

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1641]
../home/travis/build/CellProfiler/CellProfiler/cellprofiler/modules/tests/test_convertobjectstoimage.py:174: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 224 but corresponding boolean dimension is 223
  ijv = ijv[~same, :]

Looks like an off-by-one error in the test code.

**Comment by mcquin** [comment]
Unable to reproduce.
