### ISSUE TITLE
test_enhanceorsuppressfeatures: VisibleDeprecationWarning

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1642]
From the Travis build:

.../home/travis/build/CellProfiler/CellProfiler/cellprofiler/modules/tests/test_enhanceorsuppressfeatures.py:351: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 20 but corresponding boolean dimension is 21
  image[i**2+j**2 < 23] = 1

in the test code, so does not affect CP.

**Comment by mcquin** [comment]
Unable to reproduce.
