### ISSUE TITLE
Table subplots sometimes disappear

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1643]
(I thought there was an Issue for this already, but I can't find it...)
On Mac at least, figure windows with tables, e.g. IdentifyPrimaryObjects, can have the tables disappear until they happen to be resized.  This has been an issue occasionally for awhile, but I think it happens more often lately (wx-related?) with recent trunk builds, like 2015_09_08.  

For example, this is what IDPrimary looked like zoomed out, with an invisible table:
![screen shot 2015-10-13 at 8 57 52 am](https://cloud.githubusercontent.com/assets/1225595/10455542/f6328b5a-7189-11e5-94e1-0d681a74cfed.png)
and then I resized the window slightly and it reappears:
![screen shot 2015-10-13 at 8 58 01 am](https://cloud.githubusercontent.com/assets/1225595/10455579/1cc8d850-718a-11e5-8808-fd52290407bb.png)

I have seen this numerous times, but I'm having trouble replicating this reliably :/

**Comment by AnneCarpenter** [comment]
Have you seen this lately, or been able to reproduce reliably?

**Comment by dlogan** [comment]
I have not seen this recently.  Closing.  Re-open if experienced again.
