### ISSUE TITLE
Measure branch lengths

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1647]
See https://github.com/CellProfiler/centrosome/pull/44. I've added code to compute the lengths of skeletonized labels. It should be straightforward to add a measurement of total neurite length per neuron and/or a measurement of average neurite length (take total length and divide by # of trunks).

@dlogan what do you think?

**Comment by dlogan** [comment]
That sounds great!  Simply adding these length parameters would be a boon.  One nice thing to add (or does it do this already?) is to keep the order of the branches in the graph structure.  This way we could compute a 'fast Sholl' analysis using the distances of the branches from their cell body and termini as described here:
https://paperpile.com/shared/xJGgTv

**Comment by LeeKamentsky** [comment]
My read of the paper is that the length of the neurite never factors into the equation - X(r) is the number of neurites that extend a radius of r from the soma. We already find all of the branchpoints, trunk points and end points so X(r) = trunk points + branch_points(R  <= r) - end_points(R <= r). We can't write X(r), but we can write measurements X(r) for some set of r.

I think that keeping track of the lengths between trunk, branch, and end and using that instead of radius could be more informative, though.
