### ISSUE TITLE
Trunk builds are not getting updated

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1648]
The trunk build page now has builds almost 6 weeks old, ~Sept 10: http://www.cellprofiler.org/cgi-bin/trunk_build.cgi 

I use this as my standard build for projects now, and need to have both Windows and Mac builds, so it's easier to use these than a developer's version for projects in "production".  Is it just a matter of pointing to the correct artifact, or is the master build too alpha for this use now?

**Comment by 0x00B1** [comment]
Master is solid. I suspect it’s a Jenkins issue. I’ll look into it.

**Comment by dlogan** [comment]
:+1:

**Comment by dlogan** [comment]
trunk builds (beta and nightly) are now moved to cellprofiler.org/releases
