### ISSUE TITLE
Dragging a .txt file list into Image window should populate file list

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1649]
Drag https://github.com/broadinstitute/CP_projects/blob/master/CRISPR_syn_Zhang/Main_pipeline.txt into an Images module's window and the file itself, rather than the contents, i.e. the image set list, get populated.  I believe this works properly for CSV files.

The .txt file was created by saving a project file with the Preferences set to save "Pipeline and file list", so it came straight from CellProfiler and therefore it seems to me that it should load straightaway too.

**Comment by dlogan** [comment]
Alternatively, change the behavior of the Preferences > "Save pipeline and/or file list..." setting to save a CSV rather than TXT.  Perhaps it's cleaner to just switch to one type of file list output.

**Comment by braymp** [comment]
Related to #676?

**Comment by dlogan** [comment]
Yup, related at least, thanks

**Comment by LeeKamentsky** [comment]
File / Import / File List will do this, so there is a work-around. There are enough corner cases (for instance, dragging in a bunch of files and one of them just happens to be a .txt file that you intended to filter out) to make me nervous about implementing this.
