### ISSUE TITLE
Provide solution for adaptive feedback microscopy

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#1650]
Often people want CellProfiler to be used for microscopy on the fly, where the results of analysis instruct the microscope what to do next. We want to document how this should be done and/or provide some code for bits of it. Several research groups have made it work in various ways.

Lee previously said, "pull-style utilization of CellProfiler should use the Knime bridge and ImageJ pipeline plugin to do it."

Our planned interface with MicroManager might be another route.

**Comment by braymp** [comment]
Some links to prior work:
* Tischer C, Hilsenstein V, Hanson K, Pepperkok R. "Adaptive fluorescence microscopy by online feedback image analysis." Methods Cell Biol. 2014;123:489-503 http://www.ncbi.nlm.nih.gov/pubmed/24974044
* https://github.com/VolkerH/MatrixScreenerCellprofiler

**Comment by LeeKamentsky** [comment]
See #1580. I think this is a duplicate. Feel free to re-open if not.
