### ISSUE TITLE
Drop-downs only select when you click the teeny down-arrow

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1651]
On Mac at least (Dev master, yes!), you need to click the little blue down-arrow to select the drop-down, rather than clicking anywhere on the text.
![image](https://cloud.githubusercontent.com/assets/1225595/10696323/179d62ae-7975-11e5-95e5-5106788ca3af.png)
This is a regression.

**Comment by 0x00B1** [comment]
You’re the best.

It’s also clipped. Here’s how it’s supposed to render:

![ok](https://cloud.githubusercontent.com/assets/315821/10699983/c14d9cac-7988-11e5-9f37-29542abfb015.png)

**Comment by dlogan** [comment]
Some do display and work properly, but in Images, e.g. the top-most one looks bad, but the rest are ok:

![image](https://cloud.githubusercontent.com/assets/1225595/11217078/957de350-8d1c-11e5-8095-5a286b60381b.png)

**Comment by 0x00B1** [comment]
Won't fix (this is a wx issue, unfortunately)
