### ISSUE TITLE
Preferences disappear when clicking Cmd-C

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1655]
In Mac Dev on master, open Python -> Preferences.  Click Command-C and the Preferences window disappears (I was trying to copy-paste a path). Command-V (paste) works ok.

**Comment by dlogan** [comment]
Related, this annoyance occurs:

- File -> Preferences
- Click any "?" help button
- Close the Help window by clicking "OK"
- The whole Preferences window closes 

Only the Help window ought to close.

(Reassign to @LeeKamentsky if more appropriate)

**Comment by 0x00B1** [comment]
Verified both issues

**Comment by 0x00b1** [comment]
fixed
