### ISSUE TITLE
Image intensity scaling Pref is not respected

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1657]
"Preferences > Intensity normalization" is set to normalize,   

![image](https://cloud.githubusercontent.com/assets/1225595/10733678/2a62290c-7bd6-11e5-9827-29144fca4772.png)

yet images displayed after double-clicking them in Images are always displayed in Raw

![image](https://cloud.githubusercontent.com/assets/1225595/10733728/60a119c4-7bd6-11e5-906a-9812a72bada6.png)

**Comment by LeeKamentsky** [comment]
Worked for me on the PC.

**Comment by LeeKamentsky** [comment]
Worked for me on the Mac too.

**Comment by dlogan** [comment]
Hmm, works for me now, too.  Not sure what happened, but will close, thanks.
