### ISSUE TITLE
JIRA [IMG-917] Allow changes to variable names to propagate down pipeline

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#166]
When an object/image name was changed in pipeline, the changes were propagated downstream (albeit often imperfectly). It would be nice to have this feature back in CP2.0<br/><br/>Note: should be done with visual element at the end of *Provider that activates when changes are made that invalidate a downstream Provider and offers to propagate the change.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-917
Fix version: next
Assignee: leek

**Comment by mcquin** [comment]
This can lead to surprising behavior. It isn't clear what should happen when a user accidentally renames a variable to an existing name.

**Comment by bethac07** [comment]
FWIW, this is a hugely common request at tutorials/forum posts/personal experience thing.  I agree it's not at all vital, but might be worth getting its `Future consideration` tag back.

**Comment by braymp** [comment]
Re: renaming to an existing name - CP actually permits duplicate names currently. The duplicates show up in drop-downs and CP somehow keeps them straight if you pick one over the other.
