### ISSUE TITLE
Add Boolean operators to FilterObjects with multiple filters 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1661]
[This Forum user](http://cellprofiler.org/forum/viewtopic.php?f=14&t=4549&p=13835#p13831) was having trouble filtering out objects that are both small AND round, but leaving intact small-non-round and big-round objects.  In other words, filtering out only a single quadrant of a truth table.  FilterObjects currently, as far as I can tell, does sequential filtering steps, and thus filters that require 'gatings' with multiple features that are all satisfied are not possible, except with more complicated pipelines.

It would be nice, and also clarifying for the user, to add boolean operators if more than one filter is set.  It could be done in the nice Images module format with the ITunes-style +/- buttons, or if that's too complicated, then a simple boolean chooser for the whole module would be fine, I think.

**Comment by braymp** [comment]
Same could be said for ClassifyObjects,
