### ISSUE TITLE
Docker builds failing

### ISSUE THREAD

**Issue by purohit** [CellProfiler/CellProfiler#1667]
Hello,

The last two months of cellprofiler builds here seem to be broken: https://hub.docker.com/r/cellprofiler/cellprofiler/builds/

Any idea as to why that might be?

Thanks,
Ashwin

**Comment by 0x00B1** [comment]
I accidentally broke them. I'll fix tomorrow. I apologize for the inconvenience!

**Comment by purohit** [comment]
Thank you! Much appreciated.

**Comment by 0x00B1** [comment]
@purohit I refactored and updated our Dockerfile. If you have a problem, please let us know with an issue on our new [docker](https://github.com/CellProfiler/docker) repository.

**Comment by purohit** [comment]
Thank you! I will likely try it today.
