### ISSUE TITLE
Improve MeasureGranularity column sort order

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1670]
[This Forum user](http://cellprofiler.org/forum/viewtopic.php?f=14&t=4562) is using the output of MeasureGranularity, but has noticed that the column sort order is not great.  The columns are presumably sorted alphabetically, however this results in a granularity sort order like:
MeasureGranularity_1_...
MeasureGranularity_10_...
MeasureGranularity_11_...
...
MeasureGranularity_2_...
MeasureGranularity_20_...
...
 i.e. not numerical in the second underscore-delimited field.

We could pad the number with zeros when exporting and then the sort order should be numerical, I think.

**Comment by LeeKamentsky** [comment]
That makes a certain amount of sense. There's a little bit of incompatibility if we change - updating CellProfiler will change the feature names. If that's not an issue, I can pad with zeros, using the range of the granular spectrum to figure out if I don't need to pad (range of granular spectrum < 10), need to pad to 2 digits (10 <= range of granular spectrum < 100), etc...

**Comment by dlogan** [comment]
Right, feature name changes and backwards compatibility... 
I'd say it's ok.  Thought on this, @braymp ?

**Comment by braymp** [comment]
I'm fine with it, if only b/c I'm certain MeasureGranularity is used so seldom. :smirk:

But then I was thinking of other modules with similar nomenclature, e.g., MeasureNeighbors. I'd be loathe to change that one.
