### ISSUE TITLE
LabelImages: Add numbering-to-character conversion

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1677]
Wow, this module might actually get some use....

When exporting the images from the PE Phenix, the file nomenclature is <code>r02c06f01p01-ch1sk1fk1fl1</code> where 'r' is the row index and 'c' is the column. Unfortunately, CPA does not recognize this format, so it would be great to have a way to convert it to the standard 'A01' format w/o updating the image table after the fact.

Labelmages is supposed to take care of this, but it appears to key off of the ImageNumber and it doesn't do the right thing if the images are not consecutive or do not start from the 1st well of the plate.  Perhaps settings can be added asking for which metadata correspond to row and column indices?

**Comment by LeeKamentsky** [comment]
It can be done - maybe others might use it. What's the priority on this?

**Comment by braymp** [comment]
Not super-high, perhaps in a month's time. We have a 140+ plate screen starting by end of Nov, probably the biggest QC I've had to do yet.

**Comment by dlogan** [comment]
(Ah yes, this is the one, thanks @braymp).  Ponder whether this is better handled in CPA, as detailed in the link above.

**Comment by braymp** [comment]
Yes, there's something to be said for that. I think I made the original CP
issue thinking that for those who use CP but not CPA, it might be more
generally useful.

**Comment by LeeKamentsky** [comment]
To upgrade:

    pip uninstall prokaryote
    pip install prokaryote
