### ISSUE TITLE
Crash in CP Mac 10.11.1

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1680]
Crash log and explanation here: http://cellprofiler.org/forum/viewtopic.php?f=16&t=4559#p13865

Or has this been fixed recently? If so, is there a new build we can send them?

**Comment by LeeKamentsky** [comment]
Steps to reproduce? Version #? I can't see anything useful in the stack dump.

**Comment by 0x00B1** [comment]
Won’t fix (cannot reproduce)
