### ISSUE TITLE
TrackObjects error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1681]
Running from Mac command-line.  See Forum post: http://cellprofiler.org/forum/viewtopic.php?f=16&t=4559&p=13870#p13866

Related to #1680

**Comment by LeeKamentsky** [comment]
I need a pipeline from the user. Asked for it on the forum.

**Comment by AnneCarpenter** [comment]
Does anyone know how to translate from old CP forum URLs to the new forum?

**Comment by mcquin** [comment]
Lost to time...
