### ISSUE TITLE
ij-patcher isn't being properly invoked

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1683]
Before prokaryote, ij-patcher.jar was invoked as a java agent (`-javaagent:ij-patcher=init` more or less). This patched imagej1 to be decidedly headless. This needs to be switched to work on prokaryote.jar instead.

**Comment by LeeKamentsky** [comment]
There's some logger info that indicates that ij-patcher is failing, so keep open still

**Comment by 0x00B1** [comment]
ImageJ support has been dropped.
