### ISSUE TITLE
Plate Viewer error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1684]
I was just trying Data Tools > Plate Viewer, and reading it's Help when the error below occurred.

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/CellProfiler-2.7.10/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16766, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/plateviewer.py", line 562, in update_figure
    offs[1]:(offs[1]+image.shape[1]), :] += image
TypeError: Cannot cast ufunc add output from dtype('float32') to dtype('uint8') with casting rule 'same_kind'
```
Images here: /Volumes/imaging_analysis/2015_06_25_CoxiellaPathogenesis_CharlieLarson_HeinzenLab_NIAID/CP_output/Dataset3_v1/outlines

Attachments:
http://cellprofiler.org/issues/uploaded/GxP8ov/PlateViewer_error.cppipe

**Comment by dlogan** [comment]
Using Mac Dev version: 320605c (current master)

**Comment by LeeKamentsky** [comment]
https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/plateviewer.py#L562

Change

    megapicture[offs[0]:(offs[0]+image.shape[0]),
        offs[1]:(offs[1]+image.shape[1]), :] += image

to

    megapicture[offs[0]:(offs[0]+image.shape[0]),
        offs[1]:(offs[1]+image.shape[1]), :] += image.astype(megapicture.dtype)

and see if it works - if it does, feel free to submit a pull request or I will get to it eventually.

**Comment by dlogan** [comment]
Works ok now! (With one caveat which I will make a new issue for)  Pull requested. Can close after that.
