### ISSUE TITLE
Image Browsing request

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1687]
It would be a nice, simple addition IMHO if we allowed a keyboard shortcut to navigate through images in the Images module, rather than having to double-click each one individually.  Of course, it would be great to have some sort of Zegami integration for image browsing, but CP does a great job of loading an image list, metadata extraction, auto intensity scaling, and I think one crucial missing step is a simple up-down arrow navigation to flip through the images quickly.  Possibly some sort of integration with the Workspace viewer or Plate Viewer might help here, but I think it would be helpful most expediently to have just a simple flipping through the image list.  

Also I suggest that the figure window be *reused* for this and not open a new window for each image.

Comments @shntnu @braymp ?

**Comment by braymp** [comment]
When I initially did the CP UI revision, I envisioned a figure window for flipping through image sets. So, :+1: from me.
