### ISSUE TITLE
Plate Viewer sash double-click problem 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1689]
If you double-click the sash in Plate Viewer (almost invisible dot to the right of platemap scheme) the platemap maximizes.  I don't how to return back to viewing the image thumbnails, other than restarting Plate Viewer. 

![screen shot 2015-11-04 at 9 30 32 pm](https://cloud.githubusercontent.com/assets/1225595/10958414/b247a2fe-833b-11e5-9ac4-92388bd545a8.png)
 
I'd be happy if the double-click functionality was just removed.

**Comment by LeeKamentsky** [comment]
Yuck. That behavior isn't my choice but there's always some way to change it - a spectrum ranging from setting a flag somewhere to intercepting a click event to rewriting the widget.

**Comment by dlogan** [comment]
I expected the sash to be at some far edge after (accidentally) double-clicking, so this behavior seems more like a bug somewhere.  Not a high priority though.
