### ISSUE TITLE
GC Overhead error

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1690]
Error on clicking Update in NamesAndTypes on a bunch of nd2 (stacked tiff) files:

```
Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 2146, in prepare_run
  File "cellprofiler\modules\metadata.pyc", line 741, in prepare_run
  File "javabridge\jutil.pyc", line 830, in call
  File "javabridge\jutil.pyc", line 797, in fn
JavaException: GC overhead limit exceeded
```

I had upped my java memory to 4096MB which got me through the Metadata extraction steps.  Do I have to just move to LoadData?  (Can I with nd2 files?) 

Pipeline and file list here: https://github.com/broadinstitute/CP_projects/tree/master/Coxiella

Related to #836

**Comment by LeeKamentsky** [comment]
Unfortunately, (as #836 says), I knew the memory consumption of the file UI would scale linearly with the number of frames meaning that there will always be an experiment that it can't handle. We can recapitulate OMERO and back the calculation with a database model (and OMERO has an order of magnitude more staff than us) or you can use LoadData. If you need a script to write the LoadData .csv, I can do that - the .csv can accept Series and Frame columns to pick out the individual planes and python-bioformats can read the .nd2 metadata and give you the correspondence between frame and image plane.
