### ISSUE TITLE
"Send report..." (really?)

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1697]
If "Send report..." really goes to /dev/null (or the equivalent), we should remove this.  Or utilize it.

![image](https://cloud.githubusercontent.com/assets/1225595/11215014/256c8de6-8d12-11e5-8568-8cef69c9419b.png)

**Comment by 0x00B1** [comment]
:+1:

**Comment by LeeKamentsky** [comment]
:+2:

**Comment by burgerga** [comment]
Some variations I'm currently getting:
    
    Failed to upload: [Errno 104] Connection reset by peer

and 

    Failed to upload, server reported code 405

so it's still not working as expected ;)

**Comment by LeeKamentsky** [comment]
We have shut down the server URL that processes this request, so the failure is expected. If you find any bugs, feel free to post an issue here or describe the problem on the CellProfiler forum.

**Comment by AnneCarpenter** [comment]
We need to remove the chunk of code that claims to report errors.

**Comment by mcquin** [comment]
#2404
