### ISSUE TITLE
Workspace viewer: (Sort of) odd color picker appearance.

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1699]
Not really a bug, but an oddity:

When you start the viewer, the color picker for selecting images looks like this:
![image](https://cloud.githubusercontent.com/assets/1186440/11215275/622e6c6c-8d13-11e5-97a2-37b72a9f3d8b.png)

If you add an image, and select a custom color (green in this case) , the color patch looks like this:
![image](https://cloud.githubusercontent.com/assets/1186440/11215338/a53b95c0-8d13-11e5-9267-9a34118ee250.png)

I think I'd prefer the patch to look like the latter. (In wx 2.8, the color patch looked like the latter too).

**Comment by AnneCarpenter** [comment]
Reasonable but not gonna happen soon :)
