### ISSUE TITLE
Dragging modules in pipeline window creates a copy rather than moves

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1701]
They used to move and not copy, which seems more intuitive.

**Comment by braymp** [comment]
Definitely not the case in Windows.

**Comment by AnneCarpenter** [comment]
I confirm this behavior in the April 18 beta on my Mac 10.10.5

**Comment by AnneCarpenter** [comment]
Confirmed it's still the case in 3.0.0rc3

**Comment by DavidStirling** [comment]
Can confirm this is still a Mac-specific issue as of 3.1.9, Windows is unaffected.

**Comment by bethac07** [comment]
I am reasonably sure we looked it up at one point this is a wx3 bug, not a CellProfiler bug.  Leaving open until we confirm it's fixed by wx4.
