### ISSUE TITLE
FilterObjects with Rules not working right

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1703]
This pipeline https://github.com/broadinstitute/CP_projects/blob/master/ilastik_CP_AssayDev/GroundTruth/Count_Ground_Truth_Compare_CPA.cppipe
applies the FilterObjects Rules and should recapitulate this CPA classification
![image](https://cloud.githubusercontent.com/assets/1225595/11250278/c3fbeac8-8df9-11e5-9e79-dd272d92ff94.png)

The first FilterObjects for fibroblasts looks right, but the second FilterObjects for hepatocytes misses lots of them relative to CPA.  The third FilterObjects works fine for Other.

The LoadData file list is here: https://github.com/broadinstitute/CP_projects/blob/master/ilastik_CP_AssayDev/GroundTruth/file_lists/File_list_full_with_GroundTruth.csv

**Comment by dlogan** [comment]
P.S.  This is what I get for hepatocytes (class 1 in Rules) using CP version 20150805
![image](https://cloud.githubusercontent.com/assets/1225595/11250470/971e968a-8dfa-11e5-8d51-1cf9b94e4954.png)
which is very different than the Hep in the CPA example image above

**Comment by LeeKamentsky** [comment]
Do you have links to the CPA database and training set? I want to be able to tell whether the problem is in the classification calculation or in the way FilterObjects reads the measurements.

**Comment by dlogan** [comment]
Sure, thanks:
db= 2007_11_07_Hepatotoxicity_1
db Tables = AssayDev_CP_only_Seeding_v2_Per_*
Training Set= https://github.com/broadinstitute/CP_projects/blob/master/ilastik_CP_AssayDev/CP_CPA/SeedingDensities/CP_CPA_IllumCorrInput_GHAD2-D6-20x/TrainingSet_DL_NoControls.txt

**Comment by LeeKamentsky** [comment]
The segmentations may be slightly different - I am not getting identical results using the trunk build to what you are seeing. For instance, object # 17 has an area of 959 for my run and one of 952 for yours and is not properly classified as a hepatocyte.   I have to postpone diagnosing this until I have time to figure out whether differences in calculations caused the problem or whether the problem occurs if the training is done using measurements from an identical version.

**Comment by LeeKamentsky** [comment]
There are other measurements that differ. I'm going to rig up a script to pull measurements from the database and run them through the same code that FilterObjects runs, then compare the results to CPA. That should tell me whether FilterObjects is at fault or whether something else is the cause.

**Comment by dlogan** [comment]
Thanks so much Lee.  I am using this for my paper revisions, so it's important to me.

**Comment by LeeKamentsky** [comment]
OK - the problem is that NaNs are being handled differently - in CPA, NaN means the rule fails and in CP, NaN means the rule succeeds. I think the hepatocytes often have no spots and the rules involving spots probably give weight to the fibroblasts. So things that would fail the rules (hepatocytes) were getting called fibroblasts. I will fix.

**Comment by dlogan** [comment]
Awesome debug work.  That potential cause wasn't in my thinking (ok, guessing) at all. Thanks!
