### ISSUE TITLE
MeasureNeurons settings bug?

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1704]
[This Forum user](http://forum.cellprofiler.org/t/measureneurons-bug/2552/3) pointed out what seem to be an extraneous ascii colon in his saved pipeline file in MeasureNeurons.  Is the colon character on line 124 of measureneurons.py extraneous?

**Comment by LeeKamentsky** [comment]
I suppose it's a matter of style. You can put colons in the setting text and they appear in the pipeline as 0x3A, so the user is wrong that it's a bug, but you're free to remove it.
