### ISSUE TITLE
Processing OMERO images in CP 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1706]
[This Forum user](http://forum.cellprofiler.org/t/processing-omero-server-images-with-cellprofiler/2461/9) is trying to debug loading and processing images straight from their OMERO server.  They had replied to earlier queries from Lee. Any comments?

**Comment by LeeKamentsky** [comment]
The thread, https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7821#p15817, indicates that another user was able to access the images using a setup that was largely identical to that of the reporter. If you look at that post, you'll see an image:
https://www.openmicroscopy.org/community/download/file.php?id=361&sid=c03392593815190ae897032c1a44b6f4

you'll see the user has a double colon `omero::iid` which would cause the problem they see.

**Comment by dlogan** [comment]
Great, thanks for looking at this Lee
