### ISSUE TITLE
JIRA [IMG-878] MeasureObjectIntensity, Relate: Implement user-contributions from forum

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#171]
From CP TODO:<br/># Anne 2008_11_12: Add the capabilities described in this [<a href="http://cellprofiler.org/forum/viewtopic.php?f=4&t=538&p=2071#p2071">http://cellprofiler.org/forum/viewtopic.php?f=4&t=538&p=2071#p2071</a>Forum post] to the appropriate CP module - finding center of the intensity for a subregion, and an alternate mode of relating objects.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-878
Fix version: future
Assignee: leek

**Comment by dlogan** [comment]
I think this is the post on the new Forum: http://forum.cellprofiler.org/t/new-modules-and-help-with-further-development/402
