### ISSUE TITLE
Provide credit to dependencies in binary versions of CP

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#1710]
Per Lee: The attributions are currently in the about box - there's a pretty comprehensive (but maybe not complete?) list. It even includes attributions for the icons. The python package attributions are hardcoded currently, an obvious place where we could improve (cellprofiler/gui/cpframe.py line 1005ish).

**Comment by 0x00B1** [comment]
Won't fix since the about dialog was redesigned
