### ISSUE TITLE
CorrectIlluminationCalculate: Wonky illumination function produced by median filtering

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1713]
The attached project computes the illumination correction function across a series of images. If you load the project, go into test mode, and step over CorrectIlluminationCalculate, the computed illumination function from the first image looks wonky.

The smoothing method is median filtering; I assume that there's some sort of edge effect that unavoidable? If this is expected behavior, the conditions under which it occurs would be good to document. 

Attachments:
http://cellprofiler.org/issues/uploaded/i0JYQY/issue.cpproj

**Comment by LeeKamentsky** [comment]
It looks like there's something wrong with very large filter sizes - the cutoff seems to be between 280 and 281 (see below). The median filter uses some integer arithmetic - int16's and such and it looks like you crossed the border and some value somewhere is overflowing. I will look into it further.

![280](https://cloud.githubusercontent.com/assets/660469/11373648/2e2fb6e4-92a1-11e5-881b-56c6762977fc.png)
![281](https://cloud.githubusercontent.com/assets/660469/11373675/43906e66-92a1-11e5-8826-be863cc81c4b.png)
