### ISSUE TITLE
Display window doesn't change image cycle #

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler#1722]
The subplot title has the image cycle # but the display top bar says image cycle # 1
![snip20151202_12](https://cloud.githubusercontent.com/assets/9591682/11548603/3016105c-992c-11e5-8231-40753f6c4c07.png)

**Comment by AnneCarpenter** [comment]
Note that the number 6 refers to the fact that this module is the sixth in the pipeline which is irrelevant to this issue. .. the issue is that it says number 1 at the top right but number 29 in the top left subplot.
