### ISSUE TITLE
Cannot download old Forum pipelines  

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1725]
(Sorry if this is not the best place for CP Forum admin requests, but it seemed the least worst place...)

[Users are complaining](http://forum.cellprofiler.org/t/cannot-download-pipeline-examples/1731/3?u=david_logan) that they cannot download older forum attachments, I believe the ones from before the migration.  I cannot either, and this is frustrating since so much 'history' is in our old pipelines on the forum.

Old attachments do not download successfully, e.g. the .cp and .cpproj files here http://forum.cellprofiler.org/t/problem-with-morph-module-after-import-from-cp-2-0/2317?u=david_logan
It appears to try and download, but the file is empty.

This thread may hold some clues: https://meta.discourse.org/t/wrong-file-extension-after-re-upload-of-duplicate-file/36285 and see especially the [last post](https://meta.discourse.org/t/wrong-file-extension-after-re-upload-of-duplicate-file/36285/8)
What *may* have happened in our case:
* The Forum was migrated to Discourse
* The old attachments did get ported ok, but certain extensions were not allowed at that time, including .cp and .cpproj (this doesn't quite make sense, since those restrictions are only for *down*loading files I thought)
* We subsequently allowed those extensions
* Now when a user clicks on an old attachment, the MD5 gets matched to the old file, and it perhaps falsely marked as an excluded attachment type, and does not allow download?  Again, I don't quite get it, but maybe is a clue

I did some tests:
(1) Re-uploaded an old .cp file that was previously on the forum here: http://forum.cellprofiler.org/t/test-upload-download-cp-file/2937
Try downloading this file and it is empty, as it must match the old MD5 file and for some reason is messed up
(2) I uploaded a .cp file that was NOT on the old forum here: http://forum.cellprofiler.org/t/test-new-cp-upload/2938 
This one downloads fine

**Comment by 0x00B1** [comment]
We should create a forum.cellprofiler.org to track forum issues

It sounds like we’ll need to re-migrate. Is this urgent? Can it wait a day or two until we’re finished with the 2.2.0 release?

**Comment by dlogan** [comment]
Good point, yes we can use the Staff category for Forum issues: http://forum.cellprofiler.org/t/about-the-staff-category/3. But we should be sure that all interested parties are "Watching" that category on the forum, I think, or be sure to tag folk.

Of all the Forum issues, yes, this is important. BUT nothing on the Forum is "urgent" per se :wink: .  So yes, it can certainly wait especially if we're that close to release.

**Comment by dlogan** [comment]
Moving to Staff category on Forum
