### ISSUE TITLE
GUI hidden upon launch

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1738]
When I launch Mac build 20151207, the window is not visible. Even when I use Expose ("explode windows")  the window is not there (or maybe minimized?).

![image](https://cloud.githubusercontent.com/assets/1225595/11895976/be57ed24-a550-11e5-95a8-075531c61876.png)

But then it appears when I click on the menu bar CP icon.

**Comment by 0x00B1** [comment]
Yeah, it’s annoying. If you click the icon in the dock, it’ll fix itself.

**Comment by 0x00b1** [comment]
I fixed this a few months ago. I really don't miss this bug.
