### ISSUE TITLE
JIRA [IMG-868] Image tools: Display image header info

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#174]
From CP TODO:<br/># Dlogan 2008_09_23: It would be a nice feature to add a button to the Image Tools context menu (i.e. when an image is clicked) that would display image header info from&#39;imfinfo&#39;, e.g. bit-depth, file mod date, width/height, colortype, filesize

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-868
Fix version: next
Assignee: afraser

**Comment by dlogan** [comment]
Closing now, for future consideration.
