### ISSUE TITLE
ExportToDatabase: Measurements not written out when separate tables selected

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1754]
Running the attached project file (in which the measurements are exported to separate tables) produces the requisite tables but with no measurements written. 

Attachments:
http://cellprofiler.org/issues/uploaded/NaWOqf/assay.cpproj

**Comment by DavidStirling** [comment]
Hosted file no longer exists and I've not been able to replicate this in current CP versions. Please re-open with further instructions if this is still a problem. Thanks!
