### ISSUE TITLE
For plugins to work, need to explicitly set plugins directory 

### ISSUE THREAD

**Issue by shntnu** [CellProfiler/CellProfiler#1756]
I created a plugin, dropped it into the plugins directory. It worked fine in test mode but not in analysis mode (plugin was not found)

I need to set the plugins directory through the UI (I set it to a new directory) and it worked fine.

OSX 10.10
CellProfiler 2.1.2 rev 8698682

**Comment by LeeKamentsky** [comment]
@0x00b1 says:
    Awesome
    We should probably use:
    $HOME/Library/Application Support/CellProfiler/

which would solve the problem if that were the default for OS/X. A 5 minute fix.
