### ISSUE TITLE
Slashes on plugins,ImageJ prefs folders not escaped on fresh install

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1759]
After a fresh install of 2.2.0rc2, I had a look at the preferences; it appears that the slashes for the plugins and ImageJ folders are not escaped. Other folders like the temp folder and DOF look fine.
![image](https://cloud.githubusercontent.com/assets/1186440/12299692/e3bcd896-b9e5-11e5-9d8f-a22a83445720.png)

**Comment by LeeKamentsky** [comment]
Hmmm... worked for me. You're not installing over an old version like 2.1.0? I installed over my old version and the directory names were preserved, then I deleted the entries, installed again and got the following:
![image](https://cloud.githubusercontent.com/assets/660469/12306437/bb01dc18-ba07-11e5-9580-765e31de8cb7.png)

**Comment by braymp** [comment]
Ah, that sounds like a reasonable explanation. I wonder if it will pose a problem for those who are upgrading? But in any case, I'd be more worried if the temp folder were affected this way than these two folders.

Closing...

**Comment by LeeKamentsky** [comment]
It was a problem for the last release too.
