### ISSUE TITLE
Windows install and missing JRE - better info

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1765]
Currently, the Windows binary installer for CellProfiler displays a message box if the installer doesn't detect the 64 bit JRE. It's confusing because if the user tries to install the JRE, they typically do it from a 32-bit browser and they get a link to install the 32-bit JRE and, after "installing" the JRE as they were told, the message box still reports that it can't find it.

We need a stable link to the JRE download. We can then either direct the user to download and install the JRE from the provided URL or we can offer to launch a browser to the URL. Investigate the HTML code for a Java plugin - there must be some alternate stuff in the plugin launcher that supplies the HTML UI that directs you to the (sadly 32-bit) download.

**Comment by dlogan** [comment]
I just felt the pain of this when installing CP Beta 2.2.0 on a Windows VM.  The dialog box just says something like "go to java.com and install Java"... but if folks like Christian Tischner [here](http://forum.cellprofiler.org/t/cellprofiler-beta-2-2-0-has-been-released/3194/4) and myself are having trouble, this needs addressing.

I'd suggest to at least add this to the dialog box:

0. Uninstall existing Java instances (necessary? JDK and/or JRE if existing? )
1. Install Java from here (hopefully link is stable enough for now): http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
2. Change JAVA_HOME which I had to do on a Win7 VM (If you are so oracular Oracle, Why can't you do this automatically??)  Any chance this be done programmatically, or at least guide the novice?

**Comment by jhung0** [comment]
I totally agree (same for CPA)

**Comment by braymp** [comment]
I went through a bit of this myself yesterday.
* Installing Java uninstalls prior versions now.
* Lee and I tried searching out a stable link to an Oracle download, but the needed to agree to the EULA made that impossible (there's an issue against this somewhere)

**Comment by LeeKamentsky** [comment]
The only step should be to install Java from the link. You shouldn't need
to uninstall the old instance and you should not have JAVA_HOME defined on
Windows. I can put the link into the instructions, but there's always the
possibility that the link will change. We could maintain a link to the JRE
at cellprofiler.org that would redirect to the current download page. We
could maintain the JRE binary on cellprofiler.org. We could go back to
packaging the JRE.

Perhaps we need to check whether the JRE at JAVA_HOME is suitable (64-bit /
Java 7 +). If so, probably best to make a separate issue for that. But
IMHO, we are second-guessing the user's intent and they shouldn't have set
JAVA_HOME in the first place.

**Comment by jhung0** [comment]
At least when I was trying to install JRE for CPA on my windows, it took a
lot of effort to change JAVA_HOME to the right thing

**Comment by 0x00B1** [comment]
Should we consider dropping Oracle for OpenJDK?

**Comment by bethac07** [comment]
Closed since we now package Java in again.
