### ISSUE TITLE
Classifier: Blank space left if drag/dropping an image tile

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1766]
While using a Classifier, I was doing the usual drag/dropping from the unclassified bin to the pos/neg bins. I noticed that in some cases when I dropped a tile, the remaining tiles in the unclassified bin didn't move over to fill the gap but instead left a blank space where the tile was. E.g. see screenshot (space where the 1st tile would be).

![image](https://cloud.githubusercontent.com/assets/1186440/12557568/707e4afe-c359-11e5-9294-ab35bc5f6785.png)

**Comment by LeeKamentsky** [comment]
Transfer to CPA repo?
