### ISSUE TITLE
Make a bigger window for Test menu > "Choose image set"

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1767]
The window created by clicking the menu "Test" (mode) > "Choose image set" is invariably too small.  I always resize it bigger in both dimensions. It's modal, so it should be a problem to be much bigger, and it would be cool to have it resize smartly, relative to the Main window GUI or the monitor. 

![image](https://cloud.githubusercontent.com/assets/1225595/12562692/851ed40e-c374-11e5-8f17-d2d923f20cd9.png)

**Comment by LeeKamentsky** [comment]
One possibility would be to have the size be persistent - when you resize, CP writes the new size to the preferences and when you reopen, CP sizes it to the size from the preferences. That keeps me from having to think too much about how big is too big just in case one of the fields is ginormous.

**Comment by dlogan** [comment]
:+1:
