### ISSUE TITLE
Occasional PyAssertionErrors with build from master

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1768]
I've been using the compiled 2.2.0 rc2 build (01ad695) and I've been getting occasional wx errors for various UI actions. Unfortunately, I don't have a workflow that replicates this but below is a msg I just got from selecting 'Hide all windows on run'

```
Traceback (most recent call last):
  File "cellprofiler\gui\cpfigure.pyc", line 502, in on_close
  File "wx\_core.pyc", line 12107, in Delete
PyAssertionError: C++ assertion "item" failed at ..\..\src\common\menucmn.cpp(455) in wxMenuBase::Delete(): invalid item in wxMenu::Delete
```

All such errors I've been getting are of the type <code>PyAssertionError: C++ assertion</code>

**Comment by LeeKamentsky** [comment]
It's going through the menu items associated with the figure and deleting them before the figure is destroyed. Most likely, they are already gone for some reason or another. I am having problems figuring out the sequence of events to reproduce as well.

**Comment by 0x00b1** [comment]
Fixed by wxPython upgrade
