### ISSUE TITLE
ExportToDatabase: Request/infer time-lapse related metadata for Tracer

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1776]
(Based on https://github.com/CellProfiler/CellProfiler-Analyst/issues/56)

Tracer needs a few cols which are currently guessed at/inferred. ExportToDatabase should write them into the properties file.

From https://github.com/CellProfiler/CellProfiler-Analyst/blob/cellprofiler-tracer/cpa/tracer.py, the following cols are needed.
* props.series_id = ["Image_Group_Number"]
* props.group_id = "Image_Group_Number"
* props.timepoint_id = "Image_Group_Index"

If these col names are pretty much fixed (and I think they are), ExportToDB could simply write them into the props file silently; no user input needed. If Tracer is opened, they'll be available.

**Comment by LeeKamentsky** [comment]
They should always be the same.
