### ISSUE TITLE
Unicode error under El Capitan

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1779]
A user reports getting a Unicode error under El Capitan for IdentifiySecondaryObjects and the ExportToSpreadsheet modules. Project file attached.

See screenshot for ExportToSpreadsheet:
![image](https://cloud.githubusercontent.com/assets/1186440/13118124/c17ed74c-d570-11e5-9119-0435cf5afc9b.png)

Stack trace for IdentifySecondary when he clicks on the Distance B popup.
```
Traceback (most recent call last):
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinelistview.py", line 914, in __on_item_activated
  File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/moduleview.py", line 411, in set_selection
  File "wx/_core.pyc", line 13075, in SetValue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 44: ordinal not in range(128)
```
At first, I thought it was the usual non-standard character issue we've seen before, so I had him blow away ~/Library/Preferences/CellProfilerLocal.cfg, and then restarting. No dice.
[LincsSS3.cpproj.txt](https://github.com/CellProfiler/CellProfiler/files/134818/LincsSS3.cpproj.txt)

**Comment by LeeKamentsky** [comment]
That's in code for putting text into the module notes panel. The work-around is to type the comments using ASCII characters. I am not sure why wx is not accepting the unicode, but hopefully the work-around is enough to get the user by.

I did open the project file on the windows source-code version on my own computer and was not able to replicate the problem. I also did not see any unusual characters in the notes - perhaps the Mac is doing some automagic open-quotes / close-quotes matching and changing the text. I did see, however, that if you type ALT+234 on Windows (to get the Ω character) in the notes panel and then refresh the module display, you get "Î©" instead. There needs to be a utf-8 to unicode translation there.
