### ISSUE TITLE
JIRA [IMG-854] IdentifyPrimaryObjects: Automatic estimation of object diameter limits

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#178]
From CP TODO: # Ray 2007_12_12: Can we compute Set Diameter for objects (quickly)?

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-854
Fix version: future
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
