### ISSUE TITLE
Pop-up menus not working under El Capitan

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1780]
A user reports that under El Capitan, he is able to load a project file (see #1779) but:
```
...all the popup menus are not popping up so I can not make any changes to it. I also can not get the question mark buttons to pop up help, but I can seem to change text items. kind of weird
```

He also reported later:
```
what is happening is that the popup menu actually pops up _behind_ the main window. It does not look like it is useable but I will keep playing with it.
```
Sorry for the vagueness, but not sure how to diagnose further.

**Comment by LeeKamentsky** [comment]
I can't repeat this, just downloaded the DMG and installed on an El Capitain machine. I tried right mouse button clicking in the pipeline panel and the context menu appeared correctly. I think I need screen shots or a demo of it to understand the problem fully.

**Comment by AnneCarpenter** [comment]
Closing - if someone is able to reproduce by all means let us know!
