### ISSUE TITLE
Missing Figure Toolbar

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1785]
In Mac nightly build from a couple days ago, figure windows have no toolbar:
<img width="1365" alt="screen shot 2016-02-26 at 7 27 49 am" src="https://cloud.githubusercontent.com/assets/1225595/13352384/f185b78a-dc5a-11e5-9e19-22027ba5d57c.png">

**Comment by dlogan** [comment]
The toolbar _is_ there when running from source:
![image](https://cloud.githubusercontent.com/assets/1225595/13353475/b278fdce-dc62-11e5-910e-80dec285e61c.png)

**Comment by LeeKamentsky** [comment]
What version of WX do you have on your Mac, @dlogan?

**Comment by LeeKamentsky** [comment]
This post hints that calling Reailze on the toolbar before SetToolBar works
https://groups.google.com/forum/#!topic/wx-users/-YJOnvHTWmw
