### ISSUE TITLE
JIRA [IMG-843] Interface with BioImageXD, thus adding 3D algorithms

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#179]
The BioImageXD project deals with 3D segmentation and visualization and is written in Python, so we would like to interface with it. Lee&#39;s notes on it:&quot;It looks like we could interface with BioImage at the level of their modules, filters and data sources. They have some standardized interfaces for data sources, modules and filters which means that we could write adapters for these interfaces that would allow us to run their modules in our framework. The internal data format is a little different, so we would have to translate forward and back for each of these, but, having done it once, we&#39;d be able to use the same code for all of them. It&#39;s not that hard to do this, probably a couple of days including testing and packaging issues.  They have written nine data sources; I&#39;m guessing that writing the interface to these would be less work than writing and validating the code. We can make CellProfiler take advantage of BioImage.&quot;<br/><br/>BioImageXD also contains some colocalization measures that might be helpful to incorporate into our Measure Correlation module, and they also do some image input/output that might be useful to us.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-843
Fix version: future
Assignee: leek

**Comment from panthony on Mon, 26 Apr 2010 15:51:10 -0400:**
Wiki page has been moved to<a href="http://dev.broadinstitute.org/imaging/privatewiki/index.php/2010_04_15_BioImageXD">http://dev.broadinstitute.org/imaging/privatewiki/index.php/2010_04_15_BioImageXD</a>

**Comment by dlogan** [comment]
Closing now, for future consideration.
