### ISSUE TITLE
CellProfiler 2.1.1, the "Input modules" area can not be opened in Windows System

### ISSUE THREAD

**Issue by xueshirong** [CellProfiler/CellProfiler#1811]
Hi, can anybody help me? It is my first time to use CellProfiler. I download the source code of "2.1.1 6c2d8960". After compiling and running, there are something wrong.
1. The "Input modules" area can not be expanded.
2. When I move the mouse within the area of "Module settings", there will pop up an error box "Pipeline error".
3." Could not load cellprofiler.modules.ilastik_pixel_classification"

![input modules](https://cloud.githubusercontent.com/assets/3871607/13481254/a8872138-e0a9-11e5-922c-615d85d071c6.png)

![load error](https://cloud.githubusercontent.com/assets/3871607/13481314/416a2288-e0aa-11e5-8401-85dc1a7a5ee8.png)

The detail is as attachment.

**Comment by 0x00B1** [comment]
@xueshirong, would you mind trying a newer build?

**Comment by xueshirong** [comment]
@0x00B1 Thank you for you reply. Which version number do you recommend? I will try it.

**Comment by LeeKamentsky** [comment]
We ran into problems of the sort that you're experiencing when we switched from wx 2.8 to  3.0. I would use the head of the master branch and use either wx 2.8 or 3.0 or switch to using wx 2.8 if you need to use 2.1.1.

**Comment by 0x00B1** [comment]
@xueshirong You can find the nightly 64-bit release for Windows on our [releases](http://cellprofiler.org/releases/) page.

**Comment by xueshirong** [comment]
Thank you all. I switch wx 3.0 to 2.8. Now it works well.

**Comment by 0x00B1** [comment]
Awesome
