### ISSUE TITLE
test_exporttodatabase relies on Broad MySQL database

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1814]
The code in test_exporttodatabase uses an in-house database. The code should use environment variables for the host, database, user and password.

Travis should start a MySQL database for testing:
https://docs.travis-ci.com/user/database-setup/#MySQL

**Comment by 0x00B1** [comment]
We could consider [mocking](http://python-mock.sourceforge.net/#example-usage) instead of using a physical database.
