### ISSUE TITLE
Build errors with latest Dockerfile from CellProfiler/docker

### ISSUE THREAD

**Issue by jd-recursion** [CellProfiler/CellProfiler#1819]
I'm attempting to build a docker image using the [CellProfiler/docker/Dockerfile](https://github.com/CellProfiler/docker/blob/master/Dockerfile).  I'm running `make` as specified in the README.  However, I'm getting this error:

```
Step 8 : RUN python external_dependencies.py
 ---> Running in bd1d4fed336c
python: can't open file 'external_dependencies.py': [Errno 2] No such file or directory
The command '/bin/sh -c python external_dependencies.py' returned a non-zero code: 2
make: *** [build] Error 1
```

It appears this file was removed from the [CellProfiler/CellProfiler]() repo.  I took a guess and assumed this step wasn't needed anymore, so I removed [this line](https://github.com/CellProfiler/docker/blob/master/Dockerfile#L83) in the Dockerfile:

```
RUN python external_dependencies.py
```

I rebuilt and then saw this error:

```
Step 8 : RUN python CellProfiler.py --build-and-exit
 ---> Running in ecd88efea6cd
Version: 2016-03-04T16:06:57 e5117de / 20160304160657
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "/usr/local/src/CellProfiler/cellprofiler/__main__.py", line 235, in main
    raise ValueError("You must specify a pipeline filename to run")
ValueError: You must specify a pipeline filename to run
Failed to stop Ilastik
Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "/usr/local/src/CellProfiler/cellprofiler/__main__.py", line 235, in main
    raise ValueError("You must specify a pipeline filename to run")
ValueError: You must specify a pipeline filename to run
The command '/bin/sh -c python CellProfiler.py --build-and-exit' returned a non-zero code: 1
make: *** [build] Error 1
```

Am I using the most up-to-date Dockerfile?  If not, can you point me to it?  Thanks!

**Comment by purohit** [comment]
+1
It would be really helpful for us to get a working Dockerfile to build CellProfiler, so we can continue processing.

**Comment by dlogan** [comment]
Hi all, I'm not sure if any work's been done on this recently.  @0x00B1 ?

**Comment by 0x00B1** [comment]
Hi, @purohit, I’m looking into this now!

**Comment by purohit** [comment]
Thanks so much!

**Comment by 0x00B1** [comment]
@purohit and @jd-recursion, [CellProfiler/docker](https://github.com/CellProfiler/docker) is fixed! Enjoy. :smile:

**Comment by 0x00B1** [comment]
https://hub.docker.com/r/cellprofiler/cellprofiler/builds/bmwntqpjthupfoanj4mc6wq/

**Comment by purohit** [comment]
@0x00B1 Thanks so much! I really appreciate the fast response.
