### ISSUE TITLE
GUI does not appear until clicking the icon in the dock on Mac OS 10.10.5

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#1821]
Using today's beta (CP 2.2.0rc2 (rev e5117de)), I doubleclick the app and wait, and wait, and wait. If I click the icon in the dock the GUI appears.

**Comment by dlogan** [comment]
Related to https://github.com/CellProfiler/CellProfiler-Analyst/issues/170 ?

**Comment by LeeKamentsky** [comment]
Most likely, it just needs a call to Frame.Raise somewhere in CellProfilerApp.py.

**Comment by daviddao** [comment]
Maybe it is because of our automatic mac build machine. I don't experience this in windows or on builds using my machine. CP and CPA are automatically build on the same Mac.

**Comment by dlogan** [comment]
Duplicate of #1738

**Comment by dlogan** [comment]
Is this fixed?  Does the fix also apply to https://github.com/CellProfiler/CellProfiler-Analyst/issues/170?
