### ISSUE TITLE
Add Phenix naming scheme to metadata guesses

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1824]
![image](https://cloud.githubusercontent.com/assets/1225595/13646689/994e944e-e5fe-11e5-910f-f0abff47c308.png)

It would be convenient to add the Phenix naming scheme to the guesses.

Related to the issues about well-naming assumption issues #1677 and also to https://github.com/CellProfiler/CellProfiler-Analyst/issues/95

**Comment by dlogan** [comment]
P.S. I can't assign this to anyone or add labels etc.  Something amiss with my settings, or by design now?

**Comment by LeeKamentsky** [comment]
Try now

**Comment by dlogan** [comment]
:+1:

**Comment by LeeKamentsky** [comment]
So what should be the metadata tags that should be assigned for the above:

WellRow: 02
WellColumn: 02
ChannelNumber: 1
???

**Comment by braymp** [comment]
Site:01 (i.e., the 2-digit number after the "f")

**Comment by dlogan** [comment]
Good question - all yes.

r02c02f01p01-ch1sk1fk1fl1.tiff

Like Mark said, f = Site/Field

p, sk, fk, and fl never seem to vary in my experience, so I guess neglect them for now.

**Comment by dlogan** [comment]
BUT even better, to fulfill #1677, it would be better for 

> WellRow = 02 

to actually be made 
>WellRowNum = 02

and also convert the number to the traditional alphabetical letter scheme

>WellRow = 'B'

so that the subsequently constructed 'Well' metadata would be in the format that CPA likes ('B02' rather than '0202').  Maybe there's a better solution to this, but I thought maybe an extra col might be ok

**Comment by LeeKamentsky** [comment]
I just made changes in Prokaryote to turn WellRow = 02, WellColumn = 01 into Well = B02. I am hoping that's ok - a little much to keep track of for everyone if users have to know that they should use WellRowNum to capture a numeric well row.

**Comment by dlogan** [comment]
Sounds good to me!

**Comment by braymp** [comment]
That's great; you can probably close the associated issues https://github.com/CellProfiler/CellProfiler/issues/1677 and https://github.com/CellProfiler/CellProfiler-Analyst/issues/95.
