### ISSUE TITLE
Open a new CP Window doesn't show a change

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler#1829]
When you choose Open a new CP Window, nothing seems to happen. You have to look at the dock (in mac) and click to see the new window.

**Comment by dlogan** [comment]
related to #1821

**Comment by daviddao** [comment]
and to [CPA #170](https://github.com/CellProfiler/CellProfiler-Analyst/issues/170) - I am almost certain now that it is because of the automatic build machine. Both CPA and CP are somehow packaged without a Python Framework. I will dig into it for CPA.

**Comment by mcquin** [comment]
Closing as duplicate. We should verify the fix for #1821 also fixes this.
