### ISSUE TITLE
Figure toolbar has new subplots button

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1830]
There is an extra button labeled "Subplots" on figure windows.  It seems extraneous to me except to move subplots around.  I'd vote to remove if not difficult.

OLD 2.1.2 toolbar (left) and NEW 2.2.0 beta toolbar (right) ![image](https://cloud.githubusercontent.com/assets/1225595/13674554/f37d5632-e6ab-11e5-9f6b-46330c670d5b.png)

Related to #1785

**Comment by AnneCarpenter** [comment]
Seems safe to not fix this issue, but if I'm mistaken and it's actually causing trouble in some way, please re-open!
