### ISSUE TITLE
ExportToSpreadsheet now has a red triangle rather than yellow in Test Mode

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1831]
The red triangle shown here (left is 2.1.2; right is Beta Mac 2.2.0) implies that there is a config problem, and not just a warning about not producing output in Test Mode, right?  Or did the nomenclature change?
![image](https://cloud.githubusercontent.com/assets/1225595/13674827/05d4f906-e6ad-11e5-8196-ed9b425f8d85.png)

**Comment by LeeKamentsky** [comment]
I loaded the example pipeline from the welcome screen and I get a yellow triangle:
![image](https://cloud.githubusercontent.com/assets/660469/13680734/e8dcba94-e6c7-11e5-9d90-a96fe59471de.png)

Tried it on the trunk build and when running from source, both on Windows.

**Comment by dlogan** [comment]
Just tried on Mac running from source, after git pulling, and I still get the red triangle.  Odd.

![image](https://cloud.githubusercontent.com/assets/1225595/13681761/d35e583a-e6cc-11e5-84a3-12defb1c9bf1.png)
