### ISSUE TITLE
Ilastik not working on 2.2.0 release

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#1832]
Reported by @tischi

Hey Lee,

I am just testing the ilastik of cellprofiler-2.2.0 and I am running into an old error again (see below e-mails). Any chance this could be fixed?

C:\Program Files\CellProfiler-2.2.0\.\ilastik\modules\classification\core\featur
es\featureBase.py:75: RuntimeWarning: tp_compare didn't return -1 or -2 for exce
ption
########################## exception in FeatureThread ###################

    Precondition violation!
    convolveLine(): kernel longer than line
    
    Traceback (most recent call last):
    
      File "ilastik\gui\volumeeditor.pyc", line 1224, in run
    Traceback (most recent call last):
        File "ilastik\modules\classification\core\featureMgr.pyc", line 207, in calcFeature
        File "ilastik\modules\classification\core\features\featureBase.pyc", line 82, in compute
        File "ilastik\modules\classification\core\features\featureBase.pyc", line 75, in compute
        File "ilastik\modules\classification\core\features\standardFeatures.pyc", line 197, in differenceOfGaussians
        File "ilastik\modules\classification\core\features\standardFeatures.pyc", line 136, in compute2d
    RuntimeError:
    Precondition violation!
    convolveLine(): kernel longer than line
    
    SystemError: error return without exception set

**Comment by tischi** [comment]
This error occurs when selecting the "Giga Huge" Features on images of a certain size.
I attached such an image below.

A while ago we found some code changes in ilastik that seemed related to the issue:
https://github.com/ilastik/ilastik/blob/74a227ce3131fd395b8892291f9dc54740c580a2/ilastik/applets/thresholdTwoLevels/opThresholdTwoLevels.py#L111
Maybe one can change this in the cellprofiler ilastik?
 
![image](https://cloud.githubusercontent.com/assets/2157566/13675137/84effb54-e6e0-11e5-9fc1-eef58e924ef5.png)

**Comment by LeeKamentsky** [comment]
Offhand, the gigahuge feature looks like it requires a kernel size of 60 and your image has a dimension of 218x204. I'm guessing that the tiling requirements for the borders do something bad (probably (60+64) * 2 = 248 or something). Gigahuge on images of this size won't work so well because a good part of the image is in a region where it can't be computed.

But I will look into seeing where in the code the bug might be happening.

**Comment by LeeKamentsky** [comment]
I think I found the problem: https://github.com/LeeKamentsky/ilastik-0.5/blob/cellprofiler/master/ilastik/core/dataMgr.py#L140

The block bounds have to be smaller than the overlap which for the gigahuge is 35 pixels. There were blocks that were smaller than 71 pixels across and these need to be expanded to a larger size to let the filter run. Not the best fix (there should be fewer blocks allocated in the first place), but it works.

I'm rebuilding CellProfiler now - if all goes well, the nightly build should be updated to include the fix in about an hour.

**Comment by LeeKamentsky** [comment]
So the nightly build for Windows appears to work. Would appreciate you checking.
http://cellprofiler.org/releases/
Ignore the March 7 date - it's wrong.

**Comment by tischi** [comment]
works!
