### ISSUE TITLE
JIRA [IMG-777] Put documentation into Mac format to allow searching

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#184]
Create helpbook from HTML manual to allow searching on mac.<br/><br/><a href="http://developer.apple.com/mac/library/DOCUMENTATION/Carbon/Conceptual/ProvidingUserAssitAppleHelp/authoring_help/authoring_help_book.html">http://developer.apple.com/mac/library/DOCUMENTATION/Carbon/Conceptual/ProvidingUserAssitAppleHelp/authoring_help/authoring_help_book.html</a><br/><br/>

Original reporter: thouis
Jira link: https://jira.broadinstitute.org/browse/IMG-777
Assignee: mbray

**Comment by dlogan** [comment]
Seems done, to an extent?  One can search Help from the menus on Mac, at least, even if it's not "by the (Mac) book".
