### ISSUE TITLE
"Version mismatch" between Windows and Mac builds

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1840]
A [Forum user](http://forum.cellprofiler.org/t/endocytic-organelles/3120/7) was concerned that the  pipeline I supplied from the Beta was a different version than mine since they got the "Version mismatch" warning upon their loading the pipeline.  This is a reasonable concern.  It turns out they have Windows and I have Mac but we are running the same 2.2.0 beta, so they need not have been worried (at least, they are both the current beta on the cellprofiler.org/releases page but I suppose one could be patched and not the other, sigh...)

With more and more betas and releases, can we help the users on different OSes by perhaps:
(1) Add the date to the githash on the "Version mismatch" warning when loading a pipeline from Mac/Windows onto the other OS? This way they could at least compare the dates and decide whether the versions are close enough to ignore the warning

or even better
(2) Make the Version mismatch warning smarter and not warn if the builds really did come from the same code base?

**Comment by LeeKamentsky** [comment]
The builds almost certainly didn't come from the same code base if there was a version mismatch. The warning has always been a bit bogus IMHO. If there's a true forwards incompatibility, you can always detect by the module variable revision number. If not, how much harm is there in loading?

I am assuming I can close this if I put the date into the warning. If there's a problem with the release process, you can file another issue against that.

**Comment by dlogan** [comment]
Yeah, I assumed the Windows and Mac betas did have the same code base, but the [user reports](http://forum.cellprofiler.org/t/endocytic-organelles/3120/9) that my Mac beta pipeline errored in his Windows beta (it uses the new MeasureObjectIntensityDistribution).  But his nightly works fine.  So yes, putting the date in would be great.
