### ISSUE TITLE
Metadata regexp 'match until'?

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1843]
[A forum user](http://forum.cellprofiler.org/t/metadata-match-until-regex-previews-correctly-but-the-update-button-gives-wrong-metadata/3076?u=david_logan) reports that they tried a 'match until' regexp (which I had not ever seen or tried before, I don't think) that didn't work, and may have altered other matches.  

Is this a problem?  Or is it just a regexp that CP doesn't offer?  The preview magnifying glass tool doesn't show it matching anything but it also doesn't show an error.

**Comment by LeeKamentsky** [comment]
I'm looking into it now. The regular expressions are handled in the regex editor using Python, but for efficiency reasons (in case someone dumps 10000000000 images into the image window), they are bulk-processed using Java. The Java code does some massaging to the regex and perhaps I missed something.

The offending regex: `^(?P<Experiment>[0-9]+).+?(?=_p[0-9])_p(?P<Position>[0-9]+)t(?P<Time>[0-9]+)c(?P<ChannelNumber>[0-9]+)`
The offending file name: `121201_RCM_HBC_cell density_complete_p01t00001c01.tif`

Thx for reporting.

**Comment by dlogan** [comment]
Thanks Lee.  And even more troubling which I hadn't noticed before, the Forum user notes [here](http://forum.cellprofiler.org/t/metadata-match-until-regex-previews-correctly-but-the-update-button-gives-wrong-metadata/3076/6) that two of the metadata tags have swapped metadata values (tags Position & Time).

**Comment by LeeKamentsky** [comment]
If you're running from source, you'll have to do

   pip uninstall prokaryote
   pip install prokaryote

this will be fixed in the next build.
