### ISSUE TITLE
Instructions for installing from source on OSX

### ISSUE THREAD

**Issue by gregjohnso** [CellProfiler/CellProfiler#1845]
I was not able to install on OS X 10.11 from source given the instructions on this git page, but had to do the following:

git clone https://github.com/CellProfiler/CellProfiler.git
pip install numpy
pip install cython
brew install mysql
cd CellProfiler
pip install --editable .

**Comment by dlogan** [comment]
@gregjohnso Thanks but I can't tell, are you suggesting any changes to these instructions? https://github.com/CellProfiler/CellProfiler/wiki/*Source-installation-(OS-X)
