### ISSUE TITLE
Test mode does not show test window

### ISSUE THREAD

**Issue by burgerga** [CellProfiler/CellProfiler#1846]
I am on Linux, managing a couple of installations on desktops and servers, but on all of them when I click test mode, I don't get a window. I can click run, step, next image, it all works, but I don't see anything which is supposed to be the whole point of the testing mode.

If you need anything from me, debug logs, etc. just let me know!

**Comment by 0x00B1** [comment]
Hi, @burgerga!

When you press the “Start Test Mode” button, you should see:

![skitch](https://cloud.githubusercontent.com/assets/315821/13752864/026ad88e-e9e7-11e5-931b-ee8edfb7e1f5.jpg)

(i.e. a window doesn’t pop after pressing “Start Test Mode”).

Is that happening? If not, it’s certainly an issue and I’ll need some more information. :smile:

**Comment by burgerga** [comment]
Unfortunately, I don't have that button (also tried increasing the pane size, but nothing):

![screenshot from 2016-03-14 19 03 44](https://cloud.githubusercontent.com/assets/907362/13755821/4cf35d3c-ea1d-11e5-9578-58650544e854.png)

**Comment by braymp** [comment]
The "eyeballs" (i.e., the icons to the left of the green checkmarks) are closed, which disables the display. Click the icon to "open" the eyes (or select Window > Show all on run) to enable them and then try again.

**Comment by burgerga** [comment]
Oh wow, that never occured to me ;) I was running CellProfiler in Debug mode and everything. Thanks so much!

**Comment by burgerga** [comment]
(Isn't there a way to make that clearer?)

**Comment by 0x00B1** [comment]
@burgerga I hope so! Do you have any ideas?

**Comment by burgerga** [comment]
Hmm, no(t yet).  The viewer option that I see in the 2.2.0 already looks like a nice start.

**Comment by LeeKamentsky** [comment]
Yup - it will start the viewer and the viewer will have access to the images, objects and measurements for a module, even if the eyeball is closed.
