### ISSUE TITLE
JIRA [IMG-769] Add evolving generalized voronoi diagrams as alternative to Watershed, Propagate

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#185]
Potential UROP project

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-769
  (Original JIRA has attachments.)
Assignee: leek

**Comment from leek on Wed, 24 Mar 2010 10:41:05 -0400:**
Code from article

**Comment by dlogan** [comment]
Closing now, for future consideration.
