### ISSUE TITLE
Buttons grayed out mistakenly 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1855]
Load Welcome screen Example fly pipeline. 
Start Test Mode 
Change the order of the modules, using the Up/Down arrows.
The Test Mode and Analyze buttons are grayed out.

I have also seen the Test Mode buttons (e.g. Step) grayed out, but I can't reproduce.

Only seems to occur on Windows.

**Comment by dlogan** [comment]
Running 2.2.0rc2, rev 1b13225

**Comment by LeeKamentsky** [comment]
It's some sort of refresh bug in WX. I was able to recreate the problem this time by loading a project. I looked at the gray button's attributes and it was in the "Enabled" state, which means it shouldn't be gray. I then did `button.Refresh(eraseBackground=True)` and when it repainted, it had the proper appearance.

I'll go looking for some way to explicitly repaint it to fix the problem.

**Comment by dlogan** [comment]
This (re?)appeared, i.e. the Test Mode and Analyze buttons can be mistakenly grayed out.  Using the Windows nightly build from today (2016-12-07).

Again, to reproduce:
- Load Welcome screen Example fly pipeline. Buttons look fine:
![image](https://cloud.githubusercontent.com/assets/1225595/20982843/26d57412-bc88-11e6-8730-790d3d0a6ede.png)
- Start Test Mode
- Change the order of the modules, using the Up/Down arrows.
- The Test Mode and Analyze buttons are grayed out, however they still function properly..
![image](https://cloud.githubusercontent.com/assets/1225595/20982859/38d89e1e-bc88-11e6-9ce6-ec8583778a85.png)

**Comment by DavidStirling** [comment]
I used to experience this issue, but it no longer seems to occur in Master, possibly after some of the wx fixes made recently. Feel free to re-open this if it still occurs.
