### ISSUE TITLE
Drag&Drop module creates copy of module

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler#1857]
Drag&Drop a module should move the module to the new position. Instead, CP creates a copy of the module at the new position and keeps the module at the old position (so that in the end the module exists twice).
CP Version: Beta 2.2.0

**Comment by dlogan** [comment]
This is a serious UI problem ... mostly because I forgot about it and it just bit me again 😉

**Comment by AnneCarpenter** [comment]
Duplicate of #1701 - closing. Something of a miracle that @braymp  didn't catch the duplicate, he somehow has photographic memory of all Github issues ever.
