### ISSUE TITLE
JIRA [IMG-740] Complete plotting data tools

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#187]
CP 1.0&#39;s&quot;PlotMeasurement&quot; data tool has been replaced by the new scatterplot and histogram data tools, but we still need the other functions to be added as CP (and CPA) tools: line, bar, 1D scatterplot<br/><br/>Be sure to update&quot;Where&#39;s my module&quot; Forum help/CP help when this task is complete.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-740
Fix version: next
Assignee: afraser

**Comment from mbray on Thu, 24 Jun 2010 11:46:47 -0400:**
A user has asked for this:<a href="http://cellprofiler.org/forum/viewtopic.php?f=16&t=1008&start=0">http://cellprofiler.org/forum/viewtopic.php?f=16&t=1008&start=0</a>.

**Comment by dlogan** [comment]
Closing now, for future consideration.
