### ISSUE TITLE
JIRA [IMG-737] Create ViewData data tool

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#188]
ViewData - should make CPA&#39;s table viewer tool available in CP (to re-create a CP 1.0 data tool called ViewData).  The name of the tool should match CPA&#39;s name, of course.<br/><br/>Be sure to update&quot;Where&#39;s my module&quot; Forum help/CP help when this task is complete.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-737
Assignee: afraser

**Comment by dlogan** [comment]
Closing now, for future consideration.
