### ISSUE TITLE
Help/About on Windows Release

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1887]
Yields
```
Traceback (most recent call last):
  File "cellprofiler\gui\cpframe.pyc", line 986, in about
  File "cellprofiler\gui\dialog.pyc", line 15, in __init__
  File "pkg_resources\__init__.pyc", line 545, in get_distribution
  File "pkg_resources\__init__.pyc", line 425, in get_provider
  File "pkg_resources\__init__.pyc", line 946, in require
  File "pkg_resources\__init__.pyc", line 833, in resolve
DistributionNotFound: The 'cellprofiler' distribution was not found and is required by the application
```

**Comment by 0x00B1** [comment]
Nightly?

**Comment by 0x00B1** [comment]
`pip install --upgrade pip`?

**Comment by braymp** [comment]
Same error for nightly (3cb30f4e9e0627434600db5dbdc71017f1d4f737).

**Comment by braymp** [comment]
Pip is up-to-date.

**Comment by braymp** [comment]
I should mention I did not use <code>pip install --pre cellprofiler</code> to get CP running from source (though I assume that shouldn't matter...?)

**Comment by 0x00B1** [comment]
`pip install -e .` from the CellProfiler source directory works too. :smile: 

Would you mind posting the output of `pip freeze`?

**Comment by braymp** [comment]
Here you go. Along with CP deps, there's a lot of Jupyter-related deps as well:
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC>pip freeze
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
biopython==1.66
centrosome==1.0.4
certifi==2016.2.28
cycler==0.10.0
Cython==0.23.4
dask==0.8.1
decorator==4.0.9
functools32==3.2.3.post2
futures==3.0.5
h5py==2.5.0
inflect==0.2.5
ipykernel==4.3.1
ipyparallel==5.0.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
javabridge==1.0.14
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.1
jupyter-console==4.1.1
jupyter-core==4.1.0
lxml==3.4.4
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
MySQL-python==1.2.5
nbconvert==4.1.0
nbformat==4.0.1
networkx==1.11
notebook==4.1.0
numpy==1.10.4
pandas==0.18.0
path.py==8.1.2
pickleshare==0.6
Pillow==3.1.1
prokaryote==1.0.10
Pygments==2.1.3
pyparsing==2.1.0
PyQt4==4.11.4
python-bioformats==1.0.5
python-dateutil==2.5.0
pytz==2016.1
pyzmq==15.2.0
qtconsole==4.2.0
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.17.0
seaborn==0.7.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
toolz==0.7.4
tornado==4.3
traitlets==4.2.1
verlib==0.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
```

**Comment by 0x00B1** [comment]
```
biopython==1.66
centrosome==1.0.4
certifi==2016.2.28
cycler==0.10.0
Cython==0.23.4
```

It looks like you’re missing an important package. :D

**Comment by braymp** [comment]
Huh, that did it.
![image](https://cloud.githubusercontent.com/assets/1186440/14045476/f78d84c4-f270-11e5-8ca8-6dd992a396eb.png)
Since I was able to run CP (at least in test mode), I didn't realize that the project needed installation too. 

BTW, there's a &Acirc; in the About; can you get rid of it?

**Comment by 0x00B1** [comment]
> BTW, there's a Â in the About; can you get rid of it?

Yeah, it’s a silly Unicode issue. I’ll fix it today. I think @LeeKamentsky is leaving the Broad because of Unicode errors. :laughing:

**Comment by 0x00B1** [comment]
>  Since I was able to run CP (at least in test mode), I didn't realize that the project needed installation too. 

Yep. CellProfiler is both a library and an application. :+1:
