### ISSUE TITLE
Error on dragging images into Images module

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1899]
Mac nightly build downloaded today.

Simply drag images into Images: 
```
Traceback (most recent call last):
  File "/Applications/CellProfiler_nightly_20120328.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinecontroller.py", line 3452, in OnData
  File "wx/_misc.pyc", line 5613, in GetData
AttributeError: 'function' object has no attribute 'im_class'
```

There are 4 images, zipped, that I received the error when dragging and dropping. 
[Images.zip](https://github.com/CellProfiler/CellProfiler/files/192111/Images.zip)

**Comment by dlogan** [comment]
NOTE: I'm on the pixel_classifier branch, so maybe this is solved too?

**Comment by LeeKamentsky** [comment]
Can you test it on the master branch?

**Comment by 0x00B1** [comment]
@LeeKamentsky I can reproduce on master.

**Comment by 0x00B1** [comment]
> NOTE: I'm on the pixel_classifier branch, so maybe this is solved too?

Unfortunately, no.

**Comment by dlogan** [comment]
Occurs on Windows too.

Also occurs when dragging a pipeline into pipeline window.

**Comment by dlogan** [comment]
This is seriously painful, and a game-stopper for release IMHO.  And because we can't Browse for folders (#600), for instance for one project I have to browse to folders, select all images for each one, and then do this 27 times, ugh.

**Comment by LeeKamentsky** [comment]
I will see if I can fix today

**Comment by LeeKamentsky** [comment]
There is functionality that only worked in Windows and only for some cases which allowed you to drag in the text of a file name. I think wx 3.0 broke that functionality and I tried w/o it and things worked. So I am going to remove that functionality to fix.

**Comment by dlogan** [comment]
👍 Works! The game is on!
