### ISSUE TITLE
JIRA [IMG-732] Consistentify menus

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#190]
Consult the Mac style guide to see how to handle the menu - right now, new options appear when an image window has focus, which is ok, except other stuff disappears (important stuff, like CellProfiler Help).

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-732
Assignee: klmadden

**Comment from klmadden on Fri, 15 Oct 2010 13:43:24 -0400:**
actually....according to the apple style guide, these kind of application specific settings should be in a panel:<br/>&quot;panels describe auxiliary windows that contain controls and options that affect the active document or selection&quot;<br/><br/>otherwise, technically the toolbar of matplotlib stuff we have now should also be available all the time from the main menu (it can be grayed out when you cant access it, but should appear as&#39;image tools&#39; or something)<br/><br/>i dont know know annoying it is to make this all mac-specific, since i&#39;m assuming on pc everything looks just fine? but otherwise i would reccommend collapsing all the image window-tools into a menubar item that is simply grayed out when there is no active cpfigure. this seems most consistent with other apps, unless we go the&quot;panel&quot; route which is just annoying. (think the little&quot;inspector&quot; in preview or excel)<br/><br/>-kate

**Comment by dlogan** [comment]
Closing now, for future consideration.
