### ISSUE TITLE
Job queue

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1900]
A few observations:
- CellProfiler’s job queue architecture supports one message queue: ZeroMQ. While ZeroMQ is a fine choice for many scenarios, some users would like to use their preferred message queue and broker (e.g. Amazon Simple Queue Service (SQS), Kafka, or RabbitMQ).
- Since ZeroMQ isn’t a message broker, CellProfiler includes a bespoke ZeroMQ-backed message broker. This is contrary to the “Do One Thing and Do It Well” concept. Moreover, the modules:
  - Cellprofiler.analysis
  - Cellprofiler.analysis_worker
  - Cellprofiler.utilities.zmqrequest

have become a significant part (i.e. LoC) of the cellprofiler and cellprofiler.utilities packages
- CellProfiler’s job queue architecture is responsible for an outsized number of issues.
- ZeroMQ is difficult to package.

I think it’s worth investigating a new architecture that’s simpler and permits the use of alternative message brokers.

**Comment by 0x00B1** [comment]
Ideally, our default message broken shouldn't introduce a third-party requirements.
