### ISSUE TITLE
Nightly suggests naming application as 2.2, different than the releases page (2.3)

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1902]
Not a big deal, but the version numbers don't match (see below).  Maybe it should just be "nightly" and have no number associated?  The user can always change this.

![image](https://cloud.githubusercontent.com/assets/1225595/14087198/c30fd5b6-f4f6-11e5-87df-a91d2d438b44.png)

The same occurs after this for the application folder itself:
![image](https://cloud.githubusercontent.com/assets/1225595/14087263/014fdd12-f4f7-11e5-9c82-f7f6c6c6b9ed.png)

**Comment by 0x00B1** [comment]
Nice. I’ll look into this before the next release.

**Comment by mcquin** [comment]
Closing: no longer relevant
