### ISSUE TITLE
If a pipeline uses only TIFFs, should we `import bioformats`?

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1903]
Has anyone considered lazily loading `python-bioformats` when an esoteric format is used?

**Comment by dlogan** [comment]
Seems reasonable!  Note that saving images can be (is often?) in a different format, like PNG.  Perhaps saving should be lazily done too.

**Comment by 0x00B1** [comment]
Good idea.

**Comment by 0x00B1** [comment]
Closing because this is a duplicate
