### ISSUE TITLE
File > Save Project As... default directory

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1904]
If I drag a project into CP, I expect the File > Save Project As... dialog to default to the directory from which I dragged it.  It does not, but rather to some other recent output folder(?).  

File > Save does indeed overwrite the project that had been dragged in, but File > Save Project As... has a different (imho, non-intuitive) behavior.

File > Export pipeline seems to have the "correct" behavior.

Mac Beta ~2016_03_08

**Comment by AnneCarpenter** [comment]
Worth a quick look (maybe?), but if not readily solvable, ok IMO to close, given bandwidth constraints.

**Comment by mcquin** [comment]
Resolved #2722
