### ISSUE TITLE
Package Vigra for OS X builds

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1917]

**Comment by 0x00B1** [comment]
Unfortunately, I was unable to install Vigra by:

```sh
$ brew install vigra --with-python
```

**Comment by LeeKamentsky** [comment]
No surprise there. Look at https://github.com/LeeKamentsky/build-ilastik-on-windows for some hints. At the least, you need Boost, you need a specific version of Vigra if the goal is to use Ilastik 0.5, you need Vigra's library dependencies, you need CMake and you need to shift from a python setup.py mindset to a CMake mindset.

It took me two months to do "build_ilastik_on_windows" and you should be prepared for more than a one-liner to do similar on OS/X.

**Comment by 0x00B1** [comment]
> It took me two months to do "build_ilastik_on_windows" and you should be prepared for more than a one-liner to do similar on OS/X.

It’s actually very close. It’s a Clang bug. When that’s resolved, it should work.

(`brew install vigra` installs Boost and other dependencies.)

**Comment by 0x00B1** [comment]
[Homebrew issue](https://github.com/Homebrew/homebrew-science/issues/2428)

**Comment by 0x00B1** [comment]
Won’t fix (Ilastik support has been dropped)
