### ISSUE TITLE
JIRA [IMG-722] Support of relative image widths/path in Help

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#192]
Currently, any html code re: images referenced in the help, whether non-module or module-specific:<br/>(1) Uses relative paths to the actual images as part of the src string in the&lt;img&gt; tag<br/>(2) Does not support relative sizing, i.e,&quot;width=50%&quot; doesn&#39;t work<br/><br/>For (1), relative paths need to be specified better using a 2.5 implementation of os.path.relpath<br/>For (2), the image size needs to be obtained from the images and the whole&lt;img&gt; tag needs to be created programmatically.<br/><br/>Files affected: gui/help.py, CellProfiler.py, perhaps gui/cpframe.py

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-722
Assignee: leek

**Comment from anne on Fri, 16 Jul 2010 10:52:41 -0400:**
It&#39;s constrained by wx at the moment. We are waiting for them to fix things but maybe someday will do it ourselves.

**Comment by dlogan** [comment]
Closing now, for future consideration.
