### ISSUE TITLE
JIRA [IMG-713] SaveImages (save module display window)

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#193]
SaveImages should support saving the ENTIRE cpfigure window (rather than just an axis) associated with a given module.<br/><br/>Here&#39;s the help text:<br/>&quot;Module display window: The window associated with a module can be saved, which will include all the panels and text within that window.&quot;

Original reporter: afraser
Jira link: https://jira.broadinstitute.org/browse/IMG-713
Assignee: afraser

**Comment from mbray on Fri, 18 Jun 2010 12:12:31 -0400:**
Remember to update help. Currently it says it&#39;s not implemented.

**Comment by dlogan** [comment]
Closing now, for future consideration.
