### ISSUE TITLE
Delete cellprofiler.cpmath

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1935]

**Comment by 0x00B1** [comment]
CellProfiler 2.2.0 depreciated cellprofiler.cpmath. When should cellprofiler.cpmath be removed from the repository?

**Comment by LeeKamentsky** [comment]
This affects any plugin module that uses the old location for cpmorphology, etc. IMHO, the tutorial should be updated before doing this.

**Comment by 0x00B1** [comment]
Noted! I’ll create an issue.
