### ISSUE TITLE
Remove “Maximum memory for Java (MB)” option

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1938]
CellProfiler should obey the user’s configuration (i.e. `-Xms`).

**Comment by mcquin** [comment]
Still a thing. My search was bad.

**Comment by bethac07** [comment]
CellProfiler still (as of 3.1.5) obeys this preference, not the system java options.  This is a bummer since we already removed the command-line-switch to override, which means until this is fixed the user needs to manually edit `preferences.py` on their system.

**Comment by mbarish** [comment]
Has this issue of memory limits in Java been addressed?  In CP 3.1.8, I cannot find a preferences.py file to modify.
Thanks.

**Comment by 0x00b1** [comment]
resolved by https://github.com/CellProfiler/core/pull/17
