### ISSUE TITLE
JIRA [IMG-710] Threshold adjacency statistics - New image metric to add?

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#194]
Consider implementing the Threshold adjacency statistics described in this paper:<br/><a href="http://www.ncbi.nlm.nih.gov/pubmed/17394669">http://www.ncbi.nlm.nih.gov/pubmed/17394669</a>paper] by Hamilton&amp; Teasdale.<br/><br/>They sound useful.<br/><br/>Once done, it might be useful to compare and contrast this approach vs. WND-CHARM; see our project wiki page:<br/><a href="http://dev.broadinstitute.org/imaging/privatewiki/index.php?title=2009_01_05_WND-CHARM%2C_NIH-Ilya_Goldberg_%28NIH%29">http://dev.broadinstitute.org/imaging/privatewiki/index.php?title=2009_01_05_WND-CHARM%2C_NIH-Ilya_Goldberg_%28NIH%29</a>

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-710
Assignee: leek

**Comment from leek on Mon, 9 May 2011 13:05:26 -0400:**
I took a look at the images. I think that the method is just indirectly measuring particle size - larger particles will have higher measurements in the category where all adjacent pixels are over threshold because more pixels will be in the interior of the objects. Smaller particles will have higher measurements in the lower adjacency categories because more pixels will be closer to the edge of the particles.<br/><br/>OK - implement anyway, a really high bogosity index here, but it&#39;s a way of measuring particle size without segmenting them.

**Comment by tilenkranjc** [comment]
I have this module ready, just need to do a bit of cleanup.

**Comment by dlogan** [comment]
Closing now, for future consideration. @tilenkranjc re-open and/or comment when you are ready.
