### ISSUE TITLE
“Maximum number of workers” should have a default value

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1941]
We should provide a sensible default to simplify configuration.

We can use the user’s system information to dynamically set a default value.

**Comment by braymp** [comment]
I thought it already did: https://github.com/CellProfiler/CellProfiler/blob/49cc81da7db1730b7adaca09185a3adc99338906/cellprofiler/preferences.py#L1373

**Comment by 0x00B1** [comment]
@braymp We do. But we don’t populate the field with the value.

**Comment by mcquin** [comment]
Fixed.
