### ISSUE TITLE
Remove “Batch Profiler URL” option

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1943]

**Comment by dlogan** [comment]
Will this setting be available anywhere else going forward? Same goes for all the Prefs you'd like to remove, e.g. #1938 - #1944

**Comment by 0x00B1** [comment]
It depends on whether it’s covered by an environment variable.

`Batch Profiler URL` is specific to our group and shouldn’t be a preference. We should address this elsewhere (e.g. outside of CellProfiler). I’m trying my best to untangle CellProfiler’s unwieldy dependencies!

**Comment by 0x00B1** [comment]
@dlogan If you’d like to keep one of the preferences address, please say so in the appropriate issue! :smile:
