### ISSUE TITLE
The link to the trunk builds doesn't work

### ISSUE THREAD

**Issue by PetterRanefall** [CellProfiler/CellProfiler#1946]
404

File not found

The site configured at this address does not contain the requested file. 

If this is your site, make sure that the filename case matches the URL.
 For root URLs (like http://example.com/) you must provide an index.html file. 

Read the full documentation for more information about using GitHub Pages. 

GitHub Status — @githubstatus

**Comment by 0x00B1** [comment]
Hi, @PetterRanefall 

What link? The “trunk builds” have moved to our [releases](http://cellprofiler.org/releases/) page.

**Comment by 0x00B1** [comment]
And issues for cellprofiler.org can be submitted to [github.com/cellprofiler.github.io/issues](https://github.com/CellProfiler/cellprofiler.github.io/issues).

**Comment by braymp** [comment]
He's talking about this: www.cellprofiler.org/cgi-bin/trunk_build.cgi. It's referenced quite frequently on the forum.

**Comment by PetterRanefall** [comment]
The link from cellprofiler.org and then Help/For developers/Trunk builds

**Comment by dlogan** [comment]
I fixed those wiki links that @PetterRanefall referred to, thanks.

Basically same issue as https://github.com/CellProfiler/cellprofiler.github.io/issues/1, so closing here

**Comment by braymp** [comment]
Can any other existing trunk_build.cgi links be redirected, e.g., on the forum?

**Comment by braymp** [comment]
Oops, just saw https://github.com/CellProfiler/cellprofiler.github.io/issues/1
