### ISSUE TITLE
Option to select folders in Image module

### ISSUE THREAD

**Issue by tischi** [CellProfiler/CellProfiler#1947]
@LeeKamentsky 
Right-clicking in the Image module only gives the option "Browse for Images".
It would be really good if it also gave the option "Browse for Image-containing Folders".
This is important if the drag and drop does not work, e.g. when launching CellProfiler "in the could", e.g., on a remote computer with X forwarding to see the GUI.

**Comment by braymp** [comment]
Duplicate of #600?

**Comment by 0x00B1** [comment]
@braymp:
> Duplicate of #600?

Yep
