### ISSUE TITLE
cgi script gives 404

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1950]
This cgi link won't work on cellprofiler.org any more: https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/errordialog.py#L17

Make a new reporting method, or otherwise remove this.

**Comment by 0x00B1** [comment]
Yeah, this will be resolved by #1886.

**Comment by dlogan** [comment]
Sounds good, closing
