### ISSUE TITLE
what GUI software do you use to design CellProfiler's ui?

### ISSUE THREAD

**Issue by xueshirong** [CellProfiler/CellProfiler#1953]
I am a learner of CellProfiler. I just wonder what software of tool you use to design the ui?
For example, I used visual studio to design the window form, like add button or change background.

**Comment by LeeKamentsky** [comment]
Hi,
We use wx for the UI widgets, but the actual design is done manually without a design framework. Most of the elements have to be shown in the context of a resizable window, so sizers instead of fixed coordinates are used to do the layout.
--Lee
