### ISSUE TITLE
Error while loading pipeline 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#1962]
Running nightly b65341c, importing a pipeline from another nightly build gives the following error: 
```Error while loading None: Unknown mat file type, version 47, 47
Do you want to stop processing?```
Runs ok in Mac per David but not on Windows

**Comment by dlogan** [comment]
[Malaria_Phenix_Main_pipeline_CP20160408.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/219290/Malaria_Phenix_Main_pipeline_CP20160408.cppipe.zip)

**Comment by dlogan** [comment]
Never mind, this is likely not a bug and a downloading issue.

**Comment by 0x00B1** [comment]
I just realized @bethac07 is Beth. Hi, Beth!
