### ISSUE TITLE
Windows randomly opening and closing during run

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#1963]
Running the nightly rev b65341c on Windows- even though I don't have it set to show any output during the run, it keeps opening and closing "phantom" windows for fractions of a second, which causes it to run into the error from  #1768 .  Thought it should be separate issue as the problem is really the opening/closing windows, not the other bug.  

`Traceback (most recent call last):
  File "cellprofiler\gui\cpfigure.pyc", line 523, in on_close
  File "wx\_core.pyc", line 12107, in Delete
PyAssertionError: C++ assertion "item" failed at ..\..\src\common\menucmn.cpp(455) in wxMenuBase::Delete(): invalid item in wxMenu::Delete`

I'd upload the pipeline but Git keeps saying it doesn't support my file type even though my file type is .zip.  It's in the BhatiaMalaria folder of the projects Git.

![clipboard](https://cloud.githubusercontent.com/assets/6721515/14539920/a09d2f3a-0250-11e6-90e5-dd24aedadead.jpg)

**Comment by 0x00B1** [comment]
Spooky :ghost: :ghost: :ghost: 

I agree that it’s a separate issue (but it’s likely be resolved by the same fix).

**Comment by 0x00B1** [comment]
(I don’t know what that fix is, but I guess it’s related to Lee’s comment about populating and de-populating the menu.)
