### ISSUE TITLE
Using OS background color = Ugh!

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1971]
No disrespect, but using the Windows default background color for CP (e138cdaad9736568939a1d84d584fa2269e8f097) looks pretty horrible:
![image](https://cloud.githubusercontent.com/assets/1186440/14654605/84bdf394-064c-11e6-9600-6087edcb4e64.png)

**Comment by braymp** [comment]
Poking around: wx.NullColor might be better? http://www.blog.pythonlibrary.org/2009/09/03/wxpython-resetting-the-background-color/

**Comment by 0x00B1** [comment]
hahaha

**Comment by 0x00B1** [comment]
Fixing now. Eek!

**Comment by 0x00B1** [comment]
"Horrible" was charitable BTW. I would say "non-functional."

**Comment by 0x00B1** [comment]
@braymp would you mind testing #1980?

**Comment by braymp** [comment]
Nope, still looks black.

**Comment by braymp** [comment]
http://trac.wxwidgets.org/ticket/12389

**Comment by braymp** [comment]
I would actually say this is a show-stopper for publicizing the 2.2.0 release...

**Comment by 0x00B1** [comment]
This is not in 2.2.0.

**Comment by 0x00B1** [comment]
Fixed and merged: 

![windows_10_x64](https://cloud.githubusercontent.com/assets/315821/14793291/5f4bd92e-0aec-11e6-8ede-b3fdca445fc2.png)
