### ISSUE TITLE
There is no updated CP manual

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1972]
At least, no updated manual that I know of!  I was going to add a link to the new download/releases page, but the old download page html manual links here: http://cellprofiler.org/manuals.html which indeed loads, but says it 

> This manual accompanies version 2014-07-23T17:45:00 6c2d896 of CellProfiler. The most recent manual is available [here](http://www.cellprofiler.org/CPmanual/).

but that last link is dead
[EDIT: The link probably just needs to point to S3 cloudfront, but this is presumably best done when the manual is built?]

**Comment by AnneCarpenter** [comment]
Wow, this is pretty important to fix. 

A few additional notes:
1) The URL within CP that  you get when choosing Help > Online Manual goes here (which is the 2014 version):
http://d1zymp9ayga15t.cloudfront.net/CPmanual/index.html
2) On the page cited in (1), there is a link to the "website" that is outdated and goes somewhere weird.
3) As David states, clicking "here" goes to a 404 not found.

I don't know whether there is a more recent HTML or PDF manual, but either way this all needs updating! A current HTML manual is especially helpful when googling.

**Comment by AnneCarpenter** [comment]
Marking as "easy" but needs clarification from @0x00b1 or @mcquin - please tell us everything you know about how the manual is made (if nothing, then we resort to the instructions on our internal wiki).

**Comment by mcquin** [comment]
The manual has been updated. It it built using Sphinx and should be manually updated to AWS with each CellProfiler release.
