### ISSUE TITLE
Windows 2.2.1 stable download link points to 2.1.1

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#1974]
Let me know if there's a better place than the git to put stuff like this in the future.
@0x00B1

**Comment by dlogan** [comment]
Thanks Beth!  Yes, we have noted this internally and Allen is working on it.  I added a note on the releases page just now alerting folks.

FYI, CellProfiler website issues have their own github site and issues, here: https://github.com/CellProfiler/cellprofiler.github.io/issues 
I'll close this here, but open another stub in the above repo, no problem.

**Comment by bethac07** [comment]
Thanks David!  That's why I asked, I didn't think this was the right place but wasn't sure where it was.  Much obliged!

**Comment by 0x00B1** [comment]
Nonetheless, thanks @bethac07. And thanks @dlogan for enforcing!
