### ISSUE TITLE
Add (back?) sash to Module Notes window in main UI

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1975]
Make Module Notes window expandable.  I thought this used to be the case?

Possibly also make it collapsible, see #572

**Comment by 0x00B1** [comment]
sash?

**Comment by dlogan** [comment]
From https://en.wiktionary.org/wiki/sash
```
(software, graphical user interface) A draggable vertical or horizontal bar used to adjust the relative sizes of two adjacent windows.
```

Same as "Splitter" I think
