### ISSUE TITLE
Post-processing hangs with MATLAB output file format

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#1976]
Running CellProfiler in Beta 2.2.0rc2 rev 1b13225 in Windows 64-bit.

When this pipeline was run it hangs after export_to_spreadsheet, the last module. This happens only when MATLAB output is selected and not with HDF5 or none.

[pipeline_2016_04_05_TMEM119-Abeta.zip](https://github.com/CellProfiler/CellProfiler/files/230228/pipeline_2016_04_05_TMEM119-Abeta.zip)

**Comment by 0x00B1** [comment]
Hangs? How do you know?

**Comment by 0x00B1** [comment]
Windows excessively throws a “Not Responding” message when running CellProfiler.

While this is also an issue, it’s a separate issue.

**Comment by karhohs** [comment]
It is true that there is an excessive "Not Responding" message associated with the hang, but I ran this pipeline without the MATLAB output and it took 1 minute. I waited 20 minutes with the MATLAB output before giving up. I did not see an error thrown, but this is undesirable and it seems to depend on the MATLAB output option.

**Comment by AnneCarpenter** [comment]
Hm, MATLAB output is pretty rare these days, so not so many people are clamoring for bug fixes there... @karhohs is this an ongoing problem for a particular project? If so feel free to re-open, otherwise we will focus energy on more critical issues.
