### ISSUE TITLE
A request for more descriptive errors when image dimensions disagree.

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#1977]
Currently, if the dimensions of images disagree Cellprofiler will throw an error that references numpy, but does not explicitly indicate what is wrong. The troubleshooting would be much easier if the error contained a message to the effect of "The source images must have the same width and height."

**Comment by 0x00B1** [comment]
Can you provide an example?

**Comment by karhohs** [comment]
![image](https://cloud.githubusercontent.com/assets/156232/14719636/5bd9052e-07cb-11e6-9a6b-752f009ee6f6.png)

I'd consider this a minor issue, because it is clear the dimensions don't match. However, I did not immediately realize that these numbers were related to the image dimensions, because I did not suspect this would be an issue, the error was thrown late in the pipeline, and the numbers in the error were not contextualized with common vocabulary, e.g. the "shapes" refer to images.

**Comment by 0x00B1** [comment]
Would you mind writing an appropriate error message?

**Comment by AnneCarpenter** [comment]
"This module requires that images in the same set have matching widths and matching heights."

This is a little awkward and improvements are welcome; I was trying to avoid "must have same width and height" because that implies that for each image width = height.

**Comment by AnneCarpenter** [comment]
I think this is ready to do.
