### ISSUE TITLE
Cellprofiler 2.2.0 (PR 1), the javabridge error in windows 8.1 64bit

### ISSUE THREAD

**Issue by xueshirong** [CellProfiler/CellProfiler#1979]
I download the source code of ellprofiler 2.2.0 (PR 1) and install the related package. Now, when I try to run the source code, there is an error about javabridge as follow:
--------------------------------------------------------------------------------------------------------
"D:\Program Files\Anaconda\python.exe" D:/CellProfiler-2.2.0-PR.1/CellProfiler.py
Traceback (most recent call last):
  File "D:/CellProfiler-2.2.0-PR.1/CellProfiler.py", line 4, in <module>
    cellprofiler.__main__.main()
  File "D:\CellProfiler-2.2.0-PR.1\cellprofiler\__main__.py", line 175, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "D:\CellProfiler-2.2.0-PR.1\cellprofiler\utilities\cpjvm.py", line 15, in <module>
    import javabridge
  File "D:\Program Files\Anaconda\lib\site-packages\javabridge\__init__.py", line 28, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "D:\Program Files\Anaconda\lib\site-packages\javabridge\jutil.py", line 155, in <module>
    import javabridge._javabridge as _javabridge
ImportError: DLL load failed: %1 is not a valid Win32 application.

Process finished with exit code 1
----------------------------------------------------------------------------------------------------------
Is there any ideas?

**Comment by 0x00B1** [comment]
What version of Windows?

How did you install javabridge? `pip install javabridge`?

**Comment by xueshirong** [comment]
windows 8.1
Yes, I use "pip install javabridge".
I also download  "javabridge-1.0.14-cp27-cp27m-win_amd64.whl" file, then pip install it.

**Comment by 0x00B1** [comment]
```sh
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

It looks like you need to use the 32-bit wheel:

```sh
javabridge-1.0.14-cp27-cp27m-win32.whl
```

Available from:

http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by 0x00B1** [comment]
You should use `cellprofiler.exe` or `python.exe -m cellprofiler` too.

**Comment by xueshirong** [comment]
“javabridge-1.0.14-cp27-cp27m-win32.whl” can't be installed in my computer.

![qq 20160422105106](https://cloud.githubusercontent.com/assets/3871607/14747078/259ea8b2-0878-11e6-9a36-157a9fdf2189.png)

**Comment by xueshirong** [comment]
You mean that in the terminal, switch to the directory of Cellprofiler source code, run the command "python.exe -m cellprofiler"?

**Comment by xueshirong** [comment]
The thing is that. I also download the "CellProfiler_6c2d8960" source code, when I run this version, it is okay without the error related to javabridge. But for the "CellProfiler-2.2.0-PR.1" source code, there are always the problem of javabridge. I tried to "pip install" javabridge-1.0.14-cp27-cp27m-win_amd64.wh and javabridge-1.0.14-cp27-cp27m-win32.whl, the error is still be there.

**Comment by xueshirong** [comment]
My Ubuntu collapsed. I will restore my system, then try again like you said.
Please leave my issue for some days. Thank you so much.

**Comment by 0x00B1** [comment]
How did you install Python? From python.org?

**Comment by xueshirong** [comment]
I installed Anaconda from https://www.continuum.io/downloads and PyCharm
from https://www.jetbrains.com/pycharm/ .

**Comment by AnneCarpenter** [comment]
Hi there, @xueshirong - are you still having troubles? If so, please re-open the issue and let us know any further details you might have.
