### ISSUE TITLE
JIRA [IMG-687] Tile: add image stitching

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#198]
Someday, we might want to add actual image stitching capabilities to Tile, though I don&#39;t know whether we&#39;ve actually received requests via the Forum for such a feature.  See also<a href="https://jira.broadinstitute.org/browse/IMG-84"title="Tile image stitching"><strike>IMG-84</strike></a>.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-687
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
