### ISSUE TITLE
Figure zoom oddities on Windows

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1982]
Windows 2.2.0rc2 Beta (~2016_03_30) from a virtual machine 
The figure zoom tool works functionally, however there are a couple visual oddities when zooming:
1. An odd hatching appears sometimes
2. Other windows may show no zoom box at all 

See this screen recording for examples of both
http://cl.ly/212S0n1x323J

@karhohs can you confirm this on any recent Windows beta or nightly?

Related to #1844 ?

**Comment by 0x00B1** [comment]
I can't reproduce with master on Windows 10.

**Comment by 0x00B1** [comment]
OK, I was able to reproduce. Open the Image Viewer for the output of Identify Secondary Objects and try zooming in the segmented image.

**Comment by dlogan** [comment]
@karhohs no need to reproduce then.

**Comment by DavidStirling** [comment]
Appears to have been fixed.
