### ISSUE TITLE
Can't select Illumination Function or Objects NamesAndTypes set to All Images 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1992]
Master on Mac
Open a blank pipeline.
In NamesAndTypes, leave "Assign a name to:" = "All images"
You can see that there are only three image types to choose from:
![image](https://cloud.githubusercontent.com/assets/1225595/14923321/8ac7c7a4-0e0a-11e6-9376-46a17f11cf03.png)

Now in NamesAndTypes, change "Assign a name to:" = "Grayscale image"
You can see that there are now five image types to choose from:
![image](https://cloud.githubusercontent.com/assets/1225595/14923330/99ce12bc-0e0a-11e6-9fde-c901d6e85ac6.png)

Maybe this is a feature, but I can't think why.  Probably should show all 5.

**Comment by braymp** [comment]
I think the idea there was to omit more esoteric image types from the simple "I just have one channel" view.

**Comment by dlogan** [comment]
Hmm, I see.  I think it's preferable to show them all -- the default is Grayscale anyway which aligns with the simplest use-case.  I was writing up instructions for folks using ilastik and they might be loading label matrices as inputs, and I could imagine someone wanting to load only Objects.  

I'd prefer to do this sort of simplifying when (if?) we implement the Simple/Advanced Mode, but am ok with ignoring this if others don't agree.

**Comment by AnneCarpenter** [comment]
I think it makes no sense to choose "Illumination Function" if you're choosing all images. I don't see why Objects would be intentionally excluded from the list, though. 

So, for simplicity, it sounds like we are all supportive of putting all 5 options in.

**Comment by DavidStirling** [comment]
I've been looking into this (better late than never!), but it seems that it's not trivial to allow using 'Objects' when not matching with rules. "Assign to everything" mode works very differently and would need a substantial rewrite to be compatible with using objects as well. Since this can easily be worked around by creating a generic rule, I've just added a note to the help text explaining this.
