### ISSUE TITLE
About... dialog version numbers are unclear

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1993]
The two version numbers below are not labeled, and is unclear what they refer to.  
Python is 2.7.10, and CellProfiler is 2.2.0, and they should be labeled as such.

![image](https://cloud.githubusercontent.com/assets/1225595/14926428/29841348-0e1a-11e6-89d6-bb1f3b779724.png)

**Comment by 0x00B1** [comment]
Fixed
