### ISSUE TITLE
Clicking module in pipeline window should not toggle selected/unselected

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2001]
When you click multiple times on a module in the "Analysis modules" (a.k.a. pipeline) window, the module selects and de-selects.  This is an annoyance. E.g. in the video below, if a module is deselected, a user cannot delete the module.  I can't see any reason why a user would want to deselect a module -- at least one module should always be selected at all times (as long as View Output Settings is included too)  

http://cl.ly/0j1q2n1o1b3U

**Comment by bethac07** [comment]
Hi David,
I disagree here- sometimes I select multiple modules to duplicate/move/etc,
and in that case the ability to deselect does come in handy.

**Comment by dlogan** [comment]
I see - @bethac07 you mean if you want to select multiple modules, then deselect one in the middle of the selection?  That is reasonable and I have done that before.

I was thinking of the (most common) case when a user selects one module, and then by accident selects it again, thereby deselecting it.  Would it be ok to make a rule that there should always be at least one module selected?  But still allow deselecting.

**Comment by bethac07** [comment]
That seems fine to me!

**Comment by AnneCarpenter** [comment]
The proposed behavior certainly sounds reasonable. However, if it's time-consuming to fix or if it endangers the behavior Beth describes, then we should abandon the effort and not fix.
