### ISSUE TITLE
ExportToCell5H crashes in beta 2.2

### ISSUE THREAD

**Issue by Fafa87** [CellProfiler/CellProfiler#2003]
I have been working on my plugin for CellProfiler Beta 2.2 (from 03.2016 - havent check the stable version which is not yet available on Windows) and noticed that the module does not load in Analysis but works in Test Mode. Then I realised that it has a partner in crime which is ExportToCell5H.

Stack trace shown in UI is not very helpful:
Traceback (most recent call last):
  File "cellprofiler\analysis_worker.pyc", line 365, in do_job
  File "cellprofiler\pipeline.pyc", line 1095, in loadtxt
  File "cellprofiler\pipeline.pyc", line 731, in instantiate_module
  File "cellprofiler\modules__init__.pyc", line 391, in instantiate_module
  File "cellprofiler\modules__init__.pyc", line 387, in get_module_class
ValueError: Could not find the ExportToCellH5 module

But console reveals the problem
![image](https://cloud.githubusercontent.com/assets/9865688/15008005/4fa23e58-11dd-11e6-80e3-39d161bf9312.png)

It seems that CellProfiler cannot load pyplot as it goes for tkagg which is not available. 

In case of my module it is used only for debug that I can turn off.
However this might not be the case for ExportToCell5H  so unless it is already fixed, it makes using ExportToCell5H impossible.

:

**Comment by 0x00B1** [comment]
We could package the tk backend to resolve the immediate problem. But we should probably figure out why cellh5 is trying to use the tk rather than the wx backend. Are you seeing this problem with other modules?

You should also try using the beta from mid-April. I might've updated the packaging between versions.

**Comment by 0x00B1** [comment]
P.S. What's the new module??? 🤓

**Comment by Fafa87** [comment]
> Are you seeing this problem with other modules?
None of the ones that I use.

At http://cellprofiler.org/releases/ the dates are updated to April but in case of Windows, links go to the same file. Seems like something got lost in the way.

> P.S. What's the new module???
Well, CellStar segmentation but I think we are already in touch.

**Comment by AnneCarpenter** [comment]
Any further updates on this, guys? @Fafa87 are you still having this issue with more recent betas or nightly bulids?

**Comment by Fafa87** [comment]
No version from http://cellprofiler.org/releases/ (stable, beta, nightly) is working so it is still an issue.

**Comment by seanwarren** [comment]
Hello, I am also also encountering this issue in Cellprofiler 2.2.0 (rev ac0529e) on Windows 7 using the ExportToCellH5 plugin. The error message I get is:

> Traceback (most recent call last):
  File "cellprofiler\analysis_worker.pyc", line 354, in do_job
  File "cellprofiler\pipeline.pyc", line 1095, in loadtxt
  File "cellprofiler\pipeline.pyc", line 731, in instantiate_module
  File "cellprofiler\modules\__init__.pyc", line 393, in instantiate_module
  File "cellprofiler\modules\__init__.pyc", line 389, in get_module_class
ValueError: Could not find the ExportToCellH5 module

Is there a known workaround for this?

**Comment by mcquin** [comment]
CellH5 has been removed.
