### ISSUE TITLE
Pipeline when choosing "Load an example pipeline" from Welcome Screen yields warning

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2016]
New users who have just downloaded CP and clicked  "Load an example pipeline" from the Welcome Screen are greeted with the attached warning which seems scary. 

One option: update the pipeline w each new release of CP and place it at the same URL. It would solve this problem but people using older versions of CP will obtain an error when loading the latest pipeline (because it was made w a newer version of CP).

So, there may not be a great solution here other than placing a new pipeline at a new URL, and changing the URL this link goes to, for each new version of CP, to keep them compatible. That seems a bit annoying. Maybe there are other solutions?

![warning](https://cloud.githubusercontent.com/assets/1213811/15061717/76c17d94-1306-11e6-889c-31ef6c8f2ce0.jpg)

.

**Comment by 0x00B1** [comment]
One alternative is packaging the example pipeline with CellProfiler.

**Comment by AnneCarpenter** [comment]
Including the example pipeline + images has the added advantage of working if people are working offline. I think that's a simple/elegant solution and I can't think of any reason why it needs to be at a URL instead (other than perhaps we thought it would be nice to have the option to update it and/or we were concerned about file size but I think it's tiny.)

**Comment by AnneCarpenter** [comment]
We think this is fixed. Closing and @0x00b1 will re-open if not.
