### ISSUE TITLE
Adjust contrast in Images module

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2017]
Minor aesthetic point: In the Images module, beforehand the file list panel was pretty clear. Now that the bg color has been altered, it's not as apparent (obvious lettering aside):

![image](https://cloud.githubusercontent.com/assets/1186440/15126244/173868c8-15ff-11e6-8955-84f4cc0b3091.png)
I think it would be nice to have this back to the white background it once was.

**Comment by braymp** [comment]
A similar point can be made for the welcome screen; it should be adjusted to use the system background color as well to make the UI consistent (right now, it appears a paler shade):
![clipboard01](https://cloud.githubusercontent.com/assets/1186440/15126554/82339282-1600-11e6-9fac-b08b6786f72e.png)

**Comment by dlogan** [comment]
And @karhohs, wasn't the file list hard to read for files that were excluded (on Windows)?  I think their text was white on this very light gray background.

**Comment by 0x00B1** [comment]
@braymp mentioned this to me last week during @dlogan’s going-away party. I consider this is a major issue.

However, I think the CellProfiler Welcome is a minor issue. I’d eventually like to make this super slick since it’s just a web view.
