### ISSUE TITLE
GTKSendPaintEvent(): unsupported background style

### ISSUE THREAD

**Issue by blikzen** [CellProfiler/CellProfiler#2020]
Hi,

I installed using the PyPI instructions, and I'm running into an issue with a pipeline I'm running. It was running fine for the first set of 80 image sets, but the set that I'm currently processing has been hung for about 16hrs, and I'm not sure what the issue is. This is the most recent bash readout:

Worker 3: Wed May 11 18:04:39 2016: Image # 84, module IdentifyPrimaryObjects # 5: 1.76 secs
Worker 3: Running module IdentifyPrimaryObjects 6
Progress Counter({u'Unprocessed': 4236, u'Done': 80, u'InProcess': 3, u'FinishedWaitingMeasurements': 1})
Worker 2: Starting job
Progress Counter({u'Unprocessed': 4235, u'Done': 81, u'InProcess': 4})
Previously displayed uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/buttons.py", line 148, in GetDefaultAttributes
    return wx.Button.GetClassDefaultAttributes()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 247, in GetClassDefaultAttributes
    return _controls_.Button_GetClassDefaultAttributes(*args, **kwargs)
PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4096) in GTKSendPaintEvents(): unsupported background style
Previously displayed uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/buttons.py", line 148, in GetDefaultAttributes
    return wx.Button.GetClassDefaultAttributes()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 247, in GetClassDefaultAttributes
    return _controls_.Button_GetClassDefaultAttributes(*args, **kwargs)
PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4096) in GTKSendPaintEvents(): unsupported background style
Previously displayed uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/buttons.py", line 148, in GetDefaultAttributes
    return wx.Button.GetClassDefaultAttributes()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 247, in GetClassDefaultAttributes
    return _controls_.Button_GetClassDefaultAttributes(*args, **kwargs)
PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4096) in GTKSendPaintEvents(): unsupported background style
Previously displayed uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/buttons.py", line 148, in GetDefaultAttributes
    return wx.Button.GetClassDefaultAttributes()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 247, in GetClassDefaultAttributes
    return _controls_.Button_GetClassDefaultAttributes(*args, **kwargs)
PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4096) in GTKSendPaintEvents(): unsupported background style
Previously displayed uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/buttons.py", line 148, in GetDefaultAttributes
    return wx.Button.GetClassDefaultAttributes()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.py", line 247, in GetClassDefaultAttributes
    return _controls_.Button_GetClassDefaultAttributes(*args, **kwargs)
PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4096) in GTKSendPaintEvents(): unsupported background style

I found a similar issue on google, suggesting there might be some issue with a local anaconda installation, but that shouldn't be an issue on my end, so I'm just trying to wrap my head around this and figure out what the problem is. I looked at the image files themselves and there doesn't look there is an issue, so I'm thinking it's probably something to do with my systems configuration. Or maybe even resource allocation. I did a top and the process is at ~35% cpu load, and over 16Gb of memory. On this machine I only have 6Gb of actual RAM, the rest is swap. Could that be the issue with the slow down?

Thanks for any help,
Martin

**Comment by 0x00B1** [comment]
How did you install wxPython?

**Comment by blikzen** [comment]
not entirely sure. im not really a python guy, and i get confused by the version issues between apt and pip installs. i dont think it was through apt, because it's not in my sources. best way to purge then reinstall properly?

**Comment by blikzen** [comment]
it looks like it's actually installed through apt:

python-wxgtk3.0/stable,now 3.0.1.1+dfsg-2 amd64 [installed,automatic]

**Comment by 0x00B1** [comment]
If you want to use Anaconda, I’d consider uninstalling wxPython with apt-get and reinstalling it with Anaconda. It should work. 😄

**Comment by blikzen** [comment]
im really not a python guy, so the difference is most likely lost on me. i can try it. do i need to change the path for python in cellprofiler then, otherwise wouldn't it be running off of the non-anaconda python?

**Comment by AnneCarpenter** [comment]
@blikzen Are you still needing assistance? If so, feel free to re-open this issue!
