### ISSUE TITLE
Mouseover of images no longer shows pixel intensity in 2.4

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2021]
Not sure if it was accidentally removed or left as part of the recent UI cleanup, but it's been noted as missing in the forum and I agree that it's a nice thing to have.
http://forum.cellprofiler.org/t/bug-in-cp2-4-0-does-not-show-pixel-intensities/3521

**Comment by 0x00B1** [comment]
@bethac07 Where was this located?

@tischi Feel free to write issues on GitHub. You know we love you!

**Comment by bethac07** [comment]
Not sure if you mean a) where in the window did this used to be or b) in what windows did I notice this so
A) down on the bottom frame, next to the x and y coordinate widgets
B) I tried it in the "load images" and an "ImageMath" window, it's gone from both

**Comment by 0x00B1** [comment]
I was asking where it used to be. :)

**Comment by tischi** [comment]
Hello, **every** module window, e.g. ImageMath or Smooth, showed the X,Y, and Intensity values at the bottom of each window. In 2.4 it only shows the X and Y values. And frankly, for scientific image analysis this is not only a "nice to have" but a "must have" :-)

**Comment by dlogan** [comment]
Please see this video below of where this simple, but critical, functionality is now missing. On the left is a CP 2.2 window which shows intensity in the lower-right portion of the window, and on the right is the latest Windows nightly build which is missing this info: 
https://cl.ly/042l1h2V021l

**Comment by AnneCarpenter** [comment]
Note that this functionality is requested in CPA as well; however, it sounds pretty complex so unless it's resolved pretty nicely here in CP, we don't likely want to add to CPA (where we try to minimize maintenance):
 https://github.com/CellProfiler/CellProfiler-Analyst/issues/206

**Comment by AnneCarpenter** [comment]
Note that this functionality is mentioned in the Threshold module as follows (I assume it's best to leave documentation as is for now):
"To view pixel intensities in an open image, use the pixel intensity tool which is available in any open display window. When you move your mouse over the image, the pixel intensities will appear in the bottom bar of the display window. "
