### ISSUE TITLE
JIRA [IMG-640] Deprecate DisplayGridInfo functionality into DisplayDataOnImage

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#203]
It seems that the functionality of DisplayGridInfo can be replicated with DisplayDataOnImage, provided that the LoadData metadata can linked with grid element location information generated by IdentifyObjsInGrid.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-640
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
