### ISSUE TITLE
Slider has disappeared in test mode

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2032]
In 9cad7ea (after all the changes to the icons and such, which I like), the slide has disspeared in test mode:
![image](https://cloud.githubusercontent.com/assets/1186440/15291074/3bba05d0-1b4a-11e6-96d1-aafaefefe1a9.png)
Not the most horrible thing in the world, but it makes it more difficult to find where you are when stepping through the pipeline.

Also, I noticed that the warning icon is still using the old format.

**Comment by 0x00B1** [comment]
This was intentional. 😄 

(However, the item you’re on should be selected.)

**Comment by 0x00B1** [comment]
P.S. Any other thoughts about the icons?

**Comment by braymp** [comment]
I also saw that the warning icon is still the same as it was (see the above
screenshot); perhaps it didn't get updated?

**Comment by 0x00B1** [comment]
Yeah, I need to update a few more icons. Warning, error, pause, play, skip, etc.

**Comment by bethac07** [comment]
Why the decision to get rid of the slider if I may ask? With no slider and
no Workspace Viewer, it's going to make running/troubleshooting in test
mode much harder :-/ .

**Comment by 0x00B1** [comment]
It was an aesthetic decision. However, it isn’t gone entirely. The running module should be highlighted.

**Comment by braymp** [comment]
The slider also allowed for the pipeline to be re-run in test mode starting
from a given point (by pulling the slider to the start point). Does
selecting the module do the same thing?

**Comment by bethac07** [comment]
Yeah, that's the functionality I'm concerned about losing- being able to
drag back a few steps and re-run things to either change them or even just
to re-generate the output window to double check what the output was(hence
the allusion to WorkspaceViewer).  It's a pretty important tool to have.

**Comment by AnneCarpenter** [comment]
This might be a good time to chime in that I always found the slider behavior confusing. I was never quite sure whether it was placed before or after the module in question, and whether it was a start point vs end point. For example, I wasn't sure whether it always ran from the beginning up to the stop point or now. I rarely used it, so of course I could have figured it out... eventually. 

Sounds like this functionality is critical but perhaps some brainstorming about the actual UI is in order if we are willing to re-think it!

**Comment by bethac07** [comment]
Hmmm, I found it very intuitive, but just goes to show that these things are always YMMV!

If not a slider, what about an ability to right-click a module while in Test Mode and say "Re-run from this module" or something like that?

**Comment by AnneCarpenter** [comment]
Makes sense. I'm worried that right-clicking is pretty hidden for a lot of folks, so even if we have that it would be best to offer an alternative. Allen @0x00B1 , I'm confused: highlighting is supposed to signify the location of the slider but then what happens when you click on a module to look at its settings, wouldn't that also be highlighted? (I'm not looking at the UI so might be missing something)

**Comment by braymp** [comment]
Another issue I just remembered (similar to @bethac07) is that the slider
is handy when you use drag/drop to rearrange modules. The pipeline may not
be invalidated in test mode, but running it outright may cause an error.
The slider indicates where the last valid state was, which is different
than which module is highlighted.

**Comment by bethac07** [comment]
I know it seems like a super small thing, but can we not close this yet?  In practice this makes the UI much harder to deal with.  I'm not dead set on it being a slider, but some ability to a) see where you are in the pipeline and b) jump instantly to a different part of the pipeline is crucial for day-to-day usage of the software.  Happy to help brainstorm alternatives to the slider if the slider is hated, but something is needed.

**Comment by mcquin** [comment]
Let's create a new issue to design a new feature.

**Comment by bethac07** [comment]
#2712
