### ISSUE TITLE
Add Global gray-level thresholding based on object size

### ISSUE THREAD

**Issue by PetterRanefall** [CellProfiler/CellProfiler#2035]
Hi,
I have tried to do a new pull request but it seemed like I didn't have permission send it. How is the procedure for pull requests?

This one is about an Object Feature based Gray-level Threshold using optimized global precision. It computes the threshold level that optimized the global precision with regards to a given expected object size range.
Implemented from Ranefall P and Wählby C, "Global Gray-level Thresholding Based on Object Size", Cytometry Part A, 89:4, 2016, pp. 385-390. In this paper we show that the method performs better that all global threshold methods in CellProfiler and ImageJ, given that you can input a range of expected object sizes.

In my pull request I have incorporated it into ApplyThreshold, IdentifyPrimaryObjects, and IdentifySecondaryObjects.

The following files are modified: applythreshold.py, identify.py, threshold.py, test_threshold.py
New files: sizeintervalprecision.py, _sizeIntervalPrecision.c

Earlier I have been in contact with Lee regarding a plugin based on this, but it would be nice to have it integrated into the IdentifyPrimaryObjects and ApplyThreshold modules.

**Comment by mcquin** [comment]
@PetterRanefall You need to fork CellProfiler and submit your pull request from there. [Documentation on forks](https://help.github.com/articles/fork-a-repo/).

**Comment by AnneCarpenter** [comment]
And sorry it took so long to reply! We have been catching up on a backlog.

**Comment by PetterRanefall** [comment]
Thanks for the reply. Previously I tried to do it from my GitHub GUI, but now I have tried to do it from github.com and then I came a lot further. However, since using GitHub is new to me, I am not sure if I made the pull request correctly. I would appreciate if you let me know if you can see the pull requests. They should be in CellProfiler\cellprofiler\modules and in CellProfiler\centrosome

**Comment by bethac07** [comment]
Hi Peter,
You actually haven't quite managed it yet- you made pull requests within your own fork, as opposed to back to the main copy of CP (or "upstream" in git terms).  Git is super confusing sometimes, I say this from personal experience!

Here for example I've made a branch called "EditHelp" in my own fork of the Distributed-CellProfiler repository.  Create your pull request, then click the link to "compare across forks"
![image](https://cloud.githubusercontent.com/assets/6721515/18712368/1d088188-7fdc-11e6-9cc8-31b430cc42ab.png)

Now edit the base fork- here I'm pushing to the parent repository of Distributed-CellProfiler just as an example, but you want to change this base fork to CellProfiler/CellProfiler, master branch.  
![image](https://cloud.githubusercontent.com/assets/6721515/18712482/9eeb4c26-7fdc-11e6-995a-c489824b783f.png)

It'll tell you that the changes can't be automatically merged but that you can make the pull request anyway, just like in my screenshot here.  You can check the pull request list at the main [CellProfiler](https://github.com/CellProfiler/CellProfiler/pulls) and [centrosome](https://github.com/CellProfiler/centrosome/pulls) pages here afterwards to confirm that the request went to the right place.

**Comment by PetterRanefall** [comment]
Yes, I suspected that. Now I have made a new attempt by using "compare across forks".
