### ISSUE TITLE
JIRA [IMG-628] CorrectIllumination: Set illm function flag in Calc so Apply knows to divide or subtract

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#204]
Users occasionally run the risk of inappropriately divide/subtracting their illum fxn in Apply contrary to what they chose for Calc. It might be nice to set a flag for the illum fxn in Calc, such that when it is selected in Apply, the settings reflect the Calc choice.<br/><br/>However, the user should still have the option of overriding this setting, since Calc/Apply can be put to a variety of unorthodox uses.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-628
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
