### ISSUE TITLE
Command-line interface cleanup

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2044]
- [x] #2045 
- [x] #2046
- [x] #2047
- [x] #2048
- [x] #2049
- [x] #2050
- [x] #2051
- [x] #2052
- [ ] #2053
- [x] #2054
- [x] #2055
- [x] #2056
- [x] #2057
- [x] #2058
- [ ] #2059

**Comment by mcquin** [comment]
We have projects now, bro.
