### ISSUE TITLE
Remove `add-message-for-user` command-line option

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#2047]

**Comment by braymp** [comment]
I'm a bit on the fence about this one. We put it in so we could easily annotate the example pipelines; you'll notice that when you load one, a msg pops up telling you what do next. I guess one can manually insert it into the pipeline...

**Comment by 0x00B1** [comment]
I’m on the fence too.

My reasoning was simple: it’s a hidden and undocumented feature that’s only used by us.
