### ISSUE TITLE
Error (bug?) when manually editing objects on mac

### ISSUE THREAD

**Issue by embruce** [CellProfiler/CellProfiler#2060]
I am unable to manually split objects in the "EditObjectsManually" mode (ie, edit my automatic nuclei segmentation to correct for when two nuclei are classified incorrectly as one).  I can't manually split an object without Cell Profiler giving me an error "Exception in CellProfiler core processing", which freezes the program.  After this error appears, I cannot do anything else (ie, clicking the "Continue processing..." or Send report" buttons does not close the "Pipeline error" box, and I while I can move around the other windows in CellProfiler everything is grayed out and I can't close that error box.  This error occurs both in test mode and while actually analyzing images. 

 I am using a Mid 2015 MacBookPro with OS X Yosemite, and CellProfiler 2.2.0 and the newest version of Java.  My lab mate can run this exact pipeline on his PC and has no difficulty segmenting the nuclei.

**Comment by mcquin** [comment]
Resolved https://github.com/CellProfiler/CellProfiler/pull/3431
