### ISSUE TITLE
Missing Log and Error from Names and Types

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2069]
[video explanation](http://screencast.com/t/7byl7xiHJ)

I see an error dialog that refers to a log that I cannot find. The error is specific to NamesAndTypes, because this is the only modification I made to an existing pipeline and I get the error when I click _Update_. I also get this error when I click the _Analyze Images_ button, which is shown in the video.

The error was triggered by an incomplete set of images. One image, from a set of 3, was missing or deleted.

**Comment by braymp** [comment]
See https://github.com/CellProfiler/CellProfiler/issues/1124

**Comment by karhohs** [comment]
That explains it :+1:
