### ISSUE TITLE
Remove cellprofiler.image.readc01

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2078]

**Comment by braymp** [comment]
Would suggest two things:
* Confirming whether Bioformats supports format or not (my guess is 'no')
* If not, make sure .c01 is removed from recognized extensions

This format is from Cellomics, a microscope vendor, so I would think twice before removing it; folks may still have use of it.

**Comment by 0x00B1** [comment]
Thanks, @braymp! Useful information. Are you saying someone is using this from private modules?

**Comment by 0x00B1** [comment]
It looks like BioFormats supports Cellomics (i.e. .c01 and .dib):

http://www.openmicroscopy.org/site/support/bio-formats5.1/supported-formats.html

However, if people are still using this, I'll need to revert and wrap the BioFormats call.

**Comment by braymp** [comment]
No, not really from private modules. I mean .c01 was a recognized format in the Images module (so it would be included if you selected "Images only"), and the Input modules in general dealt with it like any other image. However, I can't speak to how widespread the usage is in the microscopy community.

**Comment by braymp** [comment]
Also see https://github.com/CellProfiler/CellProfiler/issues/1043
