### ISSUE TITLE
Error Saving Image to Same Folder as Image

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2086]
![image](https://cloud.githubusercontent.com/assets/156232/15874768/dcb87e1e-2cd2-11e6-94ec-244890eb60d4.png)

The _SaveImages_ module throws an error when trying to save to the same folder as an image.

[video explanation](http://screencast.com/t/lE0gPe8f8Qu)

**Comment by braymp** [comment]
Duplicate of #1325.
