### ISSUE TITLE
ImageMath behaves differently when it's dragged and dropped vs added directly

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2092]
Long drawn out explantion below.   TL;DR ImageMath correctly "Ignore[s] the image masks" when instructed if you've added it via "add module", it does not ignore the masks when it has been dragged and dropped into the pipeline from another CP window.  Reading the pipeline line-by-line confirms that "Ignore the image masks" is set to yes, it just doesn't do it.  

---

So I have a weird one for you- was working on 2 different pipelines (same version of CP, the 2.2.0 beta)- A and B for simplicity.  "A" had a step where a class of nuclei were found, they were masked from the original image, allowing segmentation of another nuclei.   To measure stuff about all nuclei, I used 2x "ConvertObjectsToImage", an ImageMath to add them (where it's instructed to ignore the previous masking since we want those nuclei back), followed by a final IdentifyPrimary step with a super-low manual threshold to get them all.  It's inelegant but it works.  You can see below that all of the spots are circled.
![originalmasking](https://cloud.githubusercontent.com/assets/6721515/16094717/8420172e-330f-11e6-9073-635599bf7b29.jpg)

I was working on a parallel way to segment these images in "B" and decided that a similar masking approach would be helpful, so I dragged and dropped the relevant modules into B- now whatever I did, it refused to ignore the image masking.  If I add the same exact modules manually into B, it ignores the mask correctly- see left vs right below.  Read over the .cppipe files, everything is set the same between the two, it just doesn't obey.
![draganddropmasking](https://cloud.githubusercontent.com/assets/6721515/16094865/1e6f2978-3310-11e6-8c9f-6b89432e4636.jpg)

Ideas?  Is this like, a known thing that you shouldn't drag and drop modules between windows?

**Comment by DavidStirling** [comment]
Do we know if this is still a problem in 3.0? I'm struggling to replicate this and can't imagine how this could occur in the current version of the module.

**Comment by bethac07** [comment]
(when I read the issue title in my email was like "what crazy-@$$ nonsense is this, must have been before my time)

I just verified the behavior was correct in 3.1.9, at least for Mac, so if you also can't verify in Windows (which is where this was initially reported) we can close.

To verify:

- open two copies of CellProfiler, load welcome screen pipeline+images in each. 
- In one import the pipeline below (keeping the welcome screen images).  
- In the other, delete IDPrimary, and drag-and-drop across the 7-module-suite from the first one that starts and ends with IDPrimary (plus one in the middle) into its place between Crop and IDSecondary.
- Run in test mode as far as the 3rd IDPrimary.  If it looks like the first screenshot, the bug is fixed; if it looks like the second, it's not.


[issues_2092.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/4345463/issues_2092.cppipe.zip)
![image](https://user-images.githubusercontent.com/6721515/76895341-2e3e2900-6866-11ea-9121-983de88e85fc.png)
![image](https://user-images.githubusercontent.com/6721515/76895364-3bf3ae80-6866-11ea-94fa-fef4c21e3113.png)

**Comment by DavidStirling** [comment]
Thanks, confirmed that this is fixed.
