### ISSUE TITLE
CP 2.2.0 can’t set "Manual" bit depth for more than one image?

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2095]
I've tested this on Windows and Ubuntu 15.10. When I add more than one image in NamesAndTypes, it does not allow me to set the bit depth manually. There is no corresponding text box, and I can not add more images anymore. See attached screenshot, the value field for the second image is missing, and I can'T add more images as soon as I set to "Manual":
![841f505a4527bf7c9d6b56690f54c08e5a17ed70](https://cloud.githubusercontent.com/assets/1098087/16127659/b241229e-33fd-11e6-9bbe-016c2be31af6.png)

**Comment by bethac07** [comment]
Noted from the forum, this still happens in 3.1.8 :-/
