### ISSUE TITLE
Dissappearing module labels in 2.2.0

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2097]
To replicate in master (I hope):
- Load the welcome screen pipeline
- Click the 1st analysis module (i.e., Crop)

The other module labels disappear until they are clicked on. Definitely occurs on Windows, but maybe other OSes as well?
![image](https://cloud.githubusercontent.com/assets/1186440/16129863/a5935720-33d4-11e6-8c01-ef2e57ff0315.png)

**Comment by AnneCarpenter** [comment]
Is this still a problem @braymp ? i.e. in nightly builds or newer beta? (though not sure there is a newer one since this filing)

**Comment by braymp** [comment]
I should clarify that this does not seem to occur on the 2.2.0 stable build nor the 2.3.0 beta or 2.4.0 nightly (though I do notice that the settings panel refresh is not as prompt as it once was).

However, it does still occur on master (which is 7fed55c as of this writing). Also another funny thing I just noticed since I had my browser open on top of CP master, with the pipeline panel peeking out to the left. When I shift focus to the browser, the labels come back (see below). If I go back to CP, they disappear again.

![image](https://cloud.githubusercontent.com/assets/1186440/18322738/310f03a8-7502-11e6-8ad4-64eb94eb0abc.png)
