### ISSUE TITLE
Redraw on Linux selects the whole entry field, making typing impossible

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2098]
I have been plagued by a CellProfiler 2 issue on Linux since several years: when entering text in any of the text fields, there seem to happen timed update events that "select" the whole text entry field. See attached screenshot for an example. Due to the selection, its impossible to enter further text because it will erase the field. In attached screenshot, the current text field for "CorrPathogen" was automatically "fully selected" before I could finish writing the text:
![cp-screenshot-cellprofiler2 2 0 rev1b52569 _008](https://cloud.githubusercontent.com/assets/1098087/16143365/8aaaca0e-346c-11e6-99e8-ca53afe82cf3.png)

These update events seem to happen every second or so, making it impossible to type longer names or numbers.

**Comment by emmenlau** [comment]
I could trace this back to `focus_control.SetFocus()` in `def do_reset(self):` in `cellprofiler/gui/moduleview.py`. When I disable SetFocus() then instead of a fully selected text field I get an unselected text field, making typing equally impossible.

**Comment by emmenlau** [comment]
A possible solution for this issue is in https://github.com/CellProfiler/CellProfiler/pull/2099
The downside with my solution is that it will clear a possible selection in case the user did select something. It will also place the cursor at the end of the text box in case the user moved the cursor. It is therefore not a perfect solution. Better would be to store the selection and cursor position before updating the gui, and setting the same properties after the update.

**Comment by braymp** [comment]
I've run afoul of this issue as well; quite annoying.

**Comment by emmenlau** [comment]
Did you experience this on Linux, Mac or Windows? Or multiple of them? I've used only Linux so I thought I'm the only one affected :-)

PS: I've implemented a workaround for this, and for another multi-redraw issue in my pull request above. Its not a perfect solution because it has still a few issues, but its better than the previous behavior :-)

**Comment by braymp** [comment]
Linux only in my case.

**Comment by mcquin** [comment]
https://github.com/CellProfiler/CellProfiler/pull/2099
