### ISSUE TITLE
Image contrast in figures is not remembered in test mode

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2101]
I'm stepping through a number of images to better understand tracking. The figure window (of GrayToColor, but probably others are affected too?) does not remember the setting of "Image Contrast" to "log normalized" whenever I step.

I think its a bug and not a feature, because I would assume that a certain kind of visualization is good for a number of images, and should not be reset to default for the next image. What do you think?

**Comment by bethac07** [comment]
While it won't remember it cycle-to-cycle, on 2.2 and higher you can set whether you want to default to "Raw" "Normalized" and "LogNormalized" in the File->Preferences menu.

**Comment by mcquin** [comment]
It is correct behavior to set visualization per image. You can use the suggestion above to set a reasonable overall default.

**Comment by braymp** [comment]
There's the workspace viewer option as well.
