### ISSUE TITLE
Using CTRL-C to copy text clears the text field

### ISSUE THREAD

**Issue by emmenlau** [CellProfiler/CellProfiler#2102]
I often work with batches of settings, and like to use copy-paste for text fields to quickly change many settings. When I select a text field and press CTRL-C to copy, the text field gets cleared.
Observed on Ubuntu 15.10 Linux with default packages, installed according to the wiki instructions.

**Comment by VolkerH** [comment]
+1 on this one. Was just going to open an issue and then found this existing issue. 
Highly annoying. I completely messed up some good pipelines by thinking I was doing "copy and paste" and not looking closely before saving when in fact I had performed a "cut and paste".

Also happens on Mac OS X (sierra in this case) and CP 2.2.0 release version.
Not sure whether this is a problem with PyQT.

**Comment by VolkerH** [comment]
I just saw that this seems to have been addressed in issue #1961

**Comment by 0x00b1** [comment]
@VolkerH Yep. :)
