### ISSUE TITLE
Drag and drop from Omero file list to CellProfiler images module doesn't work in 2.4

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2111]

**Comment by karhohs** [comment]
I'd like to add that the following related behavior does not work: Drag and drop of images into the _Images_ module and of modules from one instance of CP into another.

**Comment by 0x00B1** [comment]
@karhohs create a new issue

**Comment by mcquin** [comment]
Should it?

**Comment by mcquin** [comment]
"Wat" - @0x00b1
