### ISSUE TITLE
Cherry pick 2.4 commits before beta

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2116]
So, what do we want to keep? What do we want to drop?

**Comment by 0x00B1** [comment]
cc: @braymp and @bethac07. 

I’ll drop commits related to interface changes and workspace viewer. Anything else I should drop?

**Comment by 0x00B1** [comment]
cc: @braymp and @bethac07. 

I’ll drop commits related to interface changes and workspace viewer. Anything else I should drop?

**Comment by 0x00B1** [comment]
And by “drop” I mean “don’t push into the next beta release.”

**Comment by bethac07** [comment]
Sounds good to me!

**Comment by braymp** [comment]
How about some of the cmd-line switches? I think most of them I had no issue with, except for a couple?
