### ISSUE TITLE
Error: 'MySQL server has gone away'

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2131]
When running either 1b13225 (2.2 beta) or 2.1.1 on Windows 10 and trying to run the CellPainting QC pipeline I get the following error after it freezing up for a loooooong time (like an hour)
`Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 2135, in prepare_run
  File "cellprofiler\modules\exporttodatabase.pyc", line 1665, in prepare_run
OperationalError: (2006, 'MySQL server has gone away')
`

Database definitely exists on our imgdb, the "Test connection" button reports it connects successfully.   Pipeline runs fine if I change the DB type to SQLite. 

Nice and poetical though.

**Comment by braymp** [comment]
Sounds like the connection timed out. I can think of two suggestions:
* Test with a smaller # of image sets (1 or 2 wells), to confirm that the run is actually doable.
* If you are using the Input modules, try exporting the image set to a CSV and using LoadData. That way, you bypass the imageset creation, and have a better chance of running in a timely fashion.

**Comment by bethac07** [comment]
Hmmm, yup, that fixed it- I'm surprised that "only" 216 image sets (1080 images total) is enough to break it.  That doesn't seem like super many.
