### ISSUE TITLE
Is there a way to export label map or outline coordinates of individual cells ?

### ISSUE THREAD

**Issue by mistycheney** [CellProfiler/CellProfiler#2132]
I would like to retrieve the outlines of each cell from the results of CellProfiler.

Currently I can export the outline image but in this image all outlines have the same color, making it impossible to recover the outlines of different cells. Meanwhile, the label maps are computed in the pipeline, and can be used for this exact purpose, but I cannot figure how to export them. Can you add this functionality or point me to the module if it already exists?

p.s. Being able to directly export the coordinates of each outline is also desirable.

Thanks.

**Comment by braymp** [comment]
To save the label matrices, you'll want to use SaveImages with the image type set to "Object". 

You can also create outline objects by shrinking the objects by 1px with ExpandOrShrink, and then IdentifyTertiary to get the outline object labels. Then save these as above.

Exporting the outline coords is not currently possible, though I think there's a GitHub issue against somewhere...?

**Comment by mistycheney** [comment]
Thanks. I was able to generate the label map using SaveImages with image type set to Object.
