### ISSUE TITLE
Color Coding or Labeling Modules

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2133]
For long pipelines it would be convenient to label modules in order to "group" them. The labels could be colors. For example, a group of three modules, 1. ColorToGray 2. Morph 3. IdentifyPrimaryObjects, could all be highlighted/labeled "Red". When visually inspecting a pipeline it would be obvious that these 3 modules are related to each other and form a pipe-segment that is distinguished from the rest of the pipeline.

**Comment by bethac07** [comment]
Apparently the desire for this came up with one of our forum users in a discussion with AZ- see [here](http://forum.cellprofiler.org/t/cp-2-2-not-working-on-mac/3946/3).

**Comment by AnneCarpenter** [comment]
Cool idea. I'm marking it as "Future consideration" (that is the only label that we periodically review to see if it should be re-opened.

 @bethac07, It's best to copy relevant info into the issue; @0x00b1 likes it. I've done that here: 

"it would be great to be able to change the names of the modules when you build a pipeline. It is true that sometime you have 5 IdentifyPrimaryObjects and you don’t which refer to which. If one could change the name to IdentifyNuclei and IdentifyGolgi etc it would be much more readable and easier to modify."   

Response: "I doubt that being able to change the displayed names of the modules is likely to happen, but we've definitely experienced the difficulty of having too many modules in a pipeline and have thought about different ways we could make it easier to track which modules go with which."
