### ISSUE TITLE
Metadata from file headers does not apply to all images

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2134]
When trying to extract metadata from multi-level tiffs the extraction method "Extract from image file headers" will only search for all "Frame"s of a multi-level tiff for the first image. I noticed that if I duplicate this extraction method for each file I do get the metadata I desire. [See image](http://imgur.com/2QYgh8g). In this example, I have 3 multi-frame tiffs as an input and therefore required 3 "extract from image file headers" to identify all frames in all images.

Note this bug is tricky to recreate. I think it may have to do with the order of operations. When the bug appeared I had added a single image to the pipeline and then updated the metadata. When I added the second and third image and updated the metadata again it would not update completely. However, when I add all three images at once and then update, the metadata is correctly identified.

**Comment by braymp** [comment]
Did you hit the "Update metadata" button below the "Extract metadata from" setting?

**Comment by karhohs** [comment]
Good suggestion. I've "frozen" a pipeline to reproduce this issue. Unfortunately, your suggestion with this pipeline it did not solve the issue.

**Comment by braymp** [comment]
One clarifying q: When you pushed the "Update" button, did the dialog for retrieving the file info flash quickly and disappear, or persist for a bit as it read the files?

I've found that if the former, no update actually occurred and so nothing would change. In that case, sometimes I've needed to clear the Images module and then re-drop a file for the update to "take".

If the latter, then I don't know...

**Comment by karhohs** [comment]
The false Update sounds plausible. I've noticed that sometimes if I remove the option to find metadata by file headers and then add it back, then it will work as expected. My current strategy is to keep adding more metadata extraction methods mixed with removing and adding back  metadata extraction methods.

**Comment by karhohs** [comment]
FWIW, this is still an outstanding issue. The suggestion about adding a warning text is a good idea, but I do not see an obvious error that can be caught to post the message. I think the error ends up happening downstream in NamesAndTypes when an image set cannot be found. I suppose it would help to say, "An image set error can result from files missing from the Images module, or failure of the Metadata module to parse file name headers."

The issue appears constrained to multi-page image files. I ran into this problem recently with a pyramidal CZI image container.

**Comment by DavidStirling** [comment]
This was hopefully solved by #3894. In CP4 the Metadata module will now check that you've extracted from headers before trying to update the metadata table. If you change the file list the check for whether you've extracted is also reset, which should mitigate this issue with it mistakenly assuming data is extracted.

There will probably still be ways to fool it by adding/removing methods, but it's unlikely that someone would accidentally encounter this. Feel free to re-open this if the problem persists in the next version.
