### ISSUE TITLE
JIRA [IMG-483] Combine ExportToDatabase and ExportToExcel into a single module

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#214]
This will also solve the problem where ExportToExcel does not have the capability to export per-well measurements.  The new module should be called ExportData.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-483
Assignee: leek

**Comment by braymp** [comment]
From old roadmap: In parallel manner to the refashioning of the Load modules, the Export modules (to spreadsheet, database, etc) should be combined into one and placed at the end of the pipeline, replacing the default output folder in the process.
