### ISSUE TITLE
Combine objects identified at two different times into a single object class

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2140]
Currently if you have two separately identified sets of objects (such as automatically identified nuclei and then manually identified nuclei, or a case where some nuclei are bright and some are dim so they need separate IdentifyPrimaryObjects modules to pull each type out) it's a pain and several steps to try to turn them into a single umbrella class such as "AllNuclei", but sometimes you need the combined set to proceed with your downstream analysis.  It seems like this might be much simpler to do in the backend by combining the matrices for the two or something like that, but IANASE.  If it is possible it would be a big help for at least one project each for Kyle and I, not to mention [the resolution of a forum issue from one of our top posters](http://forum.cellprofiler.org/t/ability-to-combine-objects-identified-at-different-times/1272?u=bcimini) .

**Comment by braymp** [comment]
Duplicate (or subset?) of https://github.com/CellProfiler/CellProfiler/issues/876

**Comment by braymp** [comment]
I can't tell you how long I've wanted this implemented....

**Comment by bethac07** [comment]
Ahh, I searched combine but never hit on "consolidate", seems to be basically the same thing.  

You can tell how long I've wanted this implemented by clicking though :smile:

**Comment by AnneCarpenter** [comment]
Supplanted by #2151

**Comment by mcquin** [comment]
@bethac07 @karhohs @braymp Sorry for the issue/PR confusion!!

**Comment by KarishmaVal** [comment]
Hi,

Sorry for reviving such an old thread but a combine objects module would still be very useful.

Currently I am identifying different cell types in different identifyprimary/secondary modules and exporting them as seperate cell masks.
But to get data on object neighbours and relationships I need all my cell objects to be in one single total cell mask. As a workaround, I have tried using convert object to images (unit16), and then image math modules. Here, to retain the object numbers I add the max intensity(= max object number) of image 1 to image 2, and add the resulting image to image 1. But when trying to convert this back into objects I run into the 'images of type float must be inbetween -1 and 1' error. 
Also the background pixels are not 0 anymore, so is there a way to do image math on only objects excluding background pixels?

It would be great if anyone has any advice about this!

Thanks,
Karishma
