### ISSUE TITLE
Remove white space from borders of DisplayDataOnImage exported images

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2142]
So apparently when you tell DisplayDataOnImage to export "just the image", what it exports is not actually just the image but a [scaled down version of the image with white space around it] (http://forum.cellprofiler.org/t/can-label-from-track-objects-be-used-to-generate-indexed-images/3739/5?u=bcimini).   I understand from reading #991 why that may be, and for the other two export mechanisms (axes and figure) it makes sense, but it's certainly not the intuitive behavior for image.  

I gave him a workaround for now, and it's not something that comes up super often, but might be good to fix.

(Sorry I would just reopen 991 but I'm having weird permissions stuff right now and cannot.  Feel free to merge)

**Comment by AnneCarpenter** [comment]
Unless it's missions critical for someone, let's leave #991 marked as future consideration and close this one.
