### ISSUE TITLE
JIRA [IMG-482] Combine per-image and per-object measurement modules, if possible

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#215]
Consider whether it&#39;s feasible to combine MeasureImageIntensity and MeasureObjectIntensity into a single module (like MeasureTexture and MeasureCorrelation, which can measure both objects and images).  Also add per-object capabilities to MeasureImageGranularity and make it MeasureGranularity.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-482
Assignee: leek

**Comment by AnneCarpenter** [comment]
Would likely make the UI complex to have lots of functions within each module, except for the simple cases noted. Will consider this concept in a futuristic wizardy form of CP that 'measures everything' with less fuss. But for now, closing.
