### ISSUE TITLE
MeasureObjectRadialDistribution doesn't support overlapping objects

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2152]
There's no reason I can think of that this must _a priori_ be true; it'd be cool if we could update it so that it could!

**Comment by braymp** [comment]
Subset of #115

**Comment by braymp** [comment]
What sort of use case are you looking at for this? Just curious....

**Comment by bethac07** [comment]
You have the most crazy encyclopedic memory on this stuff!  Respect :)

Trying to segment then CPA train some tube-like structures that overlap in the dish- right now we're breaking them apart with UntangleWorms, if we use the overlapping "worm" segments we get about 70% classification accuracy, if we just take the non-overlapping segements that we've done Radial on it jumps to 97% since they're bright at the edges of the tube and hollow in the middle.

**Comment by AnneCarpenter** [comment]
Likely would be fixed via #2239 (or won't happen)... @bethac07 if this is likely the best route for your project, definitely re-open. Otherwise it's a similar priority as the rest of #115 which awaits future consideration.
