### ISSUE TITLE
Image module idea: deconvolution 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2153]
May have already been considered and rejected in the past for reasons I don't know about (comment from Mark in 3, 2, 1... :smile: ), but especially as we move into 3D this would be super awesome to have.  There is a scikit image deconvolution function which should mean it's not theoretically impossible.

**Comment by braymp** [comment]
See #180.

**Comment by braymp** [comment]
The thought back then was to let ImageJ handle this, but since the RunImageJ link is severed, and esp. if scikit  image handles it, I'd be :+1: for including it.

**Comment by braymp** [comment]
Side thought: If one has a PSF, the process of applying it would be akin to using an ICF for illumination correction. So we'll need to make sure that establishing a one-vs-many relationship in NamesAndTypes works properly for 3D as well.

**Comment by AnneCarpenter** [comment]
Great idea, marking it for future consideration.
