### ISSUE TITLE
Module Request: Workspace Viewer as a module

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2155]
Workspace viewer has many options to create overlays of objects and images. It would be nice if a module had all the same options so that they can be saved as part of the output of a pipeline.

**Comment by braymp** [comment]
Could you not use a combination of GrayToColor and OverlayOutline modules?

**Comment by karhohs** [comment]
I believe GrayToColor and OverlayOutline represent only a subset of Workspace Viewer capabilities. Workspace Viewer colors objects and overlays them with transparency. It can also label objects with text of measurements.

**Comment by mcquin** [comment]
It would be great to break this out into separate issues as they are requested.
