### ISSUE TITLE
Make UnmixColors subplots maintain approximately square aspect ratio/layout

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2157]
Related to #1584 

Instead of adding subplots in 1x4 row:
![image](https://cloud.githubusercontent.com/assets/1225595/16997127/1d8c03e0-4e82-11e6-82d3-4bb2084c6307.png)
the subplots should be 2x2 in this case.

**Comment by AnneCarpenter** [comment]
Along with #1584, this is being marked for future consideration, just not a high priority now.
