### ISSUE TITLE
TrackObjects fails on Distance setting for Secondary and Tertiary objects

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2164]
From [the forum](http://forum.cellprofiler.org/t/trackobject-fails-with-indexerror-possible-bug/3687/3)\- TrackObjects fails with the error below (the ridiculous index varies) when they use the Distance method on a Secondary or Tertiary object (but not on the Primary).  They said it happens in 2.1.1 and the stable, and I have the pipeline in hand and can confirm it's still in a recentish nightly.  Possibly there's something different about how the centers of Secondary and Tertiary are handled- I strongly suspect that's a factor because segmenting the same objects (cells) with IdentifyPrimaryObjects followed by tracking succeeds. 

```
Traceback (most recent call last):
  File "cellprofiler\pipeline.pyc", line 1992, in run_image_set
  File "cellprofiler\pipeline.pyc", line 2103, in run_module
  File "cellprofiler\modules\trackobjects.pyc", line 960, in run
  File "cellprofiler\modules\trackobjects.pyc", line 1061, in run_distance
IndexError: index -2147483648 is out of bounds for axis 0 with size 1024
```

**Comment by DavidStirling** [comment]
Appears to be fixed in current CP versions.
