### ISSUE TITLE
Export > Image Set Listing... CSV output is not consistent with the metadata that is identified within the gui.

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2166]
Within the gui the metadata for an image set is properly identified:
![image](https://cloud.githubusercontent.com/assets/156232/17141930/2228a4f0-531c-11e6-9908-2c35bd1daa42.png)
However, when exporting the metadata by _Export > Image Set Listing..._ the metadata of some columns become nan:
![image](https://cloud.githubusercontent.com/assets/156232/17141811/a2d9d246-531b-11e6-9e40-f8347666501b.png)
In this instance, there were 17 columns of metadata and only 2 failed.

**Comment by braymp** [comment]
The reason for this (I believe) is that the Metadata module lists the metadata *per-file*, whereas the exporting is done *per-image set*.

So for items like ChannelNumber and FileLocation, there is one value per file, but multiple values per image set. So the image set list simply gives up and writes a NaN. But for items like Well, Site and the like (where there is one value per image set), it does the right thing.

**Comment by karhohs** [comment]
Your observation is consistent with the other metadata columns from my dataset. Can the exporting be changed to _per-file_?

**Comment by braymp** [comment]
Hmm, I don't think that functionality exists; we haven't needed that 'til now? You can open a new issue on it (I'm pretty sure one doesn't exist yet)

**Comment by karhohs** [comment]
With help from @mcquin, I dug into the code a bit. It appears _Image Set Listing..._ calls namesandtypes.py before writing the CSV, which, compared to metadata.py, is coded with a different way of tabulating the metadata. We noticed that javabridge is used to parse and store the metadata, which adds complexity to the problem.

I wanted the CSV to use with the LoadData module. FWIW, my workaround is to avoid using the LoadData module entirely and calling CP from the command line using the _--file-list_ option.

**Comment by AnneCarpenter** [comment]
This sounds really hairy. GIven there is a workaround and it sounds like a relatively rare use case, let's close it and await #2272
