### ISSUE TITLE
Add module # to module context menu

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2167]
Each figure window has a title which includes a module number -- this is nice to have to reference from other modules.  But in crazy-long pipelines, this number is nearly useless, since I don't want to spend all day counting down to the 51st module in my pipeline:

![image](https://cloud.githubusercontent.com/assets/1225595/17185331/af404edc-53fe-11e6-85d9-1c5fe846587a.png)

I suggest to add the module number in the context menu for the module in the module list, as shown in the above screenshot, for example:
...
"Disable Module"
"Help"
"Module 51".

Or maybe a mouseover popup with "Module 51"? But that can get distracting.

**Comment by AnneCarpenter** [comment]
Even simpler, let's just change four entries instead of adding one:
Delete module 51
Duplicate module 51
Disable module 51
Help for module 51

My rationale is that if we add an item that just says "Module 51" people will wonder why nothing happens when they "choose" that option!

**Comment by mcquin** [comment]
#2731
