### ISSUE TITLE
Simplify module registration

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2168]
A user registers their module by adding the appropriate values to the `pymodule_to_cpmodule` dictionary and `builtin_modules` list inside the `cellprofiler.modules.__init__` module. We could simplify this process by programmatically populating the `pymodule_to_cpmodule` dictionary and `builtin_modules` list by truncating and formatting the filenames from `./cellprofiler/modules`.

**Comment by mcquin** [comment]
FWIW, there is a "plugins" directory specified in preferences. A user can place her custom modules there and these will be auto-loaded in CellProfiler.

The broader issue is that all CellProfiler modules should be auto-loaded. :)

**Comment by DavidStirling** [comment]
I think the new loading system largely resolves this. A builtins dictionary is now used to register "official" modules and the plugins directory can be used to load custom modules.
