### ISSUE TITLE
Noise reduction

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2172]
- [ ] Non-local means

**Comment by 0x00B1** [comment]
This module should compliment rather than replace the “smoothing” module.

**Comment by 0x00B1** [comment]
“Library-based non-local means” (LB-NLM) is worth investigating.

**Comment by 0x00B1** [comment]
[Plug-and-Play Priors for Bright Field Electron Tomography and Sparse Interpolation](https://arxiv.org/pdf/1512.07331.pdf)

**Comment by 0x00B1** [comment]
[BM3D Image Denoising with Shape-Adaptive Principal Component Analysis](http://www.cs.tut.fi/~foi/papers/SPARS09-BM3D-SAPCA.pdf)
