### ISSUE TITLE
Image segmentation

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2178]
“Image segmentation” is a proposed image segmentation module that exposes common image segmentation methods (e.g. graph partition or watershed) for segmenting an image into objects. It’ll also act a utility module for creating markers and masks.

An “Image segmentation” module is intended to complement rather than replace existing identification modules (e.g. “Identify primary object”). Nonetheless, the output should be a collection of CellProfiler objects (i.e. `cellprofiler.object.Object`).

Whether the functionality exposed by the proposed “Thresholding” module should be incorporated or merged into the “Image segmentation” is unclear. 
- Active contour model
  - [ ] Chan-Vese
- Graph partition
  - [ ] Minimum spanning tree-based segmentation
  - [ ] Random walker algorithm
- Partial differential equation (PDE)
  - Level set method (LSM)
- Region growing
  - [ ] Simple Linear Iterative Clustering (SLIC)
- [ ] Watershed

**Comment by mcquin** [comment]
#2336 #2391 #2428
