### ISSUE TITLE
Loading dm4-files?

### ISSUE THREAD

**Issue by magnunor** [CellProfiler/CellProfiler#2179]
In `loadimages.py`, there is a list of file formats which cellprofiler can open. It includes the dm3-format, but not the newer dm4. [Linky to code](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/loadimages.py#L146)

We have an implementation in HyperSpy for loading [dm4-files](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/io_plugins/digital_micrograph.py), would there be any interest in getting this loading functionality into cellprofiler as well?

I'm guessing one issue is HyperSpy is licensed GPLv3, while cellprofiler has the BSD-license.

**Comment by 0x00B1** [comment]
👍 

Would you mind opening a pull request? It shouldn’t require anything more than adding “.dm4” to the array passed to `SUPPORTED_IMAGE_EXTENSIONS.update`.

**Comment by magnunor** [comment]
That was easier then expected. I'll do it in a couple of days, unless someone bets me to it :)

**Comment by AnneCarpenter** [comment]
Looks like no one is beating you to it, @magnunor  Bring it on!  :)

**Comment by magnunor** [comment]
I think it already got merged in the pull request: https://github.com/CellProfiler/CellProfiler/pull/2189
(So I should probably have closed this issue :) )

**Comment by AnneCarpenter** [comment]
All the better! Thanks so much for contributing.
