### ISSUE TITLE
JIRA [IMG-470] Investigate combining Crop and Mask modules into a single CropOrMask

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#218]
We suspect that the functionality between the two modules is actually overlapping so most likely the two modules should be combined.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-470
Fix version: future
Assignee: leek

**Comment from mbray on Wed, 21 Apr 2010 10:59:22 -0400:**
From CP TODO:<br/># Anne 4-20-07: In the Crop module, have an option when cropping based on previously identified objects: remove rows/columns without any objects (Yes/No) so that the resulting image can stay the same size if desired. ANNE FINISHED THAT 5-4-07. Also, We need to clarify what is the difference between Mask and Crop? Is adding that Yes/No option to Crop giving it the same functionality as Mask? If so, we can eventually delete the Mask module, except that we would want to change the code of Mask to have a window pop open saying - please replace this module with a Crop module (set appropriately), because the Mask module will soon be eliminated from CellProfiler.

**Comment by 0x00b1** [comment]
Since this issue is nearly a decade old, we’ve reached a point where it doesn’t make sense to change the usage of either module without the risk of breaking every existing pipeline.
