### ISSUE TITLE
Find Metadata CSV in Default Input Folder

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2180]
The _Import from file_ option in the _Metadata_ module requires an absolute path to the _Metadata file location_. It would be convenient to have the option to search the _Default Input Folder_ for the filename, so that the same pipeline can be run on different computers without having to update the absolute path.

![image](https://cloud.githubusercontent.com/assets/156232/17298923/0d1e3724-57da-11e6-97f6-581068d75454.png)

**Comment by bethac07** [comment]
I think this is going to be really important to have for AWS; I spent a bunch of time on Friday trying to get AWS to recognize an absolute path that was written in a .cppipe file and never managed to make it work.  So far relative paths are the only thing that work for me on AWS, so they would hopefully be available for all modules.

**Comment by karhohs** [comment]
@bethac07 has pointed out this would also be useful for testing pipelines with Travis.

**Comment by bethac07** [comment]
Bumping and adding in 3.0.1 project, though it should not be a blocker there if it turns out to be hard; it turned out not to be important for AWS but would be REALLY nice for tutorials/workshops/example pipelines.  I suspect it's easy, and if so it'd be great.
