### ISSUE TITLE
Classify module produces classifiers that aren't cross-platform

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2183]
I trained a classifier in a linux environment, but when I tried to classify an image from my windows laptop I kept getting an error about a missing RandomSplitter attribute that is found in scikit-learn.

When I train the classifier from my windows machine I can successfully classify my images. The classifiers were also different sizes on disk FWIW.

@bethac07 read into the python code and found there may be a numpy dot product problem.

**Comment by DavidStirling** [comment]
Please re-open if this is still an issue in 3.1.9. An example pipeline would also be very helpful. Thanks!
