### ISSUE TITLE
MeasureObjectIntensityDistribution returns nan on all cells if any cells touch the edge of the image.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2187]
See [the forum](http://forum.cellprofiler.org/t/unable-to-measure-and-visualise-a-radial-distribution/3800/3) for description and a pipeline demonstrating the issue.

**Comment by 0x00B1** [comment]
@bethac07 Would you mind copying the relevant information from the forum (it simplifies searching for issues)?

**Comment by bethac07** [comment]
But of course :smile: 

User is using 2.2.0 stable.  When using MeasureObjectIntensityDistribution if any of the objects touch the edge of the image all objects return "nan" for their Fraction at Distance and Mean Fraction (though not for COV) measurements in all bins.  Removing the objects that touch the edges fixes the issue.

Even if you want to argue (as I would) that it doesn't make sense to use this metric on something that touches the edge of the image since it means the edges are probably cut off and your distribution will probably be wrong, preferably we shouldn't bork the rest of the cells in the image.

**Comment by DavidStirling** [comment]
Appears to have been fixed by 3.1.9
