### ISSUE TITLE
thread safe cellprofiler.*

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2197]

**Comment by mcquin** [comment]
#2271

**Comment by mcquin** [comment]
@0x00b1 is this related to #2204 ?

**Comment by AnneCarpenter** [comment]
Once this happens Allen says we can "just annotate each skimage call with http://scikit-image.org/docs/dev/api/skimage.util.html#apply-parallel".

**Comment by 0x00b1** [comment]
way, way better
