### ISSUE TITLE
ExportToSpreadsheet reports incorrect timing information 

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2221]
```
Fri Jul 15 22:55:17 2016: Image # 1, module ExportToSpreadsheet # 23: 0.01 sec
```

**Comment by braymp** [comment]
Does it report the proper timing only during post-run, when it actually writes everything out?

**Comment by 0x00B1** [comment]
@braymp Good question

**Comment by 0x00B1** [comment]
@braymp It looks like the same incorrect timing.

**Comment by bethac07** [comment]
I think this is now fixed since we report wall clock and CPU time, can reopen if recurs.
