### ISSUE TITLE
NamesAndTypes has unusual performance characteristics

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2222]
![rpubs_-_cellprofiler_logs_-_mito_project](https://cloud.githubusercontent.com/assets/315821/17633314/a3c4c300-609a-11e6-805f-053bb653caa0.png)

(Thanks, @shntnu)

**Comment by 0x00B1** [comment]
`NamesAndTypes` shares some performance characteristics with image caching bugs @mcquin and I recently discovered.

**Comment by DavidStirling** [comment]
@0x00b1 Do you know if this is still a problem in modern CellProfiler versions?

**Comment by DavidStirling** [comment]
I expect that with all the changes from 2.2 to 4.0 this is likely solved. Feel free to re-open if it's still an issue.
