### ISSUE TITLE
rename MeasureCorrelation to Colocalization or MeasureColocalization

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2223]
`MeasureCorrelation` is an unexpected name for this module.

**Comment by braymp** [comment]
I diagree (I think?) since colocalization has a v. specific meaning, i.e., do two objects/stained regions/etc appear in the same location. Even if this module is used enabling the per-object correlation, I would say it's still not the same.

**Comment by bethac07** [comment]
The module really does both- correlation and colocalization.  Maybe MeasureCorrelationAndColocalization ?

**Comment by AnneCarpenter** [comment]
Personally I think Colocalization is broad enough to encompass everything this module measures, including pixel by pixel correlations. Further, I think Colocalization is more interpretable to a biologist reading through a list of module names (correlation could include for example correlation between nucleus size and cell size or something). But, Mark's opinion gives me pause. I'd say if we are split on the matter it's best to leave as is. I think the long version "MeasureCorrelationAndColocalization" is too unwieldy even if correct. Other opinions welcome!

**Comment by AnneCarpenter** [comment]
Last call for comments! There's another module on deck for renaming  #2697 - so if we are going to do it, now is the time.

**Comment by braymp** [comment]
Looking at this again, I started googling for both terms to see how it's used. I've changed my mind and now agree w/ @AnneCarpenter; *colocalization* seems to the more biologically-expected term, with *correlation* as a particular instance.

**Comment by AnneCarpenter** [comment]
We can move forward with MeasureColocalization then!

**Comment by AnneCarpenter** [comment]
Hi @DuaaAli , did this one get renamed? If so, you can close this!

**Comment by DuaaAli** [comment]
Yes It is already changed.
