### ISSUE TITLE
choosing colocalization statistics in `MeasureCorrelation`

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2225]
Users should be able to select the statistics they’d like to compute, e.g.
- Costes, et al.
- Li, et al.
- Manders, et al.
- Pearson product-moment correlation coefficient (PPMCC)

**Comment by AnneCarpenter** [comment]
The current measurements the module makes are these (and they have no choice - the module calculates all of them): 

- Pearson's correlation coefficient
- Slope
- Overlap coefficient
- Mander's coefficient
- Mander's coefficient (Costes Automated Threshold)
- Rank Weighted Colocalization coefficient

@0x00b1 Are you advocating for adding additional metrics, or for offering the user to choose among whatever the options are?

**Comment by 0x00b1** [comment]
I think this is a bad idea. It’s also inconsistent with my current view that we should remove options to selectively make measurements and just measure everything.
