### ISSUE TITLE
Refactor segmentation representation in cellprofiler.object.Objects

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2239]
There are currently 3 (documented) ways to represent a segmentation in `cellprofiler.object.Objects`:
- `segmented`: A plane of labels that does not support overlapping objects. Considered legacy but used most frequently throughout the code base.
- `labels`: Similar to `segmented` with overlapping object support. No setter is implemented.
- `ijv`: Essentially, triples of `(x, y, label)`. Supports overlapping objects. Minimally used compared to `segmented`.

All 3 properties use the same internal `self.__segmented` variable to store state. This is probably undesirable since methods like `shape` can return different results based on the representation of the segmentation.

Proposal:

There should be one and only one internal representation of a segmentation. Likely, that representation should resemble `labels`, because of overlapping support. The functionality of `ijv` can be kept by introducing new methods `to_coordinates` (which takes a labeling matrix and returns triples `(x, y, label)`) and `from_coordinates` (which takes triples `(x, y, label)` and returns a labeling matrix).

**Comment by mcquin** [comment]
I don't think that the labeling matrix needs to be much more complicated than a list of matrices.

**Comment by 0x00B1** [comment]
👍 

Can we simplify this further (e.g. replacing `segmented` with an ordinary NumPy array that’s compatible with scikit-image)?

**Comment by mcquin** [comment]
I was thinking that we could probably not bother with supporting overlapping labels. If this was desired, then create multiple `cellprofiler.object.Segmentation`s.

I'm all for representations that are compatible with Python's mathematic/scientific libraries. I don't yet understand why segmentations are stored with shape (1, 1, 1, 1, dim(x), dim(y)).

**Comment by 0x00B1** [comment]
Regardless, `ijv` should be replaced with methods.

**Comment by 0x00B1** [comment]
`small_removed_segmented` should be removed and use should be replaced with `skimage.morphology.remove_small_objects`.

**Comment by bethac07** [comment]
>I was thinking that we could probably not bother with supporting overlapping labels.

There are definitely several cases where being able to to have overlapping labels is really nice.  Vote for please supporting them.

**Comment by braymp** [comment]
What Beth said, with the caveat if a better overlapping representation is available than what's currently implemented, then by all means, go for it.

**Comment by 0x00B1** [comment]
@bethac07 and @braymp we are not talking about the feature.

**Comment by bethac07** [comment]
Whoops, sorry then!

**Comment by mcquin** [comment]
Additionally, setters should only set one property.

**Comment by AnneCarpenter** [comment]
For reference, some history is captured in #115 confirming that switching everything over to IJV was in progress but got sidetracked (you will note it's marked "future consideration" which means it wasn't completed but wasn't a high priority).

**Comment by mcquin** [comment]
I'd like to simplify the Object representation in CellProfiler, but I don't have the time. I will open a new issue when I am ready to begin this work.
