### ISSUE TITLE
Document which modules respect masks

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2245]
See related forum issue:
http://forum.cellprofiler.org/t/how-does-measuretexture-handle-a-masked-image/3860

**Comment by 0x00B1** [comment]
@AnneCarpenter please copy relevant information inside your message.

**Comment by AnneCarpenter** [comment]
The above-mentioned post...
----
Dear all,
I've got two problem for which, though very simple, I cannot find any help.

1- I've got a stack of Z-slices of DAPI stained nuclei and would like to find the best focused one, then work with that slice. MeasureImageQuality works well for that, but then the only way I've found to select that slice and work with it is:
1. Run a first project using MeasureImageQuality and save the scores for all slices into a database (SQLite in my case).
2. Run a SQLite query to retrieve metadata for best focused slice into a CSV file.
3. Use that CSV in a second project to load the best focused slice.
Is there any way these three steps, which I have to load and execute sequentially, can be put into a single project?

2- With the best focused slice identified in the process above, I construct a mask which I want to use over the whole stack of slices for another channel. Could you tell me if there's a way in which I can match all slices in, say GFP, to one slice in DAPI (from which, later in the project, I generate a mask common to all slices)?
Thanks very much for any help
Best
Carlos

**Comment by AnneCarpenter** [comment]
The above-mentioned post:
--
Hi,

The documentation of MaskImage states that masked pixels will be ignored by modules that respect masks but I can't find a list of which modules respect masks and which ones don't. What will MeasureTexture do if I run it in Images mode on output from MaskImage? Will it:

(a) Compute the texture using only the domain inside the mask, ignoring the big black expanse surrounding them?
(b) Compute the texture of the whole masked image, including the big black perfectly smooth expanse, therefore returning smoother texture values when the mask covers more of the image.

Regards,

John


bcimini3d
The code for MeasureTexture checks for masks, so I think it's very likely the former (though we should include that in the documentation). An easy test would be to perform MeasureTexture on the same image with and without a pretty big mask and see if the results are similar or wildly different.

NS_finan3d
That's correct. I wrote a little matlab script to generate some test images and a corresponding CP project to confirm the expected behavior for anyone who's curious. The CP project is attached. The .m file is prohibitied so I'll just paste in the code since it's short:

John

side = 400; %side length of image
noise = uint8(255*rand(side));
mask = zeros(side);
masked_ind = [round(0.4*side) : round(0.6*side)];
mask(masked_ind, masked_ind) = 1;
outside = ~logical(mask);
mask = uint8(255*mask);
masked_noise = noise;
masked_noise(outside) = 0;

imwrite(mask, 'mask.tif');
imwrite(noise, 'noise.tif');
imwrite(masked_noise, 'masked_noise.tif')

**Comment by mcquin** [comment]
Hm... it's not *super* easy to tell. There are a few indications:

1. Search for `image.mask` or, more generally, `.mask` in `cellprofiler/modules`. This generally indicates an image mask is being used and probably then applied to an operation. Similarly (though maybe not necessary for this issue), look for `image.crop_mask` or `.crop_mask`. This is an image's cropping mask, generated by **Crop**.
1. Search for `mask=` in `cellprofiler/modules`. If it's used as a keyword argument for something that looks like `cpi.Image(..., mask=mask, ...)` or `cellprofiler.image.Image(..., mask=mask, ...)`, then the mask is being passed to an image constructor for what's probably the output image for the module.

**Comment by AnneCarpenter** [comment]
Cool - if we are aiming at a 'good enough' solution then I'd say searching literally for "mask" alone should suffice. Jeanelle can at least look to see whether the word is in the midst of code (vs in the intro help in a sentence that says "this module ignores masks" for example!) and if yes, it's a safe bet to add the mask verbiage above. Seem reasonable?

**Comment by mcquin** [comment]
@AnneCarpenter Yep, sounds reasonable!

**Comment by AnneCarpenter** [comment]
OK then @N3llz , have at it!

**Comment by N3llz** [comment]
I will add this in after the mention about 2D/3D support so that the ordering of help sections will be as follows:

- Title, one liner, and intro help text describing the module
- **This module (respects/does not respect) masks. See MaskImage and MaskObjects.**
- Supports 2D/3D
- See also
- (module specific headings, unless they make sense elsewhere)
- What do I need as input?
- What do I get as output?
- Measurements made by this module
- Technical notes
- References
- Settings

**Comment by N3llz** [comment]
@AnneCarpenter Do you think we need any additional help text associated with the "Respects Masks?" column? Or will people know what that means? If we wanted some supporting text, it could just be an asterisk below the table, in italics, saying * _If NO, this module will ignore the mask, and use the original image_ or something like that (not sure if that's 100% true or the best way to put it!)

**Comment by AnneCarpenter** [comment]
Hm, I vote skip any clarifying language like that. It's hard to do concisely and if you don't know what it means that is ok because you won't care if it respects masks or not.

**Comment by N3llz** [comment]
Fine to close this issue? @AnneCarpenter

**Comment by AnneCarpenter** [comment]
If you've indeed added the table throughout the modules then yes!

**Comment by N3llz** [comment]
Already merged and closed here: https://github.com/CellProfiler/CellProfiler/pull/3306
But for some reason, I don't have the option or button to close this issue?
