### ISSUE TITLE
Enable multi-stack images to be reduced to one within a pipeline

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2246]
See related forum post here:
http://forum.cellprofiler.org/t/retrieving-best-focused-slice/3858

I believe this is a common type of limitation. And if we are soon able to handle 3D images as a single unit passing through CellProfiler (rather than a set of slices as has been the case in the past) then it is at least a possibility that this kind of situation (user's part (1)) could be handled more gracefully.

How exactly to do this requires some discussion; is the solution a very generic module that selects a particular slice from a multi-stack entity (based on some prior measurement made by CP like focus metrics, or alternately first, middle, last) and passes the single slice along the pipeline? Or is it a modification of MakeProjection (which already turns a stack into a single image)? or MeasureImageQC (which makes focus measurements)?

**Comment by braymp** [comment]
I think Lee made CP able to able handle such a thing (at least theoretically) in CorrIllumCalc if using the "All: First cycle" option. All aggregation calculations are done during the first cycle and then the result is passed to the remaining cycles. I imagine that it's sort of like doing the LAP 2nd phase for tracking, except done on the front end rather than at the back.

I've never used this myself, though, and I recall that Lee was not a fan of such a scheme, at least with how CP is structured currently.

**Comment by 0x00B1** [comment]
@AnneCarpenter please copy the relevant information inside your message.

**Comment by AnneCarpenter** [comment]
The above-mentioned Forum post that started this issue:
--
Dear all,
I've got two problem for which, though very simple, I cannot find any help.

1- I've got a stack of Z-slices of DAPI stained nuclei and would like to find the best focused one, then work with that slice. MeasureImageQuality works well for that, but then the only way I've found to select that slice and work with it is:
1. Run a first project using MeasureImageQuality and save the scores for all slices into a database (SQLite in my case).
2. Run a SQLite query to retrieve metadata for best focused slice into a CSV file.
3. Use that CSV in a second project to load the best focused slice.
Is there any way these three steps, which I have to load and execute sequentially, can be put into a single project?

2- With the best focused slice identified in the process above, I construct a mask which I want to use over the whole stack of slices for another channel. Could you tell me if there's a way in which I can match all slices in, say GFP, to one slice in DAPI (from which, later in the project, I generate a mask common to all slices)?
Thanks very much for any help
Best
Carlos

**Comment by AnneCarpenter** [comment]
A similar post is here: http://forum.cellprofiler.org/t/how-to-mask-objects/3663
Relevant bit pasted here:
--
I am struggling in creating a mask for some objects I want excluded from my analysis. I have some dust particles (the arrows show them) I want to eliminate from a series of time lapse images. Once the dust particles are masked, I want to be able to use the mask as a template to mask dust particles in the remaining images loaded.

**Comment by mcquin** [comment]
This issue was solved by the user http://forum.cellprofiler.org/t/retrieving-best-focused-slice/3858/4
