### ISSUE TITLE
Clarify the CP version on PyPi 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2247]
The CP version installed via the method on https://github.com/CellProfiler/CellProfiler/blob/master/README.md is apparently the Stable release version.  The only indication the user gets within a command-line envoronment (e.g. cluster) is 

```
$ cellprofiler --version
CellProfiler 2.2.0
Git ac0529e
Version 20160503183100
Built 2016-05-03T18:31:00
```

This is all fine, but ought to to be clear on the README.md page.

**Comment by AnneCarpenter** [comment]
@0x00b1 does something need updating each time a new release comes out to make this happen or will those instructions always point to whatever the current stable release is? 

If the former, we should say "Install 2.2.0 from the Python Package Index (PyPI)" (and make reminders to update this w each release). If the latter, then "Install current stable release from the Python Package Index (PyPI)". I can do this once someone confirms.

**Comment by mcquin** [comment]
Resoved #2699
