### ISSUE TITLE
MeasureObjectSkeleton only writes CSV headers sometimes

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2252]
Running ac0529e on AWS and writing outputs to CSVs, I found that the CSVs for the "edges" and "vertices" spreadsheets from MeasureNeurons were missing their headers about 15% of the time (1615 of 9855).  No pattern yet that I've been able to find other than when I've spot checked it if the header's missing from edges it's missing from vertices (running a script now to be sure).  The other CSVs from the experiment (Cells, Cytoplasm, Nuclei, Image) all seem to be in good working order.  If you have hypotheses as to why some but not others I'm happy to investigate patterns but I've got no clue what might cause this and therefore where to start.

**Comment by bethac07** [comment]
There were 1616 missing from vertices and 1615 from edges, so while it's almost 1:1 it's not exact.

**Comment by DavidStirling** [comment]
Do we know if this is still a problem?

**Comment by bethac07** [comment]
Nope, not since 2.2, I think it's fair to close until we see if it recurs in 4.0
