### ISSUE TITLE
Create a new module: ExportImagesPerObject

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2255]
This would save an individual image for each object that has been identified in an upstream module. 

This is useful for training deep learning models on individual cell images that have been segmented using CellProfiler. It can also generate the image data needed for data exploration tools designed for imaging flow cytometry, where each cell is imaged separately (though we do not yet know of any requests for this).

INPUT: 
— objects (with XY locations)
— corresponding image(s) to save (should handle RGB or grayscale, masked or not - i.e., any masking or color merging/splitting should happen upstream of this module)

SETTINGS:
— specify the input, as detailed above
— needs an “add another image” option (for multiple grayscale images, for example)
— fixed size tiles (then, specify the pixel X, Y size) or per-object size (each tile fits the object with no blank rows/columns around it) or full size image (the entire size of the original image, with the one little object in the middle - this only makes sense if the input is masked or else it saves the entire original image for every object)
— Rotate major axis of object to the XY axes of the image (two options: limit to 90deg only, vs. any angle). Default = no rotation

DISPLAY:
- nothing really needs to be displayed, but maybe could show “Number of individual images saved to disk: NNN”.  

OUTPUT: files saved to disk, plus maybe we need to save file names to the per-object measurements

**Comment by AnneCarpenter** [comment]
We should consider whether this module should also be allowed to spit individual object images to a remote service rather than save to disk.

**Comment by braymp** [comment]
Would it make sense to split this functionality up across two modules?
* A new TileObjects module which captures the input and settings you suggest (and is reminiscent of TileImage); and 
* SaveImages with a "Tile" option under "Type of input"

The reason for the suggestion is that a module with this function sounds a little esoteric (even though I know the request for this functionality is long-standing). 

On the other hand, carrying out this functionality across two modules might be harder for novice user to find.

**Comment by AnneCarpenter** [comment]
Interesting and clever thought. We should ponder that!

**Comment by afolarin** [comment]
@AnneCarpenter @braymp sounds great. I think this would prove a useful extension of CP. We were looking for a quick way of getting data into a TensorFlow CNN.

**Comment by 0x00b1** [comment]
@afolarin This is our motivation too.

**Comment by 0x00b1** [comment]
@afolarin And for that reason I think we should export NumPy arrays rather than images.

**Comment by afolarin** [comment]
:+1:

**Comment by afolarin** [comment]
@AnneCarpenter 

> OUTPUT: files saved to disk, plus maybe we need to save file names to the per-object measurements


in the output it might be good to also include the X,Y positioning in the image-tile, e.g. knowledge of relative proximity of objects might be of value in some scenarios

**Comment by mcquin** [comment]
Is #2718 sufficient?

**Comment by AnneCarpenter** [comment]
CellProfiler now has "SaveCroppedObjects" - it currently only saves separate images as binary masks for each object. I believe the request for the functionality described above still remains.

**Comment by afolarin** [comment]
@AnneCarpenter actually I hope to have a conversation today with @SariNusier today, #2831 is where this functionality is being worked on (not #2790)
