### ISSUE TITLE
Create a new module: MeasureImageViaRemoteService

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2260]
MeasureImageViaRemoteService would allow you to send images from CellProfiler to a remote service, and record the measurements produced by that service.

Remote image-processing services can accept incoming images from CellProfiler, perform some image processing, and return to CellProfiler some measurement(s) derived from the image. These services might exist because the processing requires the provider’s substantial computing resources, or because the service provider wants to keep their source code proprietary, or because the service provider wants to charge per-use. 

This module would allow you to specify the location of a particular remote service and send an image there. When the provider produces measurements, they are returned and stored in CellProfiler as per-image measurements.

Authentication is assumed to happen outside of this module - that is, you may need to log in to the remote service in order for it to accept incoming images.

**Comment by AnneCarpenter** [comment]
Nick has a prototype in progress.

Still to do:
- Figure out how to store measurements coming from various services. In the case of the Inception module we are using as a demo, its output is the top 5 class names and top 5 class scores. So we store 10 measurements: Class1name	Class1score	Class2name	Class2score	Class3name	Class3score	Class4name	Class4score	Class5name	Class5score
Each image will yield scores for different class names. Ideally, we would want to know the ~1000 possible classes, give each an index, and store the scores for every possible class. 

- Needs flexibility to adapt to different output formats - Some services may return a 2D array, so it would need:
— Check if input is a 2-d array, if not throw an error (or write a separate parser for the format)
— Check rows and columns: is one and only one plain text? if not throw an error. If yes, assign that dimension to be measurement names
— Check rows and columns: is one and only one numeric? if not throw an error. If yes, assign that dimension to be measurement values
— Then iterate through either rows or columns per the rules defined above, storing the measurements in CP format.

- Figure out what module number this module is, call it N, and append it to the measurement name. Note that we need to store the module number within the measurement name because we don’t want multiple instances of this module to overwrite each others’ measurements. So the measurement name would be:
ImageName_RemoteService_N_ClassName
example:
DNA_RemoteService_8_ClassName1
(Anyone have any comments on whether it should be RemoteService_N or RemoteServiceN?)

**Comment by AnneCarpenter** [comment]
Still to do:
- Some services may need input parameters of some sort. So add this setting option:
Input parameters required for the service (optional): (text box)  default = ???
If the service requires any input parameters, enter them here using the format specified by the service provider.

**Comment by AnneCarpenter** [comment]
Still to do:
* Within the module, the image is converted to .jpg in order to be acceptable to the service we were using. This is non-optimal.

**Comment by pawni** [comment]
I pushed my code here: https://github.com/pawni/CellProfiler/commit/acddc34ad9aefc3def0124245f91b99fa2c92740
The server is configured according to https://tensorflow.github.io/serving/serving_inception

**Comment by mcquin** [comment]
This is a great idea that came out of a coding day exercise.
