### ISSUE TITLE
time-lapse image registration

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2264]
Align images through time to account for stage drift.

**Comment by AnneCarpenter** [comment]
I think to solve your problem, the actual request would be to change the Align module such that images can be aligned relative to the most recent slice of the time-lapse movie, is that right?

**Comment by braymp** [comment]
I can imagine a setting something along the lines of "Align to which image set?" with options "Image in this cycle" (what it does now), "Image from first cycle", or "Image from previous cycle"

**Comment by 0x00b1** [comment]
Some additional background would help, e.g. a description of the problem, possible implementations, alternative solutions, etc.

**Comment by karhohs** [comment]
[testimages.zip](https://github.com/CellProfiler/CellProfiler/files/445550/testimages.zip)

I've attached a series of time-lapse images. I think Mark and Anne's comments describe the feature well. "Image from previous cycle" is the type of alignment that addresses the problem when there is cell movement in addition to stage drift. Aligning to the previous cycle will minimize the cell movement.

**Comment by 0x00b1** [comment]
It’s an interesting idea but it’d require substantial work to gracefully retrieve a previously processed ImageSet. Moreover, it’d break existing distributed features where one node is completely unaware of other ImageSets.

**Comment by AnneCarpenter** [comment]
Grouping solves the situation where one node is completely unaware of other ImageSets; grouping can force CP to process images from the same time series within a single batch - this is how we use TrackObjects on a cluster. I don't recall whether any of TrackObjects' options (if any, it would be the simpler ones) gracefully retrieves an image from a prior image set. The LAP option I'm nearly certain does not but instead does calculations on XY locations at the end of the entire time series being processed.

I'm wondering if @braymp or @dlogan can remember any modules that look back to the prior image in a group. I suppose TrackObjects might actually be the only candidate after all.

**Comment by braymp** [comment]
> I'm wondering if @braymp or @dlogan can remember any modules that look back to the prior image in a group. I suppose TrackObjects might actually be the only candidate after all.

How's this for arcane: DefineGrid allows the defined grid from the first cycle to be used in case gridding in any successive cycles fail. I don't how it does this; I assume it simply retains the needed information from the 1st cycle.

**Comment by AnneCarpenter** [comment]
Wow, you dug that up from the archives!  Yeah, first cycle but not *prior* cycle. So Allen's concern about adding complexity to handle prior cycles sounds warranted. I vote leaving this closed. Workaround might be standalone tools to do alignment/registration first (maybe Fiji/ImageJ).

**Comment by dlogan** [comment]
CorrectIlluminationCalculate can also keep a 'running total' of the illumination function in a Group if "All: Across Cycles" is chosen.  So the functionality of keeping a non-current-cycle image in memory (or on disk) is not unheard of, but sure, I can understand the desire not to add complexity.

@karhohs I know it's a late suggestion, but this seems to me to be one of those cases that a separate ImageJ preprocessing step here is warranted.

**Comment by 0x00b1** [comment]
> How's this for arcane: DefineGrid allows the defined grid from the first cycle to be used in case gridding in any successive cycles fail. I don't how it does this; I assume it simply retains the needed information from the 1st cycle.

This is accurate. (It’s also a mess from an implementation perspective!)

**Comment by 0x00b1** [comment]
> @karhohs I know it's a late suggestion, but this seems to me to be one of those cases that a separate ImageJ preprocessing step here is warranted.

I know everybody will be shocked, but I agree with @dlogan.

Alternatively, A Python script would work too (e.g. SimpleITK has a robust collection of registration operations).

**Comment by 0x00b1** [comment]
@dlogan P.S. I updated metabolism. 👍

**Comment by dlogan** [comment]
> @dlogan P.S. I updated metabolism. 

Cool @0x00b1 - but I think I can't use it until this (https://github.com/CellProfiler/metabolism/pull/1) is merged? Otherwise there is no setup_cpa.sh, which I only just saw.
