### ISSUE TITLE
Merge Small Objects to Size Threshold

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2267]
This would add features to the unify operation of merging objects. In addition to merging based upon distance, there would be the merging based on size. Objects below a size threshold would be merged together until these new objects were above the threshold. There could also be a "gravity" effect, where if a small object is near two larger objects, the larger objects would exert a kind of "pull" to decide which object the smaller object should merge to. The pulling force would be a function of size and distance.

**Comment by 0x00b1** [comment]
Thanks, @karhohs. However, you should add your comment to the appropriate pull request:

https://github.com/CellProfiler/CellProfiler/pull/2151
