### ISSUE TITLE
Link skeletons to nearby skeletons

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2268]
This feature would link non touching regions of a skeletonized image together. One parameter would be distance, i.e. two regions must be close enough together to link. The convex hull of two regions would be used to calculate the closest point between two regions. A line would then be added to the image to connect the two regions. This would be a binary operation.

**Comment by karhohs** [comment]
![image](https://cloud.githubusercontent.com/assets/156232/18101266/fae79fc0-6ebb-11e6-942a-84a1e4c4d733.png)

Region 1 should be merged to Region 2

**Comment by 0x00b1** [comment]
What do you mean by “merged?”

**Comment by karhohs** [comment]
![img_2106](https://cloud.githubusercontent.com/assets/156232/18131394/a5115a6e-6f60-11e6-9c40-54b2a6bb2ff7.JPG)

The red line would be added to the image of green spindles.

**Comment by 0x00b1** [comment]
Thanks for the clarification!

Unfortunately, I don’t think this is worth the engineering or usability trade-off. However, we’d be more than willing to reconsider if you send a pull request.

**Comment by AnneCarpenter** [comment]
A potential workaround: some morphological operation that connects skeletonized components within a certain distance. Break apart networks that belong to different cells by subtracting outlines of the cells from the connected network.
