### ISSUE TITLE
Main help text for FilterObjects missing the help info for "Relabel additional objects" option

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2269]

**Comment by 0x00b1** [comment]
Thanks, @bethac07! Pull requests are encouraged.

**Comment by AnneCarpenter** [comment]
Is the issue that no one on the team knows how it works? (I'm afraid to ask)

**Comment by bethac07** [comment]
I _assume_ that the whole-module help scrapes the help settings from the various options (and this particular missing one does have a help next to the option, just not in the whole-module help)- I'm in the process of figuring this all out for MeasureRadialEntropy, as soon as I figure out what the heck the call is I'll fix it for this one too.

**Comment by 0x00b1** [comment]
> Is the issue that no one on the team knows how it works? (I'm afraid to ask)

I suspect it’s solvable. I didn’t look.

**Comment by bethac07** [comment]
You can assign me if you like, it's good learning if nothing else.

**Comment by AnneCarpenter** [comment]
Ah, I see. The issue is not that someone needs to write the content, it's that there is a bug in whether it displays in the right places.

**Comment by bethac07** [comment]
Resolved by #3020
