### ISSUE TITLE
Retire Github wiki pages detailing release notes

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2273]
It's a manual process to update these - should we bother? 

We have two pages on the Github wiki, short concise summaries and detailed notes: https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-release-notes  https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-release-notes%3A-detailed  

Especially if we are on a faster release cycle these become annoying to make. I’m wondering if anyone has an argument for why these are so valuable (other than for me writing progress reports).

If we decide not to further update... is deleting ok? Not sure if history is retained somewhere for deleted pages or not.

**Comment by AnneCarpenter** [comment]
If we do so, we need to remove the CP Menu item: Help > Release notes. Actually I think that is worth doing regardless, who wants to see those from a menu inside the software anyway? Making a separate issue for that: #2288

**Comment by mcquin** [comment]
Release notes are great. We should keep them!
