### ISSUE TITLE
Bad practices in Ubuntu 16.04 installation instructions 

### ISSUE THREAD

**Issue by burgerga** [CellProfiler/CellProfiler#2275]
I think installing to user directory should be the default, it prevents people from screwing up their computers.
Please no `sudo git clone` to `/opt` and 
`sudo chmod o+w` on `/usr/local` and `/usr/lib`, I would even prefer `sudo pip` because then at least you know you're doing a bad thing :P
And the last line `rm -fr /usr/lib/python2.7/dist-packages/*` is REALLY bad advice (even with the disclaimer).

**Comment by 0x00b1** [comment]
Yikes! You’re totally right. I updated the page. Thanks, @burgerga.

Also, the wiki pages are community edited. You’re more than welcome to update them!

**Comment by burgerga** [comment]
Oh I assumed that wouldn't work, good to know :+1:
