### ISSUE TITLE
Labels should be on top rather than to the left of inputs

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2278]
![forms_ _bootstrap](https://cloud.githubusercontent.com/assets/315821/18169536/8751ea16-7028-11e6-8bed-1cd36510a9df.png)

**Comment by braymp** [comment]
Why?

**Comment by 0x00b1** [comment]
> Why?

…

**Comment by 0x00b1** [comment]
Since you’re curious, it simplifies box sizing. Moreover, it permits dynamic sizing (e.g. long labels and form elements clip if the label is too long).

**Comment by mcquin** [comment]
It would also make settings which take multiple inputs (like Binary or https://github.com/CellProfiler/CellProfiler/pull/2280) easier to read.

**Comment by 0x00b1** [comment]
And it wouldn’t break every baseline.

**Comment by 0x00b1** [comment]
e.g. 
![h_and_v_and_window_and_5e92039e-702e-11e6-9728-36ae0b7ff6de_png__png_image__364 x 64_pixels_](https://cloud.githubusercontent.com/assets/315821/18171197/0dbe2532-702f-11e6-8665-83a80e094153.png)

**Comment by braymp** [comment]
Gotcha. Part of me was wondering two things:
* Whether it makes the overall top-bottom panel content would become just that much lengthier (since they'd be stacked)
* I assumed that the straight-up left-to-right flow was easier to read/interpret, but I'm not dogmatic on that.

**Comment by mcquin** [comment]
If a module take more than a screen of options to configure, then something is wrong.

**Comment by 0x00b1** [comment]
> I assumed that the straight-up left-to-right flow was easier to read/interpret, but I'm not dogmatic on that.

I think this is the least of our usability concerns.

**Comment by AnneCarpenter** [comment]
This would solve #2135 so closing that one.
