### ISSUE TITLE
ImageJ not handling anymore multiple channel images

### ISSUE THREAD

**Issue by erexhepa** [CellProfiler/CellProfiler#2279]
Hi,

I was trying to use ImageJ inside cellprofiler for analysing a color images and got an error. I tried to track the error and the error is raised (it seems at this level)

[line 797]
ij_processor = ijiproc.make_image_processor(
                        input_image.astype('float32'))

in run_imagej.py

I was wondering if it was related to the multichannel nature [RGB] in this case because I can instanstiate the ImageProcessor if index only one of the channels. Are only 2D images supported and we should create the color version once all channels are in imagej space ?

Elton

**Comment by 0x00b1** [comment]
Hi, @erexhepa, you might have better luck asking your question on the [forum](http://forum.cellprofiler.org).

**Comment by erexhepa** [comment]
Hi,

Thanks I will post this also in the forum. I posted it here because I thought issues were discussed here ?

Thanks anyway,

Elton

**Comment by 0x00b1** [comment]
@erexhepa, it is. I misread your comment! Sorry about that. 😄 

Unfortunately, the RunImageJ module was dropped from the last release.

**Comment by erexhepa** [comment]
so imageJ is not supported anymore ?

**Comment by 0x00b1** [comment]
> so imageJ is not supported anymore ?

Right. 2.2.0 is the last release with the ImageJ module.

**Comment by erexhepa** [comment]
ok, that's a real pity. It was handy for a lot of things.

**Comment by 0x00b1** [comment]
> ok, that's a real pity. It was handy for a lot of things.

Totally. Unfortunately, it was responsible for a massive share of CellProfiler issues we needed to make a trade-off.

What are you using it for?

**Comment by erexhepa** [comment]
I understand what you mean. I was looking forward to run an imagej plugin that was published recently 

but maybe I can find an alternative solution by running imagej outside cellprofiler env as a standard os call and then recuperate results and image inside cellprofiler.

**Comment by AnneCarpenter** [comment]
@erexhepa We were sad to have it go, too, but you can read the silver lining and future plans here: https://github.com/CellProfiler/CellProfiler/issues/1994

**Comment by erexhepa** [comment]
Thanks, for the reference good to know where you guys are going forward. 

I think is a good strategy to ensure inter-operability between ImageJ and CP taking also into consideration the evolution of ImageJ. 

Thanks for all your efforts
