### ISSUE TITLE
JIRA [IMG-301] BatchProfiler: Webpage showing incorrect information for batches with mulitple runs

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#228]
Example: Batch 1484 -<a href="http://seaborgium/batchprofiler/cgi-bin/ViewBatch.py?batch_id=1484">http://seaborgium/batchprofiler/cgi-bin/ViewBatch.py?batch_id=1484</a><br/>Jobs for 195601 - 196000: SELECT job.job_id, job.run_id FROM run,job WHERE batch_id = 1484 AND bstart = 196001 AND bend = 196400 AND run.run_id = job.run_id;<br/><br/>Currently running as job 213871 on imageweb under priority queue, but listed as unknown job 9862736 on the webpage.<br/><br/>I think the problem is in RunBatch.py, line 125:<br/><br/>select run_id,batch_id,bstart,bend,status_file_name, (select max(job_id) from job j where j.run_id = r.run_id)<br/><br/>max(job_id) does not get the value needed. Perhaps add a timestamp field and order by that?

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-301
Assignee: leek

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/BatchProfiler#30
