### ISSUE TITLE
Avoid "Pipeline saved with old version" warning when loading from Welcome Screen

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2284]
I couldn't find any discussion of this previously (though I thought we had!) and I'm not sure what to do to fix it. 

Currently when you load CellProfiler for the first time, you see a Welcome Screen and our hope is that novice users will choose to see a pipeline in action by clicking "Load" an example pipeline. It's much easier to understand CP if you see a pipeline loaded and then running. 

When you click Load, though, you immediately get a verbose warning dialog stating "Your pipeline was saved using an old version of CellProfiler (rev 6c2d896)". Clicking ok is the only option and after that everything proceeds perfectly normally, but this warning is pretty disturbing to a new user, making them think they've done something wrong right off the bat.

So, obviously we need to update the pipeline that is located at the URL that "Load" points to. If we just update the pipeline, though, then old versions of CP will complain (but in much less graceful way because they will be trying to load a future-versioned pipeline). 

I think this means the answer is to:
1) create a new version of the pipeline (easy: after it complains and loads, simply save it again with a new name). Note that I'm not certain whether it's the pipeline file stored remotely or instead a project file.
2) place the file at a new version-specific URL
3) change CP's code to refer to a version-specific URL

Does this seem a viable solution to the problem?  Is this something we'd have to do for every new release and if so is there a way to avoid this being a manual process each time?

**Comment by AnneCarpenter** [comment]
It's fixed in beta!  :wow:

**Comment by 0x00b1** [comment]
@AnneCarpenter Yeah! This was a fixed a few months back. I apologize for not closing!

**Comment by AnneCarpenter** [comment]
Well, I just made the issue two hours ago so I'd be impressed if you could've pre-emptively closed it a few months back!

**Comment by braymp** [comment]
The fix was to globally remove the warning altogether, correct?

**Comment by AnneCarpenter** [comment]
I think @0x00b1 would be the only one to know - can you comment @0x00b1 ? 

BTW, found the existing issue, I've no idea why Github's search refused to show it to me before! It's here: #2016  But it is odd that it is open. I will close it now, but hopefully Allen can take a look and re-open if I've misunderstood something.
