### ISSUE TITLE
Update module templates to reflect current preferred style

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2289]

**Comment by 0x00b1** [comment]
Thanks, @bethac07!

**Comment by AnneCarpenter** [comment]
Some style issues to verify: 
- Note whether the module supports 3D (#3156)
- Note whether the module respects masks or not (#2245)
- See also should have a heading (#3215)
- Heading sections should be in right order (#3177)

I'm guessing there are lots of other things to check re code style, these just pertain to the help sections.
