### ISSUE TITLE
Remove RenameOrRenumberFiles

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2293]
This is a dangerous module and it can be done from the command line by someone who knows what they are doing.

**Comment by braymp** [comment]
Believe it or not, I used it just the other day :smile: But I have no opinion one way or the other....

**Comment by AnneCarpenter** [comment]
Well, I'll be!  That's surprising!  We are aiming to reduce the codebase and constrain what functions CellProfiler is really responsible for. Feel free to use old releases of CP for this functionality for the next decade or so.  :)
