### ISSUE TITLE
Error using main window

### ISSUE THREAD

**Issue by tomgreen66** [CellProfiler/CellProfiler#2294]
When loading up Cellprofiler (2.2.0 and building from latest repository version) I get the following error:

> Traceback (most recent call last):
>   File "/software/tools/pyenv/versions/2.7.9/envs/2.7.9-cellprofiler-dev/src/cellprofiler/cellprofiler/gui/pipelinelistview.py", line 1630, in on_mouse_move
>     else self.items[index]
> IndexError: list index out of range

It seems to happen fairly randomly.  I attach a screenshot
![cellprofiler_error](https://cloud.githubusercontent.com/assets/2301394/18312898/cfc04146-7503-11e6-8ee0-1c4835ac1e1b.png)

If I continue the processing it seems to work.

Happy to provide further information.

**Comment by DavidStirling** [comment]
No longer a problem in CellProfiler 3.
