### ISSUE TITLE
Underscores in object names create sublevels in ExportToSpreadsheet measurement selection

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2297]
Working with a user at an in-person tutorial today (CP 2.2 Stable, OSX Yosemite 10.10.5); I created some objects for him (Green_Nuclei). When I went to "Select measurements to output" in ExportToSpreadsheet under Image->Count instead of seeing "Green_Nuclei" I saw "Green", with then a sublevel called "Nuclei".  My presumption is that it wouldn't probably break anything critical in the export but it's definitely confusing.

**Comment by VolkerH** [comment]
Just noticed this behaviour is still present in 3.1.5

![image](https://user-images.githubusercontent.com/2210044/48044829-00f95980-e1e2-11e8-882f-914c8517985c.png)

![image](https://user-images.githubusercontent.com/2210044/48044877-369e4280-e1e2-11e8-89e7-9cc35ed6acc9.png)

**Comment by DavidStirling** [comment]
Since this is to do with the way that measurements are named and parsed there won't be a simple fix for this. The actual image names are not effected, only sub measurements in other groups, so I expect the actual practical impact is minimal - just check the extra box.
