### ISSUE TITLE
Ensure all mention of GPL is purged, given CP's BSD-3 license

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2301]
1) check the codebase/everything in Github for "GPL" and "gnu"
2) check online to see if anything prominent comes up (I just changed Wikipedia a few weeks ago, for example - it had slipped through the cracks)

**Comment by 0x00b1** [comment]
Issues isn’t a to-do list. 😉

If you find a mention of GNU or GPL, please file a new issue.

**Comment by AnneCarpenter** [comment]
Allen checked (1) and we are clear! I will ask Jeanelle to do (2).
