### ISSUE TITLE
Load multi-page TIFs as volumes

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2355]
The Open module opens an image.

While functionality equivalent to `LoadSingleImage`, the Open module is much simpler.

**Comment by AnneCarpenter** [comment]
Oh! When I read this I assumed you meant open like mathematical opening. Then was amused. Isn't there a module in the works called Opening  that would be confused with this?

**Comment by 0x00b1** [comment]
The user should be asked for the following information about their image:

Is the file multichannel?

If the file is a multichannel image, it’ll have the shape:

```
(x, y, channel)
```

If the file isn’t a multichannel image (i.e. it’s a grayscale image), it’ll have the shape:

```
(x, y)
```

Is the file a volume (i.e. a three-dimensional or multi-page image)?

If the file is a volume, it’ll have the shape:

```
(z, x, y)
```
And if the file is a multichannel volume, it’ll have the shape:

```
(z, x, y, channel)
```

If the image is a volume, they should provide an optional spacing—spacing between voxels in each spatial dimension (i.e. x, y, and z). If spacing isn’t provided, the spacing is assumed to be (1.0, 1.0, 1.0).

Is the file time varying (i.e. a time-lapse image)?

If the file is time varying, it’ll have the shape:

```
(t, x, y)
```

And if the file is multichannel time varying, it’ll have the shape:

```
(t, x, y, channel)
```

And if the file is a time-varying volume:

```
(t, z, x, y)
```

And if the file is a multichannel time-varying volume, it’ll have the shape:

```
(t, z, x, y, channel)
```

**Comment by 0x00b1** [comment]
Here’s a table that describes the possible shapes:

| multichannel | volume | time varying | shape                   |
| ------------ | ------ | ------------ | ----------------------- |
| True         | True   | True         | `(t, z, x, y, channel)` |
| True         | True   | False        | `(z, x, y, channel)`    |
| True         | False  | True         | `(t, x, y, channel)`    |
| True         | False  | False        | `(x, y, channel)`       |
| False        | True   | True         | `(t, z, x, y)`          |
| False        | True   | False        | `(z, x, y)`             |
| False        | False  | True         | `(t, x, y)`             |
| False        | False  | False        | `(x, y)`                |

**Comment by 0x00b1** [comment]
The next step is adapting CellProfiler’s Image class. We’d expose the following properties:

Channels: an integer value that states the number of channels in a grayscale or multichannel image. If an image is grayscale (i.e. the value of the “grayscale” property is “True”), the value of the “channels” property is “1.” “Channels” is an immutable property.

Grayscale: a Boolean value that states whether an image is or isn’t a grayscale (i.e. single-channel) image. If an image is grayscale, the value of the “grayscale” property is “True.” Similarly, if an image isn’t grayscale the value of the “grayscale” property is “False.” It’s the inverse of the “multichannel” property. “Grayscale” is an immutable property.

Multichannel: a Boolean value that states whether an image is or isn’t a multichannel image. If an image is multichannel, the value of the “multichannel” property is “True.” Similarly, if an image isn’t multichannel the value of the “multichannel” property is “False.” It’s the inverse of the “grayscale” property. “Multichannel” is an immutable property.

Frames: an integer value that states the number of frames in a time varying image. If an image isn’t time varying (i.e. the value of the “time varying” property is “False”), the value of “Frames” is “None.” “Frames” is an immutable property.

Planes: an integer value that states the number of planes in a three-dimensional image. If an image is two-dimensional (i.e. the value of the two-dimensional property is “True”), the value of “Planes” is “None.” “Planes” is an immutable property.

Spacing: a three-tuple of floats that expresses spacing between voxels in each spatial dimensional (i.e. x, y, and z). If the “two-dimensional” property is “True” (and the “three-dimensional” property is “False”), the value of the “spacing” property is “None.” If the “three-dimensional” property is “True” (and the “two-dimensional” property is “False”), the value of the “spacing” property defaults to “(1.0, 1.0, 1.0).” “Spacing” is a mutable property.

Three-dimensional: a Boolean value that states whether an image is or isn’t three-dimensional. If an image is three-dimensional, the value of the “three-dimensional” property is “True.” Similarly, if an image isn’t three-dimensional the value of the “three-dimensional” property is “False.” It’s the inverse of the “two-dimensional” property. “Three-dimensional” is an immutable property.

Time varying: a Boolean value that states whether an image is or isn’t time varying. If an image is time varying, the value of the “time varying” property is “True.” Similarly, if an image isn’t time varying the value of the “time varying” property is “False.” “Time varying” is an immutable property.

Two-dimensional: a Boolean value that states whether an image is or isn’t two-dimensional. If an image is two-dimensional, the value of the “two-dimensional” property is “True.” Similarly, if an image isn’t two-dimensional the value of the “two-dimensional” property is “False.” It’s the inverse of the “three-dimensional” property. “Two-dimensional” is an immutable property.

**Comment by 0x00b1** [comment]
A preferable alternative to returning an integer from the “Channels,” “Frames,” and “Planes” properties is to return an iterator for their respective matrices. It’s simplify dimension-wise iteration, e.g.

```Python
for channel in image.channels:
    channel = foo(bar)
```

```Python
for frame in image.frames:
    frame = foo(bar)
```

```Python
for plane in image.planes:
    plane = foo(bar)
```

**Comment by 0x00b1** [comment]
Minimally, when an image is opened, the following measurements must be persisted:

* “MD5Digest” is an image’s MD5 checksum.
* “Scaling” is an image’s intensity scaling.
* “Height” and “Width” are an image’s dimensions.

If “measurements” is a measurement instance, the values are persisted like so:

```Python
measurements["ImageMD5Digest_example"] = …
measurements["ImageScaling_example"] = …
measurements["ImageHeight_example"] = …
measurements["ImageWidth_example"] = …
```

The MD5 checksum and intensity scaling are provided by methods on the underlying image provider.

**Comment by 0x00b1** [comment]
An example image provider:

```Python
class ExampleImageProvider(cellprofiler.modules.loadimages.LoadImagesImageProviderBase):
    def __init__(self, name, pathname, filename):
        super(ExampleImageProvider, self).__init__(name, pathname, filename)

    def provide_image(self, image_set):
        filename = self.get_filename()

        pathname = self.get_pathname()

        data = skimage.io.imread(filename)

        image = cellprofiler.image.Image(
            file_name=filename,
            image=data,
            path_name=pathname
        )

        return image
```

**Comment by 0x00b1** [comment]
An example run method:

```Python
    def run(self, workspace):
        import cellprofiler.modules.namesandtypes

        provider = ExampleImageProvider(self.name.value, self.pathname.value, self.pathname.value)

        name = provider.get_name()

        image = provider.provide_image(workspace.measurements)

        checksum = cellprofiler.modules.namesandtypes.NamesAndTypes.get_file_hash(provider, workspace.measurements)

        workspace.measurements["Image", "MD5Digest_" + name] = checksum

        x, y = image.pixel_data.shape[1], image.pixel_data.shape[0]

        workspace.measurements["Image", "Width_" + name] = x
        workspace.measurements["Image", "Height_" + name] = y

        scaling = provider.scale

        workspace.measurements["Image", "Scaling_" + name] = scaling
```

**Comment by 0x00b1** [comment]
An example Open module:

```Python
"""

Open

"""

import cellprofiler.image
import cellprofiler.measurement
import cellprofiler.module
import cellprofiler.setting
import loadimages
import os
import skimage.io
import numpy


class Open(cellprofiler.module.Module):
    category = "File Processing"

    module_name = "Open"

    variable_revision_number = 1

    def create_settings(self):
        self.pathname = cellprofiler.setting.Pathname(
            "Pathname",
            cellprofiler.setting.NONE
        )

        self.name = cellprofiler.setting.Text(
            "Name",
            ""
        )

        self.multichannel = cellprofiler.setting.Binary(
            "Multichannel",
            False
        )

        self.volume = cellprofiler.setting.Binary(
            "Volume",
            False
        )

        self.spacing = cellprofiler.setting.Float(
            "Spacing",
            1.0
        )

    def run(self, workspace):
        provider = ExampleImageProvider(self.name.value, self.pathname.value, self.pathname.value)

        workspace.image_set.providers.append(provider)

        name = provider.get_name()

        image = provider.provide_image(workspace.measurements)

        checksum = provider.get_md5_hash(workspace.measurements)

        workspace.measurements["Image", "MD5Digest_" + name] = checksum

        x, y = image.pixel_data.shape[1], image.pixel_data.shape[0]

        workspace.measurements["Image", "Width_" + name] = x
        workspace.measurements["Image", "Height_" + name] = y

        scaling = provider.scale

        workspace.measurements["Image", "Scaling_" + name] = scaling

        x_data = image.pixel_data

        dimensions = 2

        if self.show_window:
            workspace.display_data.x_data = x_data

            workspace.display_data.dimensions = dimensions

    def display(self, workspace, figure):
        layout = (1, 1)

        # figure.set_subplots(layout, dimensions=workspace.display_data.dimensions)

        # figure.subplot_imshow(0, 0, workspace.display_data.x_data, dimensions=workspace.display_data.dimensions)

    def settings(self):
        return [
            self.pathname,
            self.name,
            self.multichannel,
            self.volume,
            self.spacing
        ]

    def visible_settings(self):
        __settings__ = [
            self.pathname,
            self.name,
            self.multichannel,
            self.volume
        ]

        if self.volume.value is True:
            __settings__ = __settings__ + [
                self.spacing
            ]

        return __settings__


class ExampleImageProvider(loadimages.LoadImagesImageProviderBase):
    def __init__(self, name, pathname, filename):
        super(ExampleImageProvider, self).__init__(name, pathname, filename)

        self.scale = 1

    def provide_image(self, image_set):
        pathname = self.get_pathname()

        data = skimage.io.imread(pathname)

        image = cellprofiler.image.Image(
            file_name=pathname,
            image=data,
            path_name=pathname
        )

        return image
```

**Comment by 0x00b1** [comment]
If we replace `pathname` with a directory setting, we can glob the images from that directory and read them one by one.

**Comment by 0x00b1** [comment]
We can forego a new module entirely by modifying `LoadImagesImageProvider`:

```Python
class LoadImagesImageProvider(LoadImagesImageProviderBase):
    def __init__(self, name, pathname, filename, rescale=True, series=None, index=None, channel=None):
        super(LoadImagesImageProvider, self).__init__(name, pathname, filename)

        self.channel = channel

        self.index = index

        self.rescale = rescale

        self.scale = 1.0

        self.series = series

    def provide_image(self, image_set):
        channel_names = []

        filename = self.get_filename()

        pathname = self.get_pathname()

        scale = self.scale

        data = skimage.io.imread(
            fname=os.path.join(pathname, filename)
        )

        image = cellprofiler.image.Image(
            filename=filename,
            image=data,
            pathname=pathname,
            scale=self.scale
        )

        if data.ndim == 3 and len(channel_names) == data.shape[2]:
            image.channel_names = list(channel_names)

        return image
```

**Comment by 0x00b1** [comment]
However, we’ll still need to add the aforementioned properties to CellProfiler’s Image class.

We’ll also need to modify the types for the “Select the image type” setting from the NamesAndTypes module, e.g.

“Grayscale” should become “Two-dimensional grayscale.”

“Color” should become “Two-dimensional color.”

“Binary mask” should become “Two-dimensional binary mask.”

And add some additional image types:

“Three-dimensional grayscale”

“Three-dimensional color”

Alternatively, we could replace the “Select the image type” setting with discrete settings, e.g.

“Binary”

“Multichannel”

“Dimensionality”

(And if “Dimensionality” is “Three-dimensional,” add a setting for “Spacing”.)

“Time varying”

**Comment by bethac07** [comment]
Radio buttons?
![image](https://cloud.githubusercontent.com/assets/6721515/18759517/c7aefcc2-80ca-11e6-9051-3e1cdc56c7b7.png)

**Comment by 0x00b1** [comment]
Updated:

```Python
"""

Open

"""

import cellprofiler.image
import cellprofiler.measurement
import cellprofiler.module
import cellprofiler.setting
import loadimages
import os
import skimage.io
import numpy


class Open(cellprofiler.module.Module):
    category = "File Processing"

    module_name = "Open"

    variable_revision_number = 1

    def create_settings(self):
        self.name = cellprofiler.setting.Text(
            "Name",
            ""
        )

        self.pathname = cellprofiler.setting.Pathname(
            "Pathname",
            cellprofiler.setting.NONE
        )

        self.spacing = cellprofiler.setting.Float(
            "Spacing",
            1.0
        )

        self.three_dimensional = cellprofiler.setting.Binary(
            "Three-dimensional",
            False
        )

        self.time_varying = cellprofiler.setting.Binary(
            "Time varying",
            False
        )

    def run(self, workspace):
        provider = ThreeDimensionalImageProvider(self.name.value, self.pathname.value, self.pathname.value)

        workspace.image_set.providers.append(provider)

        name = provider.get_name()

        image = provider.provide_image(workspace.measurements)

        checksum = provider.get_md5_hash(workspace.measurements)

        workspace.measurements["Image", "MD5Digest_" + name] = checksum

        x, y = image.pixel_data.shape[1], image.pixel_data.shape[0]

        workspace.measurements["Image", "Width_" + name] = x
        workspace.measurements["Image", "Height_" + name] = y

        scaling = provider.scale

        workspace.measurements["Image", "Scaling_" + name] = scaling

        x_data = image.pixel_data

        dimensions = 3

        if self.show_window:
            workspace.display_data.x_data = x_data

            workspace.display_data.dimensions = dimensions

    def display(self, workspace, figure):
        layout = (1, 1)

        figure.set_subplots(
            dimensions=workspace.display_data.dimensions,
            subplots=layout
        )

        figure.subplot_imshow(
            dimensions=workspace.display_data.dimensions,
            image=workspace.display_data.x_data,
            x=0,
            y=0
        )

    def settings(self):
        return [
            self.name,
            self.pathname,
            self.spacing,
            self.three_dimensional,
            self.time_varying
        ]

    def visible_settings(self):
        __settings__ = [
            self.pathname,
            self.name
        ]

        if self.three_dimensional.value is True:
            __settings__ = __settings__ + [
                self.spacing
            ]

        __settings__ = __settings__ + [
            self.three_dimensional
        ]

        if self.three_dimensional.value is True:
            __settings__ = __settings__ + [
                self.spacing
            ]

        __settings__ = __settings__ + [
            self.time_varying
        ]

        return __settings__


class ThreeDimensionalImageProvider(loadimages.LoadImagesImageProviderBase):
    def __init__(self, name, pathname, filename):
        super(ThreeDimensionalImageProvider, self).__init__(name, pathname, filename)

        self.scale = 1

    def provide_image(self, image_set):
        pathname = self.get_pathname()

        data = skimage.io.imread(
            fname=pathname
        )

        image = cellprofiler.image.Image(
            dimensions=3,
            file_name=pathname,
            image=data,
            path_name=pathname
        )

        return image
```

While it successfully opens and displays three-dimensional images, adding another module and running the pipeline yields:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011479ced4, pid=1261, tid=2571
#
# JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [_core_.so+0x69ed4]  _Z17_wrap_Window_HideP7_objectS0_+0x4f
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/agoodman/Documents/com/github/CellProfiler/CellProfiler/hs_err_pid1261.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
```

**Comment by mcquin** [comment]
This is SO last year https://github.com/CellProfiler/CellProfiler/pull/2366
