### ISSUE TITLE
DirectoryPath doesn’t return correct pathname

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2357]
When I select my desktop directory on macOS, the DirectoryPath setting returns

`/Desktop` 

rather than `/Users/agoodman/Desktop`.

**Comment by 0x00b1** [comment]
I’ll never understand why Apple used mixed-case for system directories (e.g. “Users” and “Desktop”).

**Comment by DavidStirling** [comment]
Doesn't seem to be a problem in current CP, do re-open if it is!
