### ISSUE TITLE
JIRA [IMG-169] Combine Correct Illumination - Calculate and Apply

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#236]
what do you think about having a single illum corrxn module, where the user has the option to&#39;turn off&#39; the Calculate or Apply portions of the module?  Seems more user friendly to me, rather than the typical person needing to know that they should put both modules into the pipeline.<br/><br/>The HT advanced users are the only ones who separately want to calculate and apply in two dift pipelines and they will be able to answer&quot;NOne&quot; to the question -&quot;to which image do you want to apply the illum corrxn?&quot;, and in the Analysis pipeline they can answer&quot;How do you want to calculate illum corrxn?&quot; with the name of a precalculated image rather than a method for calculating within the pipeline.<br/><br/>What do you all think?<br/><br/>On Aug 13, 2009, at 10:37 AM, Lee Kamentsky wrote:<br/><br/>It&#39;s not bad for the simplest case where the illumination correction is calculated directly on the images of a group of files. It&#39;s difficult to understand what Calculate does with derivative images - the pipeline has to run to completion with these and they can&#39;t be used, except by SaveImages. I guess that maybe combining Calculate and Apply actually helps - I might be able to make it so that you can&#39;t apply a derived image.<br/><br/>Anne Carpenter wrote:<br/>ooh, yes that would be a nice side benefit - it would notify you that there is a problem if you select Calculate based on All images but then Apply in the same pipeline.... alternately, we could allow it to work by doing sub-cycles of the Calculate step to completion before proceeding to Apply, but most likely that makes the pipeline take way longer than the person would have expected and they should probably just be warned that they most likely want to Calculate and Save it so that they don&#39;t have to repeat the&#39;calculation on all&#39; step every time they process images with the pipeline.<br/><br/>With a combined module, I like that the simple user doing an Each method can easily do what they want, and that we can additionally provide more guidance for complex cases as described above.

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-169
Assignee: leek

**Comment from anne on Fri, 16 Jul 2010 09:51:30 -0400:**
This may be affected by decisions related to looping.

**Comment by AnneCarpenter** [comment]
Not a bad thing to think about but needs discussion and isn't a priority.
