### ISSUE TITLE
Make validate settings faster

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2364]
Users on the forum report that it's slow to the point of impeding use:
http://forum.cellprofiler.org/t/youtube-tutorials-feedback-thoughts/3935/6

Relevant portion here:

>  the flashing of the drop down boxes when things are changed as CP checks for correct variable assignment is slow. It seems overly painful for a simple checking like that, and I wonder how much it's being bogged down by the GUI over the actual check (maybe greying out would be better).

**Comment by braymp** [comment]
Oh yes, definitely. It appears to have gotten worse with 2.2.0, perhaps something to do with going from wx 2.8 to 3.0?

**Comment by AnneCarpenter** [comment]
Oooh, that is very helpful to know that it's changed over time.

**Comment by DavidStirling** [comment]
Doesn't seem to be a problem in the current build. I'm not sure if it was changed from 2.2 to 3.0, but please do re-open this if there's still an issue with validation speed.
