### ISSUE TITLE
Adjust the module behavior in test mode, so can adjust settings for the module of interest

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2365]
A user mentions in a CP tutorial that it would be very handy to "lock" the view to a certain module's settings when in Test Mode. This appeared here: http://forum.cellprofiler.org/t/youtube-tutorials-feedback-thoughts/3935/2

When asked for clarification, he says this: 

> My request to 'lock' to one module stems from my simple minded frustration when editing, for example, a primary object (P) that's right above a secondary object (S) (or say two primary objects in a row), and getting mixed up with which one I'm editing. In test mode when I change a setting in P it brings the left-hand marker back to that module. I then click step and it shifts to S, which looks near identical to P and then I start editing S thinking that I'm editing P... All I have to do is remember to click back, but I never do, and I'm constantly 'arhhhhh'-ing to myself and clicking back and forth. When editing a module I might want to empirically repeat that test step many times, and it would be nice to hold the focus of the test steps to that module in these cases. Maybe a 'pin' icon column could appear in test mode indicating those modules that would be 'pinned'... The test would step as usual, but when it hits a pinned module the settings window would freeze with those settings displayed...?

Another user chimes in and says:

> I agree with you that being able to prevent test mode from stepping to the next module would allow to more quickly optimize the parameters of the current step. Similarly, it would be useful if there was an option for a "live update mode", where the output window of a module is kept open and when a parameter is changed, this is reflected in the output window immediately (without clicking "Step"). In addition to making parameter optimization (the most time consuming step) faster, I think live updates would appeal to beginners by making CellProfiler more intuitive and straightforward to use (shorter time between changing a parameter and seeing the result). I also believe this would affect how user friendly CellProfiler is perceived to be (someone who is used to image analyses might not think it is a big deal to click a few additional buttons for a result to pop up, but when getting accustomed to new software, it is very helpful to immediately see the effects of changing a setting), which might be one of the most important aspects in getting some of my colleague to switch to CellProfiler from commercial image analyses solutions.

I'm afraid it's not super clear to me personally what the behavior ought to be precisely, but @bethac07 might be able to verbalize. I can't tell if it's just a matter of changing which module remains 'selected' after test mode hits the pause point?

**Comment by braymp** [comment]
Re: focus shift - I understand what they're saying here, b/c I get frustrated by the same thing and do it all the time. But I think it's a bit counter-intuitive to *not* have the focus shift to the next module, seeing as you just executed the prior one. Like you, not sure what the proper behavior should be...

Re: visualizing the effects of changing a setting - This is a big reason why the workspace viewer is awesome-sauce and needs more airtime :smile:

**Comment by AnneCarpenter** [comment]
It seems to me that in test mode you want the pipeline to stop after a certain module X is completed (so that you can muck with X's settings). I would expect that after module X completes, the focus/selection would be on module X. Is that not the case?

**Comment by braymp** [comment]
> I would expect that after module X completes, the focus/selection would be on module X. Is that not the case?

Correct, that's not the case. When module X completes, focus shifts to the following module. Similarly, if I need a pause, I place it immediately _after_ the last module I want executed, not the last module itself.

**Comment by VolkerH** [comment]
Just weighing in here as a user with a different opinion.

I think the "stepping forward to the next module" in test mode is necessary. This is the way debuggers work and for me test mode is a debugger. 
Without shifting focus to the next module automatically, if you wanted to go through a pipe-line step by step you would have to follow a logic of "execute current command", "advance to next command", requiring two clicks per step. 

I agree that it is a bit bothersome always having to move back the slider one step if one wants to optimize parameters and repeatedly execute a single module. Maybe this could be made easier be a keyboard shortcut "move one step back" (there may already be one).

**Comment by mcquin** [comment]
Agree that locking a module is unexpected behavior and will lead to more confusion.
