### ISSUE TITLE
Enable adding text to the module names displayed in the pipeline

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2370]
As requested on this forum post: http://forum.cellprofiler.org/t/attention-users-help-us-with-usability-improvements/1124/31?u=anne_carpenter

Salient part here:
> what i would really like is to be able to add annotation to or near the module name. It would help me navigate the pipeline a bit easier during auditing, and tweaking.

This is a very common request. People often want to differentiate, for example, IdentifyPrimaryObjects-Nuclei and IdentifyPrimaryObjects-Spots. Or, Morph-open and Morph-close.

I suspect we would want to right-click the module name in the pipeline, choose "Edit module name" (or something better like "Add to module name" since you can't really edit the name itself), and then it allows you to type in text which is added to the conventional module name and separated by some symbol like "-" to make parsing it easier within the code (and also make it easier to see within the pipeline). 

We'd want to ensure people could only type in plain text if doing otherwise will upset the code.

I'm closing the issue and marking it for discussion and future consideration because it's not likely a huge priority and also because my suspicion is that it's a pain to implement due to the fact that currently the module names themselves are not just arbitrary strings but working pieces of code.

**Comment by bethac07** [comment]
I agree that changing the module names seems like a headache, but I like @karhohs ' idea in #2133 for some sort of color coding/grouping- you could do it by changing the color behind each module name or by using a [StaticBox](http://docs.wxwidgets.org/trunk/classwx_static_box.html) around logical segments.  However, I have no intuition which is more annoying- rewriting how module names are handled or rewriting GUI code.    I kind of suspect the latter.

**Comment by 0x00b1** [comment]
This is half-the-problem, you also need to consider persistence (e.g. storing keys in the pipeline file).
