### ISSUE TITLE
pip does not grab the scipy wheel when running `pip install -e .`

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2372]
It tried (and failed) to install from source.

Tested on OS X (10.11.6).

**Comment by mcquin** [comment]
This appears to no longer be true

![screen shot 2017-04-20 at 8 59 29 am](https://cloud.githubusercontent.com/assets/4721755/25231939/b4687de6-25a7-11e7-90d7-d34952c4af83.png)
