### ISSUE TITLE
`pip install -e .` fails if cython is missing

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2376]
Tested on OS X (10.11.6).

**Comment by 0x00b1** [comment]
Centrosome requires Cython. We can fix this by shipping Wheels for Centrosome.

**Comment by burgerga** [comment]
Same issue on Ubuntu 16.04 with current installation instructions

**Comment by mcquin** [comment]
Closed via https://github.com/CellProfiler/centrosome/pull/81
