### ISSUE TITLE
GammaCorrection: Odd font

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2377]
Had a look at the new modules in master (as is my wont). Noticed that the third setting in GammaCorrection had wonky text:
![image](https://cloud.githubusercontent.com/assets/1186440/18968397/cf1fb71c-8656-11e6-9a32-04d9134fbf8d.png)

**Comment by 0x00b1** [comment]
Bummer. I guess I should use "Gamma" for the label until we fix Unicode support.

**Comment by 0x00b1** [comment]
@braymp And thanks for poking! All feedback on the new modules is welcome.
