### ISSUE TITLE
JIRA [IMG-127] Handle lost connections to MySQLdbserver better

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#238]
CP data was uploaded (Batch #1113) but an error occurred during the upload, which truncated the upload, though the user was unawares.<br/><br/>The error:<br/>ERROR 2013 (HY000) at line 1777: Lost connection to MySQL server during query<br/>found within this upload output file:<br/><a href="http://seaborgium/batchprofiler/cgi-bin/ViewTextFile.py?file_name=/imaging/analysis/2007_10_19_Gilliland_LeukemiaScreens/Screen5_May6/2007_10_19_Gilliland_LeukemiaScreens_Validation_SETUP.out">http://seaborgium/batchprofiler/cgi-bin/ViewTextFile.py?file_name=/imaging/analysis/2007_10_19_Gilliland_LeukemiaScreens/Screen5_May6/2007_10_19_Gilliland_LeukemiaScreens_Validation_SETUP.out</a>

Original reporter: dlogan
Jira link: https://jira.broadinstitute.org/browse/IMG-127
Assignee: leek

**Comment from anne on Fri, 16 Jul 2010 09:47:00 -0400:**
The key thing here is just to issue a warning.

**Comment by 0x00B1** [comment]
This issue was moved to CellProfiler/BatchProfiler#31
