### ISSUE TITLE
Welcome Screen example pipeline URL broken

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2385]
CP Dev.
Launch Welcome Screen
Click on first link "[Load](http://cellprofiler.org/ExampleFlyImages/ExampleFlyURL.cppipe) an example pipeline..."

Link is broken.

![image](https://cloud.githubusercontent.com/assets/1225595/19115222/26006d2e-8adf-11e6-80c1-095be9bdb714.png)

Related to https://github.com/CellProfiler/cellprofiler.github.com/issues/28

**Comment by braymp** [comment]
This actually works for me. Could it be that your http/https proxy isn't set up properly? I've seen folks here who haven't been able to load the welcome screen pipeline b/c (most likely) of proxy settings.

**Comment by AnneCarpenter** [comment]
I confirm it's working for me, now- @N3llz has just recently fixed it and might not have closed the issue yet?

**Comment by N3llz** [comment]
Yup, sorry, closed it on the CP website github but not here, thanks @braymp and @AnneCarpenter!
