### ISSUE TITLE
Masking display NaN instead of zero

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2386]
Per this forum post [http://forum.cellprofiler.org/t/inf-and-nan-treatment-in-measureobjectintensity/2399/4](url): 
`I think the issue here is that after applying MaskImage you cannot really see as a user whether a pixel is just set to zero or whether it is really masked, because masked pixels appear as zeros in mouse-over. I am always double checking with some test images where I know the desired result. This situation is in fact not ideal and it is very easy to go wrong here and publish some wrong results without even noticing. For instance if I do further operations on a masked image, e.g. add it to another one, I am always super scared that the mask is lost at some point; which I think it isn't but still it is scary. Probably it would be very good (essential) if the mouse-over would show NaN instead of zero in case it is a masked pixel.`

Given that this probably involves changing how masks are stored and passed along the pipeline, in addition to the display, I'm marking it for future consideration but closing for now.

**Comment by braymp** [comment]
Related to https://github.com/CellProfiler/CellProfiler/issues/846
