### ISSUE TITLE
features/joblib immediate NamesAndTypes error

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2392]
![image](https://cloud.githubusercontent.com/assets/156232/19360133/2fa5193e-914b-11e6-8b09-c2b3fdb8e061.png)

I can update the Metadata module and the NamesAndTypes module successfully. However, when running the pipeline or starting test mode, I get the error seen in the above dialog box. I can successfully run the demo pipeline from this branch.

**Comment by mcquin** [comment]
#2271
