### ISSUE TITLE
Implement CP module to segment with ilastik 1.2

### ISSUE THREAD

**Issue by stuarteberg** [CellProfiler/CellProfiler#2393]
It would be nice if CP could use ilastik's pixel classification workflow for segmentation.

As discussed on Friday, let's start with the simplest possible solution, and then see if that isn't suitable for some reason.  At that point, we can talk about making it better.

Here are the options we discussed:
## 1. Use the headless CLI

The simplest solution is to just ask the user where to locate the ilastik executable, and then call it via it's command-line ("headless") interface.  The documentation for the command-line interface is here:

http://ilastik.org/documentation/pixelclassification/headless

Pros:
- Easy to implement
- Command-line API is stable at this point

Cons:
- Results are passed via the hard-disk, which is slower than necessary
- ilastik application start-up time is non-trivial, but not so bad in headless mode, which doesn't import any GUI modules (e.g. PyQt)
- There's no explicit progress reporting signal for CP to monitor and display to the user (unless you try to parse the console output from ilastik, which I don't recommend)
## 2. `import ilastik` python module directly into the CP process

Pros:
- Least I/O overhead

Cons:
- Requires CP and ilastik build systems to be compatible with each other -- not trivial
- ilastik's Python API is reasonably stable, but not officially so (yet)
## 3.  Extract the saved ilastik classifier from the user's `.ilp` project file, and re-implement the pixel prediction algorithm within CP

Pros:
- No IPC/CLI communication with ilastik needed

Cons:
- Requires re-implementing ilastik's image features and classifier output. Without `vigra` this is (at best) inefficient or impossible.  (For example, `skimage` doesn't support 3D structure tensors, AFAICT.)
- Requires defined "API" for the classifier storage format (including which features are selected), which is at the moment considered to be an implementation detail, not a public interface.
## 4.  Use IPC to send/receive image data from a running ilastik instance

Pros:
- No startup lag if ilastik is already running in the background
- Faster than using the hard disk to transfer images

Cons:
- Need to agree on an IPC mechanism (e.g. JSON over sockets), and a shared API.
- Requires user cooperation ("Please open ilastik and click 'Start RPC Server' then, select port 3000.")

**Comment by chaubold** [comment]
Hi all,

I'planned my visit to the Broad Institute this week such that we could approach the ilastik integration together on Wednesday, June 14th -- if you are interested and your schedule permits?

We are putting a lot of effort into interoperability on the ilastik side at the moment, so it would be really great to get the integration into CellProfiler working again.

I think we should be able to set up option 1. easily, and then maybe discuss what kind of API for option 4. would suit you best, because we are currently in the planning stage to provide an IPC API for ilastik's computational backend.

Best,
Carsten

**Comment by mcquin** [comment]
https://github.com/CellProfiler/CellProfiler-plugins/pull/13

**Comment by mcquin** [comment]
This issue has been moved to CellProfiler-plugins.
