### ISSUE TITLE
Deprecate MATLAB compatibility

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2403]
- [ ] https://github.com/CellProfiler/CellProfiler/issues/2522 Deprecate loading Matlab pipelines.
- [ ] [needs issue] Deprecate Matlab compatible data-type conversion in cellprofiler.image.

**Comment by AnneCarpenter** [comment]
🎉  The non-MATLAB based version of CellProfiler (2.0) was released in 2010. Thus, I believe removing this compatibility will inconvenience very few users (possibly none).

**Comment by mcquin** [comment]
Closing issue in favor of a GH project.
