### ISSUE TITLE
Remove "Where's my module?"

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler#2425]
In the Add Modules box, the Where's my module? button goes to this link http://cellprofiler.org/forum/viewtopic.php?f=14&t=806&p=3221#p4486

**Comment by braymp** [comment]
It should be this: http://forum.cellprofiler.org/t/cellprofiler-2-0-faq/664/2. But this button probably should go away :smile:

**Comment by AnneCarpenter** [comment]
+1 for deprecating. :)
