### ISSUE TITLE
Improve brightness/contrast options for image display

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2446]
Copied from a discussion of #2285 by @tischi  regarding image display in CellProfiler:

I think CP would greatly benefit from a more sophisticated Brightness and Contrast adjustment. It is probably enough to be able to enter(slider) min and max values which are mapped to dark and bright, as sometimes neither the log-scale nor the auto-contrast work.

**Comment by braymp** [comment]
Would be nice to have in the workspace viewer.
