### ISSUE TITLE
Add dimensions property to cellprofiler.object.Objects

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2449]
Adding a dimensions property to `cellprofiler.object.Objects` will simplify choosing whether to extract two-or-three dimensional features.

**Comment by mcquin** [comment]
This is a good idea.

**Comment by mcquin** [comment]
Does `spacing` make any sense on objects?

**Comment by 0x00b1** [comment]
I think so! I’ll write an issue.
