### ISSUE TITLE
Add method to return regionprops-like features from cellprofiler.objects.Objects 

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2450]
Adding a method to return `regionprops`-like (e.g. area) features from `cellprofiler.objects.Objects` will simplify feature extraction. While `Objects` has an `areas` method, it would be nice if this was generalized into a method that returned other commonly used features.

**Comment by 0x00b1** [comment]
It would also benefit from the `regionprops` caching mechanism.

**Comment by mcquin** [comment]
+1, especially for sensible caching on object features
