### ISSUE TITLE
Add method to return meshes from three-dimensional cellprofiler.objects.Objects instances

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2451]
Adding a method to return meshes from three-dimensional `cellprofiler.objects.Objects` instances would simplify feature extraction since many measurements require a mesh rather than a label matrix.

**Comment by mcquin** [comment]
Is this a subproblem of #2450 ? Meshes would be necessary to compute some of the `regionprops`-like features. Are there features not included in `regionprops` which require meshes?

**Comment by 0x00b1** [comment]
@mcquin Yes, this was motivated by `mesh_surface_area`.
