### ISSUE TITLE
Store objects that have parents in new object in Relate

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#249]
http://cellprofiler.org/forum/viewtopic.php?f=16&t=1497

tl;dr - RelateObjects should store those objects that actually have parents in a new Objects image.

Perhaps we should optionally store objects that are not parented, as well.

**Comment by AetherUnbound** [comment]
This is still desirable! I'll set about adding this.

**Comment by braymp** [comment]
Some comments:
* The background color in the display figure is blue not black: 
![image](https://user-images.githubusercontent.com/1186440/37719916-91c83670-2cfc-11e8-9ea5-4636869e3c2d.png)
*  Setting text: "Name the output object" --> "Name the output objects"
* The help for this setting for this new setting could be more clear as to what the new object is, i.e., does it come from the parent object or the children?
* Do the new objects receive the parent IDs as a measurement? (I think MaskObjects does this, which does somewhat the same thing)

I'm actually sort of wondering whether this new object can be made optional; I'm wondering what sort of use you're thinking of? (I wish the link to the forum post still worked....)

**Comment by AetherUnbound** [comment]
@braymp The "optional" thing seems to be needed! I'll work on getting that addressed #3623 
For now though I'm going to close this.
