### ISSUE TITLE
Zoom doesn't act on all image views simultaneously volumetric-supporting modules.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2496]

**Comment by mcquin** [comment]
Issue name edited because all volumetric modules are affected, and all will be fixed together.

**Comment by mcquin** [comment]
GridSpec doesn't share xy coordinates. Either we:

- Do our own bookkeeping
- Submit a change to matplotlib allowing the functionality.

@bethac07 considers this very important for all assay development.

2D display doesn't use GridSpec. It would be possible to fix this for 2D assay development. However, fixing this would require rewriting the `Figure` constructor. @bethac07 says this would be sufficient for 3.0 release.

Alternatively, move through slices on mouse wheel. This would remove the GridSpec stuff.

**Comment by NasimJ** [comment]
This feature is very much needed and currently it is not working for even a single planes (how it works in 2D). For example, in the 3D image below, in plane z=0 the non-thresholded image is zoomed in, but the corresponding plane of the thresholded image doesn't show zooming:

<img width="835" alt="Zoom-3D" src="https://user-images.githubusercontent.com/55710463/86972587-30900000-c141-11ea-8d2f-b0a16c98fe1b.png">
