### ISSUE TITLE
Centos repo not found

### ISSUE THREAD

**Issue by ysagon** [CellProfiler/CellProfiler#2502]
According to this page:

https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Linux%29

The recommended way to install CellProfiler on Centos is using yum. There is a link on this page for more information :

http://cellprofiler.org/linux.html

But this page is redirected to http://cellprofiler.org/releases/ where it's written that there are no linux version available.

Is the centos repo not available anymore?

**Comment by mcquin** [comment]
@ysagon Correct, the CentOS build is not available on yum. Take a look at these high-level [instructions for installing CellProfiler on CentOS](https://github.com/CellProfiler/CellProfiler/issues/2383#issuecomment-251642904).

**Comment by mcquin** [comment]
I've updated the Wiki page with the same instructions.
