### ISSUE TITLE
Toolbar freezes when EditObjectsManually used

### ISSUE THREAD

**Issue by eahoffman3** [CellProfiler/CellProfiler#2505]
I'm using a 2014 MacBookAir with El Capitain 10.11.6 and CellProfiler 2.2.0. When the EditObjectsManually screen pops up, I am able to click on the tool bar (keep all, remove all, done, etc.) as long as I don't edit any of the objects. As soon as I click on an object, I can no longer click on any of the toolbar icons - it's as if the toolbar is frozen, but I don't get an error report and the other open CellProfiler pipeline screen seems to be fine and I can move it around. I can't X out of the Edit manually screen; the only way I can close the screen is by force quit. Any ideas as to what's happening? Thanks!

**Comment by DavidStirling** [comment]
Unable to replicate on 3.1.9 on either Mac or Windows. Please re-open if this does persist.
