### ISSUE TITLE
Fix stated location of the 'How measurements are named' help thing

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2527]
It's [apparently wrong](http://forum.cellprofiler.org/t/how-measurements-are-named/4241/2) in ExportToSpreadsheet and ExportToDatabase.  Feel free to assign me.

**Comment by braymp** [comment]
It's now in _Help > Using Your Output > How Measurements Are Named_

**Comment by bethac07** [comment]
Whoops, good save on the title Mark, this is why we don't try to post GitHub issues like 30 seconds before needing to exit a train 😄

**Comment by mcquin** [comment]
You've been assigned, @bethac07 .

**Comment by mcquin** [comment]
Closed https://github.com/CellProfiler/CellProfiler/pull/2856
