### ISSUE TITLE
Missing UI indicator in Test Mode for the current module

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2531]
I don't know what that slider thingy is called, but I think it used to look like a triangle in the left-most position in the pipeline window.  For Mac Dev at least, it's missing or invisible: 

![image](https://cloud.githubusercontent.com/assets/1225595/21437377/81506c4c-c851-11e6-8bc0-272c24316301.png)

The current module appears outlined, but if you click another module, this outline disappears.

To reproduce, 
- version = Mac Developer's, master
- Load Welcome screen pipeline
- Start Test Mode

**Comment by 0x00b1** [comment]
I removed this a few months ago. My reasoning was that this feature was easily replaceable by using the pause button. However, that doesn’t address the issue of informing the user where the pipeline is. I suppose this is kind of covered by the status window that pops up when running?

**Comment by dlogan** [comment]
I see, but yeah, the latest figure window might be hidden or even closed.  And it used to be that you could slide the slider up and re-run a module even without any changes in order to, say, recreate a closed figure window.  

So I like the idea of cleaning up the UI, but when the user clicks "Step", they need to be really sure which module is to be run.  Maybe another indicator which doesn't take UI real estate, like a gray- or yellow-shaded module name?  

In any case, a topic for future UI discussion!

**Comment by braymp** [comment]
See #2032 for more discussion points.

**Comment by dlogan** [comment]
OK, I figured this was covered elsewhere.  Closing, as I think all my points above are covered in #2032
