### ISSUE TITLE
watershed from markers should apply binary mask

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2532]

**Comment by mcquin** [comment]
@0x00b1 do you recall the reasoning behind this issue? Looking into it again now, I recall  watershed from markers was designed after [this skimage tutorial](http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_marked_watershed.html). I'm not sure that the input will always be a binary image (unlike when using the "distance" method).

**Comment by AnneCarpenter** [comment]
I think the watershed is performed on an intensity image as you suggest, it's just that if a user in an upstream module applied a mask, that binary mask should be respected. Does that help?

**Comment by mcquin** [comment]
@AnneCarpenter what you say is correct. This module currently accepts an explicit mask setting so that the watershed is only applied to the regions where mask is True. It does this correctly.

I'm closing this issue until we can describe what the incorrect behavior is.
