### ISSUE TITLE
Upgrade to wxPython Phoenix

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2536]
* [Migration guide](https://wxpython.org/Phoenix/docs/html/MigrationGuide.html)
* [Classic vs Phoenix](https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html)

**Comment by mcquin** [comment]
[Installing wxPython Phoenix](https://wiki.wxpython.org/How%20to%20install%20wxPython)

**Comment by DavidStirling** [comment]
Already done
