### ISSUE TITLE
remove `cellprofiler.utilities.utf16encode`

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2538]

**Comment by AetherUnbound** [comment]
After some investigation, it seems that this homebrewed utf-16 converter does some odd stuff with special characters. I think the best plan is to advance the pipeline version set (from current version 3), leave this utf-16 conversion in place for legacy reading but write all new pipelines in the newer format. Once we hit a new major version, we can remove it entirely
