### ISSUE TITLE
Don't convert image data in the style of MATLAB

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2546]
`cellprofiler.image.Image` setter `set_image` ([definition](https://github.com/CellProfiler/CellProfiler/blob/a73bed705d0810540ec206a2489393dcd72da41c/cellprofiler/image.py#L134-L188)) should no longer convert data in a MATLAB-compatible way.

**Comment by braymp** [comment]
Will doing this pose a problem re: expected intensity values coming out?

**Comment by mcquin** [comment]
@braymp Sure, this change could cause incompatibilities in results between CP 2.X and 3.0. It depends on the data type of your images.

As stated in the code comments, the current behavior is:

```
Rescale according to Matlab's rules for im2double:
  * single/double values: keep the same
  * uint8/16/32/64: scale 0 to max to 0 to 1
  * int8/16/32/64: scale min to max to 0 to 1
  * logical: save as is (and get if must_be_binary)
```

From the discussion at https://github.com/CellProfiler/CellProfiler/issues/2285, it is generally agreed that implicit rescaling is bad. This is an opportunity to remove one more instance where CP modifies your data behind the scenes.

This rescaling generally happens once per image, on load, because it rescales only when converting integer data to floating point data. I'd expect you could make most of your 2.X and 3.0 pipelines compatible using RescaleIntensity (assuming you know the data type of your images), but that is only speculation at this time.

**Comment by mcquin** [comment]
Closing because I can use `convert=False` when I need to.
