### ISSUE TITLE
Random image set selection fails when 1 image set per group

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2549]
To replicate:
* Load the welcome screen pipeline
* Enable metadata extraction for "Extract from file folder names", set regex as <code>^(?P<Plate>.\*)\_POS(?P<Site>[0-9]\*)_</code> and hit the "Update metadata" button
* Enable Groups module and set metadata tag for grouping as "Plate" and "Site" (so there's only 1 image set per group)
* Enter test mode and select "Random image set" to yield the following error:
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2969, in on_debug_random_image_set
  File "mtrand.pyx", line 941, in mtrand.RandomState.randint (numpy\random\mtrand\mtrand.c:10717)
ValueError: low >= high
```

**Comment by DavidStirling** [comment]
Appears to be fixed in the current branch.

**Comment by DavidStirling** [comment]
Scratch that, it's just a lot more broken in the current branch. 😮
