### ISSUE TITLE
The nightly Windows build is 6+ months old

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#2552]
As pointed out here (https://github.com/CellProfiler/cellprofiler.github.com/issues/12) the CPA (and CP) Windows nightly build is well out of date.  I'm opening this here, since the website issue is closed with the understanding that it points to the correct location, but that the build is simply old.

Is there even a Windows build machine any more?

**Comment by mcquin** [comment]
Windows nightlies have fallen behind. Our goal is to get them out there before the 3.0 release. We'll update you once we have them up. :)

**Comment by 0x00b1** [comment]
I’ll note this for posterity, @mcquin and I setup a Windows build machine. It’s running tests (or a subset of tests), but it isn’t building binaries. If it’s helpful, I could work on this for 3.0 since I have some knowledge of the build process.

**Comment by AnneCarpenter** [comment]
Super, glad it's running tests. 

I vote that providing nightlies to the public is a strong priority, it avoids our assay developers repeatedly being asked to make one-offs (while also helping the rest of the world be more self-sufficient).

**Comment by dlogan** [comment]
Thanks for the updates!

**Comment by mcquin** [comment]
Closing in favor of https://github.com/CellProfiler/cellprofiler.github.com/issues/154
