### ISSUE TITLE
Mac Nightly Failing: ImportError: No module named _cwt

### ISSUE THREAD

**Issue by c-scott** [CellProfiler/CellProfiler#2555]
The current (11 Jan 2017) nightly is still not working for me on OSX 10.11.6:

> 11/01/2017 15:38:02.652 CellProfiler[987]: Traceback (most recent call last):
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/__boot__.py", line 81, in <module>
11/01/2017 15:38:02.653 CellProfiler[987]:     _run()
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/__boot__.py", line 62, in _run
11/01/2017 15:38:02.653 CellProfiler[987]:     exec(compile(source, path, 'exec'), globals(), globals())
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/CellProfiler.py", line 1, in <module>
11/01/2017 15:38:02.653 CellProfiler[987]:     import cellprofiler.__main__
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 6, in <module>
11/01/2017 15:38:02.653 CellProfiler[987]:     import cellprofiler.pipeline
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/pipeline.py", line 46, in <module>
11/01/2017 15:38:02.653 CellProfiler[987]:     import cellprofiler.setting as cps
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/setting.py", line 24, in <module>
11/01/2017 15:38:02.653 CellProfiler[987]:     import skimage.morphology
11/01/2017 15:38:02.653 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/morphology/__init__.py", line 11, in <module>
11/01/2017 15:38:02.653 CellProfiler[987]:     from .greyreconstruct import reconstruction
11/01/2017 15:38:02.654 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/morphology/greyreconstruct.py", line 14, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:     from ..filters._rank_order import rank_order
11/01/2017 15:38:02.654 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/filters/__init__.py", line 3, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:     from .edges import (sobel, sobel_h, sobel_v,
11/01/2017 15:38:02.654 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/filters/edges.py", line 17, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:     from ..restoration.uft import laplacian
11/01/2017 15:38:02.654 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/restoration/__init__.py", line 23, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:     from ._denoise import denoise_tv_chambolle, denoise_tv_bregman, \
11/01/2017 15:38:02.654 CellProfiler[987]:   File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/restoration/_denoise.py", line 8, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:     import pywt
11/01/2017 15:38:02.654 CellProfiler[987]:   File "pywt/__init__.pyc", line 16, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:   File "pywt/_extensions/_pywt.pyc", line 14, in <module>
11/01/2017 15:38:02.654 CellProfiler[987]:   File "pywt/_extensions/_pywt.pyc", line 10, in __load
11/01/2017 15:38:02.654 CellProfiler[987]:   File "pywt/_extensions/_pywt.pyx", line 1, in init pywt._extensions._pywt (pywt/_extensions/_pywt.c:32569)
11/01/2017 15:38:02.654 CellProfiler[987]: ImportError: No module named _cwt
11/01/2017 15:38:02.855 CellProfiler[987]: CellProfiler Error
11/01/2017 15:38:02.856 CellProfiler[987]: 2017-01-11 15:38:02.855 CellProfiler[987:12470] CellProfiler Error
>

**Comment by mcquin** [comment]
Thanks for reporting this error! :)

Formatting for readability (wrap text in ` ``` `)

```
11/01/2017 15:38:02.652 CellProfiler[987]: Traceback (most recent call last):
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/boot.py", line 81, in
11/01/2017 15:38:02.653 CellProfiler[987]: _run()
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/boot.py", line 62, in _run
11/01/2017 15:38:02.653 CellProfiler[987]: exec(compile(source, path, 'exec'), globals(), globals())
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/CellProfiler.py", line 1, in
11/01/2017 15:38:02.653 CellProfiler[987]: import cellprofiler.main
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/main.py", line 6, in
11/01/2017 15:38:02.653 CellProfiler[987]: import cellprofiler.pipeline
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/pipeline.py", line 46, in
11/01/2017 15:38:02.653 CellProfiler[987]: import cellprofiler.setting as cps
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/setting.py", line 24, in
11/01/2017 15:38:02.653 CellProfiler[987]: import skimage.morphology
11/01/2017 15:38:02.653 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/morphology/init.py", line 11, in
11/01/2017 15:38:02.653 CellProfiler[987]: from .greyreconstruct import reconstruction
11/01/2017 15:38:02.654 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/morphology/greyreconstruct.py", line 14, in
11/01/2017 15:38:02.654 CellProfiler[987]: from ..filters._rank_order import rank_order
11/01/2017 15:38:02.654 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/filters/init.py", line 3, in
11/01/2017 15:38:02.654 CellProfiler[987]: from .edges import (sobel, sobel_h, sobel_v,
11/01/2017 15:38:02.654 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/filters/edges.py", line 17, in
11/01/2017 15:38:02.654 CellProfiler[987]: from ..restoration.uft import laplacian
11/01/2017 15:38:02.654 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/restoration/init.py", line 23, in
11/01/2017 15:38:02.654 CellProfiler[987]: from ._denoise import denoise_tv_chambolle, denoise_tv_bregman,
11/01/2017 15:38:02.654 CellProfiler[987]: File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/skimage/restoration/_denoise.py", line 8, in
11/01/2017 15:38:02.654 CellProfiler[987]: import pywt
11/01/2017 15:38:02.654 CellProfiler[987]: File "pywt/init.pyc", line 16, in
11/01/2017 15:38:02.654 CellProfiler[987]: File "pywt/_extensions/_pywt.pyc", line 14, in
11/01/2017 15:38:02.654 CellProfiler[987]: File "pywt/_extensions/_pywt.pyc", line 10, in __load
11/01/2017 15:38:02.654 CellProfiler[987]: File "pywt/_extensions/_pywt.pyx", line 1, in init pywt._extensions._pywt (pywt/_extensions/_pywt.c:32569)
11/01/2017 15:38:02.654 CellProfiler[987]: ImportError: No module named _cwt
11/01/2017 15:38:02.855 CellProfiler[987]: CellProfiler Error
11/01/2017 15:38:02.856 CellProfiler[987]: 2017-01-11 15:38:02.855 CellProfiler[987:12470] CellProfiler Error
```
