### ISSUE TITLE
Drag and drop of images into the IMAGES module (within the nightly) does not work.

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2558]

**Comment by braymp** [comment]
Duplicate of https://github.com/CellProfiler/CellProfiler/issues/2115?

**Comment by karhohs** [comment]
@braymp agreed. I wasn't sure if we're past 2.4. This feature isn't mission critical, but it is really nice. Drag and drop feels intuitive.

**Comment by mcquin** [comment]
Maybe only Windows? No problem for me on OS X.

**Comment by karhohs** [comment]
I'm not sure when it happened, but this is no longer a problem. Thanks!
