### ISSUE TITLE
Document how to replicate the IDPrimary functions on volumetric images

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2561]
!!!

**Comment by bethac07** [comment]
I think we don't actually want to do this- it would take like 30 minutes to redo every time you changed a setting.  We should, however, have a help thing in CellProfiler which explains how to replicate this functionality.

**Comment by DavidStirling** [comment]
@bethac07 I'm wondering where in the help we'd want to put this?

**Comment by AnneCarpenter** [comment]
The aim is to show people how to combine a bunch of different 3D compatiable modules together to essentially make IdPrimary work for 3D, right?

If so, then I think there should be just a stub in the IdPrimary's help saying it doesn't work on 3D images but if you'd like to do 3D then (go to this URL to learn how). There should be a similar one in one or more of the 3D modules that make up the core of the solution for 3D (whatever finds the seeds and does the watershed for example).

Now: what should that URL point to? I think we have a 3D tutorial so I'm actually not sure whether that tutorial already serves this purpose?

**Comment by DavidStirling** [comment]
A blog post on "how to replicate IdentifyPrimaryObjects in 3D mode" might be an option. Either that or a dedicated help page in the `help --> other features` menu?

The current 3D tutorial doesn't quite explain how to do this as a standalone workflow. I think it'd be better to have a dedicated page with a more lengthy explanation and the link in the IDPrimary help like you suggest.

**Comment by NasimJ** [comment]
Yes, we do have a [3D tutorial](https://github.com/CellProfiler/tutorials/tree/master/3d_monolayer) that covers the major modules involved, but not all. 

I don't think people could find the help-->other features easily. 
As David suggested, a blog post or tutorial?

**Comment by AnneCarpenter** [comment]
Either sounds good!

>

**Comment by bethac07** [comment]
A blog post is fine, but I think in general we want it to be in the Help->OtherModules as well, so that it ends up part of the main manual.

(Whoops, wrote this 4 days ago, and just found it in an open tab, unsubmitted!)
