### ISSUE TITLE
Option to choose axis direction for Orientation in MeasureObjectSizeAndShape

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2562]
@dlogan and I were trying to work out from the source code what the expected orientation angles calculated by MeasureObjectSizeAndShape ought to be in [this forum post](http://forum.cellprofiler.org/t/nuclear-orientation/4149); in summary, in CP an object pointing up and to the right has a negative angle of orientation, where we expected it to be positive.

After discussing with @0x00b1, this is the expected behavior due to how numpy (and other computer graphics programs) calculate the coordinate space.  Since he said it's easy to pass a "transpose" argument so that the coordinate system becomes the more 'familiar' one, I'm suggesting we use the transposed orientation as the default, plus probably adding a radio button to pick which coordinate system to use.

**Comment by braymp** [comment]
I was just discussing this with my colleagues, who had a similar question re: coordinate origin :smile:  
I pointed them towards http://gamedev.stackexchange.com/questions/83570/why-is-the-origin-in-computer-graphics-coordinates-at-the-top-left for a historical explanation.

**Comment by AnneCarpenter** [comment]
IIUC, then, our convention matches computer graphics'? If so, it does not seem compelling to change its existing behavior (which at the least would cause problems for some users whose data suddenly changes direction). I'd therefore suggest that this issue's title be changed to adjusting the documentation to explain why it is what it is.

**Comment by dlogan** [comment]
I get that images have coordinate systems have origins at the upper-left.  But here that doesn't affect the issue, it seems to me!  Angular orientation is measured with respect to the x-axis, which even for the image coordinate system, still points to the "right".  

For example, an object oriented from lower-left to upper-right like this

![image](https://cloud.githubusercontent.com/assets/1225595/22153645/246bac42-def6-11e6-8337-aa05f6664191.png)

... I expect to have an orientation of +45 degrees, not -45 degrees like CP would return.

As MeasureObjectSizeShape defines it:
```
Orientation: The angle (in degrees ranging from -90 to 90
degrees) between the x-axis and the major axis of the ellipse that has the
same second-moments as the region.
```
but it depends on which arm of the x-axis you start measuring from.

Ultimately, I don't care!  (You say Brontosaurus, I say Apatosaurus, whatever.) Agreed with @AnneCarpenter -- the simplest thing to do is just add a bit more explanation to the help.  I'd prefer a diagram like the one in the Forum post showing how angles are measured.

**Comment by AnneCarpenter** [comment]
Ok, I vote @bethac07 updates the documentation because she is more likely than me to not mess it up by misunderstanding it!
