### ISSUE TITLE
Installation on Ubuntu 15.10

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2565]
From #2564 by @xuanmingshi 

I am trying to install CellProfiler on my Ubuntu15.10. Steps before compiling worked well, but it has problem from there. Below is the information. 

```
/opt/CellProfiler$ pip install --editable . --process-dependency-links
Obtaining file:///opt/CellProfiler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/CellProfiler/setup.py", line 13, in <module>
        import cellprofiler.utilities.version
      File "/opt/CellProfiler/cellprofiler/utilities/version.py", line 121, in <module>
        version_string = get_version()
      File "/opt/CellProfiler/cellprofiler/utilities/version.py", line 81, in get_version
        cwd = cellprofiler_basedir).strip().split(' ')
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/CellProfiler/
```

**Comment by mcquin** [comment]
@xuanmingshi Which branch or tag are you using? Please run:

```
cd /opt/CellProfiler
git branch -vv
```

**Comment by xuanmingshi** [comment]
* (HEAD detached at 2.2.0) ac0529e Update setup.cfg
  master                   f3b7cc3 [origin/master] Merge pull request #2556 from CellProfiler/issues/2555
  stable                   ac0529e [origin/stable] Update setup.cfg



________________________________

**Comment by mcquin** [comment]
@xuanmingshi What is the output of 

```
cd /opt/CellProfiler
git log --format="%ct %h" -n 1
```

**Comment by xuanmingshi** [comment]
1462300260 ac0529e


________________________________

**Comment by mcquin** [comment]
That seems like reasonable output.

We've made several improvements to version detection in CellProfiler since the 2.2.0 release. Do you mind working off the latest code?

```
cd /opt/CellProfiler
git checkout master
pip install -e . --process-dependency-links
```

Let us know if you have success with that! :)

**Comment by xuanmingshi** [comment]
Thank you so much for your help.

I tried "git checkout master"
"fatal: Unable to create '/opt/CellProfiler/.git/index.lock': Permission denied".

Then run under sudo:
[sudo] password for nicholas:
error: Your local changes to the following files would be overwritten by checkout:
    cellprofiler/utilities/version.py
    setup.py
Please, commit your changes or stash them before you can switch branches.
Aborting


then, I did as followed:
pip install -e . --process-dependency-links
Obtaining file:///opt/CellProfiler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/CellProfiler/setup.py", line 13, in <module>
        import cellprofiler.utilities.version
      File "/opt/CellProfiler/cellprofiler/utilities/version.py", line 121, in <module>
        version_string = get_version()
      File "/opt/CellProfiler/cellprofiler/utilities/version.py", line 81, in get_version
        cwd = cellprofiler_basedir).strip().split(' ')
    TypeError: a bytes-like object is required, not 'str'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/CellProfiler/




________________________________

**Comment by mcquin** [comment]
It looks like you may have edited `cellprofiler/utilities/version.py` and `setup.py`. Were you trying to diagnose the error?

To discard all changes, run `git checkout -- .`. Then you can check out master and run the installation command.

**Comment by xuanmingshi** [comment]
Yes, I did. I was trying to fix the problem. I will re-install it and let you know the results.


________________________________

**Comment by xuanmingshi** [comment]
I reinstall the software. And the problem happened again.


nicholas@nshi:~$ cd /opt/CellProfiler/
nicholas@nshi:/opt/CellProfiler$ ls -alh
total 96K
drwxr-xr-x 7 root root 4.0K Jan 25 09:37 .
drwxr-xr-x 6 root root 4.0K Jan 25 09:36 ..
drwxr-xr-x 2 root root 4.0K Jan 25 09:37 artwork
drwxr-xr-x 6 root root 4.0K Jan 25 09:37 cellprofiler
-rw-r--r-- 1 root root 5.5K Jan 25 09:37 CellProfiler64.iss
-rw-r--r-- 1 root root   90 Jan 25 09:37 CellProfiler.py
-rw-r--r-- 1 root root  10K Jan 25 09:37 CONTRIBUTING.md
drwxr-xr-x 8 root root 4.0K Jan 25 09:37 .git
-rw-r--r-- 1 root root  102 Jan 25 09:37 .gitignore
-rw-r--r-- 1 root root 2.3K Jan 25 09:37 LICENSE
-rw-r--r-- 1 root root   45 Jan 25 09:37 MANIFEST.in
drwxr-xr-x 2 root root 4.0K Jan 25 09:37 plugins
-rw-r--r-- 1 root root 1.5K Jan 25 09:37 README.md
-rw-r--r-- 1 root root   13 Jan 25 09:37 requirements.txt
-rw-r--r-- 1 root root 2.6K Jan 25 09:37 setup.cfg
-rw-r--r-- 1 root root  13K Jan 25 09:37 setup.py
drwxr-xr-x 6 root root 4.0K Jan 25 09:37 tests
-rw-r--r-- 1 root root 1.4K Jan 25 09:37 .travis.yml
nicholas@nshi:/opt/CellProfiler$ git checkout stable
fatal: Unable to create '/opt/CellProfiler/.git/index.lock': Permission denied
nicholas@nshi:/opt/CellProfiler$ sudo git checkout stable
Branch stable set up to track remote branch stable from origin.
Switched to a new branch 'stable'
nicholas@nshi:/opt/CellProfiler$ git checkout tags/2.2.0
fatal: Unable to create '/opt/CellProfiler/.git/index.lock': Permission denied
nicholas@nshi:/opt/CellProfiler$ sudo git checkout tags/2.2.0
Note: checking out 'tags/2.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ac0529e... Update setup.cfg
nicholas@nshi:/opt/CellProfiler$ sudo chmod -R o+w \
>     /usr/local/lib/python2.7/dist-packages \
>     /usr/local/bin
nicholas@nshi:/opt/CellProfiler$ pip install --editable . --process-dependency-links
Obtaining file:///opt/CellProfiler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/CellProfiler/setup.py", line 279
        for ext in ".ui", ".png"])]
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/CellProfiler/



________________________________

**Comment by xuanmingshi** [comment]
I ran the codes you sent me yesterday. The same thing happened.


nicholas@nshi:/opt/CellProfiler$ git branch -vv
* (HEAD detached at 2.2.0) ac0529e Update setup.cfg
  master                   98796d7 [origin/master] Merge pull request #2559 from CellProfiler/issues/2293
  stable                   ac0529e [origin/stable] Update setup.cfg
nicholas@nshi:/opt/CellProfiler$ git log --format="%ct %h" -n 1
1462300260 ac0529e
nicholas@nshi:/opt/CellProfiler$ git checkout master
fatal: Unable to create '/opt/CellProfiler/.git/index.lock': Permission denied
nicholas@nshi:/opt/CellProfiler$ sudo git checkout master
Previous HEAD position was ac0529e... Update setup.cfg
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
nicholas@nshi:/opt/CellProfiler$ pip install -e . --process-dependency-links
Obtaining file:///opt/CellProfiler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/CellProfiler/setup.py", line 279
        raise distutils.errors.DistutilsFileError, \
                                                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/CellProfiler/



________________________________

**Comment by xuanmingshi** [comment]
I just saw how to uninstall CellProfiler from wiki page. I only did the first step to delete the folder "/opt/CellProfiler", not the others. Does it affect the installation? Do I need reinstall it with deleting everything as mentioned at wiki page.

**Comment by mcquin** [comment]
Try fully uninstalling CellProfiler before installing again.

**Comment by xuanmingshi** [comment]
I fully uninstalled CellProfiler. It looks like the same thing as previous. Before deleting "/usr/local/bin/cellprofiler", I checked there is no this folder. But there are a lot of programs in "/usr/lib/python2.7/dist-packages/". 
After reinstallation, there is no any file in the both folders any more. Would this be the problem? When I ran the installation of environment, it reported no any problem. Please note that I installed different version of pythons in my laptop, and I understand that CellProfiler should be under python 2.7. 

nnicholas@nshi:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... The following packages were automatically installed and are no longer required:
  linux-headers-4.2.0-38 linux-headers-4.2.0-38-generic
  linux-image-4.2.0-38-generic linux-image-extra-4.2.0-38-generic
  linux-signed-image-4.2.0-38-generic
Use 'apt-get autoremove' to remove them.
Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
nicholas@nshi:~$ sudo apt-get install \
>     cython             \
>     git                \
>     libmysqlclient-dev \
>     libhdf5-dev        \
>     libxml2-dev        \
>     libxslt1-dev       \
>     openjdk-8-jdk      \
>     python-dev         \
>     python-pip         \
>     python-h5py        \
>     python-matplotlib  \
>     python-mysqldb     \
>     python-scipy       \
>     python-vigra       \
>     python-wxgtk3.0    \
>     python-zmq
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cython is already the newest version.
libxslt1-dev is already the newest version.
python-dev is already the newest version.
python-mysqldb is already the newest version.
libhdf5-dev is already the newest version.
python-h5py is already the newest version.
python-matplotlib is already the newest version.
python-scipy is already the newest version.
python-vigra is already the newest version.
python-wxgtk3.0 is already the newest version.
python-zmq is already the newest version.
git is already the newest version.
libmysqlclient-dev is already the newest version.
libxml2-dev is already the newest version.
openjdk-8-jdk is already the newest version.
python-pip is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-headers-4.2.0-38 linux-headers-4.2.0-38-generic
  linux-image-4.2.0-38-generic linux-image-extra-4.2.0-38-generic
  linux-signed-image-4.2.0-38-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
nicholas@nshi:~$ ls /usr/lib/python2.7/dist-packages/
nicholas@nshi:~$ sudo git clone https://github.com/CellProfiler/CellProfiler.git /opt/CellProfiler
Cloning into '/opt/CellProfiler'...
remote: Counting objects: 82306, done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 82306 (delta 159), reused 0 (delta 0), pack-reused 82029
Receiving objects: 100% (82306/82306), 81.14 MiB | 3.26 MiB/s, done.
Resolving deltas: 100% (67788/67788), done.
Checking connectivity... done.
nicholas@nshi:~$ cd /opt/CellProfiler/
nicholas@nshi:/opt/CellProfiler$ ls
artwork             CellProfiler.py  MANIFEST.in  requirements.txt  tests
cellprofiler        CONTRIBUTING.md  plugins      setup.cfg
CellProfiler64.iss  LICENSE          README.md    setup.py
nicholas@nshi:/opt/CellProfiler$ ls -alh
total 96K
drwxr-xr-x 7 root root 4.0K Jan 25 10:04 .
drwxr-xr-x 6 root root 4.0K Jan 25 10:04 ..
drwxr-xr-x 2 root root 4.0K Jan 25 10:04 artwork
drwxr-xr-x 6 root root 4.0K Jan 25 10:04 cellprofiler
-rw-r--r-- 1 root root 5.5K Jan 25 10:04 CellProfiler64.iss
-rw-r--r-- 1 root root   90 Jan 25 10:04 CellProfiler.py
-rw-r--r-- 1 root root  10K Jan 25 10:04 CONTRIBUTING.md
drwxr-xr-x 8 root root 4.0K Jan 25 10:04 .git
-rw-r--r-- 1 root root  102 Jan 25 10:04 .gitignore
-rw-r--r-- 1 root root 2.3K Jan 25 10:04 LICENSE
-rw-r--r-- 1 root root   45 Jan 25 10:04 MANIFEST.in
drwxr-xr-x 2 root root 4.0K Jan 25 10:04 plugins
-rw-r--r-- 1 root root 1.5K Jan 25 10:04 README.md
-rw-r--r-- 1 root root   13 Jan 25 10:04 requirements.txt
-rw-r--r-- 1 root root 2.6K Jan 25 10:04 setup.cfg
-rw-r--r-- 1 root root  13K Jan 25 10:04 setup.py
drwxr-xr-x 6 root root 4.0K Jan 25 10:04 tests
-rw-r--r-- 1 root root 1.4K Jan 25 10:04 .travis.yml
nicholas@nshi:/opt/CellProfiler$ git checkout stable
fatal: Unable to create '/opt/CellProfiler/.git/index.lock': Permission denied
nicholas@nshi:/opt/CellProfiler$ sudo git checkout stable
Branch stable set up to track remote branch stable from origin.
Switched to a new branch 'stable'
nicholas@nshi:/opt/CellProfiler$ sudo chmod -R o+w \
>     /usr/local/lib/python2.7/dist-packages \
>     /usr/local/bin
nicholas@nshi:/opt/CellProfiler$ pip install --editable . --process-dependency-links
Obtaining file:///opt/CellProfiler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/CellProfiler/setup.py", line 279
        for ext in ".ui", ".png"])]
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/CellProfiler/
nicholas@nshi:/opt/CellProfiler$ ls /usr/lib/python2.7/dist-packages/*
ls: cannot access /usr/lib/python2.7/dist-packages/*: No such file or directory
nicholas@nshi:/opt/CellProfiler$ ls /usr/local/bin/cellprofiler
ls: cannot access /usr/local/bin/cellprofiler: No such file or directory

**Comment by mcquin** [comment]
Ensure you are using Python 2.7 when installing CellProfiler. You are installing the stable branch. Please try installing the master branch of CellProfiler, as I believe the errors you see have been resolved.

```
cd /opt/CellProfiler
git checkout origin master
pip install -e . --process-dependency-links
```

**Comment by xuanmingshi** [comment]
I have no idea how to install it using Python2.7. There is no any windows to link CellProfiler specifically to Python2.7.

**Comment by mcquin** [comment]
You can check your working Python version by running `python --version`. If the output is 2.7, you're fine. Else, you'll have to switch Pythons.

**Comment by xuanmingshi** [comment]
The default one is Python3.5
python --version
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

**Comment by xuanmingshi** [comment]
I now know the python version is the problem. I googled the method to run python2 only, but it can not help. I am upgrading my system to 6.04 to see what will happen. Thanks a lot.


________________________________

**Comment by xuanmingshi** [comment]
I upgraded to ubuntu 16.04. Things are better, but I still can not run the last step with ImportError: No module named wx. I tried "


pip install --upgrade wx" but "Failed building wheel for wxpython-phoenix".



Command "/home/nicholas/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_2u4gfjl/wx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dmf66b9b-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_2u4gfjl/wx/


________________________________

**Comment by mcquin** [comment]
Did you run `sudo apt-get install python-wxgtk3.0`?

**Comment by xuanmingshi** [comment]
I did run that command. A good news is that I successfully install CellProfiler in another computer without python3. Hence it is possibly still that python3

affect the installation. I am trying to uninstall python3/anacando from my laptop. Thanks a lot.

________________________________

**Comment by mcquin** [comment]
It's almost definitely Python 3. :) We installed CellProfiler from source on Ubuntu 16.04 using the installation instructions on the wiki recently, without issue.

I'm glad to hear your installation was successful!
