### ISSUE TITLE
Decouple Identify and ApplyThreshold

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2590]

**Comment by braymp** [comment]
Just curious: what does "decouple" mean in this context?

**Comment by mcquin** [comment]
Good question! I'm trying to make it so that ApplyThreshold doesn't subclass Identify. All the thresholding settings and operations will live inside ApplyThreshold and be accessed by Identify. It's less a decoupling than a redefining of relationships. :)

**Comment by mcquin** [comment]
This is turning out to take more time that it's currently worth.

**Comment by mcquin** [comment]
I've figured it out!

And these changes are going to be super necessary as we share code with other modules in the future ;)

**Comment by mcquin** [comment]
#2603
