### ISSUE TITLE
wx error in Test mode run

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2591]
On occasion, using 2.2.0 in Test mode, I will encounter the following error after hitting the "Run" button.
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2917, in on_debug_continue
  File "wx\_windows.pyc", line 3712, in Update
PyAssertionError: C++ assertion "value <= m_maximum" failed at ..\..\src\msw\progdlg.cpp(369) in wxProgressDialog::Update(): invalid progress value
```
No pipeline/images uploaded since the problem is intermittent, across different assays.

**Comment by braymp** [comment]
Should also mention that the user can hit "Continue processing" and proceed with no ill effects.

**Comment by dlogan** [comment]
Appears to be same as #1768.  But Lee had a comment there.

**Comment by braymp** [comment]
Possible StackOverflow solution: http://stackoverflow.com/questions/4824431/wxpython-error-handling-and-repeated-uses

**Comment by mcquin** [comment]
This looks related to https://github.com/CellProfiler/CellProfiler/issues/3461

We can back port the fix.

**Comment by AetherUnbound** [comment]
On second glance it looks like this issue was related to the progress bar value, not the ID overflow issue we've been seeing with #3461

**Comment by DavidStirling** [comment]
Appears to be fixed, please re-open if it's not.
