### ISSUE TITLE
Printing from help pages fails

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2592]
In stable, hitting ctl+p or going to File->Print:
```
Traceback (most recent call last):
  File "cellprofiler\gui\cpframe.pyc", line 1144, in on_print
  File "cellprofiler\gui\cpframe.pyc", line 1203, in print_help
  File "wx\html.pyc", line 1333, in __init__
TypeError: in method 'new_HtmlEasyPrinting', expected argument 2 of type 'wxWindow *'
```

**Comment by AnneCarpenter** [comment]
Just discovered that this solution works for module help, but doesn't work for help files that you access from the main menu such as Help > Running your pipeline.

A possible clue: when a module help window is open/focused, the only items in the menu bar (on Mac) are "CellProfiler, File, Edit". When the main menu Help windows are open, the full menu bar is retained ("CellProfiler, File, Edit, Test, Data Tools, Windows, Help"). 

Interestingly, if you click a module window (which behaves properly) and THEN click a menu bar help window, printing DOES work (and the short "CellProfiler, File, Edit" menu is shown). 

**So it seems like the menu bar help windows just adopt the menu bar (and thus printing behavior/non-behavior) of whatever had focus prior to clicking on the help menu window.**
