### ISSUE TITLE
Make "After declumping only" default for "Fill holes in identified objects?" 

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2593]
Proposed by @dlogan 

https://github.com/CellProfiler/CellProfiler/pull/2586#issuecomment-279065948
https://github.com/CellProfiler/CellProfiler/pull/2586#issuecomment-279067589

Looking for feedback @bethac07 @braymp @karhohs

**Comment by AnneCarpenter** [comment]
What about me???  :D  Yeah, Agreed this should happen, big kudos to @dlogan for catching this!

**Comment by braymp** [comment]
Yes, I've been switching to this option whenever I use IDPrim for at least the last couple of years :smile:
