### ISSUE TITLE
Remove ExportToCellH5 module

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2598]
The ExportToCellH5 module has limited use but requires a number of complex dependencies. We should remove the module from the standard CellProfiler distribution (the ExportToCellH5 module should still be usable by users if they retrieve independent of CellProfiler and copy it to their plugins directory).

**Comment by mcquin** [comment]
Where is ExportToCellH5 now available? Or, where will it be available?

**Comment by 0x00b1** [comment]
@mcquin https://gist.github.com/0x00b1/f6d7ae32c1d8bf2b2fddc6f251dd2087

**Comment by AnneCarpenter** [comment]
Shouldn't the module go here? https://github.com/CellProfiler/CellProfiler-plugins

**Comment by 0x00b1** [comment]
@AnneCarpenter https://github.com/CellProfiler/CellProfiler-plugins/blob/master/exporttocellh5.py

**Comment by AnneCarpenter** [comment]
Yay. I figured you didn't REALLY want it living in your world :D

**Comment by 0x00b1** [comment]
:)
