### ISSUE TITLE
OverlayOutlines only supports one set of outlines at a time

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2604]
In master, setting two sets of outlines to draw in OverlayOutlines causes a blank image to be exported.  You can create the double-overlay by using two OverlayOutlines modules in sequence, but it would be nice to restore the functionality to draw both sets at once.

**Comment by mcquin** [comment]
@bethac07 I am unable to reproduce in 2D:

![screen shot 2017-02-27 at 9 34 59 am](https://cloud.githubusercontent.com/assets/4721755/23365605/9ce731fc-fcd1-11e6-9141-559bcd60e967.png)

Is this happening in 3D? How is your module configured?

**Comment by mcquin** [comment]
I found a different bug in 3D ;)

![screen shot 2017-02-27 at 9 57 23 am](https://cloud.githubusercontent.com/assets/4721755/23366004/32d0d1ea-fcd3-11e6-99e1-a35740615e0b.png)

**Comment by bethac07** [comment]
It's happening in 3D.
![oneoutline](https://cloud.githubusercontent.com/assets/6721515/23366268/2212e8d8-fcd4-11e6-92d8-4e2e701d5d99.jpg)
![twooutlines](https://cloud.githubusercontent.com/assets/6721515/23366270/247b5254-fcd4-11e6-9bc7-51dad0cf4d22.jpg)

**Comment by mcquin** [comment]
I've figured it out! We need to ensure the background image is scaled to [0.0, 1.0]. I'll fix it today. :)
