### ISSUE TITLE
Update documentation on Data Tools

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2641]
Per [this forum post](http://forum.cellprofiler.org/t/many-images-to-one-histogram/133/7), we're currently not sure if the Data Tools support whole-experiment data anymore. If they don't, we should update the documentation accordingly.

**Comment by mcquin** [comment]
Verify whether or not DataTools can be used to view whole-experiment data. If it only supports single-image data, then the documentation should be updated to reflect that.

**Comment by bethac07** [comment]
I believe @DuaaAli was going to verify?  If it verifies pulling #3063 should be enough additional documentation; if it turns out I'm wrong then simply close that PR.

**Comment by bethac07** [comment]
Closed in #3063
