### ISSUE TITLE
NamesAndTypes module does not find any image sets

### ISSUE THREAD

**Issue by cells2numbers** [CellProfiler/CellProfiler#2642]
When I start CellProfiler (3.0.0rc1) I can add images and extract the metadata ( I added a time series containing 121 images; in the metadata module, 121 images are found correctly). 

The NamesAndTypes module says "No Image Sets Available, Sorry, your pipeline doesn't produce any valid image sets as currently configured. Check your Input module settings, or see Help > Creating A Project for additional assistance on using the Input modules."

**Comment by braymp** [comment]
This is going to largely depend on:
* The basis for channel assignment, e.g., file name, metadata, etc
* The actual files being matched, i.e., do the files actually satisfy the criteria you think they should.

So for example, the Metadata module can find the proper metadata but if you refer to it incorrectly/ambiguously in NamesAndTypes, the matching may fail.

The "Loading stacks and movies" tutorial may help on this: http://d1zymp9ayga15t.cloudfront.net/tutorials/Loading_image_stacks_and_movies.pdf

**Comment by cells2numbers** [comment]
Thanks Bray, I checked my settings but still can not find the error. Some more details: I have a time series of 121 image, each image is named as following: 

20130424_FN_cont_0000.png  
20130424_FN_cont_0001.png 
... 
20130424_FN_cont_0120.png. 

I use the following expression to extract dateCreated (=20130424), matrix type ( "FN" in this example), the condition (here it is "cont") and the time point (starting with 0000). 

```^(?P<dateCreated>[0-9]{8})_(?P<matrix>[A-Z]{2})_(?P<condition>[a-z]{4})_(?P<timepoint>[0-9]{4})```

It seems that the Metadata module assigns the values correctly, see attached screenshot. In the NamesAndTypes module I select "Assign a name to All images", see second screenshot. 

I hope I missed something obvious :) 


<img width="1214" alt="screen shot 2017-03-15_metadata" src="https://cloud.githubusercontent.com/assets/21295504/23973507/e08bce76-09ac-11e7-9d04-786d8a97b330.png">
<img width="1213" alt="screen shot 2017-03-15_nameandtypes" src="https://cloud.githubusercontent.com/assets/21295504/23973512/e64549dc-09ac-11e7-8618-377ccc24e980.png">

**Comment by braymp** [comment]
Hmm, I gave it try with some images named similarly (`Ch<5-digit number>.tif` ), extracted metadata and assigned the name exactly as you did; it worked fine.
![image](https://cloud.githubusercontent.com/assets/1186440/24016089/311c8e3e-0a61-11e7-8eb2-c4c18612ae0a.png)

In my case, I was running from source on Windows, after updating from master just now. But it's hard to imagine that would be the cause.

**Comment by cells2numbers** [comment]
I found the error, it was caused by the "Groups" module; the .cppipe contained the entry    ```Metadata category:None``` which caused the error. This was probably my fault: I simply renamed a Metadata category and the groups module did rename the category to ```None```. Thanx all, will close this issue!

**Comment by braymp** [comment]
If that's the case, that's probably a bug that's worth fixing....
