### ISSUE TITLE
Feature Request: Resize Objects in addition to Images

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2644]
When working with 3D data downsampling greatly increases processing speed. However, objects identified in the shrunken image cannot be used to make measurements in the original full size images due to the size difference. Therefore, it would be helpful to have the resize module also apply to objects in addition to images.

**Comment by mcquin** [comment]
Makes sense!

@karhohs If you want to take a stab at implementing this, it would look a lot like the Resize module for images. The interpolation method would always be "nearest neighbor" because you don't want blurring of labels. You wouldn't have to worry about masks, either. :)
