### ISSUE TITLE
Enhanching neurites in a volume leads to all-black or all-white images

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2668]
When I try to use EnhanceOrSuppressFeatures on a 3D volume with linear objects in it, using Feature type- 'Speckles' works fine, but if I do 'Neurites' via 'Tubeness' I get an all-black image, and 'Neurites' via 'Line structures' I get an all-white image.  I've tried a couple of different feature sizes for each with no success.

**Comment by mcquin** [comment]
Can you try #2645 and see if that helps with "Neurites" and "Tubeness"?

**Comment by mcquin** [comment]
@bethac07 Can you verify if this is fixed in master? (from #2646)

**Comment by bethac07** [comment]
It appears unfixed, sorry.

**Comment by mcquin** [comment]
Cool! Thanks for the follow up!

**Comment by mcquin** [comment]
This no longer appears to be an issue.
