### ISSUE TITLE
Adjust telemetry language

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2673]
The term "telemetry" is not universally understood.
I'd suggest:
"Send Telemetry to the CellProfiler Team" -> "Send information to the CellProfiler team"
("Enable Telemetry", "Disable Telemetry") -> "Yes"  "No"

The sub-message is great as it is:
"Allow limited and anonymous usage statistics and " 
"exception reports to be sent to the CellProfiler " 
"team to help improve CellProfiler. "

**Comment by bethac07** [comment]
Could also add (I think it might increase compliance):
For example, focusing our attention on the most commonly used modules.

**Comment by mcquin** [comment]
#2744
