### ISSUE TITLE
Pipeline version mismatch shows funky numbering

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2674]
Running the example pipeline by clicking the welcome window in the nightly build yields the attached error. The error itself is probably fine because we won't reconcile the pipeline w the latest version until release. However, the numbering is weird, referring to 3.0 as 300. Could lead to some confused Forum posts from people claiming to be using CP300!

![warning](https://cloud.githubusercontent.com/assets/1213811/24565201/3091971c-1622-11e7-9388-696cd8fec707.jpg)

**Comment by mcquin** [comment]
Yes! We should change the display to `3.0.0`.
