### ISSUE TITLE
Error loading pipeline file

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2675]
On the nightly downloaded today on the Mac, I got the attached message upon startup of CP. I don't think I did anything to attempt to load a pipeline so I'm not sure what triggers it
![untitled2](https://cloud.githubusercontent.com/assets/1213811/24565264/8c1684e4-1622-11e7-8963-9f5c3a103157.jpg)
.

**Comment by AnneCarpenter** [comment]
I can reproduce with nightly downloaded right now. It says "sn_0_3613554." this time. 
Is the nightly actually recent? If not, then I should re-try with an actual recent build.

**Comment by AnneCarpenter** [comment]
Turns out the nightlies are indeed outdated. Someone LMK when it's available again.

**Comment by 0x00b1** [comment]
Fixed. @AnneCarpenter Would you mind verifying with the latest nightly?

**Comment by AnneCarpenter** [comment]
Sure, I grabbed from here, hope this is accurate: https://dpvpof9ygr7ad.cloudfront.net/CellProfiler-nightly.dmg

No Ghostbusters (yay), still has unidentified developer warning, but THIS ERROR IS GONE!!  Ran the example pipeline just fine w no errors or weirdnesses  :excited kermit emoji:

**Comment by 0x00b1** [comment]
Thanks, @AnneCarpenter!
