### ISSUE TITLE
Changing scaling on OverlayOutlines doesn't work if it's an RGB image and you've messed with the channels

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2676]
From [this](http://forum.cellprofiler.org/t/potential-bug-in-overlay-outlines-cp2-2-0/4534); if you're using OverlayOutlines to overlay onto a multichannel image and are examining the output in the display window and you turn some of the channels off, the rescaling functionality stops working when you click it, the only way you can get changes in the scaling to take effect is by turning a channel on or off.  Original forum user was on Mac, I can verify on PC, both in 2.2.0.

**Comment by AetherUnbound** [comment]
@bethac07 any chance you can provide a set of images/pipeline for this?

**Comment by bethac07** [comment]
Seems to be fixed in 3.0.  Closing!
