### ISSUE TITLE
MeasureCorrelation: ValueError: zero-size array

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2680]
MeasureCorrelation apparently doesn't like zero-sized objects.

Running the attached pipeline with the attached images/objects errors with:
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2826, in do_step
  File "cellprofiler\pipeline.pyc", line 2067, in run_module
  File "cellprofiler\modules\measurecorrelation.pyc", line 229, in run
  File "cellprofiler\modules\measurecorrelation.pyc", line 540, in run_image_pair_objects
  File "scipy\ndimage\measurements.pyc", line 581, in sum
  File "scipy\ndimage\measurements.pyc", line 500, in _stats
  File "numpy\core\_methods.pyc", line 29, in _amin
ValueError: zero-size array to reduction operation minimum which has no identity
```
Interesting, I tried to re-create this with the welcome screen pipeline modified to created zero-sized objects, and it worked fine. So there may be something subtle I'm missing.

[issue.zip](https://github.com/CellProfiler/CellProfiler/files/894322/issue.zip)

**Comment by braymp** [comment]
Interestingly, a prior MeasureObjectIntensity module in the original pipeline had this msg (but no error)
```
Incompatable objects: Nuclei has 2 objects and Cytoplasm has 1 objects
```
So there might be some upstream weirdness as well...

**Comment by apahl** [comment]
I also get this error in a batch job on a cluster in image # 3305 of 3456.  
Do you need more information for fixing this?

Kind regards,  
Axel

**Comment by mcquin** [comment]
@apahl can you please provide a stack trace, like the one above?

**Comment by apahl** [comment]
Hi, thanks for coming back to me.

I am using the latest commit of CellProfiler from Github in an Anaconda installation.  
The error is reproducible between runs.

Stacktrace:
```
Tue May  9 00:45:57 2017: Image # 3305, module IdentifyTertiaryObjects # 7: 0.96 sec
Error detected during run of module MeasureCorrelation
Traceback (most recent call last):
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/pipeline.py", line 1763, in
 run_with_yield
    self.run_module(module, workspace)
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/pipeline.py", line 2007, in
 run_module
    module.run(workspace)
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/modules/measurecorrelation.
py", line 228, in run
    object_name)
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/modules/measurecorrelation.
py", line 622, in run_image_pair_objects
    RWC1 = np.array(scind.sum(fi_thresh * weight_thresh, labels[combined_thresh], lrange)) / np.array(
  File "/host_obscured/home/a/apahl/conda-envs/cellprof/lib/python2.7/site-packages/scipy/ndimage/me
asurements.py", line 584, in sum
    count, sum = _stats(input, labels, index)
  File "/host_obscured/home/a/apahl/conda-envs/cellprof/lib/python2.7/site-packages/scipy/ndimage/me
asurements.py", line 502, in _stats
    labels.min() < 0 or labels.max() > labels.size):
  File "/host_obscured/home/a/apahl/conda-envs/cellprof/lib/python2.7/site-packages/numpy/core/_meth
ods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
Tue May  9 00:45:58 2017: Image # 3305, module MeasureCorrelation # 8: 28.66 sec
HDF5Dict.flush(): /ptmp/allg/apahl/cp/tmp/CpmeasurementsYkBVBU.hdf5, temporary=True
HDF5Dict.__del__(): /ptmp/allg/apahl/cp/tmp/CpmeasurementsYkBVBU.hdf5, temporary=True
HDF5Dict.__del__(): /ptmp/allg/apahl/cp/tmp/CpmeasurementskSwHN0.hdf5, temporary=True
Closing reader <bioformats.formatreader.ImageReader object at 0x2ab73c6c5550>
Closing reader <bioformats.formatreader.ImageReader object at 0x2ab73e392250>
Closing reader <bioformats.formatreader.ImageReader object at 0x2ab73e392d10>
Closing reader <bioformats.formatreader.ImageReader object at 0x2ab733d6e890>
Closing reader <bioformats.formatreader.ImageReader object at 0x2ab730e87fd0>
```

**Comment by apahl** [comment]
Hi, is there something else I contribute for resolving this? Do you need the cppipe file?

The images themselves look fine to me and do at least not seem to be corrupted.


Kind regards,  
Axel

**Comment by mcquin** [comment]
A pipeline file and an image which causes this error would be very helpful!

**Comment by braymp** [comment]
@mcquin: Please see the attachment to my original post.

**Comment by mcquin** [comment]
@braymp I see! I interpreted those files as being the zeroed out fly pipeline that didn't trigger the error. My mistake!

**Comment by apahl** [comment]
Have to rerun my pipeline to see which image triggered the error.  
I will attach the files, then.

**Comment by apahl** [comment]
Please find attached now the images that cause the error as well as the processing pipeline. The images are from site 2 of well P08 on a 384 plate and appear to be quite empty (no cells left).

[pipeline_data.zip](https://github.com/CellProfiler/CellProfiler/files/1003447/pipeline_data.zip)

Many thanks for your help!

Kind regards,  
Axel

**Comment by braymp** [comment]
@apahl: You will also need to attach the illumination correction images for this pipeline to run:
* illumHoechstcorrect.mat
* illumERcorrect.mat
* illumSytocorrect.mat
* illumPh_golgicorrect.mat
* illumMitocorrect.mat

**Comment by mcquin** [comment]
@apahl I was able to run your pipeline by omitting the illumination correction step, but I did not get any errors.

**Comment by braymp** [comment]
@mcquin: Not having the illum correction might change the intensities and/or segmentation, so you may not be actually reproducing the error without them.

**Comment by apahl** [comment]
Yes, sorry, here they are:

[correction.zip](https://github.com/CellProfiler/CellProfiler/files/1007785/correction.zip)

**Comment by mcquin** [comment]
OK. I think I see the new problem. I'm going to file a second issue.

**Comment by apahl** [comment]
Great, thanks.

**Comment by mcquin** [comment]
@apahl https://github.com/CellProfiler/CellProfiler/issues/2764
