### ISSUE TITLE
Install error with CentOS 6.8, Python 3.6.0, wxPython-Phoenix 3.0.3

### ISSUE THREAD

**Issue by comrade1809** [CellProfiler/CellProfiler#2681]
I've done my best to get all the pre-requisites installed and was following the CentOS instructions on installing Cellprofiler from the main branch.

The result is the following snip-it. If you want, I can run pip3 -vvv install for more output.

```
[root@pyrite CellProfiler]# pip3 install --editable .
Obtaining file:///tmp/cell/CellProfiler
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/cell/CellProfiler/setup.py", line 279
        raise distutils.errors.DistutilsFileError, \
                                                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/cell/CellProfiler/
```

Thank you in advance.

**Comment by mcquin** [comment]
I believe the `raise Error, message` syntax is not supported in Python 3. CellProfiler is closing in on Python 3 support, but isn't there yet. You can:

A) Use Python 2.
B) Change the line to the format `raise Error(message)`. You may encounter other issues based on your version of Python.

**Comment by comrade1809** [comment]
That's unfortunate. I'll do some experimenting with replacing the comma with parenthesis. There isn't an ETA for Python 3 support, is there?

**Comment by 0x00b1** [comment]
I’d bet on Python 3 support landing in 2017/2018. And it isn’t too bad from a CellProfiler perspective. The major stumbling block is wxPython. We’ll need to upgrade wxPython to wxPython-Phoenix before Python 3 support can be released.

**Comment by comrade1809** [comment]
I was able to successfully install wxPython-Phoenix on CentOS 6.8 server after a bit of troubleshooting. Our team that uses CellProfiler (currently on Python 2.7.6) was hoping that we can finally move away from Python 2 to Python 3.
