### ISSUE TITLE
Module request: OverlayObjects

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2683]
Create a module for semi-transparent overlay of segmentations on grayscale images or volumes.

**Comment by braymp** [comment]
Will this supercede OverlayOutlines?

**Comment by mcquin** [comment]
@braymp No, it will be complementary to OverlayOutlines.

**Comment by AnneCarpenter** [comment]
Ah, I misunderstood too - Mark, it's overlaying pretty, transparent colors onto each object.
