### ISSUE TITLE
Error when installing CellProfiler on Linux 

### ISSUE THREAD

**Issue by lguerard** [CellProfiler/CellProfiler#2692]
Hi,

I just tried installing CellProfiler following this [link](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-(Ubuntu-16.04-LTS)) but I run into a problem everytime.

It says  "Failed building wheel for centrosome" and then some gcc error.

Any ideas ?

EDIT : sorry clicked post too fast.

**Comment by 0x00b1** [comment]
What was the error?

**Comment by lguerard** [comment]
`Command "/home/laurent/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7oOnkJ/centrosome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XRX2PG-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7oOnkJ/centrosome/
`

**Comment by 0x00b1** [comment]
What are you trying to do?

**Comment by lguerard** [comment]
I'm just trying to install CellProfiler following the mentioned instructions. But I can't seem to install it because of what seems to be an error when installing centrosome.

**Comment by mcquin** [comment]
Which command are you running, that it fails on?

**Comment by 0x00b1** [comment]
@lguerard Which step of the instructions throws this error?

**Comment by lguerard** [comment]
I found two tutorials on how to install CellProfiler on Linux. 
The first one asks for a « pip install centrosome » which gives me this error.
The second one, the one linked above, gives me the error when doing « pip install --user –editable » 



De : Allen Goodman
Envoyé le :mardi 11 avril 2017 18:16
À : CellProfiler/CellProfiler
Cc : lguerard; Mention
Objet :Re: [CellProfiler/CellProfiler] Error when installing CellProfiler onLinux (#2692)

@lguerard Which step of the instructions throws this error?

**Comment by lguerard** [comment]
Hi again,

Here is the error(s) I get from trying to install CellProfiler. Hope that helps :)

[CellProfiler.txt](https://github.com/CellProfiler/CellProfiler/files/916364/CellProfiler.txt)

**Comment by lguerard** [comment]
Ok I figured it out, some "build-essentials" packages were not installed..

**Comment by mcquin** [comment]
Glad you figured it out! `apt-get build-essentials` would have been my suggestion, too. :)
