### ISSUE TITLE
Module notes scroll bar is not enabled

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2706]
A minor UI thing: when using the module notes in 2.1.1, the height of the text box would expand to the amount of text entered.

In 2.2.0, this not longer seems to be the case: the height of the notes is fixed regardless of how much text is there. The user would have to use the arrow buttons at the right of the notes to scroll up/down to see everything, and these buttons appear grayed out/disabled even when they're not.

That means a collaborator could miss one of my wonderful nuggets of information, which would be sad.

**Comment by mcquin** [comment]
Marking this as a bug. The scroll bar should be enabled when the text is longer than the text box.

**Comment by DavidStirling** [comment]
Looks like this was fixed in CP3.
