### ISSUE TITLE
Remove ConvertObjectsToImage module from CellProfiler

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2709]
A recent issue, #2704, prompted a discussion about manipulating label matrices with image processing methods and then converting them back to objects. @mcquin noted this would be unwise to implement and the manipulation of label matrices could have unpredictable results if not done carefully. To make CellProfiler more predictable I suggest we remove the ConvertObjectsToImage module and relegate object manipulation to object specific modules like those discussed in issue #2140. The most common use case for ConvertObjectsToImage is as a precursor to the Save module that will write a label matrix to disk. To elminate the need for ConvertObjectsToImage, the Save module could either handle objects and images through a decision tree or a SaveObjects module could be created. My concern is that as long as the ConvertObjectsToImage exists there will remain a temptation to tweak label matrices.

**Comment by bethac07** [comment]
I have to disagree here- 
1) I've used ConvertObjectsToImage to create binaries representing where objects are (to use as masks or to sum with something else) within a single pipeline
2) ConvertObjectsToImage is also sometimes used to save objects in a multicolored "Display format" (similar to how they're displayed by IdentifyPrimaryObjects); this can be nice to have for various visualization purposes downstream

2) I think could be dealt with by asking Save if you want it to save your Objects as a traditional label matrix or as a multicolored display (just FYI, you already can save Object label matrices in SaveImages, you needn't go through a ConvertObjectsToImage step); 1) could not and IMO is behavior that is valuable and common enough to be worth keeping.

**Comment by karhohs** [comment]
@bethac07 Thanks for sharing these use cases and I feel like I am in agreement with you for the most part. 

Ideally, there would be object specific modules to help in both cases you present. WRT to **1** if we had a MergeObjects module, then adding binary images wouldn't be necessary. WRT to **2** I think this could be solved with an OverlayObjects module that would be similar to OverlayOutlines, but have the nice color-mapping you refer to.

Removing ConvertObjectsToImage I think would ultimately lead to shorter and more clear pipelines. I think this would be worth the cost of creating or modifying a handful of object specific modules.

Also, is Save going to replace SaveImages or vice versa?

**Comment by bethac07** [comment]
There are other reasons you might want to make an object binary- creating an object binary that you're going to skeletonize for use in MeasureNeurons, for example.  

I agree the vast majority of pipelines would be shorter/clearer if we can find ways to roll the use cases for this into other modules; I'm just not sure how easy it's going to be to round up all the use cases.

**Comment by 0x00b1** [comment]
@mcquin Want to make a call?

**Comment by braymp** [comment]
Request from the peanut gallery: Don't remove it.

**Comment by mcquin** [comment]
We're keeping it. SaveImages now requires ConvertObjectsToImage to save objects.
