### ISSUE TITLE
Indicate 3D compatible modules in GUI.

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2710]
Perhaps an error could appear next to the module when "Process as 3D" is true and the module does not support 3D processing.

**Comment by AnneCarpenter** [comment]
I've a question about this one: are we sure it isn't unheard of to choose "Process as 3D" and then do something within the pipeline that is 2D? I'm pretty sure not (even if you max project within the pipeline, you wouldn't be able to do anything with the 2D result), maybe @braymp or @bethac07 can confirm/deny.

**Comment by braymp** [comment]
I can't confirm since I have yet to try out the 3D functionality myself. But to @AnneCarpenter's point, are there cases where there's a many-to-one correspondence? E.g., a loading a 2-D mask then applying it to all slices in a stack? Or would you have to create 3-D stack for which all slices are the same 2-D mask image?

**Comment by karhohs** [comment]
I don't think there are any modules that convert a 3D image into a 2D image in-pipeline. In the max-projection case, it would require two pipelines to first calculate the max-projection and then another to process the max-projection.

So far the case I've seen that is most similar to @AnneCarpenter 's question is plane-wise morphological operations or filters. When the structuring elements of these operations are 2D, then they can be applied to the 3D image plane-wise.

**Comment by bethac07** [comment]
I've been trying and failing to come up with a use case that would require a "forbidden" operation on a 2D image (like CorrectIlluminationApply)  and also computation of something on a volume.  I'm sure if we don't support this, someone will come up with one ( :wink: ), but I think this is likely to be rare.

**Comment by 0x00b1** [comment]
Hi, just to be clear, this issue is about validating whether a module supports volumetric processing. If somebody can think of an actual issue, please file it separately.
