### ISSUE TITLE
Design UI to designate and change location in pipeline while in test mode

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2712]
See #2711, #2531, #2032

**Comment by bethac07** [comment]
Previously this was a slider- highlighting has been mentioned as an option to designate location, though if we go with that I think we need a bolder highlight than we currently have (the one now is quite subtle).  Maybe a right-click->"Jump to this module" to change location?

**Comment by braymp** [comment]
This [page](https://www.nature.com/articles/ncomms12474) has some suggestions; the slider is one way to indicate location, but there other possibilities listed.

The slider (plus the little cross-bar) nicely showed and permitted a number of functions in a simple graphic; it's gonna be hard to replace with something simpler, I think.

On the other hand, the green arrow is more superflous; if real-estate is an issue, that could do away.

**Comment by 0x00b1** [comment]
I’m going to close this until someone has a concrete idea or, even better, a functional implementation. We’re trying to avoid having ambiguous discussions on GitHub. Maybe someone should create a thread on the CellProfiler forum?

**Comment by bethac07** [comment]
http://forum.cellprofiler.org/t/poll-testmode-interface-options/4676
