### ISSUE TITLE
FilterObjects throws error in 3D

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2719]
I'm trying to using *FilterObjects* and a set of resized objects created by the *Watershed*  and *ResizeObjects* modules. The filtering criteria is a minimum based on the *MeasureObjectSizeShape* *Area* measurement. The original image size is 256x256x60 and the resize is a factor 2; these numbers seem relevant to the error.

Here is the error from the command prompt/terminal:

`C:\Program Files\Miniconda2\envs\cellprofiler\lib\site-packages\skimage\segmentation\boundaries.py:230: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 128 but corresponding boolean dimension is 256`

Here is the error from the dialog box:

![image](https://cloud.githubusercontent.com/assets/156232/25347064/a81ccf68-28e7-11e7-9643-b15868483e15.png)

In case my pipeline is weirdly configured I've attached it here:

[3d_monolayer.cppipe.txt](https://github.com/CellProfiler/CellProfiler/files/952409/3d_monolayer.cppipe.txt)

**Comment by mcquin** [comment]
Closed #2720
