### ISSUE TITLE
Inconsistent handling of commandline option --get-batch-commands

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#2725]
Dear all,

I am referring to the issue raised by Tischi in this  forum thread:
http://forum.cellprofiler.org/t/simple-batch-file-list/3338/5

I looked into the Cellprofiler sources and found a few issues in `__main__.py`

There are a few issues that I see:

First, with some command line arguments it would make sense to exit once they are processed and not to run a pipeline. In one example, one could exit after generating the batch commands. currently line 82, following 
```
 if options.batch_commands_file is not None:
        get_batch_commands(options.batch_commands_file)
``` 
 I don't see a use case where one would want  process a pipeline when generating a list of batch commands. I think a similar argument could be made for `print_groups`.

Second, `get_batch_commands(filename)` only works for grouped images.
When the images are grouped, the code block following `if m.has_feature(cellprofiler.measurement.IMAGE, cellprofiler.measurement.GROUP_NUMBER):` (currently line 552) is executed and the function returns at the end of the code block.
This `if` clause doesn't have an `else` clause, but as the above code block returns the remaining code of the function is a de-facto `else` clause.  In this remaining code, there is a call to `get_groupings` which returns the grouping `ImageNumber`.

```
(Pdb) m.get_grouping_tags()
['ImageNumber']
(Pdb) m.get_groupings(['ImageNumber'])
[({'ImageNumber': u'1'}, [1]), ({'ImageNumber': u'2'}, [2]), ({'ImageNumber': u\
'3'}, [3]), ({'ImageNumber': u'4'}, [4]), ({'ImageNumber': u'5'}, [5])]
```

I assume that `ImageNumber` is an internally assigned grouping.
Consequently, the batch commands that are created look like this
```

CellProfiler -c -r -p Batch_data.h5 -g ImageNumber=1
CellProfiler -c -r -p Batch_data.h5 -g ImageNumber=2
CellProfiler -c -r -p Batch_data.h5 -g ImageNumber=3
CellProfiler -c -r -p Batch_data.h5 -g ImageNumber=4
CellProfiler -c -r -p Batch_data.h5 -g ImageNumber=5
```

However, CellProfiler doesn't recognize this internally assinged grouping tag `ImageNumber` and creates the following error:

```
$ ./clustercp.sh -c -r  -p Batch_data.h5 -g ImageNumber=1
Times reported are CPU times for each module, not wall-clock time
Traceback (most recent call last):
  File "/g/almfscreen/ALMFCellprofiler/CellProfiler/CellProfiler.py", line 4, in <modu\
le>
    cellprofiler.__main__.main()
  File "/g/almfscreen/ALMFCellprofiler/CellProfiler/cellprofiler/__main__.py", line 15\
5, in main
    run_pipeline_headless(options, args)
  File "/g/almfscreen/ALMFCellprofiler/CellProfiler/cellprofiler/__main__.py", line 70\
8, in run_pipeline_headless
    initial_measurements=initial_measurements
  File "/g/almfscreen/ALMFCellprofiler/CellProfiler/cellprofiler/pipeline.py", line 15\
63, in run
    initial_measurements=measurements):
  File "/g/almfscreen/ALMFCellprofiler/CellProfiler/cellprofiler/pipeline.py", line 16\
81, in run_with_yield
    for group_number, group_index, image_number, closure in __group:
  File "/g/almfscreen/ALMFCellprofiler/CellProfiler/cellprofiler/pipeline.py", line 15\
73, in group
    raise ValueError("The grouping keys specified on the command line (%s) must be the\
 same as those defined by the modules in the pipeline (%s)" % (", ".join(grouping.keys\
()), ", ".join(keys)))
ValueError: The grouping keys specified on the command line (ImageNumber) must be the \
same as those defined by the modules in the pipeline ()
```

I envisage an implementation in which batch commands are simply created based on image number,
e.g. with the `--first-image-set` and `--last-image-set` options.

**Comment by braymp** [comment]
> I envisage an implementation in which batch commands are simply created based on image number,
> e.g. with the `--first-image-set` and `--last-image-set` options.

I agree with this; it's come up as a source of consternation occasionally.

**Comment by VolkerH** [comment]
Just to avoid confusion I should be more specific 

> I envisage an implementation in which batch commands are simply created based on image number, e.g. with the `--first-image-set and `--last-image-set` options

... when there is no user-specified grouping. I guess the grouping is somehow necessary when one does tracking, such that the necessary prior measurements are available within each separate batch job.

**Comment by mcquin** [comment]
Related forum post: http://forum.cellprofiler.org/t/simple-batch-file-list/3338/6

> Hello,
>
> We are also experimenting with the --get-batch-commands switch and ran into the same "grouping error".
>
> If we produce an Batch_data.h5 file without grouping the printed commands are like this:
>
> `CellProfiler -c -r -p /.../Batch_data.h5 -g ImageNumber=69`
>
>Running this command raises the error that the grouping keys on the command line do not match the grouping keys defined in the module.
>
>If we replace the command by the one below, it works just fine:
>
>`CellProfiler -c -r -p /.../Batch_data.h5 -f 69 -l 69`
>
>Could the code behind --get-batch-commands get changed to do this automatically?
