### ISSUE TITLE
Morph: "Fill small holes" doesn't seem to work

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2730]
To reproduce:
* Load the welcome screen pipeline
* Add ConvertObjectToImage after IdentifyTeritiary, and convert the Cytoplasm object to binary
* Add Morph, with the binary image as input, operation as <code>Fill small holes</code>, set <code>Maximum hole area</code> to 100 (which, judging from the IdentifyTeritiary display, should be sufficient to fill in everything

Running the Morph module produces no change in the binary image.

**Comment by mcquin** [comment]
Hey @braymp ! Give RemoveHoles a try. :)

**Comment by braymp** [comment]
When the cluster version upgrades from 2.2.0, I will. :smile: 
For the time being, my workaround using IDPrim
* manual cutoff = 0.5
* declumping = None
* hole-filling = After both thresholding and declumping

Then use ConvertObjectsToImage with the output as Binary
