### ISSUE TITLE
Create a tests/data directory that stores resources used by CellProfiler tests

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2736]
We have a number of resources like CellProfiler pipelines and images that are inlined in CellProfiler test modules. They are extremely difficult to manage and modify. They also introduce a lot of duplication. It’d be nice if we kept these resources as files on disk. It’d also be a place to store resources that are useful for integration testing like @braymp’s “MOTHER OF ALL PIPELINES.”

**Comment by 0x00b1** [comment]
This issue is a lot of work (enormous amount), but it’s “easy” from a technical perspective.

**Comment by bethac07** [comment]
We did this already!
