### ISSUE TITLE
regular expression text field in "Metadata" loses focus while typing

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#2738]
The "Regular Expression" text field in the Metadata module loses focus while I am typing in the current master branch. Cellprofiler is run in a conda environment installed as outlined on the wiki under "conda install".

This behaviour is slightly different depending on whether this is running on Mac OS X Sierra or on Linux (Centos 7). On the Mac, the text field simply loses focus while I'm typing in it, on Linux it completely disappears. Not sure whether this is a bug in wxwidgets or in CP.

**Comment by karhohs** [comment]
I have observed this bug, too, on Windows.

If focus is lost, I have found that opening the regex window through the magnifying-glass provides a reliable text-box that can be edited.

**Comment by mcquin** [comment]
This may be resolved by https://github.com/CellProfiler/CellProfiler/issues/3104. @karhohs can you please verify?

**Comment by bethac07** [comment]
This isn't actually fully fixed, it just gives it longer before it loses focus.  I'll look to see if we can push the fix in #3104 one step further.

**Comment by AetherUnbound** [comment]
@bethac07 is it on Linux, Windows and Mac?
