### ISSUE TITLE
Cellprofiler freezes after dragging images into "Image" drop zone on OS X Sierra.

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#2739]
On the current master, when I drag images or a folder into the image drop zone, the status field at the bottom says something about adding images but remains at 0%. The cursor shows a watch symbol to indicate CellProfiler is busy but I can still click some button/checkboxes on the UI. 
No traceback or console output that would indicate an error.

I do not observe this behaviour on a Linux host running the same Cellprofiler sources.
Might be a wxwidgets error ?

**Comment by 0x00b1** [comment]
It sounds like it could be a wxPython issue. Do you know what version you installed?

**Comment by VolkerH** [comment]
```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import wx
>>> wx.__version__
'3.0.0.0'
```

**Comment by karhohs** [comment]
There is a good chance this is the conda version of wxpython causing trouble. Please consider using this [alternative conda package](https://anaconda.org/BjornFJohansson/wxpython), or using this [Mac-recommended](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29) method to run CellProfiler from source.

**Comment by VolkerH** [comment]
@karhohs, thanks ... the issue on the Mac is fixed with the alternative wxpython conda package. 
I also tested wether this solves #2738 as well (as it might also be wx related), but unfortunately not.
