### ISSUE TITLE
OverlayObjects module, colors do not match the corresponding label matrix in 3d

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2751]
The same 3d object will have have multiple colors in the final overlay when it should only have a single color. The colors switch along the z-axis, i.e. the color is consistent within a slice, but differs between slices.

**Comment by mcquin** [comment]
Does this happen between slices when the number of objects changes?

**Comment by karhohs** [comment]
Yes, this happens.

**Comment by mcquin** [comment]
Resolved #2855
