### ISSUE TITLE
TopHatTransform operation is not saved into the pipeline

### ISSUE THREAD

**Issue by cihanerkut** [CellProfiler/CellProfiler#2780]
The module TopHatTransform allows applying either white or black tophat transformations on an image. However, this option is not saved in a pipeline or a project. When the pipeline is reloaded, it defaults to black tophat.

**Comment by AnneCarpenter** [comment]
Wow! Can you post the pipeline (and images, if not too much trouble) where you see this? And which version of CP are you using?

**Comment by cihanerkut** [comment]
I cloned it from the master branch and built on my MacOS last week. I was using a CP2 pipeline, in which with a morph module I was doing tophat on images. Then I found out that tophat became a module by itself. I modified it accordingly and it worked. But the new tophat module can do black or white tophat, you can choose, whereas morph does white tophat only. The default for the new tophat module is black, but I need white. When I save it after I'm done and open it later, it defaults to black. Also when I open the .cppipe file with a text editor, there's no option under that module regarding black/white.

The module actually works if I use the GUI, load the pipeline, choose white tophat from the dropdown menu in tophat module settings and run the pipeline. But I need to run the pipeline headless, on a cluster, and black tophat as default doesn't help me.

Before I send you the pipeline, can you try it out, simply by adding the tophat transform module, changing to white tophat, saving, closing the pipeline and reloading it?
