### ISSUE TITLE
MeasureObjectIntensityDistribution: Module ignores "Calculate intensity Zernickes" = None

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2781]
To replicate:
* Load the welcome screen pipeline
* Insert the MeasureObjectIntensityDistribution module, set the input image to any of the Crop* images, the input object to any of the objects. Set "Calculate intensity Zernickes?" to None

Running the pipeline and examining the output CSVs shows that ``*_RadialDistribution_ZernikeMagnitude_*`` readouts are produced.

**Comment by bethac07** [comment]
What version of CP?  Possibly related to #2193 ?

**Comment by braymp** [comment]
Running 2.2.0 in my case; I haven't tried it on master.

**Comment by bethac07** [comment]
It should be fixed now- I've got a branch of stable that has the fix for this issue in my fork if you need it (it's what we use for making the dockers for Distributed-CellProfiler)

**Comment by braymp** [comment]
Verified; closing.
