### ISSUE TITLE
Is .cppipe + --file-list staying for 3.0?

### ISSUE THREAD

**Issue by purohit** [CellProfiler/CellProfiler#2782]
Hello, quick question. Will we still be able to use `.cppipe` pipeline files with `--file-list` for 3.0? This feature saves us a ton of bandwidth over using Batch files on a distributed cluster, and therefore money and speed in processing.

The reason I ask is because I *think* I read this feature was slated for deprecation. I may have misread, because I'm having a hard time finding that warning again. But it would be good to know for sure.

Thanks! :D

**Comment by mcquin** [comment]
Hey @purohit, we're keeping `--file-list` around. :)

**Comment by purohit** [comment]
Thanks, happy to hear it :)

Am 01.06.2017 5:44 nachm. schrieb "Claire McQuin" <notifications@github.com
