### ISSUE TITLE
Module displays fail in master with >3 channel images

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2783]
Trying to update ColorToGray to make a prettier display for >3 channel images, I found out those don't work at all in master:
```
Failed to run module ColorToGray
Traceback (most recent call last):
  File "C:\Users\bcimini\GitHub\Fork\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2906, in do_step
    module.display(workspace, fig)
  File "C:\Users\bcimini\GitHub\Fork\CellProfiler\cellprofiler\modules\colortogray.py", line 316, in display
    self.display_split(workspace, figure)
  File "C:\Users\bcimini\GitHub\Fork\CellProfiler\cellprofiler\modules\colortogray.py", line 379, in display_split
    title="Original image")
  File "C:\Users\bcimini\GitHub\Fork\CellProfiler\cellprofiler\gui\figure.py", line 216, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\bcimini\GitHub\Fork\CellProfiler\cellprofiler\gui\figure.py", line 1302, in subplot_imshow
    subplot.imshow(self.normalize_image(image, **kwargs))
  File "C:\Python27\lib\site-packages\matplotlib\__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_axes.py", line 4922, in imshow
    im.set_data(X)
  File "C:\Python27\lib\site-packages\matplotlib\image.py", line 453, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data
```

Sample image taken from [this forum post](http://forum.cellprofiler.org/t/can-you-use-cellprofiler-to-analyze-whole-tissue-samples-6-color-images/4711/5?u=bcimini)

**Comment by mcquin** [comment]
@0x00b1 I know you've been working on channel stuff recently. Is this solved in #2797 ?

**Comment by bethac07** [comment]
It does not seem to be- evidence being I checked out the `features/color-space` branch and tried and failed to display a 5 channel image.  

I think it's because this is actually not ColorToGray specific, it appears to be any time you're asking [figure.py](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/figure.py#L1302) to show a >4 channel image; the call is to `imshow`, which supports greyscale and RGB(A) but nothing more than that.  So it makes sense that >4 channels would fail.  Will update the title of this.

If possible though we should handle this gracefully; it's an edge case but not a corner one (lots of experiments have 4 or 5 channels!).

**Comment by mcquin** [comment]
@bethac07 I have not been able to reproduce your result on latest master. Here's what I've tried and noticed:

1. Loading a color image in **NamesAndTypes** doesn't load all the channels properly. For example, if my input data is `(256, 256, 5)` then CellProfiler creates an image of shape `(256, 5, 3)`.

2. Artificially creating a multichannel (> 3) image via **GrayToColor** then splitting channels with **ColorToGray** yields the following error:
    
    ```
    Worker 0: Error detected during run of module ColorToGray#6
    Worker 0: Traceback (most recent call last):
    Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 1912, in run_image_set
    Worker 0:     self.run_module(module, workspace)
    Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 2022, in run_module
    Worker 0:     module.run(workspace)
    Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/modules/colortogray.py", line 391, in run
    Worker 0:     self.run_split(workspace, image)
    Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/modules/colortogray.py", line 436, in run_split
    Worker 0:     output_image = input_image[:, :, index]
    ```
    
    Indicating that CellProfiler is not storing the additional channels

3. There is no indication that the first 3 channels are being displayed. It would be nice if there was some indication of truncated data.

**Comment by mcquin** [comment]
It appears to me that **GrayToColor** never supported creating multichannel images with more than 3 channels ([exhibit A](https://github.com/CellProfiler/CellProfiler/blob/de6d02c78fee6458e568281694f77262f54da7a8/tests/modules/test_graytocolor.py#L290-L308)).

**Comment by mcquin** [comment]
> I have not been able to reproduce your result on latest master. Here's what I've tried and noticed:
> 1. Loading a color image in NamesAndTypes doesn't load all the channels properly. For example, if my input data is (256, 256, 5) then CellProfiler creates an image of shape (256, 5, 3).

Ignore me! The test data I had created did not have the proper metadata. I can load a 5-channel image and can reproduce the error in **ColorToGray**.

**Comment by bethac07** [comment]
🎊
