### ISSUE TITLE
Cellprofiler does not startup due to non-ascii characters in username (windows)

### ISSUE THREAD

**Issue by attofemto** [CellProfiler/CellProfiler#2788]
Refering to the bug mentioned in your forum thread:

http://forum.cellprofiler.org/t/cellprofiler-2-1-0-does-not-startup/2055

Could you please fix the issue with the non-starting due to non-ascii characters in username of windows.

Bug observed with Cellprofiler 2.2.0, Java JRE 8 update 131

Thx

**Comment by attofemto** [comment]
The error output in my case is:

```
Traceback (most recent call last):
  File "CellProfiler.py", line 4, in <module>
  File "cellprofiler\__main__.pyc", line 175, in main

  File "cellprofiler\utilities\cpjvm.pyc", line 3, in <module>

  File "javabridge\__init__.pyc", line 28, in <module>
    Copyright (c) 2009-2013 Broad Institute
  File "javabridge\jutil.pyc", line 137, in <module>
    the script has run, the values of these
  File "javabridge\jutil.pyc", line 123, in _find_jvm

  File "javabridge\jutil.pyc", line 83, in _find_jvm_windows
    :throws: :py:exc:`javabridge.JVMNotFoundError`
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 516: ordinal not in range(128)
```

**Comment by AetherUnbound** [comment]
This appears to be an issue with javabridge, one of CellProfiler's dependencies: https://github.com/LeeKamentsky/python-javabridge/issues/35. It should also be resolved with the most recent version of the JRE. Are you still encountering problems?

**Comment by willgdjones** [comment]
I'm also having this issue. I am using Mac OSX 10.13.1 and CellProfiler 3.1.5

**Comment by NiklasTR** [comment]
I am experiencing the same issue. Mac OSX 10.13.6 and CP 3.1.5

**Comment by DavidStirling** [comment]
Unfortunately not much can be done for the current versions. The next version of CellProfiler (and hopefully Python-JavaBridge) will be running on Python 3, which should resolve these unicode incompatibility issues.
