### ISSUE TITLE
Error when installing CellProfiler on Ubuntu

### ISSUE THREAD

**Issue by JoaoFCan** [CellProfiler/CellProfiler#2805]
HI. I'm getting an error when performing the command "pip install --user --editable ." which is the following:

> Command "python setup.py egg_info" failed with error code 1 in /home/joao/Downloads/CellProfiler/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

However, when I run "pip -V", i get this:

> pip 9.0.1 from /home/joao/.local/lib/python2.7/site-packages (python 2.7)

What have I done wrong?

I have already read some other similar errors, but none helped me.

**Comment by JoaoFCan** [comment]
Well, for some reason, there were some packages missing, live javabridge, clint, chardet, idna, urllib3, I don't know why. But I just installed Cellprofiler and it worked. Let's see if it keeps working.

**Comment by 0x00b1** [comment]
@JoaoFCan Did you run `pip install --upgrade pip`?
