### ISSUE TITLE
Measurement setting doesn't infer object name correctly.

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2814]
I following the example http://cellprofiler.org/examples/#PercentPositive. In the master branch there is an extra field that is causing an error. Please see the images below:

CP2.2.0
![image](https://user-images.githubusercontent.com/156232/28135393-041f2d64-6714-11e7-9953-8e120f165fb1.png)

master
![image](https://user-images.githubusercontent.com/156232/28135358-e638b89c-6713-11e7-89e7-5169630fd818.png)

**Comment by mcquin** [comment]
@mcquin needs to verify that saving & loading a pipeline with this module does/doesn't have this problem.

**Comment by mcquin** [comment]
This is broken in 3.0 for all modules using the Measurement setting.
