### ISSUE TITLE
A collection of IdentifyPrimaryObjects bugs

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2815]
I'm working with the ExampleYeastColonies data found at https://github.com/CellProfiler/examples

I've duplicated the IdentifyPrimaryObjects module several times to recreate the bug. Please use the pipeline in the example to test them.

Here is a summary of the bugs I've found.

1. Turning on "advanced settings" rejects all objects.
1. "advanced settings" are on and typical diameter of objects Min is <= 5 rejects all objects.
1. "advanced settings" are on, diameter Min > 5, and "Discard objects outside of diameter range" is no will reject all objects.

**Comment by 0x00b1** [comment]
Thanks, @karhohs. Would you mind opening issues for each problem? Thanks!
