### ISSUE TITLE
objects diameter <=5 rejects all objects in IdentifyPrimaryObjects

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2818]
**The bug:**
When "advanced settings" are on in IdentifyPrimaryObjects and typical diameter of objects Min is <= 5, then all objects are rejected.

**Background info:**
I'm working with the ExampleYeastColonies data found at https://github.com/CellProfiler/examples

I've duplicated the IdentifyPrimaryObjects module to recreate this bug. Please use the pipeline in the example to test it.

**Comment by mcquin** [comment]
Resolved #2821
