### ISSUE TITLE
Discarding objects based on diamter in  IdentifyPrimaryObjects rejects all objects.

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2819]
**The bug:**
When "advanced settings" are on, diameter Min > 5, and "Discard objects outside of diameter range" is "no", then CellProfiler will reject all objects.

**Background info:**
I'm working with the ExampleYeastColonies data found at https://github.com/CellProfiler/examples

I've duplicated the IdentifyPrimaryObjects module to recreate this bug. Please use the pipeline in the example to test it.

**Comment by mcquin** [comment]
Resolved #2821
