### ISSUE TITLE
Export illumination correction images as NPY arrays which can be loaded in NamesAndTypes

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2822]
When trying to save an image, using the SaveImages module, created by the CorrectIlluminationCalculate module, I observe an error that states...

`Cannot save image, because values are are not between -1 and 1`.

I am trying to save a 64-bit floating point TIFF. The documentation for the CorrectIlluminationCalculate module states that the values are intentionally calculated to be >1 (so that the corrected image is still between 0 and 1 after division).

**Comment by mcquin** [comment]
Do you think we should export illumination correction functions as NPY files? (Basically, do the Python equivalent of Matlab.)

Alternatively/in the meantime, could you rescale the illumination correction function to [0, 1] and apply the inverse rescaling factor when you reload the function?

**Comment by karhohs** [comment]
Currently, we are rescaling the image as you suggest. However, when we divide by an image between [0,1], it will inflate the resulting image, which could potentially push values >1 in the resulting image. Would this resulting image then no longer follow internal CP logic that assumes all images are between [0,1]?

**Comment by mcquin** [comment]
The error you get when saving shows the illumination correction function has values `> 1`.

It's fine for illumination correction functions to have values `> 1`, as long as you aren't performing image processing operations on them (e.g., MedianFilter).

**Comment by mcquin** [comment]
We'll add the ability to export Images as NPY files. These can be loaded as Illumination functions in NamesAndTypes.

**Comment by mcquin** [comment]
Remember to update the documentation in CorrectIlluminationCalculate with instructions on saving illumination correction functions.
