### ISSUE TITLE
Cannot save 32-bit image with SaveImages module

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2823]
Currently, the only option in the SaveImages module for a floating point image is a 64-bit format. In some cases it is useful to save floating point images in a 32-bit format.

In particular, FIJI or ImageJ cannot read 64-bit TIFFS, so having a 32-bit TIFF as an output option would make CP output more flexible in terms of compatibility with other commonly used open-source imaging software.

**Comment by mcquin** [comment]
Resolved #2824
