### ISSUE TITLE
Increase or remove maximum memory limits from preferences.  

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2826]
The CP preferences window only allows you to allot a maximum of 64GB of memory; now that systems with more than that exist in (semi-)common usage, we should increase or remove this maximum.  Relevant source code is [here](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/preferencesdlg.py#L338-L342).

**Comment by mcquin** [comment]
If we go the remove route, users can set their JVM initial and maximum heap sizes with:

```
set JAVA_OPTS="-Xms128m -Xmx256m"
```

**Comment by mcquin** [comment]
Duplicate of #1938
