### ISSUE TITLE
ExpandOrShrinkObjects module yields ValueError message

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#2830]
I got a new error message when I ran our 3D segmentation test pipeline today.  FYI, the master branch was cloned on 8-8-17.  The specific ExpandOrShrinkObjects module error was “ValueError: too many values to unpack(expected 2)”.

![image](https://user-images.githubusercontent.com/20077409/29147214-8e3465f2-7d1a-11e7-81cc-c3983e800661.png)

**Comment by mcquin** [comment]
At this time, ExpandOrShrinkObjects does not support volumes. See: https://github.com/CellProfiler/CellProfiler/issues/2672
