### ISSUE TITLE
loading plugins shows an error in CellProfiler 2.x.x

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2835]
I am loading plugins from https://github.com/CellProfiler/CellProfiler-plugins.

Here is the output recording the error:

```
Could not load activecontourmodel
Traceback (most recent call last):
  File "cellprofiler\modules\__init__.pyc", line 292, in add_module
  File "C:\Users\karhohs\Documents\plugins\activecontourmodel.py", line 9, in <module>
ImportError: No module named module
could not load these modules: activecontourmodel
Exception fetching new version information from http://cellprofiler.org/CPupdate.html: HTTP Error 404: Not Found
Version: 2016-03-02T21:08:37 1b13225 / 20160302210837
```

The error is the same for other plugins, too.

```
Could not load measureradialentropy
Traceback (most recent call last):
  File "cellprofiler\modules\__init__.pyc", line 292, in add_module
  File "C:\Program Files\CellProfiler_2_2_0\cellprofiler\modules\plugins\measureradialentropy.py", line 17, in <module>
ImportError: No module named module
could not load these modules: measureradialentropy
Exception fetching new version information from http://cellprofiler.org/CPupdate.html: HTTP Error 404: Not Found
Version: 2016-03-02T21:08:37 1b13225 / 20160302210837
```

When I run CP 3.x.x I do not see this error and the module appears in the module list gui.

**Comment by 0x00b1** [comment]
@karhohs Would you expect this to work with earlier versions? The ActiveContour module, for examples, uses the updated Module interface.

**Comment by mcquin** [comment]
We should document the minimum required CellProfiler version for CellProfiler-plugins.

@0x00b1 You know the history. Which version of CellProfiler introduced the module interface?

**Comment by bethac07** [comment]
MeasureRadialEntropy absolutely should work with 2.2, as it's what I wrote it in.

**Comment by karhohs** [comment]
I submitted this issue in response to a [forum post](http://forum.cellprofiler.org/t/problems-implementing-new-module/5027).

Should we create test files for the plugins, so that we can guarantee they'll be compatible with the latest release? re https://github.com/CellProfiler/CellProfiler-plugins/issues/17. I think this would remove ambiguity.

**Comment by mcquin** [comment]
Thanks @karhohs and @bethac07 . I'll be able to help out on this once I wrap up some other ongoing tasks.

@karhohs I think tests are a really good idea! We have a pull request in progress that will introduce Travis to the project. See: https://github.com/CellProfiler/CellProfiler-plugins/pull/8/files#diff-354f30a63fb0907d4ad57269548329e3

Once that's in place, we can backfill missing tests. :)

**Comment by 0x00b1** [comment]
It looks like an import problem. It might be resolved by ensuring `cellprofiler.module.__init__` uses absolute imports.

```Python
ImportError: No module named module
```
