### ISSUE TITLE
help.py should be updatable with Sphinx

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2840]
The main GUI help at `cellprofiler/gui/help.py` would be great if we could include in the Sphinx documentation upgrade.

**Comment by 0x00b1** [comment]
@bethac07 👍

It should be straightforward. Add the cellprofiler.gui.help to docs/source/index.rst.

**Comment by bethac07** [comment]
I did, but it's a bonkers-ly formatted mess (my guess is from all of the HTML tags that were in there).  Was there some kind of conversion you did on the module headers in the modules to try to correct that? Or was there simply not as much of that there and this'll need to be corrected manually?

**Comment by mcquin** [comment]
@bethac07 The HTML needs to be converted to reStructuredText. E.g., `USING_METADATA_TAGS_REF` becomes:

```python
USING_METADATA_TAGS_REF = """
You can insert a previously defined metadata tag by either using:

-  The insert key
-  A right mouse button click inside the control
-  In Windows, the Context menu key, which is between the Windows key
   and Ctrl key

The inserted metadata tag will appear in green. To change a previously
inserted metadata tag, navigate the cursor to just before the tag and
either:

-  Use the up and down arrows to cycle through possible values.
-  Right-click on the tag to display and select the available values.
"""
```

Here's a semi-automated tool I found online for converting HTML to reStructuredText: https://pandoc.org/try/

**Comment by bethac07** [comment]
Ok, I've used pandoc before so I can give it a try for this.  TY!

**Comment by 0x00b1** [comment]
@bethac07 I use https://dirtymarkup.com before using Pandoc. It seems to help.

**Comment by bethac07** [comment]
Sphinx gets cranky when image pipes have the same name, so we need to give images unique names- ie `|Help_BuildPipe_image0|` rather than just `|image0|`

**Comment by mcquin** [comment]
#3137
