### ISSUE TITLE
Change "Input" and "Output" to be "Select the input image" and "Name the output image"

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2866]
A few newer modules have broken this convention. 

The extra words are needed to clarify what type of information is being requested. For example "Name the output image" vs "Output" tells the user it's up to the user to pick a name from scratch (vs. thinking they are supposed to remember something they ought to type in). In other words, "Output" begs the question "What do you want to know about the output?"

I am not sure how to quickly find modules where only "Input" and "Output" are used. I sort of thought the settings label might exist in only one location that is referenced by each module, rather than in individual modules' code, but apparently that is not the case.

**Comment by bethac07** [comment]
In IdentifyPrimaryObjects, these are referred to as 'x_name' and 'y_name'; there has been nice documentation attached, but it doesn't seem to be rendering into the GUI, perhaps because it's been assigned differently than other settings in the module.  Perhaps this is true in other places as well?

**Comment by bethac07** [comment]
It seems like this is because they're inheriting this from the `module.py` class; on the one hand, this seems to me like it makes it easy to fix.  I'm submitting a PR for this, but if there's a reason I don't understand why this shouldn't be done feel free to just close it.

**Comment by bethac07** [comment]
NVM, changing anything broke lots of stuff, so I won't submit a PR because I'm clearly not doing something right, but I think this is the heart of the issue.

**Comment by bethac07** [comment]
On a per-module basis this can be solved by setting the `self.x_name.text` setting, if we think it's better to do this at the individual module level.

**Comment by mcquin** [comment]
This only affect the intermediate modules like `cellprofiler.modules.ImageProcessing`.

**Comment by mcquin** [comment]
Additionally, documentation strings should be added. E.g., 

```python
        self.x_name = cellprofiler.setting.ImageNameSubscriber(
            "Select the input image",
            doc="Select the image you want to use."
        )

        self.y_name = cellprofiler.setting.ImageNameProvider(
            "Name the output image",
            self.__class__.__name__,
            doc="Enter the name you want to call the image output by this module."
        )
```
