### ISSUE TITLE
Change module names, ensuring backwards compatibility

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2870]
1) ApplyThreshold -> Threshold (everyone agrees former is overly wordy)
2) CalculateImageOverlap -> MeasureImageOverlap (to be consistent w all other Measurement modules, which produce measurements from images or objects)
3) NoiseReduction -> ReduceNoise (to be consistent w module names being verbs)
4) GammaCorrection -> GammaCorrect (same) EDIT: Nevermind about this one, it's moving to plugins!!
5) HistogramEqualization -> EqualizeHistogram (same) EDIT: Nevermind about this one, it's moving to plugins!!
6) CropObjects -> SaveCroppedObjects (to make it clear why it's in file processing category and more accurately describe what it does)

**Comment by AnneCarpenter** [comment]
See #2223 which is ready to go, too.

**Comment by AnneCarpenter** [comment]
8. Remove objects -> RemoveObjectsBySize (It needs the space in its name removed and O capitalized, and it needs a more specific name)

**Comment by bethac07** [comment]
9. MeasureNeuron to MeasureObjectSkeleton

**Comment by mcquin** [comment]
Add compatibility support for #2697

**Comment by AnneCarpenter** [comment]
One more question, @DuaaAli : did you check the whole codebase for the old names, e.g., the Help text in other modules? I haven't found any errors, I just realized this might not be something you looked for.

**Comment by DuaaAli** [comment]
I guess yes, but sure I will double check .
