### ISSUE TITLE
Warning "8 is not one of 8-bit integer, 16-bit ..." on Mac 10.12

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2887]
When I load the example pipeline (via the welcome screen) on the latest nightly on Mac 10.12 I get this error upon hitting "Analyze images":
![untitled 4 20 45 pm](https://user-images.githubusercontent.com/1213811/29792165-91d795c4-8c0d-11e7-83db-9e1b53880baf.png)

BUT, I also notice that Save Images gives a red warning indicator in the module list (pipeline window). I'd noticed this before but when clicking the module none of the individual settings looked like it was complaining/red so hit analyze anyway. 

So I think what is going on is that there IS a bad setting - I changed SaveImages' Image bit depth to 16-bit integer and the warning goes away!

I bet @karhohs already updated the example pipeline (which will go online when we launch 3.0) to accommodate this so it's not really a problem?

Tagging @0x00b1 since I'd mentioned this problem to him.

**Comment by 0x00b1** [comment]
@AnneCarpenter Nice sleuthing! 🕵️‍♀️
