### ISSUE TITLE
Help -> About CellProfiler does nothing

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2895]
True as of commit 66421a840f96604d82442f9132247eab52b8e456

**Comment by bethac07** [comment]
In prebuilt and source on Windows 10, that is

**Comment by 0x00b1** [comment]
Verified on Windows. This appears to be a Windows-only issue.

**Comment by mcquin** [comment]
I don't even see it...

![screen shot 2017-09-03 at 2 08 33 pm](https://user-images.githubusercontent.com/4721755/30005476-6fc428f0-90b1-11e7-8daa-f5669141a37a.png)

**Comment by AnneCarpenter** [comment]
I think on Mac it might be under "CellProfiler" in the menu?

**Comment by mcquin** [comment]
Help > About was removed in the help refactor, because it appeared to do nothing. Let's open a new issue if we want this information available.

**Comment by AnneCarpenter** [comment]
I suspect what used to be there was identical to the information in the splash screen (license, authors, etc). I have no opinion as to whether that information ought to be available anywhere, TBH.
