### ISSUE TITLE
CorrectIlluminationCalculate calculates median filter incorrectly in master

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2898]
Running the attached pipeline and image in CP 2.2 vs 3.0, and compare the results of the same image smoothing with a Gaussian vs median filter:

![slide1](https://user-images.githubusercontent.com/6721515/29849255-89bc42cc-8cf3-11e7-923c-0e6410868561.JPG)
![slide2](https://user-images.githubusercontent.com/6721515/29849256-89bf43b4-8cf3-11e7-80f8-26166bdb0c9d.JPG)

Most recent thing I can find in the changes of that module was the update to use skimage in commit b72b0d443b25bb7e98f8e9d490a3695c27e8504f in [line 749](https://github.com/CellProfiler/CellProfiler/blame/master/cellprofiler/modules/correctilluminationcalculate.py#L749)

CC @karhohs, who is the one who actually found this bug this morning in checkin.

[CorrectIlluminationBug.zip](https://github.com/CellProfiler/CellProfiler/files/1262055/CorrectIlluminationBug.zip)

**Comment by braymp** [comment]
Related to https://github.com/CellProfiler/CellProfiler/issues/1713? (which I thought fixed this)

**Comment by bethac07** [comment]
Possible, but the smoothing filter size here was only 20. Whatever the
cause, it looks fine in 2.2

**Comment by AnneCarpenter** [comment]
Wow, thanks for the thorough diagnosis of this, @bethac07 - glad you rooted it out!
