### ISSUE TITLE
Display padding between elements doesn't take titles into account in 3.0

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2899]
Using today's nightly on Windows 10; I've verified it happens in other modules too (every one I've tried so far) not just CorrectIlluminationCalculate:

2.2:

![display_gauss_22](https://user-images.githubusercontent.com/6721515/29849685-63249558-8cf6-11e7-9bb7-55da742baa6c.png)

3.0:

![display_gauss_30](https://user-images.githubusercontent.com/6721515/29849686-670edb74-8cf6-11e7-9aef-ecd485f727b1.png)

**Comment by 0x00b1** [comment]
This is a nightmare. Littering the `figure` module with `matplotlib.pyplot.tight_layout()` accomplishes nothing.

**Comment by bethac07** [comment]
:( :( :(

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/pull/9082 just got merged to Matplotlib master (and will be in 2.2 which should have an RC this weekend) may be of use here.
