### ISSUE TITLE
Load an ExampleFly pipeline matching the CellProfiler version.

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#2943]
When running CellProfiler stable or beta, an example pipeline corresponding to that version should be loaded. This will prevent "Your pipeline was saved with X but you are running Y" messages. CellProfiler should grab the latest example pipeline when running from nightly or source.

We will support this feature starting with 3.0 beta release.

We can use GitHub tags in CellProfiler/examples to host versioned pipelines.

**Comment by AnneCarpenter** [comment]
Right now the code within CP says "Grab the pipeline from URL: http://URL1" (not sure what the path actually is, but you get the idea).

One option is that every time the pipeline needs updating (due to changes in CP code), the URL number is incremented within the code the new pipeline is placed online at that new URL.

**Comment by AnneCarpenter** [comment]
I just tried with the nightly build and still got the "you need to upgrade" error. Not sure if that is expected given the timing of the commits - should I try again with tomorrow's nightly?

**Comment by AnneCarpenter** [comment]
There is some suspicion I don't have a version with commits from 3 days ago, so don't worry about this til I confirm.

**Comment by mcquin** [comment]
@AnneCarpenter Nightly will more than likely always be out of date. We're only guaranteeing a compatible version with beta or stable.

**Comment by AnneCarpenter** [comment]
Good news - it works fine in a newer version I downloaded - Allen figured out that AWS was caching too aggressively so I was getting a really old version as nightly.
