### ISSUE TITLE
Remove CSV/SQL mode from ExportToDatabase

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2961]
It doesn't work well and I feel is likely not utilized much, though I don't feel so strongly about it that I can't wait for Sentry data on that.

**Comment by braymp** [comment]
Eeh, there a few times where I've found it helpful, but yes, it's rare. My main beef with this mode is that the output is almost exactly the same as ExportToSpreadsheet, but the CSVs have no headers (which is silly). 

I think a good compromise is implementing (in part) https://github.com/CellProfiler/CellProfiler/issues/697, with the changes that it should only output the SQL file and have the user use ExportToSpreadsheet to produce the CSVs.

**Comment by AnneCarpenter** [comment]
Does this option have to do with using CellProfiler Analyst conveniently?

**Comment by bethac07** [comment]
I think that's what it was designed for, but for new/non computational
people it can be a bear to figure out; I almost always push people to
SQLite instead, there's no use case I've run across yet where that didn't
work comparably or better.

In fact IIRC it was trying and failing to figure out the CSV/SQL backend
thing ~2011 that made me decide CPA wasn't worth it and I should write my
own analysis software instead! 😂

**Comment by braymp** [comment]
> In fact IIRC it was trying and failing to figure out the CSV/SQL backend
> thing ~2011 that made me decide CPA wasn't worth it and I should write my
> own analysis software instead!
LOL!

Yeah, I'm on the fence. I'm intrigued by what the Sentry data will indicate, but I wouldn't blame you so ripping it out now.

**Comment by bethac07** [comment]
Bumping this to CP4
