### ISSUE TITLE
Help > Batch processing should mention Distributed CP

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3005]
Currently one would read the documentation and think that running on a cluster is the only/best option.

@bethac07  probably will know the best way to fix this - just add a sentence at the top of the batch processing help window, then link to Distributed CP (on the wiki or wherever it is?)

And should we thus rename this help menu option from Batch Processing to "Large-scale computing", or "Large Batches of Images"? Not sure what is most comprehensible to newcomers.

The  relevant file is CellProfiler/cellprofiler/gui/help/content.py

**Comment by bethac07** [comment]
Resolved by #3019
