### ISSUE TITLE
Remove internet access requirement when loading example pipeline from Welcome screen

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3007]
Is there a good reason why we don't just package the three images + example pipeline when releasing CP? It ensures a match between version of CP and pipeline version, and works even without internet access. It would allow us to tear out a fair bit of code I'd imagine.

I'm not sure why we set it up this way: possibly because we thought it'd be nice to be able to update the example all the time... but it turns out we never make substantive changes to it anymore other than updates to version changes.

**Comment by mcquin** [comment]
I like the argument that adding the pipeline + images to the package removes the internet requirement. 

My current thinking on keeping things as they are is that it reduces duplication. We'd need to host the ExampleFly pipeline online for the website. On the other hand, we could make the website point to this repository for that pipeline.
