### ISSUE TITLE
Default Input Folder setting box has disappeared

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3026]
It's still accessible from the Preferences module but it'd be nice to have it back with the DOF where it was.

![image](https://user-images.githubusercontent.com/6721515/30076186-211b3716-9246-11e7-96e0-22ec510688c6.png)

**Comment by mcquin** [comment]
Default Input Folder setting box appears only when needed. E.g.,

![screen shot 2017-09-06 at 11 56 11 am](https://user-images.githubusercontent.com/4721755/30121756-81404c44-92fa-11e7-9130-c2e82e993219.png)
