### ISSUE TITLE
MySQL-python not loading properly in Ubuntu 16.04

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3029]
From [the forum](http://forum.cellprofiler.org/t/error-loading-coloured-czi-images/5071/6):

`
I’ve tried to install the nightly version on Ubuntu 16.04 LTS (cellprofiler 3.0.0rc2 from the git hub site). It installs fine, saying that all the requirements are already satisfied. But when I try to run it, I’m getting:
`
```
system > cellprofiler
Traceback (most recent call last):
File “/home/anja/.local/bin/cellprofiler”, line 5, in 
from pkg_resources import load_entry_point
File “/usr/lib/python2.7/dist-packages/pkg_resources/init.py”, line 2927, in 
@_call_aside
File “/usr/lib/python2.7/dist-packages/pkg_resources/init.py”, line 2913, in _call_aside
f(*args, **kwargs)
File “/usr/lib/python2.7/dist-packages/pkg_resources/init.py”, line 2940, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File “/usr/lib/python2.7/dist-packages/pkg_resources/init.py”, line 635, in _build_master
ws.require(requires)
File “/usr/lib/python2.7/dist-packages/pkg_resources/init.py”, line 943, in require
needed = self.resolve(parse_requirements(requirements))
File “/usr/lib/python2.7/dist-packages/pkg_resources/init.py”, line 829, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The ‘MySQL-python’ distribution was not found and is required by CellProfiler
```

`However, the distribution is already installed:`
```
sudo pip install mysql-python
Requirement already satisfied: mysql-python in /home/anja/.local/lib/python2.7/site-packages
```
`The installation from source worked fine for version 2.2.0. What am I missing?`

I've asked her to try pulling and running from the newest version and to keep an eye on this thread, FWIW.

**Comment by 0x00b1** [comment]
Unlike most packages, `MySQL-python` requires a number of binaries and does not make a Python Wheel available on PyPI. I would recommend trying to install mysqlclient-dev:

```sh
$ sudo apt install libmysqlclient-dev
```

**Comment by anou85** [comment]
Hi, the lib was already installed...

**Comment by AetherUnbound** [comment]
You may need to install `python-mysqldb` through apt instead: https://stackoverflow.com/a/5178698/3277713

**Comment by mcquin** [comment]
@anou85 did installing `python-mysqldb` resolve this issue?

**Comment by anou85** [comment]
@mcquin no, I dropped this version and continued with 2.2.0. A managed a few days ago to install the 3.0.0 from master, but ran into some other issues [https://github.com/CellProfiler/CellProfiler/issues/3492](#3492 )

**Comment by AetherUnbound** [comment]
@anou85 I'm going to close this issue then, but we'll continue looking into your other issue

**Comment by projectoblio** [comment]
I cannot install this no matter how many flippin versions of this package i install. If someone could provide a bash script for a fresh VPS install, where you can run "import mysql.connector", that would be great
