### ISSUE TITLE
Font resolution in CP 3.0.0rc2+

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3030]
GUI letters in new RCs are noticeably pixelated. 
For comparison: a part of Mac Finder (right) next to part of CP 3.0.0rc4 GUI (left)
<img width="1084" alt="screen shot 2017-09-05 at 3 41 16 pm" src="https://user-images.githubusercontent.com/22305129/30080497-d44aa00a-9251-11e7-8bc9-8244956f335c.png">

**Comment by AnneCarpenter** [comment]
Whoa. I compared OLD (CP 2.2.0 (rev9969f42) which has a line in this module's help) vs NEW (CP 3.0 rc5 which is accidentally labeled rc4, from Monday I believe). See the attached results on my laptop (I guess fancy Retina display?) vs. my auxiliary monitor. 

![oldvsnew_monitor](https://user-images.githubusercontent.com/1213811/30667018-2694ae04-9e24-11e7-8c1d-df6e061b5299.png)
<img width="793" alt="oldvsnew_laptop" src="https://user-images.githubusercontent.com/1213811/30667019-2697a0dc-9e24-11e7-861c-6265ba4850e6.png">

Three of the 4 are pixely... the only one that is nice is 2.2 on my laptop, so we definitely did lose something along the way. Happy to test other versions if you LMK.

**Comment by AnneCarpenter** [comment]
Confirmed that the 3.0.0 release still has this problem (looks pixely on my laptop though not so bad on my aux monitor)

**Comment by AetherUnbound** [comment]
It seems like WX may not currently support anti-aliasing for fonts: https://wxpython.org/Phoenix/docs/html/wx.FontInfo.html#wx.FontInfo.AntiAliased

**Comment by AetherUnbound** [comment]
@AnneCarpenter Okay looking at your screenshots, I'm even more confused. It seems like (for your second example) even the buttons and window title are pixelated :astonished:

**Comment by AetherUnbound** [comment]
This issue may actually still be related to #472, as it seems like the difference is only discernible on @AnneCarpenter's retina display as far as I can tell.

**Comment by AnneCarpenter** [comment]
Yes, confirmed that on the retina display on a macbook pro, even the titles are fuzzy (for 3.0.0). 

If we think that is a small fraction of users then we could just let this go? It's not life-threatening.

**Comment by mcquin** [comment]
Closing as "won't fix".
