### ISSUE TITLE
Object processing modules should not return outline images

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3035]
AFAIK, the new convention was that outline images would have to be explicitly generated in OverlayOutlines, rather than being generated by Object Processing modules.  The outline generation has been removed from IdentifyPrimaryObjects and FilterObjects, but remains in

- [x] EditObjectsManually
- [x] ExpandOrShrinkObjects
- [x] FilterObjects
- [x] IdentifyObjectsManually
- [x] IdentifySecondaryObjects
- [x] IdentifyTertiaryObjects
- [x] MaskObjects
- [x] SplitOrMergeObjects

**Comment by bethac07** [comment]
Found another- 

- [ ] NamesAndTypes

**Comment by mcquin** [comment]
- [ ] IdentifyObjectsInGrid
- [ ] IdentifyObjectsManually
- [ ] UntangleWorms
