### ISSUE TITLE
Images pulled from cellprofiler.modules._help aren't rendering properly

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3051]

**Comment by bethac07** [comment]
- [ ] _help
- [ ] ExportToDatabase
- [ ] Groups
- [ ] IdentifyPrimaryObjects
- [ ] IdentifySecondaryObjects
- [ ] Images
- [ ] MeasureObjectSizeShape
- [ ] Metadata
- [ ] NamesAndTypes
- [ ] Threshold
- [ ] TrackObjects

**Comment by mcquin** [comment]
#3052
