### ISSUE TITLE
Help windows don't obey command-W to close

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3059]
(not a terrible issue)
Upon launching if you choose Help > and any of the pages there (even the welcome screen), then command-W does not close those windows. If you open a random image, command-W works fine to close that type of window, and I think Figure windows close properly too. 

Choosing Window > Close all windows works for all the above mentioned types of windows, interestingly.

**Comment by alicelucas** [comment]
Won't fix. 
Help windows are dialog windows, they should be closed with the escape key, not command-W
