### ISSUE TITLE
Highlight the current module in TestMode

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#3062]
It would be nice to show users which module is about to run in TestMode. For example, if we paused TestMode on IdentifySecondaryObjects, the module name could be highlighted. Alternatively, an icon to the left of the pause icon could be added to indicate which module is about to run next. Another suggestion is to make the module text bold.

<img width="1072" alt="screen shot 2017-09-07 at 11 54 13 am" src="https://user-images.githubusercontent.com/4721755/30172586-4b97489e-93c3-11e7-8c55-f685a9f5ed38.png">

**Comment by bethac07** [comment]
This isn't working on my Windows machine- has it been tested on other Windows PCs?

**Comment by mcquin** [comment]
Fixed! #3087
