### ISSUE TITLE
MatchTemplate should be moved to Advanced

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#3079]

**Comment by bethac07** [comment]
55/45 for keeping it in regular rather than advanced, but not a strong feeling either way.

**Comment by mcquin** [comment]
@bethac07 It needs documentation, too.

**Comment by AnneCarpenter** [comment]
I'd say there is no harm putting in Advanced and moving it later once it is very nicely documented and we have a better feel for how it works IRL.

**Comment by 0x00b1** [comment]
I say this as someone who co-wrote (or wrote) this module, but I find MatchTemplate really difficult to use and especially difficult (or impossible) to use without relying on third-party software to create templates. While I would advocate moving to CellProfiler-plugins or the Advanced category, I will defer to the judgement of our CellProfiler users.

**Comment by 0x00b1** [comment]
I should also stress that I still think it would be useful to provide additional feature descriptor modules. Especially since MatchTemplate feels odd without complimentary or alternative modules like CreateSURFDescriptor and MatchDescriptor (or something like that).

**Comment by bethac07** [comment]
I'm convinced by Anne plus Allen's arguments.  Advanced it is :)

**Comment by AnneCarpenter** [comment]
In addition to MatchTemplate, please also move ReduceNoise to Advanced, by vote of Beth, Claire, and me.

**Comment by mcquin** [comment]
Closed #3084
