### ISSUE TITLE
Workspace viewer: Loading new pipeline doesn't clear current entries

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#3097]
(Yes, I know the WSV is MIA for 3.0. Just wanted to get this out there for when it's resurrected).

When using the workspace viewer, if a new pipeline is loaded, the old entries do not get cleared; the new entries simply get appended to them.

However, if the selected images/objects get removed and/or the selection is changed to a current entry, the old ones get cleared at that point.

**Comment by mcquin** [comment]
#2909

**Comment by DavidStirling** [comment]
I don't think WSV is coming back. :(

Feel free to re-open if this becomes a priority.
