### ISSUE TITLE
Console should be optionally viewable.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3099]
Right now it's totally suppressed, would be nice to be able to turn it back on for logging purposes.

**Comment by mcquin** [comment]
The console appears to be available on OS X:

```
wmd35-c85:~ mcquin$ /Applications/CellProfiler.app/Contents/MacOS/CellProfiler -L INFO
Progress Counter({u'Unprocessed': 3})
Starting workers on address tcp://127.0.0.1:61350
Progress Counter({u'Unprocessed': 2, u'InProcess': 1})
Worker 1: Starting job
Worker 1: Doing job: 1
Worker 1: Tue Sep 12 12:13:20 2017: Image # 1, module Images # 1: 0.00 secs
Worker 1: Tue Sep 12 12:13:20 2017: Image # 1, module Metadata # 2: 0.00 secs
Worker 1: Tue Sep 12 12:13:20 2017: Image # 1, module NamesAndTypes # 3: 1.82 secs
Worker 1: Tue Sep 12 12:13:23 2017: Image # 1, module Groups # 4: 0.00 secs
Worker 1: Tue Sep 12 12:13:23 2017: Image # 1, module Crop # 5: 0.90 secs
Worker 1: Tue Sep 12 12:13:24 2017: Image # 1, module Crop # 6: 0.01 secs
Worker 1: Tue Sep 12 12:13:25 2017: Image # 1, module Crop # 7: 0.01 secs
```

Is related to #2897 ?

**Comment by mcquin** [comment]
Okay. It would be good to get more information.

**Comment by AnneCarpenter** [comment]
@0x00b1 will comment

**Comment by 0x00b1** [comment]
Thanks, @AnneCarpenter. 😄 

@bethac07 Is this still an issue if logs are reported to Console.app on macOS and Event Viewer on Windows? If so, we could probably do both (report errors to the operating system's logging manager and stdout in a console). 

My reasoning for disabling the console window was to eliminate one of the three windows CellProfiler pops for usability (and user experience reasons). I also wanted to be mindful of App Store and Windows Store restrictions that could impact us in the future (if we want to deploy 3.0.0 or future releases) to either platform.

We should also ensure CellProfiler binaries are usable from the console (i.e. running CellProfiler from `bash` or `cmd`). This is true for Linux. It's mostly true for macOS. It is, unfortunately, untrue for Windows (for the moment). When running from a console it should print errors to that console (i.e. it should write to stdout).

**Comment by bethac07** [comment]
Closing since as of 3.0.0 release the console is still viewable.
