### ISSUE TITLE
FlagImage: Image skipping causes failure in SaveImages, ExportToDatabase

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#310]
The attached pipeline is meant to be run on the ExampleFly images. There are 3 image sets, and the last one is skipped using FlagImage:
- In SaveImages, the image saved is an illum correction function to be saved on the final cycle, which is set to be skipped. This produces the following error:
  Traceback (most recent call last):
  File "C:\Trunk\CellProfiler\cellprofiler\pipeline.py", line 1661, in post_group
    module.post_group(workspace, grouping)
  File "C:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 654, in post_group
    self.save_image(workspace)
  File "C:\Trunk\CellProfiler\cellprofiler\modules\saveimages.py", line 858, in save_image
    image = workspace.image_set.get_image(self.image_name.value)
  File "C:\Trunk\CellProfiler\cellprofiler\cpimage.py", line 549, in get_image
    image = self.get_image_provider(name).provide_image(self)
  File "C:\Trunk\CellProfiler\cellprofiler\cpimage.py", line 593, in get_image_provider
    assert len(providers)>0, "No provider of the %s image"%(name)
  AssertionError: No provider of the IllumBlue image
- In ExportToDatabase, the measurements from the last cycle are not written the db, even though measurements from that cycle exist prior to the FlagImage module.

This issue can be considered a duplicate of https://jira.broadinstitute.org/browse/IMG-905, which doesn't seem to be in GitHub.

Attachments:
http://cellprofiler.org/issues/uploaded/FG7czh/ExampleFly_FlagImageTest.cp

**Comment by braymp** [comment]
It looks like I've bitten by this again (w.r.t. SaveImages). Unless I'm totally blind, I see @LeeKamentsky committing [changes](https://github.com/CellProfiler/CellProfiler/commit/c3dc8616d8840ea86ef1d61dd316228ff6d725cc) to ```post_group``` in Tile, CorrectIlluminationCalculation and MakeProjection but not in FlagImage (?!)

**Comment by bethac07** [comment]
Copying Slack convo here for future documentation

@bethac07 12:04 PM

> So @DavidStirling  dug into #310 (with CellProfiler not saving on the last cycle, if the last cycle is Flagged by FlagImage); so it turns out SaveImages DOES actually save the output at the last cycle, IFF the image is the sort of image that's saved across cycles (ie, the output of CorrectIlluminationCalculate or Tile).  It just doesn't if the module is not one that persists across cycles (ie RescaleIntensity or ImageMath).  I'll upload a toy pipeline here to illustrate, it runs on the Welcome Pipeline images.
> Given that, what's the desired fix here @braymp  - we either need to a) always make all images persist across all cycles (seems messy), b) make FlagImage ignore skip commands on the last cycle (seems messy, but less so) or c) try to avoid using last-cycle saves on images that don't come from one of those modules (annoying for users to remember).  Do you have a preference?

@braymp  2:27 PM

> @bethac07 : thx for checking into this. i'd guess that option (b) makes the most sense. i think you might need to check for correct behavior in case all images get skipped as well (in which case, nothing from the skipped modules for all image sets gets saved/exported)

@bethac07  2:47 PM

> Cool,so it'll be a 2 part fix-
Put a user-configurable option (I think we want default to be No), for FlagImage to ignore the flag if this is the last image in a set
Make SaveImages fail more gracefully if there is no image found.
Sound good?

[310_231.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/3877529/310_231.cppipe.zip)

**Comment by bethac07** [comment]
Resolved by #3876
