### ISSUE TITLE
[Ubuntu 16.04] Regular expression box disappear and reappear

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3104]
After entering some string in regular expression box, the box disappears.

<img width="1188" alt="screen shot 2017-09-12 at 11 15 51 am" src="https://user-images.githubusercontent.com/22305129/30339319-a48b8878-97bc-11e7-9bb6-b3255cabc353.png">

If you then hit "no" and then "yes" (for question "Extract metadata?") , the box reappears again.

<img width="1188" alt="screen shot 2017-09-12 at 11 17 24 am" src="https://user-images.githubusercontent.com/22305129/30339333-b01b919c-97bc-11e7-8aab-9e044406ff8d.png">

**Comment by AetherUnbound** [comment]
I can verify this behavior. Also, switching the `Metadata source` will cause this to occur too.

**Comment by AetherUnbound** [comment]
Debugging leads me to believe the problem is in the `do_reset` function on line 2312 of `moduleview`

**Comment by AetherUnbound** [comment]
It looks like `on_focus_killed` was calling `set_selection` twice. Essentially the settings were being refreshed twice after a small delay which was triggered by changing the regex textbox. Many of the other `on_<x>` calls have checks to ensure they pass if a settings refresh is in progress, I think `on_focus_killed` was just missing it.
