### ISSUE TITLE
[Ubuntu 16.04] Inconsistent alignment of text in ExportToDatabase

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3105]
Inconsistent alignment of text in ExportToDatabase module

<img width="1184" alt="screen shot 2017-09-12 at 12 24 29 pm" src="https://user-images.githubusercontent.com/22305129/30339396-e47b8bd6-97bc-11e7-9d15-7f3e7c8f921f.png">

**Comment by AetherUnbound** [comment]
I suspect this has something to do with dividers. This module has a number of them, but they aren't showing up in the UI on Ubuntu at all.

**Comment by AetherUnbound** [comment]
This actually seems to be intended behavior of `moduleview.py`: https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/moduleview.py#L475. I'll make a PR to adjust this, but there may have been historical reasons for the right-aligned binary text @AnneCarpenter @mcquin @0x00b1

**Comment by AnneCarpenter** [comment]
We've generally had text right aligned so it's easier to tell which text goes with which text box (or other input widget).

**Comment by AetherUnbound** [comment]
Got it, so should all the other text be right aligned instead of left?

**Comment by AnneCarpenter** [comment]
I * think* so but would feel better if someone else confirmed!

**Comment by mcquin** [comment]
@AetherUnbound Right-aligning the text is consistent with the display behavior on OS X and Windows.
