### ISSUE TITLE
Update documentation about adaptive thresholding

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3111]
In threshold.py the description of adaptive thresholding is as follows:
*{TS_ADAPTIVE}:* Partitions the input image into tiles and calculate
   thresholds for each tile. For each tile, the calculated threshold is
   applied only to the pixels within that tile.

Is that really true? I had thought there is a smoothing step; this makes it sound like it's literally a different threshold from one tile to the next which seems like always a bad strategy.

**Comment by mcquin** [comment]
@AnneCarpenter There's no intermediate smoothing in computing an adaptive threshold. It's a very effective technique. See: [effective local threshold with scikit-image](http://scikit-image.org/docs/dev/auto_examples/xx_applications/plot_thresholding.html#local-thresholding).

Should we include a blurb similar to the first paragraph of that example?
> If the image background is relatively uniform, then you can use a global threshold value as presented above. However, if there is large variation in the background intensity, adaptive thresholding (a.k.a. local or dynamic thresholding) may produce better results. Note that local is much slower than global thresholding.

**Comment by AnneCarpenter** [comment]
Ohhhhh the scikit help clears it up: ok, it's working fine it's just our documentation is bad, stating that it's tiles  as opposed to neighborhoods around EACH pixel. I will fix that up shortly then.
