### ISSUE TITLE
Documentation: ResizeObjects needs an assay dev's attention

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3123]
I'm not 100% sure what it does, I guess it's ExpandOrShrink but it's only for 3D? The relationship between the two should be clarified and the documentation edited in general.

**Comment by mcquin** [comment]
It's Resize but for objects instead of images.

**Comment by AnneCarpenter** [comment]
Ohhhhhh, that never even occurred to me. Definitely needs elaboration then!

**Comment by bethac07** [comment]
Presumably resolved by #3288
