### ISSUE TITLE
[OS X, CP 3.0.0rc4] OverlayOutlines : selected color won't stick

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3135]
Changing the color of the outline won't stay in effect, always return back to default (Red, Green, etc.)

**Comment by mcquin** [comment]
@minh-doan Can you be more specific? 

Is this in the module settings? Does it change back to a default color when you load the project/pipeline?

Is this in the module display? Does it not respect the value you select?

**Comment by minh-doan** [comment]
How very weird... Close and open CP3 solves the issue. I'm actually glad you don't have one more bug though. Probably close for now?

**Comment by mcquin** [comment]
Sure. We can close it for now.
