### ISSUE TITLE
Documentation - Save Images: movie formats?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3150]
In this setting ~line 226, it says the setting is only used when saving non-movie files but then it says selecting a movie format is ok, which is a little confusing - I imagine “or movie” needs to be deleted here but wasn’t sure (note PR #3149 is awaiting merge).

       self.file_format = cellprofiler.setting.Choice(
            "Saved file format",
            [
                FF_JPEG,
                FF_NPY,
                FF_PNG,
                FF_TIFF
            ],
            value=FF_TIFF,
            doc="""\
*(Used only when saving non-movie files)*

Select the image or movie format to save the image(s)

**Comment by mcquin** [comment]
The only supported file format for movies is "tif" ([source](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/saveimages.py#L774-L775)). We should update the documentation to reflect this, and also hide the file format setting when a movie is being saved.
