### ISSUE TITLE
Documentation - SaveImages: metadata allowed?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3151]
For this chunk of code ~line 216, most similar settings have the blurbs about metadata that tell you that you can use metadata tags. Is that also true here? If so, need to paste in the proper blurbs (note PR #3149 is awaiting merge). 

        self.file_name_suffix = cellprofiler.setting.Text(
            "Text to append to the image name",
            "",
            metadata=True,
            doc="""\
*(Used only when constructing the filename from the image filename)*

Enter the text that should be appended to the filename specified above."""
        )

**Comment by mcquin** [comment]
It appears that metadata tags are supported. We should update the documentation.

<img width="1072" alt="screen shot 2017-09-14 at 4 47 07 pm" src="https://user-images.githubusercontent.com/4721755/30455033-5c95f4f2-996c-11e7-866e-bfe6bfc1f10a.png">

**Comment by AnneCarpenter** [comment]
I'm on it, will do in a few minutes.

**Comment by mcquin** [comment]
https://github.com/CellProfiler/CellProfiler/pull/3175
