### ISSUE TITLE
Documentation - Is it true Crop is the only module that can create a mask?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3152]
It says so in the help for SaveImages, here:
-  *{IF_MASK}:* Relevant only if the **Crop** module is used. The
   **Crop** module creates a mask of the pixels of interest in the
   image. Saving the mask will produce a binary image in which the
   pixels of interest are set to 1; all other pixels are set to 0.

I was wondering if other modules might create masks too, like Threshold. I don’t know whether an image must just be binary to be able to be saved as a mask here, or whether it needs to be stored explicitly as a mask by CellProfiler in order to be eligible to be saved as described here (in which case it's more plausible that Crop is the only module). But we have modules called MaskImage and MaskObjects too.

**Comment by mcquin** [comment]
> I was wondering if other modules might create masks too, like Threshold

*Threshold* produces a binary image, but it does not produce a "mask" in the sense the word is used here.

> But we have modules called MaskImage and MaskObjects too.

Yes, these modules produce masks that you can save with **SaveImages**. It's worth updating the documentation to reflect this.

**Comment by AnneCarpenter** [comment]
I'm on it.

**Comment by mcquin** [comment]
https://github.com/CellProfiler/CellProfiler/pull/3175
