### ISSUE TITLE
Documentation: MeasureObjectSizeShape - 

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3155]
Are we sure the second sentence in this description is correct? It seems that an object w a concave boundary would be <1. Also, it’s not super clear what a concave boundary is vs a convex one.

-  *Solidity:* *(2D only)* The proportion of the pixels in the convex hull that are
   also in the object, i.e., *ObjectArea/ConvexHullArea*. Equals 1 for a
   solid object (i.e., one with no holes or has a concave boundary), or
   <1 for an object with holes or possessing a convex/irregular
   boundary.

**Comment by mcquin** [comment]
@AnneCarpenter I think convex and concave are mixed up here. I found a definition of solidity as `area/convex_area` ([here](http://www.spip.imagemet.com/WebHelp6/Default.htm#PnPParameters/Measure_Shape_Parameters.htm)).

A convex shape means you can pick any two points on a boundary and the straight line between them will be entirely enclosed by the shape. A concave shape means there is some pair of points on the boundary such that the straight line cannot be drawn within the shape's boundary (it exits and re-enters the shape).

**Comment by AnneCarpenter** [comment]
Are you happy if we just delete the second sentence? People can google it.

**Comment by mcquin** [comment]
@AnneCarpenter That's fine by me!

**Comment by AnneCarpenter** [comment]
on it.

**Comment by mcquin** [comment]
Resolved #3154
