### ISSUE TITLE
Remove "Save binary image" setting in MeasureAreaImageOccupied?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3160]
In MeasureAreaImageOccupied
https://github.com/CellProfiler/CellProfiler/edit/master/cellprofiler/modules/measureimageareaoccupied.py

It seems the following option could be replaced and instead people could be guided to create an identical such image using other modules in the pipeline (I'm not the expert on which ones, but thresholding the label matrix might be a good strategy). But maybe I”m missing a common use case for this that explains why it is so handy to have this in this module?

Select *{YES}* if you would like to use a binary image later in the
pipeline, for example in **SaveImages**. The image will display the
object area that you have measured as the foreground in white and the
background in black.

**Comment by braymp** [comment]
I've never used the "Retain a binary image..." option myself. It's sort of like the "Retain outlines..." in the other modules; it probably should go away.

In fact, I've never used the "Binary image" option at all; it much more common to use the "Objects" option, IMHO.
