### ISSUE TITLE
Remove "combine object m'ments" setting in ExportToSpreadsheet?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3162]
In ExportToSpreadsheet
https://github.com/CellProfiler/CellProfiler/edit/master/cellprofiler/modules/exporttospreadsheet.py

I’m not sure why anyone would want the following option, anyone care to make a case for it?

group.append(
 "previous_file", cps.Binary(
"Combine these object measurements with those of the previous object?", False, doc="""\
*(Used only when “Export all measurements?” is set to “%(NO)s”)*

Select *"%(YES)s"* to create a file composed of measurements made on
this object and the one directly above it.
Select *"%(NO)s"* to create separate files for this and the previous
object.""" % globals()))

**Comment by bethac07** [comment]
Case:

I extracted Nuclei, Cells, and Cytoplasm objects, and I want to look at the measurements for all of them all in one spreadsheet so I can easily directly compare and do calculations between columns rather than jumping around sheet to sheet.

**Comment by bethac07** [comment]
I think it's an edge case (and does add a layer of complexity to the module, I'll be the first to admit) so I certainly won't raise a fuss about it if it went but it's a nice thing to offer people.

**Comment by AnneCarpenter** [comment]
Sounds common enough that it's worth keeping. I'm going to add that as an example in the documentation so it's more clear why it is useful.

**Comment by braymp** [comment]
Just to add my voice: **Please** do not remove this setting.

**Comment by derekthirstrup** [comment]
I also use the "combine these objects measurements with previous object" setting in many pipelines.   If possible I would like to keep the functionality.
