### ISSUE TITLE
Remove downsampling option in IdentifyPrimaryObjects?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3163]
In IdentifyPrimary
https://github.com/CellProfiler/CellProfiler/edit/master/cellprofiler/modules/identifyprimaryobjects.py

We have this setting below. What problem are we trying to solve by allowing the user to turn off downsampling? Can we make a more sophisticated calculator to make this work nicely? No downsampling if object size <10, then gradually increasing the amount of downsampling above that (but maybe this already happens this way)?

        self.low_res_maxima = cellprofiler.setting.Binary(
            'Speed up by using lower-resolution image to find local maxima?',
            True,
            doc="""\
   *(Used only when distinguishing between clumped objects)*

  Select "*{YES}*" to down-sample the image for declumping. This can be
  helpful for saving processing time on large images.

  Note that if you have entered a minimum object diameter of 10 or less,
  checking this box will have no effect."""

**Comment by mcquin** [comment]
Downsampling might erase or cause too much distortion in very small objects. Additionally, someone might not want to down sample when identifying larger objects for similar reasons (e.g., distortion), or if their images are not very large.

The downsampling factor is cleverly determined by the object size. I think it's fine to give people the power to say whether or not they want to identify objects on a down sampled image or not.
