### ISSUE TITLE
Extend FormFactor to 3D in MeasureObjectSizeShape?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3164]
It seems it would be trivial to calculate using volume and surface area. I don't know that the name "form factor" would be ideal but we already tolerate using "area" when we mean "volume" etc. Is there another reason we didn't make this metric 3D?

**Comment by mcquin** [comment]
We'd have to figure out what the equation is for 3D structures. I'm not sure it would also be `4 \pi area / perimiter^2`...

**Comment by AnneCarpenter** [comment]
I see, so it's awaiting a deeper think into what sorts of size/shape measures make sense in 3D, that's valid. I will close this but let's wait on making an issue requesting new metrics  until.... later.
