### ISSUE TITLE
Move "What do the settings mean?" help text

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3171]
IdentifyPrimary and IdentifySecondaryObjects have a help text section called "What do the settings mean?" near the beginning. It shows what the settings symbols mean. 

1) Can these be turned into a variable so it's easy to keep in sync? 
2) Can this section be placed at the very end of the intro help section so it appears nearby the actual settings?
3) Are there other modules that use these symbols that need this section added? I wasn't sure how to search.

**Comment by braymp** [comment]
Re: item 3 - I think I introduced these in just the IDPrim/Sec modules, with the intent of using them more broadly, but I don't think I got around to it.

**Comment by AnneCarpenter** [comment]
Cool - I imagine, then, it's a matter of looking for whatever unique text is used for the symbols themselves to find which modules would need this chunk of help added.

**Comment by mcquin** [comment]
This section will be removed: https://github.com/CellProfiler/CellProfiler/issues/3177#issuecomment-329808302
