### ISSUE TITLE
Documentation - use consistent order for help sections

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3177]
They certainly are not consistent at present (based on Primary vs Secondary vs Tertiary). 

Perhaps someone knows the official rules. if not, as a straw man, I think this makes sense: 
- Title, one liner, and intro help text describing the module
- Supports 2D/3D
- See also
- (module specific headings, unless they make sense elsewhere)
- What do I need as input?
- What do I get as output?
- Measurements made by this module
- Technical notes
- References
- Settings

Any suggestions are welcome!

Not sure about this section:
- What do the settings mean? 
This contains a description of the symbols used in the help (for some modules, and will be present in more soon, see #3171).  I think it should go just before the settings section of the help but not knowing how the manual is built, I’m not sure how to accomplish it.

**Comment by mcquin** [comment]
@AnneCarpenter the manual currently does not support module settings help. It's unlikely it will in the near future.

I think that blurb could have a better home in the how to build a pipeline help. There's mention of checking the settings to see what they do. That could be a good place to point out what the symbols mean.

Additionally, I think 👍  and 👎 are pretty self-explanatory.

**Comment by AnneCarpenter** [comment]
Understood about the manual not showing settings. The ordering matters for when you show the full module help in CP's GUI, which includes the settings help though. 

But I think I love the idea of removing this legend from modules altogether and putting it somewhere more introductory. 

But actually, I think I vote to remove it altogether. It would be a rare soul who wants to read about symbols out of context from where they are used, and as @mcquin  points out it's pretty self explanatory. That's my vote, just delete wherever found.

**Comment by mcquin** [comment]
Cool! I love deleting stuff :P

**Comment by AnneCarpenter** [comment]
I can do this one.

**Comment by mcquin** [comment]
@AnneCarpenter -- Your PRs removing "What do the settings mean?" have been merged. Is there anything else that needs to be done for this issue?d

**Comment by AnneCarpenter** [comment]
The original issue does remain, actually.  
I think if @bethac07 signs off on the straw man for the 'correct' ordering then @N3llz could check through modules to find any that disobey the rules and fix them.

**Comment by AnneCarpenter** [comment]
Needs @bethac07 's blessing. She is flying somewhere right now though.

**Comment by bethac07** [comment]
Consider yourself blessed ;)

**Comment by AnneCarpenter** [comment]
Added 2D/3D in the initial post.

**Comment by N3llz** [comment]
Should all of these sections have the same style heading? I've found some References sections that have the carrots under them (so they are big, bold headings) and others that have just two asterisks surrounding them. I'm wondering if this is a formatting inconsistency, or if the ones with asterisks are supposed to be within the Settings sections, and therefore do not need large headings. So, 1) are there some Refs sections that should be left as smaller sections within Settings? And 2) should all these sections be of equal value (with regard to heading formatting)?

**Comment by N3llz** [comment]
I should add, some of these References seem to be embedded within the settings somehow, and must be called by a variable or something, because they don't show when I just Ctrl+F to search for "references". So if those refs SHOULDN'T be in the settings section, then this may be a separate issue. I'm thinking that some module settings do just intentionally have some of their own references?

**Comment by AnneCarpenter** [comment]
Great catch!

Generally, if references are truly a separate section they should have ^^^ like the rest of the headings. 

However, it is true that some references sections are _within_ a setting, and those should only be bolded.

**Comment by N3llz** [comment]
Resolved by #3289
@0x00b1 OK to close this issue

**Comment by N3llz** [comment]
We're also adding a note about which modules respect masking (#2245) so this is the new ordering: 

- Title, one liner, and intro help text describing the module
- Supports 2D/3D
- This module (respects/does not respect) masks. See MaskImage and MaskObjects.
- See also
- (module specific headings, unless they make sense elsewhere)
- What do I need as input?
- What do I get as output?
- Measurements made by this module
- Technical notes
- References
- Settings

**Comment by N3llz** [comment]
"Respects masks" will also be added as a new column to the 2D / 3D table (#2245)
