### ISSUE TITLE
Documentation should be checked for typos.

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#3180]
Once the bulk of documentation changes are over, let's check the documentation for spelling errors.

You can do this in PyCharm:

1. Right-click the "cellprofiler/modules" directory in the directory tree and select "Inspect code..."
1. Click the "..." next to the "Inspection profile" to edit the profile.
1. In the menu list on the left, deselect everything except "Spelling > Typo". On the right, under "Options", select "Process literals".
1. Search for and correct any found typos.

The process can be performed on a per-file basis. We should also check the contents of:

- [x] cellprofiler/modules/*.py
- [x] cellprofiler/data/docs/*.rst (formerly cellprofiler/gui/html/content.py)
- [x] cellprofiler/gui/welcome.py

**Comment by braymp** [comment]
CalculateRatios -> CalculateMath: https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/filterobjects.py#L39

**Comment by AetherUnbound** [comment]
I've started some work on this in `issues/3180`.

**Comment by AetherUnbound** [comment]
It looks like `cellprofiler/gui/welcome.py` is good!

**Comment by mcquin** [comment]
Resolves #3436, #3437
