### ISSUE TITLE
Documentation - hole-filling behavior

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3191]
IdPrimary has an option “Fill holes in identified objects?” and this warning is provided (line 692) in the help text for the setting: 
   Please note that if an object is located within a hole and
   this option is enabled, the object will be lost when the hole is
   filled in.

IdSecondary also has an option “Fill holes in identified objects?” at line ~372 - should we add the same text?

**Comment by 0x00b1** [comment]
@AnneCarpenter Yep!
