### ISSUE TITLE
[Ubuntu 16.04] RescaleIntensity: not getting along well with DefineGrid + NameAndType + bad settings stuck

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3196]
1. When using module RescaleIntensity after **DefineGrid**, module **MaskImage** was forced to be used, otherwise throws error (even though no settings in RescaleIntensity deal with Grid) : 
`Could not find grid Grid`
<img width="270" alt="screen shot 2017-09-16 at 4 44 54 am" src="https://user-images.githubusercontent.com/22305129/30540228-3d6e4a2c-9c44-11e7-965b-0ce364bd4f0c.png">

2. Setting "Choose specific values to be reset to the full intensity range":
If use "Minimum/Maximum of **all** images", throws error:
` 'MonochromeImageProvider' object has no attribute "scale" `

<img width="367" alt="screen shot 2017-09-16 at 4 45 13 am" src="https://user-images.githubusercontent.com/22305129/30540982-4d641148-9c47-11e7-9306-602d03d72fc6.png">
Hitting "Cancel" will bring up **NameAndType** window, as if there's something to be fixed here

If use "Minimum/Maximum of **each** image", then it runs fine.

3. If error "2" happens, changing back and forth between good and bad settings doesn't clean the error, i.e. it looks like it's traumatized forever for the bad setting.
 
Have to delete the module "RescaleIntensity" >> choose the good setting immediately and proceed
Watch the demonstration (video) at: https://www.youtube.com/watch?v=GRcBWqMTCXk

**Comment by AnneCarpenter** [comment]
Can you include pipeline and images? That makes debugging easier.

**Comment by minh-doan** [comment]
Yes! Here they are.

[Objects_in_Grid_rescale.zip](https://github.com/CellProfiler/CellProfiler/files/1310671/Objects_in_Grid_rescale.zip)
