### ISSUE TITLE
Documentation - Should all modules that create objects have text about saving?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3198]
This nice blurb is in ExpandOrShrink. It seems applicable to any object processing module, should we add it as a text blob to all?

*Note on saving images:* You can pass the modified objects along to the
*Object Processing* module **ConvertObjectsToImage** to create an image.
This image can be saved with the **SaveImages** module. Additionally,
you can use the **OverlayOutlines** or **OverlayObjects** module to
overlay outlines or objects, respectively, on a base image.
The resulting image can also be saved with the **SaveImages** module.

**Comment by mcquin** [comment]
@vchernys Is taking this one on! 🎉

**Comment by mcquin** [comment]
Resolved via https://github.com/CellProfiler/CellProfiler/pull/3271
