### ISSUE TITLE
Documentation - modules missing some "Used only if X" setting descriptors

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3203]
MaskObjects (definitely)
ImageMath (I think)

**Comment by karhohs** [comment]
It appears that MaskObjects already has the "Used only if X" note for the "Keep overlapping region" option.

I looked at all the ImageMath operations and did not find a clear place to add the "Used only if X" note.

Could this issue be elaborated on?

**Comment by AnneCarpenter** [comment]
In MaskImage, I assume that "Select the masking object" is only an option if you choose objects for "Mask using a region defined by other objects or binary image?"  Same for "Select the masking image". 
I'm looking at rc4 so it's possible I'm out of date.

I looked more carefully at ImageMath. I think it's fine as is.

**Comment by karhohs** [comment]
When I compare MaskImage to MaskObjects I see where they differ. I will update MaskObjects to mirror MaskImage.

**Comment by AnneCarpenter** [comment]
Is this done?

**Comment by AetherUnbound** [comment]
@karhohs bump
