### ISSUE TITLE
Documentation - images for MeasureObjectIntensityDistribution

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3214]
This module could really use some explanatory images for how the rings/bins are scaled (or not) and for what we mean by radial slices.

**Comment by minh-doan** [comment]
I can take this. But where should I add the image? directly to the module help or to the web's version?

**Comment by mcquin** [comment]
@minh-doan Please add it to the module's help. It will automatically get pulled into the manual we publish.

**Comment by minh-doan** [comment]
Do I understand it correctly?

<img width="1408" alt="screen shot 2017-09-21 at 8 00 47 am" src="https://user-images.githubusercontent.com/22305129/30694667-fcfac9b4-9ea2-11e7-885d-9fd534328d97.png">

**Comment by AnneCarpenter** [comment]
Wow, really nice! I should say I don't know how the shapes are created in this module so I'm not the one to ask about accuracy but this looks sensible to me. 

I'd suggest changing the label for Magnitude to be "Magnitude: amount of intensity within each ring" and the other one "Phase (Zernike moment): distribution of intensity within each ring" (IIUC).

In this example the shape of the seed appears to be irrelevant, so I guess you are in "Centers" mode instead of "Edges" mode - probably you should label that fact so it's not confusing. 

In Edges mode, is it true that if it's a normal nucleus shape the shape of the rings will take after the nucleus (and not the cell border)? Or is it a compromise between the two shapes? I imagine it's the latter but I don't know; to depict this you'd need a separate drawing in Edge mode, where the nucleus has an actual shape instead of just a dot. 

We also have not explained what scaling the bins means but maybe that is ok, this is already a lot of help.

**Comment by minh-doan** [comment]
Thanks Anne !
Ah yes, this image is more like if we care about only 1 object and ignore other (secondary) objects.
I'll try to integrate other objects into this image without adding too many arrows

**Comment by AnneCarpenter** [comment]
Separate images might make sense, too. YOu needn't solve all the problems at once :)

**Comment by minh-doan** [comment]
If I understand correctly:

<img width="1440" alt="screen shot 2017-09-21 at 4 43 27 pm" src="https://user-images.githubusercontent.com/22305129/30717848-266ea204-9eec-11e7-9bec-6e68ca98be7c.png">

edge vs center
<img width="1440" alt="screen shot 2017-09-21 at 4 43 52 pm" src="https://user-images.githubusercontent.com/22305129/30717865-34158634-9eec-11e7-9f65-10a613a2f560.png">

**Comment by minh-doan** [comment]
At "scale the bin" the maximum radius is the total radius right?
E.g. if I set it to 100, with 4 bin, then each bin is 25 increment?

**Comment by AnneCarpenter** [comment]
Those fit my understanding too!  I think the only thing is that w Max Radius set to 35, 35 should label the whole distance to the edge of the cell, not the width of a single ring. Other than that things look correct to me. 

I'm hoping @karhohs can check because I think he dove into this module recently and would be able to confirm the behavior you've described is correct.
