### ISSUE TITLE
Remove ClearBorders and RemoveObjectsBySize modules

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3218]
The help for FilterObjects indicates that it works in 3D to remove objects touching the border of the image, making ClearBorders redundant. 

@mcquin says "FilterObjects will clear the image border or mask border (if not objects touch the image edge). ClearBorder just clears the image border, so it's redundant. I am in favor of removing it. There is a setting in ClearBorder for removing objects N pixels from the edge, which is interesting, but it's not hooked up to anything."

Regarding that ^^^, a workaround might be to crop the image then filter objects touching edges. So I think we are clear. 

Any other comments? I think @0x00b1 wrote this module so tagging him to see if there is a use case we are not thinking of.

**Comment by AnneCarpenter** [comment]
Confirmation that FilterObjects actually does work in 3D would be reassuring before we do this!

**Comment by mcquin** [comment]
FilterObjects got 3D support in #2694

**Comment by AnneCarpenter** [comment]
Consensus is that this module can indeed be deleted.

**Comment by AnneCarpenter** [comment]
Also, we can delete RemoveObjectsBySize. Per @mcquin , "RemoveObjectsBySize was added Nov '16, before FilterObjects. It is redundant now that FilterObjects supports 3D. We can remove it."
