### ISSUE TITLE
Move MedialAxis module to plugins

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3222]
Alternative: delete it. It's unreleased so that is allowed, but just not sure if someone sees value in keeping it as a plugin for potential future use?

**Comment by 0x00b1** [comment]
Medial axis is useful for any problem where skeletonization is needed.

**Comment by AnneCarpenter** [comment]
Only one yes vote is needed! Let's retain it in plugins then.

**Comment by bethac07** [comment]
If MeasureImageSkeleton is in Advanced (as opposed to plugins), doesn't MedialAxis need to be there too?  Otherwise MeasureImageSkeleton is useless.

**Comment by AnneCarpenter** [comment]
The bigger issue is Beth realized we use Medial Axis in real pipelines. Can we please restore it, to Advanced?

**Comment by 0x00b1** [comment]
Resolved. :)
