### ISSUE TITLE
Change Label module's name

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3223]
It's currently an Advanced module but it has functionality currently missing in CP's main modules. 

New name (draft): ConvertImageToObjects 
New category: Object processing

@mcquin: I think this is useful as a standalone module if your objects are neatly separated after thresholding. yes, this is essentially IdPrimaryObjects w/o declumping and filtering objects by size. tl;dr move to object processing? 
me: IIUC this is essentially ConvertImageToObjects? I know that name is a little silly, but if it's accurate that is probably better than Label bc the typical user never thinks about labels.
@mcquin: That would work! Also, we should make sure this module records the standard measurements for identified objects.

It is redundant with IdentifyPrimaryObjects except that module isn't 3D yet. Calling it "Convert" makes it sound appropriately much simpler than "Identify". Both modules should reference each other as "see also" 

For now (3.0 release) we can change name/category; we can make a new issue to update the m'ments made and improve documentation.

**Comment by mcquin** [comment]
Measurements are easy! I implemented a helper method which handles the basic cases. :)

**Comment by bethac07** [comment]
I know I'm a bit late to the party, but I disagree here about moving it out of advanced; it's generally superseded by IPO and/or watershed for most of its current functionality.  Or am I incorrect on that?

**Comment by AnneCarpenter** [comment]
Well, it's a good point that if it's going to be redundant someday then it doesn't deserve promotion. I am agreed w Beth. I'd still vote for the name change (though happy to hear alternatives!)

**Comment by mcquin** [comment]
> It's generally superseded by IPO and/or watershed for most of its current functionality. Or am I incorrect on that?

Threshold + ConvertImageToObjects is essentially IPO without declumping. It's tons faster than Watershed: it takes 3s to label an image of size (83, 1024, 1024), and over 4m to run watershed on the same image.

That said, I can't think of a standalone use for ConvertImageToObjects. Advanced is a good category choice.
