### ISSUE TITLE
Documentation - test mode

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3233]
It's in CellProfiler/cellprofiler/gui/help/content.py around line 540. My understanding is that test mode has changed so this help content needs checking against the current test mode.

**Comment by mcquin** [comment]
The "Run from module" feature is documented [here](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/help/content.py#L560-L565). 

We could probably add a blurb explaining that the text for the module to run next is underlined and the active module text (the one you're looking at in the GUI) is bolded.

**Comment by minh-doan** [comment]
I'll do this

**Comment by minh-doan** [comment]
Claire, with the underline and bolded text, do I understand correctly that it will replace the slider ? or there will be slider , just not at this release?

**Comment by bethac07** [comment]
Slider is gone for good. The new text settings replace the slider.

**Comment by minh-doan** [comment]
@0x00b1 can close this too, via #3293
