### ISSUE TITLE
Documentation - describe SaveCroppedObjects accurately

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3237]
I was told "this module takes objects as input and the output is to save (directly to disk) cropped images where the size and location is determined by each object's ROI and the image content is the raw image data. The help needs updating to reflect all this!  There is no actual "mask" function, contrary to the current description."

This conflicts w the current help for the module:
"SaveCroppedObjects exports each object as a binary image. Pixels corresponding to an exported object are assigned the value 255. All other pixels (i.e., background pixels and pixels corresponding to other objects) are assigned the value 0. The dimensions of each image are the same as the original image. 
The filename for an exported image is formatted as "{object name}_{label index}_{timestamp}.tiff", where object name is the name of the exported objects, label index is the integer label of the object exported in the image (starting from 1), and timestamp is the time at which the image was saved (this prevents accidentally overwriting a previously exported image). "

Someone needs to test the function of the module and clarify what it actually does!

**Comment by mcquin** [comment]
@AnneCarpenter I updated the documentation recently. The current help is correct. Here is the module's output for the nuclei from ExampleFly:

![screen shot 2017-09-19 at 5 10 36 pm](https://user-images.githubusercontent.com/4721755/30615669-a355a294-9d5d-11e7-907f-211ef16314d6.png)

**Comment by AnneCarpenter** [comment]
Agreed!! That is pretty weird, I wish I could recall who told me that and if they are thinking of a different version of this module/plugin.
