### ISSUE TITLE
Document help on saving output from Display* modules

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3258]
Can the display produced by all Display modules be saved to an image file using SaveImages? I think so but we need to test this. 

If so, add blurb reflecting this near the end of the intro help:
When run as a module, the plot is shown for display only. If you would like to save the plot, use **SaveImages** downstream in the pipeline. 

If not, say so!

Please assign @N3llz

**Comment by mcquin** [comment]
You can't save figures with SaveImages.

**Comment by AnneCarpenter** [comment]
Ah! DisplayDataOnImage can but indeed it's the only one (and you're right, it doesn't save the figure per se but at least it passes the image along the pipeline). Its documentation is correct.

So let's reopen the issue to add the following to the 4 other display modules: 
"At this time, the display produced when **DisplayX** is run as a module cannot be saved in the pipeline (e.g., by using SaveImages). The display can be saved manually by selecting the window produced by the module and clicking the Save icon in its menu bar or by choosing File > Save from CellProfiler's main menu bar."

Iv'e just opened 4 corresponding PRs for that.

**Comment by minh-doan** [comment]
I can try doing this

**Comment by AnneCarpenter** [comment]
It's done, actually.
