### ISSUE TITLE
Documentation - fix formatting of formulas in CalculateStatistics

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3276]
The formatting of the formulas needs fixing in two places (search for “1 &minus”).

**Comment by vchernys** [comment]
I can do this one

**Comment by AnneCarpenter** [comment]
I think it's done?

**Comment by vchernys** [comment]
@AnneCarpenter, it is done and I think @0x00b1 merged it a few days ago
