### ISSUE TITLE
Documentation - broken link in Tile module

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/CellProfiler#3281]
In the help documentation for the Tile Module, this link is broken:
http://graphicssoft.about.com/od/panorama/Panorama_Creation_and_Stitching_Tools.htm

**Comment by minh-doan** [comment]
I'll be checking

**Comment by minh-doan** [comment]
Follow up on [3294](https://github.com/CellProfiler/CellProfiler/pull/3294)

**Comment by AetherUnbound** [comment]
Looks like this was resolved, closing this one.
