### ISSUE TITLE
"Getting started" button is broken in 3.0rc4

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#3285]
Pressing the "Getting started" button in the "Add modules" dialog in 3.0rc4 (from source) yields the following error:
```
Traceback (most recent call last):
  File "cellprofiler\gui\addmoduleframe.py", line 198, in __on_getting_started
    from cellprofiler.gui.help import BUILDING_A_PIPELINE_HELP
ImportError: cannot import name BUILDING_A_PIPELINE_HELP
```

**Comment by AnneCarpenter** [comment]
Might be same cause as #3235

**Comment by AetherUnbound** [comment]
It looks like it loads for me but similar to what @mcquin said in #3235: reST isn't converting to HTML
