### ISSUE TITLE
Documentation - Tile, arrange settings in help nicely

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3292]
Right now, _Automatically calculate number of rows?_ (and columns) is at the end of the help, but it's a question shown towards the beginning of the GUI, so it is a little confusing when looking at the help. 

As a more general question, is there a reason that the help sections for individual settings are not automatically shown in the order they are in the GUI? It'd be awesome if that just happened magically, but if not we could have someone systematically go through and arrange them. I've noted a couple of cases that were obvious from just reading the help but we could go through them all if needed.

**Comment by bethac07** [comment]
IIRC, the order you see the settings in the help is set in one of two ways:

-If there is a help_settings list, the order in which the individual
settings are listed within it (ie self.help_settings = [self.x,
self.y,self.z])

-If help_settings has not been used, it's just a list of all of the
settings in the order they're defined in the code. This is rather random;
in at least some cases I'm reasonably certain it's historical (as modules
for new functions, the settings for them were added to the end of the
settings list).

We could fix this by always defining help_settings, but as far as I know
there's no way to do this easily or automatically.

**Comment by AnneCarpenter** [comment]
Super, very helpful. How is the order of the settings themselves determined for the GUI? I know some are conditional but they are always in sensible order. 

So it seems like it might be reasonable to refactor to ensure that help is always in the same order for the settings themselves - at least this doesn't require deep thought for each individual module (though it may be a fair bit of work to set up the system!)

But this is pretty solidly a nice-to-have. I think it's perfectly ok to just a few cases where it's confusing (like this one mentioned here) and leave the rest be.

**Comment by braymp** [comment]
There is (or was) a ``visible_settings`` definition which helps re: UI order. According to  https://github.com/CellProfiler/CellProfiler/wiki/Orientation-to-CellProfiler-code#set: 

> The Help uses the settings definition (which returns the settings in the order that they are saved/loaded) to order the help items, and the visible_settings definition to control the display order in the main GUI. If the Help items needs to be ordered in a different way than the settings, use the help_settings definition to describe the order.

**Comment by bethac07** [comment]
Yes, but I don't think all modules have visible_settings either. For those
we'd need to add something. Good point though Mark!

**Comment by mcquin** [comment]
@AnneCarpenter Automating the process of matching the visible settings with the help settings, is very difficult/nearly impossible given the use of conditionals to determine whether or not a setting is shown. I think the best path forward is to define `help_settings` in the order desired.

**Comment by AnneCarpenter** [comment]
👍  
ok, then let's just fix this particular one and not bother w the others until someone notices they are confusing.
