### ISSUE TITLE
CP 3.0.0rc1 not starting up in Mac 

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3295]
From the forum (link here: http://forum.cellprofiler.org/t/cp-3-0-0rc1-not-starting-up-in-mac/5104). I imagine the first line of defense is asking him to try a new build (rc5 or rc6? I think it could be rc1 he's getting thru the nightly link). 

puigvert1h1 
Hi,

I am really eager to see what is new in CP 3.0, but after installing the Mac version in my computer, CP 3.0 won’t start.

It appears on the dock, it jumps a couple of times and it closes again.

Any input?

Thanks!

Jordi

**Comment by bethac07** [comment]
[Resolved](http://forum.cellprofiler.org/t/cp-3-0-0rc1-not-starting-up-in-mac/5104/14?u=bcimini)
