### ISSUE TITLE
Add the manual to Help > Online Manual

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/CellProfiler#3296]
Restore [Help > Online Manual](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/help/menu.py#L21-L25). 

The manual is [linked to CloudFront](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/help/menu.py#L188-L191). Let's consider using a URL we can update so that we can updated the manual after the release.

**Comment by 0x00b1** [comment]
Something like `https://documentation.cellprofiler.org/${version_number}/`

**Comment by AnneCarpenter** [comment]
Do we want multiple copies online simultaneously?

Pro: nice for archival purposes
Con: old version of manual shows up in google searches and it might be outdated

I think I vote no, but would love to hear thoughts on this.

**Comment by mcquin** [comment]
Read The Docs supports versioned documentation: http://docs.readthedocs.io/en/latest/versions.html

**Comment by AnneCarpenter** [comment]
Interesting. It's kinda amazing that this would eliminate any hands on maintenance from us, IIUC.

If someone lands on an outdated version via Google search, I wonder how obvious it is that they are looking at the outdated version (or if there is a way to make it obvious). That'd be my only worry.

**Comment by 0x00b1** [comment]
I agree @AnneCarpenter, this is critical! I'm routinely annoyed when I encounter old versions of TensorFlow documentation, for example, when searching.

I believe RTD manages this by de-indexing non-current versions. In my experience, it works well.

**Comment by AnneCarpenter** [comment]
At least for Read the Docs itself, there is a tiny green label at the bottom left that says v:latest. Way too subtle.
I'm not saying we need flashing red/yellow banner at the top that says "This is outdated, go [here] for the newest CP manual", but still. 

So yeah, if de-indexing happens and it works, this sounds good. 

I dunno if that  means every 6 weeks when the latest stable comes out, google search rankings start from scratch again - that'd be sad.

![rtd](https://user-images.githubusercontent.com/1213811/30830320-9c7eedaa-a211-11e7-8427-7e656efb1bda.png)
