### ISSUE TITLE
Settings/help edits for NamesAndTypes

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3298]
For the 3 (x,y,z) spacing edit boxes in N&T, it might be not clear that these are are spacing specs and not coordinates or whatever else, so would be great as "Spacing in X" rather than just "X", etc.

I'm not sure if this is more complicated than it seems and requires running source, but if it's just a matter of changing the text I'm happy to do it, just assign me.

Also could someone please clarify what units are used for X, Y, Z?  The help says, "Spacing between voxels in the x-dimension." So it is not clear. My guess is that the person can use any units they want, it's more the ratio we want to specify (for example, assuming X and Y are the same units, is Z 2-fold larger than X?) IIUC, then I can modify the help to address this too. Perhaps then the setting ought to be "Relative spacing in X". 

Also, "Process as 3D" could use a question mark (might just be hidden given we have the text-getting-cut-off issue right now though).

**Comment by 0x00b1** [comment]
> Also could someone please clarify what units are used for X, Y, Z? The help says, "Spacing between voxels in the x-dimension." So it is not clear. My guess is that the person can use any units they want, it's more the ratio we want to specify (for example, assuming X and Y are the same units, is Z 2-fold larger than X?) IIUC, then I can modify the help to address this too. Perhaps then the setting ought to be "Relative spacing in X".

@AnneCarpenter It’s the ratio between the x, y, and z dimensions.
