### ISSUE TITLE
Error in imageMath module "image is missing"

### ISSUE THREAD

**Issue by cells2numbers** [CellProfiler/CellProfiler#3307]
Error: The ImageMath module throughs the error shown below when two images are subtracted although two correct Images are chosen using the drop down menu of the module (the module is marked with a red cross).

Additional notes: the drop down menu for either the first or the second image shows an empty field; when the empty field is selected and directly afterwards another image is chosen, the error disappears. 

The attached pipeline includes an example. 

CellProfiler installed from source, 3.0 RC5.

```
Error while processing ImageMath:
The  image is missing from the pipeline.

Do you want to stop processing?
```

[20170927_imageMath.cpproj.zip](https://github.com/CellProfiler/CellProfiler/files/1338708/20170927_imageMath.cpproj.zip)

**Comment by AetherUnbound** [comment]
Unfortunately the `cpproj` file you uploaded does not contain the images for this pipeline. Do you mind uploading those as well?

**Comment by DavidStirling** [comment]
I think this is already fixed, please re-open with a 3.1-compatible pipeline if you're still having problems.

**Comment by bethac07** [comment]
This still persists in 3.1.9, not sure if in master- I'm not certain it's actually ImageMath specific (though I forget which other modules I've seen it in), it crops up in a few different modules when it auto-fills the box with the alphabetically-first image (in [this forum case](https://forum.image.sc/t/imagemath-image-naming-error/35741/2), CorrBlue), not entirely certain why. Changing that box to another value (such as in that pipeline CorrGreen) and then changing back to CorrBlue permanently fixes the issue for that module.

**Comment by DavidStirling** [comment]
So on my machine loading the user's pipeline into 3.1.9 fails to populate the first image box rather than it showing CorrBlue:

![ImageMath](https://user-images.githubusercontent.com/26802537/78062280-6e200880-735c-11ea-9ce0-b244bbfbef9a.png)

I suspect this may be an issue with pipeline saving/auto-populating these fields.
