### ISSUE TITLE
Document per well options better in ExportToDatabase

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3310]
The per-well means/medians/stdevs are only usable for MySQL (and CSV/MySQL, but I'm not sure the current status of #2961 ), not SQLite (per bb13353c36108bb18e1d524a91ab223ad7fc082a); this should be better documented in the help for ExportToDatabase.

**Comment by minh-doan** [comment]
If no one has taken this yet, I'll try

**Comment by bethac07** [comment]
Closed in #3337
