### ISSUE TITLE
DefineGrid: cannot "Leave blank" for displaying image

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3321]
At the last option of the module: "Select the image on which to display the grid"
One of the default options is to "Leave blank" >>> cannot actually leave blank
It throws error:
`
'float' object cannot be interpreted as an index
`
Set it to any image solves the error

--
OS: Mac
CP3.0.0rc5

**Comment by mcquin** [comment]
Resolved #3443
