### ISSUE TITLE
Change documentation to show that two class Otsu calculates differently in 2.2 vs 3.0

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3326]
The exact same image put through 2-class Otsu in 2.2 and 3.0 gives very different results (see below) whether in Global or Adaptive mode.  As far as I've tested this is specific to 2-class Otsu; 3-class Otsu and Robust Background give identical results in 2.2 and 3.0

![image](https://user-images.githubusercontent.com/6721515/31089257-6acb05ae-a771-11e7-9ece-510009aa9228.png)
[TwoClassOtsu.zip](https://github.com/CellProfiler/CellProfiler/files/1349673/TwoClassOtsu.zip)

**Comment by bethac07** [comment]
It's probably worth adding that from what I can tell from the source code, we've switched from using centrosome's otsu method to skimage's, which could certainly be a plausible explanation.  Would we typically expect the results to be that different?  If this is not a bug but rather an expected change, I think it's going to be very important to make clear to people that they may not get the same results between 2.2 and 3.0 and why the switch was made.

**Comment by 0x00b1** [comment]
@bethac07 IIRC, skimage uses centrosome's Otsu. skimage's Otsu has received a number of bug fixes in the past few years so it would make sense to see some differences. However, your example, is pretty dramatic. Maybe there was some post-processing morphological step involved in the original implementation to smooth the threshold?

**Comment by 0x00b1** [comment]
@bethac07 If you have time, it might be worth testing with OpenCV and ImageJ to compare results.

**Comment by bethac07** [comment]
As far as I can tell the [skimage](https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/thresholding.py#L230-L295) and [centrosome](https://github.com/CellProfiler/centrosome/blob/master/centrosome/otsu.py#L3-L57) implementations don't look that related to me but IANASE.

**Comment by 0x00b1** [comment]
> ImageJ's Auto Threshold computes 50/255= 0.196, close to 3.0s call of 0.192

I think the skimage version is the way forward. I guess we should write some documentation. Would you mind updating the subject of this issue?

**Comment by AnneCarpenter** [comment]
Wow, glad you noticed this!

Given how pervasive thresholding is in a typical image analysis pipeline, I think we should consider a warning to people loading old pipelines. When the new does not behave as the old, I don't think we'd expect users to look in the help to figure out why; they might not notice right away and then be confused why results look bad. Do we have any options for notifying someone when loading a pre-3.0 pipeline that their Otsu settings may need adjustment? Something like the standard "you are using an old pipeline" dialog except here we have a message indicating the change at 3.0. Whether it's a clever dialog that only pops up when Otsu is present vs. just adding some text to the standard "old pipeline" dialog is a question of how annoying the former is to implement.

And we should be super sure we think the current behavior is good. It's really weird this happened and also that it's not affecting three-class.

**Comment by bethac07** [comment]
I can't really claim all the credit, @minh-doan noticed when he was updating example pipelines that we were seeing a pretty extreme difference between 2.2 and 3.0; without him finding the original issue, I wouldn't have been able to track down the root cause!

We're working on writing up a document (for the blog/forum, though we can include it in the CP help as well if you think we should) of "things you should know when converting pipelines from 2.X to 3.0".  We're still in example-gathering phase, once we feel like we've collected everything and made it into something readable I'll share it.

We do already have the popup that appears when you load an old pipeline, we could add more specific (and bolded) warnings that we don't guarantee result consistency between 2.2 and 3.0.

**Comment by 0x00b1** [comment]
I experimented with this yesterday. CellProfiler (using `skimage.filters.threshold_otsu`) was consistent with OpenCV, ImageJ, and SimpleITK with every image I tried.
