### ISSUE TITLE
Documentation - Images module and its settings help

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3328]
It seems there is some discrepancy between the help buttons you click in the Images module and the overall module help you get when clicking ? for the entire module. 

Here is the text for the first setting's help button:
![buttonnearshowfiles](https://user-images.githubusercontent.com/1213811/31121984-867cfcca-a83a-11e7-85bf-3fa85dde2986.jpeg)

But that text is not found in the overall help for the Images module (but there is a different chunk of text that describes a bunch of right click options). 

It seems a reconciling is in order (in particular, I'm not sure how it's possible that settings buttons do not make it into the help for the module.)

**Comment by DavidStirling** [comment]
That particular dialog is tied to the GUI and not the module itself, so I couldn't add it without causing potential problems when only using cellprofiler_core. However, I have now added the other settings to the help text generator.
