### ISSUE TITLE
Failure to open new CP window from source and distribution

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3334]
File > Open new CP window , gives error:
```
Couldn't get a file descriptor referring to the console
```
Ubuntu 16.04
CP3.0.0rc7

**Comment by AnneCarpenter** [comment]
Same on Mac OS 10.12 rc7 but no one is going to die of this, I don't think it should hold up release :)

**Comment by AetherUnbound** [comment]
This appears to be a discrepancy between Mac and Linux: https://stackoverflow.com/questions/42463929/couldnt-find-a-file-descriptor-referring-to-the-console-on-ubuntu-bash-on-win
@AnneCarpenter does it still not work on OSX?

**Comment by AetherUnbound** [comment]
I think I have a working fix for this in this branch: https://github.com/AetherUnbound/CellProfiler/tree/issues/3334
Do you two mind trying it out?

**Comment by AnneCarpenter** [comment]
I don't have CP set up from source! 😱   Hopefully @minh-doan can try it out.

**Comment by minh-doan** [comment]
@AetherUnbound thanks for the effort !

I cloned your branch issues/3334, (your git).
CP3 opened fine with wxPython 3.0.3
Then File > Open new CP window gives me this error in the terminal:

`The file /Users/..../CellProfiler/cellprofiler/CellProfiler_python.command does not exist.`

Tried it on Mac OS X 10.12

Can you please recheck.

Thanks !

**Comment by mcquin** [comment]
The script to launch another CP window was [removed in this commit](https://github.com/CellProfiler/CellProfiler/commit/7917fd95d2b99079438f6813cdbd7f7a8853b48f).

I think we should decide if launching multiple CP windows is a desired feature and, if so, implement it properly. Or, delete the menu option altogether.

**Comment by AetherUnbound** [comment]
Wow, I didn't even realize that was a thing. I'm all for removing the option, but (knowing that there once was a script that accomplished this) I think it might be possible to fix this behavior.

**Comment by mcquin** [comment]
I'm also in favor of removing the option given that no one reported the feature as broken in the year-and-a-half it hasn't been available, indicating a lack of use.

**Comment by AnneCarpenter** [comment]
Well, let's not be hasty!
just kidding. Let's torch it.

**Comment by minh-doan** [comment]
As an essay dev., I sure do it often, for e.g. open a pipeline someone on forum made, then compare to my version of it. But agree with Anne that I'm surprised no one else reported this on the forum.

**Comment by mcquin** [comment]
Ah, I'd failed to consider that it does work in CP2.2 from the distributed package. My argument is invalid.

> (the use case is to open two pipelines and compare them side by side, maybe even drag and drop modules from one to the other. But if people are not complaining maybe they do not do this very often)

I've heard this come up as a use-case before (and Minh just verified it). That's a good case for restoring this behavior from source, and ensuring it works on Ubuntu.

**Comment by mcquin** [comment]
On OS X, with CellProfiler 2 and 3 installed, *File > Open a New CP Window* starts CellProfiler 2. When I remove CellProfiler 2, nothing happens. I suspect this is because [it looks for CellProfiler.app](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/cpframe.py#L952) instead of CellProfiler-3.0.0.app.

**Comment by AetherUnbound** [comment]
Okay, thanks all for the input! I will work to find a cross-platform solution for this :+1:

**Comment by AetherUnbound** [comment]
I've made a change in the branch mentioned above, @mcquin and @minh-doan, do you mind trying it?

**Comment by mcquin** [comment]
@AetherUnbound I think your solution will only work when a non OS X user also has CellProfiler installed from source. I suspect we'll need to do something like what's suggested in https://stackoverflow.com/a/10294435 to properly pick up how CellProfiler was started.

When `os.system("cellprofiler")` runs, the parent process hangs until the new CellProfiler window is closed. I suspect we'll need to [spawn a new process](https://docs.python.org/2/library/subprocess.html#replacing-the-os-spawn-family) and figure out how to handle closing CellProfiler (close itself and all open windows? only close itself?).

Furthermore, there are a few ways to run CellProfiler from source:
- `cellprofiler` (post pip install)
- `python -m cellprofiler`
- `python cellprofiler/__main__.py`

The last two appear to require making `cellprofiler/__main__.py` executable. This seems fine, but we should do a little research to validate that idea.

Finally, I don't have a good grasp on how to run the frozen version. I suspect that could require some "build and try it" development.
