### ISSUE TITLE
More interpretable warning needed when using IdentifyPrimaryObjects with 3D volumetric datasets

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#3338]
I noticed that IdentifySecondaryObjects should support volumes was marked as done so I started testing IdentifyPrimary with volumetric datasets today.  I am getting the following error message "Error while processing IdentifyPrimaryObjects: structure and input must have equal rank".  Has IdentifyPrimaryObjects been upgraded to support 3D datasets?

**Comment by AnneCarpenter** [comment]
No it has not, but it would be nice if there is a warning for such. Do you mind changing the title to "More interpretable warning needed when..." ?

**Comment by mcquin** [comment]
Non-3D supporting modules cannot be added to a new pipeline that's configured to process volumes. Let's verify the behavior, and also verify that running an existing pipeline (which is converted to process data as 3D) raises an interpretable error.
