### ISSUE TITLE
Watershed module with Generate from Markers option bug

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#3342]
I am getting the following error message with the watershed module.  It appears to be performing a 2 fold downsampling of the image channel while leaving the marker channel at the original XY dimensions leading to the following error message "markers shape must have same shape as image".  I can add a resize module to upsample the image dimension so that the downsampling in the watershed step doesn't lead to this message. However, I think that it would be more appropriate to change watershed so it does not implicitly resize the image channel. 

<img width="547" alt="bug" src="https://user-images.githubusercontent.com/20077409/31556077-4cf0f374-aff8-11e7-9ac7-c630b9bda55f.png">

**Comment by AnneCarpenter** [comment]
Great catch!

**Comment by 0x00b1** [comment]
Thanks, @derekthirstrup! I agree.

**Comment by derekthirstrup** [comment]
Could you also please verify that the seeding module works with the marker watershed option?  It looks like it will be required for our 3D volumetric datasets.  It helps prevent the cells from growing to the top and bottom of the z-stack.

**Comment by DavidStirling** [comment]
Appears to be fixed, please re-open if it's not!
