### ISSUE TITLE
Images don't appear in help in 3.0.0 release

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3346]
All images in any help menu (that I've tried so far at least) just show up as red X's.  Likely #3343 is a small subset of this.

**Comment by 0x00b1** [comment]
Thanks, @bethac07. Verified. This appears to impact Linux, macOS, and Windows.

I believe it’s build related so I might update the existing 3.0.0 builds instead of waiting for 3.0.1.

**Comment by AetherUnbound** [comment]
@0x00b1 @bethac07,  was this addressed?

**Comment by bethac07** [comment]
@AetherUnbound Not to my knowledge, but since it's build related I'm not sure.

**Comment by AetherUnbound** [comment]
This was addressed via #3483
