### ISSUE TITLE
CP 3.0 doesn't start up

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3347]
I downloaded the 187.6 MB  CellProfiler-3.0.0.dmg from cellprofiler.org/releases just now at 8 pm. 

I get the nice window that shows you to drag CP to the Apps folder. Once it copied over it produces a 330.1 MB app in the Apps folder (timestamp 2:53 pm).

Doubleclicking it says, this is downloaded from the internet - do you want to open it? I say yes but it never opens. The bouncing icon in the dock just goes away  :(

I'm on 10.12.6

**Comment by 0x00b1** [comment]
Resolved
