### ISSUE TITLE
Change Morph's upgrade_settings to allow loading the rest of the pipeline.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3349]
When upgrading pipelines from 2.2 to 3.0, the biggest problem I've run across so far is in pipelines that contain Morph; if the Morph option is one that has now moved to its own module, you hit the [raise at line 587](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/morph.py#L587) and whether you hit "cancel" or "continue processing" on the error message (see below) the rest of the pipeline does not load.  This is an especially big problem because Morph is often used near the beginning of a pipeline to clean images before segmentation and measuring, so it is not uncommon to see a case where you can only load the first 5 modules of a 40 module pipeline and then lose the rest.

As far as I can tell, this is the only module that behaves that way; if for example you had a pipeline in 2.2 with ApplyThreshold with a thresholding method that's now been removed (like MCT), loading that pipeline (correctly) shows an error at Threshold when loaded into 3.0 until you give it a new thresholding method, but it doesn't prevent the modules after it from being able to load.  

I'm not sure if the cleaner/better solution would be to just kill the "raise" line or to fix the "Continue Processing" behavior, but for the sake of our older users and power users it would be GREAT if this behavior could be changed by 3.0.1.  It'd be great if we could fully catch it and even put the new "correct" module into the pipeline, but I'd be happy just if it could be bypassed to allow the full pipeline to load.

![image](https://user-images.githubusercontent.com/6721515/31788906-461a69e6-b4de-11e7-9772-c7d0aff07b2d.png)

**Comment by braymp** [comment]
I'm assuming that the main problem re: simply upgrading the settings is the fact that multiple operations were allowed per module with 2.2?

If so, is it too much to have 3.0 simply break each operation into its own Morph module and set the input images for each such that they chain together?  I.e.,

Morph: 
* Input image: BinaryImage
* Output image: FinalOutput
* Operations: Close, Skeleton, Shrink

gets converted into:

Morph: 
* Input image: BinaryImage
* Output image: MorphedOutput1
* Operations: Close

Morph: 
* Input image: MorphedOutput1
* Output image: MorphedOutput2
* Operations: Skeleton

Morph: 
* Input image: MorphedOutput2
* Output image: FinalOutput
* Operations: Shrink

**Comment by 0x00b1** [comment]
Thanks, @bethac07. And thanks for the feedback, @braymp.

The exception shouldn’t break control (and delete the user’s pipeline instance). I’ll prioritize this for 3.0.1. Unfortunately, I don’t know if there’ll be time or interest to catch the exception and push the correct modules onto the pipeline.

**Comment by 0x00b1** [comment]
(I’m also relabeling this as a bug.)

**Comment by AnneCarpenter** [comment]
FWIW, I agree that auto-upgrading pipelines containing Morph isn't high enough priority to be likely happen. My rationale is the module is lesser-used and when used, it's more likely to be someone familiar with image processing and more likely to be able to fix it.
