### ISSUE TITLE
Error upon double-clicking image in Images module 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#3350]
I drag some images in to 3.00 (stable release, Windows binary).  Then double-click an image in the image list and get this:

![image](https://user-images.githubusercontent.com/1225595/31790461-87fd73da-b4e3-11e7-87f3-0b87b5986efa.png)

**Comment by AnneCarpenter** [comment]
Ah, the top of your screenshot is cut off but I suspect there is supposed to be a nice CP icon in the top left of that image window, but it looks like a blue/white/gray thing instead.

**Comment by dlogan** [comment]
Here's the whole screen:
![image](https://user-images.githubusercontent.com/1225595/31820414-382cf3bc-b56f-11e7-8875-0ca1c93c3abf.png)

So it's interesting that there is a CP icon in the main window, but perhaps the image window is calling for it too and can't?

**Comment by 0x00b1** [comment]
Thanks, @dlogan.

**Comment by dlogan** [comment]
Well, I closed and re-opened CP3 and the double-click image display now works fine!  Not sure what would've caused the transient issue, but perhaps close this issue unless someone else verifies?

**Comment by mcquin** [comment]
I'm unable to verify on OS X. @dlogan closing per your suggestion. Let us know if you see this behavior again.
