### ISSUE TITLE
Remove Morph module's "life" operation

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3357]
In the Morph module, all options seem to work fine except “life”… it just hangs indefinitely. I propose we remove the option. 

In Test Mode, it freezes CP so that Force Quit is the only option. In Analyze Images mode, you retain the ability to stop it using Stop Analysis and it ends gracefully.

For extra brownie points, I tested all other operations in Morph and they work fine.

**Comment by AnneCarpenter** [comment]
For even more brownie points, here is a pipeline to demonstrate the behavior:
[Archive.zip](https://github.com/CellProfiler/CellProfiler/files/1408780/Archive.zip)

**Comment by AetherUnbound** [comment]
Since this uses the `cpmorphology` module (which it looks like we're trying to move away from) I also think it's fine to remove.

**Comment by jhung0** [comment]
It's gone https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/morph.py#L599
