### ISSUE TITLE
Link error messages to Forum posts

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3360]
From @thouis, a nice feature of GATK is that error messages usually have a link to a URL where there is an initial post to help troubleshoot, followed by community discussion with other tips and tricks.

**Comment by thouis** [comment]
Here's an example: 
https://gatkforums.broadinstitute.org/gatk/discussion/59/errors-about-read-group-rg-information

another:
https://software.broadinstitute.org/gatk/documentation/article?id=1328

**Comment by bethac07** [comment]
I'm not fully clear what the idea is here-

* Link to forum posts when making a GitHub issue?  I usually do that where possible (See #3358)
* A troubleshooting wiki?  Here or on the forum?
* Linking to GitHub issues in the forum for helping troubleshoot?  I usually do that too where appropriate (see [here](http://forum.cellprofiler.org/t/crop-module-error/5224/4?u=bcimini)).

You know me, I'm always down for more documentation and more troubleshooting help for users, I'm just not clear on what the idea is.

**Comment by thouis** [comment]
I'll try to generate a real example to screenshot, but the idea would be in the error message (that you linked in #3358), instead of CP producing:

> ‘Error while processing Crop: slice indices must be integers or None or have an index method’

it would produce:

> ‘Error while processing Crop: slice indices must be integers or None or have an index method - see http://cellprofiler.org/wiki/Crop_slice_indices'

That's a poor example, because it sounds like that case was a bug rather than a user error.  I don't know how well CP's type checking helps avoid processing-time failures, so maybe this is not that useful an idea.

Does that clear it up?

**Comment by AnneCarpenter** [comment]
Yeah, the idea is for every unique error message CP produces, we make (in advance) a corresponding forum post. That post's URL is included in the error message so when people encounter the error, they go to the URL and hopefully find info to help them in two ways:

1) Our initial forum post, which we might continually edit to include the most common explanations/fixes. 
2) Community responses that follow up on the post with other ideas/questions that might help.

**Comment by braymp** [comment]
I don't think you'd want *every* unique error, since some contain different text but stem from the same source, e.g., http://forum.cellprofiler.org/t/cellprofiler-2-0-faq/1813/15
