### ISSUE TITLE
Measure hollowness of a volume

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3370]
- Measure hollowness, e.g. if a "cave" exist or not inside a whole sphere, how large that cave compared to the whole mass.

**Comment by AnneCarpenter** [comment]
Do you mind breaking these up into separate issues? That would be helpful!

**Comment by DavidStirling** [comment]
I think the `solidity` measure from MeasureObjectSizeShape gives a reasonable estimate of this. It's now available with 3D volumes!
