### ISSUE TITLE
Catch and nicely explain ExportToDatabase too many columns error

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3373]
From [the forum](http://forum.cellprofiler.org/t/cp3-0-error-in-exporttodatabase-during-startup-too-many-columns-on-analysis-per-object/5282) via @PetterRanefall 

>I have a pipeline (based on CellPainting) that works fine in CP2.2, but when I try to run it in CP3.0 I get an error message: “Encoundtered unrecoverable error in ExportToDatabase during startup: too many columns on analysis_Per_Object”.
I am using a SQLite database.

@minh-doan noted:
>While waiting for others’ help, you can try to bypass the error by removing one of the scale at “MeasureTexture” . At the moment it measures both scale 3 and 5. Skip either of them solves the issue.

and that the full error message was
```
Failed to prepare run for module ExportToDatabase
Traceback (most recent call last):
File “/Users/…/CellProfiler/distribution/macos/CellProfiler/cellprofiler/pipeline.py”, line 2085, in prepare_run
if ((not module.prepare_run(workspace)) or
File “/Users/…/CellProfiler/distribution/macos/CellProfiler/cellprofiler/modules/exporttodatabase.py”, line 1836, in prepare_run
self.create_database_tables(self.cursor, workspace)
File “/Users/…/CellProfiler/distribution/macos/CellProfiler/cellprofiler/modules/exporttodatabase.py”, line 2371, in create_database_tables
execute(cursor, statement, return_result=False)
File “/Users/…/CellProfiler/distribution/macos/CellProfiler/cellprofiler/modules/exporttodatabase.py”, line 283, in execute
cursor.execute(query)
OperationalError: too many columns on analysis_Per_Object
```

Pipeline and images attached.
[cellpaintinganalysis.zip](https://github.com/CellProfiler/CellProfiler/files/1447492/cellpaintinganalysis.zip)

**Comment by mcquin** [comment]
The error indicates @PetterRanefall is hitting the maximum column limits for a MySQL database. Try exporting a single object per table or as a single object view.

We can definitely try to catch the error and print a friendlier message to the user.
