### ISSUE TITLE
Merge seeding artifacts into most significant neighbor

### ISSUE THREAD

**Issue by AetherUnbound** [CellProfiler/CellProfiler#3381]
In our seeded watershed segmentation with CellProfiler, we're finding that a number of seeding artifacts are left in the final segmentation. These over-segmented sections can't be removed and filled through normal methods as many of the seeds grow to the edge of the cell. 

Example:  
![image](https://user-images.githubusercontent.com/10214785/32806698-5917183c-c942-11e7-8d24-c2b26fdd1180.png)

**Comment by minh-doan** [comment]
Can you try the module "SplitOrMergeObjects" to see if it helps?

**Comment by AetherUnbound** [comment]
From @mcquin in #3384 

> The merge options for SplitOrMergeObjects indicate different approaches for merging objects than this implementation. Until that module supports 3D, it's sensible to leave this as a separate module.

**Comment by AnneCarpenter** [comment]
Hi all, thanks for adding this functionality! Shouldn't it live in plugins, though, if we foresee it being temporary (i.e. eventually replaced by a more complete/3D SplitOrMerge, or even by IdentifyPrimaryObjects)?

**Comment by AetherUnbound** [comment]
@AnneCarpenter That makes sense, I'm happy to move it there!
