### ISSUE TITLE
MeasureTexture on objects is exceptionally slow in 3.0.0

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3386]
Measuring 3 channels in 3 objects at 3 scales is taking >3 hours; measuring just the image texture features for those 3 channels/3 scales inthat image takes 20-30 seconds, so it's likely something in the objects.  Pipeline + images are confidential but will be sent via email.

**Comment by AnneCarpenter** [comment]
A debugging idea to try: just measure one object type x one channel?

**Comment by riturkki** [comment]
Any update on this? Measuring texture in CP (3.1.8) seems to be suuuper slow :)

**Comment by Charles-Baker** [comment]
Echoing the above comments. Are there any updates on this? I see in the source code that there is a comment that says: "CellProfiler in all 2.X versions increased speed by binning the image into only 8 greyscale levels before calculating Haralick features; this is not done in CellProfiler versions 3.0.0 and after". Could this be the main source of the slowness? If so, is there a way to convert images to 8-bit in CellProfiler 3 or perhaps there could be an option to use 8 bit in the module?

**Comment by ranka47** [comment]
> Echoing the above comments. Are there any updates on this? I see in the source code that there is a comment that says: "CellProfiler in all 2.X versions increased speed by binning the image into only 8 greyscale levels before calculating Haralick features; this is not done in CellProfiler versions 3.0.0 and after". Could this be the main source of the slowness? If so, is there a way to convert images to 8-bit in CellProfiler 3 or perhaps there could be an option to use 8 bit in the module?

The bit depth of the images that I am working on is 16 bits and we wanted to use `MeasureTexture` for the analysis.

Is it inherently slow for now in CP 3.X or we can speed it up by converting it into uint8 somehow? 
I saw a couple of google results that point that the module `RescaleIntensity` can be used to convert it into `uint8`. However, the web link is broken. Can you point out some other method by which we can achieve it? I can't shift to CP 2.X as we need the modules that are supported only in CP 3.X

**Comment by Charles-Baker** [comment]
My experience has been that 'converting' the images by using
RescaleIntensity does seem to speed up the computation slightly. It makes
it bearable if you are only measuring texture for the image but if you need
to calculate texture for objects, it is still extremely slow.

**Comment by ranka47** [comment]
I want to measure the texture for the individual nucleus and cells so `RescaleIntensity` not helping much.

**Comment by AminFefe** [comment]
Hi all, 
Is there any news on this side? I am trying to extract [CP-CHARM features](https://github.com/CellProfiler/CPCharm) for an experiment and the EnhancedMeasureTexture module is a huge bottleneck, making the procedure impossible to scale. Or does anyone have a workaround? Thanks.

**Comment by AnneCarpenter** [comment]
I suspect it is not a high priority right now, it would be great if someone can submit a pull request to add an option to do the CP2-style binning. 

It would be great, though, if someone can confirm that doing this binning doesn't make the metrics useless!

**Comment by bethac07** [comment]
We hit a technical issue in trying to resolve it; we can resolve it with hopefully not-too-much focused work, but it is indeed not high on the list right now.

We know though that the binning doesn't make the metrics "useless", as that is how the metrics were computed in CP2 and Texture features certainly have proven useful in CellProfiler 2 workflows!  Whether they are demonstrably BETTER with 256 levels vs 8 is an open question.
