### ISSUE TITLE
Viewer can't open filenames with space in Cellprofiler 3.0

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3388]
Forum discussion : http://forum.cellprofiler.org/t/filenames-issue-in-cellprofiler-3-0-on-windows/5371

I confirm this on Mac : filenames with space can be analyzed, but cannot be viewed.

**Comment by AetherUnbound** [comment]
I found it! The URL was being converted to a file name, but the variable with which it was defined was unused when displaying.

**Comment by mcquin** [comment]
Resolved #3414
