### ISSUE TITLE
3D Slice Viewer fails if exactly 3 or 4 slices

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3394]
Hat tip to @tischi in [the forum](http://forum.cellprofiler.org/t/loading-data-into-cellprofiler-3d/5372);

If you try to use the 3D slice viewer with only 3 or 4 slices, you get a view that looks like the below; if you have 2 or 5-10 (and presumably everything after) it works fine.  Happens to him on Mac (at least with a 3 image stack) and me on PC.  Pipeline and images to verify here.
[3DViewer.zip](https://github.com/CellProfiler/CellProfiler/files/1516114/3DViewer.zip)

![image](https://user-images.githubusercontent.com/6721515/33407020-71f40994-d53d-11e7-8360-6b16f8862e26.png)

**Comment by mcquin** [comment]
CellProfiler appears to be storing Z-stacks with 3 or 4 planes as images.

**Comment by AetherUnbound** [comment]
`skimage` (which I think uses `tifffile`) might be interpreting that as a color channel, much the same way that we check whether the last dimension is of length 3/4.

**Comment by AetherUnbound** [comment]
Looks like `tifffile` is okay: 
```
>>> data = np.random.rand(3, 256, 256)
>>> data.shape
(3, 256, 256)
>>> tifffile.imsave('temp.tif', data)
>>> image = tifffile.imread('temp.tif')
>>> image.shape
(3, 256, 256)
```

**Comment by AetherUnbound** [comment]
@mcquin these seem to be the cause: https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_io.py#L61-L64

**Comment by cgohlke** [comment]
Besides skimage swapping the axes, it's better to explicitly specify the photometric mode for volume stacks when using tifffile:

```
skimage.io.imsave("foo.tiff", numpy.random.rand(3, 256, 256), photometric='minisblack')
```

**Comment by mcquin** [comment]
Thanks for the tip, @cgohlke. We should add that to SaveImages. 

Great find, @AetherUnbound. It looks like swapping axes was introduced in https://github.com/scikit-image/scikit-image/pull/1498 in response to https://github.com/scikit-image/scikit-image/issues/1496.

Since TIF is the only supported file format for volumes, I think it's okay if we go ahead and open volume stacks with `skimage.external.tifffile.imread`.
