### ISSUE TITLE
Error using random forest classifier from CPA in FilterObjects Module

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#3397]
I am seeing two errors when I am using a random forest classifier trained in CPA.

1. In the executable version of CellProfiler I see the following: `Exception in cpmodule.test_valid No module named ensemble.forest`

1. When running from source I see the following: `Exception in cpmodule.test_valid 'max_depth'`.

I've attached the model I saved to this issue. Note I had to make the file extension *txt* in order to upload it.

[issue.model.txt](https://github.com/CellProfiler/CellProfiler/files/1519125/issue.model.txt)

**Comment by jhung0** [comment]
Ok I see the problem. There must be a mismatch in the scikit learn versions you're using to save the model in CPA and load in CP. If the versions match, you don't see this. Like I'm using sklearn 0.19.0, but if I try to use your model, it says it's from sklearn pre 0.18, so you get that error.

**Comment by Perishleaf** [comment]
I had the same issue.
`/usr/local/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version pre-0.18 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.`

How should I solve this?
Thanks in advance.

**Comment by AnneCarpenter** [comment]
You can either proceed, or use the older version.

**Comment by Perishleaf** [comment]
> You can either proceed, or use the older version.

Thanks, Anne. I replaced the sklearn folder within CPA package with a new version sklearn. This solved my issue.
