### ISSUE TITLE
Help button in File > Run Multiple Pipelines does nothing

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3399]
In v 3.0

**Comment by bethac07** [comment]
Hmmm, it does on my machine.  Mac/PC difference?

**Comment by AnneCarpenter** [comment]
Ohhh... must be.

**Comment by bethac07** [comment]
NVM, I can't read; the HELP button is indeed broken in Run multiple pipelines- pressing it gives the following:

```
Traceback (most recent call last):
  File "cellprofiler\gui\runmultiplepipelinesdialog.py", line 246, in on_help
    cellprofiler.gui.help.content.read_content("other_multiple_pipelines.rst")
  File "cellprofiler\gui\htmldialog.py", line 33, in __init__
    html.SetPage(contents)
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\html.py", line 988, in SetPage
    return _html.HtmlWindow_SetPage(*args, **kwargs)
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 432: character maps to <undefined>
```

**Comment by AetherUnbound** [comment]
It looks like it opens for me but it doesn't render properly and CellProfiler becomes unresponsive afterwards.
![image](https://user-images.githubusercontent.com/10214785/33799232-9baa3c44-dcdc-11e7-9c49-3146f7a4fa69.png)

**Comment by AetherUnbound** [comment]
I've started work on this is the branch `issues/3399`. I've gotten the help to render as HTML (and I suspect I found the cause of the "charmap codec" error, but the window still freezes for me. I'm on Linux and so I think I might be experiencing a separate issue. @bethac07, can you checkout my branch and see if it loads properly for you?

**Comment by AetherUnbound** [comment]
It looks like I've got a fix that makes it work and render properly on Linux: 1f49ec918f971cc26fd5bca49170ae861eb6ed1d, does it work for you guys?

**Comment by bethac07** [comment]
Looks great to me!  Thanks for the fix :)
