### ISSUE TITLE
In-App help button is broken

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3405]
From [the forum](http://forum.cellprofiler.org/t/filenames-issue-in-cellprofiler-3-0-on-windows/5371/10?u=bcimini)

On the welcome screen is a button under "In-App help" that's supposed to give you information on how to use the help (current button and 2.2 version of what was shown below.  Pressing it gives the following error message, at least on Windows 10 in both 3.0.0 built and today's master.

```
Traceback (most recent call last):
  File "cellprofiler\gui\welcome.py", line 476, in OnLinkClicked
    self.__display_help(href[7:])
  File "cellprofiler\gui\welcome.py", line 485, in __display_help
    html_str = self.href_to_help[href]
KeyError: u'Using%20the%20help'
```

![image](https://user-images.githubusercontent.com/6721515/33738498-6c8efdbc-db67-11e7-8465-df1ecde936cc.png)

![image](https://user-images.githubusercontent.com/6721515/33738543-82eb6e38-db67-11e7-9079-85d3d8af901f.png)

**Comment by AetherUnbound** [comment]
It looks like the "in-app help" reference is defined https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/welcome.py#L13-L21 but the content is missing from the page, and subsequently the `href_to_help` dictionary: https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/welcome.py#L458-L467

**Comment by AetherUnbound** [comment]
It looks like this might have been dropped from the original file when the UI was updates: https://github.com/CellProfiler/CellProfiler/commit/4b9c4b22c6a1a1db1ff41de3b746726b20f5fdac#diff-3a0157b849bfd55f2a6578a7fd4a386bL118
