### ISSUE TITLE
Update CP logo

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3417]
Assuming this is a file that is actually used somewhere, it'd be great to update to the new version!

https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/data/images/CP_logo.png

**Comment by AnneCarpenter** [comment]
Here is the one Jeanelle emailed around recently.

![2017_11_21-cp_logo_black_tm](https://user-images.githubusercontent.com/1213811/33851893-75cbdee6-de86-11e7-8943-d05cbe10ef14.png)

**Comment by mcquin** [comment]
This appears to be unused.

We should remove the unused images in this directory.

**Comment by mcquin** [comment]
Update: This could probably replace https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/data/images/splash.png
