### ISSUE TITLE
Using Numpy array is input

### ISSUE THREAD

**Issue by willgdjones** [CellProfiler/CellProfiler#3423]
Hello, CellProfiler community!

I have a set of 3-channel images stored as Numpy arrays, and I would like to use these as input to a CellProfiler pipeline. The CellProfiler pipeline is available here: https://stanfordmedicine.app.box.com/s/06awqopz9xzyfxhke9ph8exac2oxem2t.

As I understand from the tutorials, images are fed into Pipelines as .TIFF files, and I don't know how to adapt this to my specific use case.

Any advice would be greatly appreciated.

Thank you!

**Comment by bethac07** [comment]
Hi,
Cell Profiler 3.0+ can read .npy array files as images.

**Comment by willgdjones** [comment]
Hi @bethac07 thank you for response! I am glad that there is a solution, but because I am unfamiliar with CellProfiler I do not seem to be able to work it out.

Looking at the page: https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-as-a-Python-package

I am able to create load the pipeline into a pipeline objects. I'm just not clear from this point how I would change the pipeline to use my images instead. Thank you for your help!

Will

**Comment by mcquin** [comment]
Hi @willgdjones, 

CellProfiler 3.0 added support for Numpy array data (saved as `.npy`). You need to tell the Images module that `.npy` files are image data. Check out the custom image filtering criteria below:

![screen shot 2017-12-21 at 9 53 08 am](https://user-images.githubusercontent.com/4721755/34260789-043bed00-e635-11e7-8388-547b3f79ff6a.png)

Hope this helps!

---

Let's consider adding first-class support for images as Numpy arrays (i.e., these files should pass the default filtering criteria), or expanding the documentation.

**Comment by willgdjones** [comment]
Hi @mcquin - thank you for your reply.

Since I have many files which are located in a cluster environment, I haven't used the CellProfiler  GUI before! Is this possible to do using the Python interface? It would make my life a hell of a lot easier if so. If not, I can look to get working with the GUI.

Thanks for your help!

Will

**Comment by AetherUnbound** [comment]
@willgdjones
I believe you have 2 options for cluster work:

1. Convert your images to tiffs using `skimage.io`, create a file list, and call CellProfiler using the methods described here: https://github.com/CellProfiler/CellProfiler/wiki/Adapting-CellProfiler-to-a-LIMS-environment
2. From within your python code, call CellProfiler as a package as described here: https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-as-a-Python-package. @mcquin, is the latter possible? How does one hand images to the CP pipeline?

**Comment by mcquin** [comment]
@willgdjones You only need to access to the pipeline files and update the Images module as shown in my last reply. Then, you should be able to re-upload the pipeline to the cluster and run it there, where your images are.

@AetherUnbound's suggestion of converting your Numpy arrays to TIFs using `skimage.io` would work, too. And could be performed on the cluster, where I assume your images are. `skimage.io` also supports PNGs and JPG/JPEG, which CellProfiler can read "out of the box". 

This may be a good option for you, as I noticed your pipeline was saved with CellProfiler 2.X. Most pipelines can be upgraded seamlessly to CP 3.0, you'll need the GUI to update pipelines that can't be automatically upgraded.

**Comment by DavidStirling** [comment]
Please re-open if there are still problems with this.

**Comment by i-molodtsov** [comment]
@willgdjones 
Hi William,
Sorry to bother you after all these years, but it seems like I'm falling into your steps and I was wondering if you may help me. The link you mention in original post seems to be dead by now, but maybe by some wild chance you still have the pipeline file saved somewhere? Thank you!

**Comment by bethac07** [comment]
You should be able to drag-and-drop numpy arrays into CellProfiler 3 or 4 and have them work just like any other images.
