### ISSUE TITLE
`MeasureTexture` Object measurements inconsistent between CP2.2 and CP3.0

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#3430]
Hi,
I spent the last couple of days tracking down a problem with Texture feature calculation inconsistency between CP2.2 and CP3. 
I noticed that CP3 now calculates the Haralick features using mahotas. Therefore I will mark @luispedro as well.

While I expected that the Haralick features may be calculated in a slightly different manner between the two implementations (e.g. different scaling etc), I would expect them to at least be highly correlated. This doesn't appear to be the case. 

I put together a test case in a repository here 
https://github.com/VolkerH/ComparisonTextureFeatures
, complete with sample images and pipelines for CP2.2 and CP3.

The main findings are in this jupyter notebook:
https://github.com/VolkerH/ComparisonTextureFeatures/blob/master/CompareTextureInfo.ipynb

I don't have a gold-standard implementation for Haralick features, so I can only say that they differ. I don't know which version is correct. 

I noticed that CP3 handles per-object feature calculation by setting non-object pixels to zero and then calling the mahotas haralick feature computation with `ignore-zeros=True`. Maybe that has something to do with it.

**Comment by VolkerH** [comment]
I just saw that there is also a test for haralick features on the current master: 
https://github.com/CellProfiler/CellProfiler/blob/master/tests/test_haralick.py

However, this tests the old implementation in the centrosome module which is no longer used for the actual calculation.

**Comment by luispedro** [comment]
Initially, the mahotas implementation was debugged to obtain the same results as the old Murphy Lab C/Matlab code. That was my gold standard at the time and, within rounding error, I reproduced the features at the time.

On exception was a difference in interpreting one of the features where the original Haralick paper is somewhat ambiguous [in my interpretation, the formula in the paper has a typo, but you can infer what was meant from context; others have chosen to implement the formula as written].

Without knowing much about how CP internally computes haralick features, my guess is that the difference is not in the feature computation code, but in how images are preprocessed _prior_ to passing them to the haralick routines. For example, if previous versions of CP did not have the equivalent of `ignore_zeros=True`, then the features will be different as they would include background when computing the features for each object (this is all speculation based on past experience).

**Comment by VolkerH** [comment]
@luispedro @mcquin, thank you very much  for your insightful comments. I am still on holiday and was offline for a few days. During the holidays I also had a closer look at the centrosome implementation of haralick features and also noticed the per-object scaling and very coarse quantization of the intensity levels. 
I will play around some more with both implementations when I'm back at work.

From a users perspective, I would suggest including a cautionary note in the module documentation for CP3 that the results will differ from the one in CP2.2 due to different implementations with different pre-processing.
