### ISSUE TITLE
[Ubuntu 16.04] Unable to scroll in "Add Modules" window

### ISSUE THREAD

**Issue by AetherUnbound** [CellProfiler/CellProfiler#3438]
As said above, scrolling does not seem to be enabled in the add modules window.

**Comment by AetherUnbound** [comment]
It looks like scrolling with the mouse wheel works only when the cursor is hovering over the scrollbar. Can anyone else on another OS describe their scrolling behavior?

**Comment by mcquin** [comment]
I'm able to scroll on OS X.

**Comment by AetherUnbound** [comment]
I think this may just be a GTK thing. I'll close this issue.
