### ISSUE TITLE
Smooth 'Calculate artifact diameter' option intermittently doesn't show toggle buttons.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3450]
Observed [in the forum](http://forum.cellprofiler.org/t/smoothing-by-median-filter/5468) on Windows 10, observed by me + an attendee at a tutorial on Windows 7 (see screenshot from her below).  Issue is fixed by closing/reopening CellProfiler.  Will probably be a bear to find but thought worth reporting.

![cellprofiler bug](https://user-images.githubusercontent.com/6721515/34687170-ee28506c-f47b-11e7-8477-b464ecf18aa2.jpg)

**Comment by AetherUnbound** [comment]
This may actually be related to #3104, any chance you could see if it is fixed by the associated PR?

**Comment by bethac07** [comment]
Since it's an issue that only comes up rarely and intermittently, it's gonna be hard to reproduce.  I'm fine with closing assuming it HAS been fixed by #3104 unless we get evidence otherwise.
