### ISSUE TITLE
C++ wx assertion errors pop up randomly during analysis runs

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3461]
I've encountered this once or twice myself, but here are [some](http://forum.cellprofiler.org/t/cellprofiler-3-windows-10-large-dataset/5521/3) from [the](http://forum.cellprofiler.org/t/erro-message-c-assertion/5491) forum [recently](http://forum.cellprofiler.org/t/c-assertion-error-cp-3-0/5554); in only case did someone capture things from the terminal after (bottom snippet) but I've transcribed as best I can in the top snippet.  It's popped up in Windows 7, Mac, and Windows 10; the common thread seems to be that the pipelines run fine on smaller batches but hit this error on larger ones.  For at least 2 users running the pipeline with the display enabled ("eyes open") vs closed seemed to make a difference, one user said it did not and he had to decrease his batch size.  

I hadn't reported it before because it's an intermittent issue that apparently only crops up on large batch sizes, which I assumed would make it hard to debug and troubleshoot, but I realized it should probably be documented and hopefully you guys can do your magic and find it. 

![image](https://user-images.githubusercontent.com/6721515/35076303-b8c7435a-fbc5-11e7-9f80-c4b82d3424f8.png)
![image](https://user-images.githubusercontent.com/6721515/35076320-c8b7e2f6-fbc5-11e7-83ea-5b7d580b14aa.png)
![image](https://user-images.githubusercontent.com/6721515/35076293-a947217a-fbc5-11e7-82e6-1cf5b270028b.png)

```
C++ assertion "(itemid >=0 && itemid <SHRT_MAX) ||  (itemid>=wxID_AUTO_LOWEST && itemid <= wxID_AUTO_HIGHEST)" 
failed at ..\..\src\common\menucmn.cpp(260) in wxMenuItemBase::wxMenuItemBase(): invalid item value
```

```
Traceback (most recent call last):
File “CellProfiler\cellprofiler\gui\cpframe.py”, line 483, in OnClose
File “CellProfiler\cellprofiler\gui\pipelinecontroller.py”, line 1333, in check_close
File “site-packages\wx-3.0-msw\wx_controls.py”, line 193, in init
wx._core.PyAssertionError: C++ assertion “id == wxID_ANY || (id >= 0 && id < 32767) || (id >= wxID_AUTO_LOWEST && id <= wxID_AUTO_HIGHEST)” failed at …\src\common\wincmn.cpp(372) in wxWindowBase::CreateBase(): invalid id value
```

**Comment by braymp** [comment]
I've not seen this personally, but one of the users here reported this behavior; closing the "eyes" solved it for him.

Googling brought up some possible details: http://trac.sasview.org/ticket/448

**Comment by mcquin** [comment]
Interesting. We should see if wxIDs are being generated even if a user has the display turned off. Perhaps some GUI object is being instantiated unnecessarily?

**Comment by mcquin** [comment]
> If you just re-enter test mode and try again, it fails again with the same error at the exact same point in the pipeline (n=3)
> If you save and close the pipeline and reboot CellProfiler, it proceeds fine (n=2).

@bethac07 what is n?

**Comment by bethac07** [comment]
n=number of times observing that behavior.  Sorry!

**Comment by AetherUnbound** [comment]
All your comments make perfect sense in corroborating @braymp's search result - WX is likely running out of object IDs for new UI objects. @bethac07, have you noticed this running headless or is it always in test mode?

**Comment by bethac07** [comment]
I've never noticed it in headless, but it is sometimes in GUI analysis mode (not GUI Test mode).

**Comment by biofisherman** [comment]
Today, I also met this message run on MacBook when running 72 samples, but no error when running 24. Any solution yet? CellProfiler version: 3.1.5

**Comment by bethac07** [comment]
72 samples is a pretty small sample size to run into it- have you tried closing all the "eyes"?

**Comment by biofisherman** [comment]
> 72 samples is a pretty small sample size to run into it- have you tried closing all the "eyes"?

I just noticed I was using old version and it was fixed in the latest one.

Thanks.

**Comment by bethac07** [comment]
It lives again- #4264
