### ISSUE TITLE
include citation data

### ISSUE THREAD

**Issue by katrinleinweber** [CellProfiler/CellProfiler#3480]
After @AnneCarpenter's [recent tweet](https://twitter.com/DrAnneCarpenter/status/959572868840423424) I wondered whether following [Robin Wilson's advice to include `CITATION` files](http://blog.rtwilson.com/Encouraging-Citation-of-Software-Introducing-Citation-Files) might help reduce the number of publications that _only_ mention "CellProfiler" in the text.

How about copy-ing the citations from http://cellprofiler.org/citations/ into this repository, with BibTeX snippets for easy reference manager imports? I can send a PR if you want.

Aside from that, are you aware of [GitHub's Zenodo integration to assign DOIs](http://guides.github.com/activities/citable-code) to [releases](https://github.com/CellProfiler/CellProfiler/releases)?

**Comment by bethac07** [comment]
Hi,

RE: Citations, that's definitely something we've thought about in the lab!  It's in my medium-term to-do list.  I think a PR would likely be quite welcome.

**Comment by AnneCarpenter** [comment]
I'm really a novice about all this so we would very much appreciate guidance! Thanks, @katrinleinweber !

**Comment by katrinleinweber** [comment]
You're welcome :-)

So, "all this" is basically just including the BibTeX snippet(s) to make import convenient of the citation metadata more convenient. Eventually, this should replace manually putting together some text snippet, but have those generated from a defined set of authoritative metadata.

There are other, machine-readable formats, as well: [codemeta](http://codemeta.github.io/) and [CFF](https://citation-file-format.github.io/) and a [Software Citation Implementation Working Group](https://github.com/FORCE11/FORCE11-sciwg) :-)
