### ISSUE TITLE
Problem running CP 3.0 within conda environment- OSX

### ISSUE THREAD

**Issue by jstitlow** [CellProfiler/CellProfiler#3482]
Hello,

'pythonw cellprofiler'
 
Returns the following error:
//anaconda/envs/cellprofiler/bin/python: can't find '__main__' module in 'cellprofiler'

Installation using environment.yml appeared to go well. Also added the BFJohansson wxpython patch.

FYI, running `pythonw cellprofiler` from home directory gives this error: 
//anaconda/envs/cellprofiler/python.app/Contents/MacOS/python: can't open file 'cellprofiler': [Errno 2] No such file or directory

By navigating to //anaconda/.../MacOS and running 'python cellprofiler' I get the can't find '__main__' error. Should it be necessary to run the environment from within a specific directory?

System
OSX 10.12.4

Any ideas?
Many thanks for your time!
Josh

**Comment by jstitlow** [comment]
Joshs-MBP-3:~ joshtitlow$ source activate //anaconda/envs/cellprofiler
(//anaconda/envs/cellprofiler) Joshs-MBP-3:~ joshtitlow$ pythonw cellprofiler
//anaconda/envs/cellprofiler/python.app/Contents/MacOS/python: can't open file 'cellprofiler': [Errno 2] No such file or directory

Sorry I wasn't clear, thanks for the help!
j

[CP3_installation_trace.txt](https://github.com/CellProfiler/CellProfiler/files/1696816/CP3_installation_trace.txt)

**Comment by jstitlow** [comment]
Joshs-MBP-3:~ joshtitlow$ cd //anaconda/envs/
Joshs-MBP-3:envs joshtitlow$ source activate //anaconda/envs/cellprofiler
(//anaconda/envs/cellprofiler) Joshs-MBP-3:envs joshtitlow$ pythonw cellprofiler
//anaconda/envs/cellprofiler/bin/python: can't find '__main__' module in 'cellprofiler'
(//anaconda/envs/cellprofiler) Joshs-MBP-3:envs joshtitlow$

**Comment by mcquin** [comment]
Hey @jstitlow thanks for the extra information. I noticed that you're not executing `pythonw cellprofiler` from the CellProfiler source directory. Could you please navigate to the root of the source directory and run the command there?

**Comment by jstitlow** [comment]
Same problem when running from root. 

Also tried re-installing with pip:

$ git clone https://github.com/CellProfiler/CellProfiler.git $HOME/CellProfiler
$ pip2 install --editable $HOME/CellProfiler

$ pythonw cellprofiler
//anaconda/bin/python: can't find '__main__' module in 'cellprofiler'

**Comment by jstitlow** [comment]
Solved. 

You're right, was executing `pythonw cellprofiler` from //anaconda/envs/ instead of //anaconda/bin/. Also had the wrong wxpython because I installed it after creating the environment. 

Sorry about that. 
Thanks!
j

**Comment by mcquin** [comment]
No problem. I'm glad you were able to get CellProfiler running. :)

Is there any ambiguity we can clear up in the installation documentation?
