### ISSUE TITLE
MeasureObjectSizeShape should show the correct dimensional descriptors for its measurements

### ISSUE THREAD

**Issue by AetherUnbound** [CellProfiler/CellProfiler#3489]
For 2D images it currently displays area/perimeter. 
For 3D volumes it should display volume/surface area, etc. 

Mentioned by @derekthirstrup

**Comment by mcquin** [comment]
Modules which require updates:

- [ ] MeasureImageAreaOccupied
- [ ] MeasureImageQuality
- [x] MeasureObjectSizeShape
