### ISSUE TITLE
MeasureObjectIntensityDistribution should have option to place overflow bin in the center or the edge

### ISSUE THREAD

**Issue by hajaalin** [CellProfiler/CellProfiler#3494]
An overflow bin appears when user chooses not to scale the bins and specifies the maximum bin radius. Currently the first bin is in the center and the overflow bin is on the edge. The proposed feature would allow to reverse this order, to measure rings of fixed radius on the object perimeter. 

One of our customers needed this feature, so I made an initial version. Here are some screen captures:
https://wiki.helsinki.fi/display/LMU/CellProfiler+MeasureObjectIntensityDistribution

**Comment by mcquin** [comment]
Interesting @hajaalin! Are you able to share your initial version with us? We can work with you from there to incorporate this feature properly into CellProfiler.
