### ISSUE TITLE
Problem Initiating Cellprofiler headless

### ISSUE THREAD

**Issue by StevenRemington** [CellProfiler/CellProfiler#3497]
I am trying to run cellprofiler 3.0 headless from a java program using the command

“C:/Program Files (x86)/CellProfiler/CellProfiler.exe” -c -r -i C:/Users/Steven/Desktop/Batch/BuyoutTemp/ -o C:/Users/Steven/Desktop/Research/output -p C:/Users/Steven/Desktop/Research/Pipelines/Configuration/Config.cppipe

contained in a batch file on windows 10 Home 64-bit

when ran from standard command line, the command runs successfully with no issues. However, if i run it in an empty java project, shown below, two cell profiler instances are created but don’t pull any CPU until i manually kill the java program. Is there a reason that Cell Profiler would not run a pipeline if a parent java object is running.

```package source;
import fileutil.CSVUtil;
import fileutil.CommandUtil;
import java.io.IOException;

public class Entry{
    public static void main(String args[]){
	    try {
            Process process = Runtime.getRuntime().exec(
               "C:\\Users\\Steven\\Desktop\\Research\\CellProfilerWrapper\\Pipelines\\Configuration\\runme.bat"
            );
           process.waitFor();

        }
        catch(Exception e) {
           System.out.println(e);
        }
    
    }
}
```

**Comment by AetherUnbound** [comment]
This seems to me to be more of a Java question than a CellProfiler question. Can you one of the solutions proposed in this SO question rather than `waitFor`? https://stackoverflow.com/questions/15199119/runtime-exec-waitfor-doesnt-wait-until-process-is-done

**Comment by StevenRemington** [comment]
The waitFor() doesn't change the behaviour of the program. I have also used 
```
while(process.isAlive()){}
```
and even started the process in a new separate thread. In addition to this, I have also tried to run the command directly via the Process.
```
new Thread(){
    @Override
    public void run(){
        Process process = Runtime.getRuntime().exec( 
        "C:\\Users\\Steven\\Desktop\\Research\\CellProfilerWrapper\\Pipelines\\Configuration\\runme.bat"
            );
    }
}.start();
while(true){}
```
In all cases Cell profiler appears as a running process, runs for a short period of time, then stops pulling CPU cycles until the parent java process is killed. Once the parent java process is killed, Cell profiler finished the pipeline with no errors.  

Because the Cell profiler instance boots up and then stops, it seems to me that the waitFor() is not the issue or else the executable wouldn't pull cpu cycles for almost a full minute before stopping.

**Comment by AetherUnbound** [comment]
Ahh I see, thanks for that extra elaboration. Do you mind altering the command of `exec` to be `cmd /c <path-to-your-bat>` and seeing if that changes anything?

**Comment by StevenRemington** [comment]
Same behavior, the Cell profiler started up, then stopped pulling CPU cycles, have around 256 MB of memory, an no disk activity after the initial startup.

**Comment by popiel** [comment]
My best guess, looking at that, is that the cellprofiler process is creating some output on either stdout or stderr which the parent process isn't consuming, and thus the child process is getting stalled based on buffers getting full.  From the documentation of the Process object (created by Runtime.exec):

**Comment by StevenRemington** [comment]
That fixed the issue! Thank you for the help!
