### ISSUE TITLE
CalculateMath should support 3D

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3499]
It just does math on measurements that are per-image or per-object, it shouldn't be anything 2D or 3D specific in it... I think?

**Comment by braymp** [comment]
What if you try to mix-and-match 3D-specific measurements with 2D-specific measurements?

**Comment by bethac07** [comment]
I'm not entirely sure what you mean, but-

* You can't add 2D-only modules to a 3D pipeline (CP won't let you)
* In the end, it's all just measurements at that point, right?  Why should it "care" if the measurement it's multiplying, adding, etc is 2D or 3D ?

**Comment by braymp** [comment]
I think I was thinking of measurements coming from 3D data loaded as 2D slices mixed with measurements from 3D volumes. But you're right: it's all numbers at the end.
