### ISSUE TITLE
conda environment.yml needs scikit-image>=0.13 for ImageMath Invert

### ISSUE THREAD

**Issue by Swarchal** [CellProfiler/CellProfiler#3502]
I didn't want to edit the wiki, but after installing with conda using the example environment.yml file, I had issues trying to invert an image with ImageMath.

![cellprofiler_error](https://user-images.githubusercontent.com/10051679/36307190-f2a08730-1312-11e8-94d5-14dd12c6d93b.png)

After some snooping turns out my scikit-image version was 0.12.3 which doesn't have the `skimage.util.invert` function. After upgrading to 0.13 it works fine.

**Comment by AetherUnbound** [comment]
Thanks for bringing this up! I've edited the wiki to pin the version.
