### ISSUE TITLE
RescaleIntensity failing: The truth value of an array with more than one element is ambiguous

### ISSUE THREAD

**Issue by lauracmurphy** [CellProfiler/CellProfiler#3506]
From the forum http://forum.cellprofiler.org/t/value-error-the-truth-value-of-any-array-with-more-than-one-element-is-ambiguous/5692/2
 
I've reproduced it with the stable release and when built from source, error below happens for all three channels. Possibly related to fact that all images have a lot of zero intensity values?

Error message:
Error while processing RescaleIntensity:
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Pipeline and Dropbox link to images 
https://github.com/CellProfiler/CellProfiler/files/1741389/Value.error.pipe.cppipe.zip
https://www.dropbox.com/sh/qr0u58wdkiiqsi3/AAAF79lotBTR7lflgfchkQ3ja?dl=0

**Comment by DavidStirling** [comment]
So it turns out this happened because the input images were declared as colour images and rescale expected greyscale. Since they're just single-channel colour images, declaring them as greyscale or splitting them works fine, for CP4 we'll have a proper way of handling this.
