### ISSUE TITLE
Windows source Installation instructions are out-of-date on the wiki

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3511]
It's leading to confusion for at least one user on a [CPA issue](https://github.com/CellProfiler/CellProfiler-Analyst/issues/247#issuecomment-369279880) (which is crossposted to the [forum](http://forum.cellprofiler.org/t/apply-classifier-model/5687/3) ).

**Comment by DavidStirling** [comment]
Instructions should now be functional for CP4
