### ISSUE TITLE
"Home" button on matplotlib viewer doesn't reset the windows, only actually goes "back"

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3527]
Observed in a tutorial for 3.0.0, Mac OS High Sierra v. 10.13.3.

**Comment by AetherUnbound** [comment]
I'm (unfortunately) unable to replicate this on Ubuntu 16.04 :cry:

**Comment by bethac07** [comment]
Yeah, I can't replicate it on Windows either, appears to be Mac specific.

**Comment by DavidStirling** [comment]
We can't replicate this on Mac in 3.1.9 either. CP4's matplotlib version will also be substantially newer. Feel free to re-open this if it returns.
