### ISSUE TITLE
DisplayDataOnImage np error

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3541]
When trying to run the pipeline and image sets below (H/T the [forum](http://forum.cellprofiler.org/t/cp3-3-0-error-with-overlayoutlines-and-displaydataonimage/5929/2)) in 3.0.0 or 3.1.3, the following error is encountered.  From my testing it doesn't matter which image you choose to display data on, or even if you say you want no background image at all.  The pipeline works just fine in 2.2, and the relevant line hasn't been changed in 2 years according to the module blame, so I assume this is something to do with changes to numpy.  At that, we've reached my end of troubleshooting ability.

```
Failed to run module DisplayDataOnImage
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 2888, in do_step
    self.__pipeline.run_module(module, workspace)
  File "cellprofiler\pipeline.py", line 2031, in run_module
    module.run(workspace)
  File "cellprofiler\modules\displaydataonimage.py", line 296, in run
    mask = ~(np.isnan(values) | np.isnan(x) | np.isnan(y))
ValueError: operands could not be broadcast together with shapes (1029,) (1023,)
```

[DisplayDataOnImage.zip](https://github.com/CellProfiler/CellProfiler/files/1869689/DisplayDataOnImage.zip)

**Comment by AetherUnbound** [comment]
This looks to be a mismatch between the number of objects (1029), and the number of calculated centers (1023), so I think this issue might be further upstream from the DisplayDataOnImage module

**Comment by AetherUnbound** [comment]
I've updated the forum post regarding this fix (travis is still failing due to the cache error we're addressing).

**Comment by bethac07** [comment]
So digging into this, you were 100 percent right about the issue being further upstream.  In this pipeline, primary objects can be of any size, and there are 1041.   The number of secondary objects SHOULD equal the number of primary objects, and the number of indices do, but even when I turn filtering off in ISO it tells me there should be 1041 labels but it only has 1035 centers. 

It appears to only happen when you turn on the hole filling setting- when hole filling is off, you start with 1098 labels (before you do a filtering step), then after filtering end up with 1041; when you have hole filling on, you have 1098 labels, then after hole filling you somehow only have 1086, which after filtering gives you 1035.  The bug is therefore likely somewhere in https://github.com/CellProfiler/centrosome/blob/master/centrosome/cpmorphology.py#L33 .  My guess is that this is also what's causing #3645

**Comment by bethac07** [comment]
Based on what I tracked down in #3645 yesterday, it seems likely to me that what's happening is that the centrosome fill_holes is obliterating some tiny objects.  There, it was helping and desired; here, it's causing problems.

**Comment by DavidStirling** [comment]
I can't seem to replicate this in 3.1.9 using the attached pipeline from the original post. Is it possible that this is fixed?

**Comment by DeboraOlivier** [comment]
![image](https://user-images.githubusercontent.com/52743133/91836937-c2048580-ec4b-11ea-8d65-5187bb5ab0bd.png)
I have this same error now regularly on my IdentifySecondaryObjects in TEST mode.

I generate the primary object labels together with the original images on Linux (UNET) - transfer the data (both images and UINT16 object label) on the PC to perfomr IIary Object detection and the rest. So I know it should not be a mismatch between label and original image.
I don't get the error if I run test mode on the first image group, but if I select another image to test the pipeline on, I get the error message quite often - or it overlays the wrong objects on the image

doesn't seem to impact analysis as I get the correct output from the pipeline if I do "Analyze all".
Note @DavidStirling has some images and I attached the pipelines used and the images
[_OpenGitHubIssues - Google Docs.pdf](https://github.com/CellProfiler/CellProfiler/files/5156693/_OpenGitHubIssues.-.Google.Docs.pdf)
