### ISSUE TITLE
SaveCroppedObjects should change the file type to save disk space

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#3544]
Currently SaveCroppedObjects saves each object mask as a 8-bit TIFF. The storage overhead to create cropped objects can be orders of magnitude greater than the original size (approximately the number of objects in an image X the size of the image) of the image set being processed. I have run out of disk space several times due to this demand. Preferably, the object masks would be saved as a binary image.

**Comment by bethac07** [comment]
A single binary image? You can already do this by doing "ConvertObjectsToImage" and "SaveImages"; I'm not sure we want to fully duplicate that functionality within SaveCroppedObjects.

**Comment by karhohs** [comment]
Hi @bethac07! I think the behavior with the TIFF files is specific to the SaveCroppedObjects module. An example of the issue is if I wanted to create masks and my image set was 100MB, I'd end up with 10GB worth of masks.

**Comment by bethac07** [comment]
Resolved by #3545
