### ISSUE TITLE
savecroppedobjects filename should be customizible

### ISSUE THREAD

**Issue by vidprijatelj** [CellProfiler/CellProfiler#3549]
Hi,
I have an issue I am trying to solve.
Given a large image set upon which I identify primary objects, I also save corresponding masks for these objects. The issue at hand is the naming schema for the masks...
e.g.
I have 6,528 (16 rows by 24 columns by 17 positions per well) images of cell nuclei, where in every image there is an average of 18 nuclei. Summa summarum I have 117,504 masks of cell nuclei I wish to save.
The algorithm upon which filenames for these masks are set is given on lines 76-86 of the savecroppedobjects.py module i.e. `self.objects_name.value, label, int(time.time())`. When all the 117,504 images of masks are saved, there is no possible way to identify which subset of masks belongs to a specific image, since the program, apparently, does not save files sequentially (the first mask image of cell nuclei, a primary objects, to be saved does not necessarily belong to the first image loaded in "Images" module). 
Therefore I am left with a plethora of images of masks, named apparently randomly, that I cannot pair with their original image.

Is there a way to customize a naming schema for the savecroppedobjects outside of me changing the very module itself? Otherwise it'd be much easier for me to use opencv2...

Thank you.

Yours sincerely,
vidprijatelj

**Comment by karhohs** [comment]
Hi @vidprijatelj, if you save the masks to a subfolder, you can use filename metadata to create a unique folder for each set of masks that correspond to each image. Have you already tried doing this? Thanks!

**Comment by npitsillos** [comment]
I dont't think this is what the previous person means here.  When you use ConvertImageToObjects then you need to use SaveCroppedObjects and here you don't have the option to customise the name which ends up being very labour intensive if there many images.
