### ISSUE TITLE
 failure to import: cellprofiler.modules.measureimageareaoccupied

### ISSUE THREAD

**Issue by Palashio** [CellProfiler/CellProfiler#3551]
I am trying to programatically use CellProfiler 3.1.3.
import cellprofiler.modules.measureimageareaoccupied

Throws the following exception in copy.py and I am unable to proceed further
Error("un(shallow)copyable object of type %s" % cls)

Cellprofiler was installed in a dedicated environment as per instructions on Windows 10 + Visual Studio 2017 - https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation.

The same error occurs when I try it from outside Visual Studios, even from python prompt.

**Comment by AetherUnbound** [comment]
Do you mind posting the full stack trace?

**Comment by Palashio** [comment]
@AetherUnbound 
task42.py has a single line.

import cellprofiler.modules.measureimageareaoccupied


copy in copy line 94
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\copy.py(94)
<exec or eval> line 10
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\Lib\site-packages\cellprofiler\<string>(10)
cElementTree module line 3
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\xml\etree\cElementTree.py(3)
omexml module line 15
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\site-packages\bioformats\omexml.py(15)
formatwriter module line 44
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\site-packages\bioformats\formatwriter.py(44)
__init__ module line 23
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\site-packages\bioformats\__init__.py(23)
pipeline module line 49
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\site-packages\cellprofiler\pipeline.py(49)
module module line 12
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\site-packages\cellprofiler\module.py(12)
__init__ module line 14
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\lib\site-packages\cellprofiler\modules\__init__.py(14)
task42 module line 1
 at C:\Users\P\AppData\Local\conda\conda\envs\cellprofiler\Lib\site-packages\cellprofiler\task42.py(1)

**Comment by AetherUnbound** [comment]
Hmm, I'm not able to reproduce this in my environment. Do you mind posting the result of `pip freeze` in whatever environment you're using to run this?

**Comment by Palashio** [comment]
@AetherUnbound 

pip freeze

alabaster==0.7.10
appdirs==1.4.3
asn1crypto==0.24.0
attrs==17.4.0
Babel==2.5.3
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.lzma==0.0.8
backports.shutil-get-terminal-size==1.0.0
bleach==2.1.3
bokeh==0.12.15
boto3==1.7.4
botocore==1.10.4
cellh5==1.3.0
CellProfiler==3.1.3
centrosome==1.0.9
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
cryptography==2.0.3
cycler==0.10.0
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.2
decorator==4.3.0
distributed==1.21.6
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
h5py==2.7.1
heapdict==1.0.0
hmmlearn==0.2.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imagesize==1.0.0
inflect==0.2.5
ipaddress==1.0.22
ipykernel==4.8.2
ipython==5.6.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
javabridge==1.0.15
Jinja2==2.10
jmespath==0.9.3
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
locket==0.2.0
lxml==4.2.1
mahotas==1.4.4
MarkupSafe==1.0
matplotlib==2.2.2
mistune==0.8.3
mkl-fft==1.0.0
more-itertools==4.1.0
msgpack-python==0.5.6
MySQL-python==1.2.5
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.3.1
numpy==1.14.2
olefile==0.45.1
packaging==17.1
pandas==0.22.0
pandocfilters==1.4.2
partd==0.3.8
pathlib2==2.3.0
pickleshare==0.7.4
Pillow==5.1.0
pluggy==0.6.0
prokaryote==2.3.2
prompt-toolkit==1.0.15
psutil==5.4.5
py==1.5.3
pycparser==2.18
Pygments==2.2.0
pyOpenSSL==17.4.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.5.0
python-bioformats==1.3.1
python-dateutil==2.7.2
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==15.3.0
qtconsole==4.3.1
raven==6.6.0
requests==2.18.4
s3transfer==0.1.13
scandir==1.7
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.0.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcontainers==1.5.9
Sphinx==1.7.2
sphinxcontrib-websupport==1.0.1
tblib==1.3.2
testpath==0.3.1
tifffile==0.14.0
toolz==0.9.0
tornado==5.0.1
traitlets==4.3.2
typing==3.6.4
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.2.1
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wxPython==4.0.1
zict==0.1.3
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by AetherUnbound** [comment]
Unfortunately, I'm unable to recreate this issue on my Linux machine, even when recreating your environment. @bethac07, any chance you might be able to try this on your machine?

**Comment by DavidStirling** [comment]
I'm unable to replicate this with the current master branch on Windows 10. Dependencies have also changed for Python 3 so it may just be fixed. Feel free to re-open this if the problem returns in CellProfiler 4.
