### ISSUE TITLE
Feature request: circularity

### ISSUE THREAD

**Issue by caticoa3** [CellProfiler/CellProfiler#3553]
Great tool. It would be nice to extract or measure circularity as a feature from objects for subsequent use in a pipeline.

circularity = 4pi(area/perimeter^2)

**Comment by braymp** [comment]
By your formula, this is already captured by [MeasureObjectAreaShape](http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.0.0/modules/measurement.html#measureobjectsizeshape) as the Form Factor readout.

**Comment by caticoa3** [comment]
Thanks for link; I see that *eccentricity* is the measurement I was looking
for. Thank you.
