### ISSUE TITLE
Difficulty running pipeline using command line interface

### ISSUE THREAD

**Issue by caticoa3** [CellProfiler/CellProfiler#3554]
Hi,

First off thank you for the time and effort that goes into CellProfiler.

I'm trying to run a pipeline which I can successfully run using the GUI. I exported the image list (exported_image_list.csv) and pipeline (IC_pipeline_DAPI_GFAP_1.cppipe).
Now I would like to process many more images and try to integrate with Python and command line. I tried running the pipeline from the command line but didn't have much luck:  

$ cellprofiler -p IllumCorr/IC_pipeline_DAPI_GFAP_1.cppipe --data-file=exported_image_list.csv -r

error: CP-JAVA 00:07:15.006 [Thread-0] WARN  o.c.imageset.ChannelFilter - Empty image set list: no images passed the filtering criteria.

The error that appears in the GUI after executing the command:
"Cannot run pipeline
The pipeline cannot be started because of
a configuration problem:
The pipeline did not identify any image sets.
Please correct any problems in your input module settings
and try again."

Any suggestions or help would be appreciated

Best

PS - Im working on Ubuntu16.04 and installed cellprofiler using conda as described in the wiki.

**Comment by AetherUnbound** [comment]
Hello @caticoa3! Do you mind trying the `--file-list` flag rather than the `--data-file` flag? I believe that `--data-file` is for use in the LoadData module only.

**Comment by AetherUnbound** [comment]
@caticoa3 Ha! I'm glad that `--file-list` (sort of) worked! We'll try to improve our documentation there, I got confused myself :)
But just to be clear, the `--file-list` command still does not run your pipeline?

**Comment by caticoa3** [comment]
That is correct. When I used the --file-list command the pipeline did not run.

**Comment by caticoa3** [comment]
Good news. I had more success creating a batch, .h5, file and running headless from command line:

As described in the [manual](http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.0.0/help/other_batch.html?highlight=headless) I added the CreateBatchFile module to the end of my pipeline, created the .h5 batch file, and ran Cell Profiler locally on my computer as indicated in step 7, even though I am working locally and not submitting to a remote cluster. 

$ cellprofiler -p <location of Batch_data.h5> -c -r -f <image set number to start processing>

Now, the problem I am running into is that cell profiler stops processing when it attempts to save a blank image. 
"Error detected during run of module SaveImages...
...ValueError: zero-size array to reduction operation minimum which has no identity"

I searched for flags in the cellprofiler --help but none are available for ignoring save errors. Is there a way to ignore skip to the next image and continue processing? 
When this error occurs in the GUI I hit cancel and processing continues.

**Comment by caticoa3** [comment]
To continue processing I wrote while loop in a shell script. I scraped together a regex expression to parse the Image Set at which the error was occurring and then restart CellProfiler at the next image. I'm sure it can be done more elegantly. Not sure if this will help others but here it is:

`#!/bin/bash
n=825 #Image Set number to start processing batch
final_image=826 #Last Image Set number in your batch
cellprofiler -p ML/Batch_data.h5 -c -r -f $n -l $final_image |& tee log.txt #Here the output from terminal is save to log.txt. This is then parsed for the image set number at which the error occurs.

while [ $? -ne 1 ]; do
    #Extract the image set # at which the error occurs
    no_save_error_image=$(sed -n '/^.*ValueError:/{n;p}' log.txt | sed -n -e 's/^.*Image # //p' | sed -n -e 's/, module SaveImages.*$//p')
    n_=$(($no_save_error_image + 1))
    #Restart CellProfiler at the next image set
    echo 'Restarting at Image set #' $n_ 
    cellprofiler -p ML/Batch_data.h5 -c -r -f $n_ -l $final_image |& tee log.txt
    #Once the final image set is reached stop the script
    if ((n_==$final_image)); then
       echo 'The last image set #:' $n_', has been processed. All images have been processed. The script will now exit.' 
       break
    fi
done 
`

**Comment by AetherUnbound** [comment]
Wow @caticoa3, way to be resourceful! I'm sorry that this has continued to cause you trouble. I'm going to try and take some time to look into it, although this does look like two separate issues. Thanks for bringing your solution back here!
