### ISSUE TITLE
Restore human-readability of .cppipe files

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3562]
In general the changes in UTF (#3515) seem to be working well, but one casualty is that the .cppipe files are no longer human readable (compare L vs R below).  Most users of course won't notice this, but for advanced users who like to read and/or hack the .cppipe files in a text editor, that option now no longer works.  If it's impossible to serve both uses, I think it's definitely more important to keep things the way they are, but if there's a way to rely on stock UTF encoding while still maintaining human readability it'd be nice to have.

![image](https://user-images.githubusercontent.com/6721515/39767201-2ecbf7cc-52b4-11e8-961f-b08f883e808e.png)

**Comment by jburel** [comment]
We do not work with local files and use the ``InjectImage(imageName, data)`` module to inject the 2D-plane extracted from a 5D image stored in an OMERO server.
We were relying on the value of the ``Select the input image`` field to set the imageName 
e.g. using ExamplePercentPositive.cppipe
```
# Name of the channel expected in the pipeline
 if c == 0:
    image_name = 'OrigBlue'
 if c == 1:
   image_name = 'OrigGreen'
```
This approach no longer works for newly created pipeline

Any progress on the issue?

**Comment by DavidStirling** [comment]
Pipeline format will be changed to JSON in CellProfiler 4, which should resolve this issue.

**Comment by jburel** [comment]
What is the timeline for version 4?

**Comment by DavidStirling** [comment]
The aim is ideally to release in time for Python 2's end of life, which should be in April.
