### ISSUE TITLE
Build dependencies from source 

### ISSUE THREAD

**Issue by lguerard** [CellProfiler/CellProfiler#3564]
Crosspost from the [forum](http://forum.cellprofiler.org/t/build-dependencies-from-source/6054)

> Hi all,
> 
> As discussed with @chris-allan and @sbesson on the post Connection to OMERO reset?, in order to make CellProfiler working with newest version of OMERO, some of its dependencies (and I believe Prokaryote should be the only one) need to be built from source with the correct version of OMERO.
> 
> Is there any wiki or info about how to do that ? This would allow people to do it on their own depending on the OMERO version they have and avoid either the OME people or the CellProfiler to have to do it and distribute it.
> 
> Thanks for the help.
>

**Comment by AetherUnbound** [comment]
@0x00b1 does any of your recent work on prokaryote address this?
