### ISSUE TITLE
CellProfiler Analyst not displaying object thumbnails after ExportToDatabase

### ISSUE THREAD

**Issue by bgriffen** [CellProfiler/CellProfiler#3572]
This might be hard to somewhat diagnose but I've found that CPA (latest, 2.0) can not load thumbnails of a CP (v3.1.2) run. I'm working on Ubuntu. I load the properties file and go to the classify module and after running "Fetch 20 random cells from experiment" I get the following:

```
INFO:root:Fetched 20 random cells from whole experiment
INFO:root:20 is greater than the number of objects. Fetching 0 objects.
```
Here is a screenshot of the pipeline:

![part1](https://user-images.githubusercontent.com/2667869/40085756-684ac4a0-5850-11e8-90ff-64213055821d.png)

![part2](https://user-images.githubusercontent.com/2667869/40085757-686d214e-5850-11e8-85d9-a088f812ecc9.png)

Here is the output properties file.

```bash
db_type         = sqlite
db_sqlite_file  = /home/user/t/04_CPrr/cpa.db
image_table   = Per_Image
object_table  = Per_Object
image_id      = ImageNumber
object_id     = ObjectNumber
plate_id      = 
well_id       = 
series_id     = Image_Group_Number
group_id      = Image_Group_Number
timepoint_id  = Image_Group_Index
cell_x_loc    = Nuclei_Location_Center_X
cell_y_loc    = Nuclei_Location_Center_Y
image_path_cols = Image_PathName_CHAN1,Image_PathName_CHAN2,Image_PathName_CHAN3,Image_PathName_CHAN4
image_file_cols = Image_FileName_CHAN1,Image_FileName_CHAN2,Image_FileName_CHAN3,Image_FileName_CHAN4
image_thumbnail_cols = 
image_names = CHAN1,CHAN2,CHAN3,CHAN4
image_channel_colors = 
image_url_prepend = 
object_name  =  cell, cells,
plate_type  = 
classifier_ignore_columns  =  table_number_key_column, image_number_key_column, object_number_key_column
image_tile_size   =  50
image_size =
classification_type  = 
training_set  =
area_scoring_column =
class_table  = classified
check_tables = yes
```

I loaded my cpa.db file into DB Browser for SQLite and found that the objects do exist, the path exists for Image_PathName_CHAN1 etc. as well as the appropriate Image_FileName_CHAN1 etc. 

![part3](https://user-images.githubusercontent.com/2667869/40085810-9818eef0-5850-11e8-9003-81861a5fdc55.png)

The only issue might be that the filenames are quite long (68 characters, path+filename is 97 characters). Inside the SQLite viewer though, the pathnames and filenames appear correct. Before I dive in deeper, would this be the cause of the fact that no thumbnails are being displayed? I think perhaps the bigger issue is that no objects are found. Also, when I go to the ImageGallery module, I can load "images from experiment" no problem.

I do get these warnings when starting up CPA:

```
DEBUG:matplotlib:CACHEDIR=/home/user/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/user/.cache/matplotlib/fontList.json
DEBUG:matplotlib.backends:backend WXAgg version unknown
INFO:root:No PIL.ArgImagePlugin
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

I thought it was the current ExportToDatabase module so I tried an earlier version of CP (v3.0.0) but I still see the same issue. Any suggestions greatly appreciated..

**Update:** I just tried with a shorter filename with no luck. Also I will say this CellProfiler Analysis is opened by simply cloning the repo and running `python CellProfiler-Analyst.py` in the same conda environment that runs CellProfiler. It does load the thumbnails of the example CellProfiler dataset.
**Update 2:** The same pipeline works on CP and CPA on my Mac (that is running CP 3.0.0) and works just fine.

**Comment by bethac07** [comment]
Can you provide your pipeline and a couple of image sets?  What branch of CPA are you using, master? Stable?
Since you say it works on Windows and Mac, can you try making running CP on one of those then running CPA on Ubuntu, and vice versa? Trying to see if it's CP not writing the database properly or CPA not reading it properly.  Unless you manually update the path names or have identical paths you still won't see thumbnails, but look for the presence or absence of the "Fetching 0 objects" error message.

**Comment by bgriffen** [comment]
I am on the master branch of CellProfiler. I just took the db file and properties file generated on Ubuntu and loaded it in CellProfiler Analyst on my Mac no problem. In the properties file I edited db_sqlite_file and the PathName in the database file to point to the image folder. Then the images loaded in CellProfiler Analyst no problem. When I load the same properties file in ubuntu (on the same machine that actually generated the properties file and database) it doesn't load.

**Comment by bethac07** [comment]
If the files created in CP on Ubuntu work in CPA on other OS's, that sounds like an error in CPA on Ubuntu not in CP.  If you're not already using stable for CPA I'd try that, and if not I'd recommend making an issue on CPA.

**Comment by bgriffen** [comment]
I couldn't work out the source of my issue in the end so I built my own CPAnalyst tool. If no one else has had the issue then it must have been my specific setup causing the issue.

**Comment by DanielGrandis** [comment]
me too! I'm trying to load images for classifier after importing .db and .properties files generate from a Mac in a Windows 10 pc. I can load every image in Image gallery but it doesn't load thumbnails from classifier! Master version me too of the repository. Any suggestion?

**Comment by AnneCarpenter** [comment]
Sorry it is giving you trouble - we don't have so many experts left in the lab to answer usage Qs or diagnose things. 

However we are working with the Horvath lab and others around the world to make a deep learning-powered replacement for CPA's Classifier; the only problem is that it's very alpha stage: Try it here: https://application.cyto.ai (source code here: github.com/cytoai/cyto)
