### ISSUE TITLE
`Image set listing saved` even when not so

### ISSUE THREAD

**Issue by eldad-a** [CellProfiler/CellProfiler#3593]
Following the menu:

`File` -> `Export` -> `Image Set Listing...`

Even if the action is cancelled, that is, no file is saved, the window approving the save action pops-out 

![screenshot from 2018-06-19 14-52-15](https://user-images.githubusercontent.com/3859135/41626311-b241a7fe-73d0-11e8-9a14-bfddcfa63349.png)

**Comment by AetherUnbound** [comment]
I've been able to replicate this and I have a solution which I'll submit for review!
