### ISSUE TITLE
Anaconda cellprofiler installation (successful), yet Java error upon execution.

### ISSUE THREAD

**Issue by arcolombo** [CellProfiler/CellProfiler#3597]
Hello.
I am installing Cellprofiler using conda and successfully installed javabridge , prokaryote, dask, six, cython, ..., etc using conda.

this shows the successful installation: 
  `  blas                      1.0                         mkl  
     bokeh                     0.13.0                   py27_0  
    ca-certificates           2018.03.07                    0   
    cairo                     1.14.12              h77bcde2_0  
    cellprofiler              2.2.0            py36h1a8baa1_2    imperial-college-research-computing
`

I have java-JDK installed 
`
java-jdk                  8.0.92                        1    bioconda
javabridge                1.0.14                   py27_0  
`

however, when I run  `python2 cellprofiler` it  provides the below error:
     File "/home/arcolombo/.conda/envs/merchantLab/bin/cellprofiler", line 11, in <module>
    sys.exit(main())
  File "/home/arcolombo/.conda/envs/merchantLab/lib/python2.7/site-packages/cellprofiler/__main__.py", line 175, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/home/arcolombo/.conda/envs/merchantLab/lib/python2.7/site-packages/cellprofiler/utilities/cpjvm.py", line 3, in <module>
    import javabridge
  File "/home/arcolombo/.conda/envs/merchantLab/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/home/arcolombo/.conda/envs/merchantLab/lib/python2.7/site-packages/javabridge/jutil.py", line 155, in <module>
    import javabridge._javabridge as _javabridge
     ImportError: libjvm.so: cannot open shared object file: No such file or directory"

here is my system information: 

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Python 2.7.15 :: Anaconda, Inc.

Java is installed.

java -version
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)

I am not sure how to execute cellprofiler

**Comment by AetherUnbound** [comment]
Hello!
Do you have `libjvm.so` in any of these paths?
```
/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so
/usr/lib/jvm/jdk1.8.25/jre/lib/amd64/server/libjvm.so
/usr/local/java/jre1.7.0_75/lib/amd64/server/libjvm.so
```

**Comment by arcolombo** [comment]
this issue is resolved. sorry for the delay. but I did not have the java-oracle installed, and re-installing java fixed this error. this error is resolved!

Thank you very much.

**Comment by saskra** [comment]
I had the same problem and solved it with `conda install java-jdk`.
