### ISSUE TITLE
Right click contrast adjustment functionality is broken for 3D pipeline module windows

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#3603]
The right click functionality for adjusting image contrast in module display windows is not working for 3D pipelines.

**Comment by AetherUnbound** [comment]
This is because the `get_imshow_menu` is only called in the 2D figure displaying code path. The 3D path has a number of dissimilarities with the 2D path. This set of changes will largely be quite involved to implement.

**Comment by DavidStirling** [comment]
Contrast adjustment is now improved and also available on 3D figures.
