### ISSUE TITLE
Error: trackobjects.py line 2683

### ISSUE THREAD

**Issue by opnumten** [CellProfiler/CellProfiler#3609]
Hi,
I found the _dmax[ij]_ doesn't have the same index with _d_ in line2683. 
So I think in line 2666, it should be _i,j,dmax=i[mask],j[mask],dmax[mask]_.

Thank you.

**Comment by AetherUnbound** [comment]
Hi @opnumten! Thanks for bringing forward this issue. Do you have a minimal image set and pipeline that I can use to reproduce any error you're seeing? I can't tell from the code whether it should be what it is currently or your suggested edits.

**Comment by DavidStirling** [comment]
Unable to replicate this in 3.1.9, it's part of the LAP tracker but I've never encountered this problem at all. Please re-open this with further details if it recurs.
