### ISSUE TITLE
Crop

### ISSUE THREAD

**Issue by maydanw** [CellProfiler/CellProfiler#3612]
Doing image Crop have multiple issues:
1. In the reporting images, the cropped and the original are interchanged (see attached image)
2. Doing IdentifyPrimaryObjects over the cropped image is ignored and it is done over the original image (thus retaining the nucleus which are touching the borders even due it was instructed to remove them). 

Thanks

![cp crop issue](https://user-images.githubusercontent.com/1113021/43206567-b7c99ebe-902e-11e8-9e44-2a1da11b7522.png)

**Comment by AetherUnbound** [comment]
Thanks for reporting this @maydanw! Do you mind posting a zipped folder of your pipeline and images so we can confirm it?

**Comment by maydanw** [comment]
[Test-small2.zip](https://github.com/CellProfiler/CellProfiler/files/2230755/Test-small2.zip)

Attached is the project and two channels of an image.

The goal is to remove primary objects which are closer than _S_ px (for this example S=300px) to the image's borders (as they skew the measurements) by first cropping the image and search for primary objects in the cropped image which aren't touching the borders. Further, in the process, I would like to work with the resulted primary objects over the full-size images to extract the secondary objects (they can touch the borders as I know they should have the large majority of the information I need).
Currently, this test is falling at the beginning over finding primary objects over a cropped image.

I do hope you can help.
Thanks

**Comment by bethac07** [comment]
This is actually due to a misleading display issue- the pre-and-post crop are being forced to be at the same zoom level, so it looks like the nucleus was cut off in the pre-crop but it wasn't (see below).  See also #3387 


![b - 02 fld 01 wv dapi - dapi](https://user-images.githubusercontent.com/6721515/43340264-c8d855ac-91a9-11e8-937f-d9e2cb221bd7.png)
