### ISSUE TITLE
ExportToDatabase fails in 3.1.5 when object was made by filtering in IDSecondary

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3613]
In 3.1.5 on Mac (source or built) try running the following pipeline plus images (adapted from the [forum](http://forum.cellprofiler.org/t/exporttodatabase-error-not-json-serializable/6365) - was trying to see if user's error was fixed by simple 3.1.5 upgrade, found a new bug instead, which isolates this one to sometime since 3.0.0)- ExportToDatabase fails with the error below.  If you just set "Discard the associated primary objects?" in IDSecondary to "No", it proceeds, implying the error is the new primary object's name- which is a totally fair cell name, so there must be something about how the name of the new object is internally stored.

```
Failed to prepare run for module ExportToDatabase
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 2094, in prepare_run
    if ((not module.prepare_run(workspace)) or
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 2008, in prepare_run
    mappings = self.get_column_name_mappings(pipeline, image_set_list)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/exporttodatabase.py", line 2438, in get_column_name_mappings
    mappings.add("%s_%s" % (object_name, feature_name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

[Archive.zip](https://github.com/CellProfiler/CellProfiler/files/2233922/Archive.zip)

**Comment by bethac07** [comment]
I have an email from a user indicating this is also happening in ExportToSpreadsheet, and the lines in the error message imply it's also at the column name creation step.

**Comment by AetherUnbound** [comment]
I hate unicode :/ I'm sure these too are related
