### ISSUE TITLE
Indexing error in debug-mode when re-running the pipeline

### ISSUE THREAD

**Issue by lisalaux** [CellProfiler/CellProfiler#3616]
I am trying to build a module which can adjust some of the settings in previous modules.
I'm getting the old settings from the modules and set new ones by calling

```
 setting.set_value(new_setting) # change setting in one of the previous modules in my pipeline
 pipeline.edit_module(edited_module, is_image_set_modification=False) # tell pipeline that module was edited
```

This causes the pipeline to re-run from the module which was edited. 

A problem is caused in debug mode:
See  the method `def on_debug_continue` in `pipelinecontroller.py` 
The index is not re-set when the pipeline edit event is causing the pipeline to re-run. Accordingly, the debug execution runs into an indexing error producing the following traceback:

```
Traceback (most recent call last):
File “/Users/CellProfiler/cellprofiler/gui/pipelinecontroller.py”, line 2979, in on_debug_continue
wants_continue, wants_skip = dlg.Update(index, message)
File “/anaconda2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_windows.py”, line 3704, in Update
return windows.GenericProgressDialog_Update(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion “value <= m_maximum” failed at /BUILD/wxPython-src-3.0.0.0/src/generic/progdlgg.cpp(435) in Update(): invalid progress value
```

(To give an example, let’s say I have 27 modules in my pipeline, the module which changes previous settings is module no. 20.
When running the test mode, the pipeline executes until module no. 20. Then, module 20 changes settings in module no. 5. The pipeline will then automatically re-run, beginning from module no. 5. Problem: The overall counter is now already at module 25, meaning it is not executing the whole pipeline again but crashing at module no. 8 now, as the index has reached the max. no. of modules)

Is there any way to re-set the index of the debug mode when altering the settings so that re-running from the altered module can then execute the full remaining pipeline again? Is it probably a bug?

**Comment by AetherUnbound** [comment]
Huh, this is a very interesting way of interacting with the pipeline infrastructure! It's likely an index that's not being reset in the UI. Do you mind posting your pipeline, images, and the module you've written in a zip file for testing? If you wouldn't like to share the module publicly you can send it to me directly :)

**Comment by DavidStirling** [comment]
Please re-open if you're still having this issue.
