### ISSUE TITLE
ClassifyObjects module error - boolean indexing out by 1

### ISSUE THREAD

**Issue by mporter-gre** [CellProfiler/CellProfiler#3618]
We are building a small pipeline to identify primary objects, measure object intensity, measure object sizeshape and classify objects.

When running the ClassifyObjects module there is always an error stating, for example:

> boolean index did not match indexed array along dimension 0; dimension is 41 but corresponding boolean dimension is 40

For this particular image, 40 nuclei were identified as primary objects. Another image with 63 nuclei reports dimension 64. Is this an indexing from zero bug? This is version 3.1.5

Thanks,

Michael.

**Comment by AetherUnbound** [comment]
Hello @mporter-gre! Do you mind uploading a minimal pipeline and image set for producing this error? You can zip them together and upload them directly to GitHub. Thanks!

**Comment by hkhawar** [comment]
I am experiencing a same issue using ClassifyObjects module. I am trying to select cells which are positive for two fluorescent markers based on pair of measurements.

Error
boolean index didnot match indexed array along dimension 0; dimension is 734 but corresponding boolean dimension is 733

[pipeline.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/2625109/pipeline.cppipe.zip)

![screen shot 2018-11-28 at 9 47 17 am](https://user-images.githubusercontent.com/36200793/49159563-cc655300-f2f2-11e8-956e-7457f85775df.png)

**Comment by bnglt** [comment]
Hi! Exact same problem here, can't seem to figure out the reason... @hkhawar @AetherUnbound Have you had any luck solving it? I've uploaded my pipeline & test image giving me the error... Thank you!
Jana_V2.cpproj

**Comment by gabethornes** [comment]
Same here! Any help would be much appreciated. Thanks

**Comment by rkast1** [comment]
I am also still having this same issue. Is there any chance that we could get some help with it? Here's my pipeline and an image set.

**Comment by DavidStirling** [comment]
I know it has been a while, but if anyone is still having trouble the module actually still works in 3.0, it's just the display window that's broken. This will be fixed in 4.0, but for now a workaround is to turn off display by "closing the eye" during testing and analysis.
