### ISSUE TITLE
Potential bug in measureobjectintensity.get_measurement_images

### ISSUE THREAD

**Issue by jwindhager** [CellProfiler/CellProfiler#3622]
Looking through measureobjectintensity.py, I noticed something slightly odd/inconsistent:

`if object_name_variable == object_name:` (line 318)

Doesn't this always evaluate to False?

At multiple other locations in the file this condition is coded as follows:

`if object_name_variable.value == object_name:` (e.g. line 290, 303)

**Comment by AetherUnbound** [comment]
I think you may be right! I'll go ahead and change this. Thanks for noticing this @jwindhager!
