### ISSUE TITLE
Creating objects with RelateObjects should be optional, with default as no

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3623]
When the option to create output object sets was added in #3524 (which is awesome, don't get me wrong!), it was set to always do this- which breaks any pipeline from before that PR that had more than one RelateObjects modules (pretty common in complicated pipelines) because you now need to name all the new output object sets.  Considering in many use cases the user may not want/need the object set anyway and it will take up extra memory, my preference would be to still allow users to do it, but have it be optional and have the default be "No" (to preserve compatibility with pipelines from 3.0 and before).

**Comment by bethac07** [comment]
(I'm also sorry for not catching it before- I was traveling when the PR was submitted and pulled, and while I usually try to take a look at them even after the fact this one must've slipped my net!)

**Comment by AetherUnbound** [comment]
Dang, sorry that this is the case! I can definitely go back and make this an optional setting.

**Comment by AetherUnbound** [comment]
I think I have a fix for this (see the `issues/3623` branch), but I can't reproduce the initial issue. I've tried adding multiple `RelateObjects` modules to a pipeline but they don't seem to error out...do you mind providing a pipeline gives errors?

**Comment by bethac07** [comment]
Resolved by #3799 3799
