### ISSUE TITLE
ColorToGray decode error

### ISSUE THREAD

**Issue by lorrinlee** [CellProfiler/CellProfiler#3624]
Cellprofiler version is 3.1.5, and my OS is windows 10, can you help me?

<img width="492" alt="1533898216 1" src="https://user-images.githubusercontent.com/5257899/43954389-e7080f38-9cce-11e8-92d0-65aa27a56338.png">

**Comment by bethac07** [comment]
Hi,

Can you zip together and upload the pipeline and sample image(s) so we can reproduce?

**Comment by lorrinlee** [comment]
I have upload the pipeline and images, thanks
[cppipeandimage.zip](https://github.com/CellProfiler/CellProfiler/files/2279822/cppipeandimage.zip)

**Comment by bethac07** [comment]
Hi,

I've verified this issue and submitted a pull request for the fix- in the meantime, it's only a bug when the "eye" is open to display that module's output, so if you can work without seeing the output that's a good workaround for the short term.
