### ISSUE TITLE
Exception Fetching new version information error, similar to #496

### ISSUE THREAD

**Issue by arcolombo** [CellProfiler/CellProfiler#3625]
Hi.

 I am receiving an error similar to #496 

(Python2.7) C:\Users\Mohan\Documents\CellProfiler-2.2.0>cellprofiler
vigra import: failed to import the vigra library. Please follow the instructions on
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "c:\users\mohan\documents\cellprofiler-2.2.0\cellprofiler\modules\classifypixels.py", line 50, in <module>
    import vigra
ImportError: No module named vigra
vigra import: failed to import the vigra library. Please follow the instructions on
"http://hci.iwr.uni-heidelberg.de/vigra/" to install vigra
Traceback (most recent call last):
  File "c:\users\mohan\documents\cellprofiler-2.2.0\cellprofiler\modules\ilastik_pixel_classification.py", line 47, in <module>
    import vigra
ImportError: No module named vigra
Exception fetching new version information from http://cellprofiler.org/CPupdate.html: HTTP Error 404: Not Found
Failed to stop Ilastik
OnInit returned false, exiting...

Note this is in regard to cellprofiler 2.2.0.
 I can successfully install cellprofiler 3.0 without any errors, but can not install 2.2.0.

 I have ilastik installed 1.2.2. 

I normally ignore the vigra errors,  cellprofiler has worked fine in the past without vigra.

Any suggestions would be greatly appreciated.

Thank you again very much,
AC

**Comment by AetherUnbound** [comment]
@bethac07 what page should that link point to?

**Comment by arcolombo** [comment]
I am not sure where the link should point to.  I got the error installing on Ubuntu 14.04.  I switched to a windows system and did a clean install of CP and imctools today.

**Comment by arcolombo** [comment]
So I reinstalled cellProfiler on my linux box, and attached the YML file. the install is working correctly. and I can run cellprofiler.   Although for very large files, my machine is having issues with handling large files, but that is a separate issue.  You can close this bug, because the bug is very sensitive to the exact softwares installed for Ubuntu 14.04.  if anything if you can please update the Wiki page to have a more specific YML file, such as this, that would be helpful.


[linuxEnvironment.final.yml.txt](https://github.com/CellProfiler/CellProfiler/files/2307399/linuxEnvironment.final.yml.txt)

name: profiler
channels:
  - cyclus
  - BjornFJohansson
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - wxpython=3.0.2.0=py27_0
  - asn1crypto=0.23.0=py27h7b0c810_0
  - babel=2.5.0=py27h20693cd_0
  - binutils_linux-64=2.28.1=he4fe6c7_1
  - bleach=2.1.1=py27h655ea9b_0
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2017.11.5=py27h71e7faf_0
  - entrypoints=0.2.3=py27h502b47d_2
  - enum34=1.1.6=py27h99a27e9_1
  - futures=3.2.0=py27h7b459c0_0
  - gcc_linux-64=7.2.0=hc7b1ceb_1
  - gmp=6.1.2=hb3b607b_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.7.0=py27h5233db4_0
  - ipython_genutils=0.2.0=py27h89fb69b_0
  - javabridge=1.0.14=py27_0
  - jpeg=9b=habf39ab_1
  - jsonschema=2.4.0=py27_0
  - jupyter=1.0.0=py27_3
  - libgcc=7.2.0=h69d50b8_2
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libtiff=4.0.6=3
  - markupsafe=1.0=py27h97b2822_1
  - mistune=0.8.3=py27h14c3975_1
  - mkl=2018.0.3=1
  - nbconvert=5.3.1=py27he041f76_0
  - nbformat=4.4.0=py27hed7f2b2_0
  - notebook=5.3.1=py27_3
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py27h04863e7_0
  - pandocfilters=1.4.2=py27h428e1e5_1
  - pcre=8.39=1
  - pygments=2.2.0=py27h4a8b6f5_0
  - pywavelets=0.5.2=py27h035aef0_2
  - pyzmq=17.0.0=py27h14c3975_1
  - scandir=1.7=py27h14c3975_0
  - send2trash=1.5.0=py27_0
  - setuptools=36.5.0=py27h68b189e_0
  - singledispatch=3.4.0.3=py27h9bcb476_0
  - sip=4.18.1=py27hf484d3e_2
  - testpath=0.3.1=py27hc38d2c4_0
  - tornado=5.0=py27_0
  - traitlets=4.3.2=py27hd6ce930_0
  - xz=5.2.2=1
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=hfbfcf68_1
  - alabaster=0.7.10=py27_1
  - appdirs=1.4.3=py_1
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.5=py_1
  - backports.lzma=0.0.13=py27_0
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports_abc=0.5=py_1
  - bokeh=0.12.11=py27_0
  - cffi=1.11.2=py27_0
  - chardet=3.0.4=py27_3
  - click=6.7=py_1
  - cloudpickle=0.5.2=py_0
  - colorama=0.3.9=py_1
  - configparser=3.5.0b2=py27_0
  - cycler=0.10.0=py_1
  - cython=0.28.5=py27hfc679d8_0
  - dask=0.16.0=py_0
  - dask-core=0.16.0=py_0
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.2.1=py27_0
  - distributed=1.20.2=py27_0
  - expat=2.2.5=hfc679d8_1
  - fontconfig=2.12.1=4
  - freetype=2.7=1
  - functools32=3.2.3.2=py27_2
  - gettext=0.19.8.1=0
  - glib=2.55.0=h464dc38_2
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - h5py=2.7.1=py27_2
  - hdf5=1.10.1=2
  - heapdict=1.0.0=py27_0
  - html5lib=0.999999999=py27_0
  - icu=58.2=hfc679d8_0
  - imageio=2.3.0=py_1
  - ipython=5.8.0=py27_0
  - ipywidgets=7.4.0=py_0
  - jasper=1.900.1=4
  - jbig=2.1=0
  - jinja2=2.9.5=py27_0
  - jupyter_client=5.2.3=py_1
  - jupyter_console=5.2.0=py27_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py27h2d50403_2
  - libffi=3.2.1=1
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_2
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.4=4
  - libxslt=1.1.29=5
  - locket=0.2.0=py_2
  - matplotlib=2.1.0=py27_0
  - mkl_fft=1.0.5=py27_0
  - mkl_random=1.0.1=py27_0
  - msgpack-python=0.5.6=py27h2d50403_2
  - ncurses=5.9=10
  - networkx=2.1=py_1
  - olefile=0.45.1=py_1
  - openblas=0.2.20=8
  - pandoc=2.2.2=1
  - partd=0.3.8=py_1
  - pathlib=1.0.1=py_1
  - pathlib2=2.3.2=py27_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.4=py27_0
  - pillow=4.3.0=py27_1
  - pip=18.0=py27_1
  - prompt_toolkit=1.0.15=py27_0
  - psutil=5.4.6=py27_0
  - pthread-stubs=0.4=h470a237_1
  - ptyprocess=0.6.0=py27_0
  - pycparser=2.18=py_1
  - pyparsing=2.2.0=py_1
  - pyqt=5.6.0=py27h8210e8a_6
  - python=2.7.14=2
  - python-dateutil=2.6.0=py27_0
  - pytz=2018.5=py_0
  - pyyaml=3.12=py27_1
  - qt=5.6.2=3
  - qtconsole=4.4.0=py27h8a2030e_0
  - readline=6.2=0
  - scikit-image=0.14.0=py27hfc679d8_1
  - simplegeneric=0.8.1=py_1
  - six=1.11.0=py27_1
  - sortedcontainers=2.0.4=py_1
  - sqlite=3.13.0=1
  - subprocess32=3.5.2=py27_0
  - tblib=1.3.2=py_1
  - terminado=0.8.1=py27_0
  - tifffile=0.15.1=py27_1
  - tk=8.5.19=2
  - toolz=0.9.0=py_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5=py27_0
  - wheel=0.31.1=py27_1
  - widgetsnbextension=3.4.0=py27_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - yaml=0.1.7=h470a237_1
  - zict=0.1.3=py_0
  - java-jdk=8.25.17=0
  - blas=1.0=mkl
  - numpy=1.15.0=py27h1b885b7_0
  - numpy-base=1.15.0=py27h3dfced4_0
  - scikit-learn=0.19.1=py27hedc7406_0
  - scipy=1.1.0=py27hc49cb51_0
prefix: /home/arcolombo/.conda/envs/profiler
