### ISSUE TITLE
Headless CellProfiler compatability issues on CentOS6

### ISSUE THREAD

**Issue by fpbarthel** [CellProfiler/CellProfiler#3626]
Hi, I've tried to install CellProfiler on CentOS6 using pip following the instructions but I am facing recurring issues. 

iIf I follow the instructions step-by-step (install python, install dependencies, pip install on local directory) and try to start `cellprofiler` I get a `javabridge` error:

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/barthf/opt/miniconda3/envs/cellprofiler222/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/projects/barthf/opt/miniconda3/envs/cellprofiler222/lib/python2.7/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: numpy.core.multiarray failed to import
```

This seems to be javabridge/numpy version discrepancy. When I downgrade `javabridge` to the version mentioned elsewhere in the documentation here (`javabridge==1.0.15`), a similar error occurs. When I then also upgrade numpy (1.13.0 -> 1.14) and/or scipy I get the errors like this:

```
.../py27/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
...
```

I've tried installing various CellProfiler versions (2.2.2, 3.1.0 and the master commit) and in all attempts I am getting some variation of these errors. I've tried installing various different versions of `numpy`, `cellprofiler`, `javabridge`, `matplotlib`, `scipy` and `h5py` in various permutations and accross different versions of `cellprofiler` according to experiences from others I've found on here browing various posts but without any luck.

Here is my current `pip freeze`:

```
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.ssl-match-hostname==3.5.0.1
boto3==1.7.79
botocore==1.10.79
-e git+https://github.com/CellProfiler/CellProfiler.git@34b51abb093b32c23c1c84a1d27c1bbe1acb734e#egg=CellProfiler
centrosome==1.0.9
certifi==2018.8.13
chardet==3.0.4
cloudpickle==0.5.3
contextlib2==0.5.5
cycler==0.10.0
Cython==0.26
dask==0.18.2
decorator==4.3.0
docutils==0.14
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
h5py==2.8.0
idna==2.7
inflect==1.0.0
javabridge==1.0.15
jmespath==0.9.3
joblib==0.12.2
mahotas==1.4.4
matplotlib==2.1.2
mysqlclient==1.3.13
networkx==2.1
numpy==1.14.0
Pillow==5.2.0
prokaryote==2.4.0
pycairo==1.10.0
pyparsing==2.2.0
python-bioformats==1.4.0
python-dateutil==2.6.1
pytz==2017.2
PyWavelets==0.5.2
pyzmq==15.3.0
raven==6.9.0
requests==2.19.1
s3transfer==0.1.13
scikit-image==0.13.1
scikit-learn==0.18.2
scipy==0.17.0
singledispatch==3.4.0.3
six==1.10.0
subprocess32==3.2.7
toolz==0.9.0
tornado==4.5.2
urllib3==1.23
wxPython==3.0.0.0
wxPython-common==3.0.0.0
```

Any suggestions what I else I can do to try and get CellProfiler to run headless on CentOS6? Is there a recently updated list of packages and version numbers (eg. a `pip freeze` list of a conda environment similar to the one [here](https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation) but recent that is known to work on CentOS6? It seems like whenever I update one package to make it compatible, another one breaks.

**Comment by fpbarthel** [comment]
Hi, bumping this topic, hope I provided enough information?

**Comment by AetherUnbound** [comment]
@fpbarthel Sorry for the delay! The errors you pasted are actually warnings if I remember correctly. The rest of your code should be unaffected - is that the case?
