### ISSUE TITLE
ColorToGray: Pipelines using >4 channels cannot be loaded

### ISSUE THREAD

**Issue by votti** [CellProfiler/CellProfiler#3628]
Working on an improvement for `ColorToGray` (pull request #3619), I noticed that with the current `ColorToGray` module it is actually possible to generate pipelines, that generate a `List Index out of range` error upon loading.

To reproduce add more than 5 channels in `ColorToGray` (such that the `Channel number` 5 is used) and save the pipeline.
Then **restart** Cellprofiler. Upon trying to reload, the index error occurs.

My guess is that this is due to some bug  how `channel_names` in the `prepare_settings` step are extended.

Interestingly loading of these pipelines work as long as CP is not restarted between creation and loading.
I strange behaviour comes from the fact that the `channel_names` attribute is a class level, mutable variable (defined at class initialization: https://github.com/CellProfiler/CellProfiler/blob/34b51abb093b32c23c1c84a1d27c1bbe1acb734e/cellprofiler/modules/colortogray.py#L209)
Thus if it is modified all other instances of this class (including future instances) will have an already elongated `channel_name` list, if any of the previous instances has already extended it.

I think these unexpected behaviours are a reason class level mutable variables are usually discouraged, except if this property is specifically wanted:
https://docs.python.org/2/tutorial/classes.html#class-and-instance-variables

Edit: The error is specifically in this line of the `upgrade_settings` section:
https://github.com/CellProfiler/CellProfiler/blob/34b51abb093b32c23c1c84a1d27c1bbe1acb734e/cellprofiler/modules/colortogray.py#L540
I think the reason is that the `channel_names` are extended in the `prepare_settings` section, which likely is called only after  `upgrade_settings`.

**Comment by AetherUnbound** [comment]
Wow, what an excellent catch! We'll definitely have to implement a fix for this, even with your changes to the newest version.

**Comment by AetherUnbound** [comment]
I take it back - you actually fixed this with #3619 :tada: 
I made a pipeline with the old version of ColorToGray, and was able to replicate the bug as you described it. However, the pipeline I made _was_ able to be imported correctly with the new `upgrade_settings` :grin:. Thanks again @votti!
