### ISSUE TITLE
matplotlib 2.1.2, pyamg=3.3.2  error : "AttributeError: 'module' object has no attribute 'fromarray'".  Similar to #2581

### ISSUE THREAD

**Issue by arcolombo** [CellProfiler/CellProfiler#3629]
Hello. I have matplotlib 2.1.2, and pyamg version 3.3.2.  I do have a similar issue reported #2581 that was resolved.    First I installed CP 2.2.0 on a Windows 10, and it works. I have all IMCPlugins, and can run CP normally. all the IMCtools modules are present and can be loaded (smooth multichannel, resize, crop bb, and SaveImages Ilastik).   I receive an error when I run the smooth Multichannel step in the module.

raceback (most recent call last):
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\backends\backend_wx.py", line 944, in _onPaint
self.draw(drawDC=drawDC)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 48, in draw
FigureCanvasAgg.draw(self)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
self.figure.draw(self.renderer)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
return draw(artist, renderer, *args, **kwargs)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\figure.py", line 1299, in draw
renderer, self, artists, self.suppressComposite)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
a.draw(renderer)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
return draw(artist, renderer, *args, **kwargs)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\axes_base.py", line 2437, in draw
mimage._draw_list_compositing_images(renderer, self, artists)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
a.draw(renderer)
File "c:\users\anthony colombo\appdata\local\conda\conda\envs\profiler\lib\site-packages\cellprofiler\gui\cpfigure.py", line 2011, in draw
im = matplotlib.image.fromarray(image, 0)
AttributeError: 'module' object has no attribute 'fromarray'

Here is my environment

(profiler) C:\Users\Anthony Colombo>conda list
# packages in environment at C:\Users\Anthony Colombo\AppData\Local\conda\conda\envs\profiler:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1
alabaster                 0.7.10           py27h2cab13d_0    anaconda
appdirs                   1.4.3                    py27_0    anaconda
asn1crypto                0.23.0           py27hfce870e_0    anaconda
attrs                     17.3.0           py27hc6c0fab_0    anaconda
babel                     2.5.0            py27h50e9d34_0    anaconda
backports                 1.0              py27h6492d98_1    anaconda
backports.functools_lru_cache 1.4              py27h9586e20_1    anaconda
backports.shutil_get_terminal_size 1.0.0            py27h1657125_2    anaconda
backports_abc             0.5              py27h0ec6b72_0    anaconda
blas                      1.0                         mkl
bleach                    2.1.1            py27h48e914a_0    anaconda
bokeh                     0.12.11          py27h05167e3_0    anaconda
boto3                     1.7.80                    <pip>
botocore                  1.10.80                   <pip>
ca-certificates           2017.08.26           h94faf87_0    anaconda
cellh5                    1.3.0                     <pip>
CellProfiler              2.2.0                     <pip>
centrosome                1.0.9                     <pip>
certifi                   2017.11.5        py27h03b45e1_0    anaconda
cffi                      1.11.2           py27hba5d71c_0    anaconda
chardet                   3.0.4            py27h56c3b73_1    anaconda
click                     6.7              py27hb6defca_0    anaconda
cloudpickle               0.5.2            py27h309b2ea_0    anaconda
colorama                  0.3.9            py27hdfe4ae1_0    anaconda
configparser              3.5.0            py27h2fa79a8_0    anaconda
contextlib2               0.5.5            py27h42efda5_0    anaconda
coverage                  4.4.2            py27had8de3b_0    anaconda
cryptography              2.0.3            py27h1cc6ae9_1    anaconda
cycler                    0.10.0           py27h59acbbf_0    anaconda
cython                    0.27.3           py27h566c365_0    anaconda
dask                      0.16.0           py27h359b70f_0    anaconda
dask-core                 0.16.0           py27ha8db2d1_0    anaconda
decorator                 4.1.2            py27h383e199_0    anaconda
distributed               1.20.1           py27he6c3628_0    anaconda
docutils                  0.14             py27h8652d09_0    anaconda
entrypoints               0.2.3            py27h0271f2b_2    anaconda
enum34                    1.1.6            py27h2aa175b_1    anaconda
freetype                  2.8               vc9hf582001_0    anaconda
funcsigs                  1.0.2            py27h8885ae1_0    anaconda
functools32               3.2.3.2          py27h0cdbcdb_1    anaconda
future                    0.16.0                    <pip>
futures                   3.2.0            py27h8b2aecd_0    anaconda
git                       2.18.0               ha0abe07_1    conda-forge
h5py                      2.7.1            py27h2dd4c20_0    anaconda
hdf5                      1.10.1            vc9h9d13b45_0    anaconda
heapdict                  1.0.0                    py27_1    anaconda
hmmlearn                  0.2.0                     <pip>
html5lib                  0.999999999      py27h47766b3_0    anaconda
hypothesis                3.38.5           py27hcf2efe8_0    anaconda
icc_rt                    2017.0.4             h97af966_0    anaconda
icu                       58.2              vc9h3e79e4e_0    anaconda
idna                      2.6              py27h1ea29d3_1    anaconda
imageio                   2.2.0            py27h283db88_0    anaconda
imagesize                 0.7.1            py27h1482bd8_0    anaconda
imctools                  0.0.4                     <pip>
inflect                   1.0.0                     <pip>
intel-openmp              2018.0.0             hd92c6cd_8    anaconda
ipaddress                 1.0.18           py27h08e1fa7_0    anaconda
ipykernel                 4.7.0            py27h5233db4_0    anaconda
ipython                   5.4.1            py27hbf971b4_1    anaconda
ipython_genutils          0.2.0            py27hbe997df_0    anaconda
ipywidgets                7.0.5            py27hac8cb9a_0    anaconda
java-jdk                  8.25.17                       0    cyclus
java-jre                  8.25.17                       0    cyclus
javabridge                1.0.14                   py27_0    anaconda
jinja2                    2.10             py27hba1794b_0    anaconda
jmespath                  0.9.3                     <pip>
jpeg                      9b                vc9hb90d6ad_1    anaconda
jsonschema                2.6.0            py27haaf3834_0    anaconda
jupyter                   1.0.0                    py27_3    anaconda
jupyter_client            5.1.0            py27hced1786_0    anaconda
jupyter_console           5.2.0            py27h6ed736b_1    anaconda
jupyter_core              4.4.0            py27h1619e65_0    anaconda
libiconv                  1.15              vc9h6e1f958_5    anaconda
libpng                    1.6.32            vc9h2352712_3    anaconda
libtiff                   0.4.2                     <pip>
libtiff                   4.0.8            vc9hf4dca05_10    anaconda
libxml2                   2.9.4             vc9h17753f3_5    anaconda
libxslt                   1.1.29            vc9h15c42d4_5    anaconda
locket                    0.2.0            py27h1ca288a_1    anaconda
lxml                      4.1.1            py27h6c3328e_0    anaconda
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gsl                 2.1                           2
m2w64-libiconv            1.14                          6
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libtiff             4.0.6                         2
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-pcre                8.38                          2
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
mahotas                   1.4.4                    py27_0    conda-forge
markupsafe                1.0              py27h9d4480d_1    anaconda
matplotlib                2.1.2            py27ha51faf0_0    anaconda
mistune                   0.8.1            py27hf875dda_0    anaconda
mkl                       2018.0.1             h2108138_4    anaconda
mkl_fft                   1.0.5                    py27_0    conda-forge
msgpack-python            0.4.8            py27he0366a1_0    anaconda
msys2-conda-epoch         20160418                      1
mysql-python              1.2.5                    py27_0    anaconda
nbconvert                 5.3.1            py27h7a573cf_0    anaconda
nbformat                  4.4.0            py27hf49b375_0    anaconda
networkx                  1.11             py27h5ef25a2_0    anaconda
notebook                  5.2.2            py27h3cd48a9_0    anaconda
numpy                     1.13.3           py27h9ac254c_0    anaconda
olefile                   0.44             py27h42675a9_0    anaconda
openssl                   1.0.2l            vc9hb274bc6_5    anaconda
packaging                 16.8             py27hae1a450_1    anaconda
pandas                    0.21.0           py27h3b50df0_1    anaconda
pandoc                    1.19.2.1             hb2460c7_1    anaconda
pandocfilters             1.4.2            py27h76461d3_1    anaconda
partd                     0.3.8            py27h1e0692f_0    anaconda
pathlib                   1.0.1                     <pip>
pathlib2                  2.3.0            py27h0ae272f_0    anaconda
pickleshare               0.7.4            py27hb5f6335_0    anaconda
pillow                    4.2.1            py27hbae4915_0    anaconda
pip                       9.0.1            py27hdaa76b4_4    anaconda
pip                       18.0                      <pip>
pluggy                    0.6.0            py27h89dc50b_0    anaconda
prokaryote                2.4.0                     <pip>
prompt_toolkit            1.0.15           py27h3a8ec6a_0    anaconda
psutil                    5.4.1            py27h2104f53_0    anaconda
py                        1.5.2            py27ha24bda0_0    anaconda
pyamg                     3.3.2            py27hce6d55d_0    anaconda
pycparser                 2.18             py27hb43d16c_1    anaconda
pygments                  2.2.0            py27ha50f84f_0    anaconda
pympler                   0.5              py27hb48c9d9_0    anaconda
pyopenssl                 17.4.0           py27hd2bc570_0    anaconda
pyparsing                 2.2.0            py27hc7d9fa6_1    anaconda
pyqt                      5.6.0            py27h224ed30_5    anaconda
pysocks                   1.6.7            py27h59bdd1e_1    anaconda
pytest                    3.3.0            py27h0d7acca_0    anaconda
python                    2.7.14              h8c3f1cb_23    anaconda
python-bioformats         1.4.0                     <pip>
python-dateutil           2.6.1            py27hbdcc174_1    anaconda
pytz                      2017.3           py27hca431c1_0    anaconda
pywavelets                0.5.2            py27h0dc3f48_0    anaconda
pyyaml                    3.12                     py27_0    conda-forge
pyzmq                     15.3.0                   py27_0    conda-forge
qt                        5.6.2            vc9hc26998b_12    anaconda
qtconsole                 4.3.1            py27h77d40ac_0    anaconda
r-base                    3.4.2                hd3afeec_0
raven                     6.3.0                    py27_0    conda-forge
requests                  2.18.4           py27h3159eba_1    anaconda
rpy2                      2.8.6           py27r342h37e13a4_2
s3transfer                0.1.13                    <pip>
scandir                   1.6              py27h518bda0_0    anaconda
scikit-image              0.13.1           py27h00bf6af_0    anaconda
scikit-learn              0.19.1           py27he00e316_0    anaconda
scipy                     1.0.0            py27h7cd1477_0    anaconda
setuptools                36.5.0           py27ha483b79_0    anaconda
simplegeneric             0.8.1                    py27_1    anaconda
singledispatch            3.4.0.3          py27h3f9d112_0    anaconda
sip                       4.18.1           py27h5ec1c1a_2    anaconda
six                       1.11.0           py27ha5e1701_1    anaconda
snowballstemmer           1.2.1            py27h28d3bf7_0    anaconda
sortedcontainers          1.5.7            py27hb302113_0    anaconda
sphinx                    1.6.3            py27h858dd0f_0    anaconda
sphinxcontrib             1.0              py27h0e2fb95_1    anaconda
sphinxcontrib-websupport  1.0.1            py27h0d0f901_1    anaconda
sqlite                    3.20.1            vc9h5ec81ce_1    anaconda
ssl_match_hostname        3.5.0.1          py27hea8a0f4_2    anaconda
subprocess32              3.2.7            py27hcc576e2_0    anaconda
tblib                     1.3.2            py27h8ae915c_0    anaconda
testpath                  0.3.1            py27h1cd488d_0    anaconda
tifffile                  0.12.1                   py27_1    conda-forge
tifffile                  0.15.1                    <pip>
tk                        8.5.18                    vc9_0    anaconda
toolz                     0.8.2            py27h1873a47_0    anaconda
tornado                   4.5.2            py27hbdd278e_0    anaconda
traitlets                 4.3.2            py27h1b1b3a5_0    anaconda
typing                    3.6.2            py27h9197bb0_0    anaconda
urllib3                   1.22             py27hb9f5a07_0    anaconda
vc                        9                    h7299396_1    anaconda
vs2008_runtime            9.00.30729.5054               0    anaconda
wcwidth                   0.1.7            py27hb1a0d82_0    anaconda
webencodings              0.5.1            py27h4e224a2_1    anaconda
wheel                     0.30.0           py27ha643586_1    anaconda
widgetsnbextension        3.0.8            py27hc754cff_0    anaconda
win_inet_pton             1.0.1            py27hf41312a_1    anaconda
win_unicode_console       0.5              py27hc037021_0    anaconda
wincertstore              0.2              py27hf04cefb_0    anaconda
wxpython                  3.0                      py27_0    anaconda
xerces-c                  3.2.0                hf00aa6f_2    anaconda
yaml                      0.1.7                     vc9_0  [vc9]  conda-forge
zict                      0.1.3            py27h0171463_0    anaconda
zlib                      1.2.11            vc9ha80f4e8_1    anaconda
zope                      1.0                      py27_0    anaconda
zope.interface            4.4.3            py27hbc7a703_0    anaconda

(profiler) C:\Users\Anthony Colombo>

Any suggestions will be greatly appreciated.  Tomorrow I will look more closely at the script "cpconfigure.py"

**Comment by arcolombo** [comment]
this issue is more related to the IMCplugins and not directly CellProfiler software. closing.

**Comment by AetherUnbound** [comment]
Sorry we didn't get back to you sooner @arcolombo, but I'm glad you found the cause!
