### ISSUE TITLE
Error: Failure in analysis startup

### ISSUE THREAD

**Issue by kwhuang88** [CellProfiler/CellProfiler#3631]
Hi,

I am running CP3.1.5 on a Mac (10.13.6), and I am unable to run "Analyze Images" through the GUI although I am able to run Test Mode. The only error message I get is "Failure in analysis startup". I have also tried running an example pipeline from the CellProfiler site and run into the same error. On a separate but related note, I have not run into this issue when running "Analyze Images" from the GUI with the same pipeline in CP3.1.5 on a Windows 7 machine, but it gave very different results in IdentifyPrimaryObjects.

I can try working with an edited version of the pipeline on the Windows machine, but is there a way to fix the issue I am facing on the Mac?

Thanks!

**Comment by AetherUnbound** [comment]
Hello @kwhuang88! Thanks for submitting this error. I assume you're running the compiled version - either way, is there any additional error message text displayed?

**Comment by kwhuang88** [comment]
Yes I was using the compiled version that I downloaded from the CP website. There were no additional error messages or text displayed besides "Failure in analysis startup".

**Comment by duerna** [comment]
I met the totally same problem-"Failure in analysis startup".
MAC (10.14.2).
