### ISSUE TITLE
Increment stable to something in the 4 family

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3635]

**Comment by AetherUnbound** [comment]
What's the reason for this change?

**Comment by bethac07** [comment]
People often clone CP, install it, checkout stable, then run into a bunch of issues with installed package versions and stuff because stable is very old.  In general, we don't want to promote usage of 2.3 unless there's a specific reason to.  

I'd think in general "stable" ought to point to the most recent release, but maybe I'm wrong about what the convention is?
