### ISSUE TITLE
x-axis 'log scale' is actually natural log, not log10

### ISSUE THREAD

**Issue by tim-tx** [CellProfiler/CellProfiler#3644]
I believe there is an issue with displaying plots on a log scale. I did a _DisplayHistogram_ step with a linear scale and got the following plot:
![linear](https://user-images.githubusercontent.com/13240467/45579459-af71c580-b855-11e8-9659-7ed308fd49f0.png)
If I instead select _log_ from _Transform the data prior to plotting along the X-axis?_, I get the following:
![log](https://user-images.githubusercontent.com/13240467/45579462-b4cf1000-b855-11e8-8db2-5121dce979d0.png)
**Look at the x-axis limits.** What?
The help item for the scale selection indicates this should be a log10 transformation:
> The measurement data can be scaled with either a linear scale ("No") or a log (base 10) scaling.

In `displayhistogram.py` the scale selection (`log`) gets passed along ([here](https://github.com/CellProfiler/CellProfiler/blob/13cf85c4e8a45fc80130102df21d9b6aca28d8cc/cellprofiler/modules/displayhistogram.py#L158)) to `subplot_histogram()` in `gui/figure.py`. `subplot_histogram()` actually applies a natural log to the data ([here](https://github.com/CellProfiler/CellProfiler/blob/13cf85c4e8a45fc80130102df21d9b6aca28d8cc/cellprofiler/gui/figure.py#L1995)):

    values = numpy.log(values[values > 0])

This checks out given the scaling on the plots. Should be `numpy.log10`.

**Comment by AetherUnbound** [comment]
Excellent catch! I would imagine there would be use cases for both `log10` and natural log, so it would likely be good to preserve both but allow them to be chosen. Do you mind providing your pipeline and images in a zip file so I can test this?

**Comment by AetherUnbound** [comment]
It looks like log is used both in the numpy call as well as the matplotlib scaling. I don't think we'll have to adjust the latter (since they all just call `set_xscale('log')`, but it'd be best to double check.
