### ISSUE TITLE
ExpandOrShrinkObjects drops some objects when not filling holes

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3645]
I identified this in another confidential pipeline, but you can reproduce it with the images from ExampleFly and the pipeline below (zooming in on the ROI to show an example)- 
1) IDPrimary for Nuclei
![image](https://user-images.githubusercontent.com/6721515/45737380-a6695700-bbbb-11e8-8ea1-03c824e8a8ba.png)
2) Shrink nuclei to centers
![image](https://user-images.githubusercontent.com/6721515/45737411-bb45ea80-bbbb-11e8-8874-a5a921ee234a.png)
3) Reexpand from those seeds using the shrunken nuclei and the exact same DNA image from step 1
![image](https://user-images.githubusercontent.com/6721515/45737460-dfa1c700-bbbb-11e8-8adf-dd7ecf75edaa.png)
4) ConvertObjectsToImage of the output of Step1 vs Step3, zoomed in even more- the nucleus in question is entirely gone, not just unexpanded.
![image](https://user-images.githubusercontent.com/6721515/45737568-30b1bb00-bbbc-11e8-82f1-f89208ca3d93.png)

Pipeline
[idsecondarybug.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/2395867/idsecondarybug.cppipe.zip)

**Comment by votti** [comment]
I think these to examples from issue #3582 (more focused on the fact that non continuous numbered labels in segmentation masks are causing problems) are likely also examples of this issue of IDSecondary:
https://github.com/CellProfiler/CellProfiler/issues/3582#issuecomment-410960186
https://github.com/CellProfiler/CellProfiler/issues/3582#issuecomment-398662661

**Comment by AetherUnbound** [comment]
This seems to be caused by these lines: https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifysecondaryobjects.py#L538-L544
I suspect it has something to do with `unedited_segmented`.

**Comment by bethac07** [comment]
This apparently goes back to CP2.2, so is perhaps unrelated to the current crop of issues

![image](https://user-images.githubusercontent.com/6721515/46891228-330fd980-ce37-11e8-9021-3c0f553efd1e.png)

**Comment by bethac07** [comment]
This is, in fact, a bug in ExpandOrShrinkObjects

**Comment by bethac07** [comment]
Interestingly, the [image output](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/expandorshrinkobjects.py#L224) from EOSO (which is object.segmented) and the CSV location output (which [also works from object.segmented](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/expandorshrinkobjects.py#L215-L218)) both show the label that's missing in ISO, which calls [objects.unedited_segmented](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifysecondaryobjects.py#L538), so there's likely something there

**Comment by bethac07** [comment]
AHA! The one that gets dropped is one that, if I had turned hole filling off in IDPrimary, I would have seen has a tiny little 1 pixel object inside its bigger object. 

![image](https://user-images.githubusercontent.com/6721515/49049689-18f34600-f1ae-11e8-8ff0-0180436d39f9.png)

**Comment by bethac07** [comment]
Yup, when you look at unedited_segmented, you can see there's clearly two objects there, which were nicely filled to one in IPO after IPO hole filling but it initially came up with 2.  When you use the EOSO hole filling option it takes care of it by just smushing out the one pixel object as if it had never been, but if you DON'T, it passes it the unedited_segmented which has two seeds inside one primary object, so presumably this gets thrown out during some check in IDSecondary.  

I'll have to think about this more, because it's not obvious what the fix is (other than maybe to say in IDSecondary if you have two seeds, take the bigger of the two and move on OR to say if you have two seeds, throw the IDSecondary and the related IDPrimary out no matter what).  Ordinarily since it's a pretty corner case (you need certain combos of IPO and EOSO to even make it happen) I'd be tempted to wontfix it, but the problem is that when it does pop up it throws off the numbering of objects and the parent-child ratio in the ISO objects is reported incorrectly, which is going to lead to trouble.
![image](https://user-images.githubusercontent.com/6721515/49050343-f3b40700-f1b0-11e8-82c8-a97d373fc312.png)

**Comment by bethac07** [comment]
Related to #3816

**Comment by DavidStirling** [comment]
Currently looking into this. I think the problem is that ExpandOrShinkObjects performs the shrink operation on objects.segmented, .unedited_segmented and .small_removed_segmented independently. After hole filling the midpoint of these objects is changed ever so slightly. IdentifySecondaryObjects starts with .unedited_segmented and removes anything not in .segmented, so the problem centers don't align and get excluded.

I think a possible solution to this would be to have ExpandOrShrink handle the .segmented result as the "true" centers, then mask off the original objects when working on unedited and small_removed to find anything missing from that segmentation (then add the centers for the 'real' objects back in). I'll have a play with this next week.
