### ISSUE TITLE
Bump javabridge to 1.0.18

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#3648]
Hi all,
I made recent changes to Javabridge to enable installation on Linux with the Oracle JDK. https://github.com/LeeKamentsky/python-javabridge/issues/126 was filed to take care of a problem for a CellProfiler user. The 1.0.18 version should work for these users.

**Comment by AetherUnbound** [comment]
Thanks @LeeKamentsky!

**Comment by 0x00b1** [comment]
Thanks @LeeKamentsky!
