### ISSUE TITLE
"Test Run" where is the little position indicator in 3.1.5?

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#3658]
In previous versions of CP, Test Run had a little position indicator that showed where the test run was up to and that could be dragged backwards to REDO certain steps of the pipeline. 
It appears that this feature is missing in 3.1.5. I can see that the current module is underlined, but I do not see how to drag it back one step.

This is with the 3.1.5 binary distribution for Windows as well as with various source installations on Linux. 
Not sure whether this is a wx widget bug (indicator simply not visible) or is an intended change.

**Comment by bethac07** [comment]
This was removed intentionally in 3.0.0- if you search "slider" in the issues, you'll see it was debated a lot, but eventually was decided it needed to happen.  

You can click on an earlier module, then right-click and say "Run from module # ____"- this will replicate the "drag-back" functionality.

**Comment by VolkerH** [comment]
Thanks for your reply and apologies that I didn't find the existing discussion.
