### ISSUE TITLE
Can't open after installing on windonws7?

### ISSUE THREAD

**Issue by zhouhao-learning** [CellProfiler/CellProfiler#3665]
I installed CellProfiler 3.1.5 on Windows 7 system. After the installation is successful, I double-clicked the CellProfiler software, but an error window pops up, as follows:

![image](https://user-images.githubusercontent.com/24581773/46720622-b00a4a00-cca3-11e8-951c-83f5eb8f54e2.png)

What is the reason for this, how should I solve it?

**Comment by AetherUnbound** [comment]
Hello! Please take a look at the following forum posts:
- https://forum.image.sc/t/cellprofiler-3-1-5-failed-to-execute-script-cellprofiler/19177/2
- https://forum.image.sc/t/compatability-issue-between-cellprofiler-3-1-and-fiji/18949/4

Give these suggestions a shot, and let us know if you have any additional problems installing!
