### ISSUE TITLE
Importing module errors in CellProfiler/cellprofiler/cpmath/cpmorphology.py file

### ISSUE THREAD

**Issue by zhouhao-learning** [CellProfiler/CellProfiler#3666]
I cloned the Cellprofiler 2.1.1 version code. When I tried to run the code to process my own cell image, I got the following error:
```
Traceback (most recent call last):
  File "./CellProfiler/CellProfiler.py", line 252, in main
    run_pipeline_headless(options, args)
  File "./CellProfiler/CellProfiler.py", line 790, in run_pipeline_headless
    from cellprofiler.pipeline import Pipeline, EXIT_STATUS, M_PIPELINE
  File "/project/hit_cell/process-plate/CellProfiler/cellprofiler/pipeline.py", line 52, in <module>
    import cellprofiler.objects as cpo
  File "/project/hit_cell/process-plate/CellProfiler/cellprofiler/objects.py", line 19, in <module>
    from cellprofiler.cpmath.cpmorphology import all_connected_components
  File "/project/hit_cell/process-plate/CellProfiler/cellprofiler/cpmath/cpmorphology.py", line 20, in <module>
    import _cpmorphology
ImportError: No module named _cpmorphology
```

I found the following code in the `CellProfiler/cellprofiler/cpmath/cpmorphology.py`file:
```
import _cpmorphology
from outline import outline
from rankorder import rank_order
from index import Indexes
from _cpmorphology2 import skeletonize_loop, table_lookup_index
from _cpmorphology2 import grey_reconstruction_loop
from _cpmorphology2 import _all_connected_components
from _cpmorphology2 import index_lookup, prepare_for_index_lookup
from _cpmorphology2 import extract_from_image_lookup, fill_labeled_holes_loop
from _cpmorphology2 import trace_outlines
```
But I did not find out where the `_cpmorphology` and `_cpmorphology2` module files are.

How can I solve my mistake? Thank you very much.

**Comment by AetherUnbound** [comment]
Hello! What's the command that you're using? Additionally, version 2.1.1 is currently unsupported; 2.3.1 is our most up-to-date 2.x version, and 3.1.x is our actively supported version. Is there a reason you need to be running 2.1.1?

**Comment by zhouhao-learning** [comment]
@AetherUnbound 
Hello, I am using the script below this link:
https://github.com/ExaScience/process-plate

They are also using your software, the author of this link told me that I need to use version 2.1.1:
https://github.com/ExaScience/process-plate/issues/1

How can I solve this problem?

**Comment by AetherUnbound** [comment]
I cannot guarantee that you can get 2.1.1 working, as we don't support it. However, you may need to run `python setup.py develop` or `pip install -e .` in `cellprofiler/cpmath` folder where you have it cloned.

**Comment by AetherUnbound** [comment]
Closing this, feel free to re-open if the issue persists.
