### ISSUE TITLE
Cell Painting Features. 

### ISSUE THREAD

**Issue by 32nguyen** [CellProfiler/CellProfiler#3674]
Hi, 
I am from Electrical Engineering and completely new with CellProfiler.  At the moment, I have to calculate the Cell Painting Feature mentioned in this https://github.com/carpenterlab/2016_bray_natprot/wiki/What-do-Cell-Painting-features-mean%3F. There are 1783 features mentioned: https://raw.githubusercontent.com/wiki/carpenterlab/2016_bray_natprot/attachments/feature_names.txt

I wonder if there is a available completed way to run a single script that can extract these 1783 features from a group of 5 channels of fluorescent images.

Any help would be appreciated.

Thanks

**Comment by AetherUnbound** [comment]
@dlogan Thanks for responding! I agree @32nguyen, I'd suggest asking this on the forum. I'm going to close this issue - but if you have questions about the code feel free to ask them here!
