### ISSUE TITLE
Objects created by RelateObjects do not initialize with a Count

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3677]
Objects created by Watershed and the Identify modules initialize with an object count and a per-image count; it does not appear this happens in RelateObjects.  It doesn't seem to fully add to the object set at all, since it has no measurements.
If you therefore attempt to add measurements to an object created by RelateObjects, an error is thrown when you get to ExportToSpreadsheet and/or ExportToDatabase, because it can't write out the per-image count (presumably it would then throw an error when it tries to write out the object count in the Object spreadsheet too, but it doesn't get that far).
Pipeline to reproduce below, based on the WelcomeScreen images.

![image](https://user-images.githubusercontent.com/6721515/47859869-9d2bf680-ddc5-11e8-85b5-1828cce74739.png)

[RelateObjectsError.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/2538956/RelateObjectsError.cppipe.zip)

**Comment by bethac07** [comment]
I'm not really sure, but comparing between IPO and Relate I have a sneaking suspicion it's this- https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifyprimaryobjects.py#L1067

**Comment by AetherUnbound** [comment]
I think you're right @bethac07! What a simple thing for me to overlook when I added the child objects option. I'll add that into relate and see if that fixes it. Thanks!

**Comment by AetherUnbound** [comment]
Damn, unfortunately I don't think that's it because I'm adding the objects here :( https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/relateobjects.py#L403-L411

**Comment by AetherUnbound** [comment]
Update: I _might_ be missing this! https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/module.py#L1328 (this isn't present in RelateObjects)

**Comment by bethac07** [comment]
Fixed in 319
