### ISSUE TITLE
RelateObjects error - shape mismatch

### ISSUE THREAD

**Issue by hkhawar** [CellProfiler/CellProfiler#3718]
Worker 0: Error detected during run of module RelateObjects#16
Worker 0: Traceback (most recent call last):
Worker 0:   File "cellprofiler/pipeline.py", line 1924, in run_image_set
Worker 0:   File "cellprofiler/pipeline.py", line 2034, in run_module
Worker 0:   File "cellprofiler/modules/relateobjects.py", line 377, in run
Worker 0:   File "scipy/ndimage/measurements.py", line 638, in mean
Worker 0:   File "scipy/ndimage/measurements.py", line 478, in _stats
Worker 0:   File "numpy/lib/stride_tricks.py", line 252, in broadcast_arrays
Worker 0:   File "numpy/lib/stride_tricks.py", line 187, in _broadcast_shape
Worker 0: ValueError: shape mismatch: objects cannot be broadcast to a single shape
[test1.zip](https://github.com/CellProfiler/CellProfiler/files/2852991/test1.zip)

**Comment by hkhawar** [comment]
System Specs: macOS High Sierra (version 10.13.6)
CellProfiler-3.1.8
I get an error if I am trying to relate cells (measurements) to parent object while I dont get an error If I relate nuclei-obj (measurements) to parent object.

**Comment by DavidStirling** [comment]
I've not been able to replicate this error in 3.1.9, and the RelateObjects module did change somewhat in this version. Please re-open this if you're still having trouble.

**Comment by braymp** [comment]
Reopening; this problem persists in 4.2.1. See attached pipeline and images to replicate.

> Failed to run module RelateObjects
> Traceback (most recent call last):
>   File "cellprofiler\gui\pipelinecontroller.py", line 3363, in do_step
>   File "cellprofiler_core\pipeline\_pipeline.py", line 1298, in run_module
>   File "cellprofiler\modules\relateobjects.py", line 399, in run
>   File "scipy\ndimage\measurements.py", line 683, in mean
>   File "scipy\ndimage\measurements.py", line 511, in _stats
>   File "<__array_function__ internals>", line 5, in broadcast_arrays
>   File "numpy\lib\stride_tricks.py", line 538, in broadcast_arrays
>   File "numpy\lib\stride_tricks.py", line 420, in _broadcast_shape
> ValueError: shape mismatch: objects cannot be broadcast to a single shape

[troubleshooting.zip](https://github.com/CellProfiler/CellProfiler/files/7714536/troubleshooting.zip)

**Comment by bethac07** [comment]
@braymp this is something different (#4586) - closing here, added to our issue tracker there.
