### ISSUE TITLE
ERROR: CP3.1.8 in pipeline operating

### ISSUE THREAD

**Issue by LeeJasmineLee** [CellProfiler/CellProfiler#3719]
I've downloaded several example pipeling from the CP offical website, and designed my own pipeline for late reasearch, but frustratingly, the CP system always popup a window, saying 'the pipeline cannot be started because of a configuration probelm.' 

 and I've tried to adjust the setting, it still does not work.

<img width="310" alt="snipaste_2019-02-13_23-01-08" src="https://user-images.githubusercontent.com/47602574/52721277-4a78f200-2fe4-11e9-9d72-7c169bb20086.png">

**Comment by bethac07** [comment]
Hi,

I recommend checking out our [blog post on the topic of creating image sets](https://blog.cellprofiler.org/2017/01/09/help-why-does-cellprofiler-say-it-cant-find-any-valid-image-sets/); if that doesn't help you find the issue, please post the pipeline and some sample images (or links to them on Box, GDrive, etc) on our [help forum](https://forum.image.sc/tags/cellprofiler)
