### ISSUE TITLE
unsupported operand type(s) for +=: 'NoneType' and 'int' for LoadData module

### ISSUE THREAD

**Issue by JmonkG** [CellProfiler/CellProfiler#3721]
Currently I'm trying to create a batch to process my cif files. For that purpose, I'm using the LoadData module, which reads my csv file which has the following 4 components: name,plate,row,column, where plate, row and column are metadata. As soon as I upload it and select it to be group by metadata, I got this message:
> unsupported operand type(s) for +=: 'NoneType' and 'int'

Now, I dont have this problem when I only work with plate as the metadata . I can select those 3 metadata from the csv file, but only when its present only one, I got this error.  Its there a way to fix this problem or I am doing something wrong?
this is a slighty preview of what I am doing:
<img width="1313" alt="screen shot 2019-02-20 at 11 34 22" src="https://user-images.githubusercontent.com/886876/53085687-b6d38400-3503-11e9-9302-3a5b0fcacdc3.png">
Thank you

**Comment by bethac07** [comment]
Needs more info to validate.
