### ISSUE TITLE
Add new INCell file naming scheme to metadata regex guesser

### ISSUE THREAD

**Issue by nieder** [CellProfiler/CellProfiler#3725]
The latest version of the INCell (v7.2) acquisition software has a new preference to use a more complete output file name that encapsulates all imaging options (well, laser, filter, timepoint, z-pos, field, etc).

Under the longstanding default settings in the program, the image files are generally named like this:
`A - 01(fld 2 wv Blue - FITC).tif` or sometimes this:
`A - 01(fld 1 wv UV - DAPI z 3 time 2 - 2636ms).tif` or even this occasionally:
`A - 13(fld 2).tif`

With the new preference set, the names now always look like this, regardless of how many of the parameters are being used in the run:
`A_01_f2_c1_xUV_mDAPI_z3_t2.tif`

This naming scheme should be much easier to parse in a consistent manner since all metadata tokens are always present. A new guesser should be added to `cellprofiler/gui/regexp_editor.py` for this new scheme.

I think this is correct:
````
^(?P<Row>[A-P])_(?P<Column>[0-9]*)_f(?P<Site>[0-9]*)_c(?P<Channel>[0-9]*)_x(?P<Wavelength>.*)_m(?P<Filter>.*)_z(?P<Slice>[0-9]*)_t(?P<Timepoint>[0-9]*)\.tif$
````

**Comment by DavidStirling** [comment]
Seems to work, thanks for that!
