### ISSUE TITLE
Problem with - -data-files and - -file-list

### ISSUE THREAD

**Issue by Guikkz** [CellProfiler/CellProfiler#3736]
Dear CellProfiler community,
I try to launch a simple CorrectIllumination pipeline using CellProfiler 3.1.3 installed on a linux environment (RHEL 7.6 with LSF 9.1.3).
My pipeline consists of 4 modules:

* loadData
* CorrectIlluminationCalculate
* SaveImages
* CreateBatchFiles

When run directly through the GUI (without CreateBatchFile), it works perfectly. When run through this command line:
```
cellprofiler -c -r -p /Instruments/microscopy/2-Prog/CellProfiler/illum_out/Batch_data.h5 --plugins-directory /Software/python/Anaconda-5.2.0-cellprof/plugins/CellProfiler
```

it also run correctly using the csv I specified while running the pipeline though the GUI. But when I try to specify the csv in the command line it fails (also if I use --data-file=...):

```
cellprofiler -c -r -p /Instruments/microscopy/2-Prog/CellProfiler/illum_out/Batch_data.h5 --plugins-directory /Software/python/Anaconda-5.2.0-cellprof/plugins/CellProfiler --data-file /Instruments/microscopy/2-Prog/CellProfiler/illum_out/Illum_FileList_24418_Test.csv
```
The error is this one:
```
Error detected during run of module LoadData
Traceback (most recent call last):
  File "/Software/cellprof/CellProfiler-master/cellprofiler/pipeline.py", line 1779, in run_with_yield
    self.run_module(module, workspace)
  File "/Software/cellprof/CellProfiler-master/cellprofiler/pipeline.py", line 2031, in run_module
    module.run(workspace)
  File "/Software/cellprof/CellProfiler-master/cellprofiler/modules/loaddata.py", line 1205, in run
    value = m.get_measurement(cellprofiler.measurement.IMAGE, feature_name)
  File "/Software/cellprof/CellProfiler-master/cellprofiler/measurement.py", line 963, in get_measurement
    vals = self.hdf5_dict[object_name, feature_name, image_set_number]
  File "/Software/cellprof/CellProfiler-master/cellprofiler/utilities/hdf5_dict.py", line 374, in __getitem__
    result = self[object_name, feature_name, [num_idx]]
  File "/Software/cellprof/CellProfiler-master/cellprofiler/utilities/hdf5_dict.py", line 379, in __getitem__
    assert feature_exists, "Feature {} for {} does not exist".format(feature_name, object_name)
AssertionError: Feature Group_Number,"Group_Index","URL_raw","PathName_raw","FileName_raw","Series_raw","Frame_raw","Channel_raw","Metadata_Barcode","Metadata_ChannelNumber","Metadata_Date","Metadata_FileLocation","Metadata_Frame","Metadata_Plate","Metadata_PlateID","Metadata_Series","Metadata_Site","Metadata_Well" for Image does not exist
Wed Apr 17 11:37:13 2019: Image # 1, module LoadData # 1: CPU_time = 0.00 secs, Wall_time = 0.00 secs
```

Just to add that the csv I try to specify is just a longer version of the one I specify through the GUI so it suspect it is not due to a badly defined csv.

When I try the same pipeline using the Images/Metadata/Names/Groups and the --file-list switch, there is no error but it just use the list of files specified in the GUI and not the list specified in the csv.

Could you please points me to the error or to explain me better how to use the switches ?
Thank you for your help,

N.B: I posted the same question on [image.sc forum](https://forum.image.sc/t/problem-with-data-files-and-file-list/24908?u=guikks)
Guikkz

**Comment by bethac07** [comment]
Hi,

Did you try using the .cppipe, rather than the batch file? The batch file is meant to already include the list of files to process; I'm not sure what happens when you try to override it.

**Comment by Guikkz** [comment]
Hi @bethac07,
I tried using the .cpproj and it worked perfectly, thank you for your help !
So the correct call was:
``
cellprofiler -c -r -p /Instruments/microscopy/2-Prog/CellProfiler/illum_out/analysis.cpproj --plugins-directory /Software/python/Anaconda-5.2.0-cellprof/plugins/CellProfiler --data-file=/Instruments/microscopy/2-Prog/CellProfiler/illum_out/Illum_FileList_24418_Test.csv

``
