### ISSUE TITLE
Where can I find a list of features that CellProfiler measures

### ISSUE THREAD

**Issue by YubinXie** [CellProfiler/CellProfiler#3737]
Hi,

I tried to find the list of features that Cell Profiler can measure. It was shown that the feature number is around 500. Do you have a list of it? What I found in the software is limited in ~ 10. Thanks!

![D4A799E8-7767-43DA-B947-85A612040273](https://user-images.githubusercontent.com/16257776/56463450-6b721080-63a2-11e9-892a-0d33ea1f0e9b.png)

**Comment by bethac07** [comment]
Hi,

Each of those modules returns dozens of features, and for ones that look at combinations of images and/or objects can reach into the hundreds- [this page in the manual](http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.1.8/modules/measurement.html) is probably most helpful.
