### ISSUE TITLE
Can't save pipeline with adaptive thresholding if setting was Global/RobustBackground

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3738]
From [the forum](https://forum.image.sc/t/identifyprimaryobjects-bug-cannot-save-adaptive-threshold-strategy/24844)

>My pipeline includes an IdentifyPrimaryObjects function that works well when the Threshold strategy is Adaptive. However, when I try to save this pipeline and reopen it, the Threshold strategy automatically resets to Global. (I am able to successfully edit and save other aspects of the pipeline)
In addition, when I Analyze Images, the pipeline executes a Global thresholding even when the Adaptive threshold is selected and saved.

I got this far in debugging:

>I think I see what happened- when you just change from Global (with Robust Background) to Adaptive (which only supports Otsu), the GUI is switching to Otsu and *displaying* Otsu to you, but it still "remembers" that the last threshold strategy *you chose* was RobustBackground, which only is available from Global, so it switches you from Adaptive to Global so that you can use your preferred thresholding algorithm.  If in Global mode I switch from RobustBackground to Otsu and *then* switch from Global to Adaptive, it remembers my choice just fine (see attached).  It seems to be something specific about RobustBackground- if I switch from "Global/Manual" to "Adaptive/Otsu", it save just fine for me. 

Non-working version of the pipeline here:
[dead50_v0_20151028.cpproj.zip](https://github.com/CellProfiler/CellProfiler/files/3103972/dead50_v0_20151028.cpproj.zip)

**Comment by DavidStirling** [comment]
I'm struggling to replicate this on Master or 3.1.9. The save format is different in both versions but there still doesn't seem to be a problem. It looks like there is a separate Threshold Method setting for global vs adaptive thresholding. Switching strategies changes which set of settings is currently displayed but doesn't change the other set as that's stored elsewhere in the file.

Unless there's a particular quirk in the 3.1.8 build I can't see a reason that loading would fail to recognise adaptive settings. Perhaps there's something wrong with the settings upgrade functions and the pipelines being loaded are from another version?

**Comment by bethac07** [comment]
Definitely still present in 319, haven't checked in master yet.
