### ISSUE TITLE
Add Image File and Folder Names to Object Table

### ISSUE THREAD

**Issue by tischi** [CellProfiler/CellProfiler#3739]
Hello,

It would be great if the file and folder names of both  input images as well as of any saved images (such as segmentation overlays) could be added to an objects output table. 

The use case is that one could, in a downstream analysis, easily see from which images the object measurements are derived (and also check the corresponding object segmentations).

See also the discussion here:
https://forum.image.sc/t/cellprofiler-combined-image-and-objects-table/25053/6

**Comment by bethac07** [comment]
Endordsed if we do it as an toggle-a-ble option- there have been multiple times people have asked for this, and on more than one occasion I've "hacked" this by manually extracting the image and path names in the Metadata module so that I could add it to the image spreadsheet.
