### ISSUE TITLE
ExportToSpreadsheet tries to write into wrong folder (Win 10, CP 3.1.8)

### ISSUE THREAD

**Issue by VolkerH** [CellProfiler/CellProfiler#3756]
I observed this bug in CP 3.1.8 (binary distribution) on Windows 10:

In `ExportToSpreadsheet` I select the output location `Elsewhere` and click the little folder button to bring up a folder select dialog. In the Dialog I select the folder `C:\Users\Volker\Data\`

The elsewhere gets changed automagically to Default Input-folder subfolder
![image](https://user-images.githubusercontent.com/2210044/58615810-5c667280-82ff-11e9-9e6c-ec59e772b55d.png)
but that still looks correct.

However, during the actual run, Cellprofiler seems to try and write into its own Program Folder, which is not permitted under Windows 10, so I run into this:
![image](https://user-images.githubusercontent.com/2210044/58615651-f4179100-82fe-11e9-8669-d331bdcab2d8.png)

I have a feeling that it somewhere the default input folders get messed up.

**Comment by DavidStirling** [comment]
A bit late, but I haven't been able to replicate this. Was your default input folder actually set to C:?

**Comment by VolkerH** [comment]
I have not looked at this in a while and can't remember. I have a project for which I will use Cellprofiler coming up next month and I will see whether the Problem shows up again.

**Comment by altairwei** [comment]
Same problem:

`Experiment.csv` was saved to `C:\Program Files (x86)\CellProfiler`. If I run CellProfiler without Administrator privilege, the whole workflow will hang on `ExportToSpreadsheet` step.

![Snipaste_2020-02-21_09-29-15](https://user-images.githubusercontent.com/30854075/74995748-b6f6be80-548c-11ea-9678-9a5e10d1c2a1.png)

**Comment by DavidStirling** [comment]
Great, thanks.

@altairwei could you also confirm what your default input/output folders are set to?

Experiment.csv typically doesn't respect metadata blocks in the path since it's written without a specific image (and therefore metadata) associated with it - see #1110. I'm wondering if in the absence of a valid path it's defaulting to CellProfiler's install directory.

**Comment by altairwei** [comment]
> Great, thanks.
> 
> @altairwei could you also confirm what your default input/output folders are set to?
> 
> Experiment.csv typically doesn't respect metadata blocks in the path since it's written without a specific image (and therefore metadata) associated with it - see #1110. I'm wondering if in the absence of a valid path it's defaulting to CellProfiler's install directory.

![Snipaste_2020-02-21_11-24-49](https://user-images.githubusercontent.com/30854075/75001602-d1389880-549c-11ea-9ee9-a84323942557.png)

**Comment by DavidStirling** [comment]
Thanks, looking into this it appears that the 'elsewhere' option isn't being validated properly. It's supposed to be a complete path rather than just a folder name, but is defaulting to the install directory. I'm making some changes which should address both of these scenarios.

**Comment by altairwei** [comment]
> Thanks, looking into this it appears that the 'elsewhere' option isn't being validated properly. It's supposed to be a complete path rather than just a folder name, but is defaulting to the install directory. I'm making some changes which should address both of these scenarios.

Actually, in my case, `InputFolder` variable contains absolute path not just a folder name.

**Comment by DavidStirling** [comment]
Ah I see. Nonetheless because metadata blocks don't get applied when saving
experiment.csv (since this file exists outside of the pipeline image
groups) the blocks get ignored and it tries to save to the default path -
the install directory.
