### ISSUE TITLE
python and cellprofiler

### ISSUE THREAD

**Issue by dayya** [CellProfiler/CellProfiler#3770]
Does python run the cell profiler by installing the cell profiler in the python environment?
CellProfiler as a Python package, how to install or run cell profiler in Python environment

**Comment by bethac07** [comment]
CellProfiler downloaded as an executable includes its own python; if you want to install CellProfiler from source to run in Python 2, instructions for different operating systems are included in our [wiki](https://github.com/CellProfiler/CellProfiler/wiki).  Hope that helps!

**Comment by AnneCarpenter** [comment]
See also https://forum.image.sc/t/python-or-other-machine-languages-are-associated-with-cell-profiler/26769

**Comment by dayya** [comment]
> "CellProfiler downloaded as an executable includes its own python"    Where can I download it?

**Comment by AnneCarpenter** [comment]
cellprofiler.org
