### ISSUE TITLE
How to run headless CellProfiler with Docker

### ISSUE THREAD

**Issue by ncernek** [CellProfiler/CellProfiler#3774]
Hi, 
I am trying to run CellProfiler on a linux VM using [the docker image](https://hub.docker.com/r/cellprofiler/cellprofiler). I am able to successfully install the image, but when I run `docker run -t cellprofiler/cellprofiler` a container is created, outputs help docs to the console, and then exits. When I check `docker ps -a` I can verify that the container exited. So I am not able to use the cellprofiler CLI. Is there a different command I should use to start CellProfiler?

Thanks.

**Comment by bethac07** [comment]
It looks like from the [distribution repo](https://github.com/CellProfiler/distribution/tree/master/docker) the thought was that people would be using it to run the GUI, not necessarily headless; you could certainly update the init conditions or use it as the basis of [another Docker](https://github.com/CellProfiler/Distributed-CellProfiler/blob/master/worker/Dockerfile) that adds on other packages and desired behaviors, as we do in our Distributed-CellProfiler tool.

**Comment by DavidStirling** [comment]
Closing, please re-open if you're still having issues.
