### ISSUE TITLE
Fix faulty registry keys on Windows 10

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3775]
(Happens whether or not built CP 3+ has ever been installed on that machine, generating reg keys).  

```Traceback (most recent call last):
  File "c:\users\administrator\documents\github\cellprofiler\cellprofiler\cellprofiler\gui\app.py", line 70, in OnInit
    if cellprofiler.preferences.get_telemetry_prompt():
  File "c:\users\administrator\documents\github\cellprofiler\cellprofiler\cellprofiler\preferences.py", line 1286, in get_telemetry_prompt
    if not config_exists(TELEMETRY_PROMPT):
  File "c:\users\administrator\documents\github\cellprofiler\cellprofiler\cellprofiler\preferences.py", line 261, in config_exists
    return get_config().Read(key) is not None
wx._core.wxAssertionError: C++ assertion "!IsNumericValue(szValue)" failed at ..\..\src\msw\registry.cpp(1041) in wxRegKey::QueryValue(): Type mismatch in wxRegKey::QueryValue().
OnInit returned false, exiting...
```

**Comment by DavidStirling** [comment]
Something similar currently pops up if you try to run analysis on master, when the get_preferences_as_dict function is called.

I've been looking into this. You can bypass this error by removing STARTUPBLURB, TELEMETRY and TELEMETRY_PROMPT from the keys dictionary in preferences.py. Interestingly on my machine these are all they keys stored as REG_DWORD, despite them supposedly being boolean. Everything else is REG_SZ aside from worker count.

Not sure if it's related, but there's something weird going on in the registry. Might be linked to #3865.
