### ISSUE TITLE
Resizing the pipeline panel leads to various errors

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3779]
No stack trace generated
![image](https://user-images.githubusercontent.com/6721515/60455901-bfe90600-9c05-11e9-9482-7643774fc88f.png)
![image](https://user-images.githubusercontent.com/6721515/60455914-c8d9d780-9c05-11e9-9b79-005e8398f4fb.png)

**Comment by DavidStirling** [comment]
Also appears to be fixed.
