### ISSUE TITLE
IdentifyDeadWorms error in CellProfiler 3.1.8

### ISSUE THREAD

**Issue by vavylonis** [CellProfiler/CellProfiler#3788]
We found out that while IdentifyDeadWorms works ok in the 2.2.0 version of CellProfiler, the following error occurs in versions 3.1.8. This was reproduced by the developer of the module. 
 
![error_message](https://user-images.githubusercontent.com/12641415/60618232-a41b6680-9da3-11e9-99db-6363bd9c01b9.PNG)

**Comment by bethac07** [comment]
Resolved by #4200
