### ISSUE TITLE
Numpy error running CP3 batch from linux command line

### ISSUE THREAD

**Issue by NickCastello** [CellProfiler/CellProfiler#3793]
I'm trying to run a batch file on a machine running CP3 (stable release) on CentOS7. Here's the error:

```
(cp) [nick@dflufb06875 CellProfiler]$ python -m cellprofiler -p /mnt/finkbeinerlab/robodata/AJ_group/AJ-AI-190628-LC3ms-autophagy-modulators/Batch_data.h5 -r -c
Version: 2018-09-26T02:09:47 74da042fb / 20180926020947
Failed to stop Ilastik
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "/home/nick/repos/CellProfiler/cellprofiler/__main__.py", line 252, in main
    run_pipeline_headless(options, args)
  File "/home/nick/repos/CellProfiler/cellprofiler/__main__.py", line 859, in run_pipeline_headless
    from cellprofiler.pipeline import Pipeline, EXIT_STATUS, M_PIPELINE
  File "cellprofiler/pipeline.py", line 41, in <module>
    import cellprofiler.objects as cpo
  File "cellprofiler/objects.py", line 5, in <module>
    from centrosome.cpmorphology import all_connected_components
  File "/home/nick/miniconda3/envs/cp/lib/python2.7/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "__init__.pxd", line 918, in init centrosome._cpmorphology2
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
Failed to stop Ilastik
Traceback (most recent call last):
  File "/home/nick/miniconda3/envs/cp/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/nick/miniconda3/envs/cp/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nick/repos/CellProfiler/cellprofiler/__main__.py", line 934, in <module>
    main()
  File "/home/nick/repos/CellProfiler/cellprofiler/__main__.py", line 252, in main
    run_pipeline_headless(options, args)
  File "/home/nick/repos/CellProfiler/cellprofiler/__main__.py", line 859, in run_pipeline_headless
    from cellprofiler.pipeline import Pipeline, EXIT_STATUS, M_PIPELINE
  File "cellprofiler/pipeline.py", line 41, in <module>
    import cellprofiler.objects as cpo
  File "cellprofiler/objects.py", line 5, in <module>
    from centrosome.cpmorphology import all_connected_components
  File "/home/nick/miniconda3/envs/cp/lib/python2.7/site-packages/centrosome/cpmorphology.py", line 12, in <module>
    from ._cpmorphology2 import skeletonize_loop, table_lookup_index
  File "__init__.pxd", line 918, in init centrosome._cpmorphology2
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
Any ideas what's going on here? Let me know what other info I can provide to help troubleshoot.

**Comment by gmstanle** [comment]
This is similar to the error I get in a fresh Conda python 2.7 environment on Linux Mint (aka Ubuntu 16.04)

Here is my install error after creating a totally fresh Conda python=2.7 environment and downloading CellProfiler fresh from Github:

pip install --user --editable .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining file:///home/geoffstanley/apps/CellProfiler
ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
File "", line 1, in 
File "/home/geoffstanley/apps/CellProfiler/setup.py", line 48, in 
importlib.import_module(import_name)
File "/home/geoffstanley/anaconda3/envs/py2/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/home/geoffstanley/.local/lib/python2.7/site-packages/javabridge/init.py", line 38, in 
from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
File "/home/geoffstanley/.local/lib/python2.7/site-packages/javabridge/jutil.py", line 157, in 
import javabridge._javabridge as _javabridge
File "init.pxd", line 861, in init _javabridge (_javabridge.c:28566)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/geoffstanley/apps/CellProfiler/

**Comment by jeffsyang** [comment]
Hey guys, do you know which version of numpy you're using? (you can check by running `conda list | grep numpy` in your activated conda environment). If it's older than version 1.16.4, maybe give updating a shot?

Btw, in my experience working with this project, getting CP to work with Conda was somewhat tricky. I'd suggest using virtualenvwrapper but getting it to work in Conda's doable as well.

**Comment by NickCastello** [comment]
I using numpy==1.16.4 via Conda

**Comment by jeffsyang** [comment]
What happens if you downgrade to numpy==1.15.4?

**Comment by NickCastello** [comment]
I downgraded to numpy 1.15.4 and now get this:

`(cp) [nick@dflufb06875 cellprofiler]$ python -m cellprofiler -p /mnt/finkbeinerlab/robodata/AJ_group/AJ-AI-190723-U251-OA-BODIPY-drugs/Batch_data.h5 -c -r
/home/nick/miniconda3/envs/cp/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load pipeline
Traceback (most recent call last):
  File "/home/nick/repos/CellProfiler/cellprofiler/pipeline.py", line 1141, in loadtxt
    setting = setting.decode("utf-8")
  File "/home/nick/miniconda3/envs/cp/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
/home/nick/repos/CellProfiler/cellprofiler/utilities/hdf5_dict.py:603: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  hdf5_type_is_int = numpy.issubdtype(hdf5_type, int) or (
/home/nick/repos/CellProfiler/cellprofiler/utilities/hdf5_dict.py:606: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  hdf5_type_is_float = numpy.issubdtype(hdf5_type, float)
Times reported are CPU and Wall-clock times for each module
(cp) [nick@dflufb06875 cellprofiler]$ python -m cellprofiler -p /mnt/finkbeinerlab/robodata/AJ_group/AJ-AI-190628-LC3ms-autophagy-modulators/Batch_data.h5 -r -c
/home/nick/miniconda3/envs/cp/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Failed to load pipeline
Traceback (most recent call last):
  File "/home/nick/repos/CellProfiler/cellprofiler/pipeline.py", line 1141, in loadtxt
    setting = setting.decode("utf-8")
  File "/home/nick/miniconda3/envs/cp/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
/home/nick/repos/CellProfiler/cellprofiler/utilities/hdf5_dict.py:603: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  hdf5_type_is_int = numpy.issubdtype(hdf5_type, int) or (
/home/nick/repos/CellProfiler/cellprofiler/utilities/hdf5_dict.py:606: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  hdf5_type_is_float = numpy.issubdtype(hdf5_type, float)
Times reported are CPU and Wall-clock times for each module`


Here's my conda env:

`[nick@dflufb06875 cellprofiler]$ conda list
# packages in environment at /home/nick/miniconda3/envs/cp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
backports.functools-lru-cache 1.5                       <pip>
blas                      1.0                         mkl
boto3                     1.9.185                   <pip>
botocore                  1.12.185                  <pip>
ca-certificates           2019.5.15                     0
cellh5                    1.3.0                     <pip>
CellProfiler              2.3.1                     <pip>
centrosome                1.1.6                     <pip>
certifi                   2019.6.16                py27_1
chardet                   3.0.4                     <pip>
cloudpickle               1.2.1                     <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.4.0                     <pip>
deprecation               2.0.6                     <pip>
docutils                  0.14                      <pip>
enum34                    1.1.6                     <pip>
future                    0.17.1                    <pip>
futures                   3.2.0                     <pip>
h5py                      2.7.0                     <pip>
hmmlearn                  0.2.2                     <pip>
idna                      2.8                       <pip>
imageio                   2.5.0                     <pip>
inflect                   2.1.0                     <pip>
intel-openmp              2019.4                      243
javabridge                1.0.18                    <pip>
javabridge                1.0.14                   py27_0
jmespath                  0.9.4                     <pip>
joblib                    0.13.2                    <pip>
kiwisolver                1.1.0                     <pip>
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
lxml                      4.3.4                     <pip>
mahotas                   1.4.6                     <pip>
matplotlib                2.2.4                     <pip>
mkl                       2019.4                      243
mkl_fft                   1.0.12           py27ha843d7b_0
mkl_random                1.0.2            py27hd81dba3_0
mysql-connector-c         6.1.11               h597af5e_0
MySQL-python              1.2.5                     <pip>
mysqlclient               1.3.13                    <pip>
mysqlclient               1.3.14           py27h7b6447c_0
ncurses                   6.1                  he6710b0_1
networkx                  2.2                       <pip>
numpy                     1.15.4           py27h7e9f1db_0
numpy-base                1.15.4           py27hde5b4d6_0
openssl                   1.1.1c               h7b6447c_1
packaging                 19.0                      <pip>
pandas                    0.24.2                    <pip>
pathlib2                  2.3.4                    py27_0
Pillow                    6.1.0                     <pip>
pip                       19.1.1                   py27_0
prokaryote                2.3.3                     <pip>
pyparsing                 2.4.0                     <pip>
python                    2.7.16               h9bab390_0
python-bioformats         1.4.0                     <pip>
python-dateutil           2.8.0                     <pip>
pytz                      2019.1                    <pip>
PyWavelets                1.0.3                     <pip>
pyzmq                     18.0.1                    <pip>
raven                     6.10.0                    <pip>
readline                  7.0                  h7b6447c_5
requests                  2.22.0                    <pip>
s3transfer                0.2.1                     <pip>
scandir                   1.10.0           py27h7b6447c_0
scikit-image              0.14.3                    <pip>
scikit-learn              0.20.3                    <pip>
scipy                     1.2.2                     <pip>
setuptools                41.0.1                   py27_0
six                       1.12.0                    <pip>
six                       1.12.0                   py27_0
sqlite                    3.28.0               h7b6447c_0
subprocess32              3.5.4                     <pip>
tk                        8.6.8                hbc83047_0
urllib3                   1.25.3                    <pip>
wheel                     0.33.4                   py27_0
zlib                      1.2.11               h7b6447c_3`

**Comment by jeffsyang** [comment]
This is my conda env on Ubuntu 18.04 for tag `v3.1.8`: [cellprofiler318_conda.txt](https://github.com/CellProfiler/CellProfiler/files/3444254/cellprofiler318_conda.txt)

Are you on `master`? Maybe give tag `v3.1.8` a shot?
