### ISSUE TITLE
CellProfiler 3.18 crashes on Mac 

### ISSUE THREAD

**Issue by SBata** [CellProfiler/CellProfiler#3796]
I downloaded the latest stable version of CP for Mac, however as soon as I try to open it, it crashed without even getting to the first screenshot.
I am using OSX 10.14.6
any suggestions?
tnx

**Comment by ranka47** [comment]
@SBata I am using OSX 10.14.5 
I am not facing issues with CP 3.1.8. You may try building it from source by checking out to this commit: https://github.com/CellProfiler/CellProfiler/commit/2eea5ee589a2b8c9a8ad2ae2b8e107c777831128

**Comment by DavidStirling** [comment]
If you're still having trouble, I'd suggest trying to run CellProfiler using [the terminal](https://www.macissues.com/2015/02/06/how-to-launch-os-x-apps-via-the-terminal/). If that fails you should then get some kind of error message which could then be posted here, please re-open this if that happens.
