### ISSUE TITLE
Unsupported background style in Xubuntu 18.04

### ISSUE THREAD

**Issue by pintomollo** [CellProfiler/CellProfiler#3797]
Hello,

I'm trying to install the whole Imaging flow cytometry analysis pipeline on a Xubuntu 18.04 64bits computer. I've followed the instructions for 16.04 and with a bit of tweaking I was able to install both CellProfiler and CellProfiler-Analyst from the Git repositories. I had to install CellProfiler 3.1.8 for it to run on wxPython 3.0.2 together with CellProfiler-Analyst (which doesn't support version 4 of wx).

Now, both start just fine, but CellProfiler gives me an error when I click on any button of the Dialog for the feedback. The whole output is the following (with some warning at the beggining):

03:06:50 PM: Debug: ClientToScreen cannot work when toplevel window is not shown

(cellprofiler:28634): Gtk-WARNING **: 15:06:52.513: Negative content width -4 (allocation 30, extents 17x17) while allocating gadget (node button, owner GtkButton)

[Gtk-WARNING Repeated 18 more times].

Traceback (most recent call last):
  File "/usr/local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler==3.1.8', 'console_scripts', 'cellprofiler')()
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/__main__.py", line 162, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/gui/app.py", line 55, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/gui/app.py", line 74, in OnInit
    telemetry = cellprofiler.gui.dialog.Telemetry()
  File "/usr/local/lib/python2.7/dist-packages/cellprofiler/gui/dialog.py", line 57, in __init__
    self.status = self.ShowModal()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_windows.py", line 805, in ShowModal
    return _windows_.Dialog_ShowModal(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/window.cpp(4232) in GTKSendPaintEvents(): unsupported background style

To be noted that the error is unfortunately not always occurring. I'd say 3 out of 4 times. Also, the error doesn't occur with CellProfiler-Analyst. The installed packages I have are the following:

antlr==2.7.5rc1
asn1crypto==0.24.0
attrs==17.4.0
backports.functools-lru-cache==1.4
beautifulsoup4==4.6.0
boto3==1.9.199
botocore==1.12.199
CellProfiler==3.1.8
CellProfiler-Analyst==2.2.1
centrosome==1.1.6
certifi==2019.6.16
chardet==3.0.4
cloudpickle==1.2.1
contextlib2==0.5.5
cryptography==2.1.4
cvxopt==1.1.9
cycler==0.10.0
Cython==0.26.1
decorator==4.4.0
deprecation==2.0.6
docutils==0.14
enum34==1.1.6
et-xmlfile==1.0.1
funcsigs==1.0.2
future==0.17.1
futures==3.3.0
greenlet==0.4.12
h5py==2.9.0
html5lib==0.999999999
idna==2.6
imageio==2.5.0
inflect==2.1.0
ipaddress==1.0.17
javabridge==1.0.18
jdcal==1.0
jmespath==0.9.4
joblib==0.13.2
keyring==10.6.0
keyrings.alt==3.0
lxml==4.2.1
mahotas==1.4.7
matplotlib==2.1.1
mock==2.0.0
msgpack==0.5.6
mysqlclient==1.3.13
neovim==0.2.0
networkx==2.2
nose==1.3.7
numexpr==2.6.4
numpy==1.16.4
olefile==0.45.1
openpyxl==2.4.9
packaging==19.1
pandas==0.22.0
patsy==0.4.1+dev
pbr==3.1.1
Pillow==5.1.0
pluggy==0.6.0
prokaryote==2.4.1
py==1.5.2
pycrypto==2.6.1
pygobject==3.26.1
pyparsing==2.2.0
pysqlite==1.0.1
pytest==3.3.2
python-bioformats==1.5.2
python-dateutil==2.6.1
pytz==2018.3
PyWavelets==1.0.3
pyxdg==0.25
pyzmq==15.3.0
raven==6.10.0
requests==2.22.0
s3transfer==0.2.1
scikit-image==0.14.3
scikit-learn==0.20.4
scipy==1.2.2
seaborn==0.8.0
SecretStorage==2.3.1
simplejson==3.13.2
six==1.11.0
statsmodels==0.8.0
subprocess32==3.2.7
tables==3.4.2
trollius==2.0.1
urllib3==1.25.3
verlib==0.1
webencodings==0.5
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xlrd==1.1.0
xlwt==0.7.5

I have installed using apt  (among other packages)
:
python-wxgtk3.0/bionic,now 3.0.2.0+dfsg-7 amd64 [installed]

Thank you in advance for your help,
Cheers,
Simon

**Comment by DavidStirling** [comment]
This is hopefully fixed with CellProfiler 4, since we've migrated to a new wx version.
