### ISSUE TITLE
Hitting "Undo" in IdentifyObjectsManually makes drawing unusable

### ISSUE THREAD

**Issue by stalyansky** [CellProfiler/CellProfiler#3814]
I would like to bring to your attention some problems/inconveniences that I have encountered with CellProfiler 3.1.8:
 
•	The “Undo” button of the Identify Objects Manually module is dysfunctional, erasing the most recent marking but keeping the mouse on permanent drawing mode. Thus the only way to revise the drawing for a given frame is to click the “reset” button, which is inconvenient when tracking multiple cells because doing so erases the markings made for all cells.
•	If a cell is inadvertently tracked in the Identify Objects Manually module, or an intended cell is omitted from the tracking, it is impossible to return to a misprocessed frame once the program has proceeded to subsequent frames, which makes it necessary to re-run the misprocessed frame independently, later, and then manipulate the outputted results spreadsheets. The option to redo a frame during analysis would be useful.
•	Currently, it is impossible to save results mid-analysis, which means that, for large image sets, hours of work may be lost if the program crashes or the computer experiences a power outage. A button to export spreadsheets at will for the in-progress results would be of great help.

**Comment by bethac07** [comment]
Hi,

I can reproduce your first issue (error stack below) and have changed the title accordingly as a bug.  

Your second and third issues are not really errors per se.  They have to do with the fact that CellProfiler is ultimately designed not to do much interactive analysis but to do high content work (it certainly can do both, but it was designed for high content).

* For your second issue, whenever there is a manual identification step with Identify/EditObjectsManually I always strongly recommend that users do that identification step as its own pipeline with the ID/Edit step and then ConvertObjectsToImage and SaveImage, then load those as objects in a downstream analysis pipeline- that way you only have to do the manual step once, and it's easy to fix individual images/frames.

* For your third issue, why not use ExportToDatabase, which does indeed write results on the fly? You can always export the tables later as spreadsheets in Python/R/a free GUI program like DBBrowser, etc.  

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 387, in process
    proxy(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/editobjectsdlg.py", line 1110, in on_mouse_button_up
    self.on_mouse_button_up_freehand_draw_mode(event)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/editobjectsdlg.py", line 1758, in on_mouse_button_up_freehand_draw_mode
    self.labels[0][mask] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 88 but corresponding boolean dimension is 199
```

**Comment by stalyansky** [comment]
Thank you very much for your response and advice! I will try your
suggestions and let you know if I have any more issues.

With appreciation,

Seth
