### ISSUE TITLE
Bug in IdentifyObjectManually numpy

### ISSUE THREAD

**Issue by ncboles** [CellProfiler/CellProfiler#3815]
Standard install cellprofiler 3.1.8 on windows 10 pro. Got error says:
Error while processing IdentifyObjectManually : numpy boolean substract, the ‘-’ operator, is deprecated, use the bitwise_xor, the ‘^’ operator, or the logical_xor function instead.

**Comment by bethac07** [comment]
Hi,

Can you say what you were doing when you got that error? I can't reproduce.

**Comment by AnneCarpenter** [comment]
If you can provide the .cppipe and example image set, that would be even better, @ncboles

**Comment by DavidStirling** [comment]
Unable to replicate this on Master after trying just about every function in the module. Can't find any use of this operator in IdentifyObjectsManually either, so it's possibly in another module somewhere. Looks like this is only a deprecation warning so it's not strictly broken. Please feel free to re-open this with further details if it's found again.
