### ISSUE TITLE
What am I supposed to use as input data for the "3d monolayer" tutorial?

### ISSUE THREAD

**Issue by bersbersbers** [CellProfiler/CellProfiler#3826]
I am currently giving https://github.com/CellProfiler/tutorials/tree/master/3d_monolayer a try. As potential input data, I only see  `3d_monolayer_xy1_ch0.tif`, `3d_monolayer_xy1_ch1.tif` and `3d_monolayer_xy1_ch2.tif`. Obviously, those have nothing to do with the suggested regular expression `^(?P<Plate>.*)_xy(?P<Site>[0-9])_ch(?P<ChannelNumber>[0-9])`, so my guess is that I am supposed to use a different set of input data.

Furthermore, the tutorial does not address how to set different names for different images. In my case, having loaded the three images above, all three images are labeled "DNA", and in each of the three suggested RescaleIntensity modules, I can only select the same single "DNA" entry.

**Comment by DavidStirling** [comment]
Excuse the late response on this, but those are indeed the correct images. The expression you mention is designed to pull out the relevant channel information from those filenames.

I'll add some further text to the tutorial to clarify how to actually reference the images as channels.
