### ISSUE TITLE
Installation Error with Source Code

### ISSUE THREAD

**Issue by lwashbur** [CellProfiler/CellProfiler#3827]
I'm having an issue installing the source code (MacOS), when I get to the install CellProfiler part.  When I run, I get this:

`RuntimeError: Scikit-learn requires Python 3.5 or later. The current Python version is 2.7.16 installed in /usr/local/opt/python@2/bin/python2.7.`

Any idea how to fix this?

**Comment by ranka47** [comment]
Try these version settings, it works in my environment of CellProfiler 3.1.8
scikit-image                  0.14.2                 
scikit-learn                    0.20.3

**Comment by DavidStirling** [comment]
Dependency lists should now be up to date
