### ISSUE TITLE
python version error installing on Linux with conda

### ISSUE THREAD

**Issue by rbatorsky** [CellProfiler/CellProfiler#3833]
Hello,

I've run into a problem installing on linux (red hat 6.9) with anaconda.
Following #3787 I modified the enviornment.yml that is posted in conda instructions to be:
```
name: cellprofiler
channels:
  - anaconda
  - goodman # mysql-python for mac
  - bioconda
  - cyclus # java-jdk for windows
  - conda-forge # libxml2 for windows
  - daf
dependencies:
  - appdirs
  - boto3
  - cython
  - h5py
  - ipywidgets
  - java-jdk
  - joblib
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python=2.7.16
  - pyzmq=15.3.0
  - mahotas
  - matplotlib!=2.1.0,>2.0.0
  - mysqlclient
  - numpy
  - raven
  - requests
  - scikit-image>=0.13
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - wxpython=3.0.2.0
  - pip:
    - cellh5
    - centrosome
    - inflect
    - prokaryote==2.4.0
    - javabridge==1.0.15
    - python-bioformats==1.4.0
    - git+https://github.com/CellProfiler/CellProfiler.git@master
```
The error I get is:
```
Collecting git+https://github.com/CellProfiler/CellProfiler.git@master (from -r /cluster/kappa/90-days-archive/bio/tools/conda_envs/cellprofiler/condaenv.81y5a_3o.requirements.txt (line 7))
  Cloning https://github.com/CellProfiler/CellProfiler.git (to revision master) to /tmp/pip-req-build-GzGy1s
  Running command git clone -q https://github.com/CellProfiler/CellProfiler.git /tmp/pip-req-build-GzGy1s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
ERROR: Package u'CellProfiler' requires a different Python: 2.7.16 not in '>=3.7'

CondaValueError: pip returned an error
```
I notice the line 84 in setup.py has the requirement:
```
    python_requires=">=3.7",
```
But earlier in the file it states that python 2.7 is used, so there appears to be a discrepancy.

Thank you for your advice.
Rebecca

**Comment by bethac07** [comment]
We're in the process of transitioning to Python3; for now, it's probably safest rather than collecting 
`git+https://github.com/CellProfiler/CellProfiler.git@master`, grabbing `git+https://github.com/CellProfiler/CellProfiler.git@v3.1.8`

**Comment by rbatorsky** [comment]
Thank you, that worked nicely.

I'm moving on to install CellProfiler Analyst also on Linux (RHEL 6) on an HPC cluster without access to root protected locations. I see instructions here require either sudo access or access to any of the /usr/local/ or /opt/ directories:
https://github.com/CellProfiler/CellProfiler-Analyst/wiki/Source-installation-(Ubuntu-15.10)

Is there any way to install in custom locations? If yes, is this expected to work on other Linux distros as long as dependencies are installed?

Thank you again for your help.
Best,
Rebecca

**Comment by rbatorsky** [comment]
Hello,

I'm still struggling to get cellprofiler 3.1.8 up and running in a conda env on Linux. 
My installation works fine on the command line, running a pipeline, e.g.:
```
cellprofiler -p SimplePipeline_CountObjects.cppipe -r -c -i input/ -o output/
```
But my GUI wont start.  The problem seems to be with wxpython, which maybe is similar to the issue #3838.  If I understand correctly, wxpython 3.0.2.0 is required, but it doesn't seem to install correctly using any of the repositories I've tried. There are different errors if wxpython >=4.0 is used.

I used this to install 3.0.2.0:
```
conda install -c daf wxpython
```

The error:
```
cellprofiler
Traceback (most recent call last):
  File "/cluster/tufts/bio/tools/conda_envs/cellprofiler_v3.1.8/bin/cellprofiler", line 10, in <module>
    sys.exit(main())
  File "/cluster/tufts/bio/tools/conda_envs/cellprofiler_v3.1.8/lib/python2.7/site-packages/cellprofiler/__main__.py", line 146, in main
    import cellprofiler.gui.app
  File "/cluster/tufts/bio/tools/conda_envs/cellprofiler_v3.1.8/lib/python2.7/site-packages/cellprofiler/gui/app.py", line 12, in <module>
    import wx
  File "/cluster/tufts/bio/tools/conda_envs/cellprofiler_v3.1.8/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/cluster/tufts/bio/tools/conda_envs/cellprofiler_v3.1.8/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libjbig.so.0: cannot open shared object file: No such file or directory
```
It seems some library is missing. I never had to link libraries with conda envs before, so I'm thinking something is wrong.  Any help would be appreciated. 

Thank you again!
Rebecca

**Comment by fahsan** [comment]
@rbatorsky Were you able to find a solution to this issue? I seem to have stumbled on this issue as well when attempting to install the v.3.1.9 release on a CentOS6 HPC cluster.
