### ISSUE TITLE
Notes don't save in 3.1.8

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3839]
@ErinWeisbart reported- Erin, can you confirm CP version, built or installed from source, and MacOS version on the machine in question? Also, do the notes not show up in a .cpproj file, and/or when you export as a cppipe?

**Comment by ErinWeisbart** [comment]
In both 3.1.8 and 3.1.9 if I open a .cpproj, edit only notes, and save it as a .cpproj, when I opened it again my new notes ARE NOT saved. If I open a .cpproj, edit only notes, and save it as a .cppipe then the new notes DO save.

I'm running macOS 10.14.6. CP 3.1.8 source and 3.1.9 built.
