### ISSUE TITLE
Missing Zernike option in MeasureObjectIntensityDistribution

### ISSUE THREAD

**Issue by cfabrito** [CellProfiler/CellProfiler#3840]
Hello,
I've been using CellProfiler for the past week and even without any prior experience in this sort of software I've found it to have a very intuitive interface. Thank you for making it available!
On to the issue, on the [documentation ](http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.0.0/modules/measurement.html#measureobjectintensitydistribution) it reads that the MeasureObjectIntensityDistribution module can measure FracAtD, MeanFrac, RadialCV and Zernike. However the Zernike option is not listed in the heatmap generation section on the latest version (3.1.8):
![image](https://user-images.githubusercontent.com/6804379/64920831-c2460f80-d7b3-11e9-82af-a6c9ebfa6883.png)
Are any additional steps necessary for obtaining this output? Am I doing something wrong?
Thanks in advance!

**Comment by DavidStirling** [comment]
Sorry for the late response! Unlike measures such as Radial CV, Zernike measurements aren't a single statistic as they involve multiple polynomials which staining is compared to. It's therefore not really practical to display this as a heatmap without having dozens of options for showing each individual feature. You'll still get all of these measurements in the actual output table, there just isn't a heatmap display for them.
