### ISSUE TITLE
Solidity returns a value >1

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3841]
H/T [the forum](https://forum.image.sc/t/solidity-greater-1/29256);

>When using the Solidity measure in CellProfiler, we get values greater than 1. By definition, Solidity cannot be greater than 1. Anyone had this problem before?

Zoom in of offending area below, and pipeline/image to reproduce are attached (I've reproduced in Mac 3.1.8 and 3.1.9 built).  This is calculated in [centrosome](https://github.com/CellProfiler/centrosome/blob/313d0ddcc23574521688da8fa111d89f50321cc5/centrosome/cpmorphology.py#L2466-L2477) based on centrosome's [convex hull area implementation
](https://github.com/CellProfiler/centrosome/blob/313d0ddcc23574521688da8fa111d89f50321cc5/centrosome/cpmorphology.py#L2466-L2477), so guessing the fix may ultimately end up being over there but I haven't rigorously checked yet.

![image](https://user-images.githubusercontent.com/6721515/65173095-266b0c80-da1c-11e9-9130-e7a45383c57d.png)

[SolidityBug.zip](https://github.com/CellProfiler/CellProfiler/files/3627744/SolidityBug.zip)

**Comment by DavidStirling** [comment]
This does indeed look to be on Centrosome's end. It seems that with very small and irregularly shaped objects (1-2 pixels wide at some points) the convex hull area is calculated as smaller than the pixel count for an object's area, producing a solidity >1. Unfortunately the code for calculating the convex hull is very complicated. Would it be worth trying out skimage's implementation, or as a dirtier fix we could consider capping solidity at 1?
