### ISSUE TITLE
question: run cellprofiler UI in browser ?

### ISSUE THREAD

**Issue by sunyi000** [CellProfiler/CellProfiler#3844]
I'm just wondering if it's possible and how to run cellprofiler UI as a web application within a browser?

Is it easy/possible to port everything into javascript using tools like emscripten etc?

Thanks very much

**Comment by AnneCarpenter** [comment]
Not that I know of! 

CellProfiler can be run headless at least, from the command line:
https://github.com/CellProfiler/CellProfiler/wiki/Adapting-CellProfiler-to-a-LIMS-environment#head

Also note that we are building a web app, Piximi, to replace CellProfiler Analyst: https://github.com/piximi/application i

**Comment by DavidStirling** [comment]
To add to what Anne said, there are currently no plans to have a web-based UI. The closest scenario in the future might be some integration with Jupyter, although that still wouldn't include the desktop interface.
