### ISSUE TITLE
Update CellProfiler installation instructions and/or FAQ w javabridge tip

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3847]
see below:

Solved with a fix for installing `python-javabridge` as outlined here: https://github.com/LeeKamentsky/python-javabridge/issues/152

It would be very helpful to add this also to the CellProfiler installation instructions and/or FAQ.

_Originally posted by @emmenlau in https://github.com/CellProfiler/CellProfiler/issues/3846#issuecomment-539044039_

**Comment by bethac07** [comment]
Going to a new version called python-javabridge, and not sure this issue applies there.  Closing, will reopen if issue returns.
