### ISSUE TITLE
Can/should individual module settings' help be in the manual?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3854]
I'm pretty sure you used to be able to read about settings in the manual, e.g. here: 
http://cellprofiler-manual.s3.amazonaws.com/CellProfiler-3.0.0/modules/objectprocessing.html#identifyprimaryobjects

Maybe it's intentional that you can't anymore?

**Comment by bethac07** [comment]
It's hard to do with the new manual system, we decided to abandon- https://github.com/CellProfiler/CellProfiler/issues/3177#issuecomment-329778310
