### ISSUE TITLE
v3.1.8 Unable to access the X Display; Load pipeline headless

### ISSUE THREAD

**Issue by hissingpanda** [CellProfiler/CellProfiler#3860]
Trying to run cellprofiler within python and I'm given the following error when attempting to load my pipeline file.

```
import cellprofiler.pipeline
pipeline = cellprofiler.pipeline.Pipeline()
pipeline.load("example.cppipe")

Unable to access the X Display, is $DISPLAY set properly?
```

Python then quits as there's not display set. How can I load a pipeline in a headless mode without a display?

**Comment by hissingpanda** [comment]
Nevermind I found this with the following commands in the test_loaddata.py module

`
import cellprofiler.preferences
cellprofiler.preferences.set_headless()
`

**Comment by kojca-vsso** [comment]
With new version:
```
from cellprofiler_core.preferences import set_headless
set_headless()
```
