### ISSUE TITLE
Pressing 'undo' on a new pipeline renders it unusable.

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#3864]
Accidentally found this by using keyboard shortcuts on the wrong window. When opening CellProfiler or starting a new project it's possible to use Edit->Undo or Ctrl+Z, which bricks the pipeline by deactivating the input modules.

I think the initial setup is being recorded as a step that can be reverted. I'm not sure if there's any use for being able to do so.

**Comment by AnneCarpenter** [comment]
wow, that was a sneaky one! Good find!
