### ISSUE TITLE
ImportError: No module named tifffile

### ISSUE THREAD

**Issue by algebio** [CellProfiler/CellProfiler#3867]
Hi 

I'm having a problem with CellProfiler because of tifffile (see below). I have checked that this module is installed in Anaconda and I have also installed it in Python.

Any ideas of how to solve this?

Thanks
Juan

font search path ['C:\\Users\\njo47\\AppData\\Local\\Temp\\_MEI14~1\\mpl-data\\fonts\\ttf', 'C:\\Users\\njo47\\AppData\\Local\\Temp\\_MEI14~1\\mpl-data\\fonts\\afm', 'C:\\Users\\njo47\\AppData\\Local\\Temp\\_MEI14~1\\mpl-data\\fonts\\pdfcorefonts']
generated new fontManager
Could not load saveimages_ilastik
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 325, in add_module
  File "C:\Program Files (x86)\CellProfiler\ImcPluginsCP-develop-cp3\plugins\saveimages_ilastik.py", line 47, in <module>
    import tifffile
ImportError: No module named tifffile
could not load these modules: saveimages_ilastik

**Comment by bethac07** [comment]
If this is a plugin module that adds an extra dependency, you need to be running CellProfiler from source, not built- can you confirm that's the case here? I'm just concerned by the `C:\Program Files` path.  The reason is that if you run from built, CellProfiler is running its own copy of Python, not your system's, so packages you install with Conda or into your system python don't matter.

**Comment by algebio** [comment]
Hi 
Thank you for your help. I tried to use CP from source but I ended up having even more error messages there. I went back to CP built and I realised that it works even without loading tifffile, so I'll use the built CellProfiler.

Regards
Juan

**Comment by new2py** [comment]
I am wondering whay does it mean to use this from source? I am using a program called foxtrot and I am encountering an error "ImportError: No module named tifffile"

Maybe if I used foxtrot from source that would help?
