### ISSUE TITLE
Update TrackObjects documentation

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3875]
- [x] Explain that in "Filter objects by lifetime" that the option only works in ExportToSpreadsheet NOT ExportToDatabase 
- [x] Explain that the images aren't accurate either if you are filtering tracks by lifetime, not just when you are using the second phase in LAP

**Comment by DavidStirling** [comment]
Is lifetime filtering definitely only for Spreadsheet, not Database export? I thought it was the other way around.

**Comment by bethac07** [comment]
Yup, just checked it again.
