### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by nataliep4d** [CellProfiler/CellProfiler#3880]
Hi, trying to install CP3.0 on a Windows 7 computer and get the following screen when I start the program (the window collapses within seconds)
![CP installation problem](https://user-images.githubusercontent.com/59295538/71533178-42e4d380-28ac-11ea-9611-845c634c3e3c.jpg)

**Comment by bethac07** [comment]
Can you confirm you're trying to install 3.0.0, as opposed to 3.1.9, our current release?

**Comment by nataliep4d** [comment]
Sorry, we tried the current release 3.1.9. We were able to install it on 2 out of 4 computers without problems.

**Comment by DavidStirling** [comment]
There should be less installation difficulties when 4.0 releases, please feel free to re-open this if you're still having trouble.
