### ISSUE TITLE
Analysis problem

### ISSUE THREAD

**Issue by nataliep4d** [CellProfiler/CellProfiler#3881]
Hi,
I have started a simple nuclei counting routine, and it was continuing beautifully for about an hour, analyzing over a thousand images. Then I started getting the following error messages. I had to stop the run. When I tried to restart it, I started getting the same errors from the very beginning.
What could it be?
Many thanks!
![CP run issue](https://user-images.githubusercontent.com/59295538/71533293-c7cfed00-28ac-11ea-9aaa-62723ec48ec4.jpg)

**Comment by bethac07** [comment]
Do you have the "eyes" open on your pipeline? That error typically refers to when CellProfiler runs out of display windows to make.  Closing and restarting CellProfiler will allow the count to "reset".

**Comment by nataliep4d** [comment]
thank you! I'll try closing all eyes.
