### ISSUE TITLE
Consider making execution time a float rather than a varchar

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3884]
This would be helpful for cytominer-database, which is having issues of it sometimes having a type of int64(when 0) and sometimes of double (when not 0).

cc @diskontinuum

https://github.com/CellProfiler/CellProfiler/blob/4a9d0145b955cc3ff6fa9a783288b3a72682f0ca/cellprofiler/pipeline.py#L3776-L3784

**Comment by 0x00b1** [comment]
@bethac07 I fucked this up!
