### ISSUE TITLE
Add feedback for 'Extract Metadata from Image File Headers' feature.

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#3887]
At present extracting metadata from file headers requires the user to press an 'Update metadata' button. However, there is currently no feedback mechanism to tell the user whether this has been done or still needs to be executed. At present users can update the metadata preview without running this function, which is acceptable behaviour but leads to confusion as they tend to proceed without extracting this metadata.

I think we should have some sort of display for whether header metadata has been extracted or not. A line of text under the extraction button saying 'Not yet extracted' or something might do. Alternatively we could just have the extraction button flash yellow to make it more obvious.

**Comment by bethac07** [comment]
A potentially even better option would be to, in addition to visually highlighting the Update Metadata button more, would be to disable the lower "Update" button until it is hit, making it impossible for the user to proceed until they've done that step.
