### ISSUE TITLE
Update "Add a single image" in NamesAndTypes

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#3893]
Currently in the NamesAndTypes module to "Add a single image" you have to individually browse to add each image.
 
In the uncommon circumstance where someone has a lot of different image correction images to add, this is frustratingly slow. (e.g. the pipeline I'm working on right now has 45 different illumination correction images).
  
Though this is admittedly quite unusual, my experience would be so much better at the moment if there was the option to:
  
1) paste text into the "Single image location" field instead of only having the option to browse for the location
or
2) select multiple images to add at once through the Browse
or
3) drag and drop single images in instead of browsing for them

**Comment by bethac07** [comment]
We don't usually recommend "single image location" much anymore for this exact reason.

**Comment by bethac07** [comment]
Closing as won'tfix, since we probably just want to keep handling these with NamesAndTypes and matching when we get this many, but if someone feels strongly about it feel free to reopen and rebut!
