### ISSUE TITLE
Fn+Delete shortcut on mac removes entire Module (instead of deleting character)

### ISSUE THREAD

**Issue by DeboraOlivier** [CellProfiler/CellProfiler#3904]
Hi,
something really annoying, but the Fn-Delete shortcut I use regularly (Delete the character to the right of the insertion point) REMOVES the entire module rather than deleting the character.
this is pretty annoying when renaming databases or names within modules.
Cheers

Debbi

**Comment by DavidStirling** [comment]
Can't replicate this with CellProfiler 4 (Windows or OSX), so it might be fixed. Could you re-open this if you still have trouble once the new version is out?

**Comment by DeboraOlivier** [comment]
sure - Allen wanted me to try CP4 out so I can chekc then! any idea of when
it's coming out?
cheers

Debbi

**Comment by DavidStirling** [comment]
In the next few weeks, ideally. You could try one of the release candidates if you're feeling brave!

**Comment by DeboraOlivier** [comment]
Could do, am home alone and kid free :-)
