### ISSUE TITLE
IdentifyPrimaryObjects - see intermediate filtering steps to help optimization

### ISSUE THREAD

**Issue by DeboraOlivier** [CellProfiler/CellProfiler#3907]
Hi,
would it be possible to have a visual output for the different filter options in the module so that, for instance, I could see what a smoothing filter size 20 gives compared to using low resolution image, or where the identified maxima are etc.
Basically I would like (in an ideal world) an ouput window with:
1) original
2) original after threshold applied
3) original after applzing smoothing filter with identified maxima for declumping
4) low resolution image (with identified maxima) - if option is selected
5) segmented outlines

This would help optimizing and understanding the different parameters in TEST mode.
CHeers
Debbi

**Comment by DavidStirling** [comment]
I hope we could add an option to plot detected maxima on the outlines display. Otherwise we're already using the standard 2x2 plots in this module, so perhaps allowing the background image which outlines are plotted on to be changed to an intermediate step might help.
