### ISSUE TITLE
CellProfiler crashes when you hit the column name in "Choose image set"

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3939]
Reported in a tutorial for Windows 3.1.9; not sure if still in master. @DavidStirling as our windows guru can you check?

**Comment by DavidStirling** [comment]
Can replicate in 3.1.9, can't replicate in Master. I guess it's either fixed by wx4 or specific to built versions.

**Comment by bethac07** [comment]
Cool, thanks for doing that so fast! Let's leave this open as a note to ourselves to check when we've built wx4, but I expect it's likely fixed.

**Comment by DavidStirling** [comment]
Confirmed as fixed when frozen.
