### ISSUE TITLE
ExpandOrShrinkObjects drops some objects (filling holes)

### ISSUE THREAD

**Issue by NasimJ** [CellProfiler/CellProfiler#3965]
I noticed when I shrink nuclei (by 8 pixels; the smallest detected nuclei is 10 pixels), and then relate objects to another primary object, I'm missing some of the nuclei.
To distinguish this issue from [this](https://github.com/CellProfiler/CellProfiler/issues/3645) one:
For Nuclei IPO, filling holes after declumping
for the other IPO: filling holes after both thresholding and declumping

![CSVFilesComparison](https://user-images.githubusercontent.com/55710463/77792939-a31c1a80-703f-11ea-8a05-ea5c5faa524b.png)

Relating objects:
![Compare](https://user-images.githubusercontent.com/55710463/77793083-dc548a80-703f-11ea-9549-e73bd1ff778b.png)

Some of the missing ones:
![ShrunkenNuclei_vs_Nuclei](https://user-images.githubusercontent.com/55710463/77793034-c8a92400-703f-11ea-8e16-5a73aba6f2b1.png)

Part of object 23 (missing 7 nuclei):
![Object23](https://user-images.githubusercontent.com/55710463/77793725-f3e04300-7040-11ea-81e7-51d4eb452535.png)

Everything between the two pipelines are similar, except shrinking nuclei vs none.

**Comment by bethac07** [comment]
This was a misunderstanding about how RelateObjects works, not a bug.
