### ISSUE TITLE
Sort by Column Header in Metadata Module

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#3978]
It would be really lovely to be able to click on the headers in the bottom of the Metadata module to  sort by that column. (i.e. When NamesAndTypes isn't playing nicely it's often a problem with Metadata extraction and sorting by column would make browsing for errors in metadata extraction much easier).

**Comment by DavidStirling** [comment]
Took a quick look into this, unfortunately it doesn't look like this would be trivial to do without substantial changes to how the tables in those modules are constructed.
