### ISSUE TITLE
Identify primary object 3d?

### ISSUE THREAD

**Issue by ctr26** [CellProfiler/CellProfiler#3980]
Does this module support 3d segmentation?

**Comment by DavidStirling** [comment]
At the present time IdentifyPrimaryObjects does not support 3D images. However, IdentifyPrimaryObjects is a simplified sequence of operations which can be achieved in 3D by running other modules individually. Modules such as Threshold and Watershed can be used to identify objects in a 3D pipeline. You might want to take a look at [this tutorial](https://github.com/CellProfiler/tutorials/tree/master/3d_monolayer) for a more detailed guide on how to segment 3D images.
