### ISSUE TITLE
Deprecate LoadImage/LoadSingleImage modules

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#3981]
They say this module is 'bad'

**Comment by j-christ** [comment]
This would break our batch workflow where we programatically generate a CSV file based on a database query and use that to designate which files should be used.

**Comment by bethac07** [comment]
LoadData is specifically designed to read input CSVs, and that module will certainly be carried forward.  Does that suit your use case?

**Comment by 0x00b1** [comment]
@j-christ Like @bethac07, LoadData should be a solution. Would you mind taking a look and letting us know?
