### ISSUE TITLE
UnicodeDecodeError in NamesandTypes module

### ISSUE THREAD

**Issue by Clemdem91** [CellProfiler/CellProfiler#3983]
Worker 0: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)

I restart the software, I reinstall the soft and this error is still happening. I don't understand what it means. I can't do anything. 

Thank you for your answer.

**Comment by DavidStirling** [comment]
Do you have any non-standard characters in file paths or in other text boxes? It'd also be helpful to know if this also appears in test mode.

**Comment by Clemdem91** [comment]
Yes It also happen in test mode. I have no special characters in the file paths.

**Comment by bethac07** [comment]
What version of the software, what OS/Version of your OS, does it happen in example pipelines (for example, if you load the one from the welcome screen) or just your own pipelines? If only on your own pipelines, can you share one?

**Comment by Clemdem91** [comment]
I am using the 3.1.9 version of cell profiler with windows 10 (64bit). It seems to work with the example pipelines. 
It's not my pipelines so I'm not sure I can share it.

**Comment by AnneCarpenter** [comment]
If you can modify the pipeline to take out anything confidential and upload a simple pipeline with images that produces the error, that would be great!

**Comment by DavidStirling** [comment]
This should no longer be a problem in CellProfiler 4, feel free to re-open this the problem does return.
