### ISSUE TITLE
Discontinue support for IdentifyObjectsManually / use EditObjectsManually instead

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#399]
EditObjectsManually has a freehand drawing mode that is similar to IdentifyObjectsManually. It's possible to use EditObjectsManually to identify objects if I add a setting that lets the user use the module without any input objects. Otherwise, EditObjectsManually is a much better tool at this point than IdentifyObjectsManually.

Alternatively, I could move the editing code outside of EditObjectsManually and have both EditObjectsManually and IdentifyObjectsManually use the same UI.

**Comment by AnneCarpenter** [comment]
It sounds like the substantive issue here, giving IdentifyObjectsManually the nice newer tools in  EditObjectsManually, has been completed. Any combining would likely as part of a larger restructure, if at all, so marking for future consideration.
