### ISSUE TITLE
Timeline for Python 3 support

### ISSUE THREAD

**Issue by crm416** [CellProfiler/CellProfiler#3990]
Hi there!

Our team uses CellProfiler mostly as a Python module / library. With the Python 2 EOL on January 1, 2020 and the increasing lack of Python 2 support by cloud providers, we've been attempting to upgrade the remainder of our codebase and dependencies to Python 3.

I know that Python 3 support was initially listed as part of the [CellProfiler 4 roadmap](https://forum.image.sc/t/cellprofiler-4-0-0-timeline-and-roadmap/26191) targeting a January release, and I've been following the PRs and Issues in this repo to keep tabs on Python 3 progress. But I wanted to see if there was any external update that could be shared on the timeline for Python 3 support. Should we as users expect Python 3 support to come in the next few weeks or months? (This is not intended as a criticism -- just trying to inform our internal planning!)

Alternatively, is it the CellProfiler team's opinion (even informally / un-officially) that if we were to run off current `HEAD` in a Python 3 environment, things would mostly work? (This isn't something we've tried, though I'm certainly open to it.)

Thank you for your work! We are grateful users :)

**Comment by 0x00b1** [comment]
Hi, Charlie! 😄 

Python 2 EOL was moved. In fact, EOL was yesterday with the release of 2.7.18. ☠️ 

CellProfiler 4.0.0 is close but I don’t feel comfortable providing a release date. For now, I’d recommend checking out the `cellprofiler_core` branch. I hope that branch is merged into master in the next week or two.

**Comment by crm416** [comment]
Thanks @0x00b1! Appreciate the update!

> Python 2 EOL was moved. In fact, EOL was yesterday with the release of 2.7.18.

Oops :))

> CellProfiler 4.0.0 is close but I don’t feel comfortable providing a release date... Today, nearly everything runs on Python 3.

Totally, make sense! Glad to hear that it's close. It sounds like y'all have made a lot of progress -- nice work. I'll take a look at `cellprofiler_core` and monitor the GitHub Project ([this one](https://github.com/CellProfiler/CellProfiler/projects/16), right?).

Good luck with the rest of the migration + release! Thanks again.
