### ISSUE TITLE
Generated CPA .properties files should properly handle colour images.

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#3991]
When generating a CellProfiler-Analyst .properties file with ExportToDatabase, CellProfiler currently assumes that all input images are single channel. As a result colour/multichannel images don't display properly in CPA out of the box.

Ideally the `image_channel_blend_modes` line should be included in this file, alongside appropriate channel colours, when the user is working with colour images.

**Comment by bethac07** [comment]
(And the `channels_per_image` as well!)
