### ISSUE TITLE
Cell Profiler does not start in Ubuntu 20.04

### ISSUE THREAD

**Issue by joda01** [CellProfiler/CellProfiler#3994]
**Describe the bug**
When starting cell profiler I get following error in the command line

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler/gui/app.py", line 59, in OnInit
    self.frame = cellprofiler.gui.cpframe.CPFrame(None, -1, "CellProfiler")
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler/gui/cpframe.py", line 327, in __init__
    self.__imageset_ctrl = cellprofiler.gui.imagesetctrl.ImageSetCtrl(
  File "/usr/local/lib/python3.8/dist-packages/cellprofiler/gui/imagesetctrl.py", line 434, in __init__
    self.column_label_editor.Bind(
  File "/usr/local/lib/python3.8/dist-packages/wx/core.py", line 1451, in _EvtHandler_Bind
    event.Bind(self, id, id2, handler)
  File "/usr/local/lib/python3.8/dist-packages/wx/core.py", line 1522, in Bind
    target.Connect(id1, id2, et, function)
wx._core.wxAssertionError: C++ assertion ""HasFlag(0x0400)"" failed at /tmp/pip-install-lae0nfll/wxPython/ext/wxWidgets/src/common/textcmn.cpp(1208) in OnDynamicBind(): Must have wxTE_PROCESS_ENTER for wxEVT_TEXT_ENTER to work
OnInit returned false, exiting...

**To Reproduce**
Install Cell Profiler as described under Ubuntu 20.04

**Expected behavior**
Cell profiler shoudl start.

**Screenshots**
![Screenshot from 2020-04-30 05-56-47](https://user-images.githubusercontent.com/46405460/80670546-70829900-8aa7-11ea-8614-38626779cb23.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CellProfiler Version 3.1.9
 - Installed from source

**Comment by bethac07** [comment]
CellProfiler 3.1.9 is Python 2.7; our current master is python 3.8 compatible, but currently undergoing major changes, so I would hold off using that until we are closer to our 4.0.0 release.

**Comment by joda01** [comment]
Thank you! I used the branch with 3.1.8 now it is running!
