### ISSUE TITLE
Cellprofiler 3.1.9 HandlessConfig

### ISSUE THREAD

**Issue by ChakrapaniNCBS** [CellProfiler/CellProfiler#3996]
Hello,
Have installed CP3.1.9 version under python3.6 on Centos 7 system. Installation successful without any error. while running from command line it ends with HandlessConfig error.

 File "/opt/rh/rh-python36/root/usr/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler==3.1.8', 'console_scripts', 'cellprofiler')()
  CellProfiler-3.1.8-py3.6.egg/cellprofiler/__main__.py", line 164, in main
    cellprofiler.preferences.set_default_output_directory(options.output_directory)
site-packages/CellProfiler-3.1.8-py3.6.egg/cellprofiler/preferences.py", line 871, in set_default_output_directory
    config_write(DEFAULT_OUTPUT_DIRECTORY, path)
  File "CellProfiler-3.1.8-py3.6.egg/cellprofiler/preferences.py", line 259, in config_write
    cfg.Flush()
AttributeError: 'HeadlessConfig' object has no attribute 'Flush'
Please suggest the fix.

**Comment by DavidStirling** [comment]
CellProfiler 3.1.9 is currently only compatible with Python 2.7, a port to Python 3 is in progress. For now you may have more success if you run with Python 2.

**Comment by ChakrapaniNCBS** [comment]
Hi David, 

Thanks for this info. I tried installing on py2.7.15 with all
dependencies. It got compiled without any errors. But I get this error
when I run cellprofiler 

Tried changing numpy version from 1.15.4 to 1.16.0 but still get the
same error. 1.15.4 is the compatible version for CP3.1.9 

/opt/python2.7.15/bin/cellprofiler --version 

Traceback (most recent call last): 

  File "/opt/python2.7.15/bin/cellprofiler", line 11, in <module> 

    load_entry_point('CellProfiler==3.1.9', 'console_scripts',
'cellprofiler')() 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 489, in load_entry_point 

    return get_distribution(dist).load_entry_point(group, name) 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 2852, in load_entry_point 

    return ep.load() 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 2443, in load 

    return self.resolve() 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 2449, in resolve 

    module = __import__(self.module_name, fromlist=['__name__'],
level=0) 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/CellProfiler-3.1.9-py2.7.egg/cellprofiler/__main__.py",
line 13, in <module> 

    import bioformats.formatreader 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/bioformats/__init__.py",
line 21, in <module> 

    import javabridge 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/javabridge/__init__.py",
line 38, in <module> 

    from .jutil import start_vm, kill_vm, vm, activate_awt,
deactivate_awt 

  File
"/opt/python2.7.15/lib/python2.7/site-packages/javabridge/jutil.py",
line 157, in <module> 

    import javabridge._javabridge as _javabridge 

  File "__init__.pxd", line 885, in init _javabridge 

ValueError: numpy.ufunc has the wrong size, try recompiling. Expected
192, got 216 

Tried changing numpy version from 1.15.4 to 1.16.0 but still get the
same error. 1.15.4 is the compatible version for CP3.1.9 

Please suggest a fix. 

Thanks, 

Chakrapani

On 2020-05-05 19:43, David Stirling wrote:

> CellProfiler 3.1.9 is currently only compatible with Python 2.7, a port to Python 3 is in progress. For now you may have more success if you run with Python 2. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/CellProfiler/CellProfiler/issues/3996#issuecomment-624080544
[2]

**Comment by DavidStirling** [comment]
It looks like a problem with javabridge. Lee's reply in [this thread](https://github.com/LeeKamentsky/python-javabridge/issues/153) might be of some help, depending on which version you've already installed.

**Comment by ChakrapaniNCBS** [comment]
The required javabridge version already there.  JAVABRIDGE==1.0.18 and
python-JAVABRIDGE==4.0.0rc1.  Also all dependency modules available for
CP-3.1.9 . There is no installation error. 

Installed python version is 2.7.15. Please suggest recommended version
for CP3.1.9

On 2020-05-06 19:52, David Stirling wrote:

> It looks like a problem with javabridge. Lee's reply in this thread [1] might be of some help, depending on which version you've already installed. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/LeeKamentsky/python-javabridge/issues/153
[2]
https://github.com/CellProfiler/CellProfiler/issues/3996#issuecomment-624676207
[3]

**Comment by bethac07** [comment]
Nope, David is correct, it's definitely a javabridge error, and if you in that same environment go into python and try to import javabridge you'll almost certainly see the same thing.  You likely want to drop your numpy back down and just install javabridge from source.

**Comment by ChakrapaniNCBS** [comment]
I can import javabridge and rest all  modules without errors. When I
execute cell profiler command it throws series of errors. Kindly check
attached and suggest please. 

Thanks

On 2020-05-07 18:50, Beth Cimini wrote:

> Nope, David is correct, it's definitely a javabridge error, and if you in that same environment go into python and try to import javabridge you'll almost certainly see the same thing. You likely want to drop your numpy back down and just install javabridge from source. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/CellProfiler/CellProfiler/issues/3996#issuecomment-625251393
[2]

**Comment by DavidStirling** [comment]
CellProfiler 4 now only uses python-javabridge rather than javabridge. Please re-open this if there are still problems with new release.
