### ISSUE TITLE
Measure Radial Entropy Produces Error

### ISSUE THREAD

**Issue by NasimJ** [CellProfiler/CellProfiler#4004]
**Describe the bug**
I was trying to measure radial entropy and regardless of number of bins or type of intensity measurement (mean/median/integrated) or the channel, this error pops up: 
<img width="425" alt="Error" src="https://user-images.githubusercontent.com/55710463/81878811-1a0d6400-9557-11ea-9378-a8214ea958eb.png">

**To Reproduce**
Steps to reproduce the behavior: Here is the setup:
<img width="652" alt="SetUp" src="https://user-images.githubusercontent.com/55710463/81879015-8720f980-9557-11ea-8027-4d5a9329ca00.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - CellProfiler Version: 3.1.9
 - Downloaded from the website or installed from source? from website
 - If the latter, how?

**Additional context**

**Comment by bethac07** [comment]
MeasureRadialEntropy is a plugin, not part of the main program, can you report [there](https://github.com/CellProfiler/CellProfiler-plugins) instead?

A pipeline and images to reproduce would also be helpful!
