### ISSUE TITLE
ERROR: Package 'CellProfiler' requires a different Python: 3.7.6 not in '>=3.8, <4.0'

### ISSUE THREAD

**Issue by McDr** [CellProfiler/CellProfiler#4011]
I followed the instructions to install from source on Windows 10 and I got the error in the title when I tried to run: `pip install -e.`  The instructions say that I should use Python 3.7 and that it is not working for Python 3.8... but my error message seems to indicate that I Should upgrade to 3.8

> ERROR: Package 'CellProfiler' requires a different Python: 3.7.6 not in '>=3.8, <4.0'

**To Reproduce**
1. Clone repository using Github Desktop
2. Navigate to directory using Anaconda Powershell
3. `pip install cython` (already installed)
4. `pip install -e.`

**Expected behavior**
CellProfiler to install successfully using the installation instructions

![image](https://user-images.githubusercontent.com/27747675/82343892-abffeb80-99f3-11ea-9ef6-ca65bbb04f74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version: 4.0.0
 - Installed from source
 - Cloned using Github Desktop, `pip install -e.`

**Comment by 0x00b1** [comment]
You're fast! I just made this update an hour ago! You'll need 3.8. We'll update the instructions on the wiki.

**Comment by 0x00b1** [comment]
Wiki is updated. :)

**Comment by McDr** [comment]
Haha, makes sense now, thought it was a little strange! Thanks for the quick help!
