### ISSUE TITLE
Make Threshold more consistent, or document its inconsistencies

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4012]
Threshold is kind of a mess- most modules respect threshold mins and maxes, but some don't (manual), most respect the given smoothing settings, but some don't (manual, measurement), and the "local" and "global" nomenclature sometimes refers to local and global, and sometimes refers to "final" and "original".  

I know we're planning on making changes to skimage, we should consider ripping a LOT out in the rewrite, and documenting either a) what changes we make to bring things more in line, or b) where the inconsistencies remain.

**Comment by 0x00b1** [comment]
lol
