### ISSUE TITLE
Populate row for image set matching in NamesAndTypes

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4027]
**Is your feature request related to a problem? Please describe.**
In NamesAndTypes when matching many image sets (e.g my current edge-case pipeline matches >40 image sets), it is slow and frustrating to pick from the drop down the metadata for each. Even in more typical pipelines, usually most of the image sets match a single metadata across a row.

**Describe the solution you'd like**
It would be nice if there could be the option to add a single metadata to all the sets across a single row (of course maintaining the option to then change individual image sets by using its dropdown). Perhaps when you + to create a new row it could ask if there was a metadata you'd like to fill that row with?

**Comment by bethac07** [comment]
What do you mean by a "row" in this context?

**Comment by ErinWeisbart** [comment]
<img width="781" alt="Screen Shot 2020-05-22 at 12 38 43 PM" src="https://user-images.githubusercontent.com/54687786/82704059-9ffd6f00-9c29-11ea-9eff-108ab5e2fb52.png">
