### ISSUE TITLE
Remove h5/mat dumping, and related Data Tool functionality

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4028]
Writing your data to a .mat and/or a .h5 container, and then using CellProfiler on those after a fact, are mostly historical relics that are almost never used, and complicate the code base.  

While DataTool modules that can be run in-pipeline (like DisplayDataOnImage) will be kept, CellProfiler will no longer create those output files, and any modules that can only run after-the-fact (like MergeOutputFiles) will be removed.

**Comment by bethac07** [comment]
See #4020 and #4026 to start

**Comment by bethac07** [comment]
This functionality has been marked as deprecated since September of 2017. https://github.com/CellProfiler/CellProfiler/blob/613247de8b9227b17f9b2eb31b43ad86682aee7d/cellprofiler/data/help/legacy_output_file.rst

**Comment by DavidStirling** [comment]
Adding a note here - when this functionality is removed we should also remove the `File --> Resume Pipeline` function.
