### ISSUE TITLE
the error when use cellprofiler to extract cell features

### ISSUE THREAD

**Issue by IsDling** [CellProfiler/CellProfiler#4029]
![微信图片_20200523205506](https://user-images.githubusercontent.com/35657230/82731205-bbef3680-9d37-11ea-8492-afa498dfb5d5.png)
The error window pops up when I run the pipeline using cellprofiler to extract cell features with Win10. Is there anybody meet this problem?

**Comment by IsDling** [comment]
This problem has been solved. Click “Window-->Hide All Windows On Run" int the menu when run the pipeline!

**Comment by DavidStirling** [comment]
Would you be able to confirm which version of CellProfiler you're using and possibly upload a pipeline which does this? It sounds like there's a problem with one of the module figure functions.

**Comment by bethac07** [comment]
This is a known issue we've [fixed as best we can ](https://github.com/CellProfiler/CellProfiler/issues/3461) for CellProfiler 3, and indeed it is aided by closing the module windows.

Closing as duplicate.
