### ISSUE TITLE
Restrict module loading to those indended as builtin modules

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4037]
Currently CP4 will scan the modules folder in CellProfiler. In some cases there are old files left over, or testing modules, which are then being inappropriately added to the module list.

I'll add a filter.

**Comment by bethac07** [comment]
Would it be better just to clean the old files, rather than have to filter?

**Comment by DavidStirling** [comment]
We could certainly do that, but I think that having a defined list would also be 'safer'. If users want to add a module we really want them placing them into the plugins directory, rather than the modules directory.

**Comment by DavidStirling** [comment]
Fixed by CellProfiler/core#9
