### ISSUE TITLE
Python version error when installing in anaconda 

### ISSUE THREAD

**Issue by overvalley** [CellProfiler/CellProfiler#4050]
I'm following the instructions on the "Conda Installation" page to install CellProfiler from source on OSX. The environment seems to be compiling properly, however once the packages are downloaded and the following output is printed

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

I get a pip subprocess error, saying that the package u'CellProfiler' requires a different Python: 2.7.18 not in '>=3.8, <4.0'. I assume this is because the .yaml file specifies python=2, however if I switch it to python=3 the environment fails to compile. Any suggestions?

![Screen Shot 2020-06-03 at 10 53 28 PM](https://user-images.githubusercontent.com/66398473/83709685-0cdf1480-a5ed-11ea-81cc-21fd58632be7.png)

**Comment by marcosterland** [comment]
Having the same issue. This workaround worked for me:

1. change the branch of the CellProfiler Repo in the last line of the environment.yml to @v3.1.9 or @082930e instead of @master.
2. If you run into problems with the centrosome package, change it to "centrosome==1.1.6"

**Comment by overvalley** [comment]
Thanks for the suggestions. changing the branch to v3.1.9 worked great, however it still returned a centrosome error even after changing it to 1.1.6. Is there perhaps a different version of centrosome that may be compatible? 

(Also side note: it looks like I will also have to switch to prokaryote==2.4.1 and python-bioformats==1.5.2 to be compatible with CellProfiler v3.1.9, see screenshot)

![Screen Shot 2020-06-04 at 10 29 36 AM](https://user-images.githubusercontent.com/66398473/83772751-b3f59780-a651-11ea-8fef-dffbad93992e.png)

**Comment by overvalley** [comment]
It appears that regardless of the centrosome version I use, the fatal error is always 'complex' file not found....

**Comment by overvalley** [comment]
So after some digging, it seems the issue is that I'm compiling using Xcode command line tools v11.5, and for v10 and later there was a syntax change that makes the CellProfiler code incompatible with these versions. Has anyone found a solution, beyond the hassle of having to create a virtual machine with an older OSX and v9 command line tools?
