### ISSUE TITLE
Can't install CellProfiler 4.0.0rc4 from source

### ISSUE THREAD

**Issue by ckuijl** [CellProfiler/CellProfiler#4059]
Hi,
Installation of CellProfiler fails in Conda environment.
easy fixes
-install numpy
-install lower version of docutils (0.15.2)

While building wheel of mysqlclient I get the following error:

Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ckuij\Anaconda3\envs\CP400\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ckuij\\AppData\\Local\\Temp\\pip-install-fja5zehv\\mysqlclient\\setup.py'"'"'; __file__='"'"'C:\\Users\\ckuij\\AppData\\Local\\Temp\\pip-install-fja5zehv\\mysqlclient\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ckuij\AppData\Local\Temp\pip-wheel-6asq4yyt'
       cwd: C:\Users\ckuij\AppData\Local\Temp\pip-install-fja5zehv\mysqlclient\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\__init__.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\_exceptions.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\compat.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\connections.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\converters.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\cursors.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\release.py -> build\lib.win-amd64-3.8\MySQLdb
  copying MySQLdb\times.py -> build\lib.win-amd64-3.8\MySQLdb
  creating build\lib.win-amd64-3.8\MySQLdb\constants
  copying MySQLdb\constants\__init__.py -> build\lib.win-amd64-3.8\MySQLdb\constants
  copying MySQLdb\constants\CLIENT.py -> build\lib.win-amd64-3.8\MySQLdb\constants
  copying MySQLdb\constants\CR.py -> build\lib.win-amd64-3.8\MySQLdb\constants
  copying MySQLdb\constants\ER.py -> build\lib.win-amd64-3.8\MySQLdb\constants
  copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win-amd64-3.8\MySQLdb\constants
  copying MySQLdb\constants\FLAG.py -> build\lib.win-amd64-3.8\MySQLdb\constants
  running build_ext
  building 'MySQLdb._mysql' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\MySQLdb
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,4,5,'final',0) -D__version__=1.4.5 "-**IC:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include\mariadb"** -IC:\Users\ckuij\Anaconda3\envs\CP400\include -IC:\Users\ckuij\Anaconda3\envs\CP400\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /TcMySQLdb/_mysql.c /Fobuild\temp.win-amd64-3.8\Release\MySQLdb/_mysql.obj /Zl /D_CRT_SECURE_NO_WARNINGS
  _mysql.c
  MySQLdb/_mysql.c(29): fatal error C1083: Cannot open include file: 'mysql.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

There appear to be a link to Maria DB (C:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include\mariadb"). Installing MariaDB and the connector at this specific location does not solve the problem. The mysql.h files is nowhere to be found.

How to proceed?

Thanks

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version 4.0.0rc4
 - Downloaded from source via github

**Comment by ckuijl** [comment]
Hi,
Changing "mysqlclient==1.4.5" to "mysqlclient==1.4.6" in setup.py and installing the mysqlclient wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/" enables installation from source.

When starting CellProfiler the GUI starts, but I do get the following error:

(CP400) C:\Users\ckuij\PycharmProjects\CellProfiler>Cellprofiler
MySQL could not be loaded.
Traceback (most recent call last):
  File "c:\users\ckuij\pycharmprojects\cellprofiler\cellprofiler\modules\exporttodatabase.py", line 121, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'

**Comment by orgonth** [comment]
I had the same issue, I solved it by:
- starting from a clean venv
- installing mysqlclient first from the precompiled binaries (same as your link)
- edit `setup.py` with :
"mysqlclient>=1.4.5",
"pyzmq>=18.0.1",

**Comment by DavidStirling** [comment]
Instructions should be more up to date now

**Comment by jamila-griffith** [comment]
I am coming across this error every time I try to install from source. 

ResolvePackageNotFound: 
- mysqlclient[version='1.4.4.*,1.4.6']
- gtk2
Not sure what this means but can anyone please help.

**Comment by DavidStirling** [comment]
@jamila-griffith You'd be best off creating a new issue for this, the thread here is closed and isn't the same problem. Thanks
