### ISSUE TITLE
SaveImages in 3D-16bit-multichannel creates images with corrupted Metadata

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4070]
**Describe the bug**
Color 3D images don't save correctly when saved as 16 bit TIFFs, though they do save fine as 8 bit TIFs.  Greyscale images save fine as 16 bit TIFFs.  

**To Reproduce**
Run the 3D Tutorial pipeline; the resulting saved overlay images will not open nicely in ImageJ, with Metadata errors (they will open ok in CellProfiler).  The label images are fine.

**Expected behavior**
I suspect this is related to the TIF compression we added in #3555 .  We should see if we should only do this on greyscale, or if there is another keyword we should add to make it work nicely for both kinds of images.

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - CellProfiler 3.1.9 Built

**Comment by DavidStirling** [comment]
I've been looking into this, it is indeed the compression.

I believe this is a problem on ImageJ's end, the problem files actually load just fine using the BioFormats importer, it's only the native ImageJ importer which brings up errors and fails to load them. So the data is there, it just can't be read.

I took a look at the compression parameters, but unfortunately there aren't many options that won't introduce dependencies. The other compression method which we could specify with the current setup isn't supported by ImageJ at all.

I think we have a few options:

- Print, document or display a warning telling users that the bioformats importer will be needed to load colour image stacks.
- Disable compression specifically for multichannel stacks. This will increase filesize by 10x.
- Try and run complex tif saving operations through the bioformats writer?
- Leave it alone.
