### ISSUE TITLE
Update Welcome Screen for CellProfiler 4

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#4083]
We have a proposed redesign! Far less texty. Comments are welcome.

**Comment by DavidStirling** [comment]
As requested, here is @AnneCarpenter's drawing!

![WelcomeScreen](https://user-images.githubusercontent.com/26802537/85871831-f74cad00-b79c-11ea-9140-16cd751f3501.JPG)

**Comment by AnneCarpenter** [comment]
I'd suggest that the 'What's New' link goes to something that is auto-generated, or that we are already doing so that we don't create maintenance for ourselves. Options include: 
- link to the most recent BIG release (3.0, 4.0) blog post, since we always do blog posts (downside: it won't be completely current)
- link to some kind of automatic github-generated list of recently closed issues (downside: not as human readable/translated to end user)

thoughts?

**Comment by DavidStirling** [comment]
I like the idea of using the blog. We could link to a tag like [this](https://carpenterlab.broadinstitute.org/browse/blogs?f%5B0%5D=sm_og_vocabulary%3Ataxonomy_term%3A35) to keep things as current as possible, but perhaps make a dedicated tag for releases? Alternatively we could have a broad.io link or something to point to the newest post.

On the subject of the blog, I think you really shouldn't need to scroll down so far to see the content. Just the menu and header takes up my entire screen right now.

**Comment by AnneCarpenter** [comment]
ooh, agree about the blog, will pass that note to Becki; she could also implement a new tag if that's what you'd like to do.

**Comment by bledford87** [comment]
@DavidStirling How is the layout now?

**Comment by bledford87** [comment]
I've also added a "Releases" tag and added it to previous release announcements. https://carpenterlab.broadinstitute.org/blog/categories/releases

**Comment by DavidStirling** [comment]
Brilliant, thanks @bledford87! The new layout is much better, although there's still a gap at the top of the page before the header image. Not sure if we can do anything about that?

**Comment by bledford87** [comment]
Unfortunately that's at the theme level (which I don't have access to edit because it's the theme Broad chose with OpenScholar).

**Comment by DavidStirling** [comment]
That's understandable. Another solution might be to reduce the vertical size of the banner by having less space between each line of text (if we still have the original template), although it's not a major concern. The new version is already so much better!
