### ISSUE TITLE
CellProfiler 4.0.0rc5: TypeError:'<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by citypalmtree** [CellProfiler/CellProfiler#4098]
**Describe the bug**
In Ubuntu virtual environment, I installed CellProfiler 4.0.0rc5 and cellprofiler-core4.0.0rc7.
I was running a headless CellProfiler, and an issue came up.

/cellprofiler_core/pipeline/_pipeline.py", line 845, in group
    if image_number < image_set_start:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
So sorry. CellProfiler failed to remove the temporary file, /tmp/Cpmeasurementsacce4ifn.hdf5 and there it sits on your disk now

From what I understand, it was because that Python3 doesn't compare None and integer.
I added:

if image_set_start is None:
image_set_start=0

before line 845 and the issue was cleared.
Could you take a look at it if that's a correct fix?

**Comment by crm416** [comment]
I believe this is addressed by #4065.

**Comment by DavidStirling** [comment]
Should be fixed now
