### ISSUE TITLE
could not load these modules: combineobjects

### ISSUE THREAD

**Issue by Spucer** [CellProfiler/CellProfiler#4106]
Hi everyone, 

I am trying to use the combineobjects module by DavidStirling. 

Therefore, I have placed the combineobjects.py file into a folder, changed the plugins folder in the preferences and restarted CellProfiler 3.1.9, Windows 10.

I do get the error attached. Is there anything else I need to pay attention to?
Thank you very much for your help!!

generated new fontManager
Could not load combineobjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\modules\__init__.py", line 325, in add_module
  File "C:\Users\myusername\mypath\combineobjects.py", line 36, in <module>
    import cellprofiler_core.module
ImportError: No module named cellprofiler_core.module
could not load these modules: combineobjects

**Comment by DavidStirling** [comment]
Hi @Spucer,

CombineObjects is being written for CellProfiler 4, and unfortunately won't be backwards-compatible with CellProfiler 3. You may want to try running CP4 from source, or waiting for the proper release in the coming weeks.

**Comment by Spucer** [comment]
Great, thank you so much for your rapid reply. 
Replacing "cellprofiler_core" by "cellprofiler" did not work. I will try CP4, definitely. Hope this will work. Thanks!
