### ISSUE TITLE
Unrecoverable error in ExportToSpreadsheet when "Add image and folder names to your object data file?" is yes

### ISSUE THREAD

**Issue by MaximLippeveld** [CellProfiler/CellProfiler#4123]
**Describe the bug**
An unrecoverable error occurs in ExportToSpreadsheet when "Add image and folder names to your object data file?" is set to "yes". The error occurs when all images are processed and data is being exported.

**To Reproduce**
1. Add some images (16-bit png in my case)
2. Add object defining module
3. Add measurement module
4. Add ExportToDatabase module and set "Add image and folder names to your object data file?" to "yes".
5. Analyze images.

**Expected behavior**
Image and folder names are added to the object data file.

**Screenshots**
![image](https://user-images.githubusercontent.com/8209122/89016340-d71e8980-d318-11ea-9204-2998e36f9a33.png)

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - CellProfiler Version 4.0.0rc5
 - Installed from source
 - Github clone + `pip install -e .`

**Additional context**
Not applicable.

**Comment by DavidStirling** [comment]
Thanks for finding that, should be fixed now!
