### ISSUE TITLE
LAPTracker labelling issues in exported CSV?

### ISSUE THREAD

**Issue by DeboraOlivier** [CellProfiler/CellProfiler#4128]
**Describe the bug**
I track my nuclei using LAP tracker and then export various measurements and images.
The output images, trackedNuclei, indicates the TrackObject_Label over time and I have one instance where TrackObject_Label 1 becomes 28 at image 72 then 29 at image 74.
When I wanteed to merge the tracks manually, I realized that there is a bug in the exported spreadsheet, whereby the ImageNumber jumps from 71 to 120 when I look at TrackObject_Label1 and 28/29.
This is not the case for an object (#2) that retains its label over the course of the tracking.

In addition, it seems tehre is something fishy going on with the XY location and center of mass once the object switches form being labelled 1 to 28 (we wanted to use this to correct for tracking errors in Python later on): for instance, the AreaShape_center_X goes from ~420 to 0, while the Y values stays ok (same behaviour with Location_CenterMassIntensity_X and Location_Center_X)

I wonder if this is a bug from LAPTracker in re-labelling?

**To Reproduce**
not really easy to reproduce without the data - can provide full pipeline + some sample data
attached the csv with selected objects 
[BUG_LAP_objects2-ok_1-28-29-notOK.xlsx](https://github.com/CellProfiler/CellProfiler/files/5016855/BUG_LAP_objects2-ok_1-28-29-notOK.xlsx)

**Expected behavior**
I'd expect the series of TrackObject_Label to be continuous over time even if there is a change in object ID.

**Screenshots**
LAP tracker settings:
![image](https://user-images.githubusercontent.com/52743133/89198707-deaa9080-d5ad-11ea-83b5-cb8e1c142955.png)
Tracking Output - images and CSV
![image](https://user-images.githubusercontent.com/52743133/89197472-0dc00280-d5ac-11ea-821f-a7e9c1d6cdfb.png)
![image](https://user-images.githubusercontent.com/52743133/89197524-229c9600-d5ac-11ea-9732-9fac95b2eb17.png)

**Desktop (please complete the following information):**
 - Ubuntu16.04
 - CellProfiler Version 3.1.9
 - source install (to run CP plugins) - following instructions on Wiki

**Comment by DavidStirling** [comment]
Hi @DeboraOlivier,

In the CSV these certainly look like entirely separate objects based on the coordinates, Tracking labels 1 and 28 may not be the same object at all, so I'd question whether it's the overlay that's actually incorrect. Were the image screenshots here directly generated by CellProfiler or was this using the LAP_Relabel script?

**Comment by DeboraOlivier** [comment]
Hib
The screenshots were directly from CP at the end of the pipeline not using
your python script. I had meant to post other examples but went on holidays
but will go back to work on monday. However it is a bit of a problem for a
manual post filtering check...
I could not find to what object the labels correspond to! Can send the
pipeline if needed! (If not already done so.. brain is mush)
Cheers

Debbi

**Comment by DavidStirling** [comment]
The pipeline + image, or the segmentation files, would probably be helpful in replicating this. Thanks!

**Comment by DeboraOlivier** [comment]
Hi David,

I didn’t dare crop the different images as recently I have issues (bug with
operands carrying over different shapes - another story), so I put one file
exactly as I analysed it.


The first step of the analysis is generating object labels in Linux using
classify pixel - these are then imported in the PC pipeline for the rest of
the analysis. I did not include the first step in the data I send you.

So here are the different files:

   -

   original image: siCTRL_20190422_Pos02_cl7.tif
   -

   primary object labels: siCTRL_20190422_Pos02_cl7_label folder
   -

   tracked nuclei labels (generated at the end of the pipeline):
   siCTRL_20190422_Pos02_TrackedLabels
   -

   CSVs generated by CP: siCTRL_20190422_Pos2-3_CSV
   -

   CSVs from Python post analysis: the tracks are arranged according to
   TrackObject_Label from CP output. this csv is a condensed form of the CP
   output.
   -

   Figures from Python analysis organised according to TrackObject_label:
   this is for visual control, for instance to identify daughters from the
   same mitosis, or exclude cells with low telomere number (low expressors).

it was using these figures that I realized there is a mismatch between the
label on the CP_output image of Tracked Nuclei and the CSV…

Taking for instance object 1 in TrackedNuclei labels:

   -

   time 72 the label changes to 28 (time 71 in CP as start from 0),
   -

   time 73, label changes to 29 until the end of the movie (t194)

in CSV output by CP (siCTRL_20190422_Pos2-3_Nuclei.csv), the label 1 stops
at t70, but the label 28/29 have a time stamp of 119 to 193 (and there is
some back and forth in the labeling).

and so it is difficult to manually correct the tracks without being able to
reconcile the tracked_nuclei labels and the CSV...

Note: I ran two movies in the same analysis that is why the CSV have Pos2-3
as names.

Hope you can replicate or help sort out the issue

Cheers

Debbi


PS: I will send the data as a download link in a separate email (to your
broad adress), the file is big!!

the email will come from renater filesender (just in case it goes to spam)

**Comment by DeboraOlivier** [comment]
Hi,
this issue isn't resolved in 4.0.3 and am afraid it can affect teh downstream Python data analysis (using jupyter notebooks) where we use TrackObjects_Label to identify tracks and extract features etc.

![GH#4128_20200922_Gallery](https://user-images.githubusercontent.com/52743133/93893866-68ddbe00-fcee-11ea-92a8-82155b4ad695.png)
This is an example: the upper part is the Tracked Nuclei label (output from LAP tracker), for instance look at TrackObject_Label #44 which appears on multiple consecutive frames (time 65-70). The object #44 actually appears on Metadata_T=44 and lasts until Metadata_T=88, so a lifetime of 44 frames (pure coincident, I promise).

However, the CSV output by CP4.0.3 indicates that TrackObject_Label #44 **only appears on MetaData_T=57**
![image](https://user-images.githubusercontent.com/52743133/93896467-397c8080-fcf1-11ea-84a4-12833da3d3bf.png)


Not sure if related but it seems also that **there is an error in the XY axes:**
- CSV for Object#44 indicates AreaShape_BoundingBoxMaximum_X = 1096 AreaShape_BoundingBoxMaximum_Y=1016 and it is classified as a **prometaphase**
- TrackedNuclei Image for Object#44 is AreaShape_BoundingBoxMaximum_X is about 104 (thogh the Min is 0 as on the border)

- images indicate that the only object with AreaShape_BoundingBoxMaximum_X =1096 and  AreaShape_BoundingBoxMaximum_Y=1016 and classified as prometaphase (orange outline) is actually **Object#55**

![image](https://user-images.githubusercontent.com/52743133/93897479-667d6300-fcf2-11ea-99d9-86e67bc3f2d8.png)

==> there appears to be an inversion of the X/Y axes between TrackedNuclei image and the output CSV leading to mis-match between TrackedNuclei image and TrackObjects_Label (CSV)

Any idea how fixable this is??
cheers

Debbi

**Comment by bethac07** [comment]
We'll certainly look into the XY inversion reported and other issues, but just to clarify a point of confusion- 
you cannot match the "label image" numbers from those images to the output spreadsheet if you are filtering by track lifetime and /or using the LAP tracker with the second half turned on, they are not designed to be matched.

The output images are put out as the pipeline is run, frame-by-frame; if you're doing either of those things I described above, once all the frames of a movie are done the tracks are then edited, to either throw some tracks out or to do track merges and splits.  This means that in those cases, the final object's TrackObjects_Label is NOT guaranteed, and very typically NOT, the preliminary TrackObjects_Label it was originally assigned.  Since the images cannot be edited after-the-fact, therefore, the images show the preliminary Label, the CSVs have the final Label, and you can't assume that they match. 

I hope that helps clear it up- we already do have that info in the help for the setting for creating the images, and for all of the settings that cause the images to potentially be inaccurate, but if there's somewhere else it would be helpful to add that, please do let us know!

**Comment by DeboraOlivier** [comment]
Hi! I was aware that the intermediates where not labelled correctly and that you'd need tracer to check the intermediate tracking but I had thought (wrongly, it seems) that in post-processing of the pipeline, the correct labels would be re-assigned.
Then this might explain all the discrepancies and turn this issue into a feature request then: would it be possible to re-label the tracked nuclei with teh final labels? this is useful to do quality controls on the tracks for instance to chekc that low numbers in the CSV actually correspond to a low expressor, or that a weird behaviour corresponds to a cell at the border etc.. 
Being able to match images and trackObject_labels would be very useful/helpful to link the  numbers to the cell in question - not only for QC but also for figures in papers or presentations... maybe something along the lines of the script @DavidStirling had written to relabel?
sorry for the confusion! I guess one can close this issue and make it a feature request instead (4.0.4 or 4.1?)
