### ISSUE TITLE
CellProfiler on Mac Source doesn't closer properly.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4143]
**Describe the bug**
It just shows `Exiting the pipeline validation thread` but then hangs until you Ctl+C in the console window.

**Desktop (please complete the following information):**
 - OS: OSX 14.6
 - CellProfiler Version da6e2214d

**Comment by 0x00b1** [comment]
Indeed. @bethac07 would you mind investigating? My guess is it’s related to macOS entitlements.

**Comment by bethac07** [comment]
Update- updating python-javabridge fixed this.
