### ISSUE TITLE
New MeasureTexture has leaked semaphore objects

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4151]
**Describe the bug**
On closing CellProfiler, it hangs after exiting the pipeline (see also #4143), but if the new MeasureTexture (which contains dask) has run, you get another error you must Ctl+C through to close.

```py
/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
**Desktop (please complete the following information):**
 - OS: OSX 14.6
 - CellProfiler Version 404d11e9be276f6990d5ff05d0e6580a646293a5

**Comment by DavidStirling** [comment]
While we're at this, could someone add `dask[complete]` to setup.py

**Comment by bethac07** [comment]
@DavidStirling https://github.com/CellProfiler/CellProfiler/commit/82302a51eb8becb8aef1239ac60541455f415831

**Comment by 0x00b1** [comment]
Ah, @bethac07, you need to add some Dask cleanup to the the shutdown function in __main__.

**Comment by mrocklin** [comment]
Hi There!  

Sorry to hear about leaking semaphores.  I'm a bit surprised to see this given that you all are only using local threads and not processes.  Is there an easy way I can reproduce this issue?  I just start up CellProfiler and then shut it down?

**Comment by bethac07** [comment]
Yup, opening and closing this commit of master should do it- 82302a51eb8becb8aef1239ac60541455f415831
