### ISSUE TITLE
No "show/hide all windows on run" in Windows menu

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4163]
OSX 14.6

**Comment by alicelucas** [comment]
After looking into this a bit more, I agree with David that the OSX Window menu is overwriting the one that we define. I couldn't find a way to prevent this overriding behavior. At the top of my mind, here are the things that we could do to at least let a Mac user have access to the options: 

1. In another already existing menu item, for example "Edit", we could have a new "Windows" submenu with the different menu options. 

2. Or we could have another "Window" menu, but named differently than what Mac uses, such as "Windows" or "CellProfiler Window". In these cases both the default Mac Window menu and our defined Windows menu would shouw up in the Menu bar. It looks a bit redundant. 

I'm showing the two options in the attached screenshots.

Any other ideas/thoughts?

![windows_in_edit](https://user-images.githubusercontent.com/24425961/91094006-3164ee80-e628-11ea-970a-19d7231cdf0f.png)
![windows_renamed](https://user-images.githubusercontent.com/24425961/91094008-31fd8500-e628-11ea-8e80-96df00d06d24.png)

**Comment by DavidStirling** [comment]
Looks like the Window menu is auto-generated on OSX by wxpython. In wx3 this was something you could interact with, but it looks like in wx4 it's not easily controllable. I think the second option is better than the 'edit' menu, but I'll take a closer look at whether there's some way to grab or disable the mac Window menu.

**Comment by DavidStirling** [comment]
If we do have to revisit this functionality, it might be worth knocking out #1601 at the same time. The "Window" menu made by CellProfiler is only attached to the main frame, not sub-windows. If we're able to figure out how to add the entries directly to the native OSX menu then it might be easy to stick a 'close' button in that works universally as well.
