### ISSUE TITLE
MeasureColocalization performance issues

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4168]
In both 3.1.9 and 4.0.0 performance of MeasureColocalization degrades dramatically as the input image size increases when using "per object" mode.

This seems to be caused by the Costes measurements, particularly the loop here:

https://github.com/CellProfiler/CellProfiler/blob/07b9201260fadfcbdea439135bdcaf318778a677/cellprofiler/modules/measurecolocalization.py#L506-L516

With the example pipeline, running on the cropped images takes 0.139s per pair. Running on the full size images took 7.137s per pair, regardless of the object count.

I've bumped into this in several projects. If we can't improve performance I'd suggest defaulting that measurement to 'off'.

**Comment by bethac07** [comment]
I'm not sure we want to change the default- just to keep compatibility with older versions.  

I think it's definitely worth noting in the module help though if it can't be fixed easily!

**Comment by DavidStirling** [comment]
I've been playing around with this a bit. Most of the processing time goes into `scipy.stats.pearsonr`, but their implementation is pretty good already and numpy's performance is very similar.

At the moment we basically loop through every possible value for `i` and evaluate whether correlation dropped below 0. The vast majority of these r values are way above 0, and each decrease in `i` doesn't effect r too dramatically. Based on this I've been able to achieve about a 10x speedup by adding code to do bigger steps in `i` when the r value is very high. Doing this carefully seems to work without altering the final result. How would we feel about potentially having a 'fast vs accurate' mode setting for these loops?

**Comment by bethac07** [comment]
I think that's a great idea! I'd make it a new setting, with upgrade_settings set to "No" on old pipelines to keep compatibility with old workflows, but a default of "Yes" for new pipelines.
