### ISSUE TITLE
Unable to select first option in any dropdown on macOS Big Sur 

### ISSUE THREAD

**Issue by raivivek** [CellProfiler/CellProfiler#4174]
**Describe the bug**
I'm running the "pre-release" version of macOS Big Sur (20A5354i) currently and having weird bug with the selection of items in the drop-down items. I am unable to highlight/select the first option in the dropdown using mouse click. I can use keyboard to navigate to that option and press enter, but then nothing happens.

**To Reproduce**
1. Open any module and try to select the first option from the menu
2. Cannot select / nothing happens

**Expected behavior**
The option should be selected and relevant configuration options should update when corresponding menu item is selected.

**Screenshots**
![cellrpofiler](https://user-images.githubusercontent.com/3218617/91203646-c2a09780-e6f2-11ea-9ef6-dd03832895f7.gif)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11 (Public Beta 2)
 - CellProfiler 3.1.9 (installed through dmg download)

**Comment by 0x00b1** [comment]
Thanks, @raivivek. The image is super helpful. This is an issue with wxPython that will be fixed prior to the release of Big Sur.

**Comment by raivivek** [comment]
Closing this as I don't have this issue anymore in the latest version.
