### ISSUE TITLE
Regex Editor fails to get example filename

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4179]
It's defaulting to the hard-coded sample file name rather than fetching a valid one. Looks like the function to test filename validity is broken.

**Comment by braymp** [comment]
I think I've found that I have to press the 'Apply Filter' button in the Images module for the actual filenames to get picked up by the regex editor.

**Comment by DavidStirling** [comment]
@braymp Is that with or without the linked fix? The file list does need to be filtered to pick up valid names, but in the master branch it currently doesn't fetch the correct text chunk at all.

**Comment by braymp** [comment]
My msg and the fix must have crossed in flight :-) I have not checked the fix as yet; I was thinking back to my old CP 2.2.0 days...

**Comment by DavidStirling** [comment]
Ah, that's all good then! You're right about the expected behaviour when using an unfiltered file list, but this issue is different - the editor was failing to return anything other than the fallback text even after filtering.
