### ISSUE TITLE
Getting Started and Built-in Help buttons on welcome screen don't seem to do anything

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#4219]
Getting Started and Built-in Help buttons on welcome screen don't seem to do anything when clicked.

 - OSX 14.6
 - CellProfiler Version 4.0.2
 - Downloaded from the website

**Comment by DavidStirling** [comment]
Working fine on Windows, they should display a different page. Do you see an error in the console?

**Comment by bethac07** [comment]
No console on Mac

**Comment by bethac07** [comment]
But no, in source 4.0.2 they also don't work, and show no console errors
