### ISSUE TITLE
Update the wikipedia article with CP4.0 release

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#4225]
https://en.wikipedia.org/w/index.php?title=CellProfiler

We just need to:
1. add a sentence after this one, of similar style: "Version 3.0, supporting volumetric analysis of 3D image stacks and optional deep learning modules, was released in October 2017.[16]"
2. adjust the "stable release" section to 4.0
3. add this step to our release checklist for the future

**Comment by raivivek** [comment]
I had some time so completed Steps 1-2. https://en.wikipedia.org/wiki/CellProfiler

**Comment by DavidStirling** [comment]
Looks like this is all sorted now
