### ISSUE TITLE
CalculateIlluminationApply: Large # of displayed images causes individual images to be shrunk to almost nothing

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#4228]
**Describe the bug**
In CorrectIlluminationCalculate, if there is a large number of input images, the display window shrinks the individual images to a tiny size.

**To Reproduce**
1. Load a cell painting pipeline and point to collection of raw images plus illumination correction functions (ICFs). Alternately, mock up 5 channels worth of input images and corresponding ICFs
2. Run the pipeline to the CorrectIlluminationApply module, making sure to yield the display window.
3. The display window appears as the following:
![image](https://user-images.githubusercontent.com/1186440/92780695-73ed3180-f371-11ea-9603-4251eadc9bbc.png)

**Expected behavior**
* Expected the display figure to look similar to that for v.2.2.0:
![image](https://user-images.githubusercontent.com/1186440/92780800-8c5d4c00-f371-11ea-8121-9f2c7eab3ef1.png)
* Maximizing the window is a workaround but this was not needed previously.
* Not known if v3.1.9 was similarly affected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version v4.0.2
 - Downloaded from the website

**Additional context**
* Not sure if other modules which can accept/display a large number of images are similarly affected.

**Comment by DavidStirling** [comment]
Yup, this is kinda expected when working with large numbers of subplots. I previously couldn't think of a situation which would produce so many!

Basically the Figure viewer is now set up to not let the axes overlap eachother. This has the downside that the text size is fixed and so can squeeze out the plots. There a 2 possible fixes I can imagine for this problem:

1 - Shrink the title and axes font size to make more room for subplots.
2 - Disable the new layout engine and revert to the old, overlapping behaviour.

Do we have a preference?

**Comment by braymp** [comment]
At 1st blush, I'm leaning towards option 1. Though I wonder whether the text will then become unreadable as a result :-)
