### ISSUE TITLE
NamesAndTypes Value error: Cannot reshape array of size 63716436 into shape (3794,8397)

### ISSUE THREAD

**Issue by sjmurphy1994** [CellProfiler/CellProfiler#4230]
Hello, 
I'm trying to run a basic cell count pipeline using a mask and when I run the analysis, I get the error attached. All of my images are 8-bit and parameters set to grayscale. Is there something else I need to change?
![Screen Shot 2020-09-10 at 2 47 29 PM](https://user-images.githubusercontent.com/62559939/92784791-e27fbe80-f374-11ea-854d-c0b4db0d3dd9.png)
![Screen Shot 2020-09-10 at 2 47 53 PM](https://user-images.githubusercontent.com/62559939/92784798-e3b0eb80-f374-11ea-88a7-9e1c8462c114.png)
![Screen Shot 2020-09-09 at 10 30 47 AM](https://user-images.githubusercontent.com/62559939/92784036-4950a800-f374-11ea-9922-cec1b5da92de.png)

**Comment by DavidStirling** [comment]
Hi @sjmurphy1994,

Would you be able to copy over any error you see in the console window? It might also help if you could upload one of the problem images.

Thanks!

**Comment by sjmurphy1994** [comment]
Heres the console error:
Worker 0: generated new fontManager
Worker 0: Doing job: 1
Worker 0: C:\Users\STEVEN~1\AppData\Local\Temp\_MEI19~1\cellprofiler\utilities\hdf5_dict.py:539: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype(int).type`.
Worker 0: C:\Users\STEVEN~1\AppData\Local\Temp\_MEI19~1\cellprofiler\utilities\hdf5_dict.py:541: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
Worker 0: Thu Sep 10 15:01:33 2020: Image # 1, module Images # 1: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Worker 0: Thu Sep 10 15:01:33 2020: Image # 1, module Metadata # 2: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Worker 0: Error detected during run of module NamesAndTypes#3
Worker 0: Traceback (most recent call last):
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 1924, in run_image_set
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 2034, in run_module
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1753, in run
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1805, in add_image_provider
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1845, in add_simple_image
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1859, in add_provider_measurements
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 2358, in provide_image
Worker 0:   File "CellProfiler\cellprofiler\modules\loadimages.py", line 3573, in provide_image
Worker 0:   File "CellProfiler\cellprofiler\modules\loadimages.py", line 3536, in __set_image
Worker 0:   File "site-packages\bioformats\formatreader.py", line 832, in read
Worker 0: ValueError: cannot reshape array of size 63716436 into shape (3794,8397)

Attached is the original and mask (I run them as TIFFs but converted them for upload here)
![2020-09-08_FFC_250_Lft_S2_DAPI](https://user-images.githubusercontent.com/62559939/92787147-d85ebf80-f376-11ea-95cf-af7197c4e64a.jpg)
![2020-09-08_FFC_250_Lft_S2_DAPIHcThumbnail](https://user-images.githubusercontent.com/62559939/92787155-da288300-f376-11ea-887b-a7f4ddb81b22.jpg)

**Comment by DavidStirling** [comment]
Hi @sjmurphy1994,

Thanks for providing the info. It looks like this might be a file format-specific problem, so if you could provide just one of the original .tiff files that'd be super helpful!

**Comment by sjmurphy1994** [comment]
GitHub won't accept .tiff files so I had to change them. Is there another way I can send them to you?

**Comment by DavidStirling** [comment]
You should be able to upload a tif to dropbox, google drive or any other cloud service and create a link to it. Otherwise you could try adding the image to a .zip archive and uploading that instead.

**Comment by sjmurphy1994** [comment]
https://www.dropbox.com/sh/vtii2t5r39uu8rp/AAAeaZF7piK2RBETmObOwr7ma?dl=0

**Comment by DavidStirling** [comment]
Thanks for that @sjmurphy1994 ,

It looks like the Ilastik image is a multi-channel TIF, so you'll need to set the image type to "Color" instead of "Grayscale" for that particular image in each set. That should get it working for you. They greyscale image reader can't handle multichannel images.

**Comment by sjmurphy1994** [comment]
I switched it to color and got the same error...

**Comment by DavidStirling** [comment]
Sorry to hear that, could you send over a copy of the pipeline file?

**Comment by sjmurphy1994** [comment]
I'll add it to the dropbox

**Comment by DavidStirling** [comment]
Thanks. Looks like your second NamesAndTypes definition was set to "Does Not... Have Channel Matching "DAPI", which was making it match the Ilastik image twice instead of the binary mask. By setting that to "Does" instead I was able to get into test mode.

**Comment by sjmurphy1994** [comment]
So I tried it again and it popped up a different error saying that the color option has to be in grayscale: 

![Screen Shot 2020-09-10 at 7 22 05 PM](https://user-images.githubusercontent.com/62559939/92823185-ff2eed00-f39a-11ea-9604-e543dab5924d.png)

**Comment by DavidStirling** [comment]
Yes, you'll need to split the color image into seperate channels using the ColorToGray module.

**Comment by sjmurphy1994** [comment]
Okay great thank you so much!
