### ISSUE TITLE
CellProfiler 4 seems to have introduced an error in FilterObjects

### ISSUE THREAD

**Issue by jramunas** [CellProfiler/CellProfiler#4237]
**Bug Description**
A pipeline [(link](https://drive.google.com/drive/folders/1onxVVU-kdLbgGWESa15I7oEPE_b46DIA?usp=sharing)) that worked in CP v3 is not working in CP v4. Specifically, FilterObjects now generates an error message when filtering objects based on Texture Measurements. More specifically, in the FilterObjects interface, in the Scale dropdown, scales are listed (e.g. 5_00, 5_01, …), but selection of any of the listed scales causes an error message stating that the scale is not measured. The same error message is shown regardless of the type of texture measurement selected (Contrast, Entropy, …).

**To Reproduce the Error**
1. Download and open this project in CellProfiler v.4.03:
[https://drive.google.com/drive/folders/1onxVVU-kdLbgGWESa15I7oEPE_b46DIA?usp=sharing](https://drive.google.com/drive/folders/1onxVVU-kdLbgGWESa15I7oEPE_b46DIA?usp=sharing)
It is a bare bones project with three steps: IdentifyPrimaryObjects, MeasureTexture, and FilterObjects.  The error occurs in the FilterObjects step.
2. Click on the FilterObjects step and place the cursor over the "Scale" dropdown to see the error message.

**Expected behavior**
This error didn’t happen in VP v3; it presented measurements to filter with, you selected one, and it filtered using that measurement.

**Screenshots**
Screen shot of error message in FilterObjects step:
![FilterObjects_error](https://user-images.githubusercontent.com/7286289/93028852-97131d80-f5cb-11ea-875a-b68077e133bb.png)

Screen shot of MeasureTexture step preceding FilterObjects step:
![MeasureTexture_step](https://user-images.githubusercontent.com/7286289/93028856-9bd7d180-f5cb-11ea-8e3c-a6a36107a2d7.png)

**Desktop:**
 - Windows 10
 - CellProfiler Version 4.02 and 4.03
 - Downloaded from the website.

**Additional context**
Please email ramunas@rejuvenationtech.com if additional information is needed.  Thank you!

**Comment by bethac07** [comment]
So this is because MeasureTexture added an extra parameter you can control (grey levels), which means the feature names are now slightly different- if before you wanted to measure Contrast_5_03, now you want to measure Contrast 5_03_256 (or whatever your grey level choice is, in your screenshot it's 256).  If you use the dropdown menu next to "Select feature name to filter by", you should see that measurement- please feel free to reopen if you don't!

**Comment by bethac07** [comment]
Never mind, I see what the issue is, we will try to get a fix out asap.
