### ISSUE TITLE
Write an "updating a plugin for CP4" wiki guide

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4244]
If it doesn't already exist, we should have a page outlining the key changes that will impact plugins which people wish to update for CP4. This means explaining core and what moved there, and also some of the renamed functions and setting names.

**Comment by bethac07** [comment]
https://github.com/CellProfiler/CellProfiler-plugins/wiki/CellProfiler-3-to-4-migration-guide
