### ISSUE TITLE
Intensity normalization factor in preferences doesn't save between sessions

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4256]
**Describe the bug**
If you set the normalization number to anything other than 1, and close and then reopen CellProfiler, the number goes back to 1. Was true in CP3 as well; seems like one of those things I always noticed, but never got around to making an issue about. 

OSX 10.14, CP 3.X and 4.0.3

**Comment by DavidStirling** [comment]
https://github.com/CellProfiler/core/blob/c08983fdc36580c35b593c115ab4b789a6715e5e/cellprofiler_core/preferences/__init__.py#L1799-L1811

Well there's the problem: it's hard-coded and doesn't actually write a config setting!

**Comment by bethac07** [comment]
LOL, that'll do it!
