### ISSUE TITLE
Increase threshold sigfig display in Identify* figures

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#4263]
**Is your feature request related to a problem? Please describe.**
For lower threshold values, the number of significant figures may not be enough to capture the actual value:
![image](https://user-images.githubusercontent.com/1186440/94148800-15ca4f00-fe45-11ea-8f81-e8df86211b51.png)
This can hamper setting tweaking.

CP 2.2.0 seemed to DTRT:
![image](https://user-images.githubusercontent.com/1186440/94148703-f4696300-fe44-11ea-96c0-50cc25b12b72.png)

**Describe the solution you'd like**
A sufficient number of sigfigs, maybe using `%g` formatting instead of `%f`?

**Describe alternatives you've considered**

Comparing the master and 2.2.0 code, it appears that the value is formatted with `%.3f` so I'm not sure how this difference crept in.

**Comment by DavidStirling** [comment]
IDPrimary already used `%g` rather than `%f`, so I've made IDSecondary match that.
