### ISSUE TITLE
wxWidgets error dialog box repeatedly reappears upon dismissal

### ISSUE THREAD

**Issue by darrentyson** [CellProfiler/CellProfiler#4264]
Execution of pipeline (modified from ExamplePercentPositive.cppipe) run on large image set (2400 image pairs) causes wxWidgets error about halfway through (see Screen Shot).

<img width="424" alt="Screen Shot 2020-09-24 at 10 17 36 PM" src="https://user-images.githubusercontent.com/8713961/94223507-c112ec80-feb5-11ea-9d8b-44f87ecc3100.png">

Dialog returns after every time it is dismissed using either "cancel" or "continue" requiring force quit to continue.

Same pipeline runs all the way through with subset of images (800 images). Will attempt to reproduce using locally compiled version.

**Desktop:**
 - MacOS 10.15.6
 - CellProfiler 4.0.4
 - Downloaded from the website

**Comment by bethac07** [comment]
Do you have the "eyes" in the pipeline open or closed when running?  If open, can you try re-running with them closed? You should notice a speed increase when you do.

That's a bug we had hoped we had left behind in the CellProfiler3/wx3 days when we moved to wx4 for CellProfiler 4, but it's possible it still exists; closing the eyes and/or working in smaller batches are the only things we've found so far that circumvent it.

Now that we know it's still an issue in CP4, we'll look into it!

**Comment by darrentyson** [comment]
Yes, the "eyes" were open when the error occurred. Running the smaller subset and an altered pipeline with all files but with the eyes closed both ran without error. Thanks!

**Comment by kvshams** [comment]
Have the similar issue. No eye is open and it is appearing after almost 70% of the images processed.

CP = 4.2.1
Downloaded from the website
MacOS 11.6.2 (2

<img width="1488" alt="Screen Shot 2022-03-28 at 4 04 57 PM" src="https://user-images.githubusercontent.com/6705324/160480226-f636c833-3ab1-4adb-889e-0d49b24b42c7.png">
0G314) BigSur
