### ISSUE TITLE
Merge multiple Binary Mask images with different Cell id?

### ISSUE THREAD

**Issue by hfl112** [CellProfiler/CellProfiler#4265]
Hello,
Any suggestions for me to add multiple binary(0,1) or unit16 Mask images (the result of ) to a combined mask image (with 0 to max number of cells) ? These separated mask images have no overlaps.

I tried ImageMath operation “OR” to merge it, but the finally merged mask image only got (0,1) binary one.
Any advices might be appreciated. 
Thank you

**Comment by bethac07** [comment]
Hi, have you tried our new CombineObjects module? That would be by far the best way to do it- it will be difficult to get CellProfiler to re-number the label values of your masks.

**Comment by hfl112** [comment]
> Hi, have you tried our new CombineObjects module? That would be by far the best way to do it- it will be difficult to get CellProfiler to re-number the label values of your masks without using that.

actually I found the test_combineobjet.py, but I can’t add to the plugins. Can this module apply to cellprofiler 3.1.9 MAC version?

**Comment by DavidStirling** [comment]
Unfortunately CombineObjects was added in CellProfiler 4.0, which is available on our website. It won't be backwards-compatible. In 3.1.9 you could potentially try the ImageMath module followed by ConvertImageToObjects. If the objects don't touch it should be straightforward to apply labels to such a binary mask.

**Comment by hfl112** [comment]
> Unfortunately CombineObjects was added in CellProfiler 4.0, which is available on our website. It won't be backwards-compatible. In 3.1.9 you could potentially try the ImageMath module followed by ConvertImageToObjects. If the objects don't touch it should be straightforward to apply labels to such a binary mask.

Thank you for the help I’ll try to update the software. So the old plugins in 3.1.9 like Imcsegementation is compatible in version 4.0 ?

**Comment by DavidStirling** [comment]
Generally plugins will need to be upgraded for CellProfiler 4.
