### ISSUE TITLE
ClassifyObjects -> Select the object to be classified: does not populate a list of objects

### ISSUE THREAD

**Issue by jzsexton** [CellProfiler/CellProfiler#4270]
When the ClassifyObjects module is added after MeasureObjectIntensity or MeasureObjectSizeShape, one must type in the name of the object.

In the previous version, there was a dropdown menu here that allowed for the selection of the object.

In this version, it seems that you have to explicitly type the name of the object (Nuclei, Cell, etc) in order to activate the other options like category and measurement.

 - OS: Windows 10
 - CellProfiler Version 4.0.5
 - Downloaded from the website

![image](https://user-images.githubusercontent.com/54693853/94718879-5c75e880-0320-11eb-828b-08a73142095c.png)

Thanks!

**Comment by DavidStirling** [comment]
Thanks for that, I've corrected this now! It'll be fixed in the next release, for now typing the name of the object set should still work.
