### ISSUE TITLE
update to guidance for source installation - linux

### ISSUE THREAD

**Issue by SonjaAits** [CellProfiler/CellProfiler#4275]
Thank you for this fantastic new version of CellProfiler! 
Do you have a timeline on when the Linux instructions [https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-(Linux)](url) will be updated for CellProfiler4? Or do you have any guidance for the installation on a CentOS 7.2 cluster in the meantime? Thanks.

**Comment by votti** [comment]
Not directly answering your question: but for just running things in headless mode on a cluster, I have really good experiences in running Cellprofiler directly from a docker container via singularity:
```
singularity exec docker://cellprofiler/cellprofiler:latest cellprofiler -h 
```
This circumvents the requirement for installation :)

**Comment by SonjaAits** [comment]
in this setup, do you have CellProfiler connected to a MySQL database?

**Comment by votti** [comment]
Hm personally I am not using MySQL - but I am fairly sure worst case you need to extend the official CellProfiler Docker image to include the MySQL dependencies and than this would work as well.
In general commands run via singularity can access the file system etc more or less like the program would be natively installed, so if CP is installed with MySQL bindings in the Docker image that should work.

Maybe somebody from the main CP team knows if MySQL bindings are working in the official Docker image?
