### ISSUE TITLE
External plugin with `category=""`crashes Cellprofiler at startup

### ISSUE THREAD

**Issue by votti** [CellProfiler/CellProfiler#4277]
First: I dont expect you to fix this, but I just wanted to report this error as in case someone else runs into this error and googles it.
I just was really puzzeled as I noticed that CP failed to start and only after a while found out this was because I had a plugin sketch in my plugin folder. I don't think a rogue plugin should be able to crash CP like this.

Feel free to immediately close it again.

**Describe the bug**
I just noticed while developing an external plugin that setting an empty string as "category" in a module will crash CellProfiler at startup with the following error message:
```
Traceback (most recent call last):  
File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/app.py",
 line 75, in OnInit     self.frame = CPFrame(None, -1, "CellProfiler")   File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/cpframe.py", line 344, in __init__     self.__attach_views()  
File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/cpframe.py", 
line 1237, in __attach_views     self.__pipeline_controller = PipelineController(self.__workspace, self) 
 File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/pipelinecontroller.py", 
line 210, in __init__     self.populate_edit_menu(self.__frame.menu_edit_add_module)  
File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/pipelinecontroller.py", 
line 2365, in populate_edit_menu     menu.AppendSubMenu(sub_menu, category) wx._core.wxAssertionError: C++ assertion 
""Assert failure"" failed at /home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/stockitem.cpp(213) in wxGetStockLabel(): invalid stock item ID 
OnInit returned false, exiting...
```
**To Reproduce**
Set a module category to an empty string.

Creating a file in a mapped plugins directory with name:
`dummymodule.py`:
```
from cellprofiler_core.module import Module
import cellprofiler_core.setting as cps

class DummyModule(Module):
    module_name = "DummyModule"
    category = ""

    def create_settings(self):
        self.divider = cps.Divider()

    def settings(self):
        return [self.divider]

    def run(self, workspace):
        pass
```

**Expected behavior**
Just don't load this module but don't crash CP

**Desktop (please complete the following information):**
 - OS: Windows (Downloaded), Linux (from source)
 - CellProfiler 4.0.5

**Comment by DavidStirling** [comment]
Looks like sub-menu labels can't be empty strings, not surprising really. That's a hard limit in WX rather than on our end.

Aside from "please don't do that", we could potentially have the Module class default to a particular category if it's left empty. That said, do you still get an error if you don't provide a category at all?

**Comment by votti** [comment]
```
Traceback (most recent call last):
  File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/pipelinecontroller.py", line 2340, in populate_edit_menu
    category = module.category
AttributeError: type object 'DummyModule' has no attribute 'category'
```

If the category is not provided this works like expected - it throws an AttributeError during initialization.

If the category is set to 'None' it throws an:
```
TypeError: 'NoneType' object is not iterable
Unable to instantiate module DummyModule.

Traceback (most recent call last):
```
  File "/home/vitoz/.pyenv/versions/cp4_test/lib/python3.8/site-packages/cellprofiler/gui/pipelinecontroller.py", line 2344, in populate_edit_menu
    categories = list(category) + ["All"]
TypeError: 'NoneType' object is not iterable
```

so the issue is really only with the empty string.

As said, i think this is a bit an esoteric issue, so maybe one should not spend any more time on it :)
