### ISSUE TITLE
ConvertObjectsToImage Fails in CellProfiler v4.0.5

### ISSUE THREAD

**Issue by DJCalUK** [CellProfiler/CellProfiler#4282]
When I use the convert object to image module I receive the following error message:

Error while processing ConvertObjectsToImage:
float() argument must be a string or a number, not 'NoneType'

I have tried with the example images and the same error occurs.

Please can you fix this bug!

**Comment by DavidStirling** [comment]
This will be fixed in 4.0.6, sorry about that!

For now, you can work around this by disabling the preview display for that module (by 'closing the eye icon').
