### ISSUE TITLE
Allow manually set quantile calculation in MeasureImageIntensity

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4283]
Would be nice (as an advanced option) to be able to manually set a specific quantile/s and receive that back as a measurement from MeasureImageIntensity.

**Comment by DavidStirling** [comment]
This is easy to calculate but isn't necessarily trivial to add as a setting within MeasureImageIntensity. How would you feel about a "MeasureImageQuantile" plugin module?

**Comment by ErinWeisbart** [comment]
Since MeasureImageIntensity already outputs 25th and 75th quantiles, it makes more logical sense to me to be able to add additional quantile measurements within the same module.
Do you mind explaining why we can't allow input of a number that we pass to numpy.percentile in the module?

**Comment by DavidStirling** [comment]
Currently MeasureImageIntensity is hard-coded to do 25th and 75th using it's own method, whereas numpy would probably do it better.

I could add this to the module with a bit of work, it's just more fiddly. We'd also need to come up with a system for specifying quantiles in the settings. I figure that people would want to do more than just one additional quantile. My current idea is to allow multiple extra quantiles using a comma-separated string, which would avoid a lot of module bulk that would come from adding a widget per-quantile.

As a plugin it's easier to develop this and get it validating correctly. If it works as I expect it might be easy enough to put into the main module. Excuse me being lazy!

**Comment by ErinWeisbart** [comment]
I support you in getting it to work in the easiest possible way!
Though FWIW I'd love to see it eventually move to the main module ;)
Thanks David!
