### ISSUE TITLE
Custom MySQL port

### ISSUE THREAD

**Issue by dahlo** [CellProfiler/CellProfiler#4287]
Hi there

I have searched the documentation looking for a way to export data to a MySQL database running on a non-standard port but i have not found anything. I had a look in the ExportToDatabase module and saw that there is no port information given to the mysql binding, so it does not seem possible to change the port without changing the source code (https://github.com/CellProfiler/CellProfiler/blob/86c09cc9b6ded5b11825503eea71716dce3fec38/cellprofiler/modules/exporttodatabase.py#L354).

Would it be possible to include a way to specify a port number? Either as a separate variable, or as part of the hostname (url:port)?

I made a draft here, could make a PR, https://github.com/dahlo/CellProfiler/blob/master/cellprofiler/modules/exporttodatabase.py#L355

Cheers

**Comment by DavidStirling** [comment]
I do like the idea of being able to override the default port name, and allowing the port to be specified in the host field would avoid needing a new setting. However, I'm not sure how this would play with IPV6 database addresses (if anyone wanted to use them). A simple solution there may be to check that `.split` is only going to return 2 fragments. Otherwise your solution looks great!

**Comment by dahlo** [comment]
Ah, indeed, I did not consider ipv6. A way around that could be to use
another separator. I have seen exclamation mark (!) used in other projects.
I'll update my code later tonight.

Cheers

**Comment by DavidStirling** [comment]
Thanks, that'd be much appreciated. I think keeping the natural `:` separator would be the most user-friendly option, so it might be best to just ensure the separator only occurs once. Reliably splitting off a port number in IPV6 addresses may require a more complex solution, so it might not be worth worrying about in the first instance.

**Comment by dahlo** [comment]
Ok, added a function to unpack port number from the following formats,
        * IPv4 no port specified
        192.168.1.10

        * IPv4 with port specified
        192.168.1.10:3306

        * IPv6 no port specified
        9001:0db8:85a3:0000:0000:8a2e:0370:7334

        * IPv6 with port specified
        [9001:0db8:85a3:0000:0000:8a2e:0370:7334]:3306

Creating PR and you can have a look at it.

Cheers

**Comment by DavidStirling** [comment]
Added in #4289, thanks for that!
