### ISSUE TITLE
Possible to export a pipeline compatible with lower version?

### ISSUE THREAD

**Issue by raivivek** [CellProfiler/CellProfiler#4291]
Hi — I'm wondering if it's possible to export the pipelines from newer versions of CellProfiler such that they are back-compatible with the previous version. For instance, I'm trying to work with CellProfiler 3.1.9 in production while the pipeline was developed on 4.0.5 (due to numerous reasons regarding installation and such).

**Comment by DavidStirling** [comment]
Hi, unfortunately pipelines can't be downgraded between major versions in this way. If you're having problems with installation or other aspects please let us know, we're happy to help fix these things!

**Comment by raivivek** [comment]
Thanks for your reply. The issue is that I want to install CellProfiler through Conda, but having issues updating the recipe. Please see #3730 for details.

**Comment by DavidStirling** [comment]
Generally we recommend using `pip install cellprofiler` instead of Conda when working with CellProfiler 4, would you be able to try that?

**Comment by raivivek** [comment]
Thanks for the reply. I was able to create Docker containers using the latest CellProfiler version and use that in the HPC environment. I understand the constraint of not fully supporting earlier versions, and it's fine by me.

**Comment by DavidStirling** [comment]
Generally we conserve 'breaking' changes for major releases, and there are major under-the-hood changes in CellProfiler 4 as part of the migration to Python 3. Between minor versions you can generally load 'newer' pipelines, but with a major version change that's simply not possible. Nonetheless, we're glad that you managed to get it working!
