### ISSUE TITLE
Error during run of module SaveImages

### ISSUE THREAD

**Issue by mjkvaak** [CellProfiler/CellProfiler#4299]
Hi, I'm trying to run CP4 inside python3.8 venv on Ubuntu 18.04 following the instructions [here](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-18.04). In the last steps of trying to run your examples, e.g.  [ExampleHuman](https://github.com/CellProfiler/examples/tree/master/ExampleHuman) the script crashes with `Error detected during run of module SaveImages`. Any ideas how this could be fixed? 

```sh
(cellprofiler) root@3888ceaef4f5:/main/tmp/examples/ExampleHuman# cellprofiler -c -r -i images/  -p ExampleHuman.cppipe -o ./new_folder/          
Times reported are CPU and Wall-clock times for each module
Tue Nov  3 12:57:25 2020: Image # 1, module Images # 1: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Tue Nov  3 12:57:25 2020: Image # 1, module Metadata # 2: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Tue Nov  3 12:57:25 2020: Image # 1, module NamesAndTypes # 3: CPU_time = 1.39 secs, Wall_time = 0.28 secs
Tue Nov  3 12:57:25 2020: Image # 1, module Groups # 4: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Tue Nov  3 12:57:25 2020: Image # 1, module IdentifyPrimaryObjects # 5: CPU_time = 0.53 secs, Wall_time = 0.22 secs
Tue Nov  3 12:57:25 2020: Image # 1, module IdentifyPrimaryObjects # 6: CPU_time = 0.17 secs, Wall_time = 0.12 secs
Tue Nov  3 12:57:25 2020: Image # 1, module RelateObjects # 7: CPU_time = 0.01 secs, Wall_time = 0.01 secs
Tue Nov  3 12:57:25 2020: Image # 1, module IdentifySecondaryObjects # 8: CPU_time = 0.27 secs, Wall_time = 0.27 secs
Tue Nov  3 12:57:26 2020: Image # 1, module IdentifyTertiaryObjects # 9: CPU_time = 0.06 secs, Wall_time = 0.06 secs
Tue Nov  3 12:57:26 2020: Image # 1, module MeasureObjectIntensity # 10: CPU_time = 0.52 secs, Wall_time = 0.52 secs
Tue Nov  3 12:57:26 2020: Image # 1, module MeasureObjectSizeShape # 11: CPU_time = 2.04 secs, Wall_time = 2.05 secs
Tue Nov  3 12:57:28 2020: Image # 1, module OverlayOutlines # 12: CPU_time = 0.01 secs, Wall_time = 0.02 secs
Error detected during run of module SaveImages
Traceback (most recent call last):
  File "/main/tmp/CellProfiler/cellprofiler/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 958, in run_with_yield
    self.run_module(module, workspace)
  File "/main/tmp/CellProfiler/cellprofiler/lib/python3.8/site-packages/cellprofiler_core/pipeline/_pipeline.py", line 1275, in run_module
    module.run(workspace)
  File "/main/tmp/CellProfiler/cellprofiler/lib/python3.8/site-packages/cellprofiler/modules/saveimages.py", line 548, in run
    should_save = self.run_image(workspace)
  File "/main/tmp/CellProfiler/cellprofiler/lib/python3.8/site-packages/cellprofiler/modules/saveimages.py", line 592, in run_image
    self.save_image(workspace)
  File "/main/tmp/CellProfiler/cellprofiler/lib/python3.8/site-packages/cellprofiler/modules/saveimages.py", line 699, in save_image
    filename = self.get_filename(workspace)
  File "/main/tmp/CellProfiler/cellprofiler/lib/python3.8/site-packages/cellprofiler/modules/saveimages.py", line 877, in get_filename
    filename += suffix
TypeError: can't concat str to bytes
Tue Nov  3 12:57:28 2020: Image # 1, module SaveImages # 13: CPU_time = 0.00 secs, Wall_time = 0.00 secs
```

**Comment by DavidStirling** [comment]
Hi @mjkvaak,

Could I check whether you're running the latest version of CellProfiler 4 (4.0.6)? I think we may have addressed this in a recent update.

**Comment by mjkvaak** [comment]
CP version is 4.0.6:
```sh
$ (cellprofiler) root@3888ceaef4f5: cellprofiler --version
4.0.6
```

**Comment by DavidStirling** [comment]
Thanks, I've not been able to replicate this on my end. Would you be able to upload the specific copy of the pipeline file which you have?

**Comment by mjkvaak** [comment]
You can find the pipeline file from CellProfiler samples linked in the issue opening post. I used the `ExampleHuman` example, however I couldn't get any of the five randomly tested pipelines working.

**Comment by DavidStirling** [comment]
Thanks, just wanted to check that the pipeline wasn't edited. I'm not encountering this problem on Windows, but I'm struggling to see how this could be Ubuntu-specific. Would you mind checking your `pip freeze` and confirming which revision of `cellprofiler-core` you have?

**Comment by mjkvaak** [comment]
Thank you for enthusiastically looking into this! Here's the result of `pip freeze` in the `cellprofiler python3.8 venv`:
```sh
$ (cellprofiler) root@3888ceaef4f5: pip freeze
boto3==1.16.10
botocore==1.19.10
cached-property==1.5.2
CellProfiler==4.0.6
cellprofiler-core==4.0.6
centrosome==1.2.0
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
deprecation==2.1.0
docutils==0.15.2
future==0.18.2
h5py==3.0.0
idna==2.10
imageio==2.9.0
inflect==4.1.0
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.17.0
kiwisolver==1.3.1
mahotas==1.4.11
MarkupSafe==1.1.1
matplotlib==3.1.3
mysqlclient==1.4.6
networkx==2.5
numpy==1.19.4
packaging==20.4
Pillow==8.0.1
prokaryote==2.4.2
psutil==5.7.3
pyparsing==2.4.7
python-bioformats==4.0.0
python-dateutil==2.8.1
python-javabridge==4.0.0
PyWavelets==1.1.1
pyzmq==18.0.1
requests==2.24.0
s3transfer==0.3.3
scikit-image==0.17.2
scikit-learn==0.23.2
scipy==1.5.3
sentry-sdk==0.19.2
six==1.15.0
threadpoolctl==2.1.0
tifffile==2020.10.1
urllib3==1.25.11
wxPython==4.1.0
```

**Comment by DavidStirling** [comment]
Thanks again, that all appears to be up-to-date. Would you be able to test whether you see the same error when running in the GUI and executing the module in test mode?

It looks like this is related to the `os` module being able to return bytes objects on non-Windows systems. We should be able to find a workaround for this for the next version

**Comment by mjkvaak** [comment]
Unfortunately I cannot run GUI, but only the command line in the virtual machine. If what you are suspecting about `os` is true, then the problem should persist on my laptop with Ubuntu 20.04 where I can test the GUI also. All the errors I have faced so far have been referring to problems with bytes, so your guess is probably correct. 

Testing the GUI will take some more time though. Do you have some solution (even a "dirty hack" would do) in mind, that I could try in a git fork? Sorry for being pushy: I would need to get this working soon in a project.

**Comment by bethac07** [comment]
Stab in the dark, just to confirm- your examples repo has been pulled recently, you're not maybe accidentally running a CP3 pipeline in CP4? That would definitely be a bug for us to look into, but might explain why David and I haven't been able to replicate.

No one has reported any issues with our 4.0.6 docker, and that in fact uses the ExampleHuman pipeline as its test pipeline if you run "make test", which I just now re-confirmed works fine.  If you can't get an installed version to work, maybe a Docker would satisfy your use case?

**Comment by DavidStirling** [comment]
If you do still have trouble, you could add a quick and dirty workaround to SaveImages line 877:

```
if isinstance(filename, bytes):
    suffix = suffix.encode()
```                

That should fix the issue in that particular location, but I do expect that the same problem can pop up elsewhere. Are there any unusual characters in the pathnames you're using with this experiment?

**Comment by mjkvaak** [comment]
Hi @DavidStirling & @bethac07. I literally cloned [this repo](https://github.com/CellProfiler/examples) and even the last commit says that these should be CP4 pipelines. Unfortunately all of the pipelines fail, most due to `TypeError: can't concat str to bytes`. Docker might be an option, I will try that. There are no unusual characters in my cwd 
```sh $ pwd 
/home/mikko/Fun/examples/ExampleTumor
```
I have confirmed this with two linux distros now, Ubuntu 18.04 and Ubuntu 20.04. In both cases CP version is 4.0.6. I even tried installing CP3 but it seemed there were too many complications with the aforementioned Ubuntus.

**Comment by mjkvaak** [comment]
For your information, I could fix the `TypeError: can't concat str to bytes` error using @DavidStirling's hint and replacing line 877 in `cellprofiler/modules/saveimages.py` with
```python
filename += suffix.encode() if isinstance(filename, bytes) else suffix
```
I didn't face any problems downstream because of this. It's a hack so I won't make a PR, but maybe it's good to know for other's that may be facing this.

I found and tested that this Dockerfile also works: https://github.com/pharmbio/cellprofiler-docker/blob/master/v4.0.6/Dockerfile. In the last lines of that docker-recipe, the author tampers with the locale settings. This is so far fetched that I am almost too ashamed to say it aloud, but could the `TypeError` be related to locales?

**Comment by bethac07** [comment]
It is formally possible that it has something to do with locales, but I tested it for 4.0.6 in the [official CellProfiler Docker](https://github.com/CellProfiler/distribution/blob/master/docker/Dockerfile), which does not do anything with locale settings (I realize the version number there is 4.0.1, but we bump version numbers every time when we build), and ExportToSpreadsheet and the whole rest of the ExampleHuman pipeline run fine in that, so I still think the issue is likely to be on your system.

**Comment by bethac07** [comment]
We found out last night in the issue David linked above that h5py 3 is causing a number of underlying CellProfiler issues, can you try downgrading/pinning to 2.10 and see if that fixes your build?
