### ISSUE TITLE
Got an error in concertimagetoobject 

### ISSUE THREAD

**Issue by hfl112** [CellProfiler/CellProfiler#4300]
![image](https://user-images.githubusercontent.com/33510929/98213320-db91b880-1f7f-11eb-82d2-105f9942dc5b.png)

Error while processing ConvertImageToObjects:
too many values to unpack (expected 2)

Any ideas why this will happen?

**Comment by DavidStirling** [comment]
Hi @hfl112,

This might depend on what kind of image you loaded in. Would you be able to upload a copy of the pipeline, and perhaps an example image? Thanks

**Comment by DavidStirling** [comment]
Unable to replicate this on our end, perhaps there's something unusual about the input image? Feel free to re-open this with more information.
