### ISSUE TITLE
`exporttospreadsheets` crashes on bytes values

### ISSUE THREAD

**Issue by mjkvaak** [CellProfiler/CellProfiler#4304]
On line 1152 in `cellprofiler/modules/exporttospeadsheets.py` the elif-clause ` elif numpy.isnan(value)` may result to `TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''` if `value` is a bytes object. A possible fix is to change line 1143 from `elif isinstance(value, str): into `elif isinstance(value, bytes):`. Notice that the lines 1143 and 1145 are duplicate elif-clauses in `exporttospeadsheets.py` that you might want to delete: I propose alternative use for the duplicate. So the `TypeError` evades when the block between lines 1136 to 1158 is changed to:

```python
                    else:
                        if feature_name in agg_measurements:
                            value = agg_measurements[feature_name]
                        else:
                            value = m[IMAGE, feature_name, img_number]
                        if value is None:
                            row.append("")
                        elif isinstance(value, str):
                            row.append(value)
                        elif isinstance(value, bytes):
                            row.append(value.decode())
                        elif (
                            isinstance(value, numpy.ndarray)
                            and value.dtype == numpy.uint8
                        ):
                            row.append(base64.b64encode(value.data))
                        elif numpy.isnan(value):
                            if self.nan_representation == NANS_AS_NULLS:
                                row.append("")
                            else:
                                row.append(str(numpy.NaN))
                        else:
                            row.append(str(value))
```

**Comment by DavidStirling** [comment]
Thanks, you're absolutely right here - the bytes decoding functionality was unintentionally lost in the upgrade from Python 2 to Python 3. Fixed it now.
