### ISSUE TITLE
Upgrade to h5py 3.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4306]

**Comment by vkhodygo** [comment]
This issue requires more attention, `h5py==2.10.0` wheels go up to python 3.8 whereas many systems have migrated to 3.9 already.

**Comment by vkhodygo** [comment]
I know that this issue has been closed but I have a related question:
@bethac07 do you plan to have a minor release any time soon? 
I can use the git version but building the package with updated `h5py` support is a very unpleasant and long process.
