### ISSUE TITLE
no spreadsheet saved

### ISSUE THREAD

**Issue by zhangguy** [CellProfiler/CellProfiler#4309]
**Describe the bug**
no csv file output

**Desktop (please complete the following information):**
 - OS: Mac os 10.13.6
 - CellProfiler Version 4.0.6
 - installed from source
 - followed the wiki

**Additional context**
Hi, 

Thanks so much for developing the package. I'm trying to run the example pipeline from the 'Welcome to Cellprofiler!' window. I loaded it by clicking on the 'Try Example' button and run it by clicking on 'Analyze Images'. The modules before 'ExportToSpreadSheet' run fine without errors but I waited and waited there is no .csv files exported in my default output folder. The cropped images are saved but not the csv files.
Also the pipeline doesn't finish, i.e., the clock counting doesn't stop. And here are the output from the terminal
```
Worker 0: Running module GrayToColor 14
Worker 0: Tue Nov 17 22:05:30 2020: Image # 3, module GrayToColor # 14: CPU_time = 0.01 secs, Wall_time = 0.68 secs
Worker 0: Running module SaveImages 15
Worker 1: Tue Nov 17 22:05:30 2020: Image # 2, module MeasureTexture # 13: CPU_time = 1.01 secs, Wall_time = 1.39 secs
Worker 1: Running module GrayToColor 14
Worker 1: Tue Nov 17 22:05:31 2020: Image # 2, module GrayToColor # 14: CPU_time = 0.00 secs, Wall_time = 3.10 secs
Worker 1: Running module SaveImages 15
Worker 0: Tue Nov 17 22:05:31 2020: Image # 3, module SaveImages # 15: CPU_time = 0.01 secs, Wall_time = 3.87 secs
Worker 0: Running module ExportToSpreadsheet 16
Worker 0: Tue Nov 17 22:05:35 2020: Image # 3, module ExportToSpreadsheet # 16: CPU_time = 0.00 secs, Wall_time = 1.00 secs
Worker 1: Tue Nov 17 22:05:35 2020: Image # 2, module SaveImages # 15: CPU_time = 0.01 secs, Wall_time = 1.45 secs
Worker 1: Running module ExportToSpreadsheet 16
Progress Counter({b'Done': 1, b'InProcess': 1, b'FinishedWaitingMeasurements': 1})
Worker 1: Tue Nov 17 22:05:36 2020: Image # 2, module ExportToSpreadsheet # 16: CPU_time = 0.01 secs, Wall_time = 1.00 secs
Progress Counter({b'Done': 2, b'FinishedWaitingMeasurements': 1})
Progress Counter({b'Done': 3})
```
Could you help? Thanks.

**Comment by DavidStirling** [comment]
Hi @zhangguy 

> Also the pipeline doesn't finish

This would be why it's not writing the CSVs. Would you be able to try selecting the terminal window and pressing cmd+c while it's in this state? That may trigger an error message to be printed out in the console.

Thanks

**Comment by zhangguy** [comment]
> Hi @zhangguy
> 
> > Also the pipeline doesn't finish
> 
> This would be why it's not writing the CSVs. Would you be able to try selecting the terminal window and pressing cmd+c while it's in this state? That may trigger an error message to be printed out in the console.
> 
> Thanks

Hi @DavidStirling 

Thanks for your fast response. Nothing happens if I do cmd+c. If I do cntrl+c it'll quite, no error messages. 
I saw some hdf5 temp files blinking in my output folder. Is this something related to h5py? I had to use h5py=3.1.0, because I couldn't install 2.* from pip.

And it there a way I could troubleshoot through the API?

Thanks.

**Comment by DavidStirling** [comment]
Ah yes, that'd do it. CellProfiler is currently incompatible with H5Py 3, you'll need 2.10.0. Is there a particular reason that you were unable to install H5Py 2 using pip?

**Comment by zhangguy** [comment]
> Ah yes, that'd do it. CellProfiler is currently incompatible with H5Py 3, you'll need 2.10.0. Is there a particular reason that you were unable to install H5Py 2 using pip?

I tried pip install 2.8.0 ~ 2.10.0, all of them are giving lots of warnings and these errors
```
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:16016:56: error: too few arguments to function call, expected 3, have 2
      __pyx_t_1 = H5Oget_info(__pyx_v_loc_id, __pyx_v_oinfo); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1462, __pyx_L1_error)
                  ~~~~~~~~~~~                              ^
    /usr/local/include/H5Opublic.h:187:8: note: 'H5Oget_info3' declared here
    H5_DLL herr_t H5Oget_info3(hid_t loc_id, H5O_info2_t *oinfo, unsigned fields);
           ^
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:16131:95: error: too few arguments to function call, expected 5, have 4
      __pyx_t_1 = H5Oget_info_by_name(__pyx_v_loc_id, __pyx_v_name, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1473, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~~~~                                                             ^
    /usr/local/include/H5Opublic.h:188:8: note: 'H5Oget_info_by_name3' declared here
    H5_DLL herr_t H5Oget_info_by_name3(hid_t loc_id, const char *name, H5O_info2_t *oinfo,
           ^
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:16246:144: error: too few arguments to function call, expected 8, have 7
      __pyx_t_1 = H5Oget_info_by_idx(__pyx_v_loc_id, __pyx_v_group_name, __pyx_v_idx_type, __pyx_v_order, __pyx_v_n, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1484, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~~~                                                                                                               ^
    /usr/local/include/H5Opublic.h:190:8: note: 'H5Oget_info_by_idx3' declared here
    H5_DLL herr_t H5Oget_info_by_idx3(hid_t loc_id, const char *group_name,
           ^
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:17281:100: error: too few arguments to function call, expected 6, have 5
      __pyx_t_1 = H5Ovisit(__pyx_v_obj_id, __pyx_v_idx_type, __pyx_v_order, __pyx_v_op, __pyx_v_op_data); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1583, __pyx_L1_error)
                  ~~~~~~~~                                                                             ^
    /usr/local/include/H5Opublic.h:211:8: note: 'H5Ovisit3' declared here
    H5_DLL herr_t H5Ovisit3(hid_t obj_id, H5_index_t idx_type, H5_iter_order_t order,
           ^
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:17396:143: error: too few arguments to function call, expected 8, have 7
      __pyx_t_1 = H5Ovisit_by_name(__pyx_v_loc_id, __pyx_v_obj_name, __pyx_v_idx_type, __pyx_v_order, __pyx_v_op, __pyx_v_op_data, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1594, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~                                                                                                                ^
    /usr/local/include/H5Opublic.h:213:8: note: 'H5Ovisit_by_name3' declared here
    H5_DLL herr_t H5Ovisit_by_name3(hid_t loc_id, const char *obj_name,
           ^
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:21306:13: warning: assigning to 'void *' from 'const void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
      __pyx_t_1 = H5Pget_driver_info(__pyx_v_plist_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1969, __pyx_L1_error)
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:33261:68: error: too few arguments to function call, expected 4, have 3
      __pyx_t_1 = H5Sencode(__pyx_v_obj_id, __pyx_v_buf, __pyx_v_nalloc); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 3172, __pyx_L1_error)
                  ~~~~~~~~~                                            ^
    /usr/local/include/H5Spublic.h:129:8: note: 'H5Sencode2' declared here
    H5_DLL herr_t H5Sencode2(hid_t obj_id, void *buf, size_t *nalloc, hid_t fapl);
           ^
    2 warnings and 6 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
```
And my HDF5 1.12.0_1 is a new installation with brew.

**Comment by zhangguy** [comment]
> > Ah yes, that'd do it. CellProfiler is currently incompatible with H5Py 3, you'll need 2.10.0. Is there a particular reason that you were unable to install H5Py 2 using pip?
> 
> I tried pip install 2.8.0 ~ 2.10.0, all of them are giving lots of warnings and these errors
> 
> ```
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:16016:56: error: too few arguments to function call, expected 3, have 2
>       __pyx_t_1 = H5Oget_info(__pyx_v_loc_id, __pyx_v_oinfo); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1462, __pyx_L1_error)
>                   ~~~~~~~~~~~                              ^
>     /usr/local/include/H5Opublic.h:187:8: note: 'H5Oget_info3' declared here
>     H5_DLL herr_t H5Oget_info3(hid_t loc_id, H5O_info2_t *oinfo, unsigned fields);
>            ^
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:16131:95: error: too few arguments to function call, expected 5, have 4
>       __pyx_t_1 = H5Oget_info_by_name(__pyx_v_loc_id, __pyx_v_name, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1473, __pyx_L1_error)
>                   ~~~~~~~~~~~~~~~~~~~                                                             ^
>     /usr/local/include/H5Opublic.h:188:8: note: 'H5Oget_info_by_name3' declared here
>     H5_DLL herr_t H5Oget_info_by_name3(hid_t loc_id, const char *name, H5O_info2_t *oinfo,
>            ^
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:16246:144: error: too few arguments to function call, expected 8, have 7
>       __pyx_t_1 = H5Oget_info_by_idx(__pyx_v_loc_id, __pyx_v_group_name, __pyx_v_idx_type, __pyx_v_order, __pyx_v_n, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1484, __pyx_L1_error)
>                   ~~~~~~~~~~~~~~~~~~                                                                                                               ^
>     /usr/local/include/H5Opublic.h:190:8: note: 'H5Oget_info_by_idx3' declared here
>     H5_DLL herr_t H5Oget_info_by_idx3(hid_t loc_id, const char *group_name,
>            ^
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:17281:100: error: too few arguments to function call, expected 6, have 5
>       __pyx_t_1 = H5Ovisit(__pyx_v_obj_id, __pyx_v_idx_type, __pyx_v_order, __pyx_v_op, __pyx_v_op_data); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1583, __pyx_L1_error)
>                   ~~~~~~~~                                                                             ^
>     /usr/local/include/H5Opublic.h:211:8: note: 'H5Ovisit3' declared here
>     H5_DLL herr_t H5Ovisit3(hid_t obj_id, H5_index_t idx_type, H5_iter_order_t order,
>            ^
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:17396:143: error: too few arguments to function call, expected 8, have 7
>       __pyx_t_1 = H5Ovisit_by_name(__pyx_v_loc_id, __pyx_v_obj_name, __pyx_v_idx_type, __pyx_v_order, __pyx_v_op, __pyx_v_op_data, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1594, __pyx_L1_error)
>                   ~~~~~~~~~~~~~~~~                                                                                                                ^
>     /usr/local/include/H5Opublic.h:213:8: note: 'H5Ovisit_by_name3' declared here
>     H5_DLL herr_t H5Ovisit_by_name3(hid_t loc_id, const char *obj_name,
>            ^
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:21306:13: warning: assigning to 'void *' from 'const void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
>       __pyx_t_1 = H5Pget_driver_info(__pyx_v_plist_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1969, __pyx_L1_error)
>                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     /private/var/folders/4p/jhc1ly593tx8vyx66lg51xk40000gp/T/pip-install-tw01gdu5/h5py/h5py/defs.c:33261:68: error: too few arguments to function call, expected 4, have 3
>       __pyx_t_1 = H5Sencode(__pyx_v_obj_id, __pyx_v_buf, __pyx_v_nalloc); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 3172, __pyx_L1_error)
>                   ~~~~~~~~~                                            ^
>     /usr/local/include/H5Spublic.h:129:8: note: 'H5Sencode2' declared here
>     H5_DLL herr_t H5Sencode2(hid_t obj_id, void *buf, size_t *nalloc, hid_t fapl);
>            ^
>     2 warnings and 6 errors generated.
>     error: command '/usr/bin/clang' failed with exit code 1
>     ----------------------------------------
> ```
> 
> And my HDF5 1.12.0_1 is a new installation with brew.

figured out need to downgrade HDF5 as well, and put the path of hdf5 into the path when pip install h5py
```
## install an older version of hdf5
brew install hdf5@1.8

## check where hdf5 was installed
brew info hdf5@1.8

## install h5py with HDF5@1.8
HDF5_DIR=/usr/local/opt/hdf5@1.8 pip3 install --no-cache-dir --force-reinstall --no-binary=h5py h5py==2.10.0

## now go to the CellProfiler dir and install it
pip3 install --no-cache-dir .
```
Now the example pipeline is saving csv files.

**Comment by bethac07** [comment]
Glad to hear it's working now! Will close.
