### ISSUE TITLE
Example for "CellProfiler as python package" not working, as variable "module" never assigned.

### ISSUE THREAD

**Issue by burmeisc** [CellProfiler/CellProfiler#4319]
In the example for using CellProfiler as a python package the parameter "module" passed to Workspace is never assigned. 
Therefore, the example does not work. 

```
workspace = cellprofiler_core.workspace.Workspace(
    pipeline,
    module,
    image_set,
    object_set,
    measurements,
    image_set_list,
)
```

Furthermore,  does the example pipeline loaded in the beginning exist? 
`pipeline.load("example.cppipe")`

**Comment by DavidStirling** [comment]
Hi @burmeisc,

The page you mentioned isn't really set up as a full tutorial, it's more a demonstration of different available commands. For that reason `example.cppipe` isn't a real pipeline and should be substituted with what the user wishes to run. The user also needs to provide images to analyse.

Nonetheless I've added a bit more detail to the workspace section. `module` needs to be a module from the pipeline itself, so running `pipeline.modules()[0]` should suffice to set up any loaded pipeline to run from the first module.
