### ISSUE TITLE
Problem with alignment

### ISSUE THREAD

**Issue by ofirgriess** [CellProfiler/CellProfiler#4323]
I have the following problem when trying to align

Worker 1: Error detected during run of module Align#6
Worker 1: Traceback (most recent call last):
Worker 1: File “cellprofiler_core\pipeline_pipeline.py”, line 1142, in run_image_set
Worker 1: File “cellprofiler_core\pipeline_pipeline.py”, line 1275, in run_module
Worker 1: File “cellprofiler_core\modules\align.py”, line 283, in run
Worker 1: File “cellprofiler_core\modules\align.py”, line 407, in align
Worker 1: File “cellprofiler_core\modules\align.py”, line 469, in align_cross_correlation
Worker 1: File “scipy\fftpack\basic.py”, line 394, in fft2
Worker 1: File “scipy\fftpack\basic.py”, line 334, in fftn
Worker 1: File “scipy\fftpack\helper.py”, line 104, in _good_shape
Worker 1: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

What may be the cause?

**Comment by DavidStirling** [comment]
Thanks for reporting this and uploading the pipeline on the forum. This does look like an issue with Scipy, so I've reported that at Scipy/Scipy#13342.

In the meantime, I should be able to put in a workaround to get the Align module working again.

Thanks again!
