### ISSUE TITLE
CellProfiler does not open the correct 'Default Output Folder' on analysis completion

### ISSUE THREAD

**Issue by imoutsatsos** [CellProfiler/CellProfiler#4330]
**'Open default output folder' button opens wrong folder**
When an analysis completes and user needs to review saved output

**To Reproduce**
CellProfiler Windows v 4.0.7
1. Execute and analysis until the 'Analysis Complete' dialog is displayed
2. Click the 'Open default output folder' button
3. The 'Documents' folder opens which is not the folder assigned in the Output settings

**Expected behavior**
I expected to display default output folder from settings

**Screenshots**
![image](https://user-images.githubusercontent.com/3408226/105097445-91947b00-5a76-11eb-8c6d-1c9447ad8433.png)

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - CellProfiler Version [4.0.7]
 - Downloaded

**Comment by DavidStirling** [comment]
I've also seen this sometimes but struggle to consistently replicate it. Could I ask if you set up that directory in CellProfiler 4, or perhaps with an older version?

**Comment by imoutsatsos** [comment]
@DavidStirling not sure I understand your question. Do you mean if I let CPv4 create the directory as part of the analysis (like when you want to save results to a folder that does not yet exist)? In this case, I create the output folder first from Windows explorer and then assign it in CP4. Thanks!

**Comment by DavidStirling** [comment]
@imoutsatsos No, sorry. I meant "did you originally change the default output folder to that `\\output_1` directory in an earlier version of CellProfiler?".

**Comment by imoutsatsos** [comment]
No, the \\output_1 was specific to CP4 as I was testing this version

**Comment by DavidStirling** [comment]
Thanks, think I've figured out what's going on.
