### ISSUE TITLE
“CellProfiler2” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by gianttinkerbell** [CellProfiler/CellProfiler#4333]
“CellProfiler2” can’t be opened because Apple cannot check it for malicious software.

**Comment by alicelucas** [comment]
Hi @gianttinkerbell,

Could you try to right click on the CellProfiler icon and click "Open"? If you do that, you should see a new dialog window that allows you to open CellProfiler. After CellProfiler opens for the first time, this original dialog box should not appear again. 

Note that for CellProfiler to open, you may have to move it to your `Applications` folder, if it's not already there.
