### ISSUE TITLE
Allow MeasureObjectNeighbors to export the ObjectNumbers of the closest n neighbors

### ISSUE THREAD

**Issue by pearlryder** [CellProfiler/CellProfiler#4334]
Currently MeasureObjectNeighbors exports only the ObjectNumbers for the two closest neighbors. Some users (see forum post below), would like to have access to the full list of closest neighbors.

[https://forum.image.sc/t/measuring-nuclei-neighbours/47759](https://forum.image.sc/t/measuring-nuclei-neighbours/47759
)

**Describe the solution you'd like**
- could export a user-defined number of closest neighbors and fill any empty columns w/ NaNs

**Comment by bethac07** [comment]
This information does get output (the object numbers, not the coordinates) as part of the Object Relationships csv. I think that's currently a better solution so closing, someone can certainly reopen to argue otherwise.
