### ISSUE TITLE
Certain images make MCE thresholding barf

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4335]
Found by @ErinWeisbart 

**Describe the bug**
A subset of images in a pipeline @ErinWeisbart was running (about 1 in 1,000 of her set) failed repeatedly when she got to a particular step in the pipeline; we traced it to a failure to complete MCE thesholding on that image (runs for at least 2 hours without completing on a 1480^2 image, no errors produced, it just hangs seemingly indefinitely).  Other thresholding algorithms complete in seconds.  The image that fails is created in the pipeline by application of illumination correction; saving out the image (as either 8 or 16 bit tiff) and then importing into CellProfiler, the image is able to be thresholded, so possibly something weird is happening when the illumination correction function is applied that is being "fixed" in the saving process, but I can see no obvious problems in either the pre-correction raw image, post-correction raw image, or the correction function itself (and other images from the same plate with the same function used MCE thresholding just fine).  It's.... very odd. 

Problem does not occur for the same image in CP319.

Images and pipeline to confirm attached.

**Desktop (please complete the following information):**
 - OS: Mac 10.14, 10.15, and Ubuntu 16.04
 - CellProfiler Version 4.0.7
 - Downloaded from the website or installed from source? Both

[MCEBug.zip](https://github.com/CellProfiler/CellProfiler/files/5858512/MCEBug.zip)

**Comment by AnneCarpenter** [comment]
Maybe look at image min/max and/or histogram of the intermediate image vs the saved version of it? Can you load in the saved version of the image, make it fresh in the pipeline, and then subtract the two to see what you get?

**Comment by bethac07** [comment]
Good idea! Here's the "absolute difference" image of the two, and the histogram of the difference image.  So yes, internally, there is some representation that is being changed in the saving process, the question is what and why?

![image](https://user-images.githubusercontent.com/6721515/105545995-c436b180-5cca-11eb-8c98-af629ccdb0f5.png)
![image](https://user-images.githubusercontent.com/6721515/105546008-cb5dbf80-5cca-11eb-84b7-ef3d1c8bc6ce.png)

**Comment by DavidStirling** [comment]
Having taken a quick look, I can confirm it's hanging while it's within the skimage `threshold_li` function. I'll look into it further next week, but we may have a bug to report!

**Comment by bethac07** [comment]
(Unsurprisingly, given the X values above, the histograms of the "created" and "saved" image are not distinguishable by eye)\
![image](https://user-images.githubusercontent.com/6721515/105546365-44f5ad80-5ccb-11eb-9d74-65e9465efc7d.png)

**Comment by AnneCarpenter** [comment]
I would've guessed a pixel or two was out of bounds in some way that is clipped during saving. But if the image after math is showing it's just most pixels are shifting a little here and there I wonder if it's misalignment between the intensity bins of CP's representation vs the intensity bins of the TIF file format or something (so, some pixels are rounded up and some not). Still doesn't explain why thresholding barfs of course

**Comment by bethac07** [comment]
Yeah, 1/(65535*2) = 0.0000076, exactly where that cuts off, so those are clearly rounding differences between the internal representation (when we're dividing two floats) and the "we must discretize this when we save".  The question is what weirdness is being created in the internal representation, and why can't skimage handle it?

**Comment by DavidStirling** [comment]
Definitely something odd here, there's a loop here in Skimage where it gets stuck:

https://github.com/scikit-image/scikit-image/blob/b4c5b1bd00739b3e3b290378cf06dbcb3e3f9ea0/skimage/filters/thresholding.py#L697-L708

Something makes the tested threshold bounce between two sets of values infinitely. I believe the problem may be the `tolerance` parameter. It defaults to "half the smallest difference between intensity values in ``image``". If data was saved incorrectly then the minimum difference may be smaller than an actual step in the intensity values, thus the tolerance condition fails to terminate thresholding. As a fix we could calculate `tolerance` based on expected bit depth and pass that in ourselves?

**Comment by bethac07** [comment]
So I suppose, then, the question becomes, are our images incorrect, or is their function? Do we expect the internal representations of images in CellProfiler to be in increments of 1/65535, or do we keep them as is and only discretize them at the end? My understanding is that the latter is the more desirable behavior, but maybe not?

**Comment by AnneCarpenter** [comment]
I'm personally not going to complain about them not matching precisely, and it seems like a hassle for every image-producing module to discretize its results to avoid situations like this… so we could lodge that as a separate philosophical issue to handle… someday. In the meantime, I think making sure MCF doesn't barf on these particular images shoudl be the focus.

**Comment by DavidStirling** [comment]
> So I suppose, then, the question becomes, are our images incorrect, or is their function?

I think it's a bit of both. Our images have pixel-to-pixel differences which are smaller than floating point error, and the assumptions in the function don't account for this possibility and thus produce an infinite loop in such edge cases. On our end we could specify the bit depth properly, on their end they could 'sanity check' the automatic tolerance calculation.
