### ISSUE TITLE
CP 4.07 Problem with ProcessAs3D in NamesAndTypes and Threshold module

### ISSUE THREAD

**Issue by mbarish** [CellProfiler/CellProfiler#4336]
I think that there is a bug in CP 4.07.  This is the world’s simplest pipeline.  When I run the threshold command on the three attached images as individual images everything is fine.  But when I check ProcessAs3D in NamesAndTypes I get this error message.  Seems like something is wrong.

![image](https://user-images.githubusercontent.com/32918629/105946805-cd9e8180-601c-11eb-803a-bad59a384074.png)

[CP_out 3D test.zip](https://github.com/CellProfiler/CellProfiler/files/5877906/CP_out.3D.test.zip)

**Comment by bethac07** [comment]
Hi,

In order for CellProfiler to process your images as 3D, you need to have all of the images of each channel in a single file- aka if you have 20 Z planes, 1 file with 20 planes, if you have 20 Z planes and 3 channels, 3 files each with 20 planes, etc.  Right now, all your planes are in single files.  Hope that helps!

**Comment by mbarish** [comment]
Thanks for getting back to be so quickly.
But unfortunately when I put the images into a stack (using Fiji), keeping everything else the same, I get the following message:
![image](https://user-images.githubusercontent.com/32918629/106082058-db144400-60ce-11eb-9144-2cb84b4fd0e7.png)
I'm attaching the new image stack.
[Ch2 5-7.zip](https://github.com/CellProfiler/CellProfiler/files/5884411/Ch2.5-7.zip)

**Comment by mbarish** [comment]
Beth, I tried this and got a different error message. I added this to the thread, which I hope was OK even though you closed it.
Thanks.
