### ISSUE TITLE
CP 4.07 Working with a 3D image stack

### ISSUE THREAD

**Issue by mbarish** [CellProfiler/CellProfiler#4337]
![image](https://user-images.githubusercontent.com/32918629/106231153-e0908d80-61a5-11eb-97ec-2ebe7e98bd94.png)
[test3dseg_v2.zip](https://github.com/CellProfiler/CellProfiler/files/5891591/test3dseg_v2.zip)
[Ch2_5-7_c2.zip](https://github.com/CellProfiler/CellProfiler/files/5891596/Ch2_5-7_c2.zip)
I am still having issues with working with a 3D image stack.  When I load these images (stack created in Fiji)  into the attached pipeline, I get the error message above.  The metadata seem correct. Is this a bug in CP, or am I still doing something wrong?
Thanks.

**Comment by DavidStirling** [comment]
Thanks, this should be fixed by #4317. For now you could disable figure display from the 'problem' modules to get the pipeline running.
