### ISSUE TITLE
Memory Issue 

### ISSUE THREAD

**Issue by rachel662** [CellProfiler/CellProfiler#4356]
Hi there 
I get a memory issue when processing some images and it says 
"Error while processing
Memory Error: Unable to allocate 450 GiB for an array with shape (245708, 245708) and data type float64"

would anyone be able to help me with this issue? 
thanks so much 
Rachel

**Comment by bethac07** [comment]
It would be helpful to know your OS, CellProfiler version, the full error trace that generated this, and the pipeline and image set that caused it.  Are your images indeed that large?

**Comment by rachel662** [comment]
Hi, 
I’m on a PC running windows 10
My cellprofiler version is 4.1.3
I have 16Gb RAM

**Comment by bethac07** [comment]
>the pipeline I am using is measure_mask from the IMCsegmentation pipeline

Can you send it along, with an image that causes this issue? Thanks!
