### ISSUE TITLE
Cell profiler 4.1.3 crashes at opening on AWS Windows machine

### ISSUE THREAD

**Issue by aainbind** [CellProfiler/CellProfiler#4364]
I am trying to install the new CP on one of my remote windows machines and the installation process seems to be working well, but then the app won't open, it crashes at the start. Is there something I can do about it? 
Windows 10
CellProfiler Version 4.1.3
Downloaded from the website
No error message, just app closing right away
Thanks.

**Comment by DavidStirling** [comment]
Hi @aainbind 

Could you try installing the [Visual C++ Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe) from Microsoft and let us know if that fixes it?

Thanks

**Comment by aainbind** [comment]
This did the trick! Thanks!
