### ISSUE TITLE
Cell Profiler does not open because apple cannot check for malicious content

### ISSUE THREAD

**Issue by mthul796** [CellProfiler/CellProfiler#4365]
**Desktop (please complete the following information):**
 - macOS 10.15.7 
 - CellProfiler Version 4.1.3
 - Downloaded from the website

issue:
Cell Profiler does not open because apple cannot check for malicious content. I have tried using the workarounds listed on the website with no success.

error message
```cell profiler cannot open because apple cannot check for malicious content
```this app needs to be updated

**Comment by bethac07** [comment]
What happens if you try running with Ctl+Click -> Open? Can you screenshot the error message? 

Do your system Security & Privacy permissions allow you to use apps from "App Store and identified developers", or just "App store"?

**Comment by mthul796** [comment]
Hi Beth,

I've tried opening it that way as well and I still receive the same error.
I've attached a screenshot here.

I appreciate your help!
Mats

[image: Screen Shot 2021-03-01 at 6.19.22 PM.png]
