### ISSUE TITLE
Problems installing on CentOS 7 (with some solutions)

### ISSUE THREAD

**Issue by s-andrews** [CellProfiler/CellProfiler#4368]
Since I spent quite a while yesterday getting CellProfiler running on our cluster I thought I'd share some of the issues (and some solutions) which I hit which might help others who try the same thing.

This was pulling CellProfiler 4.1.3 onto a CentOS7 based machine.

I initially tried a standard pip install which failed during the compilation of wxPython, which seemed to have all sorts of dependencies.  Because of the requirement for python3.8+ I couldn't use the packaged python versions (2.7 and 3.6), nor the pre-compiled CentOS wxPython wheel bundles on the wxPython site.

I then tried the conda install as suggested on the CellProfiler page using the YAML file listed there.  That also failed to install as it again tried to compile wxPython through pip, even though it's listed as a dependency in the YAML file.  It turns out this is becase the ```setup.py``` has a versioned dependency for wxPython (only v4.1.0), and the one in the YAML was unversioned and was newer than that (4.1.1) so pip tried to install an older one.  After modifying the YAML to:

```
name: cp4

channels:
- conda-forge
- anaconda
- bioconda
- defaults

dependencies:
- python=3.8
- numpy
- matplotlib=3.1.3
- pandas
- mysqlclient=1.4.6
- openjdk
- gtk2
- wxpython=4.1.0
- pip:
- cellprofiler 
``` 

..the conda install solved and completed, but cellprofiler still wouldn't run as there were linker problems with the wxPython from conda.  Specifically it couldn't find ```libwebkitgtk-1.0.so.0``` or ```libjavascriptcoregtk-1.0``` and I couldn't find any conda packages which supplied these.  I did try installing versions of these which are bundled with ```gnucash``` in EPEL on CentOS,  but although the linker problems went away I then got a failure with:

```libwebkitgtk-1.0.so.0: undefined symbol: cairo_gl_surface_get_width```

..so there's still an incompatibility with the conda libraries.  I think this is a dead end unless conda update their packages to either recompile the older version of wxPython or supply the missing libraries.

I therefore went back to installing through pip.  Since it was the wxPython which failed and since it required exactly v4.1.0 I tried to manually compile that from the source.  Initially I'd used the latest python 3.9 but found that the wxPython compilation died with an error in the PyUnicode library.  I found similar reports in other packages which suggested this was a regression in python 3.9 which would require fixes.  This may well have been fixed in newer wxPython versions, but since we're stuck using 4.1.0 then cell profiler will *only* work with python 3.8.

Having installed python3.8.8 I then retried the wxPython install and after getting some confusing errors which turned out to be bugs from missing ```libXtst-devel``` and ```libGLU-devel``` having installed those I then managed to wxPython to compile and install.

Once wxPython was installed I was then able to use pip to install cellprofiler and it's now running.

Hopefully this will prove useful to others trying something similar.

**Comment by s-andrews** [comment]
There are more details about this in our internal tracker which you can see [here](https://www.bioinformatics.babraham.ac.uk/cgi-bin/helpdeskuser.cgi?action=show_job&public_id=kitesdecal).

**Comment by iosonofabio** [comment]
For what it's worth, I went through a similar exercise yesterday to get cellprofiler to install on an arch linux machine with Python 3.9 without any virtualization, i.e. no conda and no pip, just bare OS package manager.

It worked well in the end as far as I can tell, happy to post more info if there's interest.

**Comment by my-tien** [comment]
hey, yeah I’d be interested. I couldn’t find a cellprofiler package in the aur, just two orphaned dependencies: python2-prokaryote and python2-centrosome

Before that I tried the conda way with the first yaml here: https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation#cellprofiler-4
That also errored with missing `libwebkitgtk-1.0.so.0`

**Comment by Happylinzy** [comment]
I would like to know how do you install cellprofiler on arch linux

**Comment by iosonofabio** [comment]
Give me a day or two and I'll post here, or ping again please

**Comment by iosonofabio** [comment]
https://github.com/iosonofabio/cellprofiler_PKGBUILDs

Please try it out and if you get stuck because you miss a dep, open an issue on that repo and I'll take a quick look
