### ISSUE TITLE
How to stop CellProfiler to output results

### ISSUE THREAD

**Issue by ykwang1207** [CellProfiler/CellProfiler#4376]
I'm facing a project about group images processing, especially in illumination correction. My goal is to btain the final correction functions of each group, while I worry that showing corrected images memory costs additional memory.
Could there be a sulution that I can disable image output in the period of project?
Many thanks.

**Comment by bethac07** [comment]
Can I clarify, are you asking if you can not show the display windows during processing? If so, then yes, you can always hide these by closing the "eyes" next to each module, and/or going to Windows -> Hide all windows on run.
