### ISSUE TITLE
Mac OSX installation unsuccessful, none of workarounds working, no error message

### ISSUE THREAD

**Issue by yeohelp** [CellProfiler/CellProfiler#4377]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce may be closed without investigation. You may delete this section before posting your issue below.
---

 - OS: Macbook pro OS 10 (next to newest version OS software)
 - CellProfiler Version 4.1.3
 - Downloaded from the website
 - If the latter, how (cloned, installed from pypi, etc)?

I have attempted the installation many times. I am always able to access the zip but every time I try to open cellprofiler nothing happens, it just won't open. There is no error message or anything. I have tried all of the workarounds from the website and none have fixed the issue.

**Comment by bethac07** [comment]
Hi, can you tell us what version of OSX 10 (10.12, 10.15, etc) you are working on?

**Comment by yeohelp** [comment]
Hi, I am working on OSX 10.12

**Comment by bethac07** [comment]
I'm sorry, we don't have any pre-built version of CellProfiler 4 that will work on 10.12; as it says on the downloads page, CellProfiler 4 is 10.14+ only.  3.1.5 should definitely work, and I believe 3.1.8 and 3.1.9 will as well; you also should be able to install [from source](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29) if your computer can support python 3.8.

Sorry, I wish mac builds made it easier for us to support more mac versions at a time, but they sadly don't!
