### ISSUE TITLE
CellProfiler Python: Javabridge problem

### ISSUE THREAD

**Issue by hanzh98** [CellProfiler/CellProfiler#4379]
I am trying to make cellprofiler python version work on jupyter notebook. I could find cellprofiler example for notebook
at  (https://github.com/CellProfiler/notebooks/blob/master/cellprofiler_demo.ipynb). It was built on python 2. So I changed into Python3 codes and simplified it by using 1 "DNA" image and a pipeline with 1 module (IdentifyPrimaryObject) for "DNA" label. The pipleline file "newPipe.cppipe" was tested with the image "AS_09125_050116030001_D03f00d0.tif" in desktop Cellprofiler. It works well. 
![screenshot-2](https://user-images.githubusercontent.com/82445620/114711644-2c48e100-9d6a-11eb-82e0-b7d4795202e5.png)

My python version is pasted below:

import cellprofiler_core.image
import cellprofiler_core.measurement
import cellprofiler_core.object
import cellprofiler_core.pipeline
import cellprofiler_core.preferences
import cellprofiler_core.workspace
import skimage.io

def run_pipeline(pipeline_filename, image_dict):
    cellprofiler_core.preferences.set_headless()
    
    # Create and load the pipeline
    pipeline = cellprofiler_core.pipeline.Pipeline()
    pipeline.load(pipeline_filename)
    
    # Create the image set, and add the image data
    image_set_list = cellprofiler_core.image.ImageSetList()
    image_set = image_set_list.get_image_set(0)
    for image_name, input_pixels in image_dict.items():
        image_set.add(image_name, cellprofiler_core.image.Image(input_pixels))
        
    # set object_set
    object_set = cellprofiler_core.object.ObjectSet()

    # set measurements
    measurements = cellprofiler_core.measurement.Measurements()
    measurements.group_index = 1

    # Run the modules
    for module in pipeline.modules():
        workspace = cellprofiler_core.workspace.Workspace(
            image_set=image_set,
            image_set_list=image_set_list,
            measurements=measurements, 
            module=module,
            object_set=object_set, 
            pipeline=pipeline
        )
        
        module.prepare_run(workspace)
        module.run(workspace)
        module.post_run(workspace)
      
    return workspace

# Image & pipeline source.
images = { "DNA": skimage.io.imread("images/AS_09125_050116030001_D03f00d0.tif") }
pipeline_filename = "newPipe.cppipe"

#run
workspace = run_pipeline(pipeline_filename, images)

**Expected behavior**
Error message are pasted below:

AttributeErrorTraceback (most recent call last)
<ipython-input-1-cf08ac6fd797> in <module>
     49 
     50 #run
---> 51 workspace = run_pipeline(pipeline_filename, images)

<ipython-input-1-cf08ac6fd797> in run_pipeline(pipeline_filename, image_dict)
     38         )
     39 
---> 40         module.prepare_run(workspace)
     41         module.run(workspace)
     42         module.post_run(workspace)

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\cellprofiler_core\modules\images.py in prepare_run(self, workspace)
    334                 expression = self.filter.value_text
    335             env = javabridge.get_env()
--> 336             ifcls = javabridge.class_for_name("org.cellprofiler.imageset.ImageFile")
    337             scls = env.find_class("java/lang/String")
    338             iffilter = javabridge.make_instance(

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py in class_for_name(classname, ldr)
   1741     '''
   1742     if ldr == "system":
-> 1743         ldr = static_call('java/lang/ClassLoader', 'getSystemClassLoader',
   1744                           '()Ljava/lang/ClassLoader;')
   1745     return static_call('java/lang/Class', 'forName', 

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py in static_call(class_name, method_name, sig, *args)
    937     '''
    938     env = get_env()
--> 939     fn = make_static_call(class_name, method_name, sig)
    940     args_sig = split_sig(sig[1:sig.find(')')])
    941     ret_sig = sig[sig.find(')')+1:]

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py in make_static_call(class_name, method_name, sig)
    908     '''
    909     env = get_env()
--> 910     klass = env.find_class(class_name)
    911     if klass is None:
    912         jexception = get_env().exception_occurred()

AttributeError: 'NoneType' object has no attribute 'find_class'

So, it seems that the execution was jammed at "javabridge.class_for_name()". I noticed that several others have also reported issues with this function in the past. No resolution seems having been reported. Any work-around?

**Desktop (please complete the following information):**
 - OS: Windows 7 professional
 - CellProfiler Version 4.1.3
 - Python: 3.8.9
 - Installed through "pip install cellprofiler"

**Additional context**
Complete pip list:
argon2-cffi 20.1.0
async-generator 1.10
attrs 20.3.0
backcall 0.2.0
bleach 3.3.0
boto3 1.17.44
botocore 1.20.44
CellProfiler 4.1.3
cellprofiler-core 4.1.3
centrosome 1.2.0
certifi 2020.12.5
cffi 1.14.5
chardet 4.0.0
colorama 0.4.4
cycler 0.10.0
decorator 4.4.2
defusedxml 0.7.1
deprecation 2.1.0
docutils 0.15.2
entrypoints 0.3
future 0.18.2
h5py 2.10.0
idna 2.10
imageio 2.9.0
inflect 5.3.0
ipykernel 5.5.3
ipython 7.22.0
ipython-genutils 0.2.0
ipywidgets 7.6.3
jedi 0.18.0
Jinja2 2.11.3
jmespath 0.10.0
joblib 1.0.1
jsonschema 3.2.0
jupyter 1.0.0
jupyter-client 6.1.12
jupyter-console 6.4.0
jupyter-core 4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets 1.0.0
kiwisolver 1.3.1
mahotas 1.4.11
MarkupSafe 1.1.1
matplotlib 3.1.3
mistune 0.8.4
mysqlclient 1.4.6
nbclient 0.5.3
nbconvert 6.0.7
nbformat 5.1.3
nest-asyncio 1.5.1
networkx 2.5.1
notebook 6.3.0
numpy 1.20.2
packaging 20.9
pandas 1.2.3
pandocfilters 1.4.3
parso 0.8.2
pickleshare 0.7.5
Pillow 8.2.0
pip 21.0.1
prokaryote 2.4.2
prometheus-client 0.10.0
prompt-toolkit 3.0.18
psutil 5.8.0
pycparser 2.20
Pygments 2.8.1
pyparsing 2.4.7
pyrsistent 0.17.3
python-bioformats 4.0.4
python-dateutil 2.8.1
python-javabridge 4.0.3
pytz 2021.1
PyWavelets 1.1.1
pywin32 300
pywinpty 0.5.7
pyzmq 18.0.1
qtconsole 5.0.3
QtPy 1.9.0
requests 2.25.1
s3transfer 0.3.6
scikit-image 0.18.1
scikit-learn 0.24.1
scipy 1.6.2
Send2Trash 1.5.0
sentry-sdk 0.18.0
setuptools 49.2.1
six 1.15.0
terminado 0.9.4
testpath 0.4.4
threadpoolctl 2.1.0
tifffile 2021.3.31
tornado 6.1
traitlets 5.0.5
urllib3 1.26.4
wcwidth 0.2.5
webencodings 0.5.1
widgetsnbextension 3.5.1
wxPython 4.1.0

**Comment by DavidStirling** [comment]
Having taken a look at this, it appears that the problem is that it's expecting a java vm but javabridge hasn't created one. Could you try adding the following code before running the pipeline?
```
import javabridge
javabridge.start_vm()
```

It might be worth testing this alone in an interpreter first.

**Comment by hanzh98** [comment]
Hi, David. Thanks for looking into this issue. I added your javabridge command and got a different error message this time. It  probably suggests the solution works. The error message is pasted at the end of my reply.
While searching for solutions, I did find a way to get around this problem. Cellprofiler works well in headless mode using command lines in windows CMD prompt. So I just output to command lines using subprocess.run function from subprocess package in python. This works excellently, because pipelines could be well tested beforehand using GUI mode. It saves potential problems with direct calling individual cellprofiler functions from different modules.    

Error code from direct calling method:

JavaExceptionTraceback (most recent call last)
<ipython-input-2-850cef4bc733> in <module>
     52 
     53 #run
---> 54 workspace = run_pipeline(pipeline_filename, images)

<ipython-input-2-850cef4bc733> in run_pipeline(pipeline_filename, image_dict)
     41         )
     42 
---> 43         module.prepare_run(workspace)
     44         module.run(workspace)
     45         module.post_run(workspace)

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\cellprofiler_core\modules\images.py in prepare_run(self, workspace)
    334                 expression = self.filter.value_text
    335             env = javabridge.get_env()
--> 336             ifcls = javabridge.class_for_name("org.cellprofiler.imageset.ImageFile")
    337             scls = env.find_class("java/lang/String")
    338             iffilter = javabridge.make_instance(

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py in class_for_name(classname, ldr)
   1743         ldr = static_call('java/lang/ClassLoader', 'getSystemClassLoader',
   1744                           '()Ljava/lang/ClassLoader;')
-> 1745     return static_call('java/lang/Class', 'forName', 
   1746                        '(Ljava/lang/String;ZLjava/lang/ClassLoader;)'
   1747                        'Ljava/lang/Class;',

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py in static_call(class_name, method_name, sig, *args)
    941     ret_sig = sig[sig.find(')')+1:]
    942     nice_args = get_nice_args(args, args_sig)
--> 943     result = fn(*nice_args)
    944     return get_nice_result(result, ret_sig)
    945 

c:\users\fermispm\appdata\local\programs\python\python38\lib\site-packages\javabridge\jutil.py in fn(*args)
    921         jexception = env.exception_occurred()
    922         if jexception is not None:
--> 923             raise JavaException(jexception)
    924         return result
    925     return fn

JavaException: org.cellprofiler.imageset.ImageFile
