### ISSUE TITLE
Can't Read Image in FlagImage Module

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4382]
**Describe the bug**
I'm measuring colocalization between a list of images (of similar names, e.g. DAPI_round1, DAPI_round2, DAPI_round3) and want to create a flag if their correlation is low. However, in the FlagImage module, the drop down bar for Image isn't wide enough to show my full image names so I can't actually tell which comparison I'm selecting.

Can we make it expand to actually fit the text?

<img width="823" alt="Screen Shot 2021-04-21 at 1 23 20 PM" src="https://user-images.githubusercontent.com/54687786/115617092-d31b0900-a2a5-11eb-86f1-42bcf183254c.png">

**Desktop (please complete the following information):**
 -  OSX 15.7
 - CellProfiler Version 4.1.3
 - Source

**Comment by bethac07** [comment]
Hopefully yes, but until we do (and in case we can't because sometimes wx is just a butt)- my recommendation for a workaround would be to just edit that value in the text of the pipeline file after.  Super unsatisfactory, I know, but it's what I have that will work today.

**Comment by ErinWeisbart** [comment]
(In case this helps anyone else in the meantime, if you hover over the truncated text a tooltip will show with the full length of the text)

**Comment by DavidStirling** [comment]
Looked into this, it's not a problem on Windows. The sizer should expand automatically to fit the longest element, so I expect there's something going wrong on MacOS specifically. I'd suggest that someone with a Mac check that this code is generating the correct width hint : https://github.com/CellProfiler/CellProfiler/blob/e41afd2debdf507bfaf23b344d094ee6f6f2eccd/cellprofiler/gui/module_view/_module_view.py#L1881-L1887
