### ISSUE TITLE
HELP!!!---“identifyprimaryobjects”  After run () ends, how to display the results of processing separately?（获得identifyprimaryobjects模块中run()函数结束后的两张结果图）

### ISSUE THREAD

**Issue by scut-pzy** [CellProfiler/CellProfiler#4386]
These two pictures are (0,1) and (1,0) on the canvas. I want to get the results displayed in the app, but actually I can't find the two pictures, so I really need help!!

这两张图为画布上（0，1） 与（1，0）的图片，我想获取app里显示的结果，但实际上我找不到那两张图在哪里，非常需要帮助！！！

**Comment by bethac07** [comment]
Are you asking how to save out the module display windows? 

Optionally- if you want each image individually on its own, you can open them one at a time by saying "Open in a new window"

![image](https://user-images.githubusercontent.com/6721515/116555501-7a152b80-a8ca-11eb-9096-fcbc2848792a.png)

Once you have the window and view that you want, you can use the save icon

![image](https://user-images.githubusercontent.com/6721515/116555598-94e7a000-a8ca-11eb-821e-3399ad5d707f.png)

Hope that helps!

**Comment by bethac07** [comment]
Hi,

Closing this here since this isn't a bug, as tagged; if you want help issues that aren't bugs, our team and others are happy to help at forum.image.sc.  Thanks for your understanding!
