### ISSUE TITLE
HELP！how to set modul to get  count of this cell picture ?

### ISSUE THREAD

**Issue by scut-pzy** [CellProfiler/CellProfiler#4389]
![1](https://user-images.githubusercontent.com/53106215/116774517-a29a5280-aa8f-11eb-9881-ece7cf7084ff.jpg)

**Comment by bethac07** [comment]
Hi,

Closing this here since this isn't a bug, as tagged; if you want help with pipelines, our team and others are happy to help at forum.image.sc.  Thanks for your understanding!
