### ISSUE TITLE
Measurements calculated by centrosome vs skimage inconsistent with skipped values.

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4403]
H/T [the forum](https://forum.image.sc/t/cellprofiler-exporttospreadsheet-module-generates-inconsistent-object-measurements/53789)

>For one particular mask in my dataset, there are 2 objects with NaN features at the end in the exported csv. The mask image contains 136 objects with pixel labels 1, 2, …, 138 (except 98 and 108). It seems cellprofiler created 2 “empty” objects in their place. Moreover, the Location_Center_X and Location_Center_Y features for ObjectNumber corresponding to the missing pixel values (98 and 108) are NaN and the “empty” objects seem to have these values instead!

My reply

>So it looks to me like what’s happening is that for everything but the ObjectNumber, FeretDiameters, Radius, and Location_Centers, your objects are being renumbered to 1-136 (instead of 1-138), but due to some legacy code, those are not. So you end up with those columns being 0s or NaNs in the rows for the labels that are missing, and then all the measurements in those categories after are off by one-per-missing-label-so-far after. So those columns for rows 99-107 are off by 1, and 108-end are off by 2, and the final two rows of measurements are there at the end. I’ve checked that this is still also an issue in 4.1.3.
CellProfiler used to allow you to have object labels missing, but it now no longer does, which is why we didn’t catch this before. 

![image](https://user-images.githubusercontent.com/6721515/121530207-30405a80-c9cb-11eb-942a-1b44876f9506.png)

Basically, if labels are missing, skimage-provided measurements just renumber, and centrosome -provided measurements [I think due to stuff like this where the indices are being fed in](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/measureobjectsizeshape.py#L655-L667) are skipping the missing measurements and associating with the skip-numbers.

We've mostly moved away from having non-contiguous object numbers, this was a case of someone inputting a label matrix as objects, so I can imagine attacking this either from the "renumber input label matrices so no object numbers are missing" or the "stop making centrosome behave this way" direction (or both).

---
=

**Desktop (please complete the following information):**
-4.0.7 (OS not clear), 4.1.3 Mac Built.

**Comment by DavidStirling** [comment]
> skimage-provided measurements just renumber

This may actually be something we could resolve on our end. RegionProps won't generate measurements for missing labels, but the resulting table still has each measurement associated with it's proper label. In rewriting the SizeShape module I didn't realise that centrosome handled things so differently.

I think it's 'safer' to design CellProfiler in such a way that missing labels don't cause problems, rather than needing to constantly relabel images whenever an object is removed. I'm not really fond of Centrosome's approach of generating measurement arrays from 0-max, rather than calling something like `np.unique`.

**Comment by bethac07** [comment]
Yeah, i think we should use .unique in centrosome.
