### ISSUE TITLE
SaveCroppedObjects unable to save images in folders using metadata.

### ISSUE THREAD

**Issue by alexanderchang1** [CellProfiler/CellProfiler#4408]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce, including an attached/linked image set and pipeline, may be closed without investigation. You may delete this section before posting your issue below.

OS: Windows 10
Version: 4.1.3

---

**Describe the bug**

I'm trying to save the cropped images from a two color image. I have a set of images with blue DAPI signal, and another set with a green Cytoplasm signal. These images are paired using NamesAndTypes, and then objects are identified with IdentifyPrimaryObjects and IdentifySecondaryObjects. When I try to save these objects as cropped images using SaveCroppedObjects, the resulting subfolder is always labeled "None" even though I've specified for it to pull the filename. Please see the below link for further details and attachments.

https://forum.image.sc/t/save-croppedobjects-with-unique-names-throughout-several-images/40175/9

**To Reproduce**
1. Import pipeline
2. Add two example images to the file list.
3. Pair the two images with _CYT and _DAPI suffix.
4. Extract any metadata of choice.
5. Select said metadata as the name of the subfolder for SaveCroppedObjects output.
6. Run pipeline and see how the resulting images are not correctly named after meta data.

https://forum.image.sc/t/save-croppedobjects-with-unique-names-throughout-several-images/40175/9

**Expected behavior**
Each subfolder should be named after the original image used to isolate objects. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (See above link)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX 14.6] Windows 10 Home 20H2
 - CellProfiler Version [e.g. 2.2, 3.1.9] 4.1.3
 - Downloaded from the website or installed from source? From the website. 
 - If the latter, how (cloned, installed from pypi, etc)? Stable program download. 

**Additional context**

**Comment by pearlryder** [comment]
I investigated this problem and I don't think that it's a bug, but instead related to the metadata tags being different for the images within the image set. Please see: https://forum.image.sc/t/save-croppedobjects-with-unique-names-throughout-several-images/40175/10?u=pearl-ryder
