### ISSUE TITLE
Update the cellprofiler-4.yaml installation instructions for Conda

### ISSUE THREAD

**Issue by max1c** [CellProfiler/CellProfiler#4412]
**Is your feature request related to a problem? Please describe.**
The package list is incomplete and does not work for the conda installation. https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation 

**Describe the solution you'd like**
Here is an updated list that I just made and used to install the latest cellprofiler-4.1.3:

```
channels:
- conda-forge
- anaconda
- bioconda
- defaults

dependencies:
- python=3.8
- pip
- numpy
- matplotlib
- pandas
- mysqlclient
- openjdk
- scikit-learn
- mahotas
- gtk2
- Jinja2=3.0.1
- inflect=5.3.0
- wxpython=4.1.0
- mysqlclient=1.4.4
- sentry-sdk=0.18.0
- pip:
    - cellprofiler==4.1.3
```

**Additional context**
I used cellprofiler==4.1.3 because I cannot guarantee the list of dependencies will work for a newer version. But it definitely works for the current 4.1.3.

**Comment by bethac07** [comment]
Great, thanks, I've updated our wiki!
