### ISSUE TITLE
Fix --get-batch-commands --images-per-batch (and document it)

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4413]
H/T [the forum](https://forum.image.sc/t/issue-with-batchdata-h5-in-cellprofiler/53982)

**Describe the bug**
Apparently in #2725 @VolkerH  added an option to --get-batch-commands to allow you to pass in an `--images-per-batch` flag to get `-f -l` CellProfiler commands easily for a given batch file. It doesn't look like it was ever added to our documentation, and in 3.1.8 and 4.1.3 it does not appear to work. It's a good idea to have this, we should fix it and make sure it's documented such that people know that it exist!

>The case where output is being produced, it’s not actually putting out batches of 5, it’s putting out batches of 24, which corresponds to your pipeline grouping. When there is no pipeline grouping, it puts out nothing. 

**To Reproduce**
Grab the batch files from the forum post and run the command below with appropriate subsititutions.

`${CELLPROFILER_INSTALLATION} --get-batch-commands path/to/BatchData.h5 --images-per-batch=5`

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX 14.6] OSX 10.15.7
 - CellProfiler Version 3.1.8/4.1.3 built

**Comment by VolkerH** [comment]
just tagging @tischi as he originally flagged this.
