### ISSUE TITLE
OS X 10.15 NamesAndTypes Error

### ISSUE THREAD

**Issue by mcquillr** [CellProfiler/CellProfiler#4414]
I get the following error when trying to update the list generated by NamesAndTypes

"Encountered unrecoverable error in NamesAndTypes during startup:
No applicable predicate for token file"

**Comment by DavidStirling** [comment]
Would you be able to upload the pipeline which caused this?

**Comment by mcquillr** [comment]
Absolutely! I simplified this one to troubleshoot and for some reason I can't seem to save any edits to the first rule.


[Illum_Pipeline_Felix.cpproj.zip](https://github.com/CellProfiler/CellProfiler/files/6677238/Illum_Pipeline_Felix.cpproj.zip)

**Comment by DavidStirling** [comment]
Thanks for uploading that, it seems that there are some very odd filters being stored in the NamesAndTypes module. Would you be able to show a screenshot of how it looks on your end, and outline exactly what you're trying to do with it? It's not clear what the "Ignore" image is supposed to be and it seems to have some hidden rules that aren't displaying properly on my end.
