### ISSUE TITLE
Outdated examples of pipelines

### ISSUE THREAD

**Issue by vkhodygo** [CellProfiler/CellProfiler#4420]
**Describe the bug**
One of the CellProfiler examples doesn't work (or all of them?) since  the pipeline is outdated.

**To Reproduce**
1. Go to https://cellprofiler.org/examples
2. Download the "Fruit Fly cells" example
3. Try to import the pipeline
4. See error both in the terminal and as pop-up window. 

**Expected behavior**
According to the "Examples" page, all these pipelines should work with CellProfiler 4.0 (and later).

**Desktop (please complete the following information):**
 - OS: Linux
 - CellProfiler Version 4.2.0
 - Built from scratch
 - cloned, patched to work with python 3.9

**Comment by bethac07** [comment]
Hi,

I was getting an issue with that particular pipeline, but it should be patched in #4421 ; can you confirm whether you were having issues with just that pipeline or others, and if the patch here fixed your issue?

Otherwise, knowing which pipeline(s) are giving you errors and the stack traces of the errors would really be necessary for us to trace these down- i should say that we don't yet officially support python3.9, so you may encounter some issues running there as opposed to 3.8.  

Thanks in advance for your feedback!

**Comment by vkhodygo** [comment]
Hi, @bethac07 
Sorry, it took me some time to get this testing done. My results so far for all examples aside from worms:
### Ubuntu 20.04 VM, CellProfiler/core built from git, GUI, Python 3.8
Some pipelines throw an error while importing them.

- Comet assay
- Fruit Fly cells
- Imaging Flow Cytometry 

### Archlinux, CellProfiler/core built from git & patched to work with Python 3.9, GUI, Python 3.9
Same pipelines fail to get imported. Used patches can be found in the attachment.

### Archlinux, CellProfiler/core built from git & patched to work with Python 3.9, headless, Python 3.9
No noticeable issues whatsoever, all logs with `stderr` & `stdout` alongside with the test script and directory structure (for reproducibility reasons) are attached below. 

## Attachment
[core_python39.patch](https://github.com/CellProfiler/CellProfiler/files/6841169/core_python39.txt)
[cellprofiler_python39.patch](https://github.com/CellProfiler/CellProfiler/files/6841172/cellprofiler_python39.txt)


[directory_structure.txt](https://github.com/CellProfiler/CellProfiler/files/6841166/directory_structure.txt)
[test_run.sh](https://github.com/CellProfiler/CellProfiler/files/6841167/test_run.txt)

[ExampleColocalization.log](https://github.com/CellProfiler/CellProfiler/files/6841148/ExampleColocalization.log)
[ExampleCometAssay.log](https://github.com/CellProfiler/CellProfiler/files/6841149/ExampleCometAssay.log)
[ExampleFly.log](https://github.com/CellProfiler/CellProfiler/files/6841150/ExampleFly.log)
[ExampleHuman.log](https://github.com/CellProfiler/CellProfiler/files/6841151/ExampleHuman.log)
[ExampleIlluminationCorrection_Example1_AllMethod.log](https://github.com/CellProfiler/CellProfiler/files/6841152/ExampleIlluminationCorrection_Example1_AllMethod.log)
[ExampleIlluminationCorrection_Example1_EachMethod.log](https://github.com/CellProfiler/CellProfiler/files/6841153/ExampleIlluminationCorrection_Example1_EachMethod.log)
[ExampleIlluminationCorrection_Example2.log](https://github.com/CellProfiler/CellProfiler/files/6841154/ExampleIlluminationCorrection_Example2.log)
[ExampleIlluminationCorrection_Example3.log](https://github.com/CellProfiler/CellProfiler/files/6841155/ExampleIlluminationCorrection_Example3.log)
[ExampleImagingFlowCytometryObjectsInGrid.log](https://github.com/CellProfiler/CellProfiler/files/6841156/ExampleImagingFlowCytometryObjectsInGrid.log)
[ExampleNeighbors.log](https://github.com/CellProfiler/CellProfiler/files/6841157/ExampleNeighbors.log)
[ExamplePercentPositive.log](https://github.com/CellProfiler/CellProfiler/files/6841158/ExamplePercentPositive.log)
[ExampleSpeckles.log](https://github.com/CellProfiler/CellProfiler/files/6841159/ExampleSpeckles.log)
[ExampleTrackObjects.log](https://github.com/CellProfiler/CellProfiler/files/6841160/ExampleTrackObjects.log)
[ExampleTumor.log](https://github.com/CellProfiler/CellProfiler/files/6841162/ExampleTumor.log)
[ExampleWoundHealing.log](https://github.com/CellProfiler/CellProfiler/files/6841163/ExampleWoundHealing.log)
[ExampleYeastColonies.log](https://github.com/CellProfiler/CellProfiler/files/6841164/ExampleYeastColonies.log)
[ExampleYeastPatches.log](https://github.com/CellProfiler/CellProfiler/files/6841165/ExampleYeastPatches.log)
