### ISSUE TITLE
PyPI package update

### ISSUE THREAD

**Issue by vkhodygo** [CellProfiler/CellProfiler#4422]
**Desktop (please complete the following information):**
 - OS: Linux (other should be affected as well)
 - CellProfiler Version 4.2.0
 - Downloaded
 - PyPI

**Describe the issue**
The latest `cellprofiler-core` package version is `4.2.0` whereas the `cellprofiler` package itself is `4.1.3`.

**Comment by bethac07** [comment]
This is fixed now, sorry for the delay!

**Comment by vkhodygo** [comment]
No problem, thanks! Less code t build from scratch now.
