### ISSUE TITLE
Matplotlib version requirement

### ISSUE THREAD

**Issue by vkhodygo** [CellProfiler/CellProfiler#4432]
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 VM
 - CellProfiler Version 4.2.0
 - source
 - pypi

**Describe the issue**
When I follow the installation instructions I get an error saying that my `matplotlib` version is not correct.
I have to install `matplotlib==3.1.3` after that manually. 

**Error messages**
Generic pip error message saying that my version is incompatible. 

**Additional context**
Both `cellprofiler` and `centrosome` have their `matplotlib`versions specified. On a side note here, there is no need to have `matplotlib` in the `cellprofiler` requirements list since `centrosome` is a dependency of `cellprofiler` and already requires `matplotlib` installation. That would reduce maintenance work a bit.

**Comment by iosonofabio** [comment]
Also, I have it working now with `matplotlib 3.4.3` and it works just fine

**Comment by gnodar01** [comment]
Closing as completed (hopefully)

> On a side note here, there is no need to have matplotlib in the cellprofiler requirements list since centrosome is a dependency of cellprofiler and already requires matplotlib installation.

We do, since we want to have the ability to do version constraining differently between the two.
