### ISSUE TITLE
Image alignment for iterative imaging techniques

### ISSUE THREAD

**Issue by paulflang** [CellProfiler/CellProfiler#4460]
**Is your feature request related to a problem? Please describe.**
We are performing iterative multiplexed imaging experiments using three channels. One channel always stains the same target in each iteration. Unfortunately, the microscope slightly shifts after each iteration, so we have to realign the images between iterations, using the signal from the constant channel.

**Describe the solution you'd like**
All images shall be aligned based on the constant channel and the first iteration.

**Describe alternatives you've considered**
Manually clicking on the same ~25 points in all iterations and calculate transformation matrices based on that.

**Additional context**
Could be that this issue rather refers to the CellProfiler-plugins or CellProfiler-Analyst repos.

**Comment by bethac07** [comment]
Hi,

This is definitely possible in CellProfiler as it exists, by using the "Align" module, which allows you to align all the channels of imaging cycle 2 to imaging cycle 1 based on a constant channel. Linked below is a published pipeline that does just that!

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7877457/#ext1

**Comment by paulflang** [comment]
Thanks a lot for pointing this out. I was not aware of it. I'll give it a try and close this issue.
