### ISSUE TITLE
Error: value exceeds value of control 25

### ISSUE THREAD

**Issue by schroeme** [CellProfiler/CellProfiler#4480]
Hi, I am running a pipeline on 3D images in CellProfiler 4.1.3 on Windows 10, which includes Threshold and Watershed modules. On the second image set in the Watershed module, I get the following error: "Error: value exceeds value of control 25", and am prompted to select "Continue Processing" or "Cancel".  Screenshot of the log is attached. If I select continue, the error pops up again. What does this error mean?

<img width="544" alt="Screen Shot 2021-11-04 at 10 29 23 AM" src="https://user-images.githubusercontent.com/65419570/140332528-c7df237f-9932-4845-94b9-df9175d96fed.png">

**Comment by bethac07** [comment]
This seems to be reporting cases when the slider value for the "Plane" slider is beyond what it is supposed to get to; the only thing I've found that reliably generates this is in post-4.2.1 now that we can use Resize/ResizeObjects to adjust the number of Z planes when it's been resized beyond 0.5 and then executed at least twice - the middle of the un-resized stack is now too high a Z number to exist in the post-resize, which is the last thing that set the plane.
