### ISSUE TITLE
Use cellprofiler as a python package

### ISSUE THREAD

**Issue by shihangjs** [CellProfiler/CellProfiler#4481]
Hi When I want to reproduce the example, I get an error:
```
ERROR:root:Failed to display results for module Crop
Traceback (most recent call last):
  File "E:\python-3.8.10-amd64\lib\site-packages\cellprofiler_core-4.2.1-py3.8.egg\cellprofiler_core\pipeline\_pipeline.py", line 1011, in run_with_yield
    fig = workspace.get_module_figure(module, image_number)
AttributeError: 'Workspace' object has no attribute 'get_module_figure'
```
Can someone tell me how to deal with it, thank you very much

**Comment by j-renggli** [comment]
I'm having the [same problem](https://forum.image.sc/t/failed-to-display-results-for-module-crop/59753/3) (Windows too). I followed all the steps from https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-as-a-Python-package but when reaching the `pipeline.run()` line, I face that issue.

I notice that `cellprofiler_core/pipeline/_pipeline.py` creates a `Workspace` (line 951) imported as: `from ..workspace import Workspace`. However this class in `cellprofiler_core/workspace/_workspace.py` doesn't have any `get_module_figure()` function. Only when using the derived class in `cellprofiler/gui/_workspace_model.py` does this function exist.

Is there anything I can do?

**Comment by shihangjs** [comment]
Hello, I did not solve the previous problem, but if you use a single
module, it can run successfully[image: 360截图1828050763105108.jpg]

Julien Renggli ***@***.***> 于2021年12月2日周四 23:00写道：

**Comment by bethac07** [comment]
There was a missing instruction in the wiki which has now been added; at any point after importing the preferences library and before running the pipeline itself, you need to run the line below to tell CellProfiler to not try to run the GUI. Apologies for the oversight!

cellprofiler_core.preferences.set_headless()
