### ISSUE TITLE
Add the angle correspondences to the MeasureTexture documentation 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4490]
Every year or so I have to look this up, which means it probably is needed there somewhere - in fact, I was pretty sure we HAD done it but evidently we (*cough* **I** *cough cough*) forgot.

_00 = horizontal (0 degrees)
_01 = diagonal (45 degrees) - down
_02 = vertical (90 degrees)
_03 = anti-diagonal (135 degrees) - down

**Comment by bethac07** [comment]
(I'm guessing we never did this because we didn't want to write out the 3D ones, but for those we can either give [the correspondences](https://github.com/luispedro/mahotas/blob/master/mahotas/features/texture.py#L383-L396) (below) or finally just make ourselves describe them)

```
_2d_deltas= [
    (0,1),
    (1,1),
    (1,0),
    (1,-1)]

_3d_deltas = [
    (1, 0, 0),
    (1, 1, 0),
    (0, 1, 0),
    (1,-1, 0),
    (0, 0, 1),
    (1, 0, 1),
    (0, 1, 1),
    (1, 1, 1),
    (1,-1, 1),
    (1, 0,-1),
    (0, 1,-1),
    (1, 1,-1),
    (1,-1,-1) ]
```

**Comment by rsenft1** [comment]
For the 2D deltas, if the description order matches the vector order, isn't (0,1) 90 degrees (so vertical), and (1,0) horizontal? 

_00 = vertical (90 degrees)
_01 = diagonal (45 degrees)
_02 = horizontal (0 degrees)
_03 = anti-diagonal (135 degrees)

Or is there something I'm missing about this?

And as far as the 3D deltas maybe we could describe them like this: 

(1, 0, 0) -> horizontal, along the x axis
(0, 1, 0) -> vertical, along y axis
(0, 0, 1) -> along z axis

For the rest, sometimes a picture is easier. Here are the 3D vectors color-coded to help see symmetry across the x axis. The vectors that lie along each axis are colored yellow. 
![image](https://user-images.githubusercontent.com/28116530/153030732-b1bf7243-67fb-4299-8f9a-b0b0be1981f6.png)
And from a slightly different angle: 
![image](https://user-images.githubusercontent.com/28116530/153031397-b995758f-6303-4ff1-ad3a-318f3ff87f16.png)

**Comment by bethac07** [comment]
From the [documentation in Mahotas](https://github.com/luispedro/mahotas/blob/master/mahotas/features/texture.py#L412-L414) - 
```
    direction : integer
        Direction as index into (horizontal [default], diagonal
        [nw-se], vertical, diagonal [ne-sw])
```

**Comment by rsenft1** [comment]
Yep I see that now! Why is it y,x rather than x,y? I thought x,y was the more standard convention

**Comment by bethac07** [comment]
Not in arrays- 

```
>>> import numpy
>>> a = numpy.array(range(6))
>>> a
array([0, 1, 2, 3, 4, 5])
>>> a.reshape([3,2])
array([[0, 1],
       [2, 3],
       [4, 5]])
```

**Comment by bethac07** [comment]
https://github.com/CellProfiler/CellProfiler/issues/2562#issuecomment-273828183

**Comment by rsenft1** [comment]
Wow this goes back to CRTs? 🤯  That makes sense though. Would it help to include a drawing like the one in my comment in the documentation for the 3D correspondences? I can switch the x and y axes labels and move things around a little:
![image](https://user-images.githubusercontent.com/28116530/153055241-236410b0-0421-4124-8177-5e919ec8dd44.png)

**Comment by bethac07** [comment]
I think it might be z, y, x, not y, x, z, but should check

**Comment by bethac07** [comment]
(as to how to check, I would think a z stack of identical images should work, because in theory the Z should be quite distinguishable there)

**Comment by rsenft1** [comment]
[This](https://github.com/luispedro/mahotas/blob/08cc4aa0cbd5dbd4c37580d52b822810c03b2c69/mahotas/features/texture.py#L450) is in the code below where the deltas are defined: `y, x, z = tuple(distance * i for i in _3d_deltas[direction])`

**Comment by bethac07** [comment]
Ah, nice catch!

**Comment by bethac07** [comment]
(But if positive is down in y, it probably also is in z, for your diagram)

**Comment by rsenft1** [comment]
Hmm this could just be the website I'm using, but flipping things around so everything points down makes it hard to understand what's happening: 
![image](https://user-images.githubusercontent.com/28116530/153059228-fbdbfd99-4deb-416d-951d-bee6dbf4aebd.png)

This graph really wants one of the axes to point up. Not sure if a better graphic exists somewhere or if it works to explain that +1 to x moves right, +1 to y moves down, +1 to z moves down.

**Comment by rsenft1** [comment]
Nevermind, it is doable with some flipping of coordinates and changing the labels: 
![image](https://user-images.githubusercontent.com/28116530/153064566-0ebab6a2-e2e0-4b30-a74b-07f9b1c33108.png)

**Comment by rsenft1** [comment]
I made a PR that should resolve this - #4504
