### ISSUE TITLE
CellProfiler v4.2.1 seems to install but will not open/run on macOS 12.0.1

### ISSUE THREAD

**Issue by mcprocario** [CellProfiler/CellProfiler#4493]
Hello, 
This is my first attempt to download and run CellProfiler. I was able to download the macOS zip file from [https://github.com/CellProfiler/CellProfiler/releases](url) and perhaps install it on my computer. I have not, however, been able to get it to open on my computer. The app is in my applications folder. I placed it there using both methods suggested for people having issues with Opening CellProfiler on Mac OS 10.15.7 [https://github.com/CellProfiler/CellProfiler/wiki/Opening-CellProfiler-on-Mac-OS-10.15.7](url), including renaming it "CellProfiler2". Now, everytime I try to open it I get the scrolling rainbow wheel of death and the program is unresponsive, requiring me to force quit. Please help!

ETA:
It will open using command line either.

**Comment by sandhya212** [comment]
I have faced the same issue: unable to open CellProfiler on macOS 10.15.7. I have followed the steps mentioned here: https://github.com/CellProfiler/CellProfiler/wiki/Opening-CellProfiler-on-Mac-OS-10.15.7 and renaming to CellProfiler2 did not work either. Watching this thread for updates. Thanks!

**Comment by MJ811** [comment]
I tried the suggested workarounds at 
https://github.com/CellProfiler/CellProfiler/wiki/Opening-CellProfiler-on-Mac-OS-10.15.7
Mac OS 10.15.7 
However, the system will not allow us to extract directly to the application folder and I tried the rename method and received the same error: 
“CellProfiler 2” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Comment by marivinc** [comment]
I also tried the suggested workarounds at https://github.com/CellProfiler/CellProfiler/wiki/Opening-CellProfiler-on-Mac-OS-10.15.7 and successfully installed Cell Profiler (now named CellProfiler2). I also had this issue, in which it said apple cannot check it for malicious software so the software cannot be opened. 

I can open CellProfiler on MacOS 12.0.1 by going to the Applications folder, right clicking on the CellProfiler2 icon, and then pressing "Open". I then get a window warning that apple cannot check for malicious software, but at this point the option to open anyway should also appear, and the software opens.

**Comment by sandhya212** [comment]
Thank you for responding! I have checked this again but hit the same issue. Most of the Mac OS versions having trouble with CellProfiler are above MacOS 10.x.x. I wonder if the CellProfiler team has been able to run the code on back versions of MacOS. Then this error we are reporting must be OS-related and _could_ be addressed within the CP code? Thinking aloud here.

**Comment by alejannb** [comment]
I also had the same message window in my macOS 10.15.7 saying:  apple cannot check it for malicious software so the software cannot be opened. I downloaded the release 4.2.1 from https://github.com/CellProfiler/CellProfiler/releases directly into my applications folder. By just double clicking the same issue occurred. It only worked through right clicking and then open.
