### ISSUE TITLE
GrayToColor bug

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4494]
**Describe the bug**
```
Failed to run module GrayToColor
Traceback (most recent call last):
  File "/Users/eweisbar/Desktop/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 3390, in do_step
    self.__pipeline.run_module(module, workspace_model)
  File "/Users/eweisbar/Desktop/github/core/cellprofiler_core/pipeline/_pipeline.py", line 1298, in run_module
    module.run(workspace)
  File "/Users/eweisbar/Desktop/github/CellProfiler/cellprofiler/modules/graytocolor.py", line 594, in run
    rgb_image = Image(rgb_pixel_data, parent_image=parent_image, channelstack=channelstack)
TypeError: __init__() got an unexpected keyword argument 'channelstack'
```
**To Reproduce**
<img width="634" alt="Screen Shot 2022-01-25 at 2 45 35 PM" src="https://user-images.githubusercontent.com/54687786/151072428-594d303c-e1fd-4090-be28-c61f322b63fc.png">

**Desktop:**
OS 11.6.2
CP 4.2.1, source

**Comment by ErinWeisbart** [comment]
Same problem if I try to use CMYK or Composite or put different images into different colors.

**Comment by bethac07** [comment]
Can you make sure your `core` is pulled to master?

**Comment by ErinWeisbart** [comment]
Man, I could have sworn that I had a fresh pull on `core` !
Apparently not. Sorry for the bother.

**Comment by bethac07** [comment]
No bother, good documentation of how to fix it for the future :)
