### ISSUE TITLE
Flipped dimensions when saving multi-channel images

### ISSUE THREAD

**Issue by nilseling** [CellProfiler/CellProfiler#4495]
**Describe the bug**
I noticed an issue when saving multi-channel images: after reading in 5 channel `.tiff` images (60,60,5 - x,y,c) and saving them again using the `SaveImages` module, the dimensions seem flipped (5,60,60 - x,y,c as observed using FIJI). 

**To Reproduce**
1. Access the example images [here](https://github.com/BodenmillerGroup/TestData/tree/main/datasets/210308_ImcTestData/analysis/tiffs)
2. Load them into CellProfiler 4.2.1 and filter the images:

<img width="1440" alt="Screenshot 2022-01-27 at 10 24 26" src="https://user-images.githubusercontent.com/11314064/151345362-51dfec7c-4a6b-4260-9bce-5eedbb52d596.png">

3. Set the NamesAndTypes

<img width="1440" alt="Screenshot 2022-01-27 at 10 24 40" src="https://user-images.githubusercontent.com/11314064/151345494-ab0067e9-9c92-471c-a5fa-86314de8dcbc.png">

4. Add the `SaveImages` module to write out 16-bit images:

<img width="1440" alt="Screenshot 2022-01-27 at 10 24 51" src="https://user-images.githubusercontent.com/11314064/151345572-8d1976ff-4ccc-4431-ab71-d230e06fc710.png">

**Expected behavior**
I expect the files that are written out to be identical to the input files. 

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - CellProfiler Version: 4.2.1
 - Downloaded from the website or installed from source? Downloaded [here](https://cellprofiler.org/releases)

Thanks for your help! And please let me know if this issue is duplicated or if I missed something in the docs.
Best,

Nils

**Comment by bethac07** [comment]
Hi Nils, 

I can verify in 4.2.0 and 4.2.1 on OSX; does not happen in 4.1.3. 

This means it's coming from #4406  - skimage only supports saving gray, RGB, or RGBA images, so anything with more channels than that needs to be transposed, and it wasn't happening gracefully for several internal cases (#4401), leading to that PR; I confess I didn't consider the use case of re-saving out a >3 channel image that was not itself manipulated inside CellProfiler but came in that way.  We'll want to figure if the most elegant thing is to use the property we added in #4406 (it's possible that might allow us to avoid the C-to-Z issues in #4032 ) on import of multichannel images OR to just semi-revert 4406 with an OR for handling >5 channel images, but we'll take a look. 

Until we can get a new release out, workarounds would be dropping back to 4.1.3  OR splitting and re-merging that image with ColorToGray then GrayToColor, which I've confirmed in my hands fixes things. 

Thanks for letting us know and apologies for the inconvenience!

**Comment by nilseling** [comment]
Hi @bethac07 

thanks for looking into this! Indeed, CP v4.1.3 writes out multi-channel images with the correct dimensions. However, when reading in the written out set of images into a second pipeline and saving them again via `SaveImages`, only the first 3 channels are saved as RGB. Happy to open a second issue if this should be handled separately.

**Comment by bethac07** [comment]
Hi Nils,

Yeah, a separate issue with some more detail and a pipeline to reproduce would be great, thanks!

**Comment by nilseling** [comment]
Thanks! I have opened a new issue here: #4496
