### ISSUE TITLE
Multi-channel images generated by CP are written as RGB

### ISSUE THREAD

**Issue by nilseling** [CellProfiler/CellProfiler#4496]
**Describe the bug**
I used CellProfiler v4.1.3 to read in multi-channel images (5 channels, 16-bit) available [here](https://github.com/BodenmillerGroup/TestData/tree/main/datasets/210308_ImcTestData/analysis/tiffs). In the first pipeline I read in the images and directly save them as 16-bit .tiff files using the `SaveImages` module. In the second pipeline I do the same but now reading in the images that were previously written out by the first pipeline and saving them again using the `SaveImages` module. At this point only the first three channels are saved as 16-bit RGB image. This is to generate a simple setting in which I have observed the bug.  

**To Reproduce**

1. Access the example images [here](https://github.com/BodenmillerGroup/TestData/tree/main/datasets/210308_ImcTestData/analysis/tiffs)
2. Load them into CellProfiler 4.2.1 and filter the images:

<img width="1440" alt="Screenshot 2022-01-27 at 10 24 26" src="https://user-images.githubusercontent.com/11314064/151345362-51dfec7c-4a6b-4260-9bce-5eedbb52d596.png">

3. Set the NamesAndTypes

<img width="1440" alt="Screenshot 2022-01-27 at 10 24 40" src="https://user-images.githubusercontent.com/11314064/151345494-ab0067e9-9c92-471c-a5fa-86314de8dcbc.png">

4. Add the `SaveImages` module to write out 16-bit images:

<img width="1440" alt="Screenshot 2022-01-27 at 10 24 51" src="https://user-images.githubusercontent.com/11314064/151345572-8d1976ff-4ccc-4431-ab71-d230e06fc710.png">

5. Repeat steps 2-4 using the images written out in 4. as input.

**Expected behavior**
I would expect both image sets written by the `SaveImages` module to be identical.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - CellProfiler Version: 4.1.3
 - Downloaded from the website or installed from source? Downloaded [here](https://cellprofiler.org/previous-releases)

**Comment by rsenft1** [comment]
Hi @nilseling, thanks for these screenshots. 
So I believe this is happening because you're selecting to process your images as _Color image_ in NamesAndTypes. This setting is appropriate for RGB images, but for images like yours this doesn't work. In general when you have multichannel images, we recommend you split the channels (e.g. using a macro in FIJI) before importing into CellProfiler. That way each channel can be assigned appropriately within your image sets in NamesAndTypes. Does this make sense?

**Comment by nilseling** [comment]
Hi @rsenft1 
thanks for the response and suggestion! 
We are usually working with 40+ channel images and would like to avoid splitting them by channel. In general reading in multi-channel images (generated outside CP) using CellProfiler v4.1.3  and _Color Image_ works fine. The RGB issue only arises when trying to read in images that were written by CellProfiler. Ideally CellProfiler should read in images the same way it has written them.

**Comment by nilseling** [comment]
Hi @bethac07 
that sounds great, thanks! I'll check it out. I'll close this issue for now and check in again once #4495 is fixed.
Best,
Nils

**Comment by a-rayford** [comment]
Hi there, I encountered this same issue when trying to save >4 channel images and came across this thread as well as [#4495](https://github.com/CellProfiler/CellProfiler/issues/4495). The ColorToGray fix works for me now (Thank You!). However, like Nils, my images have upwards of 30 channels which vary in number between datasets, so it would be great if someone could post an example  pipeline (or screenshots of each of the module settings) which implements the metadata-based solution from @bethac07 's post above. 

Best,
Austin

Desktop (please complete the following information):

- OS: macOS Big Sur 11.6.2
- CellProfiler Version: 4.2.1
- Downloaded from the website or installed from source? --dockerized version in [Steinbock](https://github.com/BodenmillerGroup/steinbock)

**Comment by rsenft1** [comment]
Hi @a-rayford , the key settings are visible in the screenshot that Beth posted. After you add your images, go to Metadata, then select **Yes** for Extract metadata? Then for Metadata extraction method, select **Extract from image file headers** and then hit **update** below and available metadata will populate the table (as seen in Beth's post).
