### ISSUE TITLE
Install file not found

### ISSUE THREAD

**Issue by Jiraya-Aizen** [CellProfiler/CellProfiler#4524]
Desktop
 - OS: [Windows 10 enterprise LTSC]
 - CellProfiler Version [all]
 - Source Installation
 - Tried clone from git, tried directly from tar.gz file and using setup.py

All packages are being installed but not the cellprofiler. I have tried all versions of the cellprofiler (git clone, setup.py and tar.gz) but the systems is not recognizing the version

Error message stating that could not find the version that satisfies the condition
![Capture](https://user-images.githubusercontent.com/52849593/159494265-811801a2-b936-4c20-89c2-dee708ececb8.PNG)

**Comment by bethac07** [comment]
Hi, 

Sorry to hear you're having an issue! What Python version are you using? 

If you just try to `pip install cellprofiler-core`, does it work? Are you successfully able to install other pip packages?
