### ISSUE TITLE
Bypassing all error mode for GUI

### ISSUE THREAD

**Issue by kvshams** [CellProfiler/CellProfiler#4527]
It is very hard to click continue for several errors (may be part of a bug #4264  or image issues). Many times proceed runs to complete the analysis by skipping that image set helps completing the pipeline #4436.  That require clicking `proceed` several time, which is not practical for large experiments. Having an option to bypass any error to automatically proceed and have the error recorded as a log file to trace back once the pipeline is completed would be a `genie wish` (like if any error comes, proceed to next image set rather than, at present, asking whether to proceed or cancel every time). I am not sure is there any such mode exists already.

**Comment by MaxiKie** [comment]
I strongly agrre with @kvshams. Such a mode, or such a option would increase the speed of a big pipeline immensly.
For example, I have a hughe projekt (>10k images) which is running a couple of days. It is not possible to sit 24/7 in front of the computer to click "Continue" every time, an error occurs.

I would really appreciate such a feature!
