### ISSUE TITLE
More customization options for DisplayDataOnImage

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4529]
It'd be nice to have some extra customization options to the way that numbers print, especially for viewing of small numbers.
Including:
- remove leading 0 (or 0 to the left of the decimal point, or however we want to phrase it)
- use scientific notation (potentially with option to set exponent)
- multiply all values by some number (less important to implement, and I know it can be done by adding in a CalculateMath module first, but could be handy to have built into this module)

**Comment by ErinWeisbart** [comment]
And while we're at it, could we add in the option of a couple fonts to pick from and/or the ability to make the print bold?

**Comment by bethac07** [comment]
Resoved by #4539
