### ISSUE TITLE
Add input filename to SaveCroppedObjects output images

### ISSUE THREAD

**Issue by callum-jpg** [CellProfiler/CellProfiler#4534]
SaveCroppedObjects currently saves files with the filename format `{object name}_{label index}.{image_format}`. To add to this, there should be information about the input image for each crop.

There is already a way to achieve this using metadata, demonstrated [here](https://forum.image.sc/t/cellprofiler-4-issue-saving-files-in-savecroppedobjects/44569). 

It would be nice for there to be an option to do this without requiring filename capture. Additionally, the option to select output structure (nested output, with a folder for each input image, or in a flat output structure) would also be great to have.

**Comment by bethac07** [comment]
Will be resolved by #4545
