### ISSUE TITLE
Binary images fail with 3-class otsu thresholding

### ISSUE THREAD

**Issue by rsenft1** [CellProfiler/CellProfiler#4535]
Reproducible example: [binary_3_class_otsu_fail.zip](https://github.com/CellProfiler/CellProfiler/files/8484532/binary_3_class_otsu_fail.zip)

When you have an image containing only two different intensities, this will fail three-class otsu thresholding. This is kind of obvious and it makes sense, but there are special cases where you may end up with a subset of your images having only two intensities (e.g., images that are overwhelmingly background) and you don't want the pipeline to barf. 

Note that this will happen even after the other changes we've made to solve issues with three-class otsu thresholding having few intensities close together (and not being able to separate these into three histogram bins see issue #4436). 

The issue in the code is around [here](https://github.com/CellProfiler/CellProfiler/blob/30a787144414e364dbe9e02e0b0f74d7884cad97/cellprofiler/modules/threshold.py#L916-L921).

Possible solutions: 

1. Carve out explicit exception for binary images such that they aren't passed into `skimage.filters.threshold_multiotsu` (this solves the issue with images having intensities of only 0 and 1, but doesn't solve it for other edge cases where an image has only two intensities

2. Check if there are two only two intensities. If so, pass to two-class otsu instead of multiotsu. I _think_ this will avoid the problem with multiotsu.

**Comment by rsenft1** [comment]
`classes` is a kwarg that can be passed in to multiotsu thresholding. Change the code to perform a check for the # of unique values and then if `num_unique` < `num_classes`, change `num_classes` to `num_unique` and pass into multiotsu.

**Comment by bethac07** [comment]
Closed by #4532
