### ISSUE TITLE
FillObjects module : Mode changes from 'Holes' to 'H'

### ISSUE THREAD

**Issue by vbruttin** [CellProfiler/CellProfiler#4542]
# Description

Using CP 4.2.1 python module (installed from source) to run a segmentation pipeline (created in 4.0 or 4.1, not sure), the segmentation masks are different than those obtained using the GUI version of CP 4.2.1. The masks created by the python module look like convex hulls. 

The origin of this bug is the module FillObjects and its setting `self.mode`. While it is correctly set to 'Holes' by default, it is replaced by the value 'H' later on. As `FillObjects.run()` only checks if `self.mode` is 'Holes', any unexpected changes default to the hull algorithm.\\
The unexpected change of 'Holes' to 'H' happens in `FillObjects.upgrade_settings()`. As my pipeline has `variable_revision_number == 1`,  `MODE_HOLES` is added to `setting_values`. However, `setting_values` is a list, so the operator `+=` has the following effet : ```['obj1', 'obj2', 'size_int', 'fill_bool'] + 'Holes' -> ['obj1', 'obj2', 'size_int', 'fill_bool', 'H', 'o', 'l', 'e', 's']```. 

## Solution
(PR incoming)

replace `+=` by `append`

## Suggestion
The Holes mode should be the fallback mode in run, not Convex Hull that is a recently added feature (less used / unexpected).

## Disclaimer
This bug happened on Windows 10, using a conda environment. CellProfiler and CellProfiler-code libraires where installed from source (pip install -e localproject).

I'm not sure why the GUI 4.2.1 and the python 4.2.1 behave differently with the same pipeline.

**Comment by bethac07** [comment]
Closed by #4543
