### ISSUE TITLE
FlagImage fails with "Classifier not JSON serializable"

### ISSUE THREAD

**Issue by hajaalin** [CellProfiler/CellProfiler#4544]
FlagImage module fails when using a classifier. It works in test mode, but not in "real" mode when analyzing images. The error message says the classifier is not serializable, so it sounds like it's not possible to send a task including the classifier to workers via zmq.

**To Reproduce**
Preparation
1. Run a pipeline with MeasureImageQuality and ExportToDatabase
2. In CellProfiler Analyst, create a classifier based on image quality measurements
3. Save classifier.

Minimal pipeline to reproduce:
- MeasureImageQuality
- FlagImage (Flag is based on Classifier, select classifier previously saved)

**Expected behavior**
- Click "Start Test Mode" and "Run", pipeline finishes without any issue.
- Click "Exit test mode" and "Analyze images", pipeline stops with error.

**Screenshots**
![cellprofiler_classifier_json](https://user-images.githubusercontent.com/1568871/166460487-48ca05f8-2e85-4b55-81f8-9627d2c9eaca.PNG)

**Desktop:**
 - OS: Windows 10
 - CellProfiler Version 4.2.1
 - CellProfiler Analyst 3.0.2
 - Both downloaded from the website

**Comment by hajaalin** [comment]
Here's a link to a minimal example:
https://wiki.helsinki.fi/display/LMU/CellProfiler+issues

**Comment by bethac07** [comment]
Bump, still causing occasional issues
