### ISSUE TITLE
Mismatched packages in installation for CellProfiler 4.2.1, Ubuntu 20.04

### ISSUE THREAD

**Issue by atc3** [CellProfiler/CellProfiler#4546]
- OS: Ubuntu 20.04
 - CellProfiler Version: 4.2.1
 - Python version: 3.8.13
 - Downloaded, installed according to instructions: https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04

During installation with pip, I got the following package mismatches between cellprofiler 4.2.1 and cellprofiler-core 4.2.1:

```
    cellprofiler 4.2.1 depends on h5py~=3.6.0
    cellprofiler-core 4.2.1 depends on h5py==3.2.1
```

and

```
    cellprofiler 4.2.1 depends on pyzmq~=22.3
    cellprofiler-core 4.2.1 depends on pyzmq==18.0.1
```

I was able to fix this by modifying the `setup.py` file of cellprofiler to match the specific versions specified by cellprofiler-core:

```
        "h5py~=3.2",
        ...
        "pyzmq~=18.0"
```

CellProfiler now seems to work, but I haven't done any extensive testing. I'm opening an issue here instead of a PR since I'm not sure what the effects of these package downgrades would be for other use cases/installation on other OSes. But if it seems OK for the other cases then I can open a PR.

**Comment by callum-jpg** [comment]
These CellProfiler dependencies were recently changed to allow for Python 3.9 builds, available [here](https://github.com/CellProfiler/CellProfiler/pull/4503/files). CellProfiler-core has not yet been updated on PyPi, but will be in due course. You shouldn't face any issues after downgrading CellProfiler dependencies.
