### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by 302850047** [CellProfiler/CellProfiler#4550]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce may be closed without investigation. You may delete this section before posting your issue below.
---

**Desktop (please complete the following information):**
 - OS: Linux
 - CellProfiler Version 4.1
 - Downloaded from the website or installed from source?
 - If the latter, how (cloned, installed from pypi, etc)?

**Describe the issue**
A clear and concise description of which steps of the installation succeeded and which failed.

**Error messages**
If applicable, post any error messages that you saw/received.  Text is preferable to screenshots, and more text preferable to less.  
If posting text, you may post it between the two lines of ` ``` ` below, otherwise you may delete those lines.

```

```

**Screenshots**

**Additional context**

Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz (85 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /bin/sh: 1: mysql_config: Permission denied
      /bin/sh: 1: mariadb_config: Permission denied
      /bin/sh: 1: mysql_config: Permission denied
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-enfykqvy/mysqlclient_04565ec54a464174b66dcee157290a60/setup.py", line 16, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-enfykqvy/mysqlclient_04565ec54a464174b66dcee157290a60/setup_posix.py", line 61, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-enfykqvy/mysqlclient_04565ec54a464174b66dcee157290a60/setup_posix.py", line 29, in mysql_config
          raise EnvironmentError("%s not found" % (_mysql_config_path,))
      OSError: mysql_config not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by bethac07** [comment]
Hi,

Were you able to resolve this? It looks like perhaps you don't have the necessary prereqs for mysqlclient - see the [PyPI instruction page for that library](https://pypi.org/project/mysqlclient/) for what you'll need to install this for various "flavors" of Linux. Good luck!
