### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by AST87** [CellProfiler/CellProfiler#4558]
**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - CellProfiler Version 4.2.1
 - Installed from source
 - If the latter, how (cloned, installed from pypi, etc)? First by cloning by following the wiki page https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04 
 - then by using ``` pip install cellprofiler ``` 

**Describe the issue**
While I am trying to install the cellprofiler following the instructions from wiki page, I am getting the following error message:

**Error messages**
```
$ cd CellProfiler
~/CellProfiler$ pip install -e .
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cellprofiler to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cellprofiler-core==4.2.1 and cellprofiler==4.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    cellprofiler 4.2.1 depends on h5py~=3.6.0
    cellprofiler-core 4.2.1 depends on h5py==3.2.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

**Additional context**
When I used the later approach to install cellprofiler directly through pip, I was able to install it but while initiating it I am getting the following error:

```
$ pip install cellprofiler
Successfully installed cellprofiler-4.2.1 cellprofiler-core-4.2.1 inflect-5.6.0 mahotas-1.4.12 mysqlclient-1.4.6 sentry-sdk-0.18.0 wxPython-4.1.0
$ cellprofiler
Traceback (most recent call last):
  File "/home/anaconda3/bin/cellprofiler", line 5, in <module>
    from cellprofiler.__main__ import main
  File "/home/anaconda3/lib/python3.9/site-packages/cellprofiler/__main__.py", line 15, in <module>
    import matplotlib
  File "/home/anaconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 205, in <module>
    _check_versions()
  File "/home/anaconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 190, in _check_versions
    from . import ft2font
ImportError: /home/anaconda3/lib/python3.9/site-packages/matplotlib/ft2font.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

```

Could you please help me in resolving these issues?

**Comment by MaxiKie** [comment]
Hi, I encountered the same issue, when installing it from source. I worked around it by changing the dependencies in the setup.py file from cellprofiler or cellprofiler_core for example like

`h5py~=3.6.0`
to
`h5py`

**Comment by chillenzer** [comment]
Yes, we also encountered this issue. After a little digging, we found that the PyPI version of `cellprofiler-core` was last updated around a year ago while the upgrade of the `h5py` version only happened a couple of months ago (in both `cellprofiler` and `cellprofiler-core`). The source codes, thus, are currently compatible but conflicting with the PyPI versions, so the simplest workaround is to just also build `cellprofiler-core` from source and then allow `pip` to find that version on your computer. 

Still, I think that would be a good occasion to either update the versions on PyPI or (if the current source is not considered stable yet) at least update the "Source installation" section in the wiki.

**Comment by bethac07** [comment]
Indeed, `core` and `CellProfiler` are kept synced, so it should always work to have both PyPI installed OR both source installed, but we can't always guarantee that having one from PyPI and one from source will work. 

We are hoping to tag and push 4.2.2 next week! Thanks for your patience.
