### ISSUE TITLE
javabridge.jutil.JVMNotFoundError: Can't find the Java Virtual Machine

### ISSUE THREAD

**Issue by MaxiKie** [CellProfiler/CellProfiler#4559]
- OS: Windows 10
 - CellProfiler Version 4.1.2
 - Installed from source (cloned)
 - Python 3.10

I installed Cellprofiler from source

Of note: for the installation to work I had to change some dependencies in the setup.py (wxPython==4.1.0 to wxPython; matplotlib==3.1.3 to matplotlib==3.5.2).

Now when I start Cellprofiler via cmd I get the following warning:

javabridge.jutil.JVMNotFoundError: Can't find the Java Virtual Machine
(for full error see screenshot)

I already tried setting up the path to JAVA and JDK manually in the environment variable (for example [here](https://github.com/fracpete/python-weka-wrapper-examples/issues/7)) or setting it up using setx (as described [here](https://forum.image.sc/t/cell-profiler-analyst-cant-find-java-virtual-machine/25930)).

Has anyone encountered a similar error and has a solution?

Thank you
![Error](https://user-images.githubusercontent.com/62472444/174456094-f4a845c5-72c6-4820-a344-a90b3aaf76fa.PNG)
!

**Comment by bethac07** [comment]
Sorry to hear you're having issues! Can you screenshot your environment variables? It is very likely an issue of those not being set correctly.
