### ISSUE TITLE
Run CP as python package : AssertionError: Feature ImageNumber for Cells does not exist

### ISSUE THREAD

**Issue by CEDRICHK** [CellProfiler/CellProfiler#4593]
CP: 4.1.3
Python: 3.8.10
Ubuntu: 20.04.4 LTS

I try to run the pipeline ExampleVitra.cppipe as code following the example providen by [Beth Cimini](https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-as-a-Python-package) but an error occurs 

> AssertionError: Feature ImageNumber for Cells does not exist

Here my code:
```
import cellprofiler_core.pipeline
import cellprofiler_core.preferences
import cellprofiler_core.utilities.java
import pathlib

cellprofiler_core.preferences.set_headless()

cellprofiler_core.utilities.java.start_java()

pipeline = cellprofiler_core.pipeline.Pipeline()
pipeline.load('./ExampleVitra.cppipe')

current_dir = pathlib.Path().absolute()
cellprofiler_core.preferences.set_default_output_directory(f"{current_dir}//Output")
file_list = list(pathlib.Path('.').absolute().glob('local_images/*.tiff'))
files = [file.as_uri() for file in file_list]
pipeline.read_file_list(files)

output_measurements = pipeline.run()

output_measurements.get_measurement_columns()
output_measurements.get_measurement('Cells', 'ImageNumber')`
```
the output from this command **output_measurements.get_measurement_columns()** is:

> [('Experiment', 'CellProfiler_Version', 'varchar'), ('Experiment', 'Pipeline_Pipeline', 'varchar'), ('Experiment', 'Run_Timestamp', 'varchar')]

the pipeline works well inside cellprofiler software, i've got the measurements in excel files respectively Cells.csv, Cytoplasm.csv, Image.csv and Nuclei.csv.

**Comment by bethac07** [comment]
Hi,

I think you will see the source of your issue if you `ls` (or `os.listdir`) your `local_images` folder - the files needed for this pipeline don't end in `.tiff` but instead in `.tif` or `.npy`. I can reproduce your behavior in your current stack, but if you replace your glob line with the below, you should get what you expect.

```
file_list = list(pathlib.Path('.').absolute().glob('local_images/*.tif'))
file_list += list(pathlib.Path('.').absolute().glob('local_images/*.npy'))
```

**Comment by bethac07** [comment]
Probably what will make your life easiest is to just run each image set with something like:

```
for n in range(1,n_image_sets): #assuming you know what this is, if not you'll want some sort of `while` or `try` logic
    output_measurements = pipeline.run(image_set_start=n,image_set_end=n)
    for meas in measurements_I_want:
        add_to_some_data_structure(output_measurements.get_measurements(meas_object, meas_feature_name))
```

If your pipeline makes spreadsheets or databases, they will get made each time, so they'll be overwritten (and so might as well be disable) but this will work if you want to get measurements on -the-fly. Otherwise, you're going to have to dig a lot deeper into the CellProfiler internals in order to do what you want to do. CellProfiler really was never initially designed to be run in this way, which is why we usually advise against doing this.
