### ISSUE TITLE
What's new? Link broken

### ISSUE THREAD

**Issue by rsenft1** [CellProfiler/CellProfiler#4625]
**Describe the bug**
The "What's new" link in the welcome page is broken. It currently goes to https://carpenter-singh-lab.broadinstitute.org/blog/categories/releases 

Should probably go here? https://carpenter-singh-lab.broadinstitute.org/browse/blog?f%5B0%5D=custom_taxonomy%3A58&keys

This is with 4.2.1. Disregard if this is already fixed in 4.2.4.

**Comment by bethac07** [comment]
Fixed in https://github.com/CellProfiler/CellProfiler/pull/4614 :)
