### ISSUE TITLE
TypeError using stardist in cellprofiler

### ISSUE THREAD

**Issue by JanSchwenzfeier** [CellProfiler/CellProfiler#4664]
Hi everybody,

I am trying to run the runstardist module with cellprofiler. But i get the following TypeError when I add the stardist module:

> Traceback (most recent call last):
>   File "e:\jan\projects\fiscas\fiscas-venv\lib\site-packages\cellprofiler\gui\pipelinelistview.py", line 1069, in __on_i
> tem_activated
>     self.__module_view.set_selection(module.module_num)
>   File "e:\jan\projects\fiscas\fiscas-venv\lib\site-packages\cellprofiler\gui\module_view\_module_view.py", line 363, in
>  set_selection
>     control = self.make_choice_control(
>   File "e:\jan\projects\fiscas\fiscas-venv\lib\site-packages\cellprofiler\gui\module_view\_module_view.py", line 726, in
>  make_choice_control
>     choices = choices + [v.value]
> TypeError: can only concatenate tuple (not "list") to tuple
> Exiting the pipeline validation thread

- OS: windows server 2012 R2
- Python 3.8.10 installation. 
- cellprofiler 4.2.4 (installed with pip)
- stardist 0.8.3 
During the installation process I got a dependency error with pip since stardist wants to have h5py < 3 and cellprofiler wants h5py==3.6.0. I am currently using h5py 3.6.0 but the same error appears with h5py 2.1.0 (which is the one stardist wants to have) 

Can anybody help me with this?

This is my package list:
absl-py==1.3.0
astunparse==1.6.3
boto3==1.26.3
botocore==1.29.3
cachetools==5.2.0
cellpose==2.0.5
CellProfiler==4.2.4
cellprofiler-core==4.2.4
centrosome==1.2.1
certifi==2022.9.24
charset-normalizer==2.1.1
colorama==0.4.6
csbdeep==0.7.2
cycler==0.11.0
deprecation==2.1.0
docutils==0.15.2
fastremap==1.13.3
flatbuffers==2.0.7
future==0.18.2
gast==0.4.0
google-auth==2.14.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.50.0
h5py==3.6.0
idna==3.4
imagecodecs==2022.9.26
imageio==2.22.4
importlib-metadata==5.0.0
inflect==6.0.2
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.2.0
keras==2.7.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==14.0.6
llvmlite==0.39.1
mahotas==1.4.13
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.1.3
mysqlclient==1.4.6
natsort==8.2.0
networkx==2.8.8
numba==0.56.4
numpy==1.23.4
oauthlib==3.2.2
opencv-python-headless==4.6.0.66
opt-einsum==3.3.0
packaging==21.3
Pillow==9.3.0
prokaryote==2.4.4
protobuf==3.19.6
psutil==5.9.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.10.2
pyparsing==3.0.9
python-bioformats==4.0.6
python-dateutil==2.8.2
python-javabridge==4.0.3
PyWavelets==1.4.1
pyzmq==22.3.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
s3transfer==0.6.0
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
sentry-sdk==0.18.0
six==1.16.0
stardist==0.8.3
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.7.0
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.27.0
termcolor==2.1.0
threadpoolctl==3.1.0
tifffile==2022.4.8
torch==1.13.0
tqdm==4.64.1
typing-extensions==4.4.0
urllib3==1.26.12
Werkzeug==2.2.2
wrapt==1.14.1
wxPython==4.1.0
zipp==3.10.0

**Comment by bethac07** [comment]
Sorry to hear you're having trouble! Can you confirm that if you move the plugins out of whatever folder you have CellProfiler pointing at right now, whether or not you still get the error? If you still get it, then it's a CellProfiler issue, if not, then it's a plugin issue (and we will probably transfer the issue to that repository)

If it IS a CellProfiler issue, I notice that you are installing on the E drive - CellProfiler is typically not happy being installed there. Can you try installing on the C drive instead?

**Comment by JanSchwenzfeier** [comment]
Thank you for the very quick reply! 
After removing the plugins out of the plugin folder I don't get any error because I don't have access to the Stardist module, so I can't check for any errors. I wasn't quite sure were to post this issue, since it is the plugin that causes the issue but the error gets thrown from the cellprofiler gui module. But maybe it would be better then to post this issue on the stardist github page. 

The installation on C is unfortunately not possible. We have very limited storage space on C and therefore it is reserved for the Operating System alone and we are not allowed to install anything on there.

**Comment by JanSchwenzfeier** [comment]
I reposted the issue now in the cellprofiler-plugin page because it is most likely more appropriate and will therefore close this issue.
