### ISSUE TITLE
MeasureGranularity module alters images

### ISSUE THREAD

**Issue by callum-jpg** [CellProfiler/CellProfiler#4670]
A [user on the forum](https://forum.image.sc/t/bug-in-cellprofiler-modifies-image-when-measuring-granularity/74057) has reported that the `MeasureGranularity` module erroneously alters the input_image. Any module downstream of `MeasureGranularity` has therefore been working with an altered image.

This is a result of operations being applied to the original input image, rather than a copy: https://github.com/CellProfiler/CellProfiler/blob/2877e58eaa95f66167d49e13505c4384ca02cb48/cellprofiler/modules/measuregranularity.py#L304

Data to reproduce:
[measuregranularity.zip](https://github.com/CellProfiler/CellProfiler/files/10032742/measuregranularity.zip)

**Comment by bethac07** [comment]
Thank you so much @tischi for finding this and pointing this out! This has apparently been going on... a while. We will definitely fix!

<img width="901" alt="image" src="https://user-images.githubusercontent.com/6721515/202495532-57eee7a3-9f30-4562-bbd1-a7916eef540a.png">

**Comment by tischi** [comment]
Yeah, it's a nasty one, hard to spot. I was lucky to stumble over it.

**Comment by bethac07** [comment]
Just to make sure to clarify the scope - this ONLY AFFECTS YOU if your setting for “Subsampling factor for granularity measurements” is set to 1. If you use the default value, which is 0.25, or any other value between 0 and 1, you are ok.

(This is still very bad and very necessary to fix! But hopefully it means the spread is somewhat less)

**Comment by bethac07** [comment]
Closed in #4696 and #4697
