### ISSUE TITLE
Typo (extra space) in MacOS M1 source installation instructions

### ISSUE THREAD

**Issue by nmra-abarthmaron** [CellProfiler/CellProfiler#4675]
Hi CellProfiler team,

I discovered a typo in the source installation instructions on the [MacOS M1 page](https://github.com/CellProfiler/CellProfiler/wiki/Installation-of-CellProfiler-4-from-source-on-MacOS-M1#conda-installation).

Under the 'Brew Python Installation' section it is step 13: `Install CellProfiler dependencies`, and under the 'Conda Installation' section it is step 7: `Install CellProfiler dependencies, excluding wxPython`.

The problem is with `scikit- learn>=0.20`, which has a space after the dash when it shouldn't. My guess is that this was missed because there is also a line break right after the space. 

This caused me some minor problems, but was easy to fix once I realized the problem. Thanks for your support!

Best,
Asa

**Comment by callum-jpg** [comment]
Hey Asa,

Thank you for spotting that. I've gone ahead and updated the instructions so hopefully it's all good now :)
