### ISSUE TITLE
Not able to open CP4 on MacOS 12.6.1

### ISSUE THREAD

**Issue by balistre** [CellProfiler/CellProfiler#4712]
---

**Desktop (please complete the following information):**
 - OS: OSX 12.6.1
 - CellProfiler Version 4.2.4
 - Downloaded from the website or installed from source? Dowloaded From website
 - If the latter, how (cloned, installed from pypi, etc)? Extracted from compressed folder

**Describe the issue**
I just intaled CP4 on my new Macbook Pro 12.6.1 and after following your instructions to avoid security problems I still get this message: "CellProfiler4.app” can’t be opened because Apple cannot check it for malicious software".
The software cannot be opened. I have tried all the tricks suggested in the CellProfiler website.

**Error messages**
"CellProfiler4.app” can’t be opened because Apple cannot check it for malicious software".

**Screenshots**

**Additional context**

**Comment by callum-jpg** [comment]
It's possible to grant exception for apps in the `Privacy & Security` section in `Settings` on your Mac. Here's a link to the Apple documentation on this: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

Relevant section here: `Note: You can also grant an exception for a blocked app by clicking the Open Anyway button in Privacy & Security settings. This button is available for about an hour after you try to open the app.`
