### ISSUE TITLE
Installation issue on arch linux

### ISSUE THREAD

**Issue by monajue** [CellProfiler/CellProfiler#4715]
Hi,

I could easily install CellProfiler via pip. But when I open CellProfiler I get a lot of errors in the terminal (mostly "Detected WX error", example see attached) and the GUI looks wired (all buttons seem compressed and unreadable, see screenshot attached). I already re-install wxPython via pacman but I could not fully improve the appearance of the GUI.

Thanks for your help!

---

 - Arch Linux 6.1.7-arch1-1
 - CellProfiler Version 4.2.5
 - Installed from source via pypi

**Error messages**
```
Detected WX error
Traceback (most recent call last):
  File "/home/mona/.local/lib/python3.10/site-packages/cellprofiler/gui/module_view/_module_sizer.py", line 221, in RecalcSizes
    item_location = wx.Point(item_x, item_y)
TypeError: Point(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 2 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'int'
  overload 4: argument 1 has unexpected type 'int'

```
![CellProfiler](https://user-images.githubusercontent.com/123470997/214375017-212e924d-72dd-428a-9903-bdb66d4e739e.png)

**Comment by callum-jpg** [comment]
Would it be possible for you to downgrade python to 3.8 or 3.9 and retry the installation? I think that's the source of these errors and strange wxPython formatting

**Comment by monajue** [comment]
This worked! I have installed python 3.9 and worked in a virtualenv to install CellProfiler via pip. Now the GUI looks perfectly fine!

![CellProfiler_python39](https://user-images.githubusercontent.com/123470997/214440726-fb43019a-5180-4492-b56e-c265617665f6.png)
