### ISSUE TITLE
Tests failing due to skimage 0.20

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#4740]
"Selem" is now "footprint"

**Comment by bethac07** [comment]
Oh, also multichannel is deprecated in a couple places

**Comment by bethac07** [comment]
Uh oh, changing selem to footprint broke a BUNCH of tests checking for expected values. Will dig in

**Comment by bethac07** [comment]
Alright, most of the tests are fixed, but 4 tests related to expected values in granularity [are still failing](https://github.com/CellProfiler/CellProfiler/actions/runs/4317229452/jobs/7534033188) - arrays that are expected to match to 7 digits are failing with 1-2.1e-06. Comparing to the [last passing run](https://github.com/CellProfiler/CellProfiler/actions/runs/4286707588/jobs/7466631003), no other packages I would suspect to be the issue here (aka centrosome, numpy, and scipy (which are the only 3 dependencies of the granularity module; the latter two of course could also wreak small changes in skimage)) have changed versions. The Mac image that Actions used to build did change (compare screenshots below), but also, [skimage did change their build system](https://github.com/scikit-image/scikit-image/pull/6536), so that to me seems the more likely change to handling of these particular floats.

I honestly don't feel like we NEED 7 digits of precision, 5-6 are likely fine, in which case, let's update the test, but @gnodar01 lmk if you think I should be less lazy and dig in further.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/6721515/222529702-f405ac6a-e548-4a09-a68c-97bf561123e1.png"> <img width="282" alt="image" src="https://user-images.githubusercontent.com/6721515/222529783-762a8825-ee20-482d-8802-5092e26c9c46.png">

**Comment by gnodar01** [comment]
>  honestly don't feel like we NEED 7 digits of precision, 5-6 are likely fine

Agreed, but I don't think we should be using `round(abs(value - expected), tolerance) == 0` or similarly `abs(value - expected) < tolerance`. It's a bit clunky, and floating point numbers have less precision as you go up the number scale, so you have to use smaller tolerances for `value` close to 1, but bigger tolerances for larger positive or negative `value`.

Should replace with [pytest.approx](https://docs.pytest.org/en/latest/reference/reference.html#pytest.approx) which accounts for some tricky comparisons and lets us use both relative and absolute precision separately. Something like `value == approx(expected, rel=1e-6, abs=1e-12)

**Comment by bethac07** [comment]
@gnodar01 Agreed, that structure is weird, I'm not sure why it is like that. Will fix to something like pytest or assert_almost_equal

**Comment by bethac07** [comment]
[I went with numpy.testing](https://github.com/CellProfiler/CellProfiler/pull/4741/commits/d7a8a511973019a1e233ab392ce3cc4d1e82f76c) rather than pytest.approx, just because we use the former in ~50 tests and the latter in none, and we really don't need our test suite getting more varied than it already is*. Assuming tests passing (3.9 tests in question already have, 3.8 are building wx from scratch as usual (still should figure that out someday) so will need another hour), PR is ready for review.

*=(many of our other tests use `assert_almost_equal`, but the [documentation for that](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_almost_equal.html) recommends using `assert_allclose` instead. Hence why I didn't do EXACTLY what most of our other tests do. We can make another issue for moving `assert_almost_equal` to `assert_allclose` later, assuming all works as expected here.)
