### ISSUE TITLE
Cannot load ImageMath module

### ISSUE THREAD

**Issue by cliandouble08** [CellProfiler/CellProfiler#4799]
Hi, 

I have installed CellProfiler from source on Windows 11. The program starts with no problem through command prompt but always returns a warning message "Could not load cellprofiler.modules.imagemath."

`(base) C:\Github\CellProfiler\core>py -3.8 -m cellprofiler
C:\Github\CellProfiler\cellprofiler\__main__.py:16: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
[CP - WARNING] cellprofiler_core.utilities.core.modules::add_module: Could not load cellprofiler.modules.imagemath
Traceback (most recent call last):
  File "C:\Github\CellProfiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 65, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Github\CellProfiler\cellprofiler\modules\imagemath.py", line 34, in <module>
    import inflect
  File "C:\Users\genxu\AppData\Roaming\Python\Python38\site-packages\inflect\__init__.py", line 75, in <module>
    from pydantic import Field`

Subsequently, when using my pretrained model in CellPose module, an error message persists for non-negative inputs, and I could not solve this problem without the ImageMath module. 

` File "C:\Github\CellProfiler\cellprofiler\gui\figure\_figure.py", line 2086, in normalize_image
    image = skimage.exposure.adjust_gamma(image, **kwargs["normalize_args"])
  File "C:\Users\genxu\AppData\Roaming\Python\Python38\site-packages\skimage\exposure\exposure.py", line 674, in adjust_gamma
    _assert_non_negative(image)
  File "C:\Users\genxu\AppData\Roaming\Python\Python38\site-packages\skimage\exposure\exposure.py", line 606, in _assert_non_negative
    raise ValueError('Image Correction methods work correctly only on '
ValueError: Image Correction methods work correctly only on images with non-negative values. Use skimage.exposure.rescale_intensity.`

Is there any other way than ImageMath to solve the non-negative value problem? And is the failure of loading ImageMath module a bug or I did not install the program correctly? 

Thanks, 
Cameron

**Comment by bethac07** [comment]
This appears to be an issue with inflect 7, if you can `pip install inflect==6.2.0`, that should hopefully take care of this. We are working on tagging 4.2.6 to deal with some of the package version issues we've recently seen, stay tuned and apologies for the inconvenience!
