### ISSUE TITLE
Permission error when installing in macOS 13.0+

### ISSUE THREAD

**Issue by swvanderlaan** [CellProfiler/CellProfiler#4814]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce may be closed without investigation. You may delete this section before posting your issue below.
---

I have an issue installing the macOS app.

**MacBook (please complete the following information):**
 - OS: Sonoma 14.0 Beta (23A5337a) (same issue exists on 13.+ though)
 - CellProfiler version: 4.2.6 (but actually from 4.* upwards)
 - Downloaded from the website [here](https://github.com/CellProfiler/CellProfiler/releases).

**Describe the issue**
I followed your suggestions [described here](https://github.com/CellProfiler/CellProfiler/wiki/Opening-CellProfiler-on-Mac-OS-10.15.7). Those do not work. I tried 4.1.3, 4.2.4, 4.2.5, and 4.2.6. There is a permission error having to do with the Apple Developer Certificates of CellProfiler - probably the lack thereof or it's expired. More information [can be found here](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) (if not known). 

**Error messages**
See screenshots.

**Screenshots**
Attached.
<img width="372" alt="error" src="https://github.com/CellProfiler/CellProfiler/assets/8877879/e320f29d-17ab-430d-ae89-1191b713a3fe">
![message](https://github.com/CellProfiler/CellProfiler/assets/8877879/e7865e0c-a0b0-43fa-8ff7-cc84b1a34b02)

**Additional context**
There is a bypass, when you're the administrator, but if you're not, you can't bypass this issue.

**Comment by gnodar01** [comment]
Hi, can you try the instructions listed here: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by gnodar01** [comment]
Just to be clear, you have tried clicking the "Open Anyway" button in your second screenshot, and it does not succeed because you are not an admin. Is that correct?

**Comment by swvanderlaan** [comment]
I tried those instructions, and that doesn't work. And my Mac is managed, so I can't change the settings. The only solution was to apply `xattr -dr com.apple.quarantine /path/to/PROGRAM` - which is fine for my purposes. That being said, it's better for any developer to simply apply for the certification.

**Comment by gnodar01** [comment]
Thanks for the feedback!
