### ISSUE TITLE
Issues is display while in dark mode

### ISSUE THREAD

**Issue by Andrea-Papaleo** [CellProfiler/CellProfiler#4823]
**Describe the bug**
Hard to see text and ui components in dark mode. Specifically "Names and Types" image list and "Update" button.

**To Reproduce**
1. Turn on dark mode on computer
2. Open Cell profiler
3. Click around

**Expected behavior**
All colors update when switching dark/light modes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1 (22F82)
 - CellProfiler Version 4.2.5
 - Downloaded from the website

**Additional context**
<img width="1567" alt="Screenshot 2023-09-15 at 9 42 07 AM" src="https://github.com/CellProfiler/CellProfiler/assets/93597832/eb0c5ffa-8aef-4bb6-8a31-c3e99e9eacc2">
<img width="1567" alt="Screenshot 2023-09-15 at 9 43 48 AM" src="https://github.com/CellProfiler/CellProfiler/assets/93597832/204618fb-06e6-4356-9548-ad82c8901bbb">

**Comment by gnodar01** [comment]
Mostly fixed in CP 5

<img width="1359" alt="Screenshot 2023-09-15 at 1 40 42 PM" src="https://github.com/CellProfiler/CellProfiler/assets/8888732/54120f22-709c-4a22-a7b6-7d83e2aabded">
