### ISSUE TITLE
Building from Source - ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by spirpinias** [CellProfiler/CellProfiler#4855]
Following your Build from Source, verbatim. 
---

Ubuntu 20.04

**Describe the issue**
Upon installation instructions I received this error. 

**Error messages**
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

```

```

Thank you!

**Comment by gnodar01** [comment]
Hi, the repository has been restructured recently. Are you trying to build the latest CellProfiler 4 (4.2.6) or the not-yet-released CellProfiler 5? Can you also point me at which of the wiki pages you were following?

**Comment by gnodar01** [comment]
Thanks for the info. I've modified the instructions, assuming you're using python 3.8:

```
sudo apt update
sudo apt -y upgrade
sudo apt install -y make gcc build-essential libgtk-3-dev
sudo apt-get install -y python3.8-dev python3-pip openjdk-11-jdk-headless default-libmysqlclient-dev libnotify-dev libsdl2-dev libwebkit2gtk-4.0-dev

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH=$PATH:/home/ubuntu/.local/bin

wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.2.1-cp38-cp38-linux_x86_64.whl
pip3 install wxPython-4.2.1-cp38-cp38-linux_x86_64.whl

git clone --branch 4.2.x git@github.com:CellProfiler/CellProfiler.git
cd CellProfiler
pip3 install .
```

**Comment by gnodar01** [comment]
Hmmm, can you try `https` instead of `ssh`:

`git clone --branch 4.2.x https://github.com/CellProfiler/CellProfiler.git`

**Comment by spirpinias** [comment]
I thank you very much! This was extremely helpful..

One more thing though not related to the installation.

I got this error and wondering if you can help? If I need to open a new ticket, I can do that. 

module ExportToSpreadsheet # 21: CPU_time = 0.00 secs, Wall_time = 0.00 secs
  /usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
    return _methods._mean(a, axis=axis, dtype=dtype,
  /usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
    ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

after these statements the code stops. Any ideas?

**Comment by gnodar01** [comment]
Great! Can certainly take a look at that. Please do file as a separate issue and fill as much of the template as possible so that we can reproduce on our end.
