### ISSUE TITLE
CI Bug - Core tests run infinitely except for when you look at them hard enough

### ISSUE THREAD

**Issue by gnodar01** [CellProfiler/CellProfiler#4859]
May or may not be reproducable, depending on wether this bug appearing depends on randomness of Github actions (which vm GH happens to allocate, where it is run, when it happens to run, etc.)

In the most recent ~four~ six (and counting) runs of the `test.yml` workflow, tests for frontend and library pass as usual, but tests for core run without outputting anything for an indefinite amount of time. [Here](https://github.com/CellProfiler/CellProfiler/actions/runs/7629460281) there were 3 attempts. [The first](https://github.com/CellProfiler/CellProfiler/actions/runs/7629460281/attempts/1) was manually cancelled after 30 minutes. [The second](https://github.com/CellProfiler/CellProfiler/actions/runs/7629460281/attempts/2) was manually cancelled after 1 hour and 40 minutes. On [attempt 3](https://github.com/CellProfiler/CellProfiler/actions/runs/7629460281) I re-ran failed (cancelled) jobs with "enable debug logging" toggled on:

![Screenshot 2024-01-23 at 7 10 44 PM](https://github.com/CellProfiler/CellProfiler/assets/8888732/f11e0ab9-750c-48e2-be0e-36b7d351e499)

The debug information showed nothing of particular note, but the tests ran successfully, and took just over 3 minutes to do so:

![Screenshot 2024-01-23 at 7 13 39 PM](https://github.com/CellProfiler/CellProfiler/assets/8888732/9225cf26-dd67-405a-ab15-172857e7826e)

I assumed it was just coincidence, and merged PR #4847 where those tests were being launched from. After merge, tests run again since master is being pushed to.

[Again](https://github.com/CellProfiler/CellProfiler/actions/runs/7631010120/attempts/1), debug info was off, and core tests ran indefinitely; this time for 4 hours 15 minutes, at which point I cancelled.

Each of the times it ran indefinitely, the output was sparse:

![Screenshot 2024-01-23 at 7 16 38 PM](https://github.com/CellProfiler/CellProfiler/assets/8888732/c1ef6f36-c0d5-4d84-8c58-ba67d43585df)

The output just shows the command for invoking the tests, the initial pytest output right before the first test begins, and then nothing. It doesn't seem to hang on a particular test, but rather hangs before the first even begins.

Running tests locally, nothing seems to be amiss. They run perfectly fine.

~As I'm typing this,~ I've re-run the most recent cancelled tests with "enable debug logging" toggled on, and [again](https://github.com/CellProfiler/CellProfiler/actions/runs/7631010120) it ran to completion in 3 minutes.

Should note, looking through the outputs of previous steps, nothing about the installation process seems amiss (the usual culprit of long-running tasks being pip install something). It gets **to** the test step quick enough, just hangs **on** the test step.

**Comment by gnodar01** [comment]
#4867 did not resolve, just introduced increased verbosity to monitor the issue going forward.

**Comment by bethac07** [comment]
`get_work_twice` failed [here](https://github.com/CellProfiler/CellProfiler/actions/runs/8065722311/job/22032143155#step:9:31) (just to add to your collation)

**Comment by bethac07** [comment]
More random fails - [here](https://github.com/CellProfiler/CellProfiler/actions/runs/8902600716/job/24448824323?pr=4893#step:9:39) and [here](https://github.com/CellProfiler/CellProfiler/actions/runs/8901972771/job/24446928527#step:9:30)

**Comment by bethac07** [comment]
Whatever it was, it was in rare form last night, and/or it hates me personally and specifically (which, no judgment, I feel that way most days), [this one](https://github.com/CellProfiler/CellProfiler/actions/runs/8903283124) failed 4 times last night in 4 different places, so now might be a time we can actually get it to run deterministically enough to trace it (maybe)

**Comment by gnodar01** [comment]
Potentially closed by #4927. Will re-open if we notice core tests start to fail again.
