### ISSUE TITLE
Installation problem on Ubuntu

### ISSUE THREAD

**Issue by lbssn** [CellProfiler/CellProfiler#4871]
Hello,

I keep getting this error message during installation:

Collecting scikit-learn<1,>=0.20 (from CellProfiler==4.2.6)
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1391 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

I tried several ways to install cellprofiler and the latest was with getting the clone from GitHub and then running pip3 install .

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Python3.10
 - CellProfiler Version : cloned from GitHub

Thanks if you can help me resolve this issue.

Laurent

**Comment by gnodar01** [comment]
Hi.

The latest (released) version of CellProfiler is `4.2.6`. Cellprofiler 4 requires python 3.8. We have tested on python 3.9 as well, and it should work, but 3.8 has much more usage so it's safer. python 3.10 is not supported for CellProfiler 4. 

The main branch is the development branch, which contains the in-progress CellProfiler 5.

If you are cloning from github, and you want `cellprofiler==4.2.6`, make sure you are on the `4.2.x` branch, [as you can see here](https://github.com/CellProfiler/CellProfiler/tree/4.2.x).

You can do this with `git fetch` followed by `git switch 4.2.x`.

Once you've done that, run `python -m pip install .`, or `python3 -m pip install`, or `python38 -m pip install`, depending on how specific you need to be to ensure you're using python 3.8. It's best to do all of this in a virtual environment, or a conda environment.

**Comment by gnodar01** [comment]
I'll close this issue. Feel free to comment if you have any additional problems and I'll reopen.
