### ISSUE TITLE
FlagImage support for CPA3 classifiers

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4873]
Apparently the changes to ClassifyObjects (#4391) and FilterObjects (#4407) to broaden CPA classifier handling also should have been included in the FlagImage module.

**Comment by bethac07** [comment]
Yup, #4544 :(

**Comment by DavidStirling** [comment]
I seem to recall that there was also an issue with handling of NaN values but not sure if it's fixed? To my memory CPA replaces NaN values with 0 during training, but CellProfiler didn't mimic this and so the module crashed if any measurements were invalid.

**Comment by bethac07** [comment]
Unless/until we have an example of a failing case that isn't #4544 , otherwise CPA3 classifiers seem to generally work so I'll close this, we can reopen as needed.
