### ISSUE TITLE
Installation from source failing

### ISSUE THREAD

**Issue by kruettner** [CellProfiler/CellProfiler#4883]
name: Installation problem
about: Report issues installing CellProfiler
title: ''
labels: Environment/Install

---

**Desktop (please complete the following information):**
 - OS: [Windows 11 Enterprise]
 - CellProfiler Version [5.0.? and 4.2.6]
 - conda environment cellprofiler with python3.8
 - git clone https://github.com/CellProfiler/CellProfiler.git in Terminal
 - also tested downloading Zip from https://github.com/CellProfiler/CellProfiler or using the windows git desktop client

**Describe the issue**

following from source installation described here: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29. all dependencies are installed and working, including correct path for JDK_HOME and JAVA_HOME
final goal is to have it running with GPU support for runcellpose and runomnipose. I have a working installation on another machine from a year ago but currently installation does not seem to work as intended.

pip install numpy works
C:\Users\sebastian\Cellprofiler>pip install -e .

**Error messages**
Obtaining file:///C:/Users/sebastian/Cellprofiler
ERROR: file:///C:/Users/sebastian/Cellprofiler does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found. and indeed there is no such file anywhere to be found.

**Describe the issue**
Aiming to install cellprofiler-core seems successful but does not start cellprofiler

C:\Users\sebastian\Cellprofiler>git clone https://github.com/CellProfiler/core.git
(cellprofiler) C:\Users\sebastian\Cellprofiler\core>pip install -e .

Obtaining file:///C:/Users/sebastian/Cellprofiler/core
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: boto3>=1.12.28 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (1.34.72)
Requirement already satisfied: centrosome~=1.2.2 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (1.2.2)
Requirement already satisfied: docutils==0.15.2 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (0.15.2)
Requirement already satisfied: future>=0.18.2 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (1.0.0)
Requirement already satisfied: fsspec>=2021.11.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (2024.3.1)
Requirement already satisfied: h5py~=3.6.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (3.6.0)
Requirement already satisfied: lxml>=4.6.4 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (5.1.0)
Requirement already satisfied: matplotlib~=3.1.3 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (3.1.3)
Requirement already satisfied: numpy~=1.24.4 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (1.24.4)
Requirement already satisfied: psutil>=5.9.5 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (5.9.8)
Requirement already satisfied: pyzmq~=22.3.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (22.3.0)
Requirement already satisfied: scikit-image~=0.20.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (0.20.0)
Requirement already satisfied: scipy<1.11,>=1.9.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (1.9.1)
Requirement already satisfied: scyjava>=1.9.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (1.9.1)
Requirement already satisfied: zarr~=2.16.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (2.16.1)
Requirement already satisfied: google-cloud-storage~=2.10.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from cellprofiler-core==5.0.0) (2.10.0)
Requirement already satisfied: botocore<1.35.0,>=1.34.72 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from boto3>=1.12.28->cellprofiler-core==5.0.0) (1.34.72)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from boto3>=1.12.28->cellprofiler-core==5.0.0) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from boto3>=1.12.28->cellprofiler-core==5.0.0) (0.10.1)
Requirement already satisfied: deprecation in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from centrosome~=1.2.2->cellprofiler-core==5.0.0) (2.1.0)
Requirement already satisfied: pillow>=7.1.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from centrosome~=1.2.2->cellprofiler-core==5.0.0) (10.2.0)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (2.29.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (2.18.0)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (2.4.1)
Requirement already satisfied: google-resumable-media>=2.3.2 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (2.7.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (2.31.0)
Requirement already satisfied: cycler>=0.10 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from matplotlib~=3.1.3->cellprofiler-core==5.0.0) (0.12.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from matplotlib~=3.1.3->cellprofiler-core==5.0.0) (1.4.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from matplotlib~=3.1.3->cellprofiler-core==5.0.0) (3.1.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from matplotlib~=3.1.3->cellprofiler-core==5.0.0) (2.9.0.post0)
Requirement already satisfied: networkx>=2.8 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scikit-image~=0.20.0->cellprofiler-core==5.0.0) (3.1)
Requirement already satisfied: imageio>=2.4.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scikit-image~=0.20.0->cellprofiler-core==5.0.0) (2.34.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scikit-image~=0.20.0->cellprofiler-core==5.0.0) (2023.7.10)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scikit-image~=0.20.0->cellprofiler-core==5.0.0) (1.4.1)
Requirement already satisfied: packaging>=20.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scikit-image~=0.20.0->cellprofiler-core==5.0.0) (24.0)
Requirement already satisfied: lazy_loader>=0.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scikit-image~=0.20.0->cellprofiler-core==5.0.0) (0.3)
Requirement already satisfied: jpype1>=1.3.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scyjava>=1.9.1->cellprofiler-core==5.0.0) (1.5.0)
Requirement already satisfied: jgo in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from scyjava>=1.9.1->cellprofiler-core==5.0.0) (1.0.5)
Requirement already satisfied: asciitree in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from zarr~=2.16.1->cellprofiler-core==5.0.0) (0.3.3)
Requirement already satisfied: fasteners in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from zarr~=2.16.1->cellprofiler-core==5.0.0) (0.19)
Requirement already satisfied: numcodecs>=0.10.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from zarr~=2.16.1->cellprofiler-core==5.0.0) (0.12.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from botocore<1.35.0,>=1.34.72->boto3>=1.12.28->cellprofiler-core==5.0.0) (1.26.18)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (1.63.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (4.25.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (1.23.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (4.9)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from google-resumable-media>=2.3.2->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (1.5.0)
Requirement already satisfied: six>=1.5 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from python-dateutil>=2.1->matplotlib~=3.1.3->cellprofiler-core==5.0.0) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (2024.2.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\sebastian\.conda\envs\cellprofiler\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage~=2.10.0->cellprofiler-core==5.0.0) (0.6.0)
Building wheels for collected packages: cellprofiler-core
  Building editable for cellprofiler-core (pyproject.toml) ... done
  Created wheel for cellprofiler-core: filename=cellprofiler_core-5.0.0-0.editable-py3-none-any.whl size=4738 sha256=b5de8b6654aea08eebf7d4ef0e40df9042ba7392f92b80f7427fad61b661450b
  Stored in directory: C:\Users\sebastian\AppData\Local\Temp\pip-ephem-wheel-cache-s6dhe7xz\wheels\d4\be\aa\50b8f07e9a2b96b25d5c9d4356e5bb7fd58391042780a1b3e7
Successfully built cellprofiler-core
Installing collected packages: cellprofiler-core
Successfully installed cellprofiler-core-5.0.0

**Error messages**
(cellprofiler) C:\Users\sebastian\Cellprofiler\core>cellprofiler
'cellprofiler' is not recognized as an internal or external command,
operable program or batch file.

**Describe the issue**
Aiming to install .yaml for version 4.2.6 following this resource: https://github.com/CellProfiler/CellProfiler-plugins/blob/0c2e7cab5c13d17fa376b2bd42ca6a7e5db04960/Instructions/Install_environment_instructions_windows.md and using this yaml file: https://github.com/CellProfiler/CellProfiler-plugins/blob/0c2e7cab5c13d17fa376b2bd42ca6a7e5db04960/Instructions/cellprofiler_plugins_windows.yml results in a running cellprofiler 4.2.6 but has conflicts. 

pip install stardist csbdeep --no-deps works
pip install omnipose works
pip install -e .[cellpose] works

git clone https://github.com/CellProfiler/CellProfiler-plugins.git fails
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118 fails

**Comment by gnodar01** [comment]
Hi, after running this step:

git clone https://github.com/CellProfiler/CellProfiler.git in Terminal

You will be on the main branch, which is the development branch of the not-yet-released CellProfiler 5. You will need to switch to the `4.2.x` branch, in both the `CellProfiler` repository, and the `core` repository.

First make sure that `core` and `CellProfiler` are in separate directories. So you should have something like:

`C:\Users\sebastian\core`
`C:\Users\sebastian\CellProfiler`

Do `cd C:\Users\sebastian\core` and run `git switch 4.2.x`. Run `git status` and ensure it says "on branch 4.2.x". Then run `pip install -e .`.

Do the same for the CellProfiler repository. Run `cd C:\Users\sebastian\Cellprofiler` and `git switch 4.2.x`, and finally `pip install -e .`.

**Comment by gnodar01** [comment]
> And would receive this error message when loading my pipeline

Errors while loading plugins are normal and okay. If you only want to use the CellPose plugin, then that is the only one where errors are important. What CellProfiler tries to do is load all plugins, and if any fail (e.g. due to dependencies being absent), then it will just not load that plugin. Therefore if you are not planning to use a given plugin, like `runimagejscript`, `runomnipose, or `runstardist` for instance, then you do not need to try to resolve those errors.

When you run all of the following:

```
pip install -e .[cellpose]
pip install -e .[runimagejscript]
pip install -e .[cellpose_omni]
pip install -e .[imagej]
pip install -e .[stardist]
```

you are trying to use all of the plugins. This is very rarely what you want to do. The reason it is failing is because some of the plugins have mutually contradictory dependencies. 

I would recommend uninstalling the ones you don't need and don't plan to use.

**Comment by gnodar01** [comment]
I'll mark the issue as resolved since it seems both CellProfiler and CellPose installed correctly for you. However if you have follow up questions, feel free to keep posting and I'll re-open if necessary.

**Comment by kruettner** [comment]
Hi Thanks. It seems plausible what you are saying and it is also true that my pipeline is using only cellpose. However, I receive the error message when loading my pipeline and it would not be further loaded in cellprofiler. In other words I would not be able to use it. Do you have any suggestions how to circumvent this?

**Comment by gnodar01** [comment]
Ah, yes sorry. Didn't see the final error message on the first read through. Could you launch cellprofiler from the terminal, and include the flag `-L 10`. That will enable debug messages.

So: `python -m cellprofiler -L 10`.

Then paste the full log here.

**Comment by kruettner** [comment]
Hi Thanks. her is the full log: 
(cellprofiler) C:\Users\sebastian\Cellprofiler\CellProfiler-plugins>python -m cellprofiler -L 10
C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\__main__.py:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
JVM will be started with AWT in headless mode
Creating JVM object
Signalling caller
Enabled Bio-formats directory cacheing
Loaded backend qt5agg version unknown.
Loaded backend tkagg version unknown.
Loaded backend wxagg version unknown.
Loaded backend WXAgg version unknown.
Could not load runimagejscript
Traceback (most recent call last):
  File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\runimagejscript.py", line 15, in <module>
    import cpij.bridge as ijbridge, cpij.server as ijserver
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\cpij\bridge.py", line 3, in <module>
    import atexit, cpij.server as ijserver
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\cpij\server.py", line 15, in <module>
    import jpype, imagej, multiprocessing, socket, threading, time
ModuleNotFoundError: No module named 'imagej'
Could not load runomnipose
Traceback (most recent call last):
  File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\runomnipose.py", line 9, in <module>
    from cellpose_omni import models, io, core, plot
ModuleNotFoundError: No module named 'cellpose_omni'
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
could not load these modules: runimagejscript,runomnipose
HDF5Dict.__init__(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False, copy=None, mode=w
Creating converter from 5 to 3
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False
HDF5Dict.flush(): C:\Users\SEBAST~1\AppData\Local\Temp\Cpmeasurements25sxr680.hdf5, temporary=False

**Comment by gnodar01** [comment]
Hmm, it seems there may have been something that went wrong when you were pasting the content. Now even the error message from before is gone, and a bunch of text has strikethroughs in it.

Try this:

Copy the full log.

Before pasting, put three backtick symbols (the key on the upper-left-hand side of the keyboard, under the "esc" key): \`\`\`
Then press enter to create a newline
Then paste the content
Then press enter to create a newline
Then, put another three backtick symbols: \`\`\`

That will nicely format the contents of the log.

**Comment by kruettner** [comment]
Ok, here it is, hopefully in an improved style. Thanks for your efforts in helping to get this to work.
```
(cellprofiler) C:\Users\sebastian\Cellprofiler>cellprofiler
Could not load runimagejscript
Traceback (most recent call last):
  File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\runimagejscript.py", line 15, in <module>
    import cpij.bridge as ijbridge, cpij.server as ijserver
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\cpij\bridge.py", line 3, in <module>
    import atexit, cpij.server as ijserver
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\cpij\server.py", line 15, in <module>
    import jpype, imagej, multiprocessing, socket, threading, time
ModuleNotFoundError: No module named 'imagej'
Could not load runomnipose
Traceback (most recent call last):
  File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\utilities\core\modules\__init__.py", line 71, in add_module
    m = __import__(mod, globals(), locals(), ["__all__"], 0)
  File "C:\Users\sebastian\Cellprofiler\CellProfiler-plugins\active_plugins\runomnipose.py", line 9, in <module>
    from cellpose_omni import models, io, core, plot
ModuleNotFoundError: No module named 'cellpose_omni'
could not load these modules: runimagejscript,runomnipose
```

**Comment by gnodar01** [comment]
That is much better, but I don't see anything there that's unusual. Those are plugin import errors, which are typical and expected.

I am not seeing the error you originally reported. Specifically this one:

```
Traceback (most recent call last):
File "C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 1213, in OnData
self.window.on_filelist_data(
File "C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 879, in on_filelist_data
self.__frame.pipeline_controller.do_open_workspace(filename)
File "C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 914, in do_open_workspace
self.__workspace.load(filename, load_pipeline)
File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\workspace_workspace.py", line 373, in load
self.__file_list = HDF5FileList(self.measurements.hdf5_dict.hdf5_file)
File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\utilities\hdf5_dict.py", line 1045, in init
assert cellprofiler_core.utilities.legacy.equals(
AssertionError
```

I am assuming that message appears when loading your pipeline, which depending on its version may not be supported in CellProfiler 4. If you don't mind sharing the pipeline (you can email if you aren't comfortable sharing it publicly here) I may be able to help diagnose it further.

**Comment by kruettner** [comment]
Hi, thanks for your help throughout.
You are indeed correct, it seems to be the pipeline itself that is causing the issues. I now tested to load from scratch as a pipeline and not as a project as previously done. While now it would load successfully, many modules will still not be functional. The source of this seems to be that version 4.2.6 handles extraction from .czi files differently. All my sorting has been based on extracting the correct channels and Z planes. Also, there seem to be differences in how metadata is extracted in general, since my previous solution seems not to be working any longer. The version I used to build up the pipeline is 5.0.0b1.

I am attaching the pipeline for easier communication.

Best,
Sebastian


---------------------------------------------------------

Krüttner Sebastian, PhD
Y. Eva Tan fellow
Harvard Medical School, Department of Neurobiology
Goldenson Building, Room 405, 200 Longwood Avenue
Boston, MA 02115
+1 (857)-222-0532
***@***.***; ***@***.***

---------------------------------------------------------

On Apr 2, 2024, at 11:37 AM, Nodar Gogoberidze ***@***.***> wrote:



That is much better, but I don't see anything there that's unusual. Those are plugin import errors, which are typical and expected.

I am not seeing the error you originally reported. Specifically this one:

Traceback (most recent call last):
File "C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 1213, in OnData
self.window.on_filelist_data(
File "C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 879, in on_filelist_data
self.__frame.pipeline_controller.do_open_workspace(filename)
File "C:\Users\sebastian\Cellprofiler\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 914, in do_open_workspace
self.__workspace.load(filename, load_pipeline)
File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\workspace_workspace.py", line 373, in load
self.__file_list = HDF5FileList(self.measurements.hdf5_dict.hdf5_file)
File "C:\Users\sebastian\Cellprofiler\core\cellprofiler_core\utilities\hdf5_dict.py", line 1045, in init
assert cellprofiler_core.utilities.legacy.equals(
AssertionError


I am assuming that message appears when loading your pipeline, which depending on its version may not be supported in CellProfiler 4. If you don't mind sharing the pipeline (you can email if you aren't comfortable sharing it publicly here) I may be able to help diagnose it further.

**Comment by gnodar01** [comment]
Okay, thanks for the clarification. I think it would be beneficial to speak with an Image Analyst directly on how to reformat your pipeline. They'll be a lot more helpful than I would for that. You can sign up for an office hours slot here: http://broad.io/imagingofficehours.

Since the technical side seems to be resolved, I'll close the issue.
