### ISSUE TITLE
Immature ideas

### ISSUE THREAD

**Issue by ATAICwillbebest** [CellProfiler/CellProfiler#4933]
Dear Professor, Hello, I am very sorry for the intrusion, I am a neurosurgery student and have some immature thoughts I would like to share with you.

**Is your feature request related to a problem? Please describe.**
I am a Masters in Neurosurgery and a rookie in the computer field.To be honest, although CellProfiler is a great piece of software, it is still very difficult for me to use and I think it could make some improvements such as simplifying the process and focusing on a certain aspect, such as neuroscience research.Of course, that's just one rookie's stupid advice.

**Describe the solution you'd like**
I hope that improvements can be made specifically for research in the field of neuroscience.For example, combining processing with analytical processes, from cell segmentation to analysis of cells. What I would prefer is that the software allows researchers to train models using their own image data to achieve automated segmentation of ROIs and cellular phenotypes of interest to the researcher, and to perform cellular morphology analysis.Of course, I wish the above steps were simple and straightforward.

**Describe alternatives you've considered**
I'll use my field of study, microglia, as an example.The morphology of microglia is closely related to their function; for example, the morphology of microglia that promote and inhibit inflammatory function varies greatly.This makes the analysis of microglia morphology important. And, an automated, high-throughput microglia segmentation is more scientific than manual selection.So I would like to implement the following functionality.
1.The model is trained with its own image data to do the identification of microglia subtypes with different morphologies.
2.Image segmentation for new experimental results using the training model.
3.Segmented microglia subtypes were counted and statistical analysis.
4.The morphology of the cells is analysed, including parameters such as area, axons data, cytosol size, and so on.
5.Statistical graphing of the results.
6.Visual mapping of the distribution of different cell morphologies.
7.Mapping the structure of cellular forms.
8.Output of analysis results.

Forgive my abruptness!This is just a thought from an ignorant rookie,Forgive me if I've been a nuisance to you and your team!

**Comment by gnodar01** [comment]
Hello @ATAICwillbebest, thank you for your perspective. Users of CellProfiler vary wildly in both their computational and biological levels of comfort and education, and we try to cater to as much of that user-base as we can. In particular, we very much care about the ease-of-use and the capabilities of the software for people such as yourself.

The sort of workflow you lay out, where there is an interactive training portion (i.e. a trainable Machine Learning / Deep Learning component), is a bit out of scope for CellProfiler. While CellProfiler can run some deep learning models, such as Stardist or CellPose, they are pretrained models which are used only for inference. If, for instance, there was a microglia segmentation mode trained outside of CellProfiler, we could certainly provide resources for creating a plugin that will allow you to use this already-trained model as a module within a larger pipeline in CellProfiler.

However we do understand that both training a model, and building a new plugin, requires a degree of computational comfort that many of our users don't have (or they simply don't have the time!) For that reason, we are working on a no-code, easy to use tool, separate from CellProfiler, that is exactly meant to tackle the sorts of workflows you outline. It is called Piximi and is available at https://www.piximi.app/. The documentation / user guide is available at https://documentation.piximi.app/. 

Please do keep in mind that it is a work in progress, and not yet able to perform many of the tasks you lay out. For instance, we do not yet have a trainable segmenter. We are close to having an initial set of simple measurements / analysis tasks that you can conduct, but they will not included some more sophisticated measurements (such as visual mappings of the distribution of different cell morphologies, as you noted in your example). Building software takes time, and making it friendly for users takes even more time and effort. However our vision very much aligns with the requests you've outlined here.

I will close this issue, as its not directly related to work we're doing in this repository. However, do feel free to go to the piximi repository at https://github.com/piximi/piximi, and create an issue there for any feature requests or ideas for enhancement for that tool. 

Again, thanks for your thoughtful post. We really appreciate your feedback.
