### ISSUE TITLE
CellProfiler manual for `v4.2.8` unavailable from website

### ISSUE THREAD

**Issue by d33bs** [CellProfiler/CellProfiler#4945]
Thanks for the great work on this project! When attempting to access `v4.2.8` documentation from the manual available on https://cellprofiler.org/manuals I noticed that I get an access denied error:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

The link which creates this error is: https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.8/

**Comment by bethac07** [comment]
Sorry, that should have had index.html on the end -now fixed!

**Comment by d33bs** [comment]
Cheers, thanks @bethac07 for the super speedy fix!

**Comment by bethac07** [comment]
2 minutes or 8 months, no other response times available.
