### ISSUE TITLE
Unable to install CellProfiler from `pip` with Python 3.10 due to `scikit-learn` dependency constraints

### ISSUE THREAD

**Issue by d33bs** [CellProfiler/CellProfiler#4946]
**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04 
 - CellProfiler Version: 4.2.8
 - Downloaded from the website or installed from source? Installed from PyPI
 - If the latter, how (cloned, installed from pypi, etc)? PyPI
 - Python version: 3.10.12

**Describe the issue**

I noticed CellProfiler is unable to be installed from PyPI when using Python 3.10 on Ubuntu 22.04. The errors I saw were due to a dependency, `scikit-learn<1,>=0.20` (resolving to `scikit-learn==0.24.2`). I imagine but don't know whether this could hold true for other versions for the same reasons.

**Error messages**

When installing through `pip`, an error is raised when attempting to install `scikit-learn==0.24.2`:

```text
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

I attempted to use different versions of `setuptools` (`setuptools<60.0`, as suggested by deprecation notices from `pip`) and I found that the error persists.

**Screenshots**

Please see the following Google Colab notebook, which demonstrates the issue: https://colab.research.google.com/drive/1b4uEb-kj5YFdVY0DTeRYW17uWl-lrr7-

**Additional context**

Generally, I'd be interested in any background on the existing `scikit-learn` dependency constraints. `scikit-learn==0.24.2` was released Apr 28, 2021 ([link](https://pypi.org/project/scikit-learn/0.24.2/)), meaning there likely are many bug fixes and improvements which could be incorporated into CellProfiler with later revisions. While a workaround would be helpful for this issue, an update to the constraints might be more helpful to growing the project over time.

**Comment by gnodar01** [comment]
Hello, thanks for reporting this.

CellProfiler `4.2.8` is pinned to python `3.8` or `3.9` only. Although sometimes we may forget to update it, this can generally be see on the [pypi](https://pypi.org/project/CellProfiler/) page, on the left hand side, under "Programming Language".

![Screenshot 2024-09-25 at 2 40 13 PM](https://github.com/user-attachments/assets/5a30acbf-3a99-4085-a85f-48e362e61337)

Ideally, we should be able to support all python versions, but there are many api deprecations that have happened between python `3.10` and `3.12`, matrixed across the dependencies of CellProfiler which have been updated to work for those python versions. 

> meaning there likely are many bug fixes and improvements which could be incorporated into CellProfiler with later revisions

You are completely right. Over the long run, we do plan to address those api changes, however CellProfiler `4.2.x` is in minimal maintenance mode. Most of the development work is being concentrated on the not-yet-released CellProfiler `5`.

For CellProfiler 4.2.x, we ask users to stick to python 3.9.

**Comment by d33bs** [comment]
Thank you @gnodar01 ! Based on what you mentioned, could I suggest providing a Python version constraint within the `setup.py` so as to make version constraints declarative and visible to `pip`. I'd be happy to open a new issue and/or open a PR for this change, let me know what you think.

**Comment by gnodar01** [comment]
Sure, PR is welcome! Make sure to point it at the `4.2.x` [branch](https://github.com/CellProfiler/CellProfiler/tree/4.2.x). Thanks.
