### ISSUE TITLE
Unable to download CellProfiler

### ISSUE THREAD

**Issue by eshah14** [CellProfiler/CellProfiler#4950]
I have tried to download CellProfiler onto my Macbook Air (15.0.1) and keep having the following error. I've tried the two workarounds posted and am still unable to download.  
<img width="265" alt="Screenshot 2024-10-04 at 12 38 24 PM" src="https://github.com/user-attachments/assets/79d59394-4196-4e93-9ada-636b94ec0458">

**Comment by gnodar01** [comment]
Can you try (or confirm you have already tried) all of the options listed here (except for disabling Gatekeeper; do not do that): https://nordvpn.com/blog/macos-cannot-verify-this-app-is-free-from-malware/

**Comment by eshah14** [comment]
Yes, I have also tried those 2 options

**Comment by gnodar01** [comment]
There are 3 options. Can you confirm you tried `xattr -d com.apple.quarantine CellProfiler.app`?

**Comment by sbpkyle** [comment]
Hi, if you control (^) + right-click twice and then open it, it should allow you to open it!
