### ISSUE TITLE
LSF run: Maven failed to update Java dependencies

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#501]
Cluster run produces following error (among others, see attached output text file)

<blockquote>
[ERROR] Failed to execute goal on project cellprofiler-dependencies: Could not resolve dependencies for project org.cellprofiler:cellprofiler-dependencies:pom:1.0: Failed to collect dependencies for [loci:bio-formats:jar:4.4.6 (runtime), loci:ome_tools:jar:4.4.6 (runtime), net.imagej:ij-app:jar:2.0.0-beta5 (runtime), org.mozilla:rhino:jar:1.7R4 (runtime)]: Failed to read artifact descriptor for loci:bio-formats:jar:4.4.6: Could not transfer artifact loci:bio-formats:pom:4.4.6 from/to imagej.releases (http://maven.imagej.net/content/repositories/releases): Specified destination directory cannot be created: /home/unix/imageweb/.m2/repository/loci/bio-formats/4.4.6 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2013_03_04_14_01_57_FileUI/external_dependencies.py", line 111, in fetch_external_dependencies
    run_maven(imagej_dir, maven_install_path, quiet = not overwrite)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2013_03_04_14_01_57_FileUI/external_dependencies.py", line 178, in run_maven
    subprocess.check_call(args)
  File "/broad/software/free/Linux/redhat_5_x86_64/pkgs/toolbox/0.11.0/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/imaging/analysis/CPClusterSingle/CellProfiler-2.0/2013_03_04_14_01_57_FileUI/imagej/maven/apache-maven-3.0.4/bin/mvn', '-U', '-q', 'package']' returned non-zero exit status 1
Maven failed to update Java dependencies.
Run external_dependencies with the -o switch to get full output.
</blockquote> 

Attachments:
http://cellprofiler.org/issues/uploaded/QN8fPu/ViewTextFile.txt

**Comment by bekagaw653** [comment]
https://icetutor.com/question/maven-dependencies-are-failing-with-a-501-error/
