### ISSUE TITLE
Implement basic 3D segmentation, analysis

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#524]
Augment CellProfiler’s segmentation and some measurement modules (counting, size, intensity) to handle 3D across multiple channels. Also re-implement or access algorithms in ITK (on which BioImageXD is based).

**Comment by AnneCarpenter** [comment]
Notes from Lee (2015):
*** For projections and illumination correction
*** Laying the  groundwork for 3D image analysis
*** Modify NamesAndTypes to harvest 3-d (N-D?) images, probably by picking a metadata category as an axis
*** Add 3-D median filter code from median_filter branch
*** Add 3-D segmentation
*** Parallel watershed algorithm (not necessarily parallel, but to localize references): Parallel watershed transformation algorithms for image segmentation, A. N. Moga, B. Cramariuc, M. Gabbouj

**Comment by 0x00B1** [comment]
@AnneCarpenter We should break this into multiple issues.

**Comment by 0x00b1** [comment]
LOL
