### ISSUE TITLE
Support for super-resolution fluorescence microscopy

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#525]
Interface CP with Andrew York's MSIM hardware+software: https://code.google.com/p/msim/
Paper: http://www.nature.com/nmeth/journal/v9/n7/full/nmeth.2025.html

**Comment by AnneCarpenter** [comment]
Note a CellProfiler fan has published work in this area:
http://www.biologicalproceduresonline.com/content/17/1/11
