### ISSUE TITLE
JIRA [IMG-1536] measuregranularity - settings descriptions and interactions improvements

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#55]
The settings for measuregranularity should be improved.  I suggest:<br/>Texture scale<br/>Background removal radius<br/>Subsampling factor (how much to scale down the image for speed)<br/><br/>&nbsp;The first two should be in the unscaled pixel units.  The code should automatically translate them to the relevant sizes after subsampling.  Warnings can be generated if the subsampling causes them to become&lt;1.  Possibly, there should be an output&quot;setting&quot; that shows the scaled values that will be used (since they must be integers).

Original reporter: thouis
Jira link: https://jira.broadinstitute.org/browse/IMG-1536
Fix version: Current
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
