### ISSUE TITLE
Search help function needs to be more forgiving for searches with spaces

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#560]
I tried to search for "Groups module" and it failed to find anything. It would be nice if the search function could coalesce whitespace when constructing the searchable text so that searches with spaces could match words that appeared to be separated by a single space, even if, in reality, the HTML between the words had multiple whitespace characters.

**Comment by dlogan** [comment]
Searching "Groups" now finds many references, including the module itself.
