### ISSUE TITLE
MeasureObjectSizeShape: Perimeter calculation underestimation?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#583]
From a group @ Emory: "We are looking at retinal pigment epithelium (RPE) cells in human eyes and trying to characterize their shape.  These cells are ideally supposed to be shaped as a perfect hexagon. In a large sample of hundreds of cells that appear to be fairly hexagonal, we have observed an average form factor measurement of about 0.76. We are wondering why this value is so low.

The attached figure shows that a perfect hexagon should have FF=0.91.![form factor](https://f.cloud.github.com/assets/1186440/421798/5869451e-ad12-11e2-87f1-f3072ae52cce.png)

The problem: Even when we input a "test image" of a perfect hexagon....we cannot replicate that a hexagon has a FF of 0.91!  We get a value ~0.84."

I've confirmed this behavior. My best guess is that that the while the area is simply the sum of the number of foreground pixels, the perimeter is a the sum of the distances between the centers of the edge pixels, leading to an overestimation of the actual side length. This difference, when squared and then used for ratio in the form factor, leads to a large apparent discrepancy.

I'm not sure if this actually a bug, or something that needs clarification in the documentation. 

I've attached a sample hexagon for testing. 
![hexagon](https://f.cloud.github.com/assets/1186440/422194/dd2e96bc-ad1e-11e2-8e9f-3026181874ef.png)

**Comment by AnneCarpenter** [comment]
Sounds like there is some debate about the right way to do this, so closing for now for future consideration.
