### ISSUE TITLE
JIRA [IMG-1520] Use curvelets to measure add'l features

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#62]
Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1520
Fix version: future
Assignee: leek

**Comment from mbray on Thu, 8 Sep 2011 09:43:18 -0400:**
On Thu, Sep 8, 2011 at 8:18 AM, Mark Bray&lt;<a href='mailto:mbray@broadinstitute.org'>mbray@broadinstitute.org</a>&gt;  wrote:<br/>&gt;  Re: curvelets - When I was at LOCI, Kevin introduced me to a student who<br/>&gt;  worked on using curvelets for extracting features from collagen fibers<br/>&gt;  (<a href="http://www.loci.wisc.edu/software/curvelet-based-alignment-analysis">http://www.loci.wisc.edu/software/curvelet-based-alignment-analysis</a>). I<br/>&gt;  was impressed by the results, however, her program is MATLAB-based.<br/>&gt;  After talking to Vebjorn briefly about it, I found a licensed Python<br/>&gt;  implementation:<a href="https://slimweb.eos.ubc.ca/~hegilles/software.html,">https://slimweb.eos.ubc.ca/~hegilles/software.html,</a>but<br/>&gt;  never followed up on it.<br/>&gt;       -Mark<br/>&gt;<br/>&gt;  On 9/7/2011 5:41 PM, Anne Carpenter wrote:<br/>&gt;&gt;  Zhang, B.&amp;    Pham, T. Phenotype Recognition with Combined Features and<br/>&gt;&gt;  Random Subspace Classifier Ensemble. BMC Bioinformatics 12, 128<br/>&gt;&gt;  (2011).<a href="http://www.ncbi.nlm.nih.gov/pubmed/21529372">http://www.ncbi.nlm.nih.gov/pubmed/21529372</a><br/>&gt;&gt;<br/>&gt;&gt;  ----&gt;    Uses Ilya Goldberg lab&#39;s WND CHARM benchmark sets to test a<br/>&gt;&gt;  method that similarly avoids segmentation and instead uses curvelets<br/>&gt;&gt;  in combination with Haralick texture features for phenotype<br/>&gt;&gt;  classification, which is done using the random subspace (RS) ensemble<br/>&gt;&gt;  method. Seems to work better than original features used by WND-CHARM.<br/>&gt;&gt;  Might be interesting for those interested in curvelets.

**Comment by dlogan** [comment]
Closing now, for future consideration.
