### ISSUE TITLE
Add support for ImageJ 2.0 "button" parameter

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#646]
ImageJ 2.0 has added imagej.widget.Button which, if added to a plugin as a parameter, ties a UI button widget to a function to be run. Interactive modules like "Threshold" do all their work using the functions tied to the buttons; for instance, "Threshold" has an auto-threshold button that calculates an automatic threshold.

**Comment by LeeKamentsky** [comment]
For these interactive modules, CP should figure out how to invoke the function for the automatic / non-interactive mode.

**Comment by 0x00B1** [comment]
ImageJ support has been dropped.
