### ISSUE TITLE
JIRA [IMG-1382] Manual interface for incorrectly tracked objects, for TrackObjects

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#649]
For the CP SW grant, we propose to create an interface for manual adjustment of incorrectly tracked objects. Rupinder's project formed the first steps for this.

**Comment by braymp** [comment]
Consider integrating Traxtile for this purpose: https://github.com/braunb/traxtile-public

**Comment by braunb** [comment]
I'd certainly be willing to help work with and/or refactor Traxtile. Though I will point out early and loudly, this was my first substantial Python project and you may want to be prepared to cringe if you peek at the source. But I am very open to advice and willing to put the time in.

Also, I have now fixed a naming typo that was preventing all the modules from loading.
