### ISSUE TITLE
JIRA [IMG-1508] Calculate the KS statistic for every image set

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#65]
Text below is copied from here:<br/><a href="http://dev.broadinstitute.org/imaging/privatewiki/index.php/Image-based_systems_biology#Identifying_a_single_feature_to_score_the_phenotype">http://dev.broadinstitute.org/imaging/privatewiki/index.php/Image-based_systems_biology#Identifying_a_single_feature_to_score_the_phenotype</a><br/><br/>&quot;Which feature distinguishes this set of points (e.g., a well, a hairpin, a phenotype) from the controls?&quot;<br/><br/>Anne 1-17-06: We should make a new module to calculate the KS statistic for every image set. It would require notifying the software which images are controls (they can load this information using LoadText, as is done for the CalculateStatistics module), because this statistic compares the distribution of individual cell measures from each image to the distribution of individual cell measures from the control image(s). Once finished, we should see whether the calculated KS statistic produces a better Z&#39; score than the&#39;percent above threshold&#39; method for the BioImage cyto-nuc translocation assay. References: Chakravart LaR: Handbook of methods of applied statistics. Vol 1New york: John wiley, 1967:392-394; also Giuliano, Chen, Taylor, J Biomol Screening 2004; 9:557-568. See also Wilson, Si, Thompson, Smellie, Ashwell et al, J Biomol Screen 2005 or 2006&quot;Identification of a small molecule that induces mitotic arrest using s simplified high-content screening assay and data analysis method.&quot; because this has an example where KS statistics are calculated between several control images and this value is subtracted from the KS values for each image. Also, Smellie J Chem Inf Model 2005 or 2006. Ray 2007-6-21: Might also look at Kuiper statistic. -- build into CalcStats? --Dlogan 14:53, 12 February 2008 (EST). Or is it easier to just do unsupervised machine learning and pick the top-ranked feature? How do the options differ and why might one be useful vs the other?

Original reporter: dlogan
Jira link: https://jira.broadinstitute.org/browse/IMG-1508
Fix version: next
Assignee: dlogan

**Comment by AnneCarpenter** [comment]
This part is never gonna happen, and probably ought not.
