### ISSUE TITLE
Have a first-class way to load a load data CSV in the file UI

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#676]
Add either tabs on the top of the file list or add a drop-down choice to Images to choose between:

* Images / Metadata / NamesAndTypes and Groups as it stands

* Image File List - pick a .CSV to load the image set

* OMERO screen (eventually) - pick a screen to act as a file list.

**Comment by AnneCarpenter** [comment]
This would need to happen as part of a larger restructuring of the first-4 modules. Closing for now and marking for future consideration.
