### ISSUE TITLE
Assist detection of incorrect pipeline wiring

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#678]
Because CellProfiler uses the concept of linear modules in a pipeline, it can sometimes be difficult to mentally map inputs and outputs. We thought of a couple of approaches to address this:

(1) It may be possible to detect and warn instances of, for example, orphaned images - those that are produced by the pipeline but never used.  There are probably cases where this is appropriate, so we're not sure this is a great idea.

(2) Although we have agreed not to implement a visual programming interface for building CellProfiler pipelines (see issue #150), it may be useful to give visual-programming style feedback.  That is, upon click of a "map" button near the pipeline window, a window pops open showing a static view of the pipeline, with inputs and outputs drawn.  It need not be terribly pretty, but would give a general sense of, for example, whether any modules produce images that are not used downstream (orphaned).

**Comment by braymp** [comment]
Decided not to do once and for all.

**Comment by dlogan** [comment]
From our CP Roadmap, this comment:
```
Problem: Current pipeline view renders module inputs and outputs somewhat obscure for new users

Plan: Create a visual programming view. Biologists love visual programming software like Pipeline Pilot and KNIME; this format eases understanding of what inputs and outputs are required.
We have decided NOT to solve this problem. Dependency graphs show that this approach becomes hairy even for simple pipelines.
Create a new visual programming view, where modules are nodes that can be connected based on inputs and outputs.
Allow toggling between traditional pipeline view and new visual programming view.
```

So we think this to not be very important and are closing
