### ISSUE TITLE
CalculateMath: UnboundLocalError

### ISSUE THREAD

**Issue by BioTurboNick** [CellProfiler/CellProfiler#695]
This applies to 2_0_bugfix, but likely also affects the master branch.

I'm getting the following error on some images I run through:

```
Traceback (most recent call last):
  File "F:\CellProfiler\cellprofiler\pipeline.py", line 329, in run
    self.module.run(self.workspace)
  File "F:\CellProfiler\cellprofiler\modules\calculatemath.py", line 350, in run
    c0 = bincount(i0, minlength=len(values[0]))
UnboundLocalError: local variable 'i0' referenced before assignment
```

(example files available: https://skydrive.live.com/?cid=ED32C1B491DE6BB3&id=ED32C1B491DE6BB3!24778)

The pipeline leading up to this was, in summary:
1. LoadImages (Objects: Cells)
2. LoadImages (Images: NLS-tdTomato)
3. Smooth NLS-tdTomato
4. MaskImage (smoothed NLS-tdTomato by Cells)
5. IdentifyPrimaryObjects
6. RelateObjects (Nuclei --> Cells)
7. ReassignObjectNumbers (Relabeled Nuclei --> by parent Cells)
8. MeasureObjectSizeShape (Nuclei, Cells)
9. CalculateMath (Nuclei Area / Cells Area)

Two of the cell objects of the image in question do not contain nuclei objects, and this seems to be the source of the problem.

There is a work-around, which is to do an initial FilterObjects step to remove cells which do not contain any objects. But it seems like that should be unnecessary, given that ReassignObjectNumbers should have resulted in the two object sets involved in the math having matching labels.

Alternatively, skipping ReassignObjectNumbers and just doing the math based on the related objects does work, as far as not generating an error, but it would average any child objects. For this particular example, that isn't a huge problem because there's almost always just one nuclei per cell. But I'm also working with mitochondria objects, where this would be a problem.

Alternatively, inserting another RelateObjects after ReassignObjectNumbers (Relabeled Nuclei --> Cells) allows it to work as well. EDIT: Nevermind on this point, this arrangement (in my full pipeline, which does some other filtering, but not in the test pipeline) gives me this error:

```
Traceback (most recent call last):
  File "F:\CellProfiler\cellprofiler\pipeline.py", line 1306, in run_with_yield
    module.run(workspace)
  File "F:\CellProfiler\cellprofiler\modules\calculatemath.py", line 352, in run
    v1 = bincount(i0, values[1][i1], minlength=len(values[0])) / c0
IndexError: index 35 is out of bounds for size 35
```

---

This feeds somewhat into issue #666, but I'm hoping that there might be a way to address this specific error in the meantime.

**Comment by AnneCarpenter** [comment]
@mcquin Note this corner case mentioned in the last comment; might be relevant to your WIP module.
