### ISSUE TITLE
JIRA [IMG-1460] Properly handle grouping when using ExportToDatabase as a data tool

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#70]
hello,<br/><br/>i am having some issues with the ExportToDatabase menu item.<br/><br/>basically i think it would be good if it had a few more choices such as:<br/><br/>- select tile_size<br/>- select well_format<br/>- for my applications i need the Metadata also in the per-object table,<br/>because i want to compute summary statistics based on<br/>&quot;Metadata_treatment&quot; per object (not per image)<br/>&nbsp;&nbsp;(this is already possible in the ExportToSpreadSheet)<br/>- and, currently, i get an error message when i click that i would like<br/>to have groupings<br/><br/>currently my work-around-flow is:<br/><br/>i) Analyse our data on the cluster in CP =&gt; ExportToSpreadsheet<br/>ii) Merge the .csv files in R<br/>iii) generate the db.properties, Setup.SQL, per_image.csv, and<br/>per-object.csv in R<br/>iv) import into CPA<br/><br/>advantage is that like this i can do in R what i want in order to get<br/>&quot;nice&quot; input for CPA<br/><br/>however, i realized that what i actually do in R is very minor so one<br/>could compress the workflow substantially by giving the ExportToDatabase<br/>module a bit more power...<br/><br/>what do you think?<br/><br/>Tischi<br/>

Original reporter: leek
Jira link: https://jira.broadinstitute.org/browse/IMG-1460
Fix version: current
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
