### ISSUE TITLE
JIRA [IMG-1448] Add per-well export to ExportToSpreadsheet

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#71]
From this post: http://cellprofiler.org/forum/viewtopic.php?f=2&t=652&p=5301#p5273

ExportToDatabase has this option, but ExportToSpreadsheet does not.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1448
Fix version: future
Assignee: leek

**Comment by dlogan** [comment]
Note that this Forum user requested this too, and is potentially working on coding a solution themselves:
http://www.cellprofiler.org/forum/viewtopic.php?f=17&t=4207
