### ISSUE TITLE
JIRA [IMG-1437] Research microscopy methodologies and decide what corresponding features to add

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#73]
New types of microscopy approaches (FPALM, structured illumination) require some sort of image processing/deconvolution to generate the final image from the raw image(s) collected.  We should survey the field to find out which types of microscopy we would want to support, and see if researchers have algorithms they are interested in contributing to the project.<br/><br/>A good starting point:<a href="http://f1000scientist.com/article/display/57784/">http://f1000scientist.com/article/display/57784/</a><br/><br/>FPALM/PALM/STORM:  Anne is contacting Sam Hess (U Maine) to see whether he has algorithms he would like to contribute.<br/>STED: Does not require algorithms to process - the raw image IS the final image.<br/>SIM: A likely candidate where algorithms are needed, though the article does not provide any contact people.<br/><br/>

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1437
Assignee: anne

**Comment by dlogan** [comment]
Closing now, for future consideration.
