### ISSUE TITLE
Upgrade Ilastik to 0.5.12

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#738]
Christian.Tischer@embl.de would like us to upgrade Ilastik to 0.5.12 which should be compatible with 0.5.06 classifier files. Try this out on a VM and upgrade for real on build machines if it appears to work correctly.

**Comment by braymp** [comment]
@LeeKamentsky is currently working on this.

**Comment by 0x00B1** [comment]
Ilastik has been dropped.

**Comment by jhung0** [comment]
This is huge!
