### ISSUE TITLE
JIRA [IMG-1429] Usability improvements re: loading and Identify modules

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#75]
Hi Mark,<br/><br/>Someday Lee and Adam will be able to turn towards CellProfiler improvements rather than ImageJ and bug fixing.  We outlined some items in the CP SW proposal itself and were talking about two (other) areas that are ripe for improvement:<br/><br/>1.  Make loading images easier for beginners<br/>----- Ray made a start at this with his new LoadImages module. No one is quite sure the status or how far this is from being perfect.<br/>----- Lee notes that Fiji (the ImageJ distribution that we are partnered with) has a BioFormats importer of some sort that does a good job of figuring out some metadata from images<br/>----- How much info can be extracted from the headers of images via BioFormats and fed to populate a new LoadImages wizard? (e.g., channel<br/>information)<br/>----- Any Jiras in this area already?  I presume Ray&#39;s LoadImages is sitting somewhere for starters.<br/><br/>2.  Make IdentifyPrimaryObjects easier for beginners<br/>----- How many of the settings could be determined automagically by asking the user to click (or outline, or squiggle) a few cells and background areas in an image?  Should there be a button at the top&#39;Help me configure my settings&#39; that will figure out optimal choices for certain settings?  Is it possible to use Ilastik more seamlessly in this context to mark foreground/background and/or choose a thresholding method, or at the least can we do things like set the min/max cell size by asking the user to click on a few of the smallest and largest isolated (single) cells for the min/max and perhaps max suppression nhood, and also ask them to click on a few clumps of cells, to help determine whether shape vs intensity is appropriate?<br/><br/>Lee&amp; Adam are too overwhelmed to think about any of this now, but that means it&#39;s the perfect time for you to do your signature&#39;needs assessment&#39;/&#39;plot out the future&#39;, as you did for QC when working with Adam.  I imagine you would want to think about all the potential ways to make CP easier for users, based on Forum questions and having worked side by side with people, then organize a list of potential changes/features, then run past IADs for feedback, then run past everyone for feedback, then convert the result into Jiras.<br/><br/>Does this sound good?  I guess it should be lower priority than CP<br/>Education stuff; then again probably you would want to work on them in<br/>parallel in order to not get bored.  Adam&amp; Lee will be tied up for<br/>2-3 months, really, so there&#39;s plenty of time. I guess ideally it&#39;s<br/>better to have Adam work on anything that he is capable of doing, so<br/>long as it doesn&#39;t stress/mess up Lee, and since these items involve<br/>usability questions, Adam would be a good fit in that respect.<br/><br/>Anne

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1429
Fix version: next
Assignee: mbray

**Comment by dlogan** [comment]
Closing now, for future consideration.
