### ISSUE TITLE
JIRA [IMG-1404] Consider making CP available as a Python site-package

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#79]
See this post: a href="http://cellprofiler.org/forum/viewtopic.php?f=14&t=942. It seems that you are open to the idea, but it needs more thought. I&#39;m making a JIRA of this issue so it doesn&#39;t get lost.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1404
Fix version: future
Assignee: leek

**Comment by 0x00B1** [comment]
Resolved!
