### ISSUE TITLE
Load a simple pipeline URL on introduction page fails when using a proxy server

### ISSUE THREAD

**Issue by nickholway** [CellProfiler/CellProfiler#803]
We use a proxy server for our internet access which causes the "Load a simple pipeline" link on the "Welcome to CellProfiler" window to fail (see screenshot). I'm on OSX 10.8.4 and CP 2.1 rev 7a43182.

![image](https://f.cloud.github.com/assets/3875607/1148449/2036cb30-1ec3-11e3-9a38-8f0881b1f5f9.png)

**Comment by AnneCarpenter** [comment]
Likely, the solution here is to just expand the error message to say something like, "CellProfiler was unable to load (URL). If you are connected to the internet, this can happen because X Y Z."

**Comment by braymp** [comment]
Just got bitten by this during a workshop, and I believe this is also affecting loading pipelines and/or CSVs by URL. Might be a bit much to ask, but could a preference be added for a specifying a proxy URL to the Requests package?

**Comment by 0x00b1** [comment]
> Just got bitten by this during a workshop, and I believe this is also affecting loading pipelines and/or CSVs by URL. Might be a bit much to ask, but could a preference be added for a specifying a proxy URL to the Requests package?

Yeah. I think that’s a good idea.
