### ISSUE TITLE
JIRA [IMG-1377] ExportToDatabase: Add gates to props/workspace files

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#83]
In the properties file, the new gate structure is written as a list of dicts. This should be straightforward to add as an option in ExportToDB: (1) Name of gate, (2)  request measurement, (2) upper lower values.<br/><br/>I assume as many measurements can be specified as desired to be ANDed together, even though plotting tools are limited in # of dims?<br/><br/>In the workspace file, the gate field is specified with the gate name. Not sure if I can add gates to workspace options in ExportToDB.<br/><br/>Probably need to have user specify values for limits, since I don&#39;t think I can insert an post-run experiment measure, esp. if run on the cluster.

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1377
Fix version: current
Assignee: mbray

**Comment by dlogan** [comment]
Closing now, for future consideration.
