### ISSUE TITLE
Change default CP background color

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#840]
A UI review noted that there's no enough contrast between the blue selected text/red error text and the background color (currently dark sea green). Having CP use the system default color might be better.

**Comment by 0x00B1** [comment]
I think we should use the default color scheme everywhere since it inter-operates with system accessability preferences (e.g. high-contrast modes).

**Comment by LeeKamentsky** [comment]
:+1:  for default color scheme. We may need to pick among the wxSystemColour choices for some of the widgets: http://docs.wxwidgets.org/trunk/settings_8h.html#a44ad26cbd8d579d1b7eff7015c8bd24b

**Comment by AnneCarpenter** [comment]
Great point about accessibility. Ok, let's do it.
Good-bye, green CP. 
Good-bye, purple CP. 
<*sniff*>
