### ISSUE TITLE
JIRA [IMG-1365] Mimic worm flow cytometry in straightenworms

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#86]
We would like to produce measurements similar to flow cytometry for worms. You want to interpolate the intensity at regular intervals along a straight worm and output them in some reasonable format. Unfortunately, our current database schema doesn&#39;t really support that: you&#39;d like to output a series of measurements that indicate an intensity at a certain distance from the head of the worm. So either your columns account for every possible distance with many or most NaN for most worms or you wait until the database is properly normalized so that an appropriate number of measurements can be recorded for each worm. So we wait for now.

Original reporter: leek
Jira link: https://jira.broadinstitute.org/browse/IMG-1365
Fix version: next
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
