### ISSUE TITLE
ImageMath: "Invert" on masked image appears to invert the mask

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#865]
Take an image and apply an image or object mask. Then use ImageMath to invert the pixel intensities. The display in ImageMath appears as if the was ignored entirely. However, running IDPrim on the masked+inverted vs. the inverted image shows that the mask is there. So it seems that mask values are inverted for display only...?

**Comment by mcquin** [comment]
Closing in favor of https://github.com/CellProfiler/CellProfiler/issues/2545
