### ISSUE TITLE
Add functionality for object consolidation

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#876]
It would be nice to have a module which permits the combination of multiple object sets into one object set. For a disjoint collection of objects, this module wold simply be the relabeled union of them.

If the object sets spatially intersect, some decisions will need to be made. Perhaps an option to handle such regions by either (a) creating a new object from the intersection or union of the intersecting objects, or (b) perhaps removing the intersection.

There definitely needs to be "Add another object" buttons for this one.

Perhaps this could be included in ReassignObjectNumbers or MaskObjects?

**Comment by AnneCarpenter** [comment]
Work is in progress on this, name is TBD: https://github.com/CellProfiler/CellProfiler/pull/2151

**Comment by 0x00b1** [comment]
Supplanted by https://github.com/CellProfiler/CellProfiler/pull/2151
