### ISSUE TITLE
EditObjectsManually has an a non-standard window toolbar

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#919]
For example, the toolbar has a "Configure subplots" button (I mistook it for the Zoom button)

![screen shot 2013-11-22 at 4 28 35 pm](https://f.cloud.github.com/assets/1225595/1604488/69e0eb2c-53bf-11e3-9d0b-f9b273600a5b.png)

**Comment by AnneCarpenter** [comment]
This issue should be considered if/when we handle #399 which is marked for future consideration. So, closing this one as it's minor.
