### ISSUE TITLE
RunImageJ: Closing ImageJ in test mode closes CP

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#932]
If RunImageJ is present in a pipeline and the user enters test mode, ImageJ starts up. If the user then quits ImageJ, CP closes immediately, without any prompts to save the current project. 

I would think that gracefully exiting test mode would be the expected behavior?

**Comment by LeeKamentsky** [comment]
Fixed by https://github.com/CellProfiler/CellProfiler/pull/1581 - there is no UI to close now.
