### ISSUE TITLE
JIRA [IMG-1307] Consider gradient based intensity normalization

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#94]
Consider whether adding this method is useful/feasible (Carolina knows about the method, may have some code for it in matlab, and can ask about the intellectual property):<br/><br/><a href="http://www.ncbi.nlm.nih.gov/pubmed/21077885">http://www.ncbi.nlm.nih.gov/pubmed/21077885</a><br/><br/>J Microsc. 2010 Dec;240(3):249-58. doi: 10.1111/j.1365-2818.2010.03415.x.<br/>Gradient based intensity normalization.<br/><br/>Sintorn IM, Bischof L, Jackway P, Haggarty S, Buckley M.<br/>Centre for Image Analysis, Uppsala University and Swedish University of Agricultural Sciences, Uppsala, Sweden.<br/><br/>Abstract<br/>Intensity normalization is important in quantitative image analysis, especially when extracting features based on intensity. In automated microscopy, particularly in large cellular screening experiments, each image contains objects of similar type (e.g. cells) but the object density (number and size of the objects) may vary markedly from image to image. Standard intensity normalization methods, such as matching the grey-value histogram of an image to a target histogram from, i.e. a reference image, only work well if both object type and object density are similar in the images to be matched. This is typically not the case in cellular screening and many other types of images where object type varies little from image to image, but object density may vary dramatically. In this paper, we propose an improved form of intensity normalization which uses grey-value as well as gradient information. This method is very robust to differences in object density. We compare and contrast our method with standard histogram normalization across a range of image types, and show that the modified procedure performs much better when object density varies between images.<br/>&#xA9; 2010 CSIRO.<br/><br/>PMID: 21077885 [PubMed - indexed for MEDLINE

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1307
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
