### ISSUE TITLE
Include ClassifyPixels for Mac and/or Linux

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#941]
ilastik now provides Mac and Linux binaries (http://www.ilastik.org/index.php?cat=Download).  In theory then, we should be able to, no?  Next, or maybe Future?

Inquiring minds want to know (http://cellprofiler.org/forum/viewtopic.php?f=16&t=3579).

**Comment by braymp** [comment]
Decided on 1/21/2016 coding day that @LeeKamentsky, @0x00B1 will assess feasibility.
