### ISSUE TITLE
CellProfiler's ImageJ does not use the user's preferences

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#947]
I had to isolate CellProfiler's ImageJ from whatever might be on the user's machine in order to set some of the preferences and prevent the updater from running. Unfortunately, the solution was somewhat heavy-handed and CellProfiler's ImageJ preferences aren't persistent and aren't read from the standard places.

We need to be able to turn off the updater programatically in addition to through preferences.

**Comment by 0x00B1** [comment]
ImageJ has been dropped from CellProfiler.
