### ISSUE TITLE
Single threaded headless ImageJ

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#948]
In headless mode, we should replace the Scijava (= imageJ) DefaultThreadService with a single-thread thread service which calls Executors.newSingleThreadExecutor() to get its thread pool.

**Comment by 0x00B1** [comment]
ImageJ support has been dropped.

**Comment by ctrueden** [comment]
Is this up for discussion?

**Comment by 0x00B1** [comment]
Of course

**Comment by 0x00B1** [comment]
Here's the appropriate issue https://github.com/CellProfiler/CellProfiler/issues/1994 

I'll reopen the issue for discussion

**Comment by ctrueden** [comment]
Thanks!
