### ISSUE TITLE
Generalized URL cache

### ISSUE THREAD

**Issue by LeeKamentsky** [CellProfiler/CellProfiler#949]
CellProfiler needs a generalized mechanism for caching the data from a URL as a file. A caller should be able to fetch a URL and get back a path and there should be some way to manage the lifetime of the file data on disk as well as its freshness.

Modules:
NamesAndTypes
LoadImages
LoadData
LoadSingleImage
Metadata
ClassifyPixels
UntangleWorms
StraightenWorms

**Comment by AnneCarpenter** [comment]
Will consider for the future.
