### ISSUE TITLE
JIRA [IMG-1294] Investigate novel segmentation approaches

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#97]
For the long term... We might want to investigate making Scale-invariant feature transform (SIFT) algorithms available in CP:<br/><a href="http://en.wikipedia.org/wiki/Scale-invariant_feature_transform">http://en.wikipedia.org/wiki/Scale-invariant_feature_transform</a><br/><br/>And its updated cousin, Speeded Up Robust Features (SURF):<br/><a href="http://en.wikipedia.org/wiki/SURF">http://en.wikipedia.org/wiki/SURF</a>

Original reporter: anne
Jira link: https://jira.broadinstitute.org/browse/IMG-1294
Assignee: leek

**Comment from anne on Fri, 18 Feb 2011 16:42:07 -0500:**
Another potential method to discuss in the group is using local gradient convergence filters to find peaks in images, which is less dependent on image contrast.  Pedro Quelhas gave a talk on this approach recently and would be a good contact.

**Comment by dlogan** [comment]
Closing now, for future consideration.
