### ISSUE TITLE
JIRA [IMG-1278] Replace BatchProfiler with Firehose?

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#99]
Just a placeholder for Firehose implementation ideas.<br/><br/>Cancer Genome Analysis group New User wiki with some basics:<a href="http://iwww.broadinstitute.org/cancer/cga/wiki/index.php/New_User_Guide">http://iwww.broadinstitute.org/cancer/cga/wiki/index.php/New_User_Guide</a><br/>Firehose Users Guide:<a href="http://iwww.broadinstitute.org/cancer/cga/wiki/index.php/Firehose_Users_Guide">http://iwww.broadinstitute.org/cancer/cga/wiki/index.php/Firehose_Users_Guide</a>

Original reporter: dlogan
Jira link: https://jira.broadinstitute.org/browse/IMG-1278
Assignee: leek

**Comment by dlogan** [comment]
Closing now, for future consideration.
